### ISSUE TITLE
Possibility to send a poll to all recipients simultaneously at the same time

### ISSUE THREAD

**Issue by jtp680** [nextcloud/polls#1021]
Dear Polls Developers,

First of all, thank you for the great job you have done with the Polls Nextcloud app.

There are use cases with a requirement to send a poll simultenously to everyone concerned. It seems this feature request is already in the pipeline for the future version of Polls, but can you elaborate when it possibly could be available?

Best regards,
jtp680

**Comment by dartcafe** [comment]
Hey @jtp680 
I fear I don't get you. Can you explain by example?

**Comment by jtp680** [comment]
> Hey @jtp680
> I fear I don't get you. Can you explain by example?

Hello dartcafe,

After creating a poll, you normally add each recipient individually. One by one. Each time you add a new recipient, polling link is sent to him or her.

We have a scenario at work in which we have plenty of recipients for each poll. When we add recipients one by one, it may take several minutes between the first recipient and the last one receiving the link. However, all pollsters should receive the hyperlink at the same time, to make sure they are treated equally and have same time available for answering before the poll expires.

The question is, would it be possible to add all recipients first, and then send a polling hyperlink to all of recipients at once? Or would it be possible to use mailing lists?

**Comment by dartcafe** [comment]
With polls 1.5 all invitations are created, but not send. All pending invitations can then be sent with a single click on every invitation, which probably speed things up. A "send all pending invitations" function is missing at the moment. Not sure if it makes it to version 1.5. 

See screenshot in https://github.com/nextcloud/polls/issues/935#issuecomment-654066622

If all users are NC users, they could be put into one group as an alternative and then the group can be invited.

**Comment by jtp680** [comment]
Thank you @dartcafe! This was excellent news, looking forward to seeing it in coming release :-)
