### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by amittel** [nextcloud/polls#103]
Hi!
Installed it yesterday and I like the polls.
But the UI is missing the sidebar and therefore looks a little out of place in Nextcloud.
I looked at the [Documentation](https://docs.nextcloud.com/server/9/developer_manual/app/css.html#standard-layout) and found the basic structure.

**Comment by amittel** [comment]
I started a little bit in my [Branch](https://github.com/amittel/polls/tree/Update-UI)

![unbenannt](https://cloud.githubusercontent.com/assets/822396/20217490/71741810-a820-11e6-8fd4-66df0bf5717e.png)
![unbenannt1](https://cloud.githubusercontent.com/assets/822396/20217496/75eceb60-a820-11e6-8c26-c6e361d50e7c.png)

**Comment by v1r0x** [comment]
Thanks, looks very good!
You could create a PR and we could discuss further options there :)

**Comment by dartcafe** [comment]
I made a variant of the UI of @amittel with a rearrangement of the Items and adding some default classes from NC.
![grafik](https://user-images.githubusercontent.com/26707476/28723422-fec169e0-73b6-11e7-952c-1a671a85e7c4.png)

**Comment by dartcafe** [comment]
@amittel Are you still working on it? I tried to install your version, but it ends in an server error with NC12.

**Comment by v1r0x** [comment]
Going to close this in favor of the new UI in #148 
Thanks at both of you @amittel and @dartcafe !
