### ISSUE TITLE
Public polls: ugly greenish unidentified square displayed on mobile browsers

### ISSUE THREAD

**Issue by agentlibre** [nextcloud/polls#1049]
### What is going wrong?
**Describe the bug**

- A date poll is created.
- The public link is shared.
- Someone opens it from a smartphone using an usual browser.
- :beetle: An ugly greenish square is displayed between the title and the description; I can't identify what it is and why it is there.

Smartphones tested: Xperia Z3; Iphone 6
Mobile browser tested: Firefox; Chrome; Ecosia; Safari

**Expected behavior**
I would like a clean and sober display, with no greenish square. Otherwise, it looks quite unprofessional (I'm trying to promote NextCloud to the persons invited...).

**Screenshots**

![green_problem](https://user-images.githubusercontent.com/60295112/90234123-71092a80-de1f-11ea-9b21-7d255b164d11.jpeg)

For the sake of demonstration, please try it out directly: https://hub.idealex.org/index.php/apps/polls/s/aTpyqoT4CJQ5aGzo

### Information about your installation

- Polls version 1.4.3 installed per Appstore
- Nextcloud version 19.0.0, then 19.0.1

**List of activated apps:**
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - announcementcenter: 3.8.1
 - appointments: 1.6.8
 - breezedark: 19.0.4
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.5
 - emlviewer: 0.0.15
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_markdown: 2.3.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - forms: 2.0.2
 - issuetemplate: 0.6.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - mail: 1.4.1
 - metadata: 0.12.0
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - richdocuments: 3.7.3
 - richdocumentscode: 4.2.602
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.3
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0

### Server configuration
**Operating system**:
Linux 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1+deb9u1~deb8u1 (2020-06-09) x86_64

**Web server:**
Apache (fpm-fcgi)

**Database:**
mysql 5.7.30

**PHP version**
7.3.21

**Signing status:**
Array
(
)

Thank you in advance for your help and support! :pray:

**Comment by dartcafe** [comment]
Hmmm. I get this: 
![grafik](https://user-images.githubusercontent.com/26707476/90278709-252ea380-de68-11ea-9085-248a7f040461.png)

Which Phone/browser is used. It seems, that the text color is somehow calculated wrong, when using dark mode here. Seems, that the text is there but in a light grey color.

**Comment by dartcafe** [comment]
As the design got changed here, the green background is gone and should be no problem anymore. I will close this.
