### ISSUE TITLE
Poll | Invitation: The bin is missing if the contact name with email address is too long

### ISSUE THREAD

**Issue by Thomas1NC** [nextcloud/polls#1054]
Hello,
I find the following bug.
If you send an invitation (share a poll) with a contact whose name (together with the email address) is very long (too long), the bin (that normally is shown at the right side) is not visible. You will then not be able to delete any more the by mistake chosen contact.
Regards, Thomas

**Comment by dartcafe** [comment]
Fixed in upcomming Version 1.5
