### ISSUE TITLE
users struggle to enter user name on Android (public poll)

### ISSUE THREAD

**Issue by FelixSchwarz** [nextcloud/polls#1065]
### What is going wrong?
I noticed that users struggle to enter their name for public polls on Android.

**Describe the bug**

- "Ok" button not enabled even though the user entered a valid user name
- Error message (e.g. "username already in use") not highlighted

**To Reproduce**
1. create a public/anonymous poll
2. share link by email
3. user (without NextCloud account) opens link in mobile browser (Chrome and Firefox are affected)
4. user enters his name
5. (if name is invalid, the error message is very hard  to spot due to missing formatting)
6. **OK** button not enabled, no obvious feedback why
7. The button will be enabled after "clicking" somewhere outside of the text field (but not the "ok" button).

**Expected behavior**
- OK button should be enabled as soon as the user enters a valid username.

### Information about your polls installation
**Polls version?**  1.4.3

**Fresh installation or update from a prior version (from which one)?** I believe this is a fresh install which came with NextCloud 19.0.1.

**How did you install this version?** appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?** NextCloud 

**Nextcloud/ownCloud version:** 19.0.2

**List of activated apps:**
  - accessibility: 1.5.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.2.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.5
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - polls: 1.4.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - systemtags: 1.9.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

    "system": {
        …
        "skeletondirectory": "",
        "trusted_domains": [
            …
        ],
        "dbtype": "pgsql",
        "default_language": "de",
        "default_locale": "de",
        "version": "19.0.2.2",
        …
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }

### Server configuration
**Operating system**: Fedora 32
**Web server:** nginx
**Database:** postgresql
**PHP version:** 7.4.9
**Signing status:** "No errors have been found."
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Device:** various Android devices, e.g. Xiaomi Mi A2 Lite with Android 10
**Browser:** Chrome 84.0.4147.125, Firefox 68.11.0

### Logs
I don't think these are relevant

#### Browser log
Unable to get log of mobile browser

**Comment by dartcafe** [comment]
The dialog was not optimized for mobile use and obviously somehow misleading. See the new dialogs in #1096 

Will come with 1.5 release.

**Comment by tobyps** [comment]
The mobile view still seems to be a bit buggy.

When I enter my username the pop up is minimised by the keyboard but I have no way to scroll down to the email option.

You have to close the keyboard to select the mail textbox to enter the adress or to use the buttons. 
Using return on the keyboard just starts the check of the username but it doesn't set the new focus on the next field if the username is ok.

Scrolling just moves the page in the background not the popup.

Polls version: 1.5.4
OS: Android
Browser Firefox (current version) and Chrome

![2020-10-06 08 59 32](https://user-images.githubusercontent.com/52735599/95217464-7e291100-07f3-11eb-9af4-5253f3c92e57.png)

**Comment by dartcafe** [comment]
@skjnldsv The modal-container of the Modal@nextcloud-vue could need `overflow:scroll`. What do you think?
https://github.com/nextcloud/nextcloud-vue/blob/be5b271904047ed67b73baa73e15dec8377bc2bf/src/components/Modal/Modal.vue#L675-L680

**Comment by skjnldsv** [comment]
> @skjnldsv The modal-container of the Modal@nextcloud-vue could need `overflow:scroll`. What do you think?
> [nextcloud/nextcloud-vue@`be5b271`/src/components/Modal/Modal.vue#L675-L680](https://github.com/nextcloud/nextcloud-vue/blob/be5b271904047ed67b73baa73e15dec8377bc2bf/src/components/Modal/Modal.vue#L675-L680)

this was raised recently by someone, can't remember!
Yep, we could definitely have this by default to auto :)
