### ISSUE TITLE
Indicate timezone in display

### ISSUE THREAD

**Issue by emacsen** [nextcloud/polls#1076]
The timezone of a date poll changes with the user automatically, which can be a good thing, but has actually confused several users over several different polls where it wasn't clear to them which timezone was displayed- mine or theirs.

This would be remedied by adding a time zone indicator on the display. Something such as "Times are shown in EST (-5:00 UTC), or by offering to change the timezone display, ie "Show times in ___".

This would reduce any confusion from those answering.

**Comment by dartcafe** [comment]
Glad you mentioned this. We just added this to the upcomming version: 
![grafik](https://user-images.githubusercontent.com/26707476/92140078-f07f8d80-ee10-11ea-8023-e47b357a894b.png)
