### ISSUE TITLE
Allow newline in poll description

### ISSUE THREAD

**Issue by sirtoobii** [nextcloud/polls#1089]
It would be nice if we would be able to give the description a bit of a structure using newlines.

There are two related issues #500 and #501, however, they are both closed and as far I can tell, there isn't any activity related to this.

**Comment by dartcafe** [comment]
No problem with polls 1.4.3 and NC19 (besides the ugly leading space in the first line.
![grafik](https://user-images.githubusercontent.com/26707476/92409149-e4147100-f13f-11ea-90e7-793061c0c452.png)

**Comment by sirtoobii** [comment]
Can confirm, works in Chrome but not Firefox ESR (68.11.0esr, Linux)

Firefox:
![image](https://user-images.githubusercontent.com/1969330/92410140-b248dd80-f132-11ea-98f9-300f99b0a1f8.png)

Chrome:
![image](https://user-images.githubusercontent.com/1969330/92410163-c5f44400-f132-11ea-83c7-0368eb88190d.png)

**Comment by dartcafe** [comment]
The current firefox works well and I believe the latest esr (78.x) too.

**Comment by sirtoobii** [comment]
I think I found the root cause: 
The affected textbox is formatted using the `white-space:break-spaces;` CSS-Property which is fairly new and is not even supported on all [browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) (In the case of Firefox its > 69)

I suggest considering an alternative keyword (e.g `pre-wrap`) which is supported on all plattforms

**Comment by dartcafe** [comment]
scheduled for 1.5
