### ISSUE TITLE
[public poll, mobile] Participant "bubbles" overflow screen

### ISSUE THREAD

**Issue by sirtoobii** [nextcloud/polls#1090]
### What is going wrong?
When more than 10(?) persons fill out a public poll, the participant "bubbles" overflow the screen and make the whole page scroll-able to the right.

**To Reproduce**
1. Create a public poll
2. Let more than 10 people fill out the poll
3. Scroll down to bottom page

**Expected behavior**
Newline at screen border

**Screenshots**
![image](https://user-images.githubusercontent.com/1969330/92364824-29568580-f0e3-11ea-98c7-2c39b1f4c542.png)

### Information about your polls installation
1.4.3, updated multiple times, installed from Appstore

### Information about your Instance of Nextcloud/ownCloud
Nextcloud, version 19.0.2

**Comment by dartcafe** [comment]
Fixed in version 1.5
