### ISSUE TITLE
[public poll] Burger menu visible and clickable

### ISSUE THREAD

**Issue by sirtoobii** [nextcloud/polls#1091]
### What is going wrong?
When accessing a public poll through the link, the burger menu on the top left is still visible and clickable although is completely empty. Clicking on this menu results in an empty menu displayed and on mobile, it has the annoying side-effect that is makes the page left-scrollable.

**To Reproduce**
1. Access a poll through the public link
2. Click the burger menu on the top left

**Expected behavior**
The menu is not visible on poll accessed through the public link.

**Screenshots**
Desktop:
![image](https://user-images.githubusercontent.com/1969330/92367497-ff529280-f0e5-11ea-9d82-ffba017bc698.png)
Menu clicked:
![image](https://user-images.githubusercontent.com/1969330/92367575-1beeca80-f0e6-11ea-8d11-fcd3e3c9bd57.png)
Mobile:
![image](https://user-images.githubusercontent.com/1969330/92367816-71c37280-f0e6-11ea-943b-cc39562a5d04.png)

### Information about your polls installation
1.4.3, updated multiple times, installed from Appstore

### Information about your Instance of Nextcloud/ownCloud
Nextcloud, version 19.0.2

**Comment by dartcafe** [comment]
This will be fixed in version 1.5 which uses the updated nexctcloud-vue components.
