### ISSUE TITLE
Participating with public link not working for non NC users

### ISSUE THREAD

**Issue by nextcloudfan** [nextcloud/polls#1092]
I installed the Polls App. Created a poll and shared it with the public link.
But external users can not participate, because the need a valid nextcloud user name
This does not make sense at all. 

How can this be fixed or is this a bug?

### Information about your polls installation
**Polls version?** Latest

**Fresh installation or update from a prior version (from which one)?**
fresh

**How did you install this version?(Appstore or describe installation)**
Nextcloud GUI => Apps

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
19.0.0.12

**Comment by dartcafe** [comment]
I don't get it. You can enter every username. It must be at least 3 characters long and may **not** be an existing username.

**Comment by nextcloudfan** [comment]
And that is exactly what makes no sense. The box mentioned "insert your username" below that there is a link to register. People might think they must be a nextcloud user to participate.
So I would suggest to change/ adapt this text in the box.

Being a market researcher for 15+ yearsI know what I`m talking about:)

**Comment by dartcafe** [comment]
I still do not get, what you are referring to. What Link to register? 
Do we  both talk  about this dialog? 
![grafik](https://user-images.githubusercontent.com/26707476/92558883-c7775680-f26f-11ea-95bf-1f724753ef8f.png)

**Comment by nextcloudfan** [comment]
Yes this is misleading.

**Comment by dartcafe** [comment]
So it is helpful to describe the issue correct. You wrote: 

> But external users can not participate, because the need a valid nextcloud user name

and 

> Participating with public link not working for non NC users

It would have been better, if you clarified, that you refer to a misleading description and not to a malfunction. This would have prevented me from analysing into the wrong direction and searching a bug.

And BTW: This is solved in #938. So I think, we can close this, right? 

And as a market researcher you are aware for sure, how important precise words are. ;-)

**Comment by nextcloudfan** [comment]
I`m not a programmer, I only describe what is wrong, finding the precise programmer wording is not my task

**Comment by dartcafe** [comment]
> I`m not a programmer, I only describe what is wrong

No, you didn't. You didn't say, that the text is misleading, you said participating is not working. This is nothing about programmer's wordings, this is about communication. 

And when you say, that you are "a market researcher for 15+ years" and you state "know what I`m talking about:)" I suggest, that you have a sense for communication issues.

The easiest way to get a common picture of an issue is a screenshot, which helps to understand, what the communication partner is seeing. 

I would recommend that you use the forum on help.nextcloud.com, because github oviously is too technically orientated for you.

**Comment by nextcloudfan** [comment]
Nothing to add. It was wrong. That`s it. End

**Comment by dartcafe** [comment]
Nope. It was not. And I am right! 
I know, I should stop, but I don't want to.
To be honest: This kind of behavior makes it hard to communicate on a constructive base. And your other issue in another repo proves that.

You are obviously not willing to help improve things, you are just complaining from one state of view. When asking about details you just repeat what you already stated. And a kind hint, how to help maintainers in the future, you are just behaving like a wounded tiger. 

Open source communities participate from the colaboration of people facing each other on the same level and not if someone behaves like a paying customer and is not willing to learn.

**Comment by nextcloudfan** [comment]
You should put this efforts in creating bug free software with correct wording! I would be happy to extend this battle, but I don`t care about your ego.
