### ISSUE TITLE
Polls 1.5.3-RC3 released

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1093]
Planned as the last RC before release
The released is scheduled before 2020-10-03 

# Changes Since 1.4.3

## Features
 - Added setting for defining default view for
   - text polls, defaults to mobile/list layout and
   - date polls, defaults to desktop/table layout #744
 - Better UX for site users, which enter a poll via public link and could login #1096
 - Lookup calendars for conflict #1056 #747
 - Convert URIs in description into clickable links #1067
 - Added a poll option to force the poll appear under relevant polls navigation entry for all users #1072
 - Added user settings
 - Stop immediatley sending of invitation mails after adding a share #1007 #935
 - Adding a REST-API and documentation (still Draft) #966
 - Fix with adding empty dates #961 #958
 - Changed misleading prompt for username in public polls #956 #938
 - Raised minute step to 5 minutes in datepicker #963 #957
 - Added the ability to confirm options #939 #136
 - Add time zone info to date polls #1076

## Refactoring, Fixes and Minor Changes
 - Exclude disabled users from shares #1008
 - Exclude mails to disabled users in group invitations #960
 - Don't invite disabled users #997
 - Hide usernames in notification mail, if results in poll are hidden #990 #980
 - Increase speed of option cloning #1058
 - Changed some icons #862
 - Added Support for Nextcloud 20
 - Drop support for Nextcloud 16
 - Updated dependencies
 - A lot of refectoring and hardening
 - Adding Github Actions as checks
 - Travis and Scrutinizer optimizations

See also: 
* https://github.com/nextcloud/polls/milestone/27?closed=1 and
* https://github.com/nextcloud/polls/blob/master/CHANGELOG.md

Download: https://github.com/nextcloud/polls/releases/download/v1.5.3-RC3/polls-1.5.3-RC3.zip

**Comment by tobyps** [comment]
Hi,
I invested a bit of time to get a VM running to test the new version.

Is this the right place to mention a few things I noticed or should I (re)open new issues?

The new prompt for public polls is currently a mix of english and german (in a german nextcloud) and the link for non cloud users is no longer with a green background (dont know if it is intentional).

The rest seems to work.

**Comment by dartcafe** [comment]
Hey, great. Thanks for supporting with testing. Please open new issues, it is easier to track. 

The missing translations will come in the next days, because it is done via transifex (external service). The final release will be more complete. Normally, German language is complete within a few days.

The green background was removed.

**Comment by sunjam** [comment]
Are these any specific things you'd wanted tested in this release?

**Comment by dartcafe** [comment]
No. Nothing special. Maybe the public polls and the invitation system can need an eye.
