### ISSUE TITLE
Add a Co Creator to a poll

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1095]
**Is your feature request related to a problem? Please describe.**
We use polls to organise our training. The list of participants is needed to be allowed to train under the current pandemic situation. 
So the participants dont need to see who comes (or doesn't) but the Organisers need it. 
Currently only the creator can see the list, if he is unavailable there is currently no access.

**Describe the solution you'd like**
The pollcreator can name one or more users as cocreators who can see the results.

**Describe alternatives you've considered**
We tried the admin can change poll option but that option doesnt allow to see the participants.

Thx

**Comment by dartcafe** [comment]
As a workaround, the admin can remove the anonymous setting temporarily. What you are talking about is some kind of delegation system. Seems to have a bunch of complexity. I would not expect that too soon.

**Comment by tobyps** [comment]
Thanks for the workaround.

If there is a way, it would be a nice feature, but it's not essential.

A second workaround is the impersonate App. Though we only use our cloud for business I prefer less invasive methods, but with lot of users it might be the better way, so nobody can see the names while the admin checks the list.

**Comment by ischiros** [comment]
Hello,
I do agree with this request.
It is an important limit to have only one administrator per poll. We would really need to give access to the administration to more people.

**Comment by pov91** [comment]
Hello,

We also need more than one administrator. We use polls in a medical organization to organise our work. But we have more than one person who is responsible for that and needs access to the administration of existing polls. It would be great if user groups could get access, not only the administrators of Nextcloud.

Thank you to the developers!

**Comment by dartcafe** [comment]
I was thinking about a delegation system the last days. This will not appear in the next version but possibly after that.

**Comment by MarcMichalsky** [comment]
Our organization could also use this feature a lot, as we use polls to align internal and external processes and there is often more than one person in charge. We would appreciate very much.

**Comment by dartcafe** [comment]
See #1960. Solved it via granting poll admin access to invited users

**Comment by ischiros** [comment]
Hello,
I don't believe it addresses the requests we had here.
We asked if it would be possible to *choose* who can administrate a poll.
By granting access to all invited users, we switch from 1 person to everyone. But that's not as good as choosing the right people.

**Comment by tobyps** [comment]
I believe you misunderstood it. 
From the users you have invited to your poll, you can choose 1 and grant him access (see the screenshots in #1960)

Not all invited users have access automatically without your consent.

If it works as intended, I cant tell because I cant currently test it until it is released.

**Comment by dartcafe** [comment]
>  We asked if it would be possible to _choose_ who can administrate a poll.

That's how it is designed. You decide, which invited user is allowed to edit the poll. It is not an all or noone decision. The visual representation is the user icon, as demonstrated in the screenshot.

**Comment by ischiros** [comment]
> I believe you misunderstood it.

Oh, you're right. I interpreted "for invited users" as "for *all* invited users", but didn't see that in the screen, the setting was done for each user.

That's perfect (until testing ;) ), thanks

**Comment by tobyps** [comment]
I found my Nextcloud VM to test it.

3.2 RC2 seems to work fine.

The feature to grant someone Admin rights works.

But it does not help, at least in my original usecase because it just makes the option to let admins edit polls available to all users I wish to grant those right.

But those users or the admins still cant see participants when the original creator put the poll on anonymous.

#1960 is a useful feature but it does not solve this issue, so I would reopen it.

**Comment by dartcafe** [comment]
I plan to remove the option for granting edit rights to admins and therefore give delegated users full control (identical to owner). 

I'll check, if part two can be achieved easily without side effects. Maybe will be done in 3.2. 

Ah, and thanks for testing. 👍
