### ISSUE TITLE
Bigger Sign In Option

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1096]
**Is your feature request related to a problem? Please describe.**
A lot of Cloud users follow the provided link to the poll, enter a username and thus particpate without their account.
That creates a few issues:
Users complain, that their name ist already in use.
Users assume they can change the poll via their account, which doesn't work.

**Describe the solution you'd like**
An option to prioritise Sign in over participating without account would be great. Perfect would basically be to change the current options. 
Big the link to sign in, and a small link to participate without account.

Thx

**Comment by dartcafe** [comment]
As public polls are addressing users from outside NC, NC users should be invited individually or via group invitation. Nevertheless, if a user is logged in, he will be redirected to the internal poll URL. 

Maybe the term username was misleading in the registration dialog for the public poll. This got changed in the upcomming version 1.5 (see https://github.com/nextcloud/polls/issues/938#issuecomment-642698130). This got changed. But we could additionally add a link to the invitation mail, to inform users of the NC instance, that they can use the direct link.

**Comment by tobyps** [comment]
The problem ist for users who dont remain logged in to the cloud.
The Renaming and additional information to our users should help with the situation but at least in our usecase, most users dont stay logged in, so a bit more attention to the login option would still be nice.

**Comment by dartcafe** [comment]
Any design suggestions?

**Comment by dartcafe** [comment]
Quick mockup
![grafik](https://user-images.githubusercontent.com/26707476/93398089-2c880900-f87b-11ea-8d20-f7b18fa79e63.png)

**Comment by tobyps** [comment]
That looks great.
No chance to miss the Login option. 

I would change the "register" to "participate" and add "(optional)" to the  Email field (if it is optional).

**Comment by dartcafe** [comment]
Changed it to two dialogs, because the mobile layout was too tricky: 
First dialog:
![grafik](https://user-images.githubusercontent.com/26707476/93688895-c93fe600-fac9-11ea-8fa8-8976f820b734.png)
Second Dialog (No login):
![grafik](https://user-images.githubusercontent.com/26707476/93688922-099f6400-faca-11ea-90cc-4f2143f7598b.png)

**Comment by dartcafe** [comment]
![grafik](https://user-images.githubusercontent.com/26707476/93688955-4cf9d280-faca-11ea-8ddb-1bb653b336ea.png)

**Comment by tobyps** [comment]
Should still work.

I'm not sure, if the "Back Button" would work. I associate the cross not with going back but with closing the window. 
If it is possible, some other symbol would probably work better.

**Comment by dartcafe** [comment]
Yes, I know. I didn't find a prper icon in the NC icon set. Was too lazy to make one. Need free 20 minutes for that. Maybe today. 😁

**Comment by dartcafe** [comment]
OK. 10 minutes. 

![grafik](https://user-images.githubusercontent.com/26707476/93707071-1654a400-fb2c-11ea-9011-04ed51e119dc.png)
