### ISSUE TITLE
App symbol missing in Desktop Client

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1114]
### What is going wrong?
**Describe the bug**
The Polls symbol is missing in the client, see attached picture.

**To Reproduce**
start client
click nextcloud symbol in traybar
in the right upper corner click on the apps, a list of your apps appears
the symbol for polls is missing

**Expected behavior**
same symbol visible as in browser

**Screenshots**
![Screenshot (81)](https://user-images.githubusercontent.com/52735599/93708469-bc0d1080-fb36-11ea-86f3-3560cee4baa0.png)

### Information about your polls installation
**Polls version?** 
current version (1.4.3)
current client version (3.0.1 windows)

**Comment by dartcafe** [comment]
Installed in a subfolder?

**Comment by tobyps** [comment]
Not sure what you are refering to so:
Nextcloud: yes (/idontknow/web/nextcloudv2)
polls: no idea, via appstore
client: standardfolder of installer

**Comment by dartcafe** [comment]
Sorry, I refer to the the nextcloud url: 
* server.com/index.php/appname or 
* server.com/subdir/index.php/appname

**Comment by tobyps** [comment]
server.com/index.php/apps/polls/

As I havent changed anything (and wasnt aware until now) I guess its the standard path for apps installed via the integretated appstore.

**Comment by dartcafe** [comment]
Everything fine. Some users use a subdir for nextcloud under their domain. 

I asked because there could have been some errors with icons, when called from a subdir. I have to investigate, because all my installations show the icon since update to the new layout (Windows and Mac, NC19 and polls 1.4.3).

**Comment by tobyps** [comment]
Forget it, I just thought of restarting the app and it's back.
I should have thought of it earlier, sorry.
