### ISSUE TITLE
 Personalized link as email

### ISSUE THREAD

**Issue by kleener** [nextcloud/polls#1117]
**Is your feature request related to a problem? Please describe.**
We have participant surveys for several dates and the participants often edit their entries. Now it is so that the participants do not save their personal links and we have duplicate entries or how they often have to delete.
These are participants without accounts.

**Describe the solution you'd like**
It would be great if the participants were optionally asked for their email address and the personal link was sent to.

**Describe alternatives you've considered**
Alternatively, the personal link should be shown more present.
I only saw him the 2nd time.
Maybe a prompt after entering the name.

**Comment by dartcafe** [comment]
The new register dialog in upcomming version 1.5 for public polls
![grafik](https://user-images.githubusercontent.com/26707476/94026954-a27bfb00-fdba-11ea-8543-33366d2c8e94.png)
If an email address was entered, an invitaion mail will be sent.
Additionally
![grafik](https://user-images.githubusercontent.com/26707476/94027666-609f8480-fdbb-11ea-95ae-4c98bb404077.png)

**Comment by kleener** [comment]
ohh that's cool.
Thank you for your prompt reply.
