### ISSUE TITLE
1.5RC: Horizontal scrolling fails with webkit browsers

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1118]
With the RC of ver 1.5 scrolling horizontally moves the participants out of view. The participants start scrolling after more than 6 or 7 date options or more on wide screens / large browser windows.

![Screenshot 2020-09-25 at 11 14 03](https://user-images.githubusercontent.com/43957716/94251126-6cf22180-ff22-11ea-8082-4e9b2577e526.png)

I experienced this issue with the current webkit browsers  Safari 14 on macOS and on iOS/iPadOS 14. Firefox and Chrome on Desktop (tested with Win10 and macOS) are OK.

#533 is back?

**Comment by dartcafe** [comment]
I have limited possibility to test that. At some point the users move to the right. Will not be possible to fix before the release.

**Comment by herrmannsdorfer** [comment]
Checked with rel 1.5.4: Bug is present - switched to experimental styles in settings: bug is gone.

Happy debugging :-)

**Comment by dartcafe** [comment]
> Bug is only present when sidebar is on.

Thanks for the hint. I will investigate that.

**Comment by herrmannsdorfer** [comment]
Correction: The bug is independent wether the sidebar is on or off. It just depends on the visible part of the options. I made a screen recording to illustrate that. Note the visible options end with "Oct 8" (which is partially covered): As soon as this option is scrolled to the left border where the participants are listed the participants start scrolling too.
And scrolling back: the participants come into view when the part of option "Oct 8" is visible again.

![Screen_recording](https://user-images.githubusercontent.com/43957716/95954127-1f6b2500-0dfb-11eb-8a41-452237274df1.gif)

**Comment by ahcm** [comment]
For me on Mac OS 11, Polls 1.6.2,  Firefox 83.0 has the issue but not Safari.
