### ISSUE TITLE
Missing translations of new dialogue

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1126]
### What is going wrong?
**Describe the bug**
Some translations in the new pop ups are missing (see screenshots).

I checked the translations (https://github.com/nextcloud/polls/blob/v1.5.3-RC3/l10n/de.js) and the files contain the former phrases (ie "You have an account? Log in here." : "Du hast ein Konto? Hier anmelden.") but not the new stuff (ie "Are you a user of this site and have a login?").
Other languages seem to have the same issue.

As only the new parts are missing I dont if it is an issue or just part of the process but as the release for 1.5 is estimated for before 3.10. I decided to mention it anyway.

**Screenshots**
![Screenshot (84)](https://user-images.githubusercontent.com/52735599/94529590-370eaf00-023a-11eb-9ea0-8ec3f6c2e459.png)
![Screenshot (85)](https://user-images.githubusercontent.com/52735599/94529603-3aa23600-023a-11eb-9812-5a6b94956b44.png)

### Information about your polls installation
1.5.3 RC3 from 29.09.2020

**Comment by dartcafe** [comment]
Translations receive the master branch with delay, because they are done via transifex. Look in the current de.js and you'll find the missing translations. The release will contain all translations, which are delivered until it's build.

https://github.com/nextcloud/polls/blob/master/l10n/de.js

**Comment by tobyps** [comment]
Thanks, I hadn't realised that I didn't checked the right file.

Using those files the translations work, just I small thing (which could be because I just copied the 2 translation files), the user name isn't displayed in the "we will call you [username]" dialogue
![Screenshot (87)](https://user-images.githubusercontent.com/52735599/94573734-a86a5400-0272-11eb-9d6d-0113383914ec.png)

**Comment by dartcafe** [comment]
Waaaa. Someone translated the variable name. 😆 
@rakekniven Could you promote me as a reviewer on transifex?

**Comment by rakekniven** [comment]
@dartcafe Which languages do you like to review?

**Comment by dartcafe** [comment]
> @dartcafe Which languages do you like to review?

German. 
 
> EDIT:
> Have fixed it right now. It was me causing this one.

I know. 😁

**Comment by rakekniven** [comment]
You are now a reviewer for both german languages.

> I know. 😁

I know you know   😁 😁 😁

**Comment by dartcafe** [comment]
> I know you know 😁 😁 😁

So, no chance to deny. 😎
