### ISSUE TITLE
Polls App spams Mails to our users!

### ISSUE THREAD

**Issue by flixbi** [nextcloud/polls#1130]
### What is going wrong?
**Describe the bug**
The bug spams invite Links to our users.

**To Reproduce**
1. I created a new poll
2. I added the group "everyone" to share it with all users in that group (on our testsystem for - so it's only for about 4 users r.n.)
3. I edited the poll and added the description
4. The Extension spamed us all with arround six emails p.P.

**Expected behavior**
I expected that we only receive one email.

**Possible Solution**
Track the Notifications and store them as Transactions or just as an incremental number value
to prevent spaming until it's triggered by an Supporter/Creater to send inviration Mails again.
> Could be combined with an date "from - to" feature, to release invitation Mails on a poll release date (but only once)

**Screenshots**
- not requiered I guess -

### Information about your polls installation
**Polls version 1.4.3**

**Fresh installation or update from a prior version (from which one)?**
First time we tried it.
**How did you install this version?(Appstore or describe installation)**
Via the Appstore
### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
19.0.3
**List of activated apps:**

**Nextcloud configuration:**
- everything works the finest 

### Server configuration

**Operating system**:
Docker Image (official by Nextcloud)

**Web server:**
Currently Apache

**Database:**
MariaDB

**PHP version:**
7.*

**Signing status:**
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
More information (of the samples) of the mails would help to understand what happened. 
If I guess: 
* the first mail invited the users
* the next mails are send out informing about the configuration changes, because, the users subscribed to the poll
* The changes to the poll configuration was made over a couple of time (depends on how often the cron job runs)

If this is not the case, I need more information.
