### ISSUE TITLE
Option to create internal link for sharing

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/polls#1152]
Hey,

I'm currently missing the option to share a poll with users of our nextcloud withoug having to define a groupe. In files etc. there ist the option to create an internal link, I'd really appreciate such an option or polls, too.

Thanks a lot for the great work!

**Comment by dartcafe** [comment]
I don't get you. Why can't you use the URL of the specific poll?

**Comment by hansimausisteffiwurstbrot** [comment]
Because I only want people with an account to be able to vote.

Or perhaps I didn't see the option for that?

**Comment by dartcafe** [comment]
I talked about the internal URL. i.e.  .../index.php/apps/polls/vote/20

**Comment by hansimausisteffiwurstbrot** [comment]
great, haven't thought of this. thank you for the hint!

I was missing the button for copying the internal link as an option in the sharing menu.

I still think it would be good to have it there, creates consistency, too.

**Comment by dartcafe** [comment]
> I still think it would be good to have it there, creates consistency, too.

I think about it. Becaause of that I added the UX badge. Could be done without much coding.
