### ISSUE TITLE
User choice/vote leak

### ISSUE THREAD

**Issue by tarradmac** [nextcloud/polls#1159]
### What is going wrong?
When you share with a user a poll, it generate a link for this user, if you get this link you can modify the choice/vote for that user as your are him.
The link in the mail is a link to the poll and work correctly, it is not the same as the one you can copy near the username.
I create a date choice I invited foo and bar to that vote, I can copy the link sent to foo which is like https://mycloud/index.php/apps/polls/s/random-alpha. If bar use this link he can choose or modify the choice as it was the user foo...

**To Reproduce**
Create a new poll, share to few users, copy the link for one and connected to another change the choice.

**Expected behavior**
The user connected should not be able to use another vote.

### Information about your polls installation
**Polls version?** 
1.4.3

**Fresh installation or update from a prior version (from which one)?**

**How did you install this version?(Appstore or describe installation)**

### Information about your Instance of Nextcloud/ownCloud

Nextcloud 18.0.7

**List of activated apps:**
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.10.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 1.0.5
  - drawio: 0.9.7
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_fulltextsearch: 1.4.3
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.11.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - forms: 2.0.4
  - fulltextsearch: 1.4.2
  - fulltextsearch_elasticsearch: 1.5.2
  - groupfolders: 6.0.7
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.10
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflow_script: 1.3.2
  - workflowengine: 2.0.0


**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxxxxxxx.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "18.0.7.1",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cloud.xxxxxxxxxxxx.org:443",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.xxxxxxxxxx.org",
        "simpleSignUpLink.shown": false,
        "maintenance": false,
        "loglevel": 2,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "fr",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to png --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Font"
        ],
        "updater.release.channel": "stable",
        "theme": "",
        "mysql.utf8mb4": true
    }
}

### Server configuration

**Operating system**:
Debian 10.4
**Web server:**
Apache 2.4.38
**Database:**
mariadb 10.3.22
**PHP version:**
7.3

**Comment by dartcafe** [comment]
I didnt't understand your description properly. 
Are foo and bar user from the site or external users?
How did you invite foo and bar? 
Which link was sent to bar?
Which link was sent to foo?

If you create a share link for foo like mycloud/index.php/apps/polls/s/random-alpha-for-foo and send it to bar, than bar accesses the poll as foo, because he uses foo's secret. It is like leaking credentials.

**Comment by tarradmac** [comment]
Hi,
English is not my natural language...
So foo and bar are internal users, I used the share function to invite foo and bar, so they received the invitation by mail with the link to the poll mycloud/index.php/apps/polls/vote/XX and they could vote with their name.
But near the names of users there is a link like mycloud/index.php/apps/polls/s/random-alpha-for-foo and I have a user who send this link to a group so they can vote for the user associated with this link. I think there is a confusion for users with this link, maybe it could be usefull to have a "resend link to user".
I hope I have been clearer now.

**Comment by dartcafe** [comment]
So, you say, that someone copied the invitation link from an internal user and sent it to other site users. This was designed as a feature but has been removed in the current version (1.5.x). Of course, if a personal link for an external user is sent to other persons, this will still happen. But this is not preventable. 

> maybe it could be usefull to have a "resend link to user".

You find this as well in the current version.

**Comment by tarradmac** [comment]
Ok I have planned to do maintenance upgrade on my instance next week, I will then close this issue.
Thanks

Le 16 octobre 2020 15:35:24 GMT+02:00, "René Gieling" <notifications@github.com> a écrit :
>So, you say, that someone copied the invitation link from an internal
>user and sent it to other site users. This was designed as a feature
>but has been removed in the current version (1.5.x). Of course, if a
>personal link for an external user is sent to other persons, this will
>still happen. But this is not preventable. 
>
>> maybe it could be usefull to have a "resend link to user".
>
>You find this as well in the current version.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/polls/issues/1159#issuecomment-710050958

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tarradmac** [comment]
Hi maintenace done and all is ok for me, thanks.
