### ISSUE TITLE
Sorting options via sidebar does not work - option flips back to its original position when releasing the mouse

### ISSUE THREAD

**Issue by uli-heller** [nextcloud/polls#1163]
### What is going wrong?
**Describe the bug**

I tried the sidebar for sorting options. Unfortunately, it doesn't work. Dragging the "6"
downwards works at first, but when releasing the mouse it flips back to
its original position. I'm using chrome 86, nextcloud 20 and calendar 2.1.4.

![image](https://user-images.githubusercontent.com/1677414/96090844-1d6f9780-0ec9-11eb-95a6-9bd9677dc21c.png)

The issue was detected when working on #1160 

**To Reproduce**
Open the sidebar and try to reorder the options
via drag and drop. Releasing the mouse leads to
the option flipping back to its original position.

**Expected behavior**
Releasing the mouse persists the new ordering

**Screenshots**

![image](https://user-images.githubusercontent.com/1677414/96091085-6889aa80-0ec9-11eb-82f5-8b972aa67341.png)

### Information about your polls installation

See #1160

**Comment by dartcafe** [comment]
simple syntax error. Pushed to master
