### ISSUE TITLE
Desktop vs mobile seems to work more like "summary vs details"

### ISSUE THREAD

**Issue by uli-heller** [nextcloud/polls#1164]
### What is going wrong?
**Describe the bug**

Looking at an existing poll, I get this screen:

![image](https://user-images.githubusercontent.com/1677414/96093210-29108d80-0ecc-11eb-8f1e-f71d87cf8aca.png)

The screen looks different from what I'm used to see and what I want to see. I'd like to see the details
of the poll.

In the upper right corner, there are small icons:

![image](https://user-images.githubusercontent.com/1677414/96093406-6412c100-0ecc-11eb-942c-d8669b9b5240.png)

The middle icon reads "to desktop view". Clicking on it produces this:

![image](https://user-images.githubusercontent.com/1677414/96098895-edc58d00-0ed2-11eb-809f-2372c28b9abb.png)

The middle icon nox reads "to mobile view".

From my point of view,
- the texts "to mobile view"/"to desktop view" are wrong
- the graphical icons don't fit too well, too

I'm using chrome86, nextcloud 20, calendar 2.1.4

**Comment by dartcafe** [comment]
Yes. This is a relict of the time, when the list view was designed for mobile view. Maybe we should rename this consistently to grid and list view.

**Comment by pongraczi** [comment]
Probably a Pie chart could be an easy way to overview the entire poll in a small screen.  
Something like this:  
![piechart](https://user-images.githubusercontent.com/5891983/106266094-4aea1200-6228-11eb-8322-d1695e940882.jpg)

The answers could be numbered and the Legend could contains the following:  
colored box,  # of the option,  votes of this option, percentage  

Example (sketch):  
![legend_sketch](https://user-images.githubusercontent.com/5891983/106266808-2d697800-6229-11eb-8d33-127cc6974a4f.jpg)

**Comment by dartcafe** [comment]
@pongraczi as this issue addresses the term and the icons of both view modes, your proposal targets an additional view of the poll result. This should be a topic of an own issue. Your proposal will get lost here.

**Comment by pongraczi** [comment]
@dartcafe Thank you for your hint, I opened a new issue (feature request) for this idea: #1444
