### ISSUE TITLE
Localization on public poll page

### ISSUE THREAD

**Issue by areaslivres** [nextcloud/polls#1166]
When I open a public poll, it asks me if I have a login or not. Even though the rest is enabled in Portuguese, this part shows up in English. Can this be included to the localization file? I am happy to translate these strings.

**Comment by dartcafe** [comment]
The localisation is done via tranisfex. Sometimes some translations have a delay, if there are not so many translators. So this will be solved in a following version. 

But if you are interested in supporting Portuguese language, @rakekniven is the right contact person.

**Comment by rakekniven** [comment]
> When I open a public poll, it asks me if I have a login or not. Even though the rest is enabled in Portuguese, this part shows up in English. Can this be included to the localization file? I am happy to translate these strings.

Can you provide a screenshot?

For translation beginners please see https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550

**Comment by rakekniven** [comment]
Just seen that polls resource is only 15% complete for pt_PT.

We can close here, or?

**Comment by areaslivres** [comment]
> > When I open a public poll, it asks me if I have a login or not. Even though the rest is enabled in Portuguese, this part shows up in English. Can this be included to the localization file? I am happy to translate these strings.
> 
> Can you provide a screenshot?
> 
> For translation beginners please see https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550

![Screenshot from 2020-10-16 10-44-45](https://user-images.githubusercontent.com/72947479/96279712-ab688280-0f9c-11eb-9315-0d2c69437894.png)

I mean this page. I have the pt version enabled and it works fine when creating the poll, but the public poll page is in english.

**Comment by rakekniven** [comment]
Hello, 

thanks for the screenshot.

Repeating myself:
Just seen that polls resource is only 15% complete for pt_PT.

**Comment by areaslivres** [comment]
@rakekniven can I have access to this translation to finish it? I would be glad to make the effort in translating in order to fully localize this nextcloud app

**Comment by rakekniven** [comment]
@areaslivres For sure you can help.
Please see https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550 and join us at Transifex.

**Comment by areaslivres** [comment]
@rakekniven great, i joined the nextcloud team on transifex. how do i translate the specific poll app strings to pt.br?

**Comment by areaslivres** [comment]
ok! found it here https://www.transifex.com/nextcloud/nextcloud/translate/#pt_BR/polls

**Comment by areaslivres** [comment]
@rakekniven ive translated the untranslated strings. what is the next step?

**Comment by rakekniven** [comment]
@areaslivres Great to see your progress!

> what is the next step?

Nothing on your side. You have to wait until the next version of the app has been released.

**Comment by areaslivres** [comment]
great! any prospect on dates?

**Comment by rakekniven** [comment]
@dartcafe You?

**Comment by dartcafe** [comment]
Version 1.6 is currently in dev mode and no DOA right now. Unfortunately it depends on @v1r0x and his spare time for pushing to the appstore as I have no access there.

**Comment by dartcafe** [comment]
@rakekniven As we are talking about translations. Something is going wrong on transifex. Just inspected the translations and found that:

https://github.com/nextcloud/polls/blob/9463be77fea9d306269d9e017780ba054847c2b0/l10n/de.js#L17-L31

**Comment by rakekniven** [comment]
Hello,

I am aware of it. That is some automatic from Transifex. Have it on my todo list for the weekend.
Hope that is sufficient.

**Comment by dartcafe** [comment]
No hurry. Translations do not work in polls ATM. I don't know why. 

EDIT: Ah OK. Perfect.
