### ISSUE TITLE
Performance polls overview

### ISSUE THREAD

**Issue by martinelkb** [nextcloud/polls#1181]
### What is going wrong?

There are performance issues in the XHR-Requests. 

**To Reproduce**
1. Klick on "Polls"
2. The screen shows "Keine Umfragen vorhanden" (no polls available)
3. Updating the screen needs a long time (more than 10sec in my case)

### Information about your polls installation
**Polls version?** 
Version 1.5.4

**Browser:**

same in Firefox and Chrome

**Comment by dartcafe** [comment]
How many polls are configured? Including deleted ones.

**Comment by martinelkb** [comment]
> How many polls are configured? Including deleted ones.

~ 30 polls + 10 deleted polls

**Comment by dartcafe** [comment]
See https://github.com/nextcloud/polls/issues/1183#issuecomment-718723943. Also no problem here.
