### ISSUE TITLE
User selection while sharing a poll is slow and sometimes jumping

### ISSUE THREAD

**Issue by martinelkb** [nextcloud/polls#1183]
### What is going wrong?

Selecting a user to share a poll is slow and sometimes jumping.

**To Reproduce**
1. Create a poll
2. Click on "Freigaben" (Shares)
3. Share the poll to an user (+5000 existing users in the system).  
4. The users in the selectbox jumping an sometimes not showing the right selection

**Expected behavior**
Get a fast selection of users, similar when selecting a user for sharing a file. 

### Information about your polls installation
**Polls version?** 

**Nextcloud/ownCloud version:**
Version 19.0.3

**Browser:**

same in Firefox and Chrome

**Comment by dartcafe** [comment]
I am refactoring the sharing system, but I fear this will have no effect on your issue. 
Do all users have this problem?
Do you use ldap? 
We had some similar problems in #912, but I have no feedback if this issue is solved or still existent.

**Comment by dartcafe** [comment]
I tried to reproduce this, but I don't see any performance problems. I have something about 60 polls, including deleted and created something about 10.000 users. The search shows no significant performance break downs comparing with the sharing function in i.e. the files app. 

It is a little bit laggy, but plausible with 10.000 users.

I tested with polls 1.6, NC20, PHP 7.4, MySQL 5.7 on a shared host. I just created the users with a backend function and they got no initial login.

So, I have no idea.

**Comment by brtptrs** [comment]
We are still seeing this problem after upgrading to NC20 and polls 1.6.2.

A very similar problem was just solved in circles. I think in this commit:

https://github.com/nextcloud/circles/commit/0810fbbc0fcbe690fe871ac8181ecfe2ee29434c

Maybe that could shed some light on the problem.

**Comment by dartcafe** [comment]
> Maybe that could shed some light on the problem.

Maybe, but I have to understand the issue first. On my side, I can see no glitches, everything runs very smooth. Could you provide a screenvideo of the behavior.

**Comment by brtptrs** [comment]
Yes I'll be happy to. Posting a video with user name here might be a bad idea though. How can I forward it privately?

**Comment by brtptrs** [comment]
I've done a video clip with the usernames covered up.
With a short explanation you might understand what you are not seeing.
1) Create a poll
2) Open the share tab
3) Start typing. In this case "test" searching for "test.xyz" user
4) At the start correct results (all containing "test" is shown.
5 After a while without any further interaction different results (wrong) replace the previous(correct) results

The problem is:
If you don't pay attention the results may change at the moment you click the result you were looking for, thereby inviting the wrong person. This is not hypothetical, many users have complained about wrong people being invited to polls. It has happend to me personally a few times as well.
[user-search-polls-2020-12-04_16.46.32.zip](https://github.com/nextcloud/polls/files/5643848/user-search-polls-2020-12-04_16.46.32.zip)

**Comment by dartcafe** [comment]
Is it possible to get access to your system, to try it?

**Comment by dartcafe** [comment]
BTW: You can upload here (filedrop): https://dev.yagst.de/s/pAKCbDPGtoc7YAx

**Comment by brtptrs** [comment]
I've uploaded a few files, thanks for taking the time to look at this.

**Comment by daita** [comment]
Hello,

I had the same issue on Circles, it's a race condition between 2 ajax request.

When someone is searching for a user:

- The first request is done with a small string (might be 1 char length) which will take a lot of time (could be 5+ seconds) of huge instance.
- A second request is done few seconds later with a better accuracy, and will returns result almost instantly.
- The result second request are received from the back-end and displayed on the front-end.
- The result from the first request are now received and displayed, erasing the result from the second request.

How I easily fixed this race condition on Circles:

- I have 2 new variables in my front-end: a counter and a displayedCounter.
- Each time I send a search request on the back-end, I increment the value of the counter and add it to the request.
- The backend will return, with the result of the request, the exact value of the _counter_ received with the original request from the front-end.
- The front-end compare the value of the counter with displayedCounter, and will manage the result and store the counter as displayedCounter if it's not lower that the previously stored value for displayedCounter.

**Comment by dartcafe** [comment]
Aah, now I understand what you did there, interesting approach. Great, thanks.
> I had the same issue on Circles, it's a race condition between 2 ajax request.

I guessed that it could be something in this direction, but had no time to examine this further. 

Your hints saved me a lot of time for guessing and trying.

**Comment by dartcafe** [comment]
@daita I tried another approach with cancelling previous requests via axios cancel. So I can omit the handling of the request counter and let axios control the requests. 

Do you know anyone, who can proof that this approach has no side effects?

**Comment by dartcafe** [comment]
@brtptrs Thanks for providing all your information. I just wanted to confirm, that all files have been securely removed from all systems!

**Comment by daita** [comment]
You could do some testing the hard way: add a sleep(10) on 1-char length search on the back-end to simulate an heavy search :)

**Comment by dartcafe** [comment]
That's the way I tested. To avoid a request after every keystroke, I added a debouncing with 250ms to the request call, too. Works quite good.

**Comment by dartcafe** [comment]
@martinelkb @brtptrs 

Just curious: Did the last version solve the reported issues here?

**Comment by brtptrs** [comment]
Yes, this issue is solved :-)
Thanks again!
