### ISSUE TITLE
Setting "Use calendar lookup" shows conflict with all recurring all-day dates

### ISSUE THREAD

**Issue by gryban1** [nextcloud/polls#1185]
### What is going wrong?
**Describe the bug**
When the setting "Use calendar lookup" is active all date options in a poll are showing a date/time conflict with all (yearly) recurring all-day dates in all calendars.

**To Reproduce**
1. Create a yearly recurring all-day date in one of your calendar (e.g. a birthday)
![Screenshot - 20 10 2020 , 17_06_18](https://user-images.githubusercontent.com/48805276/96605504-94a49180-12f6-11eb-8aed-1aa446025216.png)

2. Activate "Use calendar lookup" setting in the polls app
![Screenshot - 20 10 2020 , 16_58_36](https://user-images.githubusercontent.com/48805276/96604879-e26cca00-12f5-11eb-91b3-abb6d715519b.png)

3. Create a date poll with one or more options
![Screenshot - 20 10 2020 , 17_02_31](https://user-images.githubusercontent.com/48805276/96605057-0d571e00-12f6-11eb-97fa-1bdb7d3f2c15.png)

4. You'll see conflicts at all dates in your poll with all your recurring all-day 
![Screenshot - 20 10 2020 , 16_15_30](https://user-images.githubusercontent.com/48805276/96606329-74c19d80-12f7-11eb-970b-9ca451012075.png)

**Expected behavior**
No conflict with any of these dates.

### Information about your polls installation
**Polls version?** (see apps page)
1.5.4

**Fresh installation or update from a prior version (from which one)?**
update from 1.5.3, but all tests are startet fresh within 1.5.4

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
19.0.4 - 19.0.4.2

**List of activated apps:**
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - apporder: 0.11.0
  - breezedark: 19.0.6
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_downloadactivity: 1.8.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - music: 0.17.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - polls: 1.5.4
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sharingpath: 0.2.5
  - spreed: 9.0.4
  - support: 1.2.1
  - tasks: 0.13.4
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - comments
  - federation
  - files_external
  - files_markdown
  - occweb
  - recommendations
  - survey_client
  - systemtags
  - user_ldap

```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.roland-siegel.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "https:\/\/cloud.roland-siegel.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "knowledgebaseenabled": true,
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

### Server configuration

**Operating system**:
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64

**Web server:**
Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:**
mysql 10.3.22

**PHP version:**
7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Signing status:**
![Screenshot - 20 10 2020 , 17_22_20](https://user-images.githubusercontent.com/48805276/96607658-db938680-12f8-11eb-8e89-66f317da6824.png)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Device:**
Desktop

**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0

**Operating system:**
Windows 10

#### Nextcloud log (data/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/polls/files/5409714/nextcloud.log)

#### Browser log
Insert your browser log here, this could for example include:

a) The javascript console log: 
[console-export-2020-10-20_17-28-30.txt](https://github.com/nextcloud/polls/files/5409727/console-export-2020-10-20_17-28-30.txt)
b) The network log: (github doesn't support the HAR-format of network-logs from Firefox)

**Comment by dartcafe** [comment]
I think, we should make it configurable, which calendars should be used for the lookup.

**Comment by dartcafe** [comment]
Looks like a bug in the calendar search (or we use it in a wrong way). We get recurring items, where we shouldn't get some. I added a  filter, to return only relevant events.
Additionally I removed the time information, if an event is an all day event.
