### ISSUE TITLE
"this poll does not exist" error for logged in users when sharing poll with link and setting option "not visible for other users" 

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/polls#1188]
When sharing a poll with a link and setting option "not visible for other users" recipients with an account can only vote when not logged in. This is contra intuitive and makes no sense since they still have the option to vote after they logged out of the instance.

I propose that this behaviour gets changed since I repeatedly saw users making this mistake because instead of sharing a poll with each user of the instance (or group or circle) they just created a link and sent it via mail…

**Comment by dartcafe** [comment]
See #1153 Await version 1.6.

**Comment by lars-becker** [comment]
Sorry, searched for this issue, but seemingly only opened ones. Thanks for the fix! :-)

**Comment by dartcafe** [comment]
Don't worry. Better this way, than no feedback.
