### ISSUE TITLE
Translations do not work

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1189]
@ChristophWurst @skjnldsv 

I need help! I have no idea, why the translations are not working. Any hint? 

### What is going wrong?
**Describe the bug**
The translations in polls are broken. All terms from the poll apps stay in english.

**To Reproduce**
1. Set language to german
2. Open polls

**Expected behavior**
German language is expected

### Information about your polls installation
**Polls version?** from current master (without imported @nextcloud/l10n)
I rolled back webpack and other modules. Seems to have no effect. See https://github.com/nextcloud/polls/tree/translations-test with imported @nextcloud/l10n

Server version is NC20 release and also NC20-RC1. Did not test on other server versions.

I get a warning in the console: `No OC found index.js:46:12` from l10n
de_DE.js is not loaded. Other apps seem to work as expected. 
![grafik](https://user-images.githubusercontent.com/26707476/96937585-c1a89e00-14c8-11eb-9906-21f4ea7922f3.png)

Test in the console, after loading polls:
- `typeof OC` returns object. 
- `OC.getLanguage()` returns 'de_DE'

![grafik](https://user-images.githubusercontent.com/26707476/96937692-06343980-14c9-11eb-8554-164542bf59e9.png)

**Comment by ChristophWurst** [comment]
> Test in the console, after loading polls:

That is the point. The first warning is shown for code that is run very early, when only some scripts are available. Your manual test is performed when everything is there.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/polls/commit/97a429c7d40c692d182bd07df17ac564f47d1426 won't make any difference as long as the l10n extraction tool finds your translation strings.

**Comment by dartcafe** [comment]
> 
> 
> > Test in the console, after loading polls:
> 
> That is the point. The first warning is shown for code that is run very early, when only some scripts are available. Your manual test is performed when everything is there.

Yes, that's what I assumed. But what could be the issue here? Especially comparing to other apps, i.e. deck, I can't find any significant difference. 


> [97a429c](https://github.com/nextcloud/polls/commit/97a429c7d40c692d182bd07df17ac564f47d1426) won't make any difference as long as the l10n extraction tool finds your translation strings.

Wasn't sure, if the loading strategy changed and could cause this issue. But there was no difference, so I second you.

So, do you have any idea, what's going on here?

**Comment by dartcafe** [comment]
OMG! Forget about it. The problem sat in front of the computer. I am testing at a remote server and didn't sync the l10n directory... 

Shame on me!

**Comment by dartcafe** [comment]
😆 🤣 

This comment got me on track.
> as long as the l10n extraction tool finds your translation strings.

Thanks for your help.....
