### ISSUE TITLE
Releases v1.5.5 + v1.5.6 not available by apps.nextcloud.com

### ISSUE THREAD

**Issue by sokai** [nextcloud/polls#1192]
The last two releases/versions of Polls ([v1.5.5](https://github.com/nextcloud/polls/releases/tag/v1.5.5) + [v1.5.6](https://github.com/nextcloud/polls/releases/tag/v1.5.6)) are not installable at/from the Nextclouds AppStore on [apps.nextcloud.com](https://apps.nextcloud.com/apps/polls). Only [v1.5.4](https://github.com/nextcloud/polls/releases/tag/v1.5.4) is available.

#thx4fixing

**Comment by dartcafe** [comment]
Yes. Sorry, but this unfortunately a process with delay. We have to wait.

**Comment by v1r0x** [comment]
1.5.5, 1.5.6 and 1.5.7 are now available.
