### ISSUE TITLE
Unable to view buttons of public shared link in side panel

### ISSUE THREAD

**Issue by andrewhotlab** [nextcloud/polls#1194]
After upgrading from Nextcloud 17 to 18, we noticed that the public link buttons are no longer displayed on small screens, because link text is no longer trimmed, as it still is for other elements (like "shared with other").

Please see the attached screenshot to understand what I mean:

![Screenshot_2020-10-24_13-20-11](https://user-images.githubusercontent.com/26433166/97080576-a50d8280-15fc-11eb-9072-8b9e04e75cfa.png)

**Comment by dartcafe** [comment]
Yep, found it too. I fixed it already for version 1.6.
