### ISSUE TITLE
Participate again with deleted name 

### ISSUE THREAD

**Issue by kleener** [nextcloud/polls#1204]
Hello,
we have the problem that some people forget to save their personal link.
As a result, they have always participated with new names.
The idea was to delete the wrong entries so that you can participate again and have the link or an email sent to you. Unfortunately, this is not possible because the name is already in use, although the entry has been deleted. 
Can you fix this please.

**Comment by dartcafe** [comment]
Resending an email from the owner's access is a feature for the comming version 1.6. Meanwhile, the owner can com the link from the share settings and send it manually. He can also remove the user and his votes.

**Comment by kleener** [comment]
OK, we understand. Thanks
