### ISSUE TITLE
The link in the notification emails cannot be used by users without an account

### ISSUE THREAD

**Issue by TaoTePuh** [nextcloud/polls#1231]
**To Reproduce**

1. Add new Poll.
2. Add a public link.
3. Visit the public link.
4. Choose "No, I have no login".
5. Enter 'Name' and 'email'
6. Check "Receive notification email on activity to ..."
7. Vote.
8. Visit the public link again.
9. Choose "No, I have no login".
10. Enter another 'Name' and 'email'
11. Vote.
12. Check emails (from 5.) and try the link in the notification email
=> The Link in the notification email redirects to official Login, but it should be the personal link to this poll.

### Information about your polls installation
**Polls version?** 
1.5.7

**How did you install this version?**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:**
19.0.4

**Comment by dartcafe** [comment]
Yep. See #1205 Will be fixed in 1.6
