### ISSUE TITLE
Issue with DB (mysql) during installation!

### ISSUE THREAD

**Issue by Lockorocko** [nextcloud/polls#1232]
Hi Guys,

i installed a few new NC-Instances on my VPS with the php-installer and upgrade them to NC20.0.1.

Yesterday I tried to install the Polls-App but got this notification:
![image](https://user-images.githubusercontent.com/42206677/98837983-ed71d080-2443-11eb-9073-1efcc597ffc0.png)

With other App-Installations i had no problems.

Actually i'm using the latest versions of Apache2 and MySQL on my vps and prepared the db with the following commands:

> mysql>CREATE DATABASE nextcloudXYZ;
> mysql>GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON nextcloudXYZ.* TO nextcloudXYZuser@localhost IDENTIFIED BY 'nextcloudXYZpw';
> mysql>quit;

Did i anything wrong?
Can anyone help me? :(

Peace
Locko

**Comment by dartcafe** [comment]
@v1r0x Any idea. 
I guess this happens here.
https://github.com/nextcloud/polls/blob/fcf5c50ef57e9bf0180fc27471e7483cc803f7f6/lib/Migration/Version0104Date20200205104800.php#L108-L113

@Lockorocko A quick look in the MySQL docs says: 

> REFERENCES
Creation of a foreign key constraint requires the REFERENCES privilege for the parent table. 

https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_references

**Comment by Lockorocko** [comment]
The solution was to grant the right privileges :)
I tried it before but i did something wrong i think -.-

Thank you for the quick support ♥
