### ISSUE TITLE
branch nc-12: poll status not updated in polls overview window

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#125]
When I vote in a (text) poll and submit the result to the database, the status light in the polls browser does not change from red to green as it should.

This is only true for Safari. In Chrome it works.

This happened after I deleted all polls databases and reinstalled polls app (auto recreate the databases).

**Comment by v1r0x** [comment]
Damn apple....:P I try to find a solution to test it with safari.

**Comment by joergmschulz** [comment]
Did you find a way to test Safari? There are virtualboxes with Sierra (previews), maybe this would be a solution.

**Comment by v1r0x** [comment]
Not yet. Will have a look at the virtualbox solution. Thanks for the hint

**Comment by Schmuuu** [comment]
Hi,

I see the same issue in Firefox 54.0.1 (32-Bit) and MS Edge. In the overview there is no update of status lights.
I'm using NC 12 (stable release) on Ubuntu 16.04 LTS and installed the app from the NC store. So might not be a browser related issue.

**Comment by joergmschulz** [comment]
no need for a OSX virtualbox if you have a current windows system somewhere - Internet Explorer has the same issue.

**Comment by dartcafe** [comment]
Fixed in #166
