### ISSUE TITLE
For Date Polls Allow End users to Select their own timezone

### ISSUE THREAD

**Issue by ekianjo** [nextcloud/polls#1250]
Right now the date polls default to UTC for all users which is hard to understand if you are not close to that timezone. End users should be able to see their own timezone and the survey would adapt the displayed dates accordingly

**Comment by dartcafe** [comment]
Timezones are taken from the browser's settings. See discussion in #995 for possible issues on your side.

**Comment by ekianjo** [comment]
thanks - let me confirm

**Comment by datendelphin** [comment]
I have a similar request. Using browser settings for the time zone seems to work well, but not everyone knows their time zone setting or how to set it in their browser. At least displaying somewhere which time zone is currently used would be appreciated.

Case: I just had a discussion with someone from another time zone, trying to figure out if we need to manually apply time shift or not. Having the time zone at least displayed would avoid such a confusion and make it clear that polls actually supports time zones (which is a nice feature, thanks)

**Comment by dartcafe** [comment]
This is the current implementation:
![grafik](https://user-images.githubusercontent.com/26707476/105615265-85d6ea80-5dcf-11eb-87d5-ac0590002efb.png)
see also: #1076

**Comment by datendelphin** [comment]
Sorry about that, indeed I just need to update and it shows what I need! Thank you

**Comment by dartcafe** [comment]
> Using browser settings for the time zone seems to work well, but not everyone knows their time zone setting or how to set it in their browser.

Just for claficiation: The timezone is normally taken from the user's OS, not set in the browser. So the timezone the browser uses should be identically to the timezone used on the entire computer.

> Sorry about that,

And please no apologies for requests and questions...

**Comment by webberian** [comment]
@dartcafe , you wrote:

> Just for clarificiation: The timezone is normally taken from the user's OS, not set in the browser. So the timezone the browser uses should be identically to the timezone used on the entire computer.

As #995 demonstrates, at least for Firefox the timezone is taken from the browser, NOT from the OS. 
And I imagine since Javascript only has limited access to the OS - probably even with Chromium and other browsers? - the timezone, is in fact taken from the browser, no?

But you are correct in pointing out that without any extra privacy plugins or settings in the browser, per default browsers will have the same timezone as the OS.

**Comment by dartcafe** [comment]
Of course js gets it's timezone information from the browser. But the browser takes it from the OS, where the timezone is defined. And usual browsers do not offer changing the timezone. I just wanted to clarify, that the definition of the timezone is controlled by the client and not by the server, nextcloud or the app.
