### ISSUE TITLE
Poll admin should see all participants personal links

### ISSUE THREAD

**Issue by forestmountain** [nextcloud/polls#1251]
If a participant (without login) closes the poll and didn't copy the personal link and later needs to re-enter the poll, that participant is out of luck re-entering the poll.

Poll creator (admin) should be able to see all personal links of the participants and be able to send the link to a participant on demand.

**Comment by dartcafe** [comment]
like this?
![grafik](https://user-images.githubusercontent.com/26707476/99904638-6981d900-2ccc-11eb-81d5-efad9ff9323c.png)

**Comment by forestmountain** [comment]
Yep. In a poll the participants are listed with their poll contribution - a menu could be available next to the name. If the mail of a participant is known a "Resend personal link" would give very much meaning and 'Copy link to clipboard' if admin is to send the personal link outside Nextcloud.

**Comment by dartcafe** [comment]
What I wanted to say: This is the current implementation. The menu entry is named acording to it's action: Resend invitation mail. Additionally an external user gets his invitation mail after he enters his email address when registering to the poll. So I think we can close this.

**Comment by forestmountain** [comment]
Not so. Your screenshot assumes participants are Nextcloud users with a login. But public polls participants can be non-Nextcloud users that do not have a login. They do not appear anywhere other than when they have contributed with poll answers. If they close the poll window in their browser they can not ask for a re-send of personal link and hence can not edit their poll answers. Hope you get my point.

**Comment by dartcafe** [comment]
It works the same way for public users (except the fixed error in #1252, when the external user didn't provide an email address). Will be fixed in the next version (1.6.3 or 1.7.x).

**Comment by dartcafe** [comment]
![grafik](https://user-images.githubusercontent.com/26707476/99915783-06ad3380-2d06-11eb-8ae7-b21fb3f2d782.png)

**Comment by forestmountain** [comment]
Ah, exactly my case, I'm in the situation in #1252 - participants are not listed in shares list, they have not received an invitation send out from Nextcloud - but did receive the poll link through other means (standard email/SMS/chat etc). and they have not provided any mail address at the poll.

Will wait for fix. OK to close this.

**Comment by dartcafe** [comment]
I published a new version 1.6.3: https://github.com/nextcloud/polls/releases/tag/v1.6.3
You can download this package here for manual installation: https://github.com/nextcloud/polls/releases/download/v1.6.3/polls-1.6.3.zip

@v1r0x If you mind, you can bring it to the appstore: tag `v1.6.3`
