### ISSUE TITLE
Link to poll in activity notification mail is broken

### ISSUE THREAD

**Issue by Findus23** [nextcloud/polls#1255]
### What is going wrong?
This is quite minor, but I have been noticing it for a while now, so I thought I might as well report it here:

The Link in the notification E-Mail "Zur Umfrage gehen" (open the poll) links to `/index.php/apps/polls/vote/26` while the web UI only works when visiting `/apps/polls/vote/26`

**To Reproduce**
1. create a poll
2. subscribe to notifications
2. wait until someone interacts with the poll
4. get a notification E-Mail informing you about this activity
5. click on the huge button
6. notice you don't see the poll, but just an empty page with the sidebar
7. select the poll the normal way and notice that the URL differes from the one in the mail

**Expected behavior**

The notification link should go to the poll

### Information about your polls installation
**Polls version?**: 1.6.2
**Fresh installation or update from a prior version (from which one)?**: I I have been using the app for a long time and many versions

**How did you install this version?(Appstore or describe installation)**: Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** 20.0.2

**List of activated apps:**
<details>
<summary>in case it helps</summary>

```text
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - integration_moodle: 0.0.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.6.2
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.9
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - carnet
  - cookbook
  - deck
  - encryption
  - end_to_end_encryption
  - files_external
  - files_fulltextsearch
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - phonetrack
  - sentry
  - socialsharing_email
  - spreed
  - support
  - suspicious_login
  - twofactor_gateway
  - user_ldap
  - workflow_pdf_converter
```

</details>

**Nextcloud configuration:**

<details>

```json
{
  "system": {
    "trusted_domains": [
      "cloud.mydomain.example"
    ],
    "overwrite.cli.url": "https:\/\/cloud.mydomain.example",
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "dbport": "",
    "dbtableprefix": "oc_",
    "installed": true,
    "mail_smtpmode": "smtp",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "sentry.minimum.log.level": 0,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
      "port": 6379,
      "dbindex": 8
    },
    "updater.release.channel": "stable",
    "twofactor_enforced": "false",
    "mysql.utf8mb4": true,
    "mail_sendmailmode": "smtp",
    "enabledPreviewProviders": [
      "OC\\Preview\\PNG",
      "OC\\Preview\\JPEG",
      "OC\\Preview\\GIF",
      "OC\\Preview\\HEIC",
      "OC\\Preview\\BMP",
      "OC\\Preview\\XBitmap",
      "OC\\Preview\\MP3",
      "OC\\Preview\\TXT",
      "OC\\Preview\\MarkDown",
      "OC\\Preview\\PDF",
      "OC\\Preview\\OpenDocument"
    ],
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
      "polls",
      "calendar",
      "contacts"
    ],
    "trashbin_retention_obligation": "30, 180"
  }
}
```
</details>

### Server configuration

**Database:** mysql 10.3.25

**PHP version:** 7.3.19-1~deb10u1

**Web server:** Nginx

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Device:** Desktop

**Browser:** Firefox 83

#### Nextcloud log (data/nextcloud.log)

nothing related in the log

#### Browser log
nothing different on the broken page

**Comment by dartcafe** [comment]
See discussion in #945 and possibly #891. 
Especially look for your CLI configuration, because the notifications are sent out via cron. Invitations are sent out using the user sesssion.

**Comment by Findus23** [comment]
Sorry for not checking for other issues before, I didn't expect this to be such a setup-specific issue.
I guess the difference to #945 is that I use nginx and therefore don't use .htaccess files

I see now that https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html has a different nginx config than back when I set it up, so I'll look into that first.

**Comment by dartcafe** [comment]
@Findus23 Were you able to solve the problem? If yes, a short explanation would be good, to help users with the same problem.

**Comment by maxemann96** [comment]
We are facing the same issue with our nextcloud instance. Nextcloud Version: 20.0.3. Polls Version: 1.6.2. Deployed with docker with nextcloud-fpm and nginx. We updated our nginx.conf to the latest available at https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html but this does not solve the issue.

**Comment by dartcafe** [comment]
This seems to be a problem in the CLI configuration. The notification is not sent out via user session, but via cron. So the web server setting should not influence that.

**Comment by maxemann96** [comment]
We have the following [proxy configuration](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations):
```
overwritehost = NOT_SET
overwriteprotocol = https
overwritewebroot = NOT_SET
overwritecondaddr = NOT_SET
overwrite.cli.url = https://nextcloud.apps.domain.tld
htaccess.RewriteBase = NOT_SET
htaccess.IgnoreFrontController = NOT_SET
proxy = NOT_SET
proxyuserpwd = NOT_SET
proxyexclude = NOT_SET
allow_local_remote_servers = NOT_SET
```

I changed the configuration now to 
```
overwritehost = nextcloud.apps.domain.tld
overwriteprotocol = https
overwritewebroot = /
overwritecondaddr = NOT_SET
overwrite.cli.url = https://nextcloud.apps.domain.tld
htaccess.RewriteBase = NOT_SET
htaccess.IgnoreFrontController = NOT_SET
proxy = NOT_SET
proxyuserpwd = NOT_SET
proxyexclude = NOT_SET
allow_local_remote_servers = NOT_SET
```

Our nextcloud is available at https://nextcloud..apps.domain.tld. Both configs are producing Mails with the `index.php` in the url. If it is of interest: Our Nextcloud cron task is triggered with cron.

**Comment by dartcafe** [comment]
> If it is of interest: Our Nextcloud cron task is triggered with cron.

That's it. I am using webcron and the URLs are correct. I tried to call the background jobs via CLI and the index.php is present. But in the end, it should work with index.php in the URL. I will check this next year.

**Comment by maxemann96** [comment]
On Frontend site the xhr request to get the poll is never requested if index.php is in the url. Further investigation turns out, that the page is also empty (the polls skeleton is there, but the right is empty) on `https://nextcloud.apps.domain.tld/index.php/apps/polls/`. I think this is because the vue router has another base url which does not include the `index.php` and as a result can't find any suitable page. [Link to Code](https://github.com/nextcloud/polls/blob/master/src/js/router.js#L38).

**Comment by Findus23** [comment]
Hi,

Sorry I didn't get back to you. I updated the nginx config, but it didn't change anything and the bug isn't that severe that I am not okay with clicking one additional time.

Indeed I am also not using webcron, but a cronjob triggering php-cli.

**Comment by dartcafe** [comment]
@kesselb It seems, that url generated via the urlGenerator are build in a different way, if they are generated via cron called CLI (ignoring the settings for clean URLs) than if they are generated via a websession. Any idea, how to solve that?

**Comment by dartcafe** [comment]
Aditionally: `overwrite.cli.url` is set, but it seems to have no effect on removing of `index.php`.

**Comment by dartcafe** [comment]
Adding `'htaccess.IgnoreFrontController' => true`, to the configuration produces URLs without index.php, when generating notifications via cron. But to be honest, I don't know what other side effects can accour.

See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html

**Comment by dartcafe** [comment]
> I think this is because the vue router has another base url which does not include the `index.php` and as a result can't find any suitable page.

Yes right, because polls uses the information about the correct root url it requests from NC. And when the page is called, NC reports the rewritten URL without index.php. 

But what confuses me, is that the navigation is created correctly regardles if index.php in the URL is present or not, but the votes page is not. I will fix the routings later with another approach of building the app.

**Comment by maxemann96** [comment]
A small bump for the stale bot, nothing else

**Comment by dartcafe** [comment]
> 
> 
> A small bump for the stale bot, nothing else

Why? There is nothing what could be done in polls to solve this. Or did I miss something?

**Comment by maxemann96** [comment]
> > I think this is because the vue router has another base url which does not include the `index.php` and as a result can't find any suitable page.
> 
> Yes right, because polls uses the information about the correct root url it requests from NC. And when the page is called, NC reports the rewritten URL without index.php.
> 
> But what confuses me, is that the navigation is created correctly regardles if index.php in the URL is present or not, but the votes page is not. I will fix the routings later with another approach of building the app.

I thought you wanted to check the routings? But if this cannot be fixed here, I can open a ticket at nextcloud/server if this cannot solve the problem.

**Comment by dartcafe** [comment]
The problem, that the index.php is inserted while generating the notifications via cron must be a configuratoin task or a bug in the server app. 

What I am targeting, ist the fact, that the app should be loaded, although the index.php is present. But I have to investigate and will go in this, when I will work on the app routings. But this has low priority. This issue here can be closed, the topc is missleading. 

Actually I was confused about the topic, while I answered yesterday. 😬

**Comment by maxemann96** [comment]
Thanks for the explanation :)
I will do some further research of the problem source and open a pr here or an issue at nextcloud/server

**Comment by rubo77** [comment]
Any news on this? it seems, I just opened a similar issue 1902

**Comment by dartcafe** [comment]
No. As I said above: low priority
