### ISSUE TITLE
Poll summary is wrong

### ISSUE THREAD

**Issue by karlbnapf** [nextcloud/polls#1256]
### What is going wrong?

Sum of votes is wrong in text-based polls. In the screenshots below, the last option ("Donnerstag") should display 6 (2) votes instead of 9 (2). Error occurs in both desktop and mobile view.

**Screenshots**

![image](https://user-images.githubusercontent.com/21277531/100137710-2884f280-2e8d-11eb-82d7-e96ffc250879.png)

![image](https://user-images.githubusercontent.com/21277531/100137780-43576700-2e8d-11eb-9d35-4ca1d8c0dcb8.png)

**Polls version?** (see apps page)

1.6.2

**Fresh installation or update from a prior version (from which one)?**

Update from previous version

**How did you install this version?(Appstore or describe installation)**

App store

### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)

19.0.3

**Comment by dartcafe** [comment]
@karlbnapf I need some more information:
* Does that also happen in other text polls?
* Is this issue limited to text polls?
* Can you get a dump of the tables oc_options and oc_votes (maybe limited to the poll above)?
  You can send it via email (you find my email address is in my profile)

**Comment by karlbnapf** [comment]
Thanks for the quick response!

> * Does that also happen in other text polls?

I tried to reproduce the problem with a simple poll (2 options, 3 users) but without success.

> * Is this issue limited to text polls?

So far, I haven't observed a problem for date-based polls.

> * Can you get a dump of the tables `oc_polls_options` and `oc_polls_votes` (maybe limited to the poll above)?

Unfortunately, I cannot access the tables since I'm using a hosted instance of Nextcloud without SSH access.

Please let me know if there is anything else I can do.

**Comment by dartcafe** [comment]
> > * Does that also happen in other text polls?
> 
> I tried to reproduce the problem with a simple poll (2 options, 3 users) but without success.

So it seems to be limited to a single poll. 
 
> > * Can you get a dump of the tables `oc_polls_options` and `oc_polls_votes` (maybe limited to the poll above)?
> 
> Unfortunately, I cannot access the tables since I'm using a hosted instance of Nextcloud without SSH access.
Under normal circumstances, you should have acces to the databases even with shared hosts via phpMyAdmin or similar. 

I guess there are some hidden votes, which got counted but not displayed. But I wonder, how this could happen. 

> 
> Please let me know if there is anything else I can do.

You can try to get the options and votes via cURL and API call from your local console:
curl -u `username`:`password` -X GET https://`server`/apps/polls/api/v1.0/poll/`pollId`/votes
curl -u `username`:`password` -X GET https://`server`/apps/polls/api/v1.0/poll/`pollId`/options

By replacing username, password, server and pollId with your values.

**Comment by karlbnapf** [comment]
Attached you will find anonymized versions of the JSON files (couldn't find your mail address on the profile page; files zipped to be able to attach them). Note that there were a couple votes in the meantime, for which reason the above screenshots are not up to date anymore. However, the results are still wrong (partially). The problem seems to be related to User6 (multiple votes for the same option).

[poll.zip](https://github.com/nextcloud/polls/files/5598175/poll.zip)

**Comment by dartcafe** [comment]
Great. As I guessed, there are duplicates in the votes. This causes the count to fail. We have to make sure, the entries will be unique to avoid that.

**Comment by dartcafe** [comment]
We already have an issue, which addresses this task #856. I will close this one here.
