### ISSUE TITLE
branch nc-12: Internet Explorer and Safari: date polls show NaN instead of date

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#126]
Date polls show NaN instead of correct dates in Safari/Current.
Chrome and Firefox do not have this issue.
![nanpolls](https://cloud.githubusercontent.com/assets/6523646/25785222/6afed22c-337b-11e7-8a57-87263dac2859.png)

**Comment by joergmschulz** [comment]
looking in debugger, there seems to be a javascript error: 
![jsdebuggernan](https://cloud.githubusercontent.com/assets/6523646/26532109/28052ece-43f9-11e7-8ccb-c4fb982f7a24.png)

**Comment by Demoniac82** [comment]
The same thing seems to happen in Internet Explorer 11. MS Edge is not affected.

**Comment by dartcafe** [comment]
Maybe the PR will help.
https://github.com/v1r0x/polls/pull/138

**Comment by 4001982248998** [comment]
@dartcafe , commit 7018f56d5c8e0c461478489961360b948af2fd97 did it for me. Thanks!

**Comment by joergmschulz** [comment]
resolved in #148
