### ISSUE TITLE
Send E-Mail to all "unsent invitations" and further UI suggestions

### ISSUE THREAD

**Issue by martinbu** [nextcloud/polls#1268]
**Is your feature request related to a problem? Please describe.**
This is a follow-up of the feature request #902. Thank you @dartcafe  for the implementation of #902 it works great so far.
But I can't find an option to invite all not yet invited shares (unsent invitations). I have contact groups with a lot of contacts. With the #902 I can now search for them and add them to the pool. But with the current implementation I have to first click on resolve to individual shares and then invite every contact individually.

Additionally, after resolving contact groups to individual contacts the information of the contact group that was added is lost.

**Describe the solution you'd like**
It would be great if the following functionality could be added. What do you mean?

1. A Button to send an invocation email to all shares which are not invited via email yet
2. A Button to send a reminder Email to all shares which do not participate yet to the poll
3. Show which contacts already participated in sidebar
4. List contacts of contact groups as sub items of the group to keep the information which groups were invited (in both "unsent invitations" and "effective shares"). Add a Button to send an invocation mail the the whole group and to each single contact.

The numbers in the image corresponds to the numbered listing above
![image](https://user-images.githubusercontent.com/1791936/100495242-ca386800-3149-11eb-98f5-475fbfba2785.png)

**Comment by dartcafe** [comment]
> But I can't find an option to invite all not yet invited shares (unsent invitations).

I skipped it in the recent implementation, but there are plenty of good suggestions in your request. 

1. was planned 
2. needs some work, because currently there is no relation between shares and participants.
3. see 2.
4. Nice idea. But also some work, to get this done. 

I would suggest to split this into three requests (1, 2+3 and 4).

**Comment by martinbu** [comment]
Ok, should I then close this issue and open 3 separate issues? Or how you would like to continue?

**Comment by dartcafe** [comment]
> Ok, should I then close this issue and open 3 separate issues? Or how you would like to continue?

Would be good, I think. When we have the three issues, this one is no more needed but should be referenced. 

You can also leave this one for No. 1 and keep ist open. 
No. 3 is the leading aspect and No. 2 an additional feature to be developed together wit No. 3
No. 4 is the the last issue.

**Comment by martinbu** [comment]
Close this issue. It was split up to 3 separate issues: #1304  #1305 #1306

**Comment by dartcafe** [comment]
@martinbu Thanks!
