### ISSUE TITLE
Publish oC 9.0/9.1/10 app versions to marketplace.owncloud.com?

### ISSUE THREAD

**Issue by kdslkdsaldsal** [nextcloud/polls#128]
Hi,

the oC guys announced that the "old" apps.owncloud.com is now deprecated:

https://owncloud.org/blog/good-bye-apps-owncloud-com/

Even oC 9.0 and 9.1 users are advised to use the new marketplace which provides a backward compatible API. Are there any chances to get the 9.0 and 9.1 app versions from:

https://apps.owncloud.com/content/show.php/Polls?content=174671

published at the new marketplace as well?

Thanks.

**Comment by v1r0x** [comment]
Hi,

I think I'm going to publish it to the oc market as soon as #113 is fixed. I hope it works :wink:

**Comment by kdslkdsaldsal** [comment]
Ah, thanks. I saw #113 but that was only about Nextcloud and ownCloud 10/X.

But the older versions for 9.0 and 9.1 still could be published at the marketplace or is there any reason against this? (not quite sure if the 9.0 and 9.1 versions will also work on 10/X)

Thanks again for your reply.

**Comment by v1r0x** [comment]
Ah, so you are talking about the current version (0.7.2)? I release new versions to OC marketplace and nc app store as soon as #113 is fixed. Hopefully this week. Hope you can wait a couple more days for the release :smile:

**Comment by kdslkdsaldsal** [comment]
Ah, yes. Sorry 😃  I was talking about the 0.7.2 from https://apps.owncloud.com/content/show.php/Polls?content=174671. Wasn't sure if any new version is also compatible with older oC releases like 9.0 or 9.1, thats why i had created this issue/question here.

>  Hope you can wait a couple more days for the release.

Sure, absolutely no hurry. Just wanted to let you know about the deprecation of the old appstore. 😄

**Comment by v1r0x** [comment]
Tried to upload the app to the marketplace, but couldn't find any info how the format of the file should be....

**Comment by kdslkdsaldsal** [comment]
Hey, looks like https://github.com/owncloud/documentation/pull/3188 didn't made it to https://doc.owncloud.org/server/master/developer_manual/app/publishing.html yet.

However that didn't contain the file format which should be used. Just have checked a few apps already published and they are all using the .tar.gz file format.

**Comment by kdslkdsaldsal** [comment]
@v1r0x Hey, do you still need some help with this? I think @PVince81 @DeepDiver1975 or @hurradieweltgehtunter might be able to help / give additional info if there are any issues with uploading to the new marketplace.

**Comment by v1r0x** [comment]
Tried it a couple of times and couldn't find a solution. Any help would be good.

**Comment by hurradieweltgehtunter** [comment]
you rang? How can I be of your assistance?

**Comment by v1r0x** [comment]
https://marketplace.owncloud.com/apps/polls
