### ISSUE TITLE
Option not selectable

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/polls#1292]
Hey,

I created a poll with six options.

The first one now can't be selected. I had it selected and once I clicked on the checkbox as users started mentioning it can't be selecet I couldn't re-select it.

It's displayed differently, too.

It's a shame because this poll is about who receives the surplus of our nextcloud cloud and this is the entry that can't be selected:

![image](https://user-images.githubusercontent.com/71875177/102380238-f831ff00-3fc7-11eb-81c7-e4a9da89577d.png)

:)

Running Nextcloud 19.0.5 with Polls 1.6.2.
Any hints would be useful.
I'll try to add additional information if needed.

Cheers!

**Comment by dartcafe** [comment]
I guess, there is a duplicate in the db with the same option.

**Comment by hansimausisteffiwurstbrot** [comment]
> I guess, there is a duplicate in the db with the same option.

Hhhmm..  any way to fix it other than create a new poll?

Thanks for the hint!

**Comment by dartcafe** [comment]
Version 1.7 will fix that. The easiest solution is to delete the dubplicate in the db. But it is only a guess, that this is the problem.
