### ISSUE TITLE
No direct link in mailnotification

### ISSUE THREAD

**Issue by chillriver** [nextcloud/polls#1294]
**Is your feature request related to a problem? Please describe.**
First, people are invited to a poll with public link, but their are not registrated.
Next I am sending with mail the invitationlink.
Then after that, I will change the configuration.
Users who participated in the poll, they get a notificationmail with a Button for the link to the login page.
Users can not see the current changes by me, because they are not registrated.
They have to search the older mail with the public link.

**Describe the solution you'd like**
Maybe the invited people with public link, should possibly have a direct link in the notificationmail to the poll
 If not possible, notifycationmail by changing the settings should be switched off.

Is there any a solution for that problem?

**Comment by dartcafe** [comment]
Please provide some more information: 
* Polls version?
* Copy and paste the wrong link from the email here

>  Users who participated in the poll, they get a notificationmail with a Button for the link to the login page.

Nope, the button in the notification mail contains the personal link to the poll, not to the login page. If the login page is opened after klicking the link it seems, that the user got an internal link to the poll, where he must login first. So I need to see the link in the mail first.

**Comment by chillriver** [comment]
Nextcloud 19.0.5.
Polls Version 1.6.2

Link in mail who get the users:
https://xxx.de/index.php/apps/polls/vote/7

**Comment by dartcafe** [comment]
Thanks. Yes, that was a bug, resolved in #1205 and released in version 1.6.2. Maybe, the user got this notification before the update to this version. Or the link is from a registered user.

**Comment by chillriver** [comment]
Ok. Thank you for your answer. Means that not registrated users get another link in the mail as registrated users?

**Comment by dartcafe** [comment]
Yes . The registered user gets a link to the actual poll id like https://domain.tld/index.php/apps/polls/vote/7
A public user gets a personal share link like https://domain.tld/index.php/apps/polls/s/LD81AJzLzuSB4e3D after he registered with his name.
