### ISSUE TITLE
Participation state of invited users - reminder email

### ISSUE THREAD

**Issue by martinbu** [nextcloud/polls#1305]
This is part 2/3 of the issue #1268
It would be nice to be able to send a reminder email to all users that do not participated to the poll yet.

**Describe the solution you'd like**

1. Show the participation state of all invited users/contacts.
2. Add a functionality to send a reminder e-mail to all users/contacts that were invited to the poll, but did not participated yet.

![image](https://user-images.githubusercontent.com/1791936/102794888-4bcb9080-43ac-11eb-9929-3c47bdb57e0c.png)

**Comment by dartcafe** [comment]
Is this really necessary anymore, now that there is a auto reminder job?
