### ISSUE TITLE
Show all users in poll before the submitted an answer

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/polls#1308]
**Is your feature request related to a problem? Please describe.**
I want to check the attendance of all users in meetings with polls.

**Describe the solution you'd like**
If I select "for all users" it would be perfect to see all existing users. So I can check who haven't edit his attendance and therefore wasn't in the meeting. To top the experience a export feature from polls which can show all polls with all users

**Describe alternatives you've considered**
I tried to invite all users, but I only see users who already submitted.

**Comment by dartcafe** [comment]
I guess you are referring to this
![grafik](https://user-images.githubusercontent.com/26707476/103214075-ce55d200-490f-11eb-9512-13f26e70b8e5.png)

"all users" is an access setting. Listing all users would be heavy on systems with many users. 

But you can invite users via a group, then you have the invited users in the shares list. But you have to check manually, which user did not vote until #1305 is developed.

> To top the experience a export feature from polls which can show all polls with all users

Sounds like #366. This is still unresolved.

**Comment by Niclas-sol** [comment]
Listing all user in the poll which are in a specific group would solve my problem. It would be heavy on large systems, but if only a admin can check check it, this shouldn't be a big problem. Maybe with an optional checkbox/dropdown with "show all user", "show all users of group ...." and "show only invited".

**Comment by dartcafe** [comment]
I am not sure, If I get you right. 

* You are already able to invite a user group to a poll. 
* Tracking of participating is subject of #1305, which needs development. 

> Maybe with an optional checkbox/dropdown with "show all user", "show all users of group ...." and "show only invited".

I don't understand your request. Where do you expect this checkbox and what should it do?

**Comment by Niclas-sol** [comment]
Sorry my fault, I read over the #1305 issue 1.)
So this a duplicate of #1305 

Sorry for the confusion!

**Comment by dartcafe** [comment]
No reason for apologises. Glad the issue meets your expectation.
