### ISSUE TITLE
Allow users to edit the survey after submitting

### ISSUE THREAD

**Issue by gituser789** [nextcloud/polls#1311]
**Is your feature request related to a problem? Please describe.**
Some users fill in the poll, e.g. finding a meeting slot. On the next day, after filling the poll, the user recognized that he made a mistake when filling the poll. But it is not possible to edit the poll after submitting. 

**Describe the solution you'd like**
 - The user who opened the poll can allow in the poll setting if it is allowed to edit the survey after submitting
 - if editing is allowed, everyone can edit the poll (users with account, and also users without an account). In this case, the user who opened the poll has to trust his friends/colleagues, that they will not edit another profile.

**Describe alternatives you've considered**
An alternative is generating a new name, e.g. name2, but most users don't think about this option. An this is also not a good solution. So it would be very great if users can edit the poll after submitting

**Comment by dartcafe** [comment]
Changing poll is possible for internal users as long, as the poll is open. 

External users get a personal link, which allows editing their votes also, as long the poll is open. 

If they enter their email address, the link will be sent out via email. As a fallback, the owner can copy the personal link from the shares list and sent the link to the user manually. 

So there should be no reason, to open editing all votes for every user. Thsi would add configuration parameters ans increases the complexity of the app.
