### ISSUE TITLE
Public user gets error, after entering a username

### ISSUE THREAD

**Issue by pucicu** [nextcloud/polls#1314]
### What is going wrong?
**Describe the bug**
When non-subscribed user tries to enter a username, the message "Fehler beim Speichern des Benutzernamens" appears. Entering the poll not possible.

**To Reproduce**
1. Go to the public poll link
2. Click on "Nein, ich habe keine Anmeldedaten"
3. Enter the Username and enter the email address (both appear to be valid)
4. Click "ok"
5. Error appears

**Expected behavior**
Progress to the poll

### Information about your polls installation
**Polls version?** (see apps page)
1.6.2

**Fresh installation or update from a prior version (from which one)?**
Update from 1.5

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocgsnyb6gxi8',
  'passwordsalt' => 'd7PNppps0ZhIN/5Ial3jNNkzVrPYg7',
  'secret' => 'sBV6LevMPfkklJwBnu3pysnMiXThhzxO2qkiIAGpfq+N5yKd',
  'trusted_domains' => 
  array (
    0 => 'cloud.isaak.org',
  ),
  'datadirectory' => '/usr/www/users/isaaka/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '20.0.4.0',
  'overwrite.cli.url' => 'xxx',
  'dbname' => 'isaak_db',
  'dbhost' => 'xxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => 'xxx',
  'theme' => '',
  'loglevel' => 2,
);

```

### Server configuration

**Database:**
mysql

**PHP version:**
7.4

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Device:**
Desktop

**Browser:**
Firefox 84.0.1, Chrome 87.0.4280.88, Safari 14.0.2

#### Nextcloud log (data/nextcloud.log)
I can send it by email if really required.

**Comment by dartcafe** [comment]
Please use a more specific title for the issue. That helps other users with the same problem and avoid duplicates. I updated the title. 

There is a similar (or the same) issue described in #1271, but it a little bit hidden, so this issue is better for tracking the issue. 

Artifacts are uploadable here: https://nc.yagst.de/s/i8LrNyJRyAcjc72

A screenshot of the dialog, when the error message appears would help and or infomation about the entered user data (name and email address). Also any serverlog extract regarding the issue. 

Thanks in advance.

**Comment by pucicu** [comment]
Thanks for the hint! I found the problem: it was the missing smtp server. Now it works!
Perhaps a warning note for the admin would be good (when installing the polls app).

**Comment by dartcafe** [comment]
That would affect all apps sending out mails, so a special check on enabling the polls app is not valuable. But maybe we can catch the error less general (minor priority). Since we have other issues addressing that, we can keep this closed.
