### ISSUE TITLE
yellow bar 

### ISSUE THREAD

**Issue by himbeere** [nextcloud/polls#132]
Hello Devs.

Thanks for this beautiful app. May I ask you to change the yellow bar to a less bright color? I think this yellow is too much.

![bildschirmfoto 2017-07-18 um 16 22 11](https://user-images.githubusercontent.com/631865/28322101-7e1307b0-6bd5-11e7-9d20-53e5fbf5e6c0.png)

thanks and cheers

**Comment by v1r0x** [comment]
Thank You!
I try to find a lighter, but still visible yellow(ish) color

**Comment by himbeere** [comment]
Great. Maybe the yellow bar could contain question marks for the unmarked fields?

**Comment by azlux** [comment]
Maybe a "?"

**Comment by dartcafe** [comment]
I would vote for the use of icons.

Quick example: 
![grafik](https://user-images.githubusercontent.com/26707476/28694740-9587d332-732b-11e7-861b-a5ffc9252025.png)

**Comment by azlux** [comment]
3rth line, but with a "?" indeed of the pause sign.

**Comment by dartcafe** [comment]
But when I think about it, three status make no sense. I think yes or no, on or off are enough. The question is: "Dou you vote for a date or not?" A 'maybe' is like a 'no'.

**Comment by azlux** [comment]
Maybe is more like a "Yes, but I don't know if something else will be scheduled here"

**Comment by dartcafe** [comment]
In my opinion a maybe is not helpful for coordinating an appointment. This would miss the goal o the poll, where the pricipal wants to know, if an participant can take part or not. It could be optional.

**Comment by azlux** [comment]
What about an option to enable and diable the possibility to select the "maybe" option ?

**Comment by v1r0x** [comment]
I like the _maybe_-option in dudle. For me it's either maybe or "It's not my favorite slot, but it's ok".

**Comment by joergmschulz** [comment]
Before adding new functionalities, we should stabilize the current version / Internet Explorer and Safari should be able to display the date fields.

**Comment by v1r0x** [comment]
@joergmschulz Sounds good. For the next release I'll add a _?_ as indicator for maybe and look for a lighter/more visible color.

**Comment by dartcafe** [comment]
A suggestion
![grafik](https://user-images.githubusercontent.com/26707476/29994189-0498e6a2-8fca-11e7-861b-5db0b7321273.png)
