### ISSUE TITLE
l10n: Plural for voting

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/polls#1324]
If the number of votes is from 2 to 4, it should be noted that in other languages there may be a different form of the word "vote":

- Only %n **votes** per option are permitted.

e.g. as in Polish:

- _Dozwolone są_ tylko 2 **głosy** na opcję.
- _Dozwolonych jest_ tylko 5 **głosów** na opcję.

Where not only is votes a variation, but the sentence is structured differently for e.g. 2 votes than for 5 votes.

https://github.com/nextcloud/polls/blob/a3577c6cd3382f84816ffef930a177016848a632/src/js/components/Base/PollInformation.vue#L50

**Comment by dartcafe** [comment]
Interesting, I didn't know that. But I fear, this is is not solvable in polls. NC only diffentiates between single and multiple. @nickvergessen Is there a solution anywhere in other projects or in the core?

**Comment by Valdnet** [comment]
> NC only differentiates between single and multiple.

I understand. I changed the translation in Transifex for a "few" and "many" 😉.

This is a bit confusing for translators because a sentence for a single inflection is more extensive and also appears in "a few" and "many".

**Comment by dartcafe** [comment]
Then the information is lost, how many votes are allowed. Why not 

- Dozwolone są tylko/jest tylko 2 głosy na opcję and 
- Dozwolone są tylko/jest tylko 5 głosy na opcję?

**Comment by nickvergessen** [comment]
> Is there a solution anywhere in other projects or in the core?

In this case you could use a `t()` for the ==1 case and then an ordinary `n()` for the remainder

**Comment by dartcafe** [comment]
> In this case you could use a `t()` for the ==1 case and then an ordinary `n()` for the remainder

But this would not help to differentiate between 2, 3, 4 and greater... Or is there any trick, I don't know?

**Comment by nickvergessen** [comment]
Well it should, you only specify 2 versions because you only have 2 strings (n=1 and n!=1) but the translation system takes care of the rest, e.g. JA only has 1 form:
https://github.com/nextcloud/polls/blob/b89cbd7348fc7001830d2407d0acceedc07db38f/l10n/ja.js#L25
while CS has 4
https://github.com/nextcloud/server/blob/b5ba1dec5d7e6a9822185d76a5952244d0152051/core/l10n/ar.js#L120


The plural form is at the end of the file:
https://github.com/nextcloud/polls/blob/b89cbd7348fc7001830d2407d0acceedc07db38f/l10n/cs.js#L227

and Transifex takes care of it and expands the forms as necessary

**Comment by nickvergessen** [comment]
So as long as the full sentence is in the same translation function `n()` translators can do it all as they need.

See https://docs.nextcloud.com/server/20/developer_manual/basics/front-end/l10n.html for more info

**Comment by Valdnet** [comment]
> Then the information is lost, how many votes are allowed. Why not
> 
>     Dozwolone są/jest tylko 2 głosy/głosów na opcję and
>     Dozwolone są/jest tylko 5 głosy/głosów na opcję?

In my opinion, this is not very readable for the user and creates a mess unnecessarily 😉.

> But this would not help to differentiate between 2, 3, 4 and greater...

I think that the plural in some languages refers to the range: 2-4 and 5-∞.

In this particular case, it can be a bit confusing for translators, because as I mentioned earlier, the sentence for a single inflection differs a lot from the sentence for the plural.

**Comment by nickvergessen** [comment]
proposal in https://github.com/nextcloud/polls/pull/1327

**Comment by dartcafe** [comment]
> proposal in #1327

hmmm... But that still does not differentiate between 2, 3, 4 and so on.

**Comment by dartcafe** [comment]
> In my opinion, this is not very readable for the user and creates a mess unnecessarily 😉.

Was just a proposal for a compromise... ;-) 



> I think that the plural in some languages refers to the range: 2-4 and 5-∞.

Could you add some actual examples for ranges from 0-5?

**Comment by Valdnet** [comment]
> Could you add some actual examples for ranges from 0-5?

- Jest to głosowanie na wyłączność, w którym tylko jeden użytkownik może głosować na opcję.
  (Dozwolony jest tylko 1 głos na opcję.)
- Dozwolone są tylko 2 głosy na opcję.
- Dozwolone są tylko 3 głosy na opcję.
- Dozwolone są tylko 4 głosy na opcję.
- Dozwolonych jest tylko 5 głosów na opcję.
- Dozwolonych jest tylko 6 głosów na opcję.

I think the problem is more with Transifex. When translating with the plural the sentence for "few", "many" and "other" does not change, which is correct. On the other hand, if we start with the singular "1", the sentence does not change up to "many" either. It looks like this:
![obraz](https://user-images.githubusercontent.com/47037905/104051576-a35d5f00-51e8-11eb-8e90-552515d58dd3.png)
![obraz](https://user-images.githubusercontent.com/47037905/104051408-5ed1c380-51e8-11eb-851c-c994801f4f3e.png)
![obraz](https://user-images.githubusercontent.com/47037905/104051457-70b36680-51e8-11eb-8ea6-be5a58269d68.png)

In my opinion, Transifex should automatically switch to "other" when clicking on "few". But that would have to be reported to the Transifex developers.

**Comment by nickvergessen** [comment]
> hmmm... But that still does not differentiate between 2, 3, 4 and so on.

`n()` takes care of that. Its just you want 1 to be special and not use the 1,11,21,31... Rule of arabic e.g.

It does what you which for

**Comment by dartcafe** [comment]
> `n()` takes care of that. Its just you want 1 to be special and not use the 1,11,21,31... Rule of arabic e.g.

Oops. My fault, I - for some strange reason - didn't see your prior comments with your example references. 

> This is a bit confusing for translators because a sentence for a single inflection is more extensive and also appears in "few" and "many".

@Valdnet Now I understand, what is meant with few and many.

So the resulting strings are
https://github.com/nextcloud/polls/blob/32e2f84f1bce108e1fa2557168807cc32da4299e/l10n/pl.js#L65-L66

I think, it is correct!?

**Comment by dartcafe** [comment]
With current master: 
All limits set to 1: 
![grafik](https://user-images.githubusercontent.com/26707476/104087218-6d5ac200-525e-11eb-96f7-6e5ced9155f3.png)
Limits set to 2/3
![grafik](https://user-images.githubusercontent.com/26707476/104087234-8bc0bd80-525e-11eb-9d29-2d653377f6ac.png)
Limits set to 4/5
![grafik](https://user-images.githubusercontent.com/26707476/104087251-a1ce7e00-525e-11eb-89f7-ca5b04065b66.png)
Limits set to 8/9
![grafik](https://user-images.githubusercontent.com/26707476/104087274-c7f41e00-525e-11eb-9d25-4a368ed9a753.png)

**Comment by Valdnet** [comment]
> I think, it is correct!?

Yes, everything is fine 😉.

For all given limits, the translation is correct for the Polish language 👍.

**Comment by dartcafe** [comment]
@Valdnet Great, thanks. 

@nickvergessen Thank you for your proposal, but I think we don't need this. But this thread helped me a lot in better understanding of the translations. 🙏

**Comment by nickvergessen** [comment]
@dartcafe while it might work for the Polish language it will not work for e.g. japanese, korean and all versions of chinese (there are actually some more)

It only has 1 plural case:
https://github.com/nextcloud/polls/blob/b89cbd7348fc7001830d2407d0acceedc07db38f/l10n/ja.js#L142
Sample:
https://github.com/nextcloud/polls/blob/b89cbd7348fc7001830d2407d0acceedc07db38f/l10n/ja.js#L25
So they can not make the "1" case different (telling its unique) like you did in english.

**Comment by dartcafe** [comment]
Ah, yes. Now I see the point. Thanks for comming back to that. I will go the easy way!
