### ISSUE TITLE
Desktop mode: result overview dark mode inconsistency

### ISSUE THREAD

**Issue by baschi29** [nextcloud/polls#1338]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
While having the nextcloud dark mode activated, the results/votings from other users appear with a white background instead of a dark one.

**To Reproduce**
1. Enable dark mode in nextcloud settings
2. Open the desktop version of the result page

**Expected behavior**
The background should adjust to the dark mode.

**Screenshots**
![Screenshot_20210110-123800_1.jpg](https://user-images.githubusercontent.com/55055342/104121722-c26f0480-5340-11eb-9e05-a1b4d93a3660.jpg)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20
- Forms-Version: latest

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: Oneplus 7t
 - Browser Firefix Mobile

**Comment by jotoeri** [comment]
Seems to me like a polls issue, not forms... ;)

**Comment by dartcafe** [comment]
> 
> 
> Seems to me like a polls issue, not forms... ;)

indeed 😃
