### ISSUE TITLE
Breaking changes in Nextcloud 21

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/polls#1341]
Hi there,

I found that your app uses some classes of Nextcloud's third party libraries. Since an upgrade of those for php8 compatibility, your app will have to be adjusted as well. See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal for details. Your app uses `Doctrine\DBAL\Types\Type` which lost the old contants: https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md#deprecated-type-constants.

Cheers

**Comment by dartcafe** [comment]
Thanks for notification. We already removed `\Doctrine\DBAL\Types\Type` in the current branch and for the upcomming release. Does this mean, the current published release 1.6.3 will fail on NC21? 

Or with other words, is NC20 maximum requirement for 1.6.3 with PHP8?

**Comment by ChristophWurst** [comment]
> Does this mean, the current published release 1.6.3 will fail on NC21?

Depends which one. We merged the doctrin/dbal update just on Friday. Also there is a tiny update regarding types and public API: https://github.com/nextcloud/server/pull/25089

NC20 does *not* work with php8. Only 21 support it.

**Comment by ChristophWurst** [comment]
Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: https://github.com/nextcloud/server/pull/25089.

**Comment by dartcafe** [comment]
I think we have no risk here.  `\Doctrine\DBAL\Types\Type`  is already removed and NC20 is max number of the last release. 1.7 for NC21 will be out shortly (new beta comes in a few moments). I am running the NC-betas here for development and I had no issues recently.

ATM we need doctrine dependency just for capturing some exceptions.



> Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: [nextcloud/server#25089](https://github.com/nextcloud/server/pull/25089).

I will look at this later.

**Comment by ChristophWurst** [comment]
> ATM we need doctrine dependency just for capturing some exceptions.

Ah well, good that you mention it: https://github.com/nextcloud/server/pull/25091 :see_no_evil: 

Be sure to catch "our" exceptions now. If you wait for the Doctrine ones, you'll never catch anything.

**Comment by dartcafe** [comment]
If this is scheduled for NC21, I hope there will be one or two betas before to get a chance to test this.

**Comment by ChristophWurst** [comment]
It is. And we are already beta-ish (there is a small delay right now due to important feature work).

In that sense I must apologize that we do this change so late in the development cycle. Unfortunately php8 support is a bit latent and libraries are just being released now with compatibility fixes. That is why we couldn't do these changes earlier.
