### ISSUE TITLE
Link to poll in activity notification mail with (internal) IP adress

### ISSUE THREAD

**Issue by ratte-rizzo** [nextcloud/polls#1342]
### What is going wrong?
The email notification in case of an update in a poll contains a link to the poll with an IP adress instead of the domain. E.g. 
https://192.168.178.123/...
instead of:
https://mydomain.tld/...
Since the link with the IP adress is one in the private network, it works fine "at home" (or VPN), but not from the internet. 

**To Reproduce**
1. create a poll
2. put in an answer as registered or unregistered user (same result for both)
3. request email notification in case of more answers
4. put in an other answer
5. recieve email with wrong link

**Expected behavior**
A link to the poll with domain.tld should be in the link instead of the IP adress

### Information about your polls installation
**Polls version?** 1.6.3

**Fresh installation or update from a prior version (from which one)?**
Update from 1.6.2

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** 20.0.4

### Server configuration

**Database:** mysql 10.3.18

**PHP version:** 7.3.13

### Client configuration
**Device:** Desktop

**Browser:** Firefox

**Comment by dartcafe** [comment]
please check your CLI settings in the config.php. See #1255

**Comment by ratte-rizzo** [comment]
Thanks for the hint. 

Updated one line in `config.php`
`'overwrite.cli.url' => 'https://www.mydomain.tld/',`

Issue solved
