### ISSUE TITLE
Allow limiting the number of options that can be selected

### ISSUE THREAD

**Issue by valentinleistner** [nextcloud/polls#1345]
**Is your feature request related to a problem? Please describe.**
I would like to limit how many options participants in a poll are allowed/required to choose. This can be useful if e.g. two of four available options have to be chosen but noone should be able to choose more/less than that.

**Describe the solution you'd like**
Add a field for minimum and maximum selected options to the configuration panel. If a field is empty there is no limitation

**Comment by dartcafe** [comment]
See #738
