### ISSUE TITLE
1.7b2: user search broken

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1346]
With the latest beta adding users to a shared poll is no longer possible. In "Add Shares" the user list is empty and remains empty whatever is entered in the search field. We use a mix of AD usr and local usr. Polls 1.7b1 and NC 20.0.4 was working fine. With 1.7b2 and 20.0.5 the log is filled with the following:

![Screenshot 2021-01-15 at 07 58 05](https://user-images.githubusercontent.com/43957716/104692545-763d0f00-5708-11eb-94f0-04b8205f3a1d.png)

Is the Circles app a new requirement?

**Comment by dartcafe** [comment]
> Is the Circles app a new requirement?

That would be fatal. I didn't test this recently with diabled circles app. Thanks for reporting...
