### ISSUE TITLE
User should be able to change his choices in a public poll

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#135]
If an partiticipant of the poll has to change his choices, he can do this only as a logged in user. On a public poll, he should be able to enter his email address, where he can receive an unique link for his choices.

**Comment by keinkurt** [comment]
You can change your vote in a public poll, by typing the same name in the input field, make new choices and click on vote.

My proposition is to make all public votes editable by everyone by simple click an edit button on an user and after that editing the choices.

**Comment by dartcafe** [comment]
Thanks. Didn't see the possibility of repeating the name. 

But if anyone can edit every vote.... ?

**Comment by Mannshoch** [comment]
No problem with the option to edit every vote. I would like an Option between this one and an option to allow edit from same PC (cookie) or if the User could get an edit  Link after voting.

**Comment by xylo** [comment]
> You can change your vote in a public poll, by typing the same name in the input field, make new choices and click on vote.

Good to know that there is this workaround.  However, there are still two risks in this:
1) It's an undocumented feature, i.e. people that do not know it might accidentally overwrite the votes of another person. So the current state is a bit unsafe. There should be at least a warning and a user confirmation that these votes shall be overwritten.
2) If the user misspells his/her name when he/she wants to overwrite his/her votes then two rows exists that ATM nobody can delete, not even the admin.

Furthermore this solution of refilling all checkboxes is really time consuming.

**Comment by xylo** [comment]
@dartcafe 
Since there are several issues with the current solution (it's more a workaround), can we reopen this ticket please?

**Comment by UkeFan** [comment]
I agree. Have in mind that a good part of peole use Polls as an alternative for doodle – and therefore it was good to have a commonly known edit button. To make things as easy as possible
