### ISSUE TITLE
[1.7.2 beta3 ] Migration error when updating from 1.6.3

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1355]
@brtptrs Could you add your NC version and the used database (inkl. version). Also the corresponding logfile lines could help. 

--------
Trying to upgrade (on a test-system) from 1.6.3 to 1.7.2 beta3 failed with this error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_polls_log CHANGE `poll_id` poll_id INT DEFAULT 0 NOT NULL, CHANGE `user_id` user_id VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`, CHANGE `message_id` message_id VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`, CHANGE `message` message VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`':

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'message' at row 1
Update failed

Edit:
Thanks for the changes! Many of changes are will help us, a lot.

_Originally posted by @brtptrs in https://github.com/nextcloud/polls/issues/1319#issuecomment-762998003_

**Comment by brtptrs** [comment]
Nextcloud:        20.0.5
MariaDB:        10.3.25-MariaDB-0ubuntu0.20.04.1
PHP-Version:  7.4.14

[upgrade-error.log](https://github.com/nextcloud/polls/files/5842891/upgrade-error.log)

**Comment by dartcafe** [comment]
I will investige this in the following days.

**Comment by dartcafe** [comment]
I changed the migration. Could you use the attached file and replace polls (it is still version 1.7.2)? 
1. deactivate polls
2. replace app
3. activate polls

Polls should be usable then.

[polls-1.7.2-beta3b.zip](https://github.com/nextcloud/polls/files/5852266/polls-1.7.2-beta3b.zip)

**Comment by brtptrs** [comment]
Yes, that works!

**Comment by dartcafe** [comment]
Perfect! Thanks for testing.
