### ISSUE TITLE
Testing: 1.7.2 beta3 - copy participants is broken on nc 20.05

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/polls#1357]
NC 20.0.5
Polls 1.7.2 beta3b

### What is going wrong?
When trying to copy the list mail addresses of participants html is returned, instead of the mail info.

**To Reproduce**
1. Open a Poll
2. Click the copy-participants button at the end of the page

**Expected behavior**
List of mail addresses is copied to the clipboard

**Screenshots**

![grafik](https://user-images.githubusercontent.com/8102905/105467727-5ec8cd80-5c96-11eb-99e2-388962a1a00d.png)

The result html loaded in firefox

![grafik](https://user-images.githubusercontent.com/8102905/105468133-e9113180-5c96-11eb-85f6-6e4246a0558a.png)

**Comment by dartcafe** [comment]
I don't have a clue, what happens there. I checked this with different installations and configurations. 

Any log information? Console? NC log?

**Comment by brtptrs** [comment]
I don't see any related log entries. Will do some more testing later.

**Comment by dartcafe** [comment]
Waaaah, got it. I didn't test this properly. I didn't get this error message, but got this screen as result instead of the email addresses.
