### ISSUE TITLE
Release 1.7.4

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1371]
See: https://github.com/nextcloud/polls/releases/tag/v1.7.4
Download: https://github.com/nextcloud/polls/releases/download/v1.7.4/polls-1.7.4.zip

### New features since 1.6.x
 - Send invitations via notification app
 - Reload current poll every 30 seconds for updates
 - Admin users can delete and takeover polls from other users via new admin section
 - Respect autocompletion limitations from share settings for users, group and circle searches
 - Limit number of participants per option
 - Limit number of votes per participant
 - Combine registration dialogs into one dialog for public polls
 - Show closed polls in the relevant list until four days after closing date
 - Changed display of expiration timespan in polls overview
 - Support dark mode and dark theme
 - Compatible with Nextcloud 21
 - Drop support for Nextcloud before 19

### Bugfixes since 1.6.x
 - Linebreaks in description were ignored
 - Avoid concurrent long term user searches with a big user base
 - Speed up poll overview, by avoiding unnecessary loading of polls, the user is not allowed to see
 - Avoid duplicates in different tables
 - Invalid string text in the email

 See also https://github.com/nextcloud/polls/milestone/31?closed=1

**Comment by dartcafe** [comment]
@v1r0x Do you have time for an appstore release before NC21 release? NC21 is scheduled for 02/02/2021.

**Comment by v1r0x** [comment]
Just in time 😏 😅 

Thanks again @dartcafe !

**Comment by dartcafe** [comment]
> Just in time 😏 😅
> 
Lucky you. The appstore was down since yesterday. Thanks for immediately response!
