### ISSUE TITLE
Update failed An exception occurred while executing 'ALTER TABLE oc_polls_share

### ISSUE THREAD

**Issue by tacruc** [nextcloud/polls#1376]
### What is going wrong?
Update fails related to  #1375, but different error.

**To Reproduce**
1. php7 -f /srv/www/nextcloud/occ upgrade

**Screenshots**

### Information about your polls installation
**1.7.4

**Fresh installation or update from a prior version (from which one)?**
Previous version, but unknown

**How did you install this version?(Appstore or describe installation)**
appstore

**Database:**
mysql 10.4.17

**PHP version:**
7.4.6

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Nextcloud log (data/nextcloud.log)
```
Setting log level to debug
Updating database schema
Updated database
Updating <polls> ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_polls_share CHANGE `user_id` user_id VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`':

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 2
Update failed
Maintenance mode is kept active
Resetting log level
```

**Comment by c-store-cp** [comment]
Removing the polls folder in nextcloud/apps let you finish the upgrade and bring the instance back. However, polls can not be reenabled.

**Comment by tacruc** [comment]
Disabling the app has the same effect.

**Comment by dartcafe** [comment]
I think, we are through with this. feel free to reopen or start another issue, if this bug still affects you.
