### ISSUE TITLE
Polls gone after Upgrade 1.6.3 -> 1.7.4

### ISSUE THREAD

**Issue by quizilkend** [nextcloud/polls#1378]
Hey,
I upgraded polls from 1.6.3 to 1.7.4.
If I now open the polls app, all polls and votings are gone. Looking in the database, they are still there.

A look in the logs sees some warnings regarding deprecated Bootstrap stuff and a really long error message:

> {"reqId":"YBf1ix81E7i9fkFF1ci1VwAAAAE","level":3,"time":"February 01, 2021 12:35:26","remoteAddr":"2.206.180.120","user":"samu
el","app":"PHP","method":"GET","url":"/ocs/v2.php/search/providers/calendar/search?term=polls&from=%2Fsettings%2Fapps","messag
e":{"Exception":"Error","Message":"Undefined index: {http://owncloud.org/ns}owner-principal at /var/www/nextcloud/apps/dav/lib
/CalDAV/CalDavBackend.php#1789","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php","line":17
89,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined index: {http://owncloud.org/ns}owner-
principal","/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php",1789,{"principalUri":"principals/users/samuel","pattern":"polls","componentTypes":["VEVENT"],"searchProperties":["SUMMARY","LOCATION","DESCRIPTION","ATTENDEE","ORGANIZER","CATEGORIES"],"searchParameters":{"ATTENDEE":["CN"],"ORGANIZER":["CN"]},"options":{"limit":5,"offset":null},"escapePattern":true,"calendarObjectIdQuery":{"__class__":"OC\\DB\\QueryBuilder\\QueryBuilder"},"calendarOr":{"__class__":"OC\\DB\\QueryBuilder\\CompositeExpression"},"searchOr":{"__class__":"OC\\DB\\QueryBuilder\\CompositeExpression"}

This is not the end, but it seems like in this error message is some information about my calendars.

I know that this is rather unspecific, but I am willing to deliver more information, if someone has a clue, what the problem is.

Best regards!
Samuel

**Comment by dartcafe** [comment]
The error you quoted has nothing to do with polls. If you try to activate polls, you should find an error message on the apps page and in you log. I guess it is related to #1377 and #1376

**Comment by quizilkend** [comment]
Thanks for your fast reply.
Polls is activated but I can't find any polls related errors except this:

> {"reqId":"YBgDoeDOZjKoG52PkIKBFQAAAAY","level":0,"time":"February 01, 2021 13:35:29","remoteAddr":"2.206.180.120","user":"samuel","app":"files_sharing","method":"GET","url":"/ocs/v2.php/search/providers/talk-message-current/search?term=polls&from=%2Fsettings%2Fadmin%2Flogging","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.6.1"}
{"reqId":"YBgDoeDOZjKoG52PkIKBFQAAAAY","level":0,"time":"February 01, 2021 13:35:29","remoteAddr":"2.206.180.120","user":"samuel","app":"metadata","method":"GET","url":"/ocs/v2.php/search/providers/talk-message-current/search?term=polls&from=%2Fsettings%2Fadmin%2Flogging","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.6.1"}

If it is related to [1377](https://github.com/nextcloud/polls/issues/1377) and [1376](https://github.com/nextcloud/polls/issues/1376) should I just wait for the next point release?

**Comment by dartcafe** [comment]
Hmm. Also not related. But oviously, I didn't read your desciption correctly. Apologises for that.

What I understood so far: 
- you enabled polls
- your existing polls disappeared
- the polls and votes are still present in the db

Please check, 
- if you can find them in the administration section
- who is owner of the polls (check column owner in polls_polls)

Are you able to send me a dump of your tables? 
Upload it here, so I can inspect you issue https://nc.yagst.de/s/GpWbWDJ5DBqgN4t

**Comment by quizilkend** [comment]
Hey,
thanks for yout help.

Your guesses are correct.

* The polls are not present in the administration section of the polls app.
* Me and other nextcloud users are owners of the polls (but all seem valid)
* There are some errors, all of the same type:

> TypeError: t.list.filter is not a function
    filtered https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    fn https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    Ce https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    fn https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    r https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    xe https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    m https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    _render https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    r https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    get https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    run https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    An https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    ae https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    Xt https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    promise callback*Qt https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    ae https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    update https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    update https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    notify https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    set https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    set https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    A https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    commit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    commit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    _withCommit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    commit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    commit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    commit https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    load https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    promise callback*load https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    A https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    dispatch https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    dispatch https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    updatePolls https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
    reloadTimer https://balkonien.org/apps/polls/js/polls.js?v=a0b9ab48-25:2
polls.js:2:1770518

I uploaded a dump of the polls tables to your nextcloud.

**Comment by dartcafe** [comment]
For some strange reason, poll lists cannot be retrieved from the server correctly. 
Could you inspect the network tab in the developer tools and report the request from the url 
h**ps://yourserver/apps/polls/polls

Or you give me an account on your server, so I am able to inspect the issue by myself. 
BTW: the title of last poll (no. 29) looks strange to me. Maybe there is an encoding problem.

**Comment by dartcafe** [comment]
Are you able to enter the poll diretly via h**ps://yourserver/index.php/apps/polls/vote/29 or another of these polls?

**Comment by quizilkend** [comment]
Hey,
thanks again fpr your fast help! I really appreciate that.

The polls app works again with the 1.7.5 release  - Thank you!

Should I close this issue or do you want to investigate further?

* of course I could give you a test account on my instance
* The title uses unicode characters to display a word strikethrough
* Right now I am able again to see and interact with all the polls correctly

Best regards!
Samuel

**Comment by dartcafe** [comment]
OK. Then the js app was not loaded properly in your browser, because the fix in 1.7.5 addresses another issue, which didn't affect you. Great that it works again.
