### ISSUE TITLE
Bugfix release 1.7.5

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1381]
See: https://github.com/nextcloud/polls/releases/tag/v1.7.5
Download: https://github.com/nextcloud/polls/releases/download/v1.7.5/polls-1.7.5.zip

## [1.7.5 - bugfix release] - 2021-02-01
  - [fix] #1374 - fix uniqueContraintsException when shifting dates (backport)
  - [fix] #1380 - remove invalid shares before migration (backport)

**Comment by dartcafe** [comment]
addressing #1377 and #1376

**Comment by dartcafe** [comment]
@v1r0x appstore release??? 🙏 🥰 
Seems some other people are involved, due to an (I believe) old bug

**Comment by v1r0x** [comment]
New version is released to the appstore. @dartcafe thank you for your quick fixes!

**Comment by dartcafe** [comment]
> New version is released to the appstore

Cool. Thanks!!
