### ISSUE TITLE
Integration with Appointments app

### ISSUE THREAD

**Issue by stefanoco** [nextcloud/polls#1384]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to effectively interact with my calendar(s) while creating and closing a poll. Same topics also discussed in #400, #411 and #121.

**Describe the solution you'd like**
Why not leveraging the existing [Appointments app](https://github.com/SergeyMosin/Appointments) for this? My idea for a use case:

1. when creating a poll a new type should exist "Appointment" where I'm asked to link to some existing Appointments App *page* (set of configurations, calendars etc)
2. I should be able to configure an interval in time (days) to be considered
3. (via API call) the new poll should get a list of slots resulting from the Appointment App *page* limited to the considered interval (in other words, as if I was looking for a slot in Appointment) and be configured accordingly when confirmed
4. (not sure if this is good or not) each time someone visits the poll page for voting the list of slots is dinamically updated with a new API call
5. once voting is done, the poll owner should be able to *reserve* by clicking the selected slot, and this should simply trigger an API call to Appointments App with a reservation request (see below for details on this call)

**Describe alternatives you've considered**
Replicating everything needed for an interaction with calendar(s) here in this app seems like a waste of time given that Appointments already does exactly this.

**Additional context**
Of course a couple of APIs and perhaps a few modifications are needed on Appointments, but the effort would be much lower than replicating similar functions here. For what I'm envisioning here, the needed modifications to Appointments App should be:
* an API call for getting available slots, given *page* and *interval* as parameters
* an API call for reserving a slot for multiple recipients, given *page*, *slot* and a list of *email addresses* as parameters

**Comment by dartcafe** [comment]
So your proposal is to use the appointments app to create calendar entries?

**Comment by stefanoco** [comment]
Basically yes, more specifically:

* Appointments already deals with calendars etc
* Poll should only query Appointments for detecting "options" when configuring a new poll

**Comment by dartcafe** [comment]
This means we depend on a third app to communicate with the calendar app. In other words, users have to install another app to use a feature of polls. Difficult to explain. 

But there are also other reasons against it
* the effort to implement an API to appointments is not less complex
* testing gets more complex
* debugging gets more difficult in case of errors
* polls would become a stakeholder and require features of the appointment app 
* polls has an impact of the information appointment handles
* we would depend on the progress and decisions made in the of appointments app
* errors in appointments have an effect for polls
* and a lot more

We will integrate the calendar natively, at last when the write access of calendar API will become available. See https://github.com/nextcloud/server/issues/20154

**Comment by stefanoco** [comment]
I understand the reasons against, I would also expect benefits from not reinventing the same framework twice on two plugins.

**Comment by dartcafe** [comment]
Thanks for your thoughts anayway. There is no reason to reinvent, that's what API are for. And the the source is open and so maybe can be reused. But an API behind an API is not a good solution IMHO. Too many dependencies.
