### ISSUE TITLE
Login loop at public polls

### ISSUE THREAD

**Issue by aendi123** [nextcloud/polls#1386]
**Describe the bug**
When I click the link of a public poll a window appears where you can login or type in a name and email. But when I click login and do a successful login (I can see my profile picture in the top right) the window where you can login or type in a name and email appears again. When I click cancel in the window I can't vote (I can see my previous answers). It works when I navigate to the poll via the NextCloud app bar polls --> relevant --> my poll.

**To Reproduce**
1. Create a new poll
2. Create a public share link
3. Open the poll via the public share link

**Expected behavior**
The window should go away after a successful login.

**Screenshots**
![Selection_222](https://user-images.githubusercontent.com/40163655/106799033-0c58bb00-665f-11eb-9c5c-453c5e458140.png)
![Selection_223](https://user-images.githubusercontent.com/40163655/106799054-11b60580-665f-11eb-825d-f9ae86f47da7.png)
![Selection_224](https://user-images.githubusercontent.com/40163655/106799065-14b0f600-665f-11eb-99af-75bf36c68b16.png)

**Polls version?** 
1.7.5

**Fresh installation or update from a prior version (from which one)?**
update from 1.7.4

**How did you install this version?(Appstore or describe installation)**
Appstore

**Nextcloud version:** (see Nextcloud admin page)
20.0.6

**List of activated apps:**
  - accessibility: 1.6.0
  - activity: 2.13.4
  - analytics: 3.2.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - checksum: 1.0.1
  - circles: 0.20.6
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.4
  - drawio: 0.9.8
  - extract: 1.3.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.1.0
  - groupfolders: 8.2.0
  - integration_moodle: 0.0.7
  - integration_reddit: 0.0.9
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.8.0
  - metadata: 0.12.0
  - music: 0.17.3
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ocr: 6.0.58
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.7.5
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_email: 2.1.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - unsplash: 1.2.1
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

**Nextcloud configuration:**
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "dbtype": "pgsql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "force_locale": "de_CH",
        "default_language": "de",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "app_install_overwrite": [
            "unsplash",
            "socialsharing_email",
            "ocr",
            "onlyoffice",
            "drawio",
            "circles",
            "checksum",
            "polls",
            "extract",
            "files_mindmap",
            "music",
            "mindmap_app"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "data-fingerprint": "b844d6f7417e7d5272c4029c43641a00",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

**Database:**
PostgreSQL

**PHP version:**
7.4.14

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Device:**
Same behaviour on every device

**Browser:**
Chrome, Firefox, Safari on iPhone

**Javascript console log**
2polls.js?v=0cacf8ad-14:2 RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at initials (polls.js?v=0cacf8ad-14:2)
    at bn.get (polls.js?v=0cacf8ad-14:2)
    at bn.evaluate (polls.js?v=0cacf8ad-14:2)
    at i.initials (polls.js?v=0cacf8ad-14:2)
    at i.<anonymous> (polls.js?v=0cacf8ad-14:2)
    at i.t._render (polls.js?v=0cacf8ad-14:2)
    at i.r (polls.js?v=0cacf8ad-14:2)
    at bn.get (polls.js?v=0cacf8ad-14:2)
    at bn.run (polls.js?v=0cacf8ad-14:2)

**Comment by dartcafe** [comment]
Oops, confirmed. The login and redirect to the poll preocedure does not work as expected. Will investigate and fix this. Thanks for reporting.

**Comment by dartcafe** [comment]
Seems that I fixed this accidentially, the current master works as expected. When I use a public link and do a login on a hidden poll, a new share is created for the user and the access is possible immediately. When, like in your case, it is an open/public poll for all users, the access is possible without creating a share.

**Comment by dartcafe** [comment]
Tested this issue again, no problems here. So I will close this. If it happens again, feel free to reopen or create a new issue. Thanks for support.
