### ISSUE TITLE
404 - poll not found

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1388]
NC 20.0.7, Polls 1.7.5, MariaDB 10.5.8

Registered users (shared) cannot participate. After login they get an err 404. The public poll is listed in the sidebar but cannot be opened.

![Screenshot 2021-02-04 at 10 14 02](https://user-images.githubusercontent.com/43957716/106873354-a9a20680-66d4-11eb-869e-a7af9b62894f.png)

In the log are entries like:
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_polls_preferences` (`user_id`) VALUES(?)' with params ["mustermann2"]: SQLSTATE[HY000]: General error: 1364 Field 'preferences' doesn't have a default value

Error happens with local and ldap usr base.

Public polls work (participation via link and without login).

**Comment by dartcafe** [comment]
It looks, as if a part of the migration did not execute, where preferences was set to allow NULL values. 

I added a commit in the stable-1.7 branch. Maybe you can patch or you replace the file in your installation with this one: https://github.com/nextcloud/polls/blob/fix-preferences/lib/Service/PreferencesService.php

**Comment by herrmannsdorfer** [comment]
That patch fixed the issue. Tx for the quick reply!

**Comment by dartcafe** [comment]
@herrmannsdorfer With the fix, I introduced another bug, which prevents saving the preferences. The latest commit fixes this. 

Sorry for inconvenience.
