### ISSUE TITLE
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'vote_option_text' at row 1

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1390]
Hello
I've tried to upgrade polls app yesterday and I've had an error similar to the one described in this issue that broke access to the nextcloud server.
I had to disable polls app in cli, to access my nextcloud server again.
Here is the error when I want to re enable polls app:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_polls_votes CHANGE `user_id` user_id VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`, CHANGE `vote_option_text` vote_option_text VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`': SQLSTATE[01000]: Warning: 1265 Data truncated for column 'vote_option_text' at row 1

What can I do to re enable this app?
Thanks for your answers

_Originally posted by @Benance in https://github.com/nextcloud/polls/issues/1377#issuecomment-773111712_

**Comment by dartcafe** [comment]
@Benance
please fill out the following questions, so I can learn about your environment.

=============================

### Information about your polls installation
**Polls version?** (see apps page)

**Fresh installation or update from a prior version (from which one)?**

**How did you install this version?(Appstore or describe installation)**

### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)

### Server configuration


**Database:**

**PHP version:**

### Logs

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by Benance** [comment]
> =============================
> ### Information about your polls installation
> 
> **Polls version?** 1.7.5
> 
> **update from version 1.6.3**
> 
> **How did you install this version?(Appstore or describe installation)** within the nextcloud apps web interface management
> ### Information about your Instance of Nextcloud
> 
> **Nextcloud version:** 20.0.4
> ### Server configuration
> 
> **Database:** mariadb  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
> 
> **PHP version:** 7.3

**Comment by dartcafe** [comment]
Are you ale to send me a dump of your `oc_polls_votes` table?
You can drop your fioles here: https://nc.yagst.de/s/GpWbWDJ5DBqgN4t

**Comment by Benance** [comment]
Hello
I've just dropped the oc_polls_votes table dump
thanks for your help

**Comment by dartcafe** [comment]
Yes, thanks. It was, what I suspected: The first record is invalid. Remove it and the exception shouldn't happen anymore.

**Comment by Benance** [comment]
ok, I've deleted the first row from the table oc_polls_votes, and I've been able to re enable the app from the apps management web interface.
Thanks again for your help.
regards
