### ISSUE TITLE
Main navigation should be removed, if the user is not logged on.

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#140]
When a non authorised user uses poll, the apps in the main navigation are still present and lead to the login screen. 

Should be done in the way, shared folders are displayed for non authorised users.

**Comment by v1r0x** [comment]
Had a look at other apps a while ago and back then they all their own layout. Is this still the case or has this changed in nc 12?
But nevertheless we should fix this 😉

**Comment by dartcafe** [comment]
The files app shows a good alternative.

**Comment by juliushaertl** [comment]
@v1r0x Current state is that every app ships its own template. I think we should really push forward on bringing a common template to the server: See https://github.com/nextcloud/server/issues/6553 for that

**Comment by v1r0x** [comment]
Thanks for opening an issue in server!

**Comment by dartcafe** [comment]
Temporarily the header elements are disabled via CSS. As this is targeted to NC 14 in core, we can close this and wait for a solution there.
