### ISSUE TITLE
Public poll nearly not usable on mobile phones

### ISSUE THREAD

**Issue by Porbi222** [nextcloud/polls#1400]
### What is going wrong?
Can not scroll inputpage to enter EMail or use the cancel or ok button. On smaller mobile phones, even the inputfield is not visible.

**Describe the bug**
When opening the poll on mobile phone, the input page is only partly visible. If the mobile has less resolution even the inputfield is not visible and it's not possible to enter a name. If ther resolution is big enough, the name can be entered but it's not possible to see the Cancel or OK button or enter an emailaddress, because the inputpage is not scrollable, instead the background page scrolls.
When clicking in the input field, with firefox the input field it hidden by the keyboard. On Chrome and Opera at least the inputfield is centered in the upper part of the display, so i see what i am typing and i can use the poll after pressing the enterbutton on the keyboard.

**To Reproduce**
open a link to a public poll on your mobile phone.

**Expected behavior**
The inputpage should be scrollable to move to the input field(s) and the buttons. Instead the Polls page scrolls.

**Screenshots**
see below

### Information about your polls installation
**Polls version?** 1.75

**Fresh installation or update from a prior version (from which one)?**
updated from 1.63

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud
Nextcloud on Raspberrypi 3B

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.7

![grafik](https://user-images.githubusercontent.com/78701105/107267625-73071b80-6a47-11eb-992e-d953348ea1f7.png)

On Opera:
![grafik](https://user-images.githubusercontent.com/78701105/107267018-9b424a80-6a46-11eb-8d16-3e215716d2a5.png)

On Firefox:
![grafik](https://user-images.githubusercontent.com/78701105/107266762-41418500-6a46-11eb-82a4-47ddff3f0fbe.png)

**Comment by Keyskeeper** [comment]
I think it's a very big issue.
If we want a real alternative to Doodle, anybody should be able to participate through a smartphone.
It's not possible at this time.
I made a poll to plan a meeting and 3 in 12 people were not able to pass the first screen because they were using a smartphone.
I know that you can pass the screen by validating with the keyboard without seeing the validate button but not anybody know they can do that.
I tried to figure out where it came from and it seems to be the modal-mask and modal-container classes but I'm not good enough to correct it myself.

**Comment by Porbi222** [comment]
As a quick and dirty workaround, i changed in src/js/components/Base/PublicReigsterModal.vue from:
![grafik](https://user-images.githubusercontent.com/78701105/108699396-7699a880-7505-11eb-9d33-fdfa667908a3.png)
to
![grafik](https://user-images.githubusercontent.com/78701105/108699416-7dc0b680-7505-11eb-8610-989b41c9588e.png)

recompiled and copied the changes to the polls folder on my Raspi.
This made it working for me on smartphones, but it look less 'good' on the PC (when having bigger window).

**Comment by Porbi222** [comment]
There is a semicolon missing at the end of line 280 above! Sorry!

**Comment by Keyskeeper** [comment]
Thanks ! I'll try it.
I will have to compile the scss file ?
Is this easy ? I didn't do such a thing since a while.

**Comment by Porbi222** [comment]
I checked out the 1.7.5 tag, changed these lines and started a make in the polls directory. According to the errors i had to install some packages but then it was easy to build (i used OpenSUSE tumbleweed for this).
