### ISSUE TITLE
Change registration layout

### ISSUE THREAD

**Issue by protist** [nextcloud/polls#1401]
**Is your feature request related to a problem? Please describe.**
I have a private instance of Nextcloud on my home server. I am the only user, and have prevented people from creating new accounts. However, public polls have a large button on the left saying "Do you want to login?". This is confusing, because even if others click `Login`, it is impossible for any of them to log in. When I share public polls, I have to tell people to ignore this confusing button, and use the field on the right instead.

**Describe the solution you'd like**
Have an option to disable this button.

**Describe alternatives you've considered**
Explicitly telling people to ignore this big button every time I share a public poll.

**Additional context**
As per the screenshot, the first item visitors see (on the left) is the option to login.

![image](https://user-images.githubusercontent.com/646668/107281458-d0ce4e80-6aad-11eb-964b-e69b7fee0a9d.png)

**Comment by dartcafe** [comment]
I would like to avoid more options for the poll settings, but maybe the order could be changed and (registering left and login right) and add some explanation below the login button.

**Comment by dartcafe** [comment]
resolve together with #1400

**Comment by protist** [comment]
> I would like to avoid more options for the poll settings, but maybe the order could be changed and (registering left and login right) and add some explanation below the login button.

That all sounds good, and I definitely agree with the proposed changes. However, I would have thought there would be strong argument for having the login button totally hidden? If it's a _public_ poll, wouldn't that imply many voters wouldn't be registered?

**Comment by dartcafe** [comment]
> If it's a _public_ poll, wouldn't that imply many voters wouldn't be registered?

We had an issue here (#1153), where a use case describes that the public polls are used for convenience reasons also for registered users. 

Unfortunately it results in #1386 (linked here to have these issues together).

**Comment by dartcafe** [comment]
Proposal:
![grafik](https://user-images.githubusercontent.com/26707476/109146991-cb872a00-7764-11eb-9688-3548a66477d8.png)

**Comment by protist** [comment]
Looks great! Thank you. I think the clarification on the right is perfect as well.
