### ISSUE TITLE
Notification email for public poll does not show the name and action

### ISSUE THREAD

**Issue by Porbi222** [nextcloud/polls#1423]
### What is going wrong?
**Describe the bug**
for (at least) public polls in the notification emails no action is written.

**To Reproduce**
1. create a public poll, enable email notification
2. wait until somebody did a vote
3. open notificationemail
4. no action is given in the email

**Expected behavior**
email should have action as before

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78701105/108516464-8d05f100-72c6-11eb-9133-3ce037043d5b.png)

**Just for Info:** i managed to get the action back by changing the === to == at line 270 in MailService.php but i am not very familiar with php, so i am not sure if this is the correct solution or just a workaround.

![grafik](https://user-images.githubusercontent.com/78701105/108517001-27663480-72c7-11eb-8798-5475ff63d8ed.png)

### Information about your polls installation
1.7.5

**Fresh installation or update from a prior version (from which one)?**
updated from 1.6.3

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)
20.0.7 on raspi

**Database:**
mariaDB 10.1.48
**PHP version:**
7.4

**Comment by dartcafe** [comment]
> i managed to get the action back by changing the === to == at line 270 in MailService.php but i am not very familiar with php, so i am not sure if this is the correct solution or just a workaround.

Close. Your solution pointed me to the right position. The types were different, so I forced the left hand property to integer.
