### ISSUE TITLE
Creator of public poll should be able to remove an user from poll

### ISSUE THREAD

**Issue by keinkurt** [nextcloud/polls#143]
If a users vote of a public poll is no more relevant, the polls creator should be able to remove this user from the poll.

**Comment by dartcafe** [comment]
I am not sure, if this is a good function, or if this should be reserved for an administrator. Can you add some user stories to that?

**Comment by dartcafe** [comment]
Since there is no relevant user story for that, I recomment closing this issue.

**Comment by RalfAlbers** [comment]
I would like to reopen this request.
I need this feature for public polls with unregistered users. The owner of the poll must be able to remove or modify a vote from an unregistered users.

**Comment by carlox97** [comment]
> Since there is no relevant user story for that, I recomment closing this issue.

I created a public poll to decide where to eat, sent the public link to my friends, they entered their names and voted.

Ofc anon decides to troll and votes 2 times. How can I remove his 2nd account so that he disappears from the results table? (Note: he joined via public link and doesn't have an account in my nexcloud)

**Comment by carlox97** [comment]
> > Since there is no relevant user story for that, I recomment closing this issue.
> 
> I created a public poll to decide where to eat, sent the public link to my friends, they entered their names and voted.
> 
> Ofc anon decides to troll and votes 2 times. How can I remove his 2nd account so that he disappears from the results table? (Note: he joined via public link and doesn't have an account in my nexcloud)

Solved
![solved](https://user-images.githubusercontent.com/31673755/145635171-9fcf86e1-98c0-4e53-81ff-400ac5e348ec.png)

@dartcafe amazing app, thanks.
