### ISSUE TITLE
Hide "user created..." details

### ISSUE THREAD

**Issue by heeplr** [nextcloud/polls#1430]
It would be nice, if the Message "`$username started this poll on $date, $time. The used time zone is $timezone.`" could be hidden.

I'm not sure which way would be best. I think a checkbox in the poll options could work.

**Comment by dartcafe** [comment]
Besides the fact, that the current solutions is rather ugly: Why would you want to remove it?

**Comment by heeplr** [comment]
For Layout/Design reasons basically.
When it's not needed, it distracts from the actual poll (especially elderly people in my experience).

**Comment by dartcafe** [comment]
Yes. I agree. I find it very distracting also. But I prefer a design than more configuration and removing it. Funny is, this is what I was starting yesterday.

**Comment by heeplr** [comment]
Don't get me wrong: I find it only distracting in some cases. When doing a lot of polls within a small group of regulars, it is very helpful to instantly see who created the poll and when. (The timezone might be less interesting but I suppose there's a reason for it).

Yes, too many configuration options are confusing, too. But I also like customization and I think it's better to challenge the pollster and not the participant. I think it might fit perfectly in the "experimental style" section where other layout aspects can be adjusted.

**Comment by heeplr** [comment]
It just came to my mind, that the ordinary "nextcloud way" to present details about creation would be to use the activity log, but I can see why those details should be embedded into the page. Designwise, I like how Wikipedia does it with its subtle "This page was last edited on 8 January 2021, at 14:30 (UTC)." message on the bottom of each page.

**Comment by dartcafe** [comment]
It's not just this text. In some situations, there is more text above and below the main content; the poll. The user has no focus. I will share a proposal, when I have the first mock.

**Comment by dartcafe** [comment]
see https://github.com/nextcloud/polls/pull/1443#issuecomment-787443850
