### ISSUE TITLE
Blank screen when reusing public link on same navigator

### ISSUE THREAD

**Issue by dmouly** [nextcloud/polls#1440]
### What is going wrong?
When someone receives a public link to a poll, doesn't correctly login or enter a name in the prompt field and closes the session, then they will receive a "blank screen" if they try to reuse the same link on the same navigator. By blank screen, I mean a screen without any login prompt, just header and footer info.

**To Reproduce**
1. Create a public poll
2. Create a public link
3. Have someone follow this public link on their navigator
4. Have them clik on login by mistake (left side of the prompt) and then cancel their login because they don't have an account
5. Have them close their session or tab
6. Have them open the public link again on the same navigator

**Expected behavior**
I would expect the user who has neither successfully logged in nor entered a name in the prompt field to receive another complete invitation to do it.

### Information about your polls installation
**Polls version?** (see apps page)
1.7.5
**Fresh installation or update from a prior version (from which one)?**
Fresh
**How did you install this version?(Appstore or describe installation)**
Appstore
### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)
21.0.0
**List of activated apps:**

**Nextcloud configuration:**<?php
$CONFIG = array (
  'instanceid' => '********',
  'passwordsalt' => '********',
  'secret' => '********',
  'trusted_domains' => 
  array (
    0 => '********',
  ),
  'datadirectory' => '/home/********/www/cloud/data',
  'dbtype' => 'mysql',
  'version' => '21.0.0.18',
  'overwrite.cli.url' => 'https://www.********/cloud',
  'dbname' => 'nextcloud',
  'dbhost' => '********.privatesql:35216',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '********',
  'dbpassword' => '********',
  'installed' => true,
  'mail_from_address' => '********',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '********',
  'mail_smtphost' => 'ex2.mail.ovh.net',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '********',
  'mail_smtppassword' => '********',
  'maintenance' => false,
);
### Server configuration

**Database:**
MariaDB 10.5.8
**PHP version:**
7.4.15
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**
Chrome
#### Nextcloud log (data/nextcloud.log)
Nothing in Nextcloud logs

**Comment by dartcafe** [comment]
Do you have any  logging information (console, server log)? I can't reproduce this. 
There is no reason (no conditions or something else) why the poll page should be empty, when using the same URL. 
Are you talking about the browser, when you say navigator?
Are the URLs exacly the same? With or without index.php?

**Comment by dmouly** [comment]
Hello, sorry for the delay, I just found your message when cleaning my spam folder.
I don't have any logs whatsoever.
I'll try to reproduce the problem and take notes about whether the url had index.php in it or not.
Yes, navigator=browser, sorry.
