### ISSUE TITLE
Can't enable polls app from master branch (self created)

### ISSUE THREAD

**Issue by Porbi222** [nextcloud/polls#1445]
### What is going wrong?
**Describe the bug**
When i try to enable the polls app on nextcloud 20.0.8.1 there is an exception

..."method":"POST","url":"/nextcloud/index.php/settings/apps/enable","message":{"Exception":"Exception","Message":"Too few arguments to function OCA\\Polls\\Migration\\RemoveIndices::__construct(), 0 passed in /srv/www/htdocs/nextcloud/lib/private/Repair.php on line 128 and exactly 1 expected","Code":0,"Trace":[{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/htdocs/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OCA\\Polls\\Migration\\RemoveIndices::__construct(), 0 passed in /srv/www/htdocs/nextcloud/lib/private/Repair.php on line 128 and exactly 1 expected","Code":0,"Trace":[{"file":"/srv/www/htdocs/nextcloud/lib/private/Repair.php","line":128,"function":"__construct","class":"OCA\\Polls\\Migration\\RemoveIndices","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/legacy/OC_App.php","line":1035,"function":"addStep","class":"OC\\Repair","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Installer.php","line":145,"function":"executeRepairSteps","class":"OC_App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/htdocs/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/htdocs/nextcloud/apps/polls/lib/Migration/RemoveIndices.php","Line":35},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"20.0.8.1"}

**To Reproduce**
1. clone master branch from github
2. make all
3. delete polls app in nextcloud 
3. copy files frome master branch to nextcloud apps directory
4. restart apache
5. try to enable
6. see error

**Expected behavior**
app should be enabled

**Screenshots**

### Information about your polls installation
1.8.0 (master branch)

**Fresh installation or update from a prior version (from which one)?**

**How did you install this version?(Appstore or describe installation)**
copy polls dir from build/source/ to nextcloud/apps 

### Information about your Instance of Nextcloud
20.0.8.1 on apache2 (openSUSE tumbleweed)

**Nextcloud version:** (see Nextcloud admin page)
20.0.8.1

**Database:**
sqlite3

**PHP version:**
7.4

**Comment by dartcafe** [comment]
See also #1402 and #1397
For some reason the dependency injection seems not to work with OC\DB\Connection in NC20. In NC21 it works. 

@ChristophWurst Sorry to bother you again. 
But do you have any idea how I can remove indices before the migration and recreate them afterwards via RepairStep? 

When injecting IDBConnenction (like in #1402) the migration works without any error, but the indices do not get removed or recreated. In NC21 the repairstep throws an error (see also #1402).

`[index] Error: Exception: OC\DB\SchemaWrapper::__construct(): Argument #1 ($connection) must be of type OC\DB\Connection, OC\DB\ConnectionAdapter given, called in /www/htdocs/nextcloud/apps/polls/lib/Migration/RemoveIndices.php on line 71 at <<closure>>
`

**Comment by ChristophWurst** [comment]
The problem is that you use two private implementations https://github.com/nextcloud/polls/blob/8e8ce349bfc5853081428caa8b71e88bf27be6a4/lib/Migration/RemoveIndices.php#L26-L27 and their constructor signature changed.

There is no clean nor official way to use this. The SchmaWrapper is not intended to constructed by an app. You could add some if-else logic based on the Nextcloud version and then pass the connection object or the interface depending on the version.

**Comment by dartcafe** [comment]
> The SchemaWrapper is not intended to constructed by an app.

Yes, that's what I guessed based on the comment of @jotoeri. The reason I chose the approach with the repair steps was https://github.com/nextcloud/server/issues/24711#issuecomment-751708893.

But oviously this does not work with NC20. 

Is there a chance to support schema changes with the repair steps officially in the future? 

Otherwise I am thinking about a version 2.0 for NC21 and up and a branch for up to NC20. there I can mange this with two migration steps.

**Comment by ChristophWurst** [comment]
> Is there a chance to support schema changes with the repair steps officially in the future?

Possibly. That always depends on whether someone adds this. Don't expect this to land if this is the only app that needs it.

> Otherwise I am thinking about a version 2.0 for NC21 and up and a branch for up to NC20. there I can mange this with two migration steps.

Sounds good and that is also the path many other apps take when there are breaking changes that make it impossible to support a wider range of Nextcloud versions.

**Comment by dartcafe** [comment]
@Porbi222 The current master (aka beta1) should do it's job now.

**Comment by Porbi222** [comment]
Thank you! I checked it (tag 1.8.0) on nextcloud 21.0 and 20.0.8, both are working as expected (including #1423)!
