### ISSUE TITLE
polls app is not official "featured"

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/polls#1448]
today i went through our installed apps and i saw that the app polls is not official "featured". 
(see also https://apps.nextcloud.com/?is_featured=true)

for me this was a supprise because this important app is a lot in use and also quite stable.
in my opionion this app would deserves it and i also really like what is comming soon with 1.8, especially https://github.com/nextcloud/polls/pull/1365 .

can we do something to bring this app into this state?

**Comment by dartcafe** [comment]
Thanks for your support. I don't know the criterias for a featured app. Maybe someone from the core team is able to tell.
