### ISSUE TITLE
uBlock filter

### ISSUE THREAD

**Issue by michel-thomas** [nextcloud/polls#1452]
### What is going wrong?
**Describe the bug**
uBlock filters some path (`##.public.share-item`). We can't access to public links already created.

With uBlock:
![image](https://user-images.githubusercontent.com/12149036/110100500-c6e4f600-7da2-11eb-99de-71c6af9d58bf.png)

Without uBlock:
![image](https://user-images.githubusercontent.com/12149036/110100547-d106f480-7da2-11eb-80b2-3b2d4743eedf.png)

**To Reproduce**
1. Install uBlock on your webbrowser
2. Share some polls
3. Look at public links
4. Links are not shown

### Information about your polls installation
**Polls version?**
1.7.5 on NC20.0.8

**Fresh installation or update from a prior version (from which one)?**
Update from long time (old time living NC)

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:**
20.0.8

### Server configuration
**Database:**
PostgreSQL

**PHP version:**
7.3

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Client.**
Mac

**Browser:**
Firefox with uBlock

**Comment by dartcafe** [comment]
Thanks for your report, and good for us to know that. 

But using blockers or other add-ons which change the content of a website always carry the risk, that wanted content gets blocked or disabled. I think it is an easy solution to disable uBlock on the nextcloud instance, where you are a member. Or configure an exception for the rule, if you do not trust the site.

**Comment by esprit-libre** [comment]
I know the workaround and this is not a problem for me, but we are not all tech users. Many web users install adblockers ([about 30%](https://www.socialmediatoday.com/news/global-ad-blocking-behavior-2019-infographic/551716/)) because web is nasty without it, but majority of them don't know how to configure or disable adblockers.

Up to you to correct or not, but I am sure that most would think this is a bug, or worst, they are not aware of these "hidden" functionality.

**Comment by dartcafe** [comment]
Maybe we will fix that, if this becomes a widespread problem. But it is hard to react to all dom manipulating or blocker add-ons and fix their behavior. Of course, we will have an eye on this and thanks for the hint. 

I am running a browser with uMatrix, uBlock Origin and privacy badger and cannot confirm this behavior. Maybe it depends on the consumed lists.

**Comment by esprit-libre** [comment]
This seems to be "esthetic filter"... I will ask more the user to confirm
