### ISSUE TITLE
l10n: Remove trailing blank from string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/polls#1464]
Such trailing blanks are hard to find at Transifex (at other translation platforms as well)

https://github.com/nextcloud/polls/blob/3a7c63657fe88195d0780d055514393adff1580e/src/js/components/Poll/PollInformation.vue#L34

There are some more. As soon as someone is correcting this in vue I can provide PR for other occurences.

**Comment by Valdnet** [comment]
Other text strings:
https://github.com/nextcloud/polls/blob/3a7c63657fe88195d0780d055514393adff1580e/src/js/components/Poll/PollInformation.vue#L40
https://github.com/nextcloud/polls/blob/3a7c63657fe88195d0780d055514393adff1580e/src/js/components/Poll/PollInformation.vue#L49

**Comment by dartcafe** [comment]
Searched for trailing spaces and removed them.

**Comment by rakekniven** [comment]
> Searched for trailing spaces and removed them.

Just seen your code changes. How do you add them now? Did I miss something

**Comment by dartcafe** [comment]
The removed spaces had no effect. The space before the mustache still exists and does its job. But I changed to the replacement option. I'm wondering, why I didn't use it at first place
