### ISSUE TITLE
Redesign of list UI

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#148]
I made some changes to the polls list, so it is more looking like the standard design. Orientation was the files app.
![polls_list](https://user-images.githubusercontent.com/26707476/30003643-ef916e08-90c0-11e7-8f36-a6bd1afac76d.png)
Comparing to the old design:
![poll_list_initial](https://user-images.githubusercontent.com/26707476/30003665-54f68922-90c1-11e7-9ee6-e69908b80ff0.png)

**Comment by v1r0x** [comment]
Very nice, looks much cleaner! Maybe you could have a look at #104, so _mayor_ UI changes are in one PR. Maybe we could also finish #104. :)

**Comment by dartcafe** [comment]
I looked at #104 and tried the branch, but I got server arrors, which I could not identify. That's why I asked @amittel, if he is working on it a few weeks ago (#103). And it is not easy for me to understand the changes, he made, since I am no programmer and not famliar with the nextcloud API. 

For the moment I am continuing with the UI optimazions locally. After that, we can try to adopt or continue with working on #104. 

So I played a little with the UI for myself. And by the way I am learning (Git, PHP, nextcloud API, ...).

**Comment by v1r0x** [comment]
Seems I missed your comment in #103, sorry!
Ok, keep going and have fun learning :) If you need anything, just mention me. Will have a look at #104 to figure out what's wrong.

**Comment by dartcafe** [comment]
I commited my changes so far. Not yet finished and I am still not happy with all of it, but curious about your thoughts and suggestions.

![bildschirmfoto vom 2017-09-05 um 20 20 42](https://user-images.githubusercontent.com/26707476/30075980-c9819dc4-9277-11e7-9e14-56d543a43762.png)
![bildschirmfoto vom 2017-09-05 um 20 21 07](https://user-images.githubusercontent.com/26707476/30075984-cd9e53de-9277-11e7-83ca-d69ed66a8891.png)
![bildschirmfoto vom 2017-09-05 um 20 20 49](https://user-images.githubusercontent.com/26707476/30075988-d0898c12-9277-11e7-9d2d-a3c0968617f5.png)

**Comment by joergmschulz** [comment]
clear, more intuitive, people who can't discern red&green are able to see the choices!
What about text polls? Do they work?

**Comment by dartcafe** [comment]
As far as I see, I have no issues. 
![bildschirmfoto vom 2017-09-05 um 20 38 27](https://user-images.githubusercontent.com/26707476/30076765-45d22aa4-927a-11e7-9c06-0868f20cdbf8.png)

**Comment by happyreacer** [comment]
It looks nice and i think the overfew is better, too.

**Comment by joergmschulz** [comment]
maybe a separator between the options would be helpful: when all is yellowish, the options can be found easier for very short headers on text polls (a, b, c, d, e...)

**Comment by v1r0x** [comment]
Really like the new UI. Great job!

**Comment by dartcafe** [comment]
Normaly in text polls the options are orderd vertically, not horizontally. Wouldn't this be better and more readable? 

Maybe vote and presentation of the result can be seperated. So the voting options can be rearranged, regardles of the partitipants. 

Date polls have a more coordinating meaning, which means, it helps to see the votes of others. In textpolls this maybe not that important. 

Understand what I mean?

**Comment by dartcafe** [comment]
I will try a few options the next days.

**Comment by joergmschulz** [comment]
Just quick-testing the release of today.
Generally I am amazed - looks good now!
Findings: 

- when a user wants to select a poll out of the list of polls, he must hit the text or description of the poll; clicks on the whitespace between the lines don't open the poll. Beginners will be confused.

-  description text for copy-to-clipboard: CTRL-c is not correct for apple Users. ENTER doesn't work, only 'ok' and CMD-C
- a date poll view display shows the 'NaN' error again, like #144 in Safari
<img width="539" alt="notanumber" src="https://user-images.githubusercontent.com/6523646/30128188-0200c98e-9342-11e7-9d99-962f3080ea36.png">

- the 'all' option is not visible in date polls, and it is visible but not clickable in text polls: 
<img width="206" alt="alle ist nicht klickbar" src="https://user-images.githubusercontent.com/6523646/30128543-58a976fe-9343-11e7-9119-a774a9ac7587.png">

- there are nice and fine horizontal lines between the rows, but no lines between the columns

Links seem to be working where I found them; notification emails didn't arrive but that may have local reasons

Keep on rocking!

If you wish I can do the same tomorrow night. The more testers we have the sooner you can publish your fine work!

**Comment by dartcafe** [comment]
Great. Thank you. I am not finished with the text polls right now. I will inspect your issues the next days. Have something to do in my other jobs. :-)

**Comment by dartcafe** [comment]
@v1r0x: Do you have an idea of calculating the right localized times without JS?

**Comment by dartcafe** [comment]
@joergmschulz 

> description text for copy-to-clipboard: CTRL-c is not correct for apple Users. ENTER doesn't work, only 'ok' and CMD-C

Didn't get you. Which functionality are you referring to?

**Comment by joergmschulz** [comment]
Well, on Apple keyboards it is CMD-C. And, the ENTER key didn't copy the text into the clipboard. Only the OK button and CMD-C.
<img width="793" alt="copytext" src="https://user-images.githubusercontent.com/6523646/30150913-908de8ec-93ad-11e7-9ee8-efdb523f2ec3.png">

**Comment by dartcafe** [comment]
Ah. OK. I will look after it.

**Comment by joergmschulz** [comment]
regarding the NaN - can't you reuse the fix https://github.com/nextcloud/polls/pull/138/commits/7018f56d5c8e0c461478489961360b948af2fd97 ?

**Comment by dartcafe** [comment]
@joergmschulz I'm getting mad with the different interpration of js date functions in the browsers. I need some time to test the compatibility. I think, I will go to it next week. Maybe I have time in the weekend.
Regarding your findings: 

- The poll should now be clickable via the whole table cell
- Ctrl-C of the description should be resolved in another way. I think the solution with a dialig is not very state of the art.
- The line you see is between two table bodies. I will play a little with the design in the weekend. We will see, what is possible. 
- For small columns I added another icon for unchecked votes as a small fix. Not very beautiful... 
![grafik](https://user-images.githubusercontent.com/26707476/30183449-c39b4bfe-941a-11e7-9bd4-169d9743ca0b.png)

**Comment by dartcafe** [comment]
A suggestion. @joergmschulz: What do you think?
![grafik](https://user-images.githubusercontent.com/26707476/30210299-59c81b6c-949c-11e7-9841-468915695a83.png)

**Comment by joergmschulz** [comment]
Honestly, I think this is unintuitive. Personally, I prefer the 'All' column.

**Comment by dartcafe** [comment]
Referring the toggle item, i agree. This solution is not intuitive. I prefer the solution, which states, that the action changes the row, of the current user. Reserving a complete cloumn for a row action is a waste of spare, especially, when we are on mobile devices. 

I will make some more inuitive suggestions for the toggle. I dislike this one, too. and in fact it is horribel to arrange divs inside a table cell. 

I wanted to know, if you were talking about a space between the cells like the way in the last picture. 

Can you confirm elimination of the date issue?

**Comment by joergmschulz** [comment]
Yes, a quick patch yesterday using your old fix fixed the date issue. I'll pull the state of the branch tonight (if I don't go mountaineering - else it takes me some days.)
And, yes, the space between the cells looks good.

**Comment by joergmschulz** [comment]
A walk-through showed no additional glitches; currently the behaviour seems to be consistent and functional using all my browsers including Safari, Chrome, Firefox on Macos and Edge and IE on W10K and Firefox /Android .
For small android screens (phone), firefox and Chromium fail to render the right menu options in the list - This might be out of scope.  I don't know whether it's a good idea to edit/modify polls with such a device anyway.
Talking about screen real estate: Why not leave away the clock at the left side / or add menu functionality to it?

**Comment by dartcafe** [comment]
What about this variant?
![grafik](https://user-images.githubusercontent.com/26707476/30335429-a65068b0-97e2-11e7-9f4d-8f76ed6ebe70.png)
Or this?
![grafik](https://user-images.githubusercontent.com/26707476/30335494-d3fb7b88-97e2-11e7-9229-b435a1262bd8.png)
Or the above one?

**Comment by v1r0x** [comment]
I like the one with rounded icons more. But the variant with colored background is my favorite.

**Comment by dartcafe** [comment]
I am not sure, which is my favorite. I like the round ones more too. But with wide options, I think the colored table cells makes it a little bit unsmoothy. 
![grafik](https://user-images.githubusercontent.com/26707476/30210299-59c81b6c-949c-11e7-9841-468915695a83.png)

In this variant the colors are not that "mighty"
![grafik](https://user-images.githubusercontent.com/26707476/30342149-0038c2da-97f9-11e7-96d2-e98e7e94fa45.png)

And again comparing to the border-radius: 20%;
![grafik](https://user-images.githubusercontent.com/26707476/30342213-4aefc882-97f9-11e7-8743-a2d5b5adb068.png)
Hmmmm... Some more opinions?

**Comment by happyreacer** [comment]
@dartcafe it is cool, too. I wish a option to have this or that design. ;-)

**Comment by dartcafe** [comment]
I try to make it configurable via css class. The recent commits first switched back to the default style. @v1r0x Is it possible to add a configurable switch in the per user settings?
![grafik](https://user-images.githubusercontent.com/26707476/30362733-a8ac2b28-985d-11e7-95ce-625132597a65.png)

There is still a bug with the create page, which I will fix later. 
@v1r0x Some bugs I found: 

- The "best score" doesn't work with text polls which have spaces in the text. Can you investigate?
- On the create page, the selecting of users/groups doesn't work properly. Maybe it should be disabled until it got fixed!?

**Comment by v1r0x** [comment]
We should have a good default instead of a configurable UI. Maybe @jancborchardt can help here :wink:

**Comment by v1r0x** [comment]
> @v1r0x Some bugs I found:
> 
>     The "best score" doesn't work with text polls which have spaces in the text. Can you investigate?
>     On the create page, the selecting of users/groups doesn't work properly. Maybe it should be disabled until it got fixed!?

is this a general problem or in your branch? If it is a general problem: Could you open an issue? Would be better to track further problems/progress there. Thanks!

**Comment by jancborchardt** [comment]
Yep, colored full background and icons are great. No configuration options as that is all stuff we need to test and will break.

@dartcafe great work! I will also test later, and add you to the Nextcloud design team. :) You are also very welcome in our #nextcloud-design IRC channel.

Also cc @nextcloud/designers for review.

**Comment by jancborchardt** [comment]
By the way, to really conform to Nextcloud design, the poll overview should be very much simplified as to which info is shown and put in the left navigation as a list.

Simply the name of the poll, and left of it an icon about the state (running, finished, etc) is enough. Then to the right the usual share / 3-dot-menu.
Look at how we do it in the Deck app and Calendar for example, that will also give you hints towards using h2 for a nice main text heading, and the right #app-sidebar for options. :)

**Comment by dartcafe** [comment]
Less configuration is less work and test of course, so I don't complain. I am almost satisfied with the current branch. Waitng for issues to plan. 

@jancborchardt You already added me to the desing team a few weeks ago. :-)

**Comment by dartcafe** [comment]
The app navigation is indeed a todo.

**Comment by jancborchardt** [comment]
@dartcafe yeah – my second comment about the navigation and sidebar is something for a separate pull request I’d say. :)

@dartcafe can you open a pull request for this? Then I’d say we can merge this, right @v1r0x?

**Comment by v1r0x** [comment]
If this PR doesn't introduce any bugs or unfinished stuff: yes. And after I had a look at it :wink:

**Comment by dartcafe** [comment]
@v1r0x What is your opinion. I changed the divs col-30 and col-70 from 

`.col-70 {
    width: 65%;
    float: left;
    padding: 0px 15px;
}`

`.col-30 {
    width: 35%;
    float: left;
    padding: 0px 15px;
}`
to 

`.col-70, .col-30 {
    float: left;
    padding: 0px 15px;
	min-width: 350px;
	max-width: 900px;
}
`
![grafik](https://user-images.githubusercontent.com/26707476/30399923-8faf4b00-98d5-11e7-8a69-068a616d8276.png)
or
![grafik](https://user-images.githubusercontent.com/26707476/30400042-f5618224-98d5-11e7-88a4-72e3f55bdd1b.png)

comparing to
![grafik](https://user-images.githubusercontent.com/26707476/30399716-edac4c0e-98d4-11e7-8698-4077cb13c2be.png)

**Comment by joergmschulz** [comment]
just walked through the current state of new-design. Amazing. This is something that should be released with a proper incrementation in the release#.

**Comment by DJCrashdummy** [comment]
just a small hint regarding the copy-url-topic if it is still valid...

> Ctrl-C of the description should be resolved in another way. I think the solution with a dialig is not very state of the art.

for a consistent UX maybe something like in the files-app (2 times) or in the  VideoCalls-app should used:
![dateien_-_testcloud](https://user-images.githubusercontent.com/26110463/30496867-0b3b0ed6-9a51-11e7-814c-5e2303aef510.png)
![admin_-_videoanrufe_-_testcloud](https://user-images.githubusercontent.com/26110463/30496884-1a71b058-9a51-11e7-9a8b-60bf07d842ca.png)

**Comment by v1r0x** [comment]
@dartcafe I think the layout of the second screenshot is my favorite. Wide table and comments. The last one looks very squeezed.

**Comment by jancborchardt** [comment]
Agree with @v1r0x the second layout is best. Also works best when you have a left navigation, and comments in the right sidebar (like in Files).

**Comment by skjnldsv** [comment]
Agreed too!
@dartcafe would you consider using flex? It would greatly increase the responsiveness of the app :)

**Comment by dartcafe** [comment]
@DJCrashdummy Just open a new issue with this suggestion.

**Comment by dartcafe** [comment]
For me, I have no more issues open regarding #151. If no more issues occur, I would like to merge #151 brand and close this issues. Any further comments, issues, suggestions?

**Comment by dartcafe** [comment]
@skjnldsv Referring to flex: I would like to see going away from the table layout to a flex or grid layout, at least for the vote page. The problem is, that grids are not supported by MS right now, and when, they will be supported by Edge, but not IE, as far as I understood. So flex would possibly be the best option.

**Comment by v1r0x** [comment]
@dartcafe Try to have a look at this PR again this weekend. Then we can merge it :)

**Comment by dartcafe** [comment]
@skjnldsv I tried to use flex, but the problem is, that it is nessecary to have dynamical height in rows and width in columns. I think, with grid it is possible, but I didn't find a way to have both with flex. Although I will try to build the overview with flex, because, we have a pure row layout.

**Comment by skjnldsv** [comment]
Do you need my help? :)

**Comment by dartcafe** [comment]
Not now, but if I go into it. I want to finish #151 first. I will call you. :-)

**Comment by jancborchardt** [comment]
@dartcafe what happened? Accidental close or is there a follow-up pull request? :)

**Comment by MorrisJobke** [comment]
> @dartcafe what happened? Accidental close or is there a follow-up pull request? :)

The PR was merged ;)

**Comment by dartcafe** [comment]
I think, I used the wron merge command. :-)

Follow up follows.

**Comment by jancborchardt** [comment]
Aaah I confused this as being the pull request. :D PR at https://github.com/nextcloud/polls/pull/151 of course
