### ISSUE TITLE
text field next to date

### ISSUE THREAD

**Issue by droogi** [nextcloud/polls#1485]
I have a choir and some dates for concert. 
I want to check if a person is able to come to the specific date.

So i would need a x-y table with x= date **(+ additional textfields e.g. location**) and y = person
every person should cross if he is able to come,  maybe or not.

i could do it with polls, but therefore i need an **textfield for each date** (1st march 2021, **concert in church**,)
Every person could enter its state.

should i do it with polls or do you recommend a different app?

**Comment by dartcafe** [comment]
ATM you can do this only with a text poll or you use the descriptoin field of the poll. A description field for date options is still an open request. #1125
