### ISSUE TITLE
Poll description is not completely visible

### ISSUE THREAD

**Issue by suparomana** [nextcloud/polls#1488]
### What is going wrong?
**Describe the bug**
The content in the field description (poll ->) will be not visible completely if the entered content is longer or has multiple lines. The description is wrapped in a `<h3>`-tag which has the following CSS `.description[data-v-71b1066d] {white-space: pre;}`

**To Reproduce**
1. open a Poll or create a new
2. open the configuration panel and select the descripton field
3. enter at least one longer sentence in there
4. close the config panel
5. reduce the width of the window till the content should wrap to the next line in the preview
6. the content will run beyond the container and will not wrap

**Expected behavior**
The entered content should always be completely visible to the user and should wrap if the window is to small to display everything in a single line. 

**Suggested Solution**
The easiest solution might be to change the CSS to: 
`.description[data-v-71b1066d] {white-space: pre-wrap;}`

### Information about your polls installation
**Polls version?** 1.7.5

### Information about your Instance of Nextcloud

**Nextcloud version:** 20.0.7

**Comment by dartcafe** [comment]
Thanks. This was already changed in one of the recent commits. 

https://github.com/nextcloud/polls/blob/7611442d6010b6227eee3fbbafc933dbe2fcfbae/src/js/views/Vote.vue#L335-L337
