### ISSUE TITLE
Results do not display number of answers per option

### ISSUE THREAD

**Issue by uka-support** [nextcloud/polls#1489]
### What is going wrong?
**Describe the bug**
When doing a simple poll, e.g. just one question, yes/no answer, there is no way to see the number of yes/no/maybe votes.

**To Reproduce**
1. create a simple poll (text poll)
2. add one question
3. have participants answer
4. see results

**Expected behavior**
I'm expecting the result to display the number of Yes/Nos per question.

**Screenshots**

![image](https://user-images.githubusercontent.com/6216577/111457454-811c1c00-8718-11eb-86f5-3958957d454b.png)

Try guessing how many said yes if there are 15 participants and you need an exact number.

### Information about your polls installation
**Polls version?** 
1.7.5

**Fresh installation or update from a prior version (from which one)?**
Fresh

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:**
20.0.0.8

**mockup of expected result**

![image](https://user-images.githubusercontent.com/6216577/111457841-0273ae80-8719-11eb-9f9e-6f740ad77c6f.png)

**Comment by dartcafe** [comment]
There is a way to see the numbers, if you switch to the table layout (desktop view). But I agree, we have to improve this. The caveat is the mobile usage, where the neccesary space could be a problem. We have to fiddle this out.
![mobile](https://user-images.githubusercontent.com/26707476/111513572-3c60a700-8751-11eb-9e7b-2b142aabf587.png)

**Comment by uka-support** [comment]
Ah, ok, thanks. It's called desktop view in my case, didn't think I had to switch view...

**Comment by dartcafe** [comment]
Since version 2.0.2 the display in the list view changed and the count is displayed instead of the bar (which oviously no one identified as counter 😉), i close this.
