### ISSUE TITLE
Polls 1.8.x not in Nextlcoud App Store

### ISSUE THREAD

**Issue by kosli** [nextcloud/polls#1504]
Is there a reason that the Polls 1.8.x releases are not (yet) in the Nextcloud [app store](https://apps.nextcloud.com/apps/polls)?

![image](https://user-images.githubusercontent.com/203928/112511438-b668df80-8d92-11eb-8d34-f5164c8056d3.png)

**Comment by dartcafe** [comment]
Yep. It's because @v1r0x has to do the release inside the appstore, I have no access. I guess this could be done this weekend. He was not available since last week. So just be patient, the release will come. Sorry for that.

**Comment by dartcafe** [comment]
See comment here: https://github.com/nextcloud/polls/issues/1470#issuecomment-806523417

**Comment by kosli** [comment]
Thanks @dartcafe All good, no stress. I missed the comment as I only looked at the [release tag](https://github.com/nextcloud/polls/releases/tag/1.8.1)
