### ISSUE TITLE
Database tables are not initialized

### ISSUE THREAD

**Issue by schroupie123** [nextcloud/polls#1505]
I've tried to reinstall the actual poll app in nextcloud 20. It was once installed in a previous version (nc 14), then removed.
No we are not able to create Polls.
I look into the mysql database showed, that there are no tables for the app, which where there when i try it out in a fresh docker-based installation of nc...

is there a way to force the reinitialization of those tables?

**Comment by dartcafe** [comment]
You have to remove the migration entries from the oc_migration table, witch relate to polls.
