### ISSUE TITLE
option to remove "registered user of this site" when invited to public participation

### ISSUE THREAD

**Issue by jasoncook-io** [nextcloud/polls#1518]
**some users don't bother reading before attempting to fill in form**
I host my Nextcloud server on a Raspberry Pi 4 with external ssd drive. I love it. But having some problems when inviting others to use this app. I have brute-force protection setup on my server (of course). My issue is specifically that in the public invitation link we give an option by default to allow users to login to the server. I am a teacher at an art school in France. The students often prefer less reading and typing when given a link like this. With this option being available I have noticed in mysql that some visitors are trying over and over to login. Brute-force protection kicks in and locks out the IP address for a given time. Since the IP address concerned is from the school, this means that all other students trying to access the link are also locked out.

**include option to remove login for registered users**
I have dug into the files myself hoping I could edit out the option for registered login. I believe the file containing this information is PublicRegisterModal.vue ... However I am not so good with web application builds. I understand that I can't simply access this file on the server after all is running. 

**suggestions welcome in the meantime**
If anyone has a suggestion for a quick fix I am willing to try. As a side note one thing I have noticed in the latest upgrade is that the option to login has now switched from the left side to the right side. This is already a good step as it would seem more intuitive to fill in prioritized information on the left side. But again, I think it would be best to have the option to remove it altogether.

**Comment by dartcafe** [comment]
An admin section is still a todo, but I guess, this will come with some minimal optins with the next version (2.0). Maybe we can toggle the login there. I will put this to the 2.0 milestone.

**Comment by PhrozenByte** [comment]
A quick solution could be as simple as adding an appconfig value that can be changed via `occ`, like many other apps do for not so commonly used options (e.g. Text to disable `README.md` editing).
