### ISSUE TITLE
Add feedback for users after vote clicks

### ISSUE THREAD

**Issue by mylaeus** [nextcloud/polls#1519]
**Is your feature request related to a problem? Please describe.**
In a public poll, the user does not see, that the changes he has made have been saved. People expect to click on a button when they have finished. As they don't see any button, they think, the changes haven't been saved. So we get lots of mails from people complaining, that they couldn't save their answers, although their answers have been saved.

**Describe alternatives you've considered**
There shold be a button added to end the work on the poll and leave the site, such as "Save changes" or "Leave th poll" / "Close the poll".

**Comment by dartcafe** [comment]
We removed this behavior long time ago and switched to instant persiting of any action. Sorry, but we will keep this behavior, until this is no widespread issue.

**Comment by mylaeus** [comment]
Well, that doesn't solve the problem users have. In Nextcloud, a message shows up that changes have been saved. It would be a good idea  to implement this in polls too.

**Comment by dartcafe** [comment]
So your user story would be: 
"As a user, I would like to have a feedback after a vote action, because I am unsure, that my vote was saved."

right?

**Comment by mylaeus** [comment]
Yes. My users who are used to other products like Doo... are used to click on a button to submit their vote. As they can't see anything like that they have the impression that it didn't work and report to me that my tool doesn't work. But when I look into the poll, I see, that the vote has been registrated.
