### ISSUE TITLE
Text polls with long text: Line break possible?

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#152]
reviewing #148 from @dartcafe , I had the idea to enter a long text for a text poll. This somewhat clutters the screen. Would it be possible to automatically line-break long texts after, for example, 30 characters?

**Comment by dartcafe** [comment]
Normaly in text polls the options are orderd vertically, not horizontally. Wouldn't this be better and more readable?

Maybe vote and presentation of the result can be seperated. So the voting options can be rearranged, regardles of the partitipants.

Date polls have a more coordinating meaning, which means, it helps to see the votes of others. In textpolls this maybe not that important.

Understand what I mean?

**Comment by dartcafe** [comment]
I will try the wrapping next days.

**Comment by dartcafe** [comment]
fixed in #151
