### ISSUE TITLE
E-Mail notifications with IP in Link

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/polls#1520]
Hi guys,
great app for nextcloud. I just recognized an issue while testing. The link in the e-mail notifications for updates includes the server's IP adress not the domain name. I only recognized the domain name in the first notification I receive as an external user.

**Comment by dartcafe** [comment]
Check `overwrite.cli.url` in your config.php.
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html
