### ISSUE TITLE
nextcloud/polls 21 does not support html anymore

### ISSUE THREAD

**Issue by stefan123t** [nextcloud/polls#1542]
### What is going wrong?
**Describe the bug**
I have been using html tags in my description which I setup prior upgrading to Nextcloud 21 and the latest polls version.
These html tags are not shown anymore but rendered as normal text on the polls page.

**To Reproduce**
1. Go to Polls
2. Click on New Poll
3. Enter Title
4. Enter Description
use `<br>, <b>bold</b>, <i>italic</i>, <u>underline</u>, <a href="/nextcloud/index.php/s/owozrmcFFtRP9k7">link to a file</a>, <a href="mailto:no-reply@nextcloud.com">no-reply@nextcloud.com</a>, <a href="call:+49123456789">1234-56789</a>`

**Expected behavior**
I expected that the HTML is rendered as expected, currently the html code is shown with no bold, italic, underline, etc. effects nor the links. This worked in the previous polls version under Nextcloud 20, hence I consider this a regression.

### Information about your polls installation
**Polls version?** (see apps page)
current version is 1.8.1

**Fresh installation or update from a prior version (from which one)?**
I upgraded from 1.6.3

**How did you install this version?(Appstore or describe installation)**
Appstore install

### Client configuration
**Browser:**
Firefox 87.0

**Comment by dartcafe** [comment]
html tags are removed due to security concerns (#1521). Use markdown (#325) instead.

**Comment by stefan123t** [comment]
Regarding backwards compatibility and according to two tutorial sites Markdown should also support some basic html:

_Some HTML tags can also be used in Markdown.
    <b>bold</b> **bold**
    <i>italic</i> *italic*
    <a href="http://nextcloud.com/">link</a> [link](http://nextcloud.com/)
_Many Markdown applications allow you to use HTML tags in Markdown-formatted text_

NB: ***bold-italic*** is somehow formatted as bold grey instead of bold-italic
_Underline_ is not available as to my quick research in Markdown.

Nevertheless I changed all my content to Markdown and it works somehow.
