### ISSUE TITLE
Error SQL when try to activate the Polls Plugins on Nextcloud 20

### ISSUE THREAD

**Issue by shadowmedicis** [nextcloud/polls#1545]
### What is going wrong?

When you download and activate the Polls plugin from the applications available on the Nextcloud. An error is displayed and the application cannot be launched

**To Reproduce**
1. Go to 'Applications'
2. Click on 'Organisation Catégorie'
3. Scroll down to 'Polls'
4. Click On "Download and activate"
5. See error

**Screenshots**
![SQL_error_plugin_Polls](https://user-images.githubusercontent.com/80291786/114362915-255a7c80-9b78-11eb-8824-efd094e17667.PNG)
![SQL_error_plugin_Polls2](https://user-images.githubusercontent.com/80291786/114362959-35725c00-9b78-11eb-9698-3719eeb6d36f.PNG)

### Information about your polls installation
1.8.1

**Fresh installation or update from a prior version (from which one)?**
Fresh install from store

**How did you install this version?(Appstore or describe installation)**
Appstore version

### Information about your Instance of Nextcloud

**Nextcloud version: 20.0.9 (Recently upgrade from 15, 16, 17,18,19 Nextcloud version)

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - camerarawpreviews: 0.7.10
  - checksum: 1.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - drawio: 1.0.0
  - event_update_notification: 1.2.0
  - extract: 1.3.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_antivirus: 3.2.0
  - files_automatedtagging: 1.10.1
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.0.1
  - files_retention: 1.9.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - group_default_quota: 0.1.1
  - imageconverter: 1.3.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.13.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - ransomware_protection: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_retention: 1.3.0
  - user_saml: 3.3.4
  - user_status: 1.0.1
  - user_usage_report: 1.4.2
  - video_converter: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - audioplayer
  - dashboard
  - deck
  - encryption
  - nextant
  - nextcloud_announcements
  - notes
  - polls
  - tasks

**Nextcloud configuration:**
 "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.9.1",
        "default_language": "fr",
        "defaultapp": "files",
        "auth.bruteforce.protection.enabled": true,
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 1,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mail_sendmailmode": "smtp"
    }
}

### Server configuration

**Database: MariaDB version "10.1.47-MariaDB-0ubuntu0.18.04.1" is used

**PHP version: php7.4-fpm

**Are you using an external user-backend, if yes which one: Yes, LDAPS Intégration (port 636)

### Client configuration

**Browser:**
Microsoft Edge	89.0.774.68 (Version officielle) (64 bits)

#### Nextcloud log (data/nextcloud.log)
[nextcloud_log_croped.log](https://github.com/nextcloud/polls/files/6295045/nextcloud_log_croped.log)

**Comment by dartcafe** [comment]
Check your database configuration and switch to  `innodb_file_format = Barracuda` and `innodb_large_prefix=ON` which is the default.
See also #1375

**Comment by dartcafe** [comment]
Additionally see https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html

**Comment by dartcafe** [comment]
You should also consider updating to mariaDB 10.2 See: https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html, becaus 10.1 is deprecated from NC 21 on.

**Comment by shadowmedicis** [comment]
Hello dartcafe, 

Indeed I have just modified the innodb configuration of the nextcloud database. It worked !!
Yes I will plan this upgrade
Thank you very much for your help and quick response.


Have a good day
