### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by chrigizhr** [nextcloud/polls#1546]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_options ON oc_polls_options (poll_id, poll_option_text, timestamp)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detaillierte Protokollmeldungen 
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Delete duplicates
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_options ON oc_polls_options (poll_id, poll_option_text, timestamp)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

**Comment by dartcafe** [comment]
see #1545

**Comment by bpcurse** [comment]
https://github.com/nextcloud/server/issues/23369#issuecomment-707313974

**Comment by chrigizhr** [comment]
I uninstalled the Polls App using the following command:
sudo -u www-data php /var/www/html/nextcloud/occ app:remove polls
Problem solved. Shouldn't happen on a productive server, though.

**Comment by dartcafe** [comment]
> Shouldn't happen on a productive server, though.
What do you mean?
