### ISSUE TITLE
Update error: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1547]
If you receive this error, you should update your database configuration
* `innodb_file_format = barracuda` 
* `innodb_large_prefix=on` which is the default.

Also make sure, you update to a current version of mariaDB or MySQL
Additional information:
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html
* https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html

**Comment by bpcurse** [comment]
https://github.com/nextcloud/server/issues/23369#issuecomment-707313974
