### ISSUE TITLE
Date-time selectors hidden on smaller screens

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/polls#1557]
This might be solved in https://github.com/nextcloud/polls/pull/1543 

We had some users complaining about this, so to just be sure:

### What is going wrong?
**Describe the bug**
On smaller (i.e. 1280 x950) screens the date-time selectors are partially hidden when selecting date-time ranges. This makes it impossible to select some options.

### Information about your polls installation
**Polls version?** (see apps page)
Polls 1.8.3
NC 20.0.1

![grafik](https://user-images.githubusercontent.com/8102905/115747720-cf66af80-a395-11eb-9233-cc6f54a440b9.png)

**Comment by dartcafe** [comment]
Yep. See https://github.com/nextcloud/nextcloud-vue/issues/998#issuecomment-816484064
I added a workaround in the current master

**Comment by brtptrs** [comment]
Thanks!!
Is there any chance of having this released as a hot-fix?

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/blob/7480f2b02d780c4684b289c3a1a03a141179a5f9/src/js/assets/scss/hacks.scss#L19-L25

**Comment by brtptrs** [comment]
Thank You!!!

**Comment by dartcafe** [comment]
Fixed with #1656
