### ISSUE TITLE
Date display is not localized (dates vote and date option adding calendar)

### ISSUE THREAD

**Issue by onurb-taktile** [nextcloud/polls#1558]
### What is going wrong?
**Describe the bug**
In a french setup, for a dates poll, the date display in the vote screen is not correct :
the vote options' dates seem to be hardcoded in an american english "month year; day; day_of_week" pattern even if the single elements (month name, day of week) are localized .
`<div data-v-801e6ac6="" class="event-from">`
`    <div data-v-801e6ac6="" class="month"> avr.  '21 </div>`
`    <div data-v-801e6ac6="" class="day"> 30 </div>`
`    <div data-v-801e6ac6="" class="dow"> ven. </div> `
`</div>`

Also, when adding a new date option, the dropdown calendar begins on sunday (even if the locale settings define the week to begin on monday)

**Expected behavior**
A date in french is displayed as "Vendredi 30 avril 2021" and not "avr. 21' 30 ven." (as displayed for 2021.04.30)
I would expect to get :
`<div data-v-801e6ac6="" class="event-from">`
`    <div data-v-801e6ac6="" class="dow"> ven. </div> `
`    <div data-v-801e6ac6="" class="day"> 30 </div>`
`    <div data-v-801e6ac6="" class="month"> avr.  2021 </div>`
`</div>`

On new date addition, the dropdown calendar should begin on monday, accordingly with locale settings

### Information about your polls installation
**Polls version?** 
1.8.1

**Fresh installation or update from a prior version (from which one)?**
Fresh install

**How did you install this version?(Appstore or describe installation)**
from appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** 21.0.1

**Comment by dartcafe** [comment]
screenshots would help understanding and the information about your locale and language setting.

**Comment by onurb-taktile** [comment]
**My locale settings :** 
![locale settings](https://user-images.githubusercontent.com/11510335/115842132-d2a57e00-a41d-11eb-8cee-851cd0e95f6f.png)
![locale settings2](https://user-images.githubusercontent.com/11510335/115842959-a2121400-a41e-11eb-9009-2a8f802d1268.png)
_Language : french (fr)
Locale : French(France) (fr_FR)_
Week starts on monday

**The way date poll options are actually displayed :**
![actualdisplay](https://user-images.githubusercontent.com/11510335/115842157-d802c880-a41d-11eb-824d-d9ecb94d50d9.png)

**The way they should be displayed according to fr_FR locale settings**
_(HTML modified with browser's developpers tools)_
![wished display](https://user-images.githubusercontent.com/11510335/115842177-db964f80-a41d-11eb-9223-880c47471c55.png)

**The way new date option calendar is displayed**
![actual option date](https://user-images.githubusercontent.com/11510335/115844699-61b39580-a420-11eb-9327-2b3f8c73c42e.png)

**The way it should be displayed according to fr_FR locale settings = monday first**
_(HTML modified with browser's dev tools)_
![whished date option popup](https://user-images.githubusercontent.com/11510335/115844900-96bfe800-a420-11eb-862e-86bdce5b570d.png)

**Comment by dartcafe** [comment]
> **The way date poll options are actually displayed :**
> ![actualdisplay](https://user-images.githubusercontent.com/11510335/115842157-d802c880-a41d-11eb-824d-d9ecb94d50d9.png)
> 
> **The way they should be displayed according to fr_FR locale settings**
> _(HTML modified with browser's developpers tools)_
> ![wished display](https://user-images.githubusercontent.com/11510335/115842177-db964f80-a41d-11eb-9223-880c47471c55.png)
> 

This is a fixed display and by intention regardles of the locale settings.

**Comment by dartcafe** [comment]
> **The way new date option calendar is displayed**
> ![actual option date](https://user-images.githubusercontent.com/11510335/115844699-61b39580-a420-11eb-9327-2b3f8c73c42e.png)
> 
> **The way it should be displayed according to fr_FR locale settings = monday first**
> _(HTML modified with browser's dev tools)_
> ![whished date option popup](https://user-images.githubusercontent.com/11510335/115844900-96bfe800-a420-11eb-862e-86bdce5b570d.png)

I have to investigate this, because, we rely on the information of the used compenents. I will open a new issue for that and close this.
