### ISSUE TITLE
First day of week is wrong in date picker

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1560]
From #1558

What is going wrong?

Describe the bug
In a french setup [...], when adding a new date option, the dropdown calendar begins on sunday (even if the locale settings define the week to begin on monday)

Expected behavior
On new date addition, the dropdown calendar should begin on monday, accordingly with locale settings
Information about your polls installation

Polls version?
1.8.1

Fresh installation or update from a prior version (from which one)?
Fresh install

How did you install this version?(Appstore or describe installation)
from appstore
Information about your Instance of Nextcloud

Nextcloud version: 21.0.1

**My locale settings :** 
![locale settings](https://user-images.githubusercontent.com/11510335/115842132-d2a57e00-a41d-11eb-8cee-851cd0e95f6f.png)
![locale settings2](https://user-images.githubusercontent.com/11510335/115842959-a2121400-a41e-11eb-9009-2a8f802d1268.png)
_Language : french (fr)
Locale : French(France) (fr_FR)_
Week starts on monday

**The way new date option calendar is displayed**
![actual option date](https://user-images.githubusercontent.com/11510335/115844699-61b39580-a420-11eb-9327-2b3f8c73c42e.png)

**The way it should be displayed according to fr_FR locale settings = monday first**
_(HTML modified with browser's dev tools)_
![whished date option popup](https://user-images.githubusercontent.com/11510335/115844900-96bfe800-a420-11eb-862e-86bdce5b570d.png)

_Originally posted by @onurb-taktile in https://github.com/nextcloud/polls/issues/1558#issuecomment-825502300_

**Comment by AvverbioPronome** [comment]
Hey, this is broken again. 

![immagine](https://github.com/nextcloud/polls/assets/1191978/f65c0f91-efc7-4632-b6ac-1e32a7249cb3)
![immagine](https://github.com/nextcloud/polls/assets/1191978/49674bea-b623-42bb-b635-4db660fcf346)

**Comment by AvverbioPronome** [comment]
If I change the locale to Italian (italy) it does what I expect, but English (europe) does not.
