### ISSUE TITLE
Cannot install polls due to database error

### ISSUE THREAD

**Issue by jgrete** [nextcloud/polls#157]
Hi,
activation is not possible on a fresh upgraded Nextcloud 12.0.2 system.
On activation I'm getting this:

`An exception occurred while executing 'ALTER TABLE oc_polls_events ADD `hash` VARCHAR(64) DEFAULT NULL, ADD `is_anonymous` INT DEFAULT 0, ADD `full_anonymous` INT DEFAULT 0, CHANGE `id` `id` INT AUTO_INCREMENT NOT NULL, CHANGE `type` `type` BIGINT DEFAULT NULL, CHANGE `created` `created` DATETIME DEFAULT NULL, CHANGE `expire` `expire` DATETIME DEFAULT NULL': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'b0r1kvr20sr74mdj' for column 'id' at row 1`

Regards
Juergen

**Comment by dartcafe** [comment]
Can you give some more information? 
What version did you ubgrade to 20.0.2
Which version of polls was installed befor?
Which Version did you try to install?

I will try to reproduce that.

**Comment by jgrete** [comment]
The upgrade was done from Nextcloud 12.0.0 to 12.0.2
I remember that I was not able to install Polls on NC 12.0.0 and thought it was a problem with NC 12.0.0
I cannot tell you which version of Poll was installed before - I think the last working version was installed long ago (>9 month). The current versyion I tried to install is 0.7.3

**Comment by dartcafe** [comment]
I think it is a problem of the missing migration from prior versions. It would be more easy to delete the tables staring with oc_poll in thwe database to start with a clean db schema, if you do not have important polls from the past. 

When leaving the beta status, I think, there will be a migration path, hopefully starting from version 0.7.4. 
@v1r0x Any additional recommendation?

**Comment by jgrete** [comment]
Ok, no problem to delete the tables.
Thank you for investigating!
Juergen

**Comment by jgrete** [comment]
By the way, may I propose a small change in the user interface for the upcoming new version? 
On creating a new poll when I'm choosing a couple of dates without choosing a time of day a dialog box warns
"Nothing selected. Click on cells to turn them green"
This is not very intuitive because it refers to cells which are not visible yet. Please allow choosing dates without time of day or indicate that the time is not optional.
Regards
Juergen

**Comment by dartcafe** [comment]
open a new issue, so we can track that. But I have that in mind. The creation page needs some more work besides this, I believe.

**Comment by jgrete** [comment]
Sorry to reopen this issue. I had no time since this thread was closed to verify the database. 
I did it now and found there are no tables starting with oc_polls_* so I cannot delete any.
Any other proposals to get rid off this error?
Regards
Juergen

**Comment by jgrete** [comment]
All oc_polls_* tables deleted and now it works!
