### ISSUE TITLE
Allow users to add additional text options

### ISSUE THREAD

**Issue by dgiebert** [nextcloud/polls#1570]
**Is your feature request related to a problem? Please describe.**
I want to create a survey and allow the users to add options as text fields.

**Describe the goal you'd like to achieve**
I want to know what my users want regarding a certain question without predetermined answers or adding to the existing answers / options.

**Describe possible solutions**
Add an empty text field underneath or a button stating add answer / option

**Comment by dartcafe** [comment]
You'll find it in the next version #1127
