### ISSUE TITLE
Order in experimental settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/polls#1572]
In the experimental setup it looks a bit chaotic for specifying a URL:

![obraz](https://user-images.githubusercontent.com/47037905/116203213-bebe8c80-a73b-11eb-8d42-392980d6c05f.png)

The user really needs to focus well on what's going on.

I suggest:

1. Move the URL box next to the description: `Enter the URL of your favorite background image.`
2. End this description with a colon: `Enter the URL of your favorite background image:`
3. In the URL input window, display a sample address (grayed out).

**Comment by dartcafe** [comment]
Something is broken here, I will look after it later. I think some CSS changings caused this.

**Comment by dartcafe** [comment]
`Enter the URL of your favorite background image:` got moved to placeholder

![grafik](https://user-images.githubusercontent.com/26707476/118411966-9de0bb80-b697-11eb-9f21-cd25afe00edf.png)
