### ISSUE TITLE
confusing structure of the date

### ISSUE THREAD

**Issue by Jana702** [nextcloud/polls#1575]
**Is your feature request related to a problem? Please describe.**
If I add a lot of dates it's really confusing to recognize which date and time are the opportunities. Also the time is really small written. 

**Describe the goal you'd like to achieve**
I would be great when they have a clear structure.

**Describe alternatives you've considered**
Maybe like doodle, they used a table for it.

**Describe possible solutions**
I wouldn't use the hierarchys and don't centered the text because it's too much input and confusing. 

**Additional context**
This screenshot shows what I mean.

<img width="700" alt="Bildschirmfoto 2021-04-27 um 16 24 33" src="https://user-images.githubusercontent.com/83290125/116258756-8340b400-a775-11eb-992e-9e7c740d59b3.png">

**Comment by dartcafe** [comment]
Hey @laura040801 Thanks for your issue. I have several questions and need your help to understand your aspects and find ways for improvement. 

> If I add a lot of dates it's really confusing to recognize which date and time are the opportunities.

Could you describe, what or why this is confusing? 

>  I would be great when they have a clear structure.

What in your optinion is a clearer structure? I mean, what you describe is from a personal view. From my view the current structure is rather clear, but if there is room for optimization, I am happy to get some proposition.

>  Maybe like doodle, they used a table for it.

Compared to doodle, I would say it is rather similair.
![grafik](https://user-images.githubusercontent.com/26707476/116354463-c09a5580-a7f8-11eb-8222-28302c505bec.png)

>  I wouldn't use the hierarchys and don't centered the text because it's too much input and confusing.

Could you explain further, what you would change and how?

**Comment by Jana702** [comment]
Hey @dartcafe Thank you for your answer!
The arrangement of the period is confusing due to the offset of the typography. As you can see in the screenshot on top, „April 30th“ is smaller than „April 26th“ and also offset like a staircase. That gives you the feeling that they do not belong together. Underneath the date, the time is written smaller and „4:30 PM“ is smaller than „9:30 AM“. Overall, the impression of an inverted pyramid is created. If you have further options, it is more difficult to see which options are available.

In the following table we will show you @laura040801 and my ideas for a new design.

Design suggestions | Description
-|-
<img width="1016" alt="Desktop - Tabelle erste Idee" src="https://user-images.githubusercontent.com/83290125/116585305-8d4ee800-a918-11eb-8544-cb752d201cb7.png"> | If you arrange the header in a uniform size (as you can see in the screenshot), the result would be a nicer shape. However, this variant also has weaknesses, so we tried a new structure.
-|-
![Desktop - alle Variante](https://user-images.githubusercontent.com/83290125/116588915-64305680-a91c-11eb-8df5-dfdb9f0dc77b.jpg) | This varies depending on the information in the table. To provide a better overview, there are three options.
-|-
![Desktop - Mockup](https://user-images.githubusercontent.com/83290125/116590895-8dea7d00-a91e-11eb-8608-cef85694e624.jpg) |  Here you can see a mockup of the desktop screen before and after. (Maybe you should click on them to see it bigger)
-|-
![Mobile - alle Variante](https://user-images.githubusercontent.com/83290125/116589836-5d561380-a91d-11eb-800d-ba3902c44bed.jpg) | The mobile version is also important. In the current version you can only see a fraction of the table, which makes the selection more difficult (first screen). We also applied the new options for the desktop to the mobile version.
-|-
![Mobile - alle fade in:out](https://user-images.githubusercontent.com/83290125/116590193-c2aa0480-a91d-11eb-8f8d-6e71bc708a46.jpg)| The more options there are, a scroll function should be a must-have. There are two ways to visualize this. The first would be a "fade out/in" effect. It helps to recognize that there are more opportunities.
-|-
![Mobile - alle Scrollleiste](https://user-images.githubusercontent.com/83290125/116590425-069d0980-a91e-11eb-97fa-784c33379511.jpg)| The second option is a "scroll bar". It also helps to recognize the other options. Given the design of Nextcloud, in our opinion this fits better because it has a clearer appearance.
-|-
![Mobile - Mockup](https://user-images.githubusercontent.com/83290125/116590788-71e6db80-a91e-11eb-8ec1-c36e75e859c1.jpg) | Here you can see a mockup of the mobile version before and after.

What do you think about our suggestions?
Greetings Laura & Jana

**Comment by dartcafe** [comment]
Congratulations. Cool Mockups! 👍 I like the structure and the design, especially the mobile layout. I would say much better than doodle. And now I understand your points in the starting post. 😉 

Could we stress this a little bit with the options below? Especially the date, which spans over the end of the month.

![grafik](https://user-images.githubusercontent.com/26707476/116605636-f0984480-a92f-11eb-9c47-86a5f8b64e82.png)

And: How would you solve the display of the warning element, which signals a conflict with an existing calendar event?
![grafik](https://user-images.githubusercontent.com/26707476/116605883-45d45600-a930-11eb-8b75-903437ae5991.png)

Another point is the menu behind the three dots near the username. Any ideas of improvement for this. 

@jancborchardt What is your impression? Want to hear something from a pro. 🧼 
BTW: Would it be possible to use the current master of polls for the instance?
AND: How long can we rely on the presence of Jana, Laura and JT? Until the end of 2021 is enough. 🤣

**Comment by dartcafe** [comment]
Moved UX propoasal to #1602
