### ISSUE TITLE
Date selector is covered by the text field

### ISSUE THREAD

**Issue by laura040801** [nextcloud/polls#1576]
While using an iPad, after clicking on „Select range“, the whole date selector is covered by the text field.
![41F24B4C-A4A9-4F51-9B5F-EE8DEF74EEAF](https://user-images.githubusercontent.com/83289975/116261459-f2b7a300-a777-11eb-96b0-ad8a36d46f37.png)

**Comment by dartcafe** [comment]
duplicate #1557
