### ISSUE TITLE
Remove Owncloud versions in appinfo?

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#158]
I am not sure, but I fear that this isn't tested. Or can somebody support this?

**Comment by v1r0x** [comment]
Some users are oC users, so we should definitely keep it in appinfo. But yes, I think this not properly tested.

**Comment by dartcafe** [comment]
OK. I fear, that my changes are not really compatible with oC, because I just watched NC.

**Comment by dartcafe** [comment]
I will setup an instance for it, just to know, what's broken...

**Comment by dartcafe** [comment]
I tested the branch against oC and everything works as expected, besides the fact, that oC cannot handle SCSS files, so we should commit the compiled CSS files for the release.

**Comment by kdslkdsaldsal** [comment]
Thumbs up for keeping the oC compatibility. 👍 Will report any upcoming issues with oC here if you would like me to do this.

**Comment by v1r0x** [comment]
Sounds good. Thank you! :)
