### ISSUE TITLE
API AUTHENTICATION

### ISSUE THREAD

**Issue by rotichbryant** [nextcloud/polls#1591]
I tried to fetch my polls from the server using api calls but i keep getting the following error

`{"error":"invalid_grant_and_session","error_description":"The provided access token and session state are invalid or were issued to another client.","reason":"Failed to identify session by session_id query parameter or by session_id cookie."}`

Is there something i am missing from initializing this request ?

**Comment by dartcafe** [comment]
Use base auth: https://github.com/nextcloud/polls/blob/master/docs/API_v1.0.md

Please respect that the API still is in draft status and can fail. Any issues regarding the API-Calls are welcome.

**Comment by rotichbryant** [comment]
What are the the credentials needed to be used ?

**Comment by dartcafe** [comment]
simply username and password of the user

**Comment by rotichbryant** [comment]
That is what i used and that is the error i got.

**Comment by dartcafe** [comment]
You need to add the credentials for every api call like

`https://username:password@nextcloud.local/index.php/apps/polls/api/v1.0/poll/1/comments`

**Comment by dartcafe** [comment]
@rotichbryant Did this help or is this issue still open for you?

**Comment by rotichbryant** [comment]
Yes it helped. We found the solution. There was a logout hook that affected the api call flow. Our nextcloud login is handled differently and that was what cause the issue.

**Comment by dartcafe** [comment]
OK, good to hear. Please be aware, that the API is not stable tested. Any issues are welcome.
