### ISSUE TITLE
Public polls: default view is always "list", regardless of settings

### ISSUE THREAD

**Issue by dtcg** [nextcloud/polls#1594]
A poll shared with public link is always displayed with list view, never table view, regardless of settings.

Ticking/unticking default list view in poll settings doesn't change this behaviour. 

**Polls version** 1.8.3

### Information about your Instance of Nextcloud

**Nextcloud version:** 21.0.0

**List of activated apps:**
```
 Cospend
1.3.0
Deck
1.4.1
Mises en avant
Accessibility
1.7.0
Mises en avant
Activity
2.14.3
Mises en avant
AppOrder
0.12.0
Calendar
2.2.1
Mises en avant
Collaborative tags
1.11.0
Mises en avant
Comments
1.11.0
Mises en avant
Contacts Interaction
1.2.0
Mises en avant
Deleted files
1.11.0
Mises en avant
Discourse SSO
1.0.21
Draw.io
1.0.0
External sites
3.8.1
Mises en avant
Federation
1.11.0
Mises en avant
File sharing
1.13.1
Mises en avant
Forms
2.2.4
Mises en avant
Log Reader
2.6.0
Mises en avant
Monitoring
1.11.0
Mises en avant
Nextcloud announcements
1.10.0
Mises en avant
Notifications
2.9.0
Mises en avant
ONLYOFFICE
6.3.0
Mises en avant
Password policy
1.11.0
Mises en avant
PDF viewer
2.1.0
Mises en avant
Photos
1.3.0
Mises en avant
Polls
1.8.3
Privacy
1.5.0
Mises en avant
Right click
1.0.0
Mises en avant
Share by mail
1.11.0
Mises en avant
Support
1.4.0
Mises en avant
Talk
11.1.2
Mises en avant
Theming
1.12.0
Mises en avant
Update notification
1.11.0
Mises en avant
User status
1.1.1
Mises en avant
Versions
1.14.0
Mises en avant
Video player
1.10.0
Mises en avant

**Comment by dartcafe** [comment]
The setting is a personal setting per user and does not control public polls. But I think, we have to change the behavior.

**Comment by dartcafe** [comment]
related to #1602

**Comment by g6094199** [comment]
> The setting is a personal setting per user and does not control public polls. But I think, we have to change the behavior.

jep. users should have to personal option to change it to their needs, but  the chosen view from the poll starter shoud be pre the selected view.

**Comment by dartcafe** [comment]
All views are already chenged to the table layout in desktop mode.
