### ISSUE TITLE
Turn green the poll options when creating a poll as default

### ISSUE THREAD

**Issue by jgrete** [nextcloud/polls#160]
Hi,

On creating a new poll when I'm choosing a couple of dates without choosing a time of day a dialog box warns
"Nothing selected. Click on cells to turn them green"
This is not very intuitive because it refers to cells which are not visible yet. Please allow choosing dates without time of day or indicate that the time is not optional.
Regards
Juergen

**Comment by jgrete** [comment]
Oh, I see this is double of #131
Sorry

**Comment by v1r0x** [comment]
closing this one if favor of #131
