### ISSUE TITLE
Wrong hour displayed within Firefox

### ISSUE THREAD

**Issue by Viguro79** [nextcloud/polls#1610]
### What is going wrong?
Withing Chrome 90.0.4430.93 the hour is displayed correctly
![Capture d’écran 2021-05-11 à 14 56 48](https://user-images.githubusercontent.com/60188402/117818665-5baf1880-b258-11eb-94fb-ccffc4afd201.png)
Within Firefox 88.0.1, the displayed hour is the UTC hour :
![Capture d’écran 2021-05-11 à 14 57 37](https://user-images.githubusercontent.com/60188402/117818801-797c7d80-b258-11eb-9620-eb467ccdb613.png)

**To Reproduce**
1. Create a poll within Chrome
2. Select date and hour (say 20:00 Paris Hour / 18:00 UTC)

**Expected behavior**
When using the poll link within Firefox, I expect to see the Paris Hour. Whereas the displayed hour is the UTC hour.

### Information about your polls installation
**Polls version?** 1.8.3

**Fresh installation or update from a prior version (from which one)?**
Update from a prior one

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:** 21.0.0

**Nextcloud configuration:**
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'datadirectory' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '21.0.0.18',
  'overwrite.cli.url' => 'xxx',
  'dbname' => 'xxxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'xxxx',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => 'xxxx',
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'xxx',
  'mail_smtpport' => '587',
  'mail_smtphost' => 'xxx',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxxx',
  'mail_smtppassword' => 'xxxx',
  'app_install_overwrite' => 
  array (
    0 => 'whiteboard',
  ),

**Comment by dartcafe** [comment]
See https://github.com/nextcloud/polls/issues/995#issuecomment-652529177

**Comment by Viguro79** [comment]
Great. I disabled the _Resist FingerPrinting_ extension which was overriding the `privacy.resistFingerprinting `value to false in config:about. I then restarted Firefox and the displayed value in Nextcloud is now correct.
Thansk.
