### ISSUE TITLE
[Feature Request] Add option to disallow multiple selections

### ISSUE THREAD

**Issue by AceSlash** [nextcloud/polls#162]
Hello,

We are evaluating polls and it's great when selecting a date for a meeting but when creating a simple poll, the current layout is suboptimal, we often need a very simple poll with only one possible selection (radio style), like:
Should we use the Nextcloud polls plug in?
1. Yes
2. No
3. I don't care

I understand that I could just create an option with the name of the poll in this case and use the default gree/red/yellow colours but from our internal testing, people don't get it and create several items.

Furthermore you may have some polls with more than 3 choices but with only one possible selection.

**Comment by dartcafe** [comment]
At least for the text polls, this is a good idea. But I think, for the appointment polls, this is beyond the sense of this kind of polls.

**Comment by UnserUp** [comment]
A very useful and necessary option.
That allows exclyentes selections.
I hope you do it fast!

**Comment by aslmx** [comment]
Yes. Please add an option to the app to have a single-option poll. 

And btw: i already love this app for the easy integration into my infrastructure. This has a lot of potential! :+1:

**Comment by TimoKunze** [comment]
We would really like to use this app, but we would need single-option polls. Otherwise it does not suit our use-case.

**Comment by dartcafe** [comment]
#738
