### ISSUE TITLE
Giving the navigation some sense

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#163]
Topic for a new PR! Will overtake some suggestion from @jancborchardt from https://github.com/nextcloud/polls/issues/148#issuecomment-329108295

**Comment by skjnldsv** [comment]
Please check the CSS guidelines for this. I will help validate your pr. Set me as a reviewer on the pr when it's opened. :)

**Comment by dartcafe** [comment]
Done https://github.com/nextcloud/polls/tree/dev-1.0
