### ISSUE TITLE
Slow rendering with increasing amount of options

### ISSUE THREAD

**Issue by tobiasstein** [nextcloud/polls#1643]
### What is going wrong?
Rendering the poll in the browser gets slower and slower with the increasing amount of options.
I imported a larger set of options into the database and the frontend got unbearably slow.
Frontend Development with JavaScript and Browser is way beyond my expertise.

**To Reproduce**
I was using nextcloud/polls to let my friends pick some DNS domains (from a large amount).

1. Create new textual poll named 'Test Performance'
2. Import a bigger set of options n = 26 * 26 * 10 = 6760 into the database.
    1. Create a set of options
        1. Create a script `options_generate.sh`
        ```bash
        #!/bin/bash

        readarray -t -d\  DOMAINS < <(echo -n {a..z}{a..z}{0..9})
        printf '%s,AVAILABLE\n' "${DOMAINS[@]}" 
        ```
        2. Write the options to a file
        `bash options_generate.sh > options_generated.list`
    2. Get the `poll_id` of the newly created poll from the database
    ```bash
    POLL_ID="$(mysql -ssr -e \
        "SELECT id FROM nextcloud.oc_polls_polls
         WHERE title = 'Test Performance';")"
    ```
    3. Bulk insert the options into the database
        1. Create a script `options2sql.sh` (assumes your DB is named 'nextcloud')
        ```bash
        #!/bin/bash
        BULK_INSERT=true
        LIMIT=1000
        ORDER=1

        ### IF POLL_ID IS NUMERICAL
        if [ "$1" -eq "$1" ]; then
                POLL_ID="$1"
        else
                echo "Please specify a valid poll_id. Exiting…"
                exit 2
        fi

        DOMAINS_STATUS="${2:-domains.status}"

        readarray -t DOMAINS_AVAIL \
                < <(grep AVAILABLE "$DOMAINS_STATUS" \
                        |cut -d, -f1)
        DOMAINS_COUNT="${#DOMAINS_AVAIL[@]}"

        if $BULK_INSERT; then
                declare -a BULK
                BULK_ITER=0
                for ((BULK_ITER=0;BULK_ITER<=((DOMAINS_COUNT/LIMIT));BULK_ITER++)); do
                        BULK=( "${DOMAINS_AVAIL[@]:((BULK_ITER*LIMIT)):$LIMIT}" );
                        BULK_COUNT="${#BULK[@]}"
                        if [ "$BULK_COUNT" -gt 0 ]; then
                                cat <<-EOF
                                        ### BULK '$BULK_ITER' WITH '$BULK_COUNT' DOMAINS
                                        INSERT
                                        INTO nextcloud.oc_polls_options
                                                 (\`poll_id\`, \`poll_option_text\`, \`order\`)
                                        VALUES
                                EOF
                                DOMAIN_ITER=0
                                for DOMAIN in "${BULK[@]}"; do
                                        ((DOMAIN_ITER++))
                                        if [ "$DOMAIN_ITER" -lt "$BULK_COUNT" ]; then
                                                DELIM=","
                                        else
                                                DELIM=""
                                        fi
                                        echo -e '\t'"('$POLL_ID', '$DOMAIN', $ORDER)$DELIM"
                                        ((ORDER++))
                                done
                                echo ";"
                        fi
                done
        else
                for DOMAIN in "${DOMAINS_AVAIL[@]}"; do
                        cat <<-EOF
                                INSERT INTO nextcloud.oc_polls_options
                                        (\`poll_id\`, \`poll_option_text\`, \`order\`)
                                        SELECT 2, '$DOMAIN', COALESCE(MAX(\`order\`), 1)
                                                FROM nextcloud.oc_polls_options;
                        EOF
                done
        fi
        ```
        2. Create the bulk import sql-script (to not wait for ever)
        `bash options2sql.sh "$POLL_ID" options_generated.list > options_generated.sql`
    1. Import the SQL into the database
    `mysql < options_generated.sql`
    1. Reconfigure database runtime
        1. Create a little code snipped `mysql_variables.sql`
        ```SQL
        #SET GLOBAL innodb_buffer_pool_size = 536870912;
        SET GLOBAL slow_query_log = ON;
        #SET GLOBAL slow_query_log_file = "/var/snap/nextcloud/27920/mysql/nextcloud1-slow.log";
        SET GLOBAL log_queries_not_using_indexes = ON;
        SET GLOBAL long_query_time = 3;
        #SET GLOBAL join_buffer_size = 1048576;
        #SET GLOBAL sync_binlog = 0;
        ```
        1. Activate logs
        `mysql < mysql_variables.sql`
    2. Call the poll in nextcloud and wait for a significant amount of time to get the page displayed.
    In my case is was waiting 12min on my workstation.
    Checking a box equally slow. 

**Expected behavior**

* Browser load time does not increase to a unbearable level.
* The browser displays the poll within a finite amount of time.
* Options can be checked and unchecked fluently.

**Screenshots**

### Information about your polls installation
Polls version: 1.8.3

**Fresh installation or update from a prior version (from which one)?**
First installation of polls

**How did you install this version?**
Polls from Appstore

### Information about your Instance of Nextcloud

**Nextcloud version:**
Nextcloud 21.0.1 from snap (got upgraded automatically).

### Server configuration

**Database:**
`/snap/nextcloud/27920/bin/mysqld  Ver 8.0.24 for Linux on x86_64 (Source distribution)`

**PHP version:**
`php 7.4.15`

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
none

### Client configuration
**Device:**
ANY

**Browser:**

Firefox/Chrome/…

#### Slow logs and queries not using indexes

I had no slow queries (t>3s) referring with polls.

Queries not using indexes:
```SQL
# Time: 2021-05-21T19:54:37.932027Z
# User@Host: nextcloud[nextcloud] @ localhost []  Id: 89163
# Query_time: 0.000398  Lock_time: 0.000135 Rows_sent: 0  Rows_examined: 3
SET timestamp=1621626877;
SELECT * FROM `oc_polls_watch` WHERE (`updated` > '1621625919') AND ((`poll_id` = '1') OR (`table` = 'polls'));
```

The query returns within 300µs (3rows in a full table scan),
but to get rid of the message in the slow log i created the index.
```SQL
CREATE INDEX WATCH_UPDATED ON `oc_polls_watch` (updated) USING btree;
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"UsFXeeTKhxxSGmpUMICA","level":0,"time":"2021-05-24T11:30:17+00:00","remoteAddr":"W.X.Y.Z","user":"rockstable","app":"contacts","method":"GET","url":"/index.php/apps/polls/poll/2/watch?offset=1621854808","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":"21.0.1.1"}
{"reqId":"UsFXeeTKhxxSGmpUMICA","level":0,"time":"2021-05-24T11:30:17+00:00","remoteAddr":"W.X.Y.Z","user":"rockstable","app":"files_sharing","method":"GET","url":"/index.php/apps/polls/poll/2/watch?offset=1621854808","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":"21.0.1.1"}
```

#### Browser log
![Nextcloud_polls_slow](https://user-images.githubusercontent.com/1701647/119343057-35489e80-bc96-11eb-866e-cdf3495cfdbe.jpg)

## Hypothesis

Browser takes an eternity to append or modify all these elements to the DOM.
TAB gets stall. There must be a more efficient wa.

(Not the Database. :-) )

Thanks in advance for your help!1!!

**Comment by dartcafe** [comment]
I would say, that your hypothesis is right. 6000 Vote options are far too much for the way, we render the vote table. Or much more precise, the way we build the data with the vue store.

Personally, I see no way for quick wins, to get this working faster.

**Comment by dartcafe** [comment]
Since we had the problem in a current implementation, it is clear, that vue is the problem here. We need to use other strategies to make this work. Seems, that vue isn`t made to handle this amount of reactive components.

**Comment by stefan123t** [comment]
If vue is the bottleneck here, would it be worthwhile to implement native HTML checkboxes in the table ?
This could also help with semantic HTML for accessibility (see #1354) as screenreaders usually know how to handle native HTML elements. For custom elements, e.g. a custom checkbox with ternary states (Yes, Maybe, No, etc.) we need to provide explanation to the icons in an aria-label. Hence it might be better to implement this as native HTML option lists. We may choose to hide the unused other options visibly, but for a disabled user the assistive technology (screenreader, braille terminal, etc.) will know how to handle that if we provide a screenreader-only text / label element.

**Comment by dartcafe** [comment]
> If vue is the bottleneck here, would it be worthwhile to implement native HTML checkboxes in the table ?

The problem stays: We have to iterate over the options and the votes. This is no issue about the rendering of the components itself, but the reactivity of the components. 

I guess we have to implement some pagination or vitual scrolling.

**Comment by Chris2011** [comment]
I see, that you still use vue 2.6.*. Maybe an update to vue 3.2 which is quite new and has some performance improvements, could be better. Just guessing.

**Comment by dartcafe** [comment]
Yes i was thinking about function components, but in vue3 they are removed, due to performance optimizations. But unfortunately, we have to wait for some dependencies to get updated and compible to vue3. I hope, that this will support getting rid of these problems.
