### ISSUE TITLE
More data access

### ISSUE THREAD

**Issue by dtcg** [nextcloud/polls#1649]
### The request

As a poll owner, I would like to be able to **add custom registration fields** and the ability to make them compulsory or optional. 
I would also like to be able to **access** that information (so I can reach participants in the case of phone number / emails).

### My use case:
I often publish polls and have many participants. Right now, my limitations are:
* If participants have the same name, I can't tell them apart. Possible solution: custom compulsory **Family name** text field.
* If I need to reach participants, I can't as emails are currently optional and unaccessible to poll admins anyway. Possible solution: custom compulsory **phone number** and **email** text fields AND the ability to access them.

Sorry, this might be 2 topics in 1. Thanks for the great work !

**Comment by dartcafe** [comment]
Are you taking about external participants or NC users as well?

**Comment by dtcg** [comment]
External, in my case.

**Comment by dartcafe** [comment]
I've put it into the backlog. But I don't think, we will see this soon.

**Comment by dartcafe** [comment]
The current version allows to set email addresses to be mandatory. Additionally from 3.3.0 email addresses are added to the share entries of public users for better identification. 

More fields are not planned and necessary IMHO. So I close this issue. Feel free to reopen it or create another issue with specific requests.
