### ISSUE TITLE
UI Broken with NC11 ?

### ISSUE THREAD

**Issue by frankpau** [nextcloud/polls#165]
Hi,

i just installed polls 0.7.3 in my NC11 and the UI looks broken:

![grafik](https://user-images.githubusercontent.com/32132237/30731761-9be458f2-9f6f-11e7-95a3-e2493a97c019.png)

This happens with current Firefox and Chrome

Any Idea ?

Regards
Frank

**Comment by dartcafe** [comment]
I just tested agains NC12 and NC13. I will setup an NC11 instance and check this.

**Comment by dartcafe** [comment]
NC 11 cannot (correctly) compile the SCSS. Maybe a special release for NC 11 with compiled css files can be packed.

**Comment by dartcafe** [comment]
I added the compiled CSS files to the branch.

**Comment by v1r0x** [comment]
So NC 11 is supported? Then we should revert #174 :wink:

**Comment by dartcafe** [comment]
@v1r0x Already committed support for 11 in the master branch. But the question is, if we should lift the min OC version. I'm not sure, if it is compatible to prior versions than 10.

**Comment by xXSTrikeXx** [comment]
@dartcafe I woul suggest to let it so and let the community test it ;) Otherwise force the user to update, to make a build receipt ;)

**Comment by dartcafe** [comment]
This is no problem, because we have to ship the CSS files for OC. So this release can support it. I will remove it for the 0.9 release then.
