### ISSUE TITLE
"Error saving username"

### ISSUE THREAD

**Issue by dtcg** [nextcloud/polls#1651]
On public polls registration, if:
1. **name** field contains a **space**  AND
2. **email** is provided

Then the user is stuck with the message "Error saving username". This is especially confusing as both fields visually validate the content with green ticks.

![error](https://user-images.githubusercontent.com/20596421/119719829-8bba0680-be69-11eb-94e6-168beea91156.png)

Note that **name field with space** WITHOUT **email** WORKS, strangely enough.

### Information about your polls installation
Polls version 1.8.3, updated from the previous version

### Information about your Instance of Nextcloud

Nextcloud version 21.0.0

Database: mysql, Version : 10.5.9 

PHP version: 7.4.16

#### Nextcloud log (data/nextcloud.log)
```
[polls] Error: Failed to authenticate on SMTP server with username "cloud@xyz.fr" using 1 possible authenticators. Authenticator PLAIN returned Expected response code 235 but got code "454", with message "454 4.7.0 Temporary authentication failure: Connection lost to authentication server
".

POST /apps/polls/s/mkCExifJ08mIAwP9/register
from 90.125.46.253 at 2021-05-26T18:18:29+00:00
[index] Error: Swift_TransportException: Failed to authenticate on SMTP server with username "cloud@xyz.fr" using 1 possible authenticators. Authenticator PLAIN returned Expected response code 235 but got code "454", with message "454 4.7.0 Temporary authentication failure: Connection lost to authentication server
". at <<closure>>

 0. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php line 371
    Swift_Transport_Esmtp_AuthHandler->afterEhlo(Swift_SmtpTransport {})
 1. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 148
    Swift_Transport_EsmtpTransport->doHeloCommand()
 2. /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php line 65
    Swift_Transport_AbstractSmtpTransport->start()
 3. /var/www/html/lib/private/Mail/Mailer.php line 205
    Swift_Mailer->send(Swift_Message {}, [])
 4. /var/www/html/custom_apps/polls/lib/Service/MailService.php line 127
    OC\Mail\Mailer->send(OC\Mail\Message {})
 5. /var/www/html/custom_apps/polls/lib/Service/MailService.php line 159
    OCA\Polls\Service\MailService->sendMail(OC\Mail\EMailTemplate {}, "xyz@yopmail.com", "James John")
 6. /var/www/html/custom_apps/polls/lib/Service/ShareService.php line 320
    OCA\Polls\Service\MailService->resendInvitation("wpXqXYKDy4zRY2M0")
 7. /var/www/html/custom_apps/polls/lib/Controller/PublicController.php line 350
    OCA\Polls\Service\ShareService->personal("mkCExifJ08mIAwP9", "James John", "xyz@yopmail.com")
 8. /var/www/html/custom_apps/polls/lib/Controller/ResponseHandle.php line 66
    OCA\Polls\Controller\PublicController->OCA\Polls\Controller\{closure}("*** sensitive parameters replaced ***")
 9. /var/www/html/custom_apps/polls/lib/Controller/PublicController.php line 351
    OCA\Polls\Controller\PublicController->responseCreate(Closure {})
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 218
    OCA\Polls\Controller\PublicController->register("mkCExifJ08mIAwP9", "James John", "xyz@yopmail.com")
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 127
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Polls\Controller\PublicController {}, "register")
12. /var/www/html/lib/private/AppFramework/App.php line 157
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Polls\Controller\PublicController {}, "register")
13. /var/www/html/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Polls\\Con ... r", "register", OC\AppFramework\ ... {}, {token: "mkCExif ... "})
14. /var/www/html/lib/base.php line 993
    OC\Route\Router->match("/apps/polls/s/mkCExifJ08mIAwP9/register")
15. /var/www/html/index.php line 37
    OC::handleRequest()

POST /apps/polls/s/mkCExifJ08mIAwP9/register
from 90.125.46.253 at 2021-05-26T18:18:29+00:00
```

**List of activated apps:**

Calendar
2.2.1
Mises en avant
Discourse SSO
1.0.21
ONLYOFFICE
6.3.0
Mises en avant
Accessibility
1.7.0
Mises en avant
Activity
2.14.3
Mises en avant
AppOrder
0.12.0
Collaborative tags
1.11.0
Mises en avant
Comments
1.11.0
Mises en avant
Contacts Interaction
1.2.0
Mises en avant
Cospend
1.3.4
Deck
1.4.2
Mises en avant
Deleted files
1.11.0
Mises en avant
Draw.io
1.0.0
External sites
3.8.1
Mises en avant
Federation
1.11.0
Mises en avant
File sharing
1.13.1
Mises en avant
Forms
2.2.4
Mises en avant
Impersonate
1.8.0
Mises en avant
Log Reader
2.6.0
Mises en avant
Monitoring
1.11.0
Mises en avant
Nextcloud announcements
1.10.0
Mises en avant
Notifications
2.9.0
Mises en avant
Password policy
1.11.0
Mises en avant
PDF viewer
2.1.0
Mises en avant
Photos
1.3.0
Mises en avant
Polls
1.8.3
Privacy
1.5.0
Mises en avant
Right click
1.0.0
Mises en avant
Share by mail
1.11.0
Mises en avant
Support
1.4.0
Mises en avant
Talk
11.2.1
Mises en avant
Theming
1.12.0
Mises en avant
Update notification
1.11.0
Mises en avant
Versions
1.14.0
Mises en avant
Video player
1.10.0
Mises en avant
Appointments
1.9.1
Auditing / Logging
1.11.0
Mises en avant
Contacts
3.5.1
Mises en avant
Dashboard
7.1.0
Mises en avant
Default encryption module
2.9.0
Mises en avant
Discourse integration
1.0.0
External storage support
1.12.0
Mises en avant
First run wizard
2.10.0
Mises en avant
LDAP user and group backend
1.11.0
Mises en avant
Mail
1.9.5
Mises en avant
Maps
0.1.8
Mises en avant
Markdown Editor
2.3.3
Notes
4.0.4
Mises en avant
Preview Generator
3.1.1
Recommendations
1.0.0
Mises en avant
Tasks
0.13.6
Mises en avant
Text
3.2.0
Mises en avant
Usage survey
1.9.0
Mises en avant
User status
1.1.1
Mises en avant
User usage report
1.5.0
Weather status
1.1.0
Mises en avant

**Comment by dartcafe** [comment]
duplicate #1559 

We still need more information. Seems to be a problem, if mails cannot be sent out (https://github.com/nextcloud/polls/issues/1559#issuecomment-845781640).

**Comment by dtcg** [comment]
I've got some (confusing) updates:

- error is **inconsistent**: today, the steps described above **work** and everything functions as it should.
- no SMTP error in the log. Possible hint?

**Comment by dartcafe** [comment]
Seems to be ralted: https://github.com/nextcloud/polls/issues/1559#issuecomment-845781640
I hope, I catched the errors correct.
