### ISSUE TITLE
[UX] [1.9.0 beta] Disallowed proposal hint is dispensable 

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1658]
Although I like the new proposal feature #496 its implementation needs improvement:

- The prominent "D" avatar (disallow's proposal) is present in the options wether proposals are allowed or not. When they are not, the hint is unnecessary. When proposals are allowed, you are always reminded of this possibility by the large green msg box with the button to add new options. In this case it would be enough when only the user added options show the avatar. IMHO the owner options don't need one.
- In date-based polls the proposal feature breaks the "shift all date options". Shifting dates is disabled (to prevent shifting of other user's proposals) also when proposals are disallowed.

-- 
Rolf

**Comment by dartcafe** [comment]
Which D? Please add a screenshot.

**Comment by dartcafe** [comment]
Erm. I am confused. This should not happen...

**Comment by dartcafe** [comment]
Argh. I found it. That was a migration error.
