### ISSUE TITLE
Add configuration option to allow non-admins to add options to a poll

### ISSUE THREAD

**Issue by tobiasstein** [nextcloud/polls#1664]
## Describe the goal you'd like to achieve

As a poll owner I want to be able to allow non-admin users (also via public link) to allow adding options to the poll.
At times the best ideas are someone others ideas and it also reduces management overhead for the poll to the owner.
This would also be a very democratic feature.

**Comment by dartcafe** [comment]
See next version or current beta: #496

**Comment by tobiasstein** [comment]
Duplicate of #496 and fixed in #1635.
Development is head of time, thanks!
I'll try the beta.
