### ISSUE TITLE
Allow to optionally add time and lenght of the appointment

### ISSUE THREAD

**Issue by tobiasstein** [nextcloud/polls#1665]
When adding a option to a poll, allow optionally to pick time and length.
This allows to chose between multiple options on the same day.

**Comment by dartcafe** [comment]
This is a feature of version 1.8.3 and already possible. Or I misunderstood you.

**Comment by tobiasstein** [comment]
@dartcafe: Thanks, i didn't notice the button in the date and time picker.
I close this feature request and open another to make already created options of poll editable.

**Comment by dartcafe** [comment]
@tobiasstein Editing of options will not be possible, because existing votes will get invalidated. Votes and options are connected together via the option text.
