### ISSUE TITLE
Generated link only useful if already logged in ("Access denied. App not enabled" )

### ISSUE THREAD

**Issue by jgrete** [nextcloud/polls#167]
Is there any chance to get links which are leading to a normal login procedure (if not already logged in) instead of presenting a "Access denied. App not enabled" ?

**Comment by dartcafe** [comment]
Hmm. I get redirected to the login page, if the app is not anabled. With the enabled app and a link to a poll for registered users, I get redirected too. 

Can you provide some more information to reproduce the bevavior?

**Comment by jgrete** [comment]
It seems to be an issue with NC 12.0.2. On a 12.0.3 Box it looks good, but in our company (NC 12.0.2) I'm getting "Access denied..." when I'm following the generated link, without being logged in.
The upgrade is still on my agenda, but will be done soon.
I'm posting my findings here or close this issue if 12.0.3 is working on that box
Thank you for investigating 
Juergen

**Comment by jgrete** [comment]
I've upgraded the 12.0.2 box to 12.0.3 and now it works!
Sorry...
Thanks again for investigating
Juergen
