### ISSUE TITLE
Polls not accessible when logged in as guest

### ISSUE THREAD

**Issue by intuadmin** [nextcloud/polls#1677]
### Polls shared to guest-users (app guests) are not accessible
**Describe the bug**
Polls shared by mail or by public link are not accessible if the user is logged using a guest account.

**To Reproduce**
1. Create a poll and share it by link.
2. Access poll using the link while not logged in (this works)
3. Create a guest account (app guests) an log in with this account.
4. Trying to access the poll again using the link from step 2 fails as long as the polls app is not whitelisted for guests.

The same problem occurs if the poll is shared with an already existing guest user.

**Expected behavior**
A user who can access a poll while not logged in should still be able to do so if logged in with a guest account. If the polls app is not whitelisted for guests this should only prevent guest users from creating new polls but not from responding to polls.

### Information about your polls installation
**Polls 1.8.3**

**installed from app store**

### Information about your Instance of Nextcloud

**Nextcloud version: 20.0.10**

**List of activated apps:**
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - announcementcenter: 4.0.1
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.2
  - circles: 0.20.9
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.7
  - documentserver_community: 0.1.9
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.4
  - guests: 1.6.3
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.4.2
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.8.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.7
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_retention: 1.3.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
```

**Comment by dartcafe** [comment]
> as the polls app is not whitelisted for guests.

As long as the app is not whitelisted, access to the polls app is denied by the system and the app is not even loaded.

**Comment by intuadmin** [comment]
> As long as the app is not whitelisted, access to the polls app is denied by the system and the app is not even loaded.

I think it is important to make a difference between responding to a poll that should be possible in any case and using the app (i.e. creating polls) that can be granted to guests by whitelisting the app.

**Comment by dartcafe** [comment]
Yep. But your issue is not solvable by the app. You maybe adress #1106 and #390

**Comment by intuadmin** [comment]
> But your issue is not solvable by the app.

Ok, I understand.
Looking through the issues of of the guests app I found [#380](https://github.com/nextcloud/guests/issues/380) that could help in the future.

**Comment by dartcafe** [comment]
Not sure, if this will help and when. But I think, we can close this one here. Right?

**Comment by intuadmin** [comment]
> Not sure, if this will help and when. But I think, we can close this one here. Right?

It's up to you. The problem still exists.

**Comment by dartcafe** [comment]
> It's up to you. The problem still exists.

Yes, but it is not solvable in this repo.
