### ISSUE TITLE
Certain Users/Groups cant be found via Share with Dialogue

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1681]
### What is going wrong?
Trying to share a Poll with a certain group or user. Entering the groups or users name gives no results and an Error in the Log (see below).

Some groups and users work fine but I wasnt able to pinpoint a problem, some groups work though users in that group dont.

Polls ist the only App with this behaviour.

Searches for shares in other App (ie files, forms) work as intended with all groups and users

### Information about your polls installation
**Polls version 1.8.3** (see apps page)

**Fresh installation or update from a prior version (from which one)?**
Update

**Nextcloud version:** (see Nextcloud admin page)
21.02

### Server configuration

**PHP version:**
7.4
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Nextcloud log (data/nextcloud.log)
OCA\Polls\Exceptions\MultipleContactsFound: Multiple contacts found for id xxx

/.../apps/polls/lib/Model/Contact.php - line 91:
    OCA\Polls\Model\Contact->loadContact()
 
/...//apps/polls/lib/Model/Contact.php - line 44:
     OCA\Polls\Model\Contact->getContact()

/.../apps/polls/lib/Model/Contact.php - line 135:
     OCA\Polls\Model\Contact->__construct()
 
 /.../apps/polls/lib/Model/UserGroupClass.php - line 208:
    OCA\Polls\Model\Contact::search()
 
 /.../apps/polls/lib/Service/SystemService.php - line 108:
     OCA\Polls\Model\UserGroupClass::search()
 
/.../apps/polls/lib/Controller/SystemController.php - line 54:
     OCA\Polls\Service\SystemService->getSiteUsersAndGroups()
 
 /.../lib/private/AppFramework/Http/Dispatcher.php - line 218:
     OCA\Polls\Controller\SystemController->userSearch()
 
/.../lib/private/AppFramework/Http/Dispatcher.php - line 127:
     OC\AppFramework\Http\Dispatcher->executeController()
 
/.../lib/private/AppFramework/App.php - line 157:
     OC\AppFramework\Http\Dispatcher->dispatch()
 
 /.../lib/private/Route/Router.php - line 302:
     OC\AppFramework\App::main()
 
/.../lib/base.php - line 993:
    OC\Route\Router->match()
 
 /.../index.php - line 37:
     OC::handleRequest()

**Comment by dartcafe** [comment]
Which version on the contacts app is used?

**Comment by tobyps** [comment]
Contactsapp: 3.5.1

**Comment by dartcafe** [comment]
related #1310

**Comment by tobyps** [comment]
> I guess, there are contacts with the same UID in multiple books. Are you able to confirm this? The UID is the ID, which is named in the error message.
> 
> > OCA\Polls\Exceptions\MultipleContactsFound: Multiple contacts found for id xxx

I should be able to check as I have admin rights but I wasnt able to locate the UIDs, can you point me in the right direction or what to search for as my google search didnt help me either in locating the UIDs.

What I can say at without checking the actual IDs. Apart from the Nextcloud users with have an adressbook with all members. And all users are in that adressbook though not all contacts in that adressbook are users.
But that fact doesnt seem to matter as a search returns both results if it works. 

In that adressbook there are users with umlauts, though they are found by the search (probably not relevant, but maybe interesting for the related problem).

**Comment by dartcafe** [comment]
The contacts are stored ion vcf-files inside the users' data directory. The filename is the UID. For example `BF211207-4622-42D2-8C1E-39D710620862.vcf`

**Comment by dartcafe** [comment]
> In that adressbook there are users with umlauts, though they are found by the search (probably not relevant, but maybe interesting for the related problem).

Umlauts are no problem generally, but with some LDAP implementations, as it seems. That's why I plan to change the search strategy. ATM the individual APIs are used and so we have to handle their individual behavior. Maybe the user search provided by the files_shares app solves this problems. 

The link to the related issue is just a reminder to solve and test both problems together.

**Comment by dartcafe** [comment]
The workaround will be released with version 1.9

**Comment by tobyps** [comment]
> 
> The contacts are stored ion vcf-files inside the users' data directory. The filename is the UID. For example `BF211207-4622-42D2-8C1E-39D710620862.vcf`
Thanks.
There are no contact information in any of the user data folders. 
I ran a search for vcf files and for specific IDs and found nothing.

Hopefully tonight I will be able to test a clompletely new installation of NC just to check if this might be connected to the Updates over the years (we started with NC14 and continously upgraded and moved Webhosters once) or any other "Altlasten". 
Though thats the first problem of that kind.

**Comment by dartcafe** [comment]
I was talking nonsense. The cards reside in the database in oc_cards

**Comment by tobyps** [comment]
Got it.
The NC Users are unique (their UIDs are their usernames ie UserA) but the Contacts have up to for identical UIDs like your example.
The etag seems to be unique for every entry.

Dont know if it helps/is relevant my Explanations/Speculations on the Duplicates:

The UIDs are identical if I copy a contact from one synchronized adressbook to another (necessary to share only relevant contacts, because sharing of contactgroups in a given adressbook wasnt possible when we set it up).
Though tha explains only half the copies.

My speculation for the rest, they are identical because the Adressbooks/Contacts are shared with 1 or 2 different users each.
Though if that would be true, every NC with shared Contacts would have that problem and I would have expected that the bug is found sooner.

**Comment by dartcafe** [comment]
I had something in mind, that it could be a situation, which occurs when copying contacts. The etag is not designed as identifier and so not usable. 

Possibly the combination of addressbook and UID could meet this situation. For the current moment, the error get's suppressed and the first of multiple found entries will be returned.

**Comment by tobyps** [comment]
Will the search return multiple results as long as they there UIDs are not identical?
ie I get NC UserA and contact UserA because those two have different UIDs but contact User A probably has multiple identical UIDs.

**Comment by dartcafe** [comment]
If there are multiple contacts with the same UID, the function throws an error and the serch aborts. 
With the comming version 1.9 the behavior changed, so that the search doesn't throw an error but returns the first entry. See commit above (https://github.com/nextcloud/polls/commit/234fad2164d966b4dfc75a3b1a97bedaef5721f5).

**Comment by tobyps** [comment]
Thanks, so if my understanding ist correct, in my example all entries would be found and displayed as they have different UIDs while all but the first identical UIDs are ignored.

**Comment by tobyps** [comment]
The workaround works, though not only the first but all identical entries are displayed.

The error is still written to the log, dont know if that is intended.

**Comment by dartcafe** [comment]
I think, this issue is outdated.
