### ISSUE TITLE
Extend API to make it more useful

### ISSUE THREAD

**Issue by noplanman** [nextcloud/polls#1689]
## Describe the goal you'd like to achieve
As a **poll owner**, I want to **be able to add option durations**, because **it helps to add proper options**.

## Describe possible solutions
Allow extra fields to be passed to the API when creating options (and the other fields too).

## Additional context
At the moment, as defined in [OptionApiController::add](https://github.com/nextcloud/polls/blob/83258402768577facfc0460fec72719341274e91/lib/Controller/OptionApiController.php#L70), only poll ID, timestamp and option text can be passed.

When creating an option on the web interface, a duration can be defined, so it would be very useful to make that available for API requests too.

As a workaround, I'm now making requests *as if i was logged in to the web interface*, passing along the necessary cookies for authentication. This allows me to pass ALL the necessary fields.

**Comment by dartcafe** [comment]
Yep, thanks. Forgot to update the API

**Comment by dartcafe** [comment]
For satisfying my curiosity: How are you using the API? I didn't believe that it is used right now. 
And congratulations: This was the first complete user story here. 😁

**Comment by noplanman** [comment]
> For satisfying my curiosity: How are you using the API? I didn't believe that it is used right now.

As explained [in the draft docs](https://github.com/nextcloud/polls/blob/master/docs/API_v1.0.md).

> And congratulations: This was the first complete user story here

😂

**Comment by dartcafe** [comment]
> As explained [in the draft docs](https://github.com/nextcloud/polls/blob/master/docs/API_v1.0.md).

Yes, ehm, I hoped so. 😬 I was curious about the use case.

**Comment by noplanman** [comment]
Aaah, sorry 😅 

I had to make a poll with a bunch of dates and it was too cumbersome to add them all on the web interface.

Also the web interface doesn't allow editing of options and when setting the time the sidebar cuts off part of the view, making it impossible for me to define the times.
