### ISSUE TITLE
Date fields broken in OC10 and polls 0.7.3

### ISSUE THREAD

**Issue by darootler** [nextcloud/polls#169]
Hi,

i just upgraded ownCloud to version 10 and polls to 0.7.3. After that the date fields seem broken:

![image](https://user-images.githubusercontent.com/11849583/31082450-56e030e6-a78f-11e7-85d7-13d55d33e3ad.png)

If you need more information please let me know.

Regards
Richard

**Comment by joergmschulz** [comment]
see #168 and others. will be fixed in next release. Try the current github master - works there already.

**Comment by dartcafe** [comment]
@v1r0x: Maybe a new release would be good to eliminate the error.
