### ISSUE TITLE
Add possibility to change options

### ISSUE THREAD

**Issue by ischiros** [nextcloud/polls#1696]
## Describe the goal you'd like to achieve
As a poll owner, I sometimes need to modify an option. Sometimes because I see a misspelling. Sometimes because after some time, it appears that it is needed to make an option more understandable.

## Describe possible solutions
Allow options modification.

## Additional context
If you consider that modifying the options may be "dangerous", a warning can be added if an option has been modified after the first vote.

**Comment by dartcafe** [comment]
You can simply delete the wrong one and create a corrected option.

**Comment by ischiros** [comment]
> You can simply delete the wrong one and create a corrected option.

If people have started to vote, we loose the answer. So, that's impossible.

**Comment by dartcafe** [comment]
> 
> If people have started to vote, we loose the answer. So, that's impossible.

That is what will happen, if you change the option text, because the votes are tied to it.

**Comment by ischiros** [comment]
Oh, I understand, then.
It's a pity, but it makes the modification impossible, then.
