### ISSUE TITLE
fail to update or install v1.9.4 using occ

### ISSUE THREAD

**Issue by uvolmer** [nextcloud/polls#1701]
### What is going wrong?

root@cloud:~# occ app:update --verbose polls 
polls new version available: 1.9.4
polls couldn't be updated

gives me a error. Without further informations.

After that, I tried to deinstall and reinstall polls:

root@cloud:~# occ app:remove polls
polls disabled
polls 1.8.3 removed
root@cloud:~# occ app:install polls
Error: Could not extract app polls: Out-of-path file extraction {/tmp/oc_tmp_rjw0dd-folder/polls/vendor/bin/commonmark --> ../league/commonmark/bin/commonmark}

**Nextcloud version:** (see Nextcloud admin page)

```
root@cloud:~# occ status
  - installed: true
  - version: 21.0.2.1
  - versionstring: 21.0.2
  - edition: 
```

**List of activated apps:**
```
root@cloud:~# occ app:list
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.2.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - maps: 0.1.8
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - spreed: 11.2.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - files_external
  - sharebymail
  - user_ldap

```

**Nextcloud configuration:**
```
cloud:~# occ config:list system
{
    "system": {
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "installed": true,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "cloud.u-v.de"
        ],
        "maxZipInputSize": 5242880000,
        "allowZipDownload": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.u-v.de",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "app_install_overwrite": [
            "documents",
            "spreed",
            "whiteboard"
        ],
        "mysql.utf8mb4": true,
        "enable_avatars": false,
        "auth.bruteforce.protection.enabled": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Server configuration

**Database:**
Package: mariadb-server
Version: 1:10.3.27-0+deb10u1

**PHP version:**

root@cloud:~# php -v
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:**
Desktop/mobile phone/ tablet/...

**Comment by dartcafe** [comment]
Yep. See https://github.com/nextcloud/polls/issues/1695#issuecomment-856004315 also. Working on a package replacement.

**Comment by bcutter** [comment]
Copy that. Couldn´t update 1.8.3 to 1.9.4...

```
Exception: Could  not extract app polls: Out-of-path file extraction  {/tmp/oc_tmp_XXXXXX-folder/polls/vendor/bin/commonmark -->  ../league/commonmark/bin/commonmark}
```

So I thought I´d be smart and remove and simply install it again but...

```
Error: Could not extract app polls: Out-of-path file extraction {/tmp/oc_tmp_XXXXXX-folder/polls/vendor/bin/commonmark --> ../league/commonmark/bin/commonmark}
```

So I´m waiting for a fixed package too.

**Comment by elearningdienst** [comment]
Same here. I'll wait in patience but If I can do something do degug, let me now.

**Comment by dartcafe** [comment]
See the comments in #1695 
Manually installing is still possible with the packages polls-1.9.4.zip|tar.gz from the release page https://github.com/nextcloud/polls/releases/tag/v1.9.4

**Comment by bcutter** [comment]
How to manually install apps in NC? Never had too... where to download them, what commands needed to extract until ready to install (use which commands - usual "occ app:install polls")? Quite complicated :-D

**Comment by elearningdienst** [comment]
> See the comments in #1695
> Manually installing is still possible with the packages polls-1.9.4.zip|tar.gz from the release page https://github.com/nextcloud/polls/releases/tag/v1.9.4

Unfortunately I get an error while activating a manually installed app: `Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.`

**Comment by dartcafe** [comment]
> 
> 
> How to manually install apps in NC? Never had too... where to download them to (target dir), what commands needed to extract until ready to install (use which commands - usual "occ app:install polls")? Quite complicated :-D

Then just don't do it, if you are not experienced to do so. Keep calm, the update will come, as soon as @v1r0x is available.

**Comment by dartcafe** [comment]
> Unfortunately I get an error while activating a manually installed app: `Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.`

Maybe, you had a beta version installed. The release migration correctly sets the default of the colum to `'default' => ''`

You can fix this by adding a default in the table configuration of your db.

**Comment by elearningdienst** [comment]
Thanks. No beta, just the last AppStore version of polls. I Installed the 1.8.3 and it works again.

**Comment by franconianmetal** [comment]
official nc app download 1.9.4 is not a valid tar file
on git here it is

pls confirm

**Comment by shaaati** [comment]
> > Unfortunately I get an error while activating a manually installed app: `Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.`
> 
> Maybe, you had a beta version installed. The release migration correctly sets the default of the colum to `'default' => ''`
> 
> You can fix this by adding a default = '' for the column `owner` in the table configuration of your db.

I get the same error message when trying to update manually. As far as I can see in my database, "oc_polls_options" does not have an "owner" column. I found the owner in "oc_polls_polls", but adding the default value there does not help. Is this expected?

**Comment by jurgenhaas** [comment]
Same here, had no beta ever and it just seems that the upgrade script for polls is failing to set the database definition correctly.

**Comment by dartcafe** [comment]
Something breaking has changed in the migration without explicit notice. (https://github.com/nextcloud/server/issues/23174)
Strange, that the tests don't throw an error. I didn't had the time to verify, but I think that a fresh install doesn't has this issue, but updates have.

I updated the migration step in version 1.9.5 -> https://github.com/nextcloud/polls/releases/tag/v1.9.5
If someone could confirm, that the migration works...?
Download of the new package: https://github.com/nextcloud/polls/releases/download/v1.9.5/polls-1.9.5.zip

**Comment by Bibo-Joshi** [comment]
Thanks for the quick update @dartcafe !

I had removed the pollls app when updating 1.9.3 -> 1.9.4 failed in hopes of a fresh install fixing the problem.
Now trying a fresh install with 1.9.5 gives me 

```
Error: Could not extract app polls: Out-of-path file extraction {/tmp/oc_tmp_XXX-folder/polls/vendor/bin/commonmark --> ../league/commonmark/bin/commonmark}
```

both via the the GUI and via `occ app:install polls`.

**Comment by dartcafe** [comment]
1.9.5 only manually, until it appears in the appstore

You just have do copy the contents of the package (polls-1.9.5.zip) to the apps folder of your nextcloud instance. You can delete the folder apps/polls before.

> ```
> Error: Could not extract app polls: Out-of-path file extraction {/tmp/oc_tmp_XXX-folder/polls/vendor/bin/commonmark --> ../league/commonmark/bin/commonmark}
> ```

This comes from the appstore release.

**Comment by elearningdienst** [comment]
> I updated the migration step in version 1.9.5 -> https://github.com/nextcloud/polls/releases/tag/v1.9.5
> If someone could confirm, that the migration works...?
> Download of the new package: https://github.com/nextcloud/polls/releases/download/v1.9.5/polls-1.9.5.zip

I did that manually and it works without errors. Great Job, thanks a lot!

**Comment by shaaati** [comment]
@elearningdienst beat my to it by about a minute ;). I also did the manual update and everything seems to work now. Thanks for your awesome resonse times @dartcafe  :).

**Comment by Bibo-Joshi** [comment]
> 1.9.5 only manually, until it appears in the appstore

Okay, got it. 1.9.5 wasalready listed at https://apps.nextcloud.com/apps/polls (and already was before I posted my previous comment) but apparently there was some caching happening somewhere or so, now occ also worked fine for me. Many thanks!

**Comment by dartcafe** [comment]
Thanks to @v1r0x, who fired this to the appstore, faster than light. 😁

**Comment by dartcafe** [comment]
done and closed! Thanks for always great supporting...

**Comment by v1r0x** [comment]
> Thanks to @v1r0x, who fired this to the appstore, faster than light. grin

In the right place at the right time :wink: 
Thank you for your great releases and fast fixes :tada: :rocket:
