### ISSUE TITLE
Option to allow public participants to change their answers without knowing their personal link

### ISSUE THREAD

**Issue by SmartPappnase** [nextcloud/polls#1706]
If I share a poll to schedule an appointment I use a public link so that everyone can take part. People using that link are asked to choose a new username. Afterwards they can add their choices and close the site again. (nobody thinks of storing their personal link, which is generated on entering a new username)

If they want to change something later on, they click on the same public link and are asked to insert a new username (they can't choose their old username). This behaviour limites the usefulness as a tool to coordinate an appointment. Things change... availability, options etc... There needs to be an easy option to change their answers later on.

In dudle even a public user has the option to claim to be a certain user and change the inputs accordingly. Usually that is not an issue if you try to find an appointment. People don't usually mess with others inputs.
![example_dudle](https://user-images.githubusercontent.com/20972078/121152742-c34f8800-c845-11eb-99d8-04ed1da62939.png)

The polls app could have an option to allow everyone using the public link (and not being logged in with a nextcloud account) to claim to be every external participant they want. Probably the easiest way of doing this would be to ask them if they want to claim a user if they put in the same username (unless it belongs to a nextcloud user).

Alternatively the polls app could automatically recognise a former participant even if the public link is used (cookies?).

**Comment by dartcafe** [comment]
We have cocurring requests on this and so we decided, to go the way with the personal link and prevent changing votes by everyone, who has access via the public link. 

By adding an email address, the link is sent to the participant for convenience. I think, this works out good.

**Comment by kevinde91** [comment]
@dartcafe I think there could be created a cookie which contains the personal link, if the user (let's call him John Doe) doesn't want to share his Mail-address.

When revisiting, the apps checks this cookie and asks the user something like "editing as John Doe?" for the case, that another user uses the same device.

**Comment by dartcafe** [comment]
@kevinde91  
The upcomming version allows to reenter the public poll via stored cookie (see #2351; I should link this issue).

> When revisiting, the apps checks this cookie and asks the user something like "editing as John Doe?" for the case, that another user uses the same device.

Thanks for your suggestion. Could you please [open another issue](https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=feature_request.md) basing on the implementation in #2351 and add, what should happen after answering the question?
