### ISSUE TITLE
time range - preselect current day instead of 1. Jan. 1970

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/polls#1707]
## Describe the goal you'd like to achieve

1. click on "Datumsoption hinzufügen"
2. click on "Bereich auswählen"
3. date range picker shows now current month + next month but the "1. Jan. 1970" is already set
4. click on "Zeit hinzufügen" (without clicking in the range modals before)
5. you now can choose time of 1. Jan. 1970

## Describe possible solutions

can we preselect the current day instead of 1. Jan. 1970?
this will give use the benefit that you not have to click in the month modals for current day and also you
are not lost in the year 1970 when you want to change the date when your come from the time-picker or when you click "Zeit entfernen".

**Comment by dartcafe** [comment]
I think, with the current implementation in 2.0.2 we solved this issue...

**Comment by kinimodmeyer** [comment]
at looked again (we have 2.0.2) and this behavior is like described.

**Comment by dartcafe** [comment]
Adding a new option starts with no selected day. I am not able to select 
![17-06-_2021_22-14-22](https://user-images.githubusercontent.com/26707476/122466373-8445d300-cfb9-11eb-9370-8cf4d76a0aab.gif)
![17-06-_2021_22-17-07](https://user-images.githubusercontent.com/26707476/122466593-cbcc5f00-cfb9-11eb-9412-89757dfb7761.gif)

**Comment by dartcafe** [comment]
Ahhh. Correction. It still happens, if a range is selected.
