### ISSUE TITLE
dont stop item deletion if leaving the page

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/polls#1708]
## Describe the goal you'd like to achieve

when i click on a item to delete it, it will get deleted after ~6 seconds.
when i leave the site before this ~6 seconds the item not get deleted.

## Describe possible solutions

when i deleted something it should get deleted even when i not wait for it.

## Additional context

in my opionion this is a design problem. the deletion at the moment works only on client js side.
when someone click the delete button it should mark the item as deleted with a delete timestamp in the database.
when someone stops the deletion you call the backend again to set the delete timestamp to 0

**Comment by dartcafe** [comment]
Yes, but this will cause another request to the server, which can fail due to latency or server failure. The timeout is a security function to avoid accidentially deleting an item, which cannot be easily restored. 

But I agree, that for sure there is room for improvement.
