### ISSUE TITLE
Links/URLs in poll options should be clickable 

### ISSUE THREAD

**Issue by elearningdienst** [nextcloud/polls#1709]
## Describe the goal you'd like to achieve
I use polls in e-learning settings. For role plays in an educational context, you distribute the roles in advance. This requires role cards and usually a description of the situation. But how do you do that in online settings?

It is comparatively easy to distribute the situation in which the game is being played, since it is actually the same for everyone. The challenge is that when distributing the roles, not everyone knows the individual role contents and is therefore genuinely challenged. Especially in adult education, the role plays are otherwise too easy to see through.

My Workflow:

First you need a place to store the role descriptions. After all, they should be retrievable in the end. I decided to use a pad in a CodiMD (for several reasons, e.g. possible collaborative work). For each role I create an own pad. (Example in German language)

Customer 1 https://codimd.elearningdienst.de/s/8FFvt5JRc#
Customer 2 https://codimd.elearningdienst.de/s/n8cAEhyjf#
Craftsmen https://codimd.elearningdienst.de/s/J0FV1B81r#

Then create a poll with a basic setting and the link to the roles:
![grafik](https://user-images.githubusercontent.com/49334345/121181271-19cabf80-c862-11eb-860a-3801c79b3c98.png)

This is actually very simple. Here you create the roles as a selection option. I just put the name of the role and the link to the pad. Then you create a public share that you can share with your participants.

![grafik](https://user-images.githubusercontent.com/49334345/121180952-c5274480-c861-11eb-90e6-5e77e99ed0b7.png)

The publicly generated link can be accessed and selected by participants. The available options reduce continuously.

![grafik](https://user-images.githubusercontent.com/49334345/121181581-775f0c00-c862-11eb-97b5-2c6b225033f1.png)

But here is also the only catch in the workflow. **The link in the selection option cannot be clicked.** The participant have to copy it out and then open it manually in a browser.

**As a poll participant, I want to be able to click the link in an new tab and not copy paste it via right click.**

![grafik](https://user-images.githubusercontent.com/49334345/121182150-16840380-c863-11eb-9943-ff371cd93bff.png)

## Describe possible solutions

Make - at least as an optional possibility - links/URLs in selection options in polls clickable.  

## Additional context
If you able to understand German you can take a look on my blog on that topic. I described how I use that possibility with nextcloud polls. Feel free to remix, its OER in CC BY-SA 4.0: https://www.ulrichivens.de/index.php/2021/05/13/rollenkarten-fuer-rollenspiele-online-verteilen-mit-nextcloud-polls/

**Comment by dartcafe** [comment]
closing if favor of #2102
