### ISSUE TITLE
incorrect format of the day number

### ISSUE THREAD

**Issue by FPasca** [nextcloud/polls#1711]
### What is going wrong?
In Italian language the day number of month is for example 9, writing 9° is a mistake.
This makes the application unusable for professional purposes.
This error was already present in version 1.8.3.
Thanks for beautifull app.
![screenshot](https://user-images.githubusercontent.com/37551432/121261135-96858a00-c8b2-11eb-8e46-874b2986ee07.png)

**Comment by FPasca** [comment]
This is the correct format:
![screenshot1](https://user-images.githubusercontent.com/37551432/121437057-f303aa80-c981-11eb-84a5-690c57bef30f.png)
Could you fix date format, please :) or tell me where to find code for that?
Thank you!

**Comment by dartcafe** [comment]
You can find the formatting here, but the layout is defined from moment.
https://github.com/nextcloud/polls/blob/1dbf7338310e7d77913fbe579d6b1365e14f7d0e/src/js/components/Options/OptionItem.vue#L126-L147

**Comment by FPasca** [comment]
OK, Thanks!

**Comment by FPasca** [comment]
Changed from:
```
month: from.format('MMM [ \']YY'),
day: from.format('Do'),
```
to:
```
month: from.format('MMM YYYY'),
day: from.format('D')
```
now date is show as expected.
Very Thanks!

**Comment by dartcafe** [comment]
I am planning to switch `day: from.format('Do'),` to `day: from.format('D'),` in the next release, but still prefer the shorter display of the year.

**Comment by FPasca** [comment]
Right, but I'm afraid that users may confuse the short year with the day. At least until 2031. :D
I have had users who do not notice the horizontal scroll bar :D
I'll do some a tests by removing the year or putting day on top and month and short year below.

**Comment by FPasca** [comment]
This is the layout I like, it seems like a good compromise between short year visualization and does not confuse the users.
I think
![Screen2](https://user-images.githubusercontent.com/37551432/122050487-cae1d480-cde3-11eb-9a18-8cebb406a222.png)
