### ISSUE TITLE
Can't enable app : Class `OCA\Polls\AppInfo\Application20` not found 

### ISSUE THREAD

**Issue by acsfer** [nextcloud/polls#1713]
Nextcloud 21.0.2

```
[index] Error: Exception: Class 'OCA\Polls\AppInfo\Application20' not found at <<closure>>

0. /lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
1. /lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
2. /lib/base.php line 993
   OC\Route\Router->match("/settings/apps/enable")
3. /index.php line 37
   OC::handleRequest()

POST /settings/apps/enable
```

**Comment by dartcafe** [comment]
I could only guess, what is wrong with your installation. Please fill out the issue form.

**Comment by supremesyntax** [comment]
same here after update via web ui there was a 505 server error and i had to disable polls via occ command to resume normal operation.
logs showed the same error

**Comment by dartcafe** [comment]
I would really try to help, but without information about the circumstances, it is not possible.

**Comment by supremesyntax** [comment]
I re-enabled the app via web ui and now it seems to work fine. 
Seems to be a php cache related issue because Application20.php has been there in v1.8.3 which implemented class Application20.

**Comment by dartcafe** [comment]
> I re-enabled the app via web ui and now it seems to work fine.
> Seems to be a php cache related issue because Application20.php has been there in v1.8.3 which implemented class Application20.

That's what confused me, because Application20 was removed in 1.9 and is not referenced anywhere. But the PHP Cache is a good hint.

**Comment by acsfer** [comment]
Fixed for me with https://github.com/nextcloud/polls/issues/1732
