### ISSUE TITLE
Update to 1.9.5 broke my polls

### ISSUE THREAD

**Issue by dtcg** [nextcloud/polls#1714]
Just updated to polls 1.9.5 (from previous version through appstore) and now all my polls are empty ! Participant names are visible but all their choices are gone. Not cool... Any way to restore / recover polls versions ?

- nextcloud 21.0.0
- **PHP version:** 7.4.16
- problem is server-related : it happens on other computers
- nothing special in the logs

**Comment by dartcafe** [comment]
Make sure, that the browser cache is cleared. I the problem still exists, please provide more information. There is an issue template, if you report a bug: https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=bug_report.md

**Comment by BadAngelZ** [comment]
Same problem here, I add to manually remove the "polls" folder from the app. Without doing this nexcloud complains that:
`{"reqId":"ZU8iRQlmgu6jxDuX1zbi","level":3,"time":"2021-06-10T21:32:18+00:00","remoteAddr":"82.65.249.224","user":"jerome","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found at /usr/share/nginx/nextcloud/apps/polls/lib/AppInfo/Application.php#37","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"19.0.12.0"}
`

I have read somewhere that :+1:
`OCP\AppFramework\Bootstrap\IBootstrap and user_status app are new in Nextcloud 20. If you see such a warning on Nextcloud 19 something very weird is going on.`

[https://github.com/nextcloud/server/issues/24286](url)

So it seems that polls 1.9.5 uses function / methods that only exist in Nextcloud 20

**Comment by dartcafe** [comment]
> Sorry I would have better open another ticket

Yes please and please use the form.

**Comment by dartcafe** [comment]
@BadAngelZ See #1710

**Comment by dartcafe** [comment]
Closing due to missing information. Feel free to open another issue, if this still exists and use the issue form. Thanks.
