### ISSUE TITLE
v1.9.6 Release as v2.0.0 in app store

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/polls#1725]
https://apps.nextcloud.com/apps/polls say it is 2.0.0 but is 1.9.6.
is this correct?

**Comment by dartcafe** [comment]
@v1r0x Did you pack the package from the 1.9.6 tag? From stable-1.9. 

The 2.0.0 is not ready for release.

**Comment by v1r0x** [comment]
I built it from 1.9.6 tag. This has indeed the wrong version and is set to 2.0.0 in `appinfo/info.xml`. I can rebuild it from stable-1.9 branch

**Comment by dartcafe** [comment]
Yes please. Can you remove 1.9.5 from the store?

**Comment by dartcafe** [comment]
The package, which is offered via the apps page inside NC is 2.0.0. The downloadable packages direct to the release packages. Something didn't work out here.

**Comment by dartcafe** [comment]
done. Update is released.
