### ISSUE TITLE
Suggestion: change "update failed message" link to point to the app polls repo, and not the nextcloud server repo

### ISSUE THREAD

**Issue by ei8fdb** [nextcloud/polls#1726]
When I tried to update to 2.0.0 from 1.9.4 via the web interface, I hit https://github.com/nextcloud/polls/issues/1723.

At the bottom of the page was a "report this to the nextcloud community" (or something similar - sorry I didn't take a screenshot), which brought me to https://github.com/nextcloud/server/

I didn't think this was the right place to go - my issue was with updating the Polls app. After this I wasn't sure where to go, so I came here.

Is this message under the control of the Polls app? If so, I suggest the link be changed to bring the user to here (https://github.com/nextcloud/polls/).

**Comment by dartcafe** [comment]
I have no idea, where the information is genereated. The links in the package are here: 
https://github.com/nextcloud/polls/blob/c0ac030ab1f55b2615779f789bf3151e35b738dd/appinfo/info.xml#L16-L21
So I think, we cannot control that from the app.
