### ISSUE TITLE
Current Version 2.0.0 and possibly 1.9.5 are defect.

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1727]
Acidentially, the dev version 2.0 made it to the appstore, which should not happen. 
A fix will be release over the weekend, so please stay patient. 
#### Sorry for the circumstances. 

See #1723 and #1725

**Comment by mMuck** [comment]
Could happen.
Would be nice to disable the update from the store ASAP to avoid update notifications, updates and more users running into the same issues mentioned. Is this something for the store maintainer/admins?

**Comment by dartcafe** [comment]
Only @v1r0x has access to the appstore, but if I come through it like with #1730, I think we will this fix smothly in short time.

**Comment by dartcafe** [comment]
Updates : #1730 and #1732

**Comment by nursoda** [comment]
Is it safe to downgrade? Just delete the app and reinstall from the store?

**Comment by dartcafe** [comment]
@v1r0x Are you able to project a release date, so we can help users to get outof this trouble?

**Comment by v1r0x** [comment]
Sorry, weekend was kinda busy. 1.9.7 and 2.0.2 are out now :tada: 
Thanks to everyone testing the releases and your reports. And especially a huge thanks to @dartcafe for his hard and fast work! :metal:

**Comment by dartcafe** [comment]
No problem. Was just curious, when you have the time to fire the versions.... Thanks!!
