### ISSUE TITLE
Give poll owner the option to require poll participants to provide an email address

### ISSUE THREAD

**Issue by ei8fdb** [nextcloud/polls#1728]
## Describe the goal you'd like to achieve
As a poll owner, I want to be able to require poll participants to give me their email addresses, because it helps me to know who to contact to follow-up with them.

## Describe possible solutions
Essentially give an option for the poll owner to require poll participants provide their email addresses.

## Additional context
I use Polls for schedule UX research sessions. I will email a list of people (I *do* know who will see it) /publicise the research on the Internet (I *don't* know who will see it), and ask them to choose the date / time from a list. I need to make sure they give me their email address so I can reply to them.

### Possible designs
![image](https://user-images.githubusercontent.com/1899506/121711141-9071f200-cada-11eb-816f-fbe0b4a3679d.png)

![image](https://user-images.githubusercontent.com/1899506/121710922-57d21880-cada-11eb-8512-dc883b5c81c6.png)

**Comment by dartcafe** [comment]
related #1419 and #1518
