### ISSUE TITLE
Update for NC19 to v1.9.7

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1730]
## This is a bugfix which addresses the problem for the falsely released version 1.9.5, which is not compatible with Nextcloud 19
Release: https://github.com/nextcloud/polls/releases/tag/v1.9.7
Download ZIP: https://github.com/nextcloud/polls/releases/download/v1.9.7/polls-1.9.7.zip
Download TAR.GZ: https://github.com/nextcloud/polls/releases/download/v1.9.7/polls-1.9.7.tar.gz

Addresses #1730 

### Help wanted
Anyone, who ran into this update (from 1.8.3 to 1.9.5) and is able to confirm, that the problem is solved by this update, is highly welcome. 

This updated was positively tested with NC19 and an upgrade path 1.8.3 -> 1.9.5 -> **1.9.7**.

### Details: 
* this version is identically to version 1.8.3 (downgrade)
* only compatible with Nextcloud 19
* This update removes the possibly created columns
  * `allow_proposals` in `polls_polls`,
  * `use_no` in `polls_polls`,
  * `proposals_expire` in `polls_polls`,
  * `owner` in `polls_options` and
  * `released` in `polls_options`

Additionally change to prevent #1723, since the migrationService doesn't allow `notNull=true` and `default='' anymore`.

### To update the polls version manually: 
* disable polls
* delete `../apps/polls` in your Nextcloud installation
* extract the contents of the package (after it is available) to `../apps` in your Nextcloud installation, You should find a fresh created folder `polls`in your `apps` folder
* enable polls

**Comment by unnilennium** [comment]
works great, thanks
disclaimer, I had already removed the extra table column, so my verification does not include this part, but I have noe more updates proposed, and the use of polls and NC is stable.

**Comment by dartcafe** [comment]
@v1r0x I tested some more combinations. The CI test were all good and I saw no issues. 
You can build this release from the head of branch `stable-1.8` and fire it up to the appstore (tag v1.9.7)

**Comment by g-work** [comment]
Worked for me.
But it took me hours to find out that Polls was causing the "Internal server error"...

**Comment by v1r0x** [comment]
Sorry, weekend was kinda busy. 1.9.7 and 2.0.2 are out now :tada: 
Thanks to everyone testing the releases and your reports. And especially a huge thanks to @dartcafe for his hard and fast work! :metal:

**Comment by pierreozoux** [comment]
@v1r0x no need to apologize, we all need nice weekends to relax!

Thanks everybody for the quickfix!

**Comment by dartcafe** [comment]
@v1r0x Version 2.0.2 is not in the appstore... 

![grafik](https://user-images.githubusercontent.com/26707476/121868718-9a296e80-cd01-11eb-9748-1e26d4c9258f.png)

NC102 and NC21 should offer version 2.0.2 from branch `stable-1.9`

**Comment by v1r0x** [comment]
@dartcafe I thought I never checked-otu `stable-1.9` and I'm up-to-date :facepalm: 
Now 2.0.2 is out for NC 20 and NC 21.

**Comment by dartcafe** [comment]
Had a quick look. Seems to work properly, even whan updating NC19 to NC20.
