### ISSUE TITLE
Error: Required parameter follows optional parameter

### ISSUE THREAD

**Issue by nursoda** [nextcloud/polls#1733]
### What is going wrong?
**Describe the bug**
The Log is flooded with Errors:

Error: Required  parameter $subscribed follows optional parameter $pollId at  apps/polls/lib/Service/SubscriptionService.php#72
Error: Required  parameter $message follows optional parameter $pollId at  apps/polls/lib/Service/CommentService.php#84

**To Reproduce**
1. Install Polls on NC 21
2. View Log

### Information about your Instance of Nextcloud
**Nextcloud version:** 21.0.2

### Server configuration
**PHP version:** 8.0.7

**Comment by dartcafe** [comment]
Fixed with a quick fix... Good night

**Comment by dartcafe** [comment]
Fixed with update to 2.0.2
