### ISSUE TITLE
Update Error (V 2.0.0)

### ISSUE THREAD

**Issue by joesch2** [nextcloud/polls#1735]
Dear all,

After the update to version 2.0.0, the following error occurred during the subsequent update (my nextcloud-Version: 21.0.2):

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Delete duplicates
InvalidArgumentException: Column name "nc_polls_options"."owner" is NotNull, but has empty string or null as default.
Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

Greatings, joesch

**Comment by winkelband** [comment]
Same problem here.
```sql
SELECT owner FROM oc_polls_options;
```
returns the error `Unknown column 'owner' in 'field list'`.
I assume something like the following should fix this and the upgrade process should continue:
```sql
ALTER TABLE oc_polls_options ADD owner varchar(255) NOT NULL;
```

**Comment by Cellophile** [comment]
Same problem here. NC 21.0.2, polls version 1.8.2 to 2.0.0.
There is no 'owner' column in oc_polls_options. 

Préparation de la mise à jour
Réglage du niveau de journalisation à "déboguage"
Mode de maintenance activé
Étape de réparation : Repair MySQL collation
Informations de réparation : All tables already have the correct collation -> nothing to do
Étape de réparation : Repair SQLite autoincrement
Étape de réparation : Copy data from accounts table when migrating from ownCloud
Étape de réparation : Drop account terms table when migrating from ownCloud
Mise à jour du schéma de la base de données
Base de données mise à jour
Étape de réparation : Delete duplicates
**InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.**

Result : I suppress polls...

**Comment by amadeous** [comment]
Same issue on my side with on NextCloud 21.0.1 when upgrading Polls to 2.0.0. Applied the same fix as @winkelband for now.

**Comment by dartcafe** [comment]
duplicate #1727
