### ISSUE TITLE
Polls Update scheitert

### ISSUE THREAD

**Issue by skipperkm** [nextcloud/polls#1736]
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Delete duplicates
InvalidArgumentException: Column name "oc_polls_options"."owner" is NotNull, but has empty string or null as default.

**Comment by dartcafe** [comment]
duplicate #1727
