### ISSUE TITLE
Baking new release 0.8.0

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#175]
ToDos: 
* [x] Create 0.8 milestone for the project
* [x] Create 0.8.1 milestone for the project
* [x] Create 0.9 milestone for the project
* [X] Merging #171 
* [X] Merging #166 
* [X] Merging #174 
* [X] Removing unnessesary files
* [x] Final tests
* [X] Replace SCSS files with compiled CSS for compatibility with OC and NC 11
* [x] Update Package on apps.nextcloud.com (this is still 0.7.2)
* [x] Build package for marketplace.owncloud.com
* [x] Update CHANGELOG.md and https://github.com/nextcloud/polls/releases/tag/0.7.3b
* [ ] Close the fixed issues

**Comment by dartcafe** [comment]
@v1r0x What do you think?

**Comment by joergmschulz** [comment]
this would be a 0.8, I presume. 
Which is the Fork where testing is needed most, currently?

**Comment by v1r0x** [comment]
@dartcafe I agree with @joergmschulz. A lot of (visual) changes and code changes. 0.8 is good. Maybe even 1.0, since it has all basic features and good looking UI. :)

**Comment by dartcafe** [comment]
0.8 is ok. But there is lot work to do. I would like to rewrite the goto.tmpl.php to change to flexbox as well and the create/edit page needs some enhancment (rewrite) too. At least the js code is not that easy to understand. So I think we have one more milestone before the 1.0. 

The #166 is ok for testing and possibly for merging. 

But we have to think about the OC compatibilty, because NC can compile SCSS to CSS, but OC cannot.  So we have to make a separate relese for OC with compiled CSS files.

As far as I see @splitt3r is doing some backend work in #171 and is preparing continuous integration. But that's definitly beyound my skills, which are quite poor for the coding.

**Comment by v1r0x** [comment]
Ok, 0.8 then :)
Should "we" (you ;)) rewrite the other templates before 0.8 or in 0.8.x?

Sorry for the JS-code. Is one of my first JS/jQuery-Code 😅 

> The #166 is ok for testing and possibly for merging.

I try to review it the next days.

> But we have to think about the OC compatibilty, because NC can compile SCSS to CSS, but OC cannot. So we have to make a separate relese for OC with compiled CSS files.

Separate release is ok I think. NC and OC need modified zips for the app stores anyway.

**Comment by dartcafe** [comment]
Don't worry about the code. I does what it should do. No rewrite before 0.8. I save this for the next milestones. I had to unerstand some more things about Nextcloud's API and the way the NC apps works. I thing I got deeper in in, so I can try to rewrite the Polls page. In the end, I have to change from the row orientation to a cloumn orientation, because the width of the header cells is variable. 

Another attempt can be using grids, but IE and edge is poor with the support for now. Other browsers seem to support grids. 

For #166 I commited the last changes. No further coding in plan for now before the release. The PR is big enough.

**Comment by dartcafe** [comment]
Hey @splitt3r. Looks great, but I do not know how to handle it right now. I fear we have not enough tests and I don't know how to write them. Will be a step for my next evolution. 

As far as I see, it is valid for your branch, right? So we have to install it for the original master branch? 

After that I try to understand, how it works.

**Comment by splitt3r** [comment]
I think it would be a good idea to create some tickets with all the refactor tasks so we can split the tasks and update the progress.

**Comment by dartcafe** [comment]
@v1r0x Can you add some milestones for planning and creating the changelog?

**Comment by splitt3r** [comment]
@MorrisJobke is it possible to activate Transifx and Travis CI for this repo? Can you help us setting up Transifex?

**Comment by dartcafe** [comment]
OK. As far as I see, #176 is merged to rc-0.8 and #171 directs now to rc-0.8. So if there are no more issues or conflicts, I would merge #171 to rc-0.8 branch, so we have an consolidated branch for testing.

**Comment by splitt3r** [comment]
Sounds good. I think we won´t need #166 anymore then or are there any changes left not in RC-0.8? The workflow should be to merge everything in RC-0.8 and finally merge RC-0.8 in master.

**Comment by dartcafe** [comment]
@v1r0x I think it is your part to make releases, right? I don't know how to do that.

**Comment by splitt3r** [comment]
@dartcafe [this](https://github.com/nextcloud/polls/blob/master/screenshots/overview.png) screenshot is outdated isn´t it? And could you remove the mouse pointer [here](https://github.com/nextcloud/polls/blob/master/screenshots/new-poll.png) 😀

**Comment by v1r0x** [comment]
Thanks for the changelog @splitt3r ! I'm not sure whether the list of changes is complete or not. Could you make a PR so we can discuss the completeness there?

@dartcafe Will release a new version after the changelog is updated.

**Comment by v1r0x** [comment]
Anybody ready for a release?

**Comment by jancborchardt** [comment]
@splitt3r I can't add Travis or Transifex (or don't know how). Could you ask in #nextcloud-dev if someone knows? Otherwise cc'ing @MorrisJobke (on vacation) and @LukasReschke

**Comment by dartcafe** [comment]
@v1r0x Sorry. Found a bug in the css and commited the minor fix to master. No more issues by me.

**Comment by v1r0x** [comment]
@dartcafe thanks. I'm not at home this weekend. Try to release the new version on the appstore on Sunday.

**Comment by dartcafe** [comment]
BTW: Can you add me to the collaborateurs in the settings settings. I want to know, if I can add travis to the project. If not, you have to get it via the marketplace.

**Comment by splitt3r** [comment]
No we simply need one of the org admins to activate it.

**Comment by v1r0x** [comment]
@dartcafe done :)

**Comment by dartcafe** [comment]
Is it possible to make different releases? I.e. for OC and NC?

**Comment by v1r0x** [comment]
One release and two modified uploaded zips should be best

**Comment by dartcafe** [comment]
🍾

**Comment by v1r0x** [comment]
I can sign the tar.gz for nextcloud only at home. New version should be available from the app store tonight :)

For the owncloud release maybe @kdslkdsaldsal or @hurradieweltgehtunter (#128) can help here?

**Comment by v1r0x** [comment]
0.8.0 is released on nextcloud app store :)
https://apps.nextcloud.com/apps/polls

**Comment by kdslkdsaldsal** [comment]
@v1r0x I don't know the marketplace of ownCloud but @hurradieweltgehtunter asked how he can help you in https://github.com/nextcloud/polls/issues/128 😃 Maybe you can explain the issues you're facing while uploading / publishing the app in https://github.com/nextcloud/polls/issues/128 as its not clear what issues you're facing?

**Comment by dartcafe** [comment]
Great! Updates were fine so far, as I see. 👌 But we should remove the unnesecary files for the next release, as there are the support files contained (.* etc.)

**Comment by splitt3r** [comment]
We could use / adopt https://github.com/nextcloud/polls/blob/master/Makefile#L127 for that.

**Comment by v1r0x** [comment]
I missed the Makefile. Good point @splitt3r Gonna use it for 0.8.1 :wink:

**Comment by dartcafe** [comment]
@v1r0x: Do you need these branches anymore?
https://github.com/nextcloud/polls/tree/full-anon
https://github.com/nextcloud/polls/tree/origin/full-anon (This is already merged)

**Comment by splitt3r** [comment]
@v1r0x we could add parts of https://github.com/owncloud/guests/blob/master/Makefile to have a make appstore-nc + make appstore-oc.

**Comment by v1r0x** [comment]
Sounds good! Can you make a PR?

**Comment by splitt3r** [comment]
I will have a look at it together with https://github.com/nextcloud/appstore/issues/529.
