### ISSUE TITLE
Poll 2.0.2 gets error NotAuthorizedException

### ISSUE THREAD

**Issue by TP75** [nextcloud/polls#1753]
Attempts to distribute a poll to users produces an error in the Nextcloud protocol:

**OCA\Polls\Exceptions\NotAuthorizedException**: Error loading share _XXXshare-codeXXX_

Nextcloud 21.0.2
Polls App 2.0.2 by manual install from https://github.com/nextcloud/polls/releases/download/v2.0.2/polls-2.0.2.tar.gz
PHP 7.3.27 on Debian 10.9

After the Polls 1.9.5 -> 2.0.0 -> 2.0.2 disaster (see #1732) there seem to be unfinished business yet, unfortunately.

**Comment by TP75** [comment]
Find the protocol below.  Note "XXXshare-codeXXX" in this case is "VWpTZTR5al" and your mileage may vary.

```
[index] Error: OCA\Polls\Exceptions\NotAuthorizedException: Error loading share VWpTZTR5al at <<closure>>

0. /var/www/nextcloud/apps/polls/lib/Controller/PublicController.php line 161
   OCA\Polls\Model\Acl->setToken("VWpTZTR5al")
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 218
   OCA\Polls\Controller\PublicController->watchPoll("VWpTZTR5al", 1624005847)
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 127
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Polls\Controller\PublicController {}, "watchPoll")
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Polls\Controller\PublicController {}, "watchPoll")
4. /var/www/nextcloud/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Polls\\Con ... r", "watchPoll", OC\AppFramework\ ... {}, {token: "VWpTZTR ... "})
5. /var/www/nextcloud/lib/base.php line 993
   OC\Route\Router->match("/apps/polls/s/VWpTZTR5al/watch")
6. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/polls/s/VWpTZTR5al/watch?offset=1624005847
from 192.168.63.14 at 2021-06-18T10:44:08+02:00
```

Naturally, there have been more errores and all similar.

**Comment by TP75** [comment]
upsi

**Comment by dartcafe** [comment]
I can't reproduce this. Please use the issue form and provide the steps for reproduction.

**Comment by TP75** [comment]
> I can't reproduce this. Please use the issue form and provide the steps for reproduction.

THX - However, please bear with me until next week due to the heat and weekend.

**Comment by dartcafe** [comment]
I am not in a hurry

**Comment by dartcafe** [comment]
I think, this is not an issue anymore

**Comment by TP75** [comment]
Anyway now on NC 21.0.3.1 with Polls 2.0.6 ...

However, THX for your time.  Happy hacking.
