### ISSUE TITLE
Separate vote limit for each option.

### ISSUE THREAD

**Issue by thefeiter** [nextcloud/polls#1756]
I would love to set the vote limit for each option individually for example I want to invite guests to a party and I want 3 people to sign up to bring a cake, 2 to bring desert and one to bring a salad.

For now I am just able to set the limit to all options at the same time but not for each option a separate number.

**Comment by tobyps** [comment]
#1712 
Sounds like a duplicate to my suggestion

**Comment by thefeiter** [comment]
Thats true. I haven't seen your Issue...
