### ISSUE TITLE
Can't enable polls after updating to 2.0.2

### ISSUE THREAD

**Issue by refda** [nextcloud/polls#1759]
Hello,

I am using NC 21 and did an update of polls. But now I cannot activate the polls app:

`Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

Also following steps did not fix the problem:

innodb_file_format = Barracuda
innodb_large_prefix → on

Gives the following result after trying to activate polls:

`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.`

Deactivating mysql 4 byte support inside the config is also not helping. Thanks for any hints!

**Comment by dartcafe** [comment]
The max length is a hint, that `innodb_large_prefix`  is `off`.
Make sure, the settings are persitent and not only temporary. 

https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix
and 
https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

**Comment by refda** [comment]
@dartcafe Thanks for the reply.
Now I saved the settings permanent, checked with show variables after restarting the mysql server:

```
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | OFF       |
+--------------------------+-----------+
```

The following error occurs after trying to activate the polls app:

`SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.`

**Comment by dartcafe** [comment]
I have no idea. Maybe the tables or the databse used got not converted? I am no database expert.
