### ISSUE TITLE
Some translations (german) dont work

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1763]
### Steps to reproduce
Go to "relevante Umfragen" (relevant polls)
The explanation below should be in german but is english ("All polls which are relevant or important to you, because you are a participant or the owner or you are invited to. Without polls closed more than five days ago. ")

Create a poll with anonymous participation
Go to the Poll
Below the Poll is an advice that the poll is not really anonymous

### Expected behaviour
Both advices in the translated language

### Actual behaviour
Advice in both cases in english instead of german.

The correct translations are in the file https://github.com/nextcloud/polls/blob/master/l10n/de.js

## Server configuration detail

**Operating system:** Linux 5.4.89 #1 SMP Wed Jan 13 06:05:19 CET 2021 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.2.36

**PHP version:** 

7.4.19

**Nextcloud version:** 21.0.2 - 21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
updated from 1.9.5 (probably had the same problem)

**Comment by Valdnet** [comment]
The German translation was added only 6 days ago: https://github.com/nextcloud/polls/commit/e5dac99a6dc340efc0d8b52cdd7cd6aaa33f588a.

**Comment by dartcafe** [comment]
The reason is, that the translations are only added to the master branch. Ther version 1.9 to 2 are created from the stable-1.9 branch. With the update to version 3 the translations will be shipped.

**Comment by Valdnet** [comment]
> The reason is, that the translations are only added to the master branch.

@dartcafe Is it possible for them to be added to other branches as well? I know it would require some configuration, but it would be good to add new translations on the fly. This will make the application easier for users to use, but translators would also like to see their translations and possibly correct them 😉.

**Comment by dartcafe** [comment]
I guess no, because the translations can only serve one branch, IMHO. Otherwise we would have conflicting strings in different branches.
