### ISSUE TITLE
 l10n: Add singular and plural

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/polls#1769]
The text string below should be changed to both singular and plural.

https://github.com/nextcloud/polls/blob/6653e21310ef79484a93990e2f959a59bbf6c905/src/js/views/Vote.vue#L57

**Comment by dartcafe** [comment]
I skipped this, because always a plural wíll be presented here. You must have 500 options to get one user skipped. In the end, this feature will get improved in the next sprint. Will add it then.

**Comment by Valdnet** [comment]
> I skipped this, because always a plural wíll be presented here. You must have 500 options to get one user skipped.

I thought so too, but wasn't sure 😉.
