### ISSUE TITLE
An unhandled exception has been thrown during update V2.0.2 -> V2.0.3

### ISSUE THREAD

**Issue by JMLatGitHub** [nextcloud/polls#1770]
```
sudo -u www-data php /var/www/nextcloud/occ app:update polls
polls new version available: 2.0.3
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Polls\Db\VoteMapper::fixVoteOptionText() in /var/www/nextcloud/apps/polls/lib/Migration/FixVotes.php:69
Stack trace:
#0 /var/www/nextcloud/lib/private/Repair.php(118): OCA\Polls\Migration\FixVotes->run()
#1 /var/www/nextcloud/lib/private/legacy/OC_App.php(1054): OC\Repair->run()
#2 /var/www/nextcloud/lib/private/legacy/OC_App.php(987): OC_App::executeRepairSteps()
#3 /var/www/nextcloud/lib/private/Installer.php(212): OC_App::updateApp()
#4 /var/www/nextcloud/core/Command/App/Update.php(116): OC\Installer->updateAppstoreApp()
#5 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute()
#6 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('...')
#12 {main}
```

After that, I had to disable polls to be able to log in at the web interface.

My setup: Debian Testing (11, Bullseye), NGINX V1.21.0, MariaDB V10.5.10, PHP V8.0.7, NextCloud V21.0.2.1

Kind Regards,
JML

**Comment by Octopus2** [comment]
Same Problem for me, my Nextcloud is not usable anymore....

**Comment by JMLatGitHub** [comment]
Hi @Octopus2, you can disable the polls app via occ cmd and all is good... (besides the polls app, of course).

**Comment by Octopus2** [comment]
@JMLatGitHub Thanks, at least the cloud is up and running again!

**Comment by dartcafe** [comment]
First of all: For some reason, we ask for filling the template when creating a new issue. This helps speeding up investigations and to reproduce fixing times. 

Remove the app via the app settings and try the install again. I just installed version 2.0.2 and did an update withour errors. Checking the installed files shows that all classes are present and accessible. In other words: I can't reproduce this error.

**Comment by dartcafe** [comment]
To complete this: I tried different upgrade paths. All of these ended in a proper 2.0.3 installation on NC12. I can only imagine, that some problem occured with unpacking the release package. 

The reported problem says, there is no method `fixVoteOptionText()` in the VoteMapper class. 

The file should look like this:
https://github.com/nextcloud/polls/blob/4b297c8ca9e927d66a70bb5ac63d54449e485d57/lib/Db/VoteMapper.php#L203-L215

**Comment by JMLatGitHub** [comment]
Hi @dartcafe, I know the value of a comprehensive issue reporting, but I decided to prioritize to report the issue as soon as possible, and secondly I wanted to wait for the reaction of other users and from you, developers...

Well, I deleted the polls app as suggested and now the installation of V2.0.3 went smoothly. For me, the issue is now solved. However, if you need further information or tests, then get in touch with me, I am available. Since I was not the only one affected, but there were also not plenty of reports, probably it is a sort of corner case.

At this point, I would like to thank you all very much for your excellent work. Very much appreciated.

Kind regards.
JML

**Comment by dartcafe** [comment]
> Hi @dartcafe, I know the value of a comprehensive issue reporting, but I decided to prioritize to report the issue as soon as possible, and secondly I wanted to wait for the reaction of other users and from you, developers...

It is just, that in the last time there were too many bug requests, without usable information, to reproduce a bug. Therefore I decided to try some education. You have just been the first victim. 😁 

The fact, that more than one user was affected, made me prioritize this. As you may have noticed we had some trouble with the last releases. But good to heear, that it worked afterwards. Maybe it was a hickup with the appstore. 

@v1r0x Did you notice something; And thanks for the quick release. 

I guess, I will dream of app updates this night...

**Comment by JMLatGitHub** [comment]
It's OK, @dartcafe, no problem, such educational measures are necessary from time to time. 😇 I saw that the new version was released just before, and it seemed to me that the bug was quite serious, so that at the end it was just too much information for the beginning to report the bug speedily.

I rebuilt my cloud & media server last week and I have been directly impacted by the Polls update issues last week. I somehow imagine there is a correlation there. The App Store hypothesis seems less plausible to me, as the package was apparently downloaded correctly and also installed, only it left the system in an inconsistent state, so that it was not possible to log in to Nextcloud again until I disabled the Polls app.

As mentioned, if you need logs or any other kind of information from me, gladly.
Greetings.
JML

**Comment by Octopus2** [comment]
@dartcafe I also get in again. I reported the error so superficially because I assumed a problem that affects many users and thus a warning or priority arises. It was the first time that my Nextcloud was no longer available due to an update of an app.

Unfortunately, I can provide little additional data because it is a managed nextcloud (version 20.0.10), in which I have administrator access, but no access to the server or log files.

Incidentally, I have not yet been able to clarify my situation. The provider has deactivated the app. I then just deleted it and reinstalled it from the appstore. But the following error message appears and the app is deactivated again:

> Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
> An exception occurred while executing 'UPDATE `oc_polls_votes` SET `vote_option_text` = ? WHERE (`vote_option_text` = ?) AND (`poll_id` = ?) AND (`vote_option_id` = ?)' with params ["2021-06-19T22:00:00+00:00 - 2021-06-20T22:00:00+00:00", "2021-06-19T22:00:00+00:00", 33, 458]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '33-heiko-2021-06-19T22:00:00+00:00 - 2021-06-20T22:00:00+00:00' for key 'UNIQ_votes'

Since the really great application is used intensively, I am grateful for every hint.

**Comment by dartcafe** [comment]
Ah f**k. 

@Octopus2 I didn't respected this constellation. Thanks for the log snippet. I guess I understand the issue. I think, we will get another update to 2.0.5.

**Comment by dartcafe** [comment]
I fixed the last bug and 2.0.4 is released. You unfortunately havce to wait until the appstore release or you can manually install it from here:  https://github.com/nextcloud/polls/releases/tag/2.0.4

**Comment by JMLatGitHub** [comment]
Thx, @dartcafe, I will test the official channel tomorrow, but maybe @Octopus2 is interested to manually install the new version...

**Comment by Bapf** [comment]
> 
> 
> I fixed the last bug and 2.0.4 is released. You unfortunately havce to wait until the appstore release or you can manually install it from here: https://github.com/nextcloud/polls/releases/tag/2.0.4

Sadly, 2.0.4 also doesn't work in my installation.
When I try to enable it, I get:

ParseError: syntax error, unexpected ')' in /srv/www/nextcloud/htdocs/apps/polls/lib/Migration/FixVotes.php:74

**Comment by dartcafe** [comment]
So, I would say, this issue is solved and can be closed. The version is also availabe via the appstore (kudos to @v1r0x)

@Bapf If your issue still exists, please open another issue and give more information about your system configuration. I can't reproduce this with the supported PHP versions and all tests are valid.

**Comment by JMLatGitHub** [comment]
@dartcafe, @Octopus2, @Bapf: Update to V2.0.4 went smoothly i my case.

**Comment by Octopus2** [comment]
@dartcafe Thank you for taking care of it so quickly. The update from 2.0.2 to 2.0.4 went smoothly and without any problems.
