### ISSUE TITLE
2.0.4 not working in NC 20 / PHP 7.2.24 / Ubuntu 18.04

### ISSUE THREAD

**Issue by Bapf** [nextcloud/polls#1774]
## What is going wrong? What did you observe?
**Describe the bug**

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
Installing or updating to 2.0.4 throws an "An error occured during the request. Unable to proceed."

Doing the same with occ gives:

130 xxxx@cloud:/var/www/html/nextcloud$ sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <polls> ...
An unhandled exception has been thrown:
ParseError: syntax error, unexpected ')' in /var/www/html/nextcloud/apps/polls/lib/Migration/FixVotes.php:74
Stack trace:
#0 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/n...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\Polls\\Migra...')
#2 [internal function]: spl_autoload_call('OCA\\Polls\\Migra...')
#3 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(107): ReflectionClass->__construct('OCA\\Polls\\Migra...')
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Polls\\Migra...')
#5 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(455): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Polls\\Migra...')
#6 /var/www/html/nextcloud/lib/private/ServerContainer.php(140): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Polls\\Migra...')
#7 /var/www/html/nextcloud/lib/private/Repair.php(126): OC\ServerContainer->query('OCA\\Polls\\Migra...')
#8 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(1035): OC\Repair->addStep('OCA\\Polls\\Migra...')
#9 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(970): OC_App::executeRepairSteps('polls', Array)
#10 /var/www/html/nextcloud/lib/private/Updater.php(379): OC_App::updateApp('polls')
#11 /var/www/html/nextcloud/lib/private/Updater.php(258): OC\Updater->doAppUpgrade()
#12 /var/www/html/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.10.1', '20.0.10.1')
#13 /var/www/html/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#14 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')

(Removing the "," at the end of line 73 of FixVotes.php fixes the issue.

## Information about your polls installation
**Polls version:** (see apps page)
2.0.4

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: 2.0.2

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [x] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
20.0.10

### Server configuration (decide, if you think it is helpful)

**PHP version:**
- [x] 7.3 or lower (7.2.24-0ubuntu0.18.04.7)
- [ ] 7.4
- [ ] 8.0

**Comment by chris-est** [comment]
Can confirm, same Nextcloud, PHP and Ubuntu Version.
Thank you for the fix!

**Comment by dartcafe** [comment]
@Bapf Thanks for the information. 

Actually PHP 7.2 is no more supported by nextcloud and out of maintenance itsself sice 6 months. So please consider updating to a more recent PHP-Version.

**Comment by Bapf** [comment]
> Actually PHP 7.2 is no more supported by nextcloud and out of maintenance itsself sice 6 months. So please consider updating to a more recent PHP-Version.

That depends. When using (the LTS!) Ubuntu 18.04 this version is still very well in maintenance.
Thinking that people always use the latest Ubuntu is quit annoying because this nullifies the intention of an LTS version.

**Comment by kinimodmeyer** [comment]
> > Actually PHP 7.2 is no more supported by nextcloud and out of maintenance itsself sice 6 months. So please consider updating to a more recent PHP-Version.
> 
> That depends. When using (the LTS!) Ubuntu 18.04 this version is still very well in maintenance.
> Thinking that people always use the latest versions is quit annoying because this nullifies the intention of an LTS version.

it not depends, have a look at https://www.php.net/supported-versions.php .
php7.2 is not even in maintenance for security anymore. no one talking about "always the latest versions".
you are years behind with your setup.

**Comment by Bapf** [comment]
> it not depends, have a look at https://www.php.net/supported-versions.php .
> php7.2 is not even in maintenance for security anymore. no one talking about "always the latest versions".
> you are years behind with your setup.
No, I'm not. Ubuntu backpots security fixes (but not new features) to its 7.2 version. That's the whole point of LTS distributions.

Nevertheless, that isn't even the issue here: NC 20 supports PHP 7.2, so if Polls 2.0.4 tagged as compatible with NC 20, it has to work on all PHP versions NC 20 supports. Otherwise people get errors when updating the app from the app store without knowing why ...
If you don't want to support PHP 7.2, you just hat to remove compatibility with NC 20, but since the fix is just removing on comma ...

**Comment by dartcafe** [comment]
> Thinking that people always use the latest versions is quit annoying because this nullifies the intention of an LTS version.

The problem here is, that I was mistaken to assume, that NC20 doesn't support PHP 7.2, but it still does. PHP 7.3 is the minimum supported version from NC21 on. 

Nevertheless, of course I removed the comma, as it was not by intention. But I will wait for a new release, to be sure no other problems occur. ATM I am struggeling with NC22 compatibility for the comming version.

Just mentioning: Your patch level is behind the last official PHP release, which is 7.2.34.

**Comment by Bapf** [comment]
> Just mentioning: Your patch level is behind the last official PHP release, which is 7.2.34.

I know. But that's also supposed to be that way: Ubuntu freezes the patch level on release (down to the minor version) an then backports only the security fixes.
This is supposed to help with stability (because there are no feature releases which also can cause issues as a side effect) without compromising security (because you still get all the security fixes).

**Comment by Moini** [comment]
What's worst is that it gets stuck in the update. Only disabling the app from the command line solves the problem (temporarily).

**Comment by dartcafe** [comment]
See comment from @Bapf https://github.com/nextcloud/polls/issues/1770#issuecomment-866701610
You can manually remove the trailing comma in line 73 of `apps/polls/lib/Migration/FixVotes.php`

like here (now it is line 83 in this version of the file and the comma after `$option->getPollOptionText()` has been removed)
https://github.com/nextcloud/polls/blob/39f3660a412b7740ee4e1bc4c561277476b7c2f8/lib/Migration/FixVotes.php#L74-L88

After that you can enable the app again. Version 2.0.5 will bring the fix.

**Comment by dartcafe** [comment]
fixed in 2.0.5

**Comment by Moini** [comment]
Thanks, @dartcafe - confirmed that it works!
