### ISSUE TITLE
Rework Email

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#178]
The email notifications need an overhaul. We should consider using the Nextcloud default template just like:

Nc: https://github.com/nextcloud/quota_warning/blob/master/lib/CheckQuota.php#L196-L234 vs.
oC: https://github.com/owncloud/calendar/blob/master/controller/emailcontroller.php#L111-L129

That way the emails match the other Nc emails and look very well. We also should consider to use email title / senders that match the other emails.

Sth. like:
![Email](https://user-images.githubusercontent.com/1869584/31558830-bf4b53dc-b04e-11e7-99ec-ed5105dd8656.png)

**Comment by splitt3r** [comment]
Help would by appriciated as i have no time atm. Perhaps @dartcafe has further plans / info?

**Comment by dartcafe** [comment]
@splitt3r I thought that. :-) 
@nickvergessen That would be great, if you could support here. Our plans are using the notification app, as well as email notification, but I have to get into it first. You could be a real accelerator for this topic. 

Yesterday, I merged everything into the master branch, so feel free to start a branch there.
