### ISSUE TITLE
Update Failed.

### ISSUE THREAD

**Issue by svajra** [nextcloud/polls#1780]
## When updated apps in nextlcoud, polls update to 20.0.2, there's errors.
1. Click on 'Update'
![1](https://user-images.githubusercontent.com/47180758/123604732-b236dd00-d82d-11eb-9f26-60fdd2074042.png)

2. Start
3. See error
![2](https://user-images.githubusercontent.com/47180758/123604809-c4b11680-d82d-11eb-9861-22bad27eead7.png)

Details
![3](https://user-images.githubusercontent.com/47180758/123604953-ec07e380-d82d-11eb-8db8-914e0084cc92.png)

“
升级到 20.0.2

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT * FROM `oc_polls_options` WHERE `duration` = ? ORDER BY `order` ASC' with params [86400]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'duration' in 'where clause'
详细日志

正在准备更新

设置日志级别为 调试

启用维护模式

修复错误： Repair MySQL collation

修复信息： All tables already have the correct collation -> nothing to do

修复错误： Repair SQLite autoincrement

修复错误： Copy data from accounts table when migrating from ownCloud

修复错误： Drop account terms table when migrating from ownCloud

正在更新数据库结构

数据库已更新

修复错误： Delete duplicates

修复错误： Polls repairstep - Fix votes with duration options
”

**Comment by vabene1111** [comment]
same issue here, completly shut down my instance. running occ app:disable polls got the instance back up. 

Thanks to all maintainers who create this awesome plugin, very happy with it and looking forward to the updated version :)

**Comment by dartcafe** [comment]
As there are no informations about the bug, I can only guess what happens here. We provide an issue template for bugs, which has its sense. Bug reports which lack on information will be closed in the furure. So please use the issue form and give us a chance to understand what happened.

**Comment by vabene1111** [comment]
Sorry, I lacked the time for a proper report and also misinterpreted your comment.

I just wanted to confirm that the issue the OP described did not only happen to him but also on two instances that I manage.

I will likely not have the time to investigate in the near future so feel free to just close this and I will leave polls disabled until someone files a valid report.

**Comment by svajra** [comment]
I try to “pkg update && pkg upgrade -y” , then ,it would proceed. but got another issue

"
升级到 21.0.2

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'duration' in 'where clause'
详细日志

正在准备更新

设置日志级别为 调试

启用维护模式

修复错误： Repair MySQL collation

修复信息： All tables already have the correct collation -> nothing to do

修复错误： Repair SQLite autoincrement

修复错误： Copy data from accounts table when migrating from ownCloud

修复错误： Drop account terms table when migrating from ownCloud

正在更新数据库结构

数据库已更新

已更新 “federation” 到 1.11.0

已更新 “lookup_server_connector” 到 1.9.0

修复错误： Update OAuth token expiration times

已更新 “oauth2” 到 1.9.0

已更新 “password_policy” 到 1.11.0

修复错误： Insert UUIDFix background job for user and group in batches

修复错误： Remove deprecated refresh time markers for LDAP user records

已更新 “user_ldap” 到 1.11.0

已更新 “files” 到 1.16.0

已更新 “activity” 到 2.14.3

已更新 “cloud_federation_api” 到 1.4.0

修复错误： Fix component of birthday calendars

修复信息： 3 birthday calendars updated.

修复错误： Regenerating birthday calendars to use new icons and fix old birthday events without year

修复信息： Adding background jobs to regenerate birthday calendar

修复错误： Fix broken values of calendar objects

[0 / 0]：Fix broken values of calendar objects

修复错误： Registering building of calendar search index as background job

修复信息： Add background job

修复错误： Register building of social profile search index as background job

修复错误： Registering background jobs to update cache for webcal calendars

修复信息： Added 0 background jobs to update webcal calendars

修复错误： Registering building of calendar reminder index as background job

修复信息： Add background job

修复错误： Clean up orphan event and contact data

修复信息： 0 events without a calendar have been cleaned up

修复信息： 0 properties without an events have been cleaned up

修复信息： 0 changes without a calendar have been cleaned up

修复信息： 0 cached events without a calendar subscription have been cleaned up

修复信息： 0 changes without a calendar subscription have been cleaned up

修复信息： 0 contacts without an addressbook have been cleaned up

修复信息： 0 properties without a contact have been cleaned up

修复信息： 0 changes without an addressbook have been cleaned up

修复错误： Remove activity entries of private events

修复信息： Removed 0 activity entries

已更新 “dav” 到 1.17.1

已更新 “files_external” 到 1.12.0

修复错误： Fix the share type of guest shares when migrating from ownCloud

修复错误： Copy the share password into the dedicated column

修复错误： Set existing shares as accepted

已更新 “files_sharing” 到 1.13.1

已更新 “files_trashbin” 到 1.11.0

已更新 “files_versions” 到 1.14.0

已更新 “sharebymail” 到 1.11.0

修复错误： Populating added database structures for workflows

已更新 “workflowengine” 到 2.3.0

已更新 “admin_audit” 到 1.11.0

已更新 “comments” 到 1.11.0

已更新 “firstrunwizard” 到 2.10.0

已更新 “nextcloud_announcements” 到 1.10.0

已更新 “notifications” 到 2.9.0

已更新 “systemtags” 到 1.11.0

已更新 “theming” 到 1.12.0

已更新 “contactsinteraction” 到 1.2.0

已更新 “dashboard” 到 7.1.0

已更新 “federatedfilesharing” 到 1.11.0

已更新 “files_pdfviewer” 到 2.1.0

已更新 “files_rightclick” 到 1.0.0

已更新 “files_videoplayer” 到 1.10.0

已更新 “logreader” 到 2.6.0

已更新 “photos” 到 1.3.0

修复错误： Delete duplicates

修复错误： Polls repairstep - Fix votes with duration options

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'duration' in 'where clause'

升级失败。请将此问题报告给 Nextcloud 社区。
"

**Comment by dartcafe** [comment]
Sorry, but this is not the wanted information. Please open a new issue and fill out the form.
