### ISSUE TITLE
l10n : json error code 3

### ISSUE THREAD

**Issue by GLLM** [nextcloud/polls#180]
Hi, my nextcloud logs are filled with hundreds of line about Polls.
See below :

![2017-10-11_17-01-05](https://user-images.githubusercontent.com/3989573/31449081-45f30222-aea6-11e7-9f14-9d4b17a6ecc0.png)

Nextcloud 12.0.3 stable (**not** docker)
NC language French
Server : Ubuntu 16.04
Apache 2.4 + PHP 7+ Letsencrypt

Not sure why,
I tried to open the json file and it did not look corrupted.

Thanks,

**Comment by splitt3r** [comment]
Next Version should fix that. There were several unescaped " in the link tags.

**Comment by GLLM** [comment]
Duly noted, cool. Because it prettry flooded my nextcloud logs :)
