### ISSUE TITLE
Missing french translation for some strings

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/polls#1800]
Hello there,

thank you for this great app :)

I noticed there are a few strings where translation is missing for French. Here are some examples :

<img width="448" alt="Capture d’écran 2021-07-02 à 11 46 18" src="https://user-images.githubusercontent.com/764332/124256162-499c7880-db2b-11eb-84e6-46e19fe393da.png">

<img width="491" alt="Capture d’écran 2021-07-02 à 11 46 30" src="https://user-images.githubusercontent.com/764332/124271935-62625980-db3e-11eb-8318-65673af979ab.png">

This is on NC21 and Polls 2.0.2

I can do the translation if need but someone has to tell me how can I do such a thing please :) I see it seems to be done with transifex, is there a server somewhere I can connect to in order to push the missing strings?

thanks!

**Comment by dartcafe** [comment]
This should be solved with version 3.0.0. Translations are done via the transifex community and merged into the master branch.

**Comment by ImaCrea** [comment]
> This should be solved with version 3.0.0. Translations are done via the transifex community and merged into the master branch.

Thanks for your answer. May I join the community to help fix these ones or you suggest we just wait for 3.0.0? By any chance, would you have an estimation of when it will be released please?

**Comment by dartcafe** [comment]
Version 3.0.0 is scheduled for next week. You can try the [release candidate](https://github.com/nextcloud/polls/releases/tag/v3.0.0-rc.1). The translations should be present. 

If you want to support the community for translations, create an account on [transifex](https://www.transifex.com/) and request access to the [nextcloud team](https://www.transifex.com/nextcloud/nextcloud).

**Comment by ImaCrea** [comment]
Thanks, I just contributed and translated missing ones. :) Needs a review now 😅

**Comment by dartcafe** [comment]
Cool, thanks. Great to have more contributers. 

The review is not neccessary for releasing, so your translations will be included in the current master and in the comming release. 

I'll close this then.
