### ISSUE TITLE
Adding multiple answer rows per user

### ISSUE THREAD

**Issue by stefan123t** [nextcloud/polls#1803]
## Describe the goal you'd like to achieve
I would like the users to enter multiple rows per session.
I.e. I want to ask them which menu they want for each of the family members coming for a birthday party.
I.e. aunt jelly, uncle jelly and their children niece jelly and cousin jelly all need to select one dish from the list of options.
I do want a way so that aunt jelly can add all her two kids and her husband to the list, without calling the URL four times.
In the doodle I tested this I can add multiple rows simply by clicking the plus + symbol on top of the respondent names.

As a poll owner I will get all the dishes I need to order on a single row and as a total count.
As a poll participant I only need to access the poll URL once and can add all the family members at once.
This is much more user friendly for any participant, because the QR code or whatever form the links has would need to be scanned again for each participant, even though it is the same user entering the details for the complete family.

## Describe possible solutions
Allow users to add multiple response rows to the poll by adding a line. 
Another feature request also asks for a separate "Send vote" button.
It would be good to have both "add another row / response" button and a "complete my poll / entries" button.

## Additional context
Respondent | Fish | Krill | Plankton | Algae Salad
--|--|--|--|--
Aunt Jelly | - | x | - | -
Uncle Jelly | x | - | - | -
Niece Jelly | - | - | - | x
Cousin Jelly | - | - | x | -
 [+ Add row] |  |  |  |

**Comment by dartcafe** [comment]
This is possible by creating a public poll and adding the participants via the public link
