### ISSUE TITLE
[3.0.0rc1] "update" to 2.0.4 is offered

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1807]
Cosmetic issue: After updating to 3.0.0rc1 an "update" to 2.0.4 is offered:

![Screenshot 2021-07-05 at 08 32 28](https://user-images.githubusercontent.com/43957716/124427766-1d236f00-dd6c-11eb-8cac-854971c84db0.png)

**Comment by dartcafe** [comment]
This is due to an ivalid version strin: 
* Is: `v.3...`
* should be: `3....`

Is fixed in the master branch in for RC2
