### ISSUE TITLE
[3.0.0rc1] Multiple errors in logs after Update

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1808]
After update to 3.0.0rc1 from 2.0.4 the log is flooded with "undefined index" and "BadFunctionCallException":

![Screenshot 2021-07-05 at 08 32 06](https://user-images.githubusercontent.com/43957716/124428150-9c18a780-dd6c-11eb-89ec-83d488e32841.png)

**Comment by dartcafe** [comment]
You can delete the column `dt` in the table `polls_comments`, to avoid the BadFunctionCallException. I updated the migration for RC2.

To the notification error: I don't know if, when or why; But it seems, the structure of the notification array changed. I added a check to fix the array.
