### ISSUE TITLE
ArgumentCountError: Too few arguments to function OCA\Polls\Migration\FixVotes::__construct()

### ISSUE THREAD

**Issue by hokascha** [nextcloud/polls#1810]
Polls 2.0.5:

While upgrading to nextcloud 20.0.11 I get the following output:

`sudo -u www-data /usr/bin/php7.4 occ upgrade 

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Updating <polls> ...
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Polls\Migration\FixVotes::__construct(), 0 passed in /var/www/nextcloud/lib/private/Repair.php on line 129 and exactly 4 expected in /var/www/nextcloud/apps/polls/lib/Migration/FixVotes.php:50
Stack trace:
#0 /var/www/nextcloud/lib/private/Repair.php(129): OCA\Polls\Migration\FixVotes->__construct()
#1 /var/www/nextcloud/lib/private/legacy/OC_App.php(1043): OC\Repair->addStep()
#2 /var/www/nextcloud/lib/private/legacy/OC_App.php(978): OC_App::executeRepairSteps()
#3 /var/www/nextcloud/lib/private/Updater.php(379): OC_App::updateApp()
#4 /var/www/nextcloud/lib/private/Updater.php(258): OC\Updater->doAppUpgrade()
#5 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#6 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#12 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#14 {main}`

Disabling the plugin via `occ app:disable polls` finishes the upgrade, though. But still cannot reactive the polls plugin with the same error.

**Comment by dartcafe** [comment]
Duplicate to #1811
