### ISSUE TITLE
[3.0.0rc2] errors saving vote

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1815]
Since 3.0.0rc2 there are errors saving votes. Example from the log:

![Screenshot 2021-07-06 at 09 00 07](https://user-images.githubusercontent.com/43957716/124556571-b8821600-de38-11eb-8e14-b58474f63760.png)

![Screenshot 2021-07-06 at 09 00 26](https://user-images.githubusercontent.com/43957716/124556585-bd46ca00-de38-11eb-8dd2-ff815bfd4db7.png)

![Screenshot 2021-07-06 at 09 00 44](https://user-images.githubusercontent.com/43957716/124556603-c172e780-de38-11eb-85fe-8bd9572276f5.png)

![Screenshot 2021-07-06 at 09 01 00](https://user-images.githubusercontent.com/43957716/124556614-c59f0500-de38-11eb-994e-58734b4e31be.png)

**Comment by dartcafe** [comment]
Need information of the existing entries in oc_votes (filter to relevant pollId) and the vote click (i.e. screenshot), which causes the exception.
Upload possible here: https://nc.yagst.de/s/f69NGZLoX42dXwg

**Comment by dartcafe** [comment]
Argh. Nonsense. Forget my last message.

**Comment by dartcafe** [comment]
Another compatibility fun

**Comment by dartcafe** [comment]
@herrmannsdorfer Are you able to confirm the fix. This only happened with NC21

**Comment by herrmannsdorfer** [comment]
3.0.0rc3 fixes this issue. I'm good with 3.0 now.
