### ISSUE TITLE
Can't create poll after update 20.0.11

### ISSUE THREAD

**Issue by cdessonnaz** [nextcloud/polls#1833]
## What is going wrong? What did you observe?
We can't create more polls, an issue appear when we try to create a new one.

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Polls
2. Add new
3. write a new name
4. See error (error during creating new poll "xx")
![2021-07-15 16_47_50-](https://user-images.githubusercontent.com/66410809/125808303-4c7cecb2-78d1-498d-9b5f-cda4fb2c0697.png)

PHP
Version : 7.2.32

Limite de mémoire : 512 MB

Temps d’exécution maximal : 3600

Taille de téléversement maximale : 2 MB

Base de données
Type : mysql

Version : 10.1.48

Taille : 91 MB

In logs we can found 

[index] Error: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM `oc_polls_votes` WHERE (`poll_id` = ?) AND (`user_id` = ?)' with params [10, "boxadmin"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextclouddb.oc_polls_votes' doesn't exist at <<closure>>

 0. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... t", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 149
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... t")
 2. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 914
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT * FROM ` ... )", {1: 10,2: "boxadmin"})
 3. /var/www/html/nextcloud/lib/private/DB/Connection.php line 202
    Doctrine\DBAL\Connection->executeQuery("SELECT * FROM ` ... )", [10,"boxadmin"], [1,2], null)
 4. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 206
    OC\DB\Connection->executeQuery("SELECT * FROM ` ... )", {dcValue1: 10,dcValue2: "boxadmin"}, {dcValue1: 1,dcValue2: 2})
 5. /var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 248
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 320
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/nextcloud/apps/polls/lib/Db/VoteMapper.php line 112
    OCP\AppFramework\Db\QBMapper->findEntities(OC\DB\QueryBuilder\QueryBuilder {})
 8. /var/www/html/nextcloud/apps/polls/lib/Model/Acl.php line 296
    OCA\Polls\Db\VoteMapper->findParticipantsVotes(10, "boxadmin")
 9. /var/www/html/nextcloud/apps/polls/lib/Model/Acl.php line 245
    OCA\Polls\Model\Acl->getIsParticipant()
10. <<closure>>
    OCA\Polls\Model\Acl->jsonSerialize()
11. /var/www/html/nextcloud/apps/polls/lib/Service/PollService.php line 111
    json_encode(OCA\Polls\Model\Acl {})
12. /var/www/html/nextcloud/apps/polls/lib/Controller/PollController.php line 73
    OCA\Polls\Service\PollService->list()
13. /var/www/html/nextcloud/apps/polls/lib/Controller/ResponseHandle.php line 42
    OCA\Polls\Controller\PollController->OCA\Polls\Controller\{closure}("*** sensitive parameters replaced ***")
14. /var/www/html/nextcloud/apps/polls/lib/Controller/PollController.php line 74
    OCA\Polls\Controller\PollController->response(Closure {})
15. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Polls\Controller\PollController->list()
16. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Polls\Controller\PollController {}, "list")
17. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Polls\Controller\PollController {}, "list")
18. /var/www/html/nextcloud/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OCA\\Polls\\Controller\\PollController", "list", OC\AppFramework\ ... {}, {_route: "polls.poll.list"})
19. /var/www/html/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/polls/polls")
20. /var/www/html/nextcloud/index.php line 37
    OC::handleRequest()

GET /index.php/apps/polls/polls?time=1626360470119
from xx.xx.xx.xx by boxadmin at 2021-07-15T14:47:50+00:00

**Comment by dartcafe** [comment]
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextclouddb.oc_polls_votes' doesn't exist

The table oc_votes is missing, so I guess someone deleted the table. 
1. Disable the polls app or remove it
2. Delete the poll related entries in the oc_migration table and 
3. enable the app again.

This should rebuild the db structure.

**Comment by cdessonnaz** [comment]
Thanks, it's working fine !¨

Have a nice day
