### ISSUE TITLE
Tooltip for adding name and Email to public link wrong (german)

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1842]
## What is going wrong? What did you observe?
I tried the feature to add a name and email to the URL as shown by the tooltip
The tooltip does not display the needed "&" if using name and email.
In Addition the tooltip writes "Email" in the URL instead of "email" as the example and the uppercase doesn't work.

Same problem with Firefox and Edge, so probably a general problem.

**Add a screenshot of the misbehavior**
![Screenshot (189)](https://user-images.githubusercontent.com/52735599/126368244-972d9877-7e65-4c65-b5d8-c831dad84116.png)

**Polls version:** (see apps page)
3.0.0

**Comment by dartcafe** [comment]
Yep, thanks. This is an error in the german translation. Fixed via transifex in `de `and `de_DE`.

And? Does it then work as expected? Just curious.

**Comment by dartcafe** [comment]
Cool. Thanks!
