### ISSUE TITLE
In public polls: Can not scroll inputpage after entering Name (to see the cancel or ok button).

### ISSUE THREAD

**Issue by Porbi222** [nextcloud/polls#1855]
## What is going wrong? What did you observe?
see: #1400, it's the same again, now on Version 3.0.0.
It's not so bad as in #1400, because you can at least enter a Name and press Enter to continue after the name is validated.

**Steps to reproduce the behavior**
see: #1400

## How should it work?
see: #1400

## Information about your polls installation
**Polls version:**  now: 3.0.0

**Fresh installation or update from a prior version (from which one)?**
update from some 2.x Version (i think it was 2.0.5, but not sure, sorry), there it worked as expected.

**How did you install this version?(Appstore or describe installation)**
appstore

## Information about your Instance of Nextcloud
**Nextcloud version:** 21.0.3

**Comment by dartcafe** [comment]
:vomiting_face:
