### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#187]
Besides the app icon we should add a favicon to the app. Most of the official apps do that but we have to find a way to choose nc / oc app favicon because they have different bg colors.

![Favicon](https://user-images.githubusercontent.com/1869584/31713145-9a1624fe-b3fd-11e7-93f2-811f81caa4a0.png)

And we should rename the app icon to `app.svg` so it shows up here:

![Manage apps](https://user-images.githubusercontent.com/1869584/32047589-b17a0df0-ba46-11e7-9624-82b65aab6723.png)

Already did that [here](https://github.com/nextcloud/polls/pull/224/commits/7365b79815bdc38137edfa38aafafbf362f5e8ba).

**Comment by dartcafe** [comment]
I will build a favicon, although, I don't like the solution of NC handlig another favicon for every app. I use a coule of NC instances and on my iPad, all icons are the favicon of the files app. 👎

**Comment by theonlytruth** [comment]
For me the use of different favicons of NC is good. When I opened different apps of one cloud in separate tabs I can easily switch to the one I want. So for example I could leave mails and calendar open and work in another tab with files. Multiple clouds at the same time would be a much more special use case for me. ;-)

**Comment by dartcafe** [comment]
See PR #229

**Comment by dartcafe** [comment]
Icon shows up in the apps list, but I have no idea how to force the theming app to youse the app icon.
