### ISSUE TITLE
 [Feature Request] Integrate with notifications app 

### ISSUE THREAD

**Issue by hanzei** [nextcloud/polls#188]
Notifications should appear when:

- [x] Poll is shared with a user
- [ ] ~~Poll is over due date~~
- [ ] ~~All participates voted~~

More notifications after integrating activities (#804).

See: https://github.com/nextcloud/notifications/blob/master/docs/notification-workflow.md

**Comment by dartcafe** [comment]
Personally, I don't like to add too much things to the notificartion app, because I am afraid, that importent information maybe will get out of scope. We should discuss this. There is already an email notification. Should we keep both or should both notifications resist side by side? 

I have no final idea.

**Comment by v1r0x** [comment]
If we decide to integrate the notifications app, I'd remove the mail notifications. But I have the same concern as @dartcafe 
Maybe @jancborchardt or @splitt3r have a "better" opinion 😉

**Comment by jancborchardt** [comment]
@nickvergessen is there any guideline for this?

I'd say it should go to the notification app, and the settings if it's online or via email too are handled via that API and in the settings, right?

**Comment by splitt3r** [comment]
I also think that integrating the notifications app would be a good idea. The notifications are pushed to mobile client / desktop client anyway so i think it´s a pretty nice way to notify the user.

**Comment by nickvergessen** [comment]
Currently there are no settings. Guidelines are “dont spam please“.
From the things listed above, I'd say:
* Shared ✅
* all voted/due date: creator only is okay, others can be informed by the creator

**Comment by jancborchardt** [comment]
Good call @nickvergessen! :)
