### ISSUE TITLE
I'm missing the "send infomail on vote" email option

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#1883]
Hi,

i'm missing the "send infomail on vote". Has it been it removed? Why? or was it moved somewhere i cant find it? I searched the whole polls several times but  wasnt able to find it. I found it always very handy to see how the voting was used by the users.

**Comment by dartcafe** [comment]
It has moved to the tree dot menu near the user name
![grafik](https://user-images.githubusercontent.com/26707476/128634635-80210111-3276-487c-965b-ceba4ea8221e.png)

**Comment by spipau** [comment]
And for all those who will also end up here and start searching, it got again moved to the menu at the top:

![Bildschirmfoto vom 2021-09-05 14-38-23](https://user-images.githubusercontent.com/2797845/132127078-55a48d90-48a9-4674-bf62-baf5bfebb8db.png)
