### ISSUE TITLE
l10n: Remove from translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/polls#1892]
These strings:

https://github.com/nextcloud/polls/blob/28512586c740bcd98971e92a23cde63d4ddbd551/src/js/components/Poll/PollTitle.vue#L80
https://github.com/nextcloud/polls/blob/28512586c740bcd98971e92a23cde63d4ddbd551/src/js/components/Poll/PollTitle.vue#L103

should be removed from the translation. We don't want them at Transifex.

_Reported by the translator._

**Comment by Valdnet** [comment]
@dartcafe Line 80 still needs to be changed 😉.

**Comment by rakekniven** [comment]
Transifex view:

<img width="359" alt="Bildschirmfoto 2021-08-15 um 20 26 34" src="https://user-images.githubusercontent.com/2069590/129488664-59d218bf-59c3-491e-bd4c-33ba2bbefdfd.png">

**Comment by dartcafe** [comment]
> 
> 
> @dartcafe Line 80 still needs to be changed 😉.

🙈
