### ISSUE TITLE
Add an option to disable comments in a poll and disable the web link in a poll

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/polls#190]
Can you add an option to disable comments in a poll and disable the web link in a poll please ? Thanks,
![image](https://user-images.githubusercontent.com/16205280/31723575-86dc84ec-b41f-11e7-8074-3f6677ec34c0.png)

**Comment by v1r0x** [comment]
I understand that disabled comments is a use-case, but what's the use-case for a hidden link? Or is it just about a full-width poll?

**Comment by dartcafe** [comment]
Deactivating comments is a good idea. I packed it to the backlog. Hiding the link has no effect, as it is the only URL, how the poll can be reached.

**Comment by Ludovicis** [comment]
The link of url can be reached when we create the poll with "copy link"
![image](https://user-images.githubusercontent.com/16205280/31766586-4ae26c5a-b4c8-11e7-83f6-f81f85c651a0.png)

**Comment by dartcafe** [comment]
I plan to push the comments and optins to a sidebar, so it is not on the polls pages. Let's dicuss the possible solutions later.

**Comment by dartcafe** [comment]
#737
