### ISSUE TITLE
Users are not shown in field "Add Shares" in NC 22.x

### ISSUE THREAD

**Issue by spreeni151** [nextcloud/polls#1901]
In Nextcloud 22.1 Polls 3.0 doesn't show the user names to be shared with in the field "Add Shares". In former Nextcloud versions, for example, the user "Tom Miller" ist shown as soon You typed "tom". 

The latest nextcloud shows nothing, no users, no circles which makes it difficult  to share polls with others.

I also tested the latest polls 3.1_rc, which doesn't make a difference. Switching from php7.4 to 8.0 does not change anything.

I'm new to version 22 of nextcloud - is this behavior a new security feature or a bug? If so, could this be a nextcloud bug or a polls bug?

Config:
Nextcloud 22.1 (fresh install)
php 7.4 (also tested 8.0)
MariaDB 10.5

Firefox and Chrome (latest)

Frank

**Comment by dartcafe** [comment]
Disable the circles app. See https://github.com/nextcloud/circles/issues/763

**Comment by spreeni151** [comment]
Thank you for pointing to this circle issue. After deactivating it polls works as expected. I would never have thought of circles as a cause.

**Comment by dartcafe** [comment]
Just for info: the RC1 of NC 22.1.1 seems to fix tht issue.
