### ISSUE TITLE
Polls 3.1: Options with quotation marks are not shown translated

### ISSUE THREAD

**Issue by spreeni151** [nextcloud/polls#1908]
After updating from NC20 to 21 and upgrading polls to 3.1 there are problems with the translations of the app. Some options are shown in English, most others in system's language (German).
I recognized, that all parts that are shown in Englich contain quotation marks like _'Allow "Maybe" vote_' . So I thought if there could be a syntax conflict with the translation files of the l10n folder, which also use quotation marks. If it's so we could easyly avoid this by using '-marks instead of "-marks. 

Nextcloud 21.0.4
Polls 3.1
PHP 7.4
MariaBD 10.5
Apache Server

in config.php used localize params:
</details>
  'default_phone_region' => 'DE',
  'force_language' => 'de',
  'default_language' => 'de',
  'default_locale' => 'de_DE',
</details>

Regards,
Frank

**Comment by dartcafe** [comment]
@Valdnet Do you mind, to check this?

**Comment by spreeni151** [comment]
I just found out that this is an issue with the 3.1 version of polls. I compared it with version 3.0, which shows all parts of the text translated correctly. Perhaps this information will help to find the problem.

**Comment by Valdnet** [comment]
In the German (de) translation, not all text strings are translated, therefore some text strings (including those mentioned in issue) in the application may appear in English.

@spreeni151 If you change 'default_language' => 'de' to 'default_language' => 'de_DE' you should get the german translation.

**Comment by Valdnet** [comment]
@rakekniven Twenty text strings are not translated for German in (de) for Polls. Can you check and supplement if not a problem 😉.

**Comment by rakekniven** [comment]
Hello all,

the "de" version is the informal version of german. The de_DE version is formal and this this version is translated and checked with care and attention.
The informal version does not get the same attention. There are not enough volunteers to take care of the project on a continuous basis.

**Comment by rakekniven** [comment]
Just did a quick search at Transifx. See https://www.transifex.com/nextcloud/nextcloud/translate/#de/forms/317253354?q=reviewed%3Ano

Currently all strings are translated for "de". Maybe this hasn't been the case at the date the last release was done.
So the next release should be fully translated.

**Comment by dartcafe** [comment]
This is polls, not forms. ;-)

**Comment by rakekniven** [comment]
You are absolutely right.

Current numbers for polls:
![grafik](https://user-images.githubusercontent.com/2069590/130754462-c6c144a6-809c-4e56-a987-708f1270309c.png)

**Comment by Valdnet** [comment]
@rakekniven Thanks for checking 😉.

> the "de" version is the informal version of german. The de_DE version is formal and this this version is translated and checked with care and attention.

@spreeni151 The only thing left for you to do is change the language to `'default_language' => 'de_DE'`.

**Comment by dartcafe** [comment]
Translation for de and DE_de completed and reviewed.

**Comment by spreeni151** [comment]
Thank you for your answers, you all do a great job! :-)
I changed 'default_language' to de_DE and the 'force_language' parameter as well. Now Nextcloud is talking a bit different to me, a bit too polite ;-) but polls' translations are shown correct now. It's a bit funny that the 3.0 version could handle the 'de' language version better, that led me on the wrong track.
So, thank you!

**Comment by cloud2018** [comment]
> Now Nextcloud is talking a bit different to me, a bit too polite ;-)

@spreeni151 
Wenn Dir die Du-Variante besser gefällt und Du etwas dazubeitragen willst, kannst auch Du mit (einem Konto) bei Transifex bei der Du-Variante (de) Strings übersetzen: https://www.transifex.com/nextcloud/nextcloud/translate/#de
Infos hierzu stehen unter  https://help.nextcloud.com/t/ubersetzungswissen-gultig-fur-das-komplette-nextcloud-projekt-wiki/59850
Je mehr sich beteiligen, desto weniger Strings bleiben unübersetzt und desto mehr Anwender können ihre bevorzugte Sprachvariante wählen.
