### ISSUE TITLE
Can you expand the name field in a poll ?

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/polls#191]
Can you expand the name field in a poll, please ? Thanks
![image](https://user-images.githubusercontent.com/16205280/31723666-cf792b10-b41f-11e7-9d4b-e13cd205e702.png)

**Comment by v1r0x** [comment]
@dartcafe Maybe a min-width of 200px or whatever for the name cell?

**Comment by dartcafe** [comment]
Argh. Don't do that kind of polls. :-) Just kidding. I will add a min width. But the comments are a problem as well, when polls get that big. I will think about it.

**Comment by dartcafe** [comment]
Did a quick fix in PR #196

**Comment by Ludovicis** [comment]
Yes it work for me :) Thanks,
![image](https://user-images.githubusercontent.com/16205280/31772068-a17495dc-b4de-11e7-832a-ec91f83c312c.png)
