### ISSUE TITLE
Change in anonymous selection is not saved

### ISSUE THREAD

**Issue by hajika** [nextcloud/polls#192]
### Steps to reproduce
1. save poll as anonymous
2. edit poll and remove anonymous
3. save it again

### Expected behaviour
Names should be visible now, or at least new voter names should be visible

### Actual behaviour
Poll is still anonymous, the change has not been saved

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
12

**Browser**
Firefox

If it is not reproducable I can add more informations

**Comment by dartcafe** [comment]
I can reproduce that. @v1r0x Can you investigate?
