### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by stony007de** [nextcloud/polls#1929]
On Update to NC 21.x with Polls update I get the following message:

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_polls_options' doesn't exist
![Bildschirmfoto 2021-09-03 um 08 44 24](https://user-images.githubusercontent.com/17473058/131962224-f90958ae-2a7f-4412-9012-943c348ed7a3.png)

Detaillierte Protokollmeldungen 
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Polls - Remove indices and foreign key constraints
Reparaturschritt: Polls - Delete duplicates and orphaned records
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_polls_options' doesn't exist
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

**Comment by dartcafe** [comment]
Thanks for reporting, but without any further information, I can only guess what happens. 

There is an issue form, when a bug report is created. Please open another issue und give the requested informations, so we have a chance for analysing.
