### ISSUE TITLE
Comments cannot be deleted (or edited)

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#193]
### Steps to reproduce
1. Create new poll
2. Comment
3. Options to delete (and edit) comment are missing

### Expected behaviour
It should be possible to delete (and edit) own comments
It should be possible for admin users to delete every comment

**Nextcloud version:** (see Nextcloud admin page)
NC 12.0.3 / Polls 0.8.0

**Comment by dartcafe** [comment]
True. Something for the becklog. Thanks.

**Comment by splitt3r** [comment]
We should have a look at https://github.com/nextcloud/announcementcenter/pulls?q=is%3Apr+comment+is%3Aclosed

**Comment by ebiel** [comment]
I'd very much appreciate the implementation of this feature.
Let me know if there is any way to support the development.

**Comment by dartcafe** [comment]
Thanks. I'll have a look on it later.

**Comment by rubo77** [comment]
@dartcafe, did you have a look? maybe you can also help me with my PR #501
