### ISSUE TITLE
Users without Email could not be found in the share entry box

### ISSUE THREAD

**Issue by imthemichi** [nextcloud/polls#1937]
## What is going wrong? What did you observe?
**Describe the bug**

I have a user, which has no Email-Address in his profile. If I search for this user or even if a search contains this user (other users could have an email), nothing is returned in the search result. 

**Steps to reproduce the behavior**
1. Go to 'a Poll'
2. Click on 'share'
3. Search for a user without an email address (username: oemail)

## How should it work?
**What you expected to happen?**

The user is returned in a submenue and can be selected for sharing.

## Information about your polls installation
**Polls version:** 3.1.0 (NC 21.0.4)

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [X] Update from a prior version
  Version number of the previous version: Polls 1.9.5 (NC 20.0.10)

**How did you install this version?(Appstore or describe installation)**

- [X] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 21.0.4

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [X] MariaDB version: 10.0.6
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [X] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [X] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [X] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

[index] Error: TypeError: Return value of OCA\Polls\Model\UserGroupClass::getEmailAddress() must be of the type string, null returned at <<closure>>

0. /var/www/html/custom_apps/polls/lib/Model/UserGroupClass.php line 273
   OCA\Polls\Model\UserGroupClass->getEmailAddress()
1. <<closure>>
   OCA\Polls\Model\UserGroupClass->jsonSerialize()
2. /var/www/html/lib/public/AppFramework/Http/JSONResponse.php line 73
   json_encode({siteusers: [OCA ... ]}, 1)
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 172
   OCP\AppFramework\Http\JSONResponse->render()
4. /var/www/html/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Polls\Controller\SystemController {}, "userSearch")
5. /var/www/html/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Polls\\Con ... r", "userSearch", OC\AppFramework\ ... {}, {query: "mail",_ ... "})
6. /var/www/html/lib/base.php line 993
   OC\Route\Router->match("/apps/polls/search/users/mail")
7. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/polls/search/users/mail

**Comment by dartcafe** [comment]
Probably this: #1901

**Comment by dartcafe** [comment]
argh. too fast.
