### ISSUE TITLE
(Excel-)Download

### ISSUE THREAD

**Issue by baschni** [nextcloud/polls#1942]
I would like to be able to download an export of a poll with a matrix of the dates or options on the horizontal axis and the names and e-mails of the participants on the vertical axis e.g. in Excel-Format or csv that is importable in Excel.

Doodle has a similar feature.

![grafik](https://user-images.githubusercontent.com/90386808/132665691-a1afa607-cfe6-4ce0-8523-379a6b13ae12.png)

**Comment by dartcafe** [comment]
I'll put it in the backlog, but I think, this will be not realized in the next versions.

**Comment by uka-support** [comment]
Maybe this could be implemented by changes to the page structure (or additional markup) to allow one to select the results, then copy/paste into a spreadsheet application.

**Comment by dazsmith** [comment]
Is this the same as #366?

**Comment by clawoflight** [comment]
#366 is more about CSV export, which would be machine-readable.
The amount of pre-processing needed to automatically deal with Doodle polls (I have tried that) make me hate their excel-only export :)

**Comment by dartcafe** [comment]
See linked pr #2169, if it meets your expectations.
