### ISSUE TITLE
See E-Mail of invited users as an admin

### ISSUE THREAD

**Issue by baschni** [nextcloud/polls#1943]
When a user changes his name to be shown, I cannot see his e-mail anymore. As an administrator/creator of the poll it is helpful to be able to identify the people that were invited to the poll.

![grafik](https://user-images.githubusercontent.com/90386808/132666016-198bbae4-8785-4fb5-816d-0042c695179a.png)
![grafik](https://user-images.githubusercontent.com/90386808/132666093-a693f467-bd96-45d8-9f74-f9bb7a8fd8de.png)

In the pictures you see the user "asdfasdf asdf" which had been originally invited via a personal invitation e-mail. In the configuration view I cannot see his e-mail anymore

**Comment by dartcafe** [comment]
See screenshots in #2001
