### ISSUE TITLE
avatar on public vote page can't be loaded

### ISSUE THREAD

**Issue by hajika** [nextcloud/polls#195]
In a public accessible vote, the page tries to load an avatar with a strange address https://cloud.example.com/index.php/avatar/%3F/32 That of course looks like:

![nc poll](https://user-images.githubusercontent.com/27491258/31729227-b96d284e-b42e-11e7-9ddd-dccbdcc8519d.png)

**Comment by dartcafe** [comment]
NC/OC? Version? I had this issue thru development, but fixed this. I need more information.

**Comment by hajika** [comment]
NC 12.0.3

**Comment by dartcafe** [comment]
Do you have a link for me with the public poll?

**Comment by dartcafe** [comment]
@hajika Do you have a similar setup like in #200?

**Comment by dartcafe** [comment]
I tried, but I couldn't reproduce that. Without further information, it is impossible to investigate further.
@hajika If you cannot give more information, will mark this issue as solved.

**Comment by dartcafe** [comment]
Obviously the issue does not exist anymore. Please reopen, if it still exists...
