### ISSUE TITLE
Make name checking for anonymous (public) users more inclusive so that people don't have to invent a name

### ISSUE THREAD

**Issue by hansdez** [nextcloud/polls#1952]
## The goal I'd like to achieve
Currently some people can't use their own first name when filling in a public poll as an anonymous user, because Nextcloud Polls only allows for names that are three characters long or more. I would like for it to be possible for all users to use their real first name.

## Possible solution
The problem would be solved if Nextcloud Polls would stop checking for a minimum length for names from anonymous users using the public link.

## Screenshot of a problematic name
![20210912-screenshot-195742-1462x848](https://user-images.githubusercontent.com/20969754/132997897-18a3f93f-84d1-4bf8-8e42-16ca6e99887a.png)

**Comment by dartcafe** [comment]
I believe this rule is active since the beginning. I think, we don't need it anymore.
