### ISSUE TITLE
[3.2.0-rc1] Update to 3.2RC1 fails with InvalidArgumentException

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#1958]
Downloaded the new RC but cannot enable it. The log shows:

![Screenshot 2021-09-14 at 07 59 57](https://user-images.githubusercontent.com/43957716/133203991-871e0dc4-bbed-4399-a5e7-d1659dc3faa4.png)

NC 21.0.4, previous working polls app was 3.1.0

**Comment by dartcafe** [comment]
Argh! Ran again into the oracle nulling trap. 
oracle treats empty strings like null

**Comment by dartcafe** [comment]
You can fix it manually before releasing RC2, see commit https://github.com/nextcloud/polls/commit/e0bda5bc70e5a10efc787360d3e8689d72d448b8

**Comment by herrmannsdorfer** [comment]
Your fix let me enable the app, but ... all polls (relevant, closed whatever) are missing.

And in the log there is an exception caused by TypeError and another TypeError:

![Screenshot 2021-09-14 at 15 25 51](https://user-images.githubusercontent.com/43957716/133266203-aff15d17-ffcd-415f-85ca-a25248f19746.png)

![Screenshot 2021-09-14 at 15 26 07](https://user-images.githubusercontent.com/43957716/133266230-99e8df77-7822-44f3-829d-a47d9f9963af.png)

**Comment by herrmannsdorfer** [comment]
Downgrade to 3.1.0 seems no option: polls are still gone and a lot of
`BadFunctionCallException: miscSettings is not a valid attribute`
in the log ...
Any suggestions?Otherwise I will return to my snapshot before my 3.2.0-rc1 attempt.

**Comment by dartcafe** [comment]
for the downgrade: 
delete the column misc_settings from the table oc_polls_polls

**Comment by herrmannsdorfer** [comment]
Sorry, I rolled back already. Will try the update again with the next RC.

**Comment by dartcafe** [comment]
Thanks for testing. The last error occured because, tha app config wasn't initialized. Should be fixed. RC2 will come this evening.

**Comment by dartcafe** [comment]
rc2 is out
