### ISSUE TITLE
The screenshots on the Nextcloud Apps site are not showing

### ISSUE THREAD

**Issue by HairyFotr** [nextcloud/polls#1959]
The screenshot images on the Nextcloud Apps site are not showing up. Looks like the screenshots here were replaced a month ago, but the URLs were not updated on the Apps site.

https://apps.nextcloud.com/apps/polls
https://github.com/nextcloud/polls/tree/master/screenshots

**Comment by dartcafe** [comment]
Yes, they were replaced. I copied some to thair old names. Thanks for pointing to that.
cheers
