### ISSUE TITLE
Optical seperation of weeks and months for date polls

### ISSUE THREAD

**Issue by baschni** [nextcloud/polls#1969]
In date polls with many date options some visual guidance is missing. Therefore I would like to have an option to optically differentiate poll options of one week or month.

One idea could be to separate different weeks by a line and options in a different months by a double line.

column view with and without line option:
![2021-09-16 23_16_53-Umfragen - Relevante Umfragen](https://user-images.githubusercontent.com/90386808/133687416-2be8a87c-004e-4c66-888b-9a1dd1258b02.png)
![2021-09-16 23_16_53-Umfragen - Relevante Umfragen - with lines](https://user-images.githubusercontent.com/90386808/133687425-0f992b8c-0537-47f8-8378-85c3319280ba.png)

list view with and without line option:
![2021-09-16 23_14_43-Umfragen - Relevante Umfragen](https://user-images.githubusercontent.com/90386808/133687422-4180bed2-69ba-410c-b6c5-8eded93e9f16.png)
![2021-09-16 23_14_43-Umfragen - Relevante Umfragen - wtih lines](https://user-images.githubusercontent.com/90386808/133687421-13245423-5278-49a1-bbe7-71e95b8b142a.png)

**Comment by dartcafe** [comment]
This is something similair like in #1602. Unfortunately it is a little bit more complicated, than it seems. As it is already on the to do list, I close this in favor of #1602.
