### ISSUE TITLE
Public poll not usable without sign in "invalid name

### ISSUE THREAD

**Issue by Jasonthefirst** [nextcloud/polls#1979]
## What is going wrong? What did you observe?
A public poll is not working because users can't fill out the poll without signing in. When filling in a name it only states: "invalid name" and they can't participate. 

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Create a public poll
2. share the poll with a public link
3. open the link as a incognito user or on a pc you are not signed in in to your nextcloud
4. try to fill out the poll without registering. 

**Add a screenshot of the misbehavior**

![image](https://user-images.githubusercontent.com/6411464/134129913-14017f73-a462-40ea-ae10-b09158fca152.png)

## How should it work?
It should be possible to fill out the poll without registering. 

A clear and concise description of

## Information about your polls installation
**Polls version:** 3.1.0.

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [ x] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x ] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.1.1  (but the bug also happened with 22.1.0.)

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [x ] PC
- [ ] Mac
- [x ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [x ] Chrome version: 93...
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
My crystal ball is broken. Do you have any logs, as requested in the issue form? This is not reproducable.
Feel free to reopen the issue, if you can add any usable information, which can help identify your problem. 

But If I may guess, there is already a user 'Testname' or a participant in this poll with this name, because usernames have to be unique.
