### ISSUE TITLE
See who votes, if poll is not anonymous but results are hidden until after closing

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1982]
## Describe the goal you'd like to achieve
As the title suggests, all users (who are invited to participate in the poll) should be able to see who voted even if they cant see what was voted.
It is the first time I'm using this particular combination (hidden results until closing but visible participants).

I could just let the participants see how everyone votes, but that can have a leading effect and change the outcome. But it is helpful to see who voted, so you can remind your colleagues/friends etc. to participate.

If it is to complicated maybe just show how many already voted.

Thx

BTW I hope this isnt a duplicate, I looked, but its hard to give it a catchy title or keyword ;)

**Comment by dartcafe** [comment]
The intention is to hide every information about the results, including the count of participants so far. I think this use case is an edge case and too expensive.
