### ISSUE TITLE
Protected master branch

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/polls#199]
@dartcafe @splitt3r @jancborchardt I set the master branch to protected.
![screenshot-2017-10-19 nextcloud polls](https://user-images.githubusercontent.com/9248714/31762822-b845f4b2-b4bc-11e7-9194-b439058a0e80.png)

Is this too much? Or do we need even more?

**Comment by splitt3r** [comment]
Looks good to me 👍

**Comment by jancborchardt** [comment]
Yeah, looks good to me too, good call! Can always be adjusted when needed too. :)
