### ISSUE TITLE
Icons not loaded

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/polls#200]
Hi,

thank you for the big UI improvements in this release. I'm having a problem with missing SVG icons.

I'm using the [wonderfall/nextcloud](https://hub.docker.com/r/wonderfall/nextcloud/) docker images, where I have also problems with this:
https://github.com/nextcloud/server/issues/5289
(Not sure, if it is related.)

Tested on:
- nextcloud 12.0.3.3 (beta) - update polls from `0.7.0` to `0.8.0`, then remove polls and install once again, also without success
- nextcloud 12.0.3.3 (stable) - fresh installation of the server and the polls app (specs below)

![polls-list](https://user-images.githubusercontent.com/20214043/31769149-a4977cfe-b4d2-11e7-8abe-ae98918a1792.png)
![polls-request2](https://user-images.githubusercontent.com/20214043/31769151-a4fc3964-b4d2-11e7-8a49-88af2052c3a6.png)
![polls-poll](https://user-images.githubusercontent.com/20214043/31789677-30e68552-b513-11e7-9bb2-79d4c99d8b54.png)

Content of the `img` subdirectory:

```
img
├── app-logo-polls.svg
├── expired-unvoted-vote.svg
├── expired-voted-vote.svg
├── maybe-toggle.svg
├── maybe-vote.svg
├── no-comment.svg
├── no-toggle.svg
├── no-vote.svg
├── open-unvoted-vote.svg
├── open-voted-vote.svg
├── share.svg
├── yes-comment.svg
├── yes-toggle.svg
└── yes-vote.svg
```

### General server configuration

**Operating system:** Linux 4.4.0-93-generic # 116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64

**Web server:** nginx/1.13.5 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit

**PHP version:** 7.1.10
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - sqlite3
 - zlib
 - ctype
 - curl
 - dom
 - fileinfo
 - filter
 - gd
 - hash
 - iconv
 - json
 - mbstring
 - SPL
 - PDO
 - pdo_sqlite
 - bz2
 - posix
 - readline
 - Reflection
 - session
 - SimpleXML
 - standard
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - mysqlnd
 - cgi-fcgi
 - apcu
 - Phar
 - exif
 - ftp
 - gmp
 - imap
 - intl
 - ldap
 - mcrypt
 - mysqli
 - pcntl
 - pdo_mysql
 - pdo_pgsql
 - pgsql
 - zip
 - redis
 - smbclient
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh  wonderfall/nextcloud docker image

**Where did you install Nextcloud from:**  fresh  wonderfall/nextcloud docker image

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - circles: 0.12.4
 - cms_pico: 0.9.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.4
 - drop_account: 0.0.6
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - metadata: 0.5.0
 - mood: 0.3.2
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.1
 - ojsxc: 3.3.0
 - ownbackup: 17.5.0
 - password_policy: 1.2.2
 - polls: 0.8.0
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - ransomware_protection: 1.0.4
 - registration: 0.3.1
 - richdocuments: 1.12.35
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - telephoneprovider: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - twofactor_u2f: 1.3.3
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - files_external
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "datadirectory": "\/data",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "12.0.3.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "logdateformat": "Y-m-d H:i:s",
    "installed": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** Fedora Rawhide

### Logs

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"aaY3Hccj8xbg140OjxMR","level":3,"time":"2017-10-19 00:56:18","remoteAddr":"172.18.0.3","user":"franta","app":"polls","method":"POST","url":"\/apps\/polls\/search","message":"Array\n(\n)\n","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
```
</details>

<details>
        <summary>Browser log</summary>

```
https://beta.scoutcloud.tk/apps/polls/img/open-unvoted-vote.svg error 302
```
</details>

**Comment by dartcafe** [comment]
There seem to be some strage rewrites in this installation. The http status of the icons is 302. When I try to access the svg directly, i get redirected to the root. When I try to access an icon from the tsks app, I find it in the subfolder /apps2/tasks/img/ under the root. Is it possible, that the apps are installed outside the docroot or outside the nextcloud root?

**Comment by dartcafe** [comment]
For some reason, I can access the icon via [root]/apps2/polls/img/open-unvoted-vote.svg on your server.
I have not a glue, how to fix that... 
@lachmanfrantisek I registered on your site. You can delete my account. Rewust for deletion does not work in the personal settings.

**Comment by lachmanfrantisek** [comment]
Thanks for looking in to it.

>  Is it possible, that the apps are installed outside the  docroot or outside the nextcloud root?

Yes, you are right. The `app` folder is outside of the `nextcloud` folder. This causes also the problems with scss files (the issue from server I've mentioned before). 

@Wonderfall  Please, do you have any ideas about it? Do you have same problems in your setup or am I doing something wrong?

> @lachmanfrantisek I registered on your site. You can delete my account. Rewust for deletion does not work in the personal settings.

No problem, it's only for testing...

Another (maybe similar) problem I had with the circles app: https://github.com/nextcloud/circles/issues/84 (If it can help.)

**Comment by dartcafe** [comment]
I think the problem is, that the icons are loaded via scss and not via php. It could be managed by loading the status icon via php, but not the yes and no icons, because they are interactive.

**Comment by lachmanfrantisek** [comment]
OK, so I have to wait for the fix of the problem with `scss` files on the server side? (Now, I used to remove the `scss` files from the `css` directory.)

`Yes`/`No` icons are not such important as the other icons. But I do not want to force you to some hacky solutions.

Nevertheless, thank you for investigating it.

**Comment by dartcafe** [comment]
Does it work after removal of the scss files and leaving the css?

**Comment by lachmanfrantisek** [comment]
Unfortunately no.

Without removing the `scss`, there is no styles loaded. After removal, the style is OK, but the icons are not loaded. I need to do the removal in all apps which switched to the `scss` (deck, circles, contacts). In other apps, the icons are fine. (Maybe the reason is in `scss` and `php`, as you sad, but I do not know much about `php`/`css` stuff.)

**Comment by dartcafe** [comment]
You could edit the css files and point the svg-resource to the apps2 folder.

**Comment by lachmanfrantisek** [comment]
Thanks for the tip. I've changed the urls in `css` and the icons are OK. Thank you!

`../../../apps/polls/css/../img/yes-vote.svg` -> `../img/yes-vote.svg`

I do not understand, why there is such a weird path.

**Comment by dartcafe** [comment]
It is generated from the scss compiler in nextcloud. I will correct this in the css files.

**Comment by dartcafe** [comment]
I updated the css files in PR #203. Can you confirm the fix?

**Comment by lachmanfrantisek** [comment]
Thank you for the fix.
