### ISSUE TITLE
Polls Update to 19.0.13 Failure

### ISSUE THREAD

**Issue by ambein** [nextcloud/polls#2000]
Hi, I don't even want this app... will have to remove from the backend when I have time... in the meantime Updater asked me to submit this:

> Update to 19.0.13
> 
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_options ON oc_polls_options (poll_id, poll_option_text, timestamp)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
> Detailed logs
> 
> Preparing update
> 
> Set log level to debug
> 
> Turned on maintenance mode
> 
> Repair step: Repair MySQL collation
> 
> Repair info: All tables already have the correct collation -> nothing to do
> 
> Repair step: Repair SQLite autoincrement
> 
> Repair step: Copy data from accounts table when migrating from ownCloud
> 
> Repair step: Drop account terms table when migrating from ownCloud
> 
> Updating database schema
> 
> Updated database
> 
> Repair step: Delete duplicates
> 
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_options ON oc_polls_options (poll_id, poll_option_text, timestamp)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
> 
> The update was unsuccessful. Please report this issue to the Nextcloud community.
> 
> 

And from the command line:

`/var/www/nextcloud$ sudo -u www-data php ./occ upgrade`

> Nextcloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Set log level to debug
> Turned on maintenance mode
> Updating database schema
> Updated database
> Updating <polls> ...
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_options ON oc_polls_options (poll_id, poll_option_text, timestamp)':
> 
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
> Update failed
> Maintenance mode is kept active
> Reset log level
>

**Comment by dartcafe** [comment]
see https://github.com/nextcloud/polls/issues/1547 for the reported issue.
