### ISSUE TITLE
Select date from to

### ISSUE THREAD

**Issue by Tealk** [nextcloud/polls#201]
Hi,

is it possible to add a feature to select date and time from ... to ...?
eg. if i will create a poll for a whole week I have to choose each day individually, but it would be nice if i click on mondey and slide to the friday

**Comment by joergmschulz** [comment]
Make a text-poll

**Comment by dartcafe** [comment]
Maybe, this could be a nice feature, but I am afraid, this would break the existing concept. I will think it over, when designing the poll creation.

**Comment by horstvogel** [comment]
Hello, dartcafe Selcet time from to is only difficult?

**Comment by dartcafe** [comment]
Ehm. In the end it is concept, coding and testing. All together: work and quality management.

**Comment by kangaroo72** [comment]
I can confirm, this would be very helpful. I'm planning appointments over between months ...
It works, but it takes a lot of time, to click every day of a half year ;-)

**Comment by dartcafe** [comment]
#492
