### ISSUE TITLE
Allow users to load all cells (when threshold is reached)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/polls#2021]
## Describe the goal you'd like to achieve
- As a poll creator, I should not be surprised by the fact that I am not shown all results.
- As a poll creators (and probably as a voter, too), I should be able to see all results if I explicitely wish for and accept performance constraints.
- As a Nextcloud admin, I expected to be able to set the threshold in /settings/admin/polls-admin.

## Describe possible solutions
- When creating a poll, a warning might be displayed that results are limited to the currently set threshold number of cells.
- When displaying the results and parts are hidden due to performance limitations, there should be an explanation on who can change this and how. Neither my poll creator nor myself did find the setting (although settings are always accessed from there in NC app, I agree.
- Ideally, there is a case-by-case override button like "I need to see it anyway and know that this may take a while to compute".
- It might be a good idea not to let users set any value in "their" settings, so on /settings/admin/polls-admin there could be a min-max setting.

**Comment by dartcafe** [comment]
As a workaround it will be possible to export the poll content to different file types. See #2169

**Comment by danir-de** [comment]
This really has been a huge issue for our company. 
Especially for bigger polls, users have started using external poll sites because "they can see everything at once".

The current solution is very unfriendly for the end user and making the average user unable to work with the poll.
