### ISSUE TITLE
[Feature Request] Is integration with circles possible?

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#204]
### Steps to reproduce
1. Feature request

Is it possible to integrate polls with circles for access restriction?

Circles: https://apps.nextcloud.com/apps/circles

For example the files app is using circles to determine who can access what.

**Comment by dartcafe** [comment]
This is a good idea, but I fear we will not begin the integration soon. I will take it to the backlog.

**Comment by splitt3r** [comment]
I will have a look at it together with #82. If we implement some sort of acl i think sharing with a cirle would be not that big deal.

**Comment by sunjam** [comment]
[Deck app has just released Circles integration](https://github.com/nextcloud/deck/pull/923) and I hope this will help you with the Polls app!

**Comment by Booteille** [comment]
Hi.

I am seeing an interest in this feature.
Would you have some time to work on it anytime soon?

**Comment by dartcafe** [comment]
Something, that could be good candidate for the next version, since we updated the invitation system. But actually there are no plans for the feature set of the next version.

**Comment by Booteille** [comment]
I think this is a must have for enhancing the collaboration toolbox.

So I hope you'll be able to work on it.

Thanks a lot for your answer.

**Comment by dartcafe** [comment]
Oviously you challanged me. I integrated circles. Took a lot of work, because some refactoring classes. The branch needs still some polish and testing. See #1128 for details.

**Comment by Booteille** [comment]
Greaaat! Thank you a lot!

I think a lot of people will enjoy this news!

**Comment by kroerig** [comment]
When will version 1.6 be released?

**Comment by dartcafe** [comment]
> 
> 
> When will version 1.6 be released?

Usual answer: When it is ready. 😁

**Comment by dartcafe** [comment]
If anybody wants to test the circles release: https://github.com/nextcloud/polls/issues/1218
Help is always welcome.
