### ISSUE TITLE
User name is prefixed with user_, + incorrect translation

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#206]
### Steps to reproduce
1. Create a poll
2. During the poll creation, select a single user to access the poll
3. Go to the poll home main page
4. Have a look at the newly create poll

### Expected behaviour
1. The user name should be listed without the  'user_'   prefix
2. Dutch translation is wrong (geleden is past).  The translation should be just 3 dagen or 'over 3 dagen'

### Actual behaviour
1. The user name is listed with the  'user_'   prefix
2. Wrong Dutch translation, see screenshot:

![image](https://user-images.githubusercontent.com/2937666/31854071-db042860-b693-11e7-9d3c-de028a6f030c.png)

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite3

**PHP version:** 7.x

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Where did you install Nextcloud from:** nextcloud

**Comment by dartcafe** [comment]
@v1r0x Is the issue with the username related to #82?
The translation comes from the core, but it is not a translation error, the calculation is a bug, because it always assumes, that the timespan always directs to the past. There is a merged PR for NC13 (https://github.com/nextcloud/server/pull/6837).

**Comment by v1r0x** [comment]
@dartcafe yes, this is related.

**Comment by dartcafe** [comment]
For the datespan and timespan checks, I asked for backports: 
https://github.com/nextcloud/server/pull/6896
https://github.com/nextcloud/server/pull/6897

**Comment by dartcafe** [comment]
Nextcloud PRs are merged for the NC12-stable and NC11-stable branch. Wait for new version or apply the patch.

**Comment by dartcafe** [comment]
User naming is subject of #82. Time span is fixed with last server releases.
