### ISSUE TITLE
"invalid name" can be very confusing on public poll shared by link

### ISSUE THREAD

**Issue by tqzamf** [nextcloud/polls#2067]
## Describe the goal you'd like to achieve

I once again managed to position myself as the idiot whose stuff never works right, by creating a poll for some private event. And fatally, during testing, entered one of my friends' names in the "pick a username" box. This blocked their name because it got associated with my (anonymous) cookie, so they got the "invalid name" message, consequently judged the app as "doesn't work" and gave up (2 out of 4 people). I then spent 15 minutes tracing this down, finally realizing that the usernames were taken even though no votes had ever been cast using those tokens.

As a gut feeling, I would expect this dialog to simply accept any name and then get out of the way. Probably reject the empty string, maybe reject a name that is already in use in the given poll, but certainly accept a name that has never answered that poll before. So the use case would go something like:

- I visit a link to a site I have never seen before and get greeted with a somewhat unexpected popup
- I enter whatever I consider my name *and have it accepted*
- I choose an option and mostly forget about the poll, and the strange site it was hosted on

This is probably the "common" use case for the app when used as a doodle replacement. (Which it otherwise does very well IMO. Love how the text and options update in real time, for example.) It certainly didn't appear to me that I would be creating some sort of account, and the dialog IMHO sounds very much like one doesn't.

Note that as far as I can tell this isn't a bug. Everything seems to work as designed, it's just that "as designed" didn't match what me or my friends were expecting.

## Describe possible solutions

I can think of the following design changes, each of which would have given much a better user experience:

1. Assign a random username to users that arrive by share link, for use in the database (user_id) only. Set display_name to whatever they enter. IMHO it should not check for duplicates, even within that poll. Though I think users are used to uniqueness constraints and would figure it out, certainly when told that the name is not unique.
2. Make it configurable whether duplicate names are allowed or not, and possibly also allow users to edit other people's responses. Then one could allow it in a casual setting where ease of use is most important, but disallow duplicates (and editing) in e.g. a business setting where there may not be mutual trust.
3. Rephrase the message to make it clear that the name entered there needs to be unique, or call it a username. People are used to having their usernames called invalid; not so much their personal names. That is probably the easiest solution, but when users lose their cookies (sooner or later they inevitably do) one ends up with names like matthias3762, to make them unique.

## Additional context

No mockup, since I don't think the layout actually needs to change, just behavior, or even just texts. Had the text simply said "duplicate name" instead, I doubt anyone would have even noticed it as more than a minor annoyance.

I may end up sending a merge request for 1. if I find the time. I'm a horrible PHP programmer though.

**Comment by dartcafe** [comment]
Thanks for the time taken to describe your issue in this understandable manner. 

Since the username is the unique identifier, duplicates are forbidden. This unfortunately is also the case for usernames and groupnames from actual users of the site. So it is not possible to enter a name, which already exists in the current poll or systemwide. So we can't pass the name check. At leas not without a huge change in the model and followed code changing and testing. The price is rather high compared to the value.

Calling it a `username` did already lead to confusion, because site users tried to use their username and login this way. Also users already complained, that they could not tell, which user is who because of duplicate names; Something what is also possible with doodle.

A random name was a prior idea, but we also have to send it through the duplicate check. So, no win.

The text is also taken by intention to avoid direct hints to internal usernames. We can rephrase the error message to something more clearer, so that people understand that a duplicate check does prohibit the chosen name, which is no secret.

Proposal: 'The name is invalid or already in use, please chose another name for this poll.'

**Comment by tqzamf** [comment]
Well thanks for the extremely quick reply. You're making a good point about "username" there. It does tend to mean "I can then log in with that", certainly when there's a login button right next to it.

I quite like the text you propose, it makes it a lot more obvious what is wrong... Also I didn't find an option to change the name afterwards, so I agree that it's probably better to just force a unique one initially.

Thinking about it some more, and reading some of the code, it does seem that the name needs to be unique *within a poll* but not globally? That does seem to be the behavior, but I misunderstood it as "globally unique" initially. In that case, that only leaves the somewhat confusing behavior when a users enters their name but then doesn't select an option. That is:

- I visit the poll and dutifully enter my name, to get rid of the popup
- I look at the options but don't choose one (perhaps realizing that I need to check my work calendar first)
- I visit the poll again on a different device
- when I enter my name it is already taken, but confusingly doesn't show up in the list of votes

This could probably be avoided by delaying user creation until the user actually selects something (IIRC that's how doodle does it). Not sure whether that's worth it though: Fairly complicated logic for a rare use case. And a potential race condition if two users try to vote at the same time.

**Comment by dartcafe** [comment]
It must be "global unique" to avoid confusion with site users who are invited to the poll, too.
