### ISSUE TITLE
Poll not displayed correctly in Chromium (at linux)

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#207]
### Steps to reproduce
1. Create a poll
2. View the poll in Chromium
3.

### Expected behaviour
  The poll should be displayed correctly  (with red, yellow and green colors)

### Actual behaviour
  No table and no colors, see screenshot

![image](https://user-images.githubusercontent.com/2937666/31854639-ddb2202c-b69c-11e7-8ceb-70efe9774d35.png)

The table is shown correctly in firefox.

### Server configuration

**Operating system**: Linux

**Web server:** apache 

**Database:**  sqlite3

**PHP version:** 7.x

**Nextcloud version:** 12.0.3

**Where did you install Nextcloud from:**  Nextcould packages

Browser information:
Chromium 61.0.3163.100 at openSUSE 42.2

**Comment by splitt3r** [comment]
Any errors in the dev tools console?

**Comment by radoeka** [comment]
Not related to the page (the reported error is seen at (all) other pages).
I verified with Chrome at windows (same version), and there it is displayed correctly.

**Comment by dartcafe** [comment]
And which error is reported?

**Comment by dartcafe** [comment]
I testet on Chromium 61.0.3163.100 on Ubuntu 17.10 (64 bit): No issues... 
Is it possible, that this is a caching issue?

**Comment by radoeka** [comment]
Reloading the page resulted made it work.

Any idea why the page was not loaded correctly initially?  As I did not know what to expect, the page looked rather odd.  As such I did not think of reloading the page.

Issue is about to get closed.

**Comment by v1r0x** [comment]
If you had an older version of polls installed your browser has some of these files cached for faster page load and network traffic. Even if the content has changed, your browser loads the cached files instead of load the new files. `Ctrl + F5` should help in most cases.

**Comment by radoeka** [comment]
I did not have polls installed before.  That's why it is confusing.  Initial setup, initial visit resulting in incorrect displaying of the poll.  Anyway, problem was indeed solved by Ctrl + F5
