### ISSUE TITLE
Cannot Delete an empty vote

### ISSUE THREAD

**Issue by jstampfer** [nextcloud/polls#2071]
I created a poll. 
I distributed an public link.

One user just entered his name, but did not make any voting.
If I try to delete this row. It is not possible, but in the upper right it comes "User XXXX removed" after 3 seconds.
But one second later, the empty row appear again.

I tried to delete any other row - with entries - without any problems. 
Just only this user cannot be remove
![cannotdelete](https://user-images.githubusercontent.com/57633002/140029841-de284856-6f81-4f3d-a266-101276d6b5d7.png)
.

**Comment by dartcafe** [comment]
Please fill out the issue form and check the logfil for error messages.
https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=bug_report.md

**Comment by jstampfer** [comment]
There are no errors in the Logfile
