### ISSUE TITLE
 Cannot Delete an empty vote

### ISSUE THREAD

**Issue by jstampfer** [nextcloud/polls#2073]
## What is going wrong? What did you observe?
**Describe the bug**

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Go to 'https://www.asdfasdf.com/apps/polls/s/qdB8lO64yafjX8S1'
2. Click on 'garbage can of the user'
3. No Error in the Logfile but the entry of the user will not be removed as seen in the screenshot

**Add a screenshot of the misbehavior**

![cannotdelete](https://user-images.githubusercontent.com/57633002/140046744-6a41ffb5-9a94-4c80-843b-c53170d843fc.png)

## How should it work?
**The User or better the entry of the user should be deleted**

A clear and concise description of

## Information about your polls installation
**3.3.0** (see apps page)

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [ x ] Update from a prior version
  Version number of the previous version: the previous version

**How did you install this version?(Appstore or describe installation)**

- [ x ] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
** Nextcloud 21.0.5 :** (see Nextcloud admin page)

<details>
<summary>
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - analytics: 3.6.1
  - announcementcenter: 5.0.1
  - audioplayer: 3.2.2
  - calendar: 2.3.4
  - circles: 0.21.4
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.5
  - drawio: 1.0.1
  - external: 3.8.2
  - extract: 1.3.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.1
  - files_downloadactivity: 1.11.1
  - files_fulltextsearch: 21.0.4
  - files_mindmap: 0.0.25
  - files_retention: 1.10.2
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - fulltextsearch: 21.0.3
  - fulltextsearch_elasticsearch: 21.0.2
  - groupfolders: 9.0.3
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.5
  - nextcloud_announcements: 1.10.0
  - notes: 4.1.1
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.2.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 3.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
Disabled:
  - encryption
  - files_external
  - files_pdfviewer
  - passwords
  - user_ldap

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "XXX.XXX.XXX",
            "www.www.ww",
            "yyy.www.ww"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.5.1",
        "overwrite.cli.url": "https:\/\/www.www.ww\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": "false",
        "logtimezone": "Europe\/Vienna",
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "theme": "",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "at",
        "memcache.local": "\\OC\\Memcache\\Redis"
    }
}

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ x ] MySql version: 8.0.27
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ x ] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [ x ] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [ x ] Chrome version: 95.0.4638.69 (Offizieller Build) (64-Bit)
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```No Error in Logfile
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
index.js:46 No OC found
Fr @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
polls.js?v=d2a503d9-9:2 Proxying an event bus of version 1.2.0 with 2.1.0
e.ProxyBus @ polls.js?v=d2a503d9-9:2
session-heartbeat.js:97 session heartbeat polling started
polls.js?v=d2a503d9-9:2 RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at o.initials (polls.js:2)
    at vn.get (polls.js:2)
    at vn.evaluate (polls.js:2)
    at o.initials (polls.js:2)
    at o.<anonymous> (polls.js:2)
    at o.t._render (polls.js:2)
    at o.r (polls.js:2)
    at vn.get (polls.js:2)
    at vn.run (polls.js:2)
Vt @ polls.js?v=d2a503d9-9:2
polls.js?v=d2a503d9-9:2 RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at o.initials (polls.js:2)
    at vn.get (polls.js:2)
    at vn.evaluate (polls.js:2)
    at o.initials (polls.js:2)
    at o.<anonymous> (polls.js:2)
    at o.t._render (polls.js:2)
    at o.r (polls.js:2)
    at vn.get (polls.js:2)
    at vn.run (polls.js:2)
Vt @ polls.js?v=d2a503d9-9:2
polls.js?v=d2a503d9-9:2 RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at o.initials (polls.js?v=d2a503d9-9:2)
    at vn.get (polls.js?v=d2a503d9-9:2)
    at vn.evaluate (polls.js?v=d2a503d9-9:2)
    at o.initials (polls.js?v=d2a503d9-9:2)
    at o.<anonymous> (polls.js?v=d2a503d9-9:2)
    at o.t._render (polls.js?v=d2a503d9-9:2)
    at o.r (polls.js?v=d2a503d9-9:2)
    at vn.get (polls.js?v=d2a503d9-9:2)
    at vn.run (polls.js?v=d2a503d9-9:2)
Vt @ polls.js?v=d2a503d9-9:2
Wt @ polls.js?v=d2a503d9-9:2
zt @ polls.js?v=d2a503d9-9:2
t._render @ polls.js?v=d2a503d9-9:2
r @ polls.js?v=d2a503d9-9:2
vn.get @ polls.js?v=d2a503d9-9:2
vn.run @ polls.js?v=d2a503d9-9:2
Tn @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
Xt @ polls.js?v=d2a503d9-9:2
Promise.then (async)
Qt @ polls.js?v=d2a503d9-9:2
ae @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
vn.update @ polls.js?v=d2a503d9-9:2
pt.notify @ polls.js?v=d2a503d9-9:2
set @ polls.js?v=d2a503d9-9:2
set @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
p._withCommit @ polls.js?v=d2a503d9-9:2
p.commit @ polls.js?v=d2a503d9-9:2
commit @ polls.js?v=d2a503d9-9:2
a.commit @ polls.js?v=d2a503d9-9:2
list @ polls.js?v=d2a503d9-9:2
async function (async)
list @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
p.dispatch @ polls.js?v=d2a503d9-9:2
dispatch @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
loadTables @ polls.js?v=d2a503d9-9:2
watchPolls @ polls.js?v=d2a503d9-9:2
polls.js?v=d2a503d9-9:2 RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at o.initials (polls.js?v=d2a503d9-9:2)
    at vn.get (polls.js?v=d2a503d9-9:2)
    at vn.evaluate (polls.js?v=d2a503d9-9:2)
    at o.initials (polls.js?v=d2a503d9-9:2)
    at o.<anonymous> (polls.js?v=d2a503d9-9:2)
    at o.t._render (polls.js?v=d2a503d9-9:2)
    at o.r (polls.js?v=d2a503d9-9:2)
    at vn.get (polls.js?v=d2a503d9-9:2)
    at vn.run (polls.js?v=d2a503d9-9:2)
Vt @ polls.js?v=d2a503d9-9:2
Wt @ polls.js?v=d2a503d9-9:2
zt @ polls.js?v=d2a503d9-9:2
t._render @ polls.js?v=d2a503d9-9:2
r @ polls.js?v=d2a503d9-9:2
vn.get @ polls.js?v=d2a503d9-9:2
vn.run @ polls.js?v=d2a503d9-9:2
Tn @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
Xt @ polls.js?v=d2a503d9-9:2
Promise.then (async)
Qt @ polls.js?v=d2a503d9-9:2
ae @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
vn.update @ polls.js?v=d2a503d9-9:2
pt.notify @ polls.js?v=d2a503d9-9:2
set @ polls.js?v=d2a503d9-9:2
set @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
p._withCommit @ polls.js?v=d2a503d9-9:2
p.commit @ polls.js?v=d2a503d9-9:2
commit @ polls.js?v=d2a503d9-9:2
a.commit @ polls.js?v=d2a503d9-9:2
list @ polls.js?v=d2a503d9-9:2
async function (async)
list @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
p.dispatch @ polls.js?v=d2a503d9-9:2
dispatch @ polls.js?v=d2a503d9-9:2
(anonymous) @ polls.js?v=d2a503d9-9:2
loadTables @ polls.js?v=d2a503d9-9:2
watchPolls @ polls.js?v=d2a503d9-9:2
async function (async)
watchPolls @ polls.js?v=d2a503d9-9:2

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
I tried to reproduce this behavior, but no luck. I can remove all votes of an user without problems. Is this an internal user or a public user? The image is white. I guess, you overpainted it for privacy reasons, right?

**Comment by jstampfer** [comment]
No. The image is white. I did not overpaint it. 
It is an public user. I distributed the poll via email

**Comment by dartcafe** [comment]
There is a user with an E in his avatar. Is his name Erwin as well? 
I fear I can't analyse further without a look into the vote table.

**Comment by jstampfer** [comment]
Yes it is. It is Erwin to but the whole user is "Erwin LASTNAME", not just Erwin.
Should I send you a dump of the vote table?

**Comment by jstampfer** [comment]
id  | poll_id |        user_id         | vote_option_id |                   vote_option_text                    | vote_answer
-----+---------+------------------------+----------------+-------------------------------------------------------+-------------
 312 |      14 | Erwin                          |             82 | 2021-12-01T08:00:00+00:00 - 2021-12-01T12:00:00+00:00 | no
 353 |      14 | Erwin.LASTNAME       |             82 | 2021-12-01T08:00:00+00:00 - 2021-12-01T12:00:00+00:00 | yes
 352 |      14 | Erwin.LASTNAME       |             84 | 2021-11-24T08:00:00+00:00 - 2021-11-24T12:00:00+00:00 | yes

I found this entries in the oc_polls_vote. 
The user is the same. I think, he did not vote for anything with his first entry "Erwin".
A little bit later, he clicked the link a second time and voted with user "Erwin.LASTNAME".

**Comment by dartcafe** [comment]
The reason, why there is still a row for Erwin, is the line no. 312. 
Strange, that this entry doesn't get deleted. But he dump helps analyzing. I will come back to this.

**Comment by dartcafe** [comment]
Just to be sure. You are aware, that the deletion is executed delayed after a countdown of 5 seconds? If you close the page or refresh it, the deletion will get interrupted.

**Comment by jstampfer** [comment]
Yes. I wait for at least 5 Minutes. The countdown works perfect. After the 5 seconds the row disappears and appears in the blink of an eye again.

**Comment by dartcafe** [comment]
And you get a success message in upper right corner?

**Comment by jstampfer** [comment]
![image](https://user-images.githubusercontent.com/57633002/141702997-26308a26-0b56-4cc1-8261-37909ef06a88.png)

yes

**Comment by dartcafe** [comment]
I am still not able to reproduce this issue. Try to delete erwin from this poll via database and observe, if this happens again.

**Comment by wisski77** [comment]
I can confirm the issue. The (external) user vote gets deleted (with a success message in the upper right), but reappears after a few seconds.
