### ISSUE TITLE
[Discussion] Redesign of the shares tab

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#2076]
Sometimes new or unexperienced users seem to have problems to understand, if their poll is published and/or to whom. We have two places, where the access is configurable
* In the configuration tab, the internal access is defined, if only invited or all users can access the poll and if an administrator is allowed to edit the poll
* In the shares tab, permission to the poll is granted via creating a share or a public link

Problems. I see:
* Users create a poll and leave the permissions to default (Only invited users have access) and wonder, why no one can access the poll
* Granting the edit right to admins is maybe critical, as most users will not know, who has admin rights.
* The connection between 'Allow only invited users to access the poll' and the shares is probably not clear.
* The term 'share' does not automatically include permission in a user's eye
* probaly more misleading or misunderstandable things

Goal: 
* reduce confusion about how to grant acces to the poll
* have all access/share settings in one sidebar tab
* less elements in the gui

Following changes were made so far:
* moving the access configuration for 'all or only invited people' to the share tab and change it to a toggle on top of the shares
* removed the relevant toggle and use relevant as default, if a poll is shared with all users
* removing the option to grant admins edit rights (individual shares can be allowed to edit the poll since version 3.3)
* combine the share lists and do not use a separate list for public shares
* sort shares (All, public links, users with admin access, groups, users, ...)
* rearranged the section (public share settings, unsent invitations, shares)
* Added a hint, that contact groups and circles have to be resolved first
* add a message, if the poll is not accessible for other users (no shares and no access for all users)
* moved the registration screen for public polls configuration to the share and make it configurable per public share

Current layout | Proposal Iteration one | Proposal Iteration two | disabled 'All users' and added public link (rearranged view)|per share options
-|-|-|-|-
![grafik](https://user-images.githubusercontent.com/26707476/140394603-8492953b-ce7e-421e-8e5b-6ef96ec8809c.png)|![grafik](https://user-images.githubusercontent.com/26707476/140394658-221f5c8e-4859-4b94-9f75-fd6d1cbc505d.png)|![grafik](https://user-images.githubusercontent.com/26707476/141671017-5834e079-aca3-4bf2-b225-280249e07d4a.png)|![grafik](https://user-images.githubusercontent.com/26707476/141696538-1f638764-d392-4edf-835c-a062750155b4.png)|![grafik](https://user-images.githubusercontent.com/26707476/143495342-f3fd2288-9f30-4b2c-b3b9-a8310fa053f6.png)

Warning, that no one can access the poll (button opens the share tab inside the sidebar):
![grafik](https://user-images.githubusercontent.com/26707476/141696591-9d87d15c-4b76-4b8d-8a98-1d6edc6bb523.png)

I will be glad, if some people would leave their impression and possibly some proposals for a good UX.

**Comment by dartcafe** [comment]
@jancborchardt Maybe you have some good remarks?

**Comment by tobyps** [comment]
Looks good.

Calling it access fits but might collide with the overall approach of calling it shares in most other apps.

I'd move the list of active shares to the bottom, so all general options are above.

Making relevant for all users active as standard sounds good but it should stay an option.

I think a manual could be helpful as polls has quite a lot of options and possibilities.
It's probably more work than I imagine but at least users like me who don't program can contribute with that.

**Comment by dartcafe** [comment]
Hey @tobyps Thanks for the time and feedback.

> Calling it access fits but might collide with the overall approach of calling it shares in most other apps.

Yes, that's what I thought to. 

Another idea: 
Add a virtual share "All users". So we can get rid of the radio buttons and it is straight forward like public, group or personal shares. And the tab can still be called "Shares". 

> I'd move the list of active shares to the bottom, so all general options are above.

Then the options for the public shares can be left there. Or we move it to an individual share configuration.

> Making relevant for all users active as standard sounds good but it should stay an option.

Do you think, this is really necessary? I would say: If a poll should be shared to all users, it is relevant for all users.

Also, I think, we should sort the shares by type: 
1. "All users"
2. public shares
3. Groupd shares
4. personal shares

> I think a manual could be helpful as polls has quite a lot of options and possibilities.

I prefer a better UX over a manual or explanation. If UX is not possible, then there should be an info button with an explanation. 

>  It's probably more work than I imagine but at least users like me who don't program can contribute with that.

I don't think, that there is so much work to do. A good start could be the admin and user configuration. The wording is some sort of unlucky ("Disallow, but add groups, but If you don't ..." ). And there is room for explanations near the toggles. 

So, If you mind: Help is always appreciated. 😁

**Comment by WNYmathGuy** [comment]
I don't know if this is a good place or the right place to bring this up, or if it's a bug I'm identifying, but...

While trying to share a poll to select officers of a board serving a 501(c)(3) non-profit in the USA, I discovered I couldn't get the expected results for the ad-hoc "Contact group" `Board_Members` in the **Shares** section of your Polls app. I had to select each member individually. I think it's a bug because the `Everyone` group is selectable the way individual users are.

- NOTE: _your UI classifies_ `Board_Members` _as_ `Contact group` _but the_ `Everyone` _and_ `admin` _are just classified as_ `Group`
- NOTE: `Board_Members` _was made in the UI section for_ `.com/index.php/settings/users`  

What happens for a built-in group like `Everyone` or `admin` is the **Effective Shares** area lists them just like the **Unsent Invitations** section does.

What happens for an ad-hoc group like `Board_Members` or `Unit_Owners` is the **Effective Shares** area remains empty, but the **Unsent Invitations** section gets populated.

In this current use case, it's an anonymous poll, only logged-in users in a group get to vote and only one Yes per person is allowed. I don't want the additional eMail going out to invite people who heard about the poll during a conference call. I find that **Unsent Invitations** section confusing. If I try to remove an unsent invitation I remove the share, but if I leave an **Unsent Invitations** alone, nothing seems to happen. Like how would I send it if I wanted it to be that way?

**Comment by dartcafe** [comment]
> I don't know if this is a good place or the right place to bring this up

Not really. Please open another issue for that or use the forum (https://help.nextcloud.com). But I can say, that contact groups are not usable for direct access like user groups. They contain just (external) contacts and no user objects. 

What you write is confusing: 
> the ad-hoc "Contact group" `Board_Members`
>     * NOTE: `Board_Members` _was made in the UI section for_ `.com/index.php/settings/users`

Either you created a user group with this name or you get a contact group. Maybe you have a user group called 'Board_Members' and a contact group with this name as well.

The listing in the 'unsent invitations' section is just for indicating, that an invitation is not sent. In case of a contact group, the share has to be resolved and then sent to the resolved members. Otherwise, the external contact will have no knowledge of the personal vote link.

**Comment by WNYmathGuy** [comment]
> Either you created a user group with this name or you get a contact group. Maybe you have a user group called 'Board_Members' and a contact group with this name as well.

Were making progress then, Your second assumption was correct, and I didn't even think of that partly because my Contacts app won't upgrade out to 4.0.4 right now. I created both identically named items, but I cannot access the `Group` named `Board_Members` because the interface only shows the `Contact group` with that name.

Your software is making a lot more sense now with respect to unsent invitations.

**Comment by dartcafe** [comment]
>  I created both identically named items, but I cannot access the `Group` named `Board_Members` because the interface only shows the `Contact group` with that name.

In this case, please open another issue, so I can check that. If it is, as you describe, this is a bug.

**Comment by dartcafe** [comment]
Update

Current layout | Proposal Iteration two | disabled 'All users' and added public link
-|-|-
![grafik](https://user-images.githubusercontent.com/26707476/140394603-8492953b-ce7e-421e-8e5b-6ef96ec8809c.png)|![grafik](https://user-images.githubusercontent.com/26707476/141671017-5834e079-aca3-4bf2-b225-280249e07d4a.png)|![grafik](https://user-images.githubusercontent.com/26707476/141671129-4fa06a48-b1a0-47d0-884f-0af5a10478f2.png)

**Comment by WNYmathGuy** [comment]
Just wondering, in the third panel "disabled 'All users' and added public link", it looks like a variety of public links could be made. So it's possible to have activity logs tell the poll creator how many people came in from each public link?
I can't see myself using that, but it's definitely a desirable feature for people who care about what venue given a public link brings in the most results.

**Comment by dartcafe** [comment]
> Just wondering, in the third panel "disabled 'All users' and added public link", it looks like a variety of public links could be made.

I don't get your point.

> So it's possible to have activity logs tell the poll creator how many people came in from each public link?

Nope. There is no relation between the public link and the share, which is created upon registriation for the poll.

**Comment by dartcafe** [comment]
At last the options for the registration dialog have been moved to the public share configuration.
![grafik](https://user-images.githubusercontent.com/26707476/143495753-587e38fc-155f-4ac9-b5e6-9a3375f2dac7.png)
