### ISSUE TITLE
Missing "Group" list items in the "Add Shares" chooser

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/polls#2086]
## What is going wrong? What did you observe?
In a recently build NC 22 instance, I have a plethora of User Groups and some similarly named Contact Groups. I can't confirm it at this moment, but I'm confident that the string differs slightly. e.g. the User Group is `Board_Member` and the Contact Group is `Board Member`.

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Create a new or select any existing **Poll**, then open the section for **Shares**
2. Click on the field for **+ Add Shares** and begin to type the letters of one of the user groups.
3. Observe that a **User Group** is not selectable, but a **Contact Group** similarly named is selectable.
4. Keep typing letters till it's a unique **User Group** designation and only the `Everyone` **User Group** will show.

![PollsBugReport2](https://user-images.githubusercontent.com/28640985/141206963-fbaca950-e573-4cb4-bd19-d08b36ce78f0.png)

**Add a screenshot of the misbehavior**
![PollsBugReport1](https://user-images.githubusercontent.com/28640985/141206899-532e072d-7587-4064-ba6d-aa2a654f81ad.png)

![PollsBugReport3](https://user-images.githubusercontent.com/28640985/141207053-29302dfa-a86d-40fe-828a-f2e3543e3ac8.png)

## How should it work?
The interactive filter/group chooser share field needs to be able to display general user groups that administrators created in a NC instance.

A clear and concise description of

## Information about your polls installation
**Polls version:** 3.3.0

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version? (Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

### Generated System Report
Link: [https://service.harrogatesquare.com/index.php/s/w7DH2Ay6w25iG5s](https://service.harrogatesquare.com/index.php/s/w7DH2Ay6w25iG5s)
Password: `eeQp7cl97FYSPV9fhbnS`

**Comment by dartcafe** [comment]
I cannot reproduce this, I get the user group and the contact group as well.
Please check your sharing settings `settings/admin/sharing`

**Comment by WNYmathGuy** [comment]
> If this is checked, you have to be member of the group, you search for.
> ![grafik](https://user-images.githubusercontent.com/26707476/141347097-dac35867-eb07-4264-81f1-0419ecc5a4ad.png)

That's not checked on either of my NC instances. 

I did more experimentation when I got home yesterday. My older but fully upgraded NC instance has trouble with the same thing as the new NC instance. What I'm finding out right now, is it might be a couple of factors based on experimentation. 

1. Users, contact lists, and contacts are discovered with case insensitive searches, user groups are requiring case sensitive strings
2. User groups that are all lower-case one-word alpha strings come up in a partial search.
3. User groups that contain non-alphabet characters or mixed case strings need an exact match and the full string to be listed.

![Screenshot from 2021-11-11 20-46-46](https://user-images.githubusercontent.com/28640985/141602659-c703c3cc-a947-4360-828b-6fa826260c35.png)

![Screenshot from 2021-11-11 20-47-07](https://user-images.githubusercontent.com/28640985/141602666-225729f8-3838-421e-8aca-fb2e3fec64a6.png)

![Screenshot from 2021-11-11 20-23-00](https://user-images.githubusercontent.com/28640985/141602675-3b9ea9ec-ea8b-45cb-bb33-2ad0ddf21fd1.png)

![Screenshot from 2021-11-11 20-29-58](https://user-images.githubusercontent.com/28640985/141602680-c266128b-6225-460f-82ef-e996eb3032c2.png)

![Screenshot from 2021-11-11 20-32-00](https://user-images.githubusercontent.com/28640985/141602684-2af6f51b-f0aa-43e9-9be9-7f24e0d873cc.png)

![Screenshot from 2021-11-11 20-45-28](https://user-images.githubusercontent.com/28640985/141602695-4fce17da-ae33-4281-b5c3-593364b6cd67.png)

**Comment by dartcafe** [comment]
Even this is not reproducable for me: 
![grafik](https://user-images.githubusercontent.com/26707476/141649073-89e08792-7165-4901-8c5d-6559c5209b26.png)

**Comment by WNYmathGuy** [comment]
Well, hell. Would the version of MariaDB or MySQL make a difference? I don't use the lower number ones from APT for Ubuntu, I have the better ones direct from the maker's sites.

**Comment by dartcafe** [comment]
Group searching is done here, using the core GroupManager: https://github.com/nextcloud/polls/blob/ca43714937e58e357c96b7685b98e95b321b8599/lib/Model/UserGroup/Group.php#L63-L77

The app forms no SQL statements. And I don't think that the version makes any difference.

Is there any difference between adding a share in the polls app to adding it in the files app?
