### ISSUE TITLE
Display comment field and url information at the bottom of the poll page

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#209]
### Steps to reproduce
1. Create a poll
2. Look up the poll
3.

### Expected behaviour
Comment field and url information are displayed at the bottom of the poll page
It makes the page easier for the eye.
More timeslots can be displayed next to each other.
When the position right as well as at the bottom are desired, could it be made configurable?  So the admin can determine where it is displayed.

See screenshot for mockup

### Actual behaviour
Comment field and url information are displayed at the right side of the poll page
(this is not bad or so)

![image](https://user-images.githubusercontent.com/2937666/31859994-39bf4968-b714-11e7-8dd8-0fd1c4e12a4f.png)

### Server configuration
**Operating system**: linux

**Web server:** apache

**Database:** sqlite3

**PHP version:** 7.x

**Nextcloud version:** 12.0.3

**Where did you install Nextcloud from:** nextcloud

**Comment by dartcafe** [comment]
As the comments went to the side bar, I close this issue.
