### ISSUE TITLE
change polls results of users

### ISSUE THREAD

**Issue by charly1080** [nextcloud/polls#2092]
is there a possibility as administrator to change polls results of users?
perhaps also change the name of the user - because of tip error?
add a new users result because not every person will go online to add his or her opinion

thank you in advance for your support

**Comment by dartcafe** [comment]
> is there a possibility as administrator to change polls results of users?

no

>  perhaps also change the name of the user - because of tip error?

Not yet (for external users).

>  add a new users result because not every person will go online to add his or her opinion

not planned

**Comment by cptMikky** [comment]
> add a new users result because not every person will go online to add his or her opinion

you can do this yourself as if you were the user - simply open the poll link in an anonymous browser window and when prompted for user name, enter whatever you need
