### ISSUE TITLE
Unique violation: 7 ERROR: duplicate key

### ISSUE THREAD

**Issue by Deltafox01** [nextcloud/polls#2095]
We cant activate Polls again on our school server ....

This is the Error Message we are getting:

`An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "uniq_votes" DETAIL: Key (poll_id, user_id, vote_option_text)=(24, Max Mustermann, 2021-06-22T22:00:00+00:00 - 2021-06-23T22:00:00+00:00) already exists.
`

**Comment by dartcafe** [comment]
Please use the form, when submitting a bug. We need information to reproduce that: https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=bug_report.md

**Comment by Deltafox01** [comment]
You cant reproduce this one.

Can you tell me how to delete all those entries? Or fresh reinstall Polls, so there is no old trace of it after i reinstall it?
Where are the config files located?

After deletion and reinstall it always finds that oney Person again, when i try to activate Polls, and it wont activate.

So there have to be some traces left... even after i delete the Polls app....

**Comment by dartcafe** [comment]
> You cant reproduce this one.

At least, I have to understand what the path to the error was. Without further information, I can only guess. 

Unfortunately the tables of apps are not removed after uninstalling the app. 

To remove poll completely, you have to 
* delete all tables beginning with `oc_polls` from the database. 
* Additionally all migration entries have to be removed: Delete all poll related entries from the `oc_migrations` table. 
* At last, but not really necessary, there are some entries belonging to polls in the `oc_appconfig` table, which can be removed. But it work out without deleting them.

After that enable polls again and the tables get recreated.

**Comment by Deltafox01** [comment]
Thank you VERY much for your answer.
Ive used Phpmyadmin and deleted the corrupt POLL ID & its corresponding votes.
After i did that, i could install & activate Polls without any problems.
