### ISSUE TITLE
Position "Receive notification email on activity"

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#210]
### Steps to reproduce
1. Create a poll
2. As user visit the poll
3.

### Expected behaviour
The button and text "Receive notification email on activity" should be left aligned with the table and 'vote' button above it.

I think that it would be better to first display the text "Receive notification email on activity"
and after that put the vote button
As one reads from top to bottom, with the proposed order one encounters the notification question before the vote (submit) button instead of afterwards.

See screenshot how it looks like

### Actual behaviour
Text is not aligned and put below the vote button

![image](https://user-images.githubusercontent.com/2937666/31859985-263af9d2-b714-11e7-8b34-777123cd5c0a.png)

### Server configuration
**Nextcloud version:** 12.0.3
**Poll version:** 0.8.0
**Where did you install Nextcloud from:** nextcloud

**Comment by radoeka** [comment]
A bit related to #190

**Comment by dartcafe** [comment]
I would prefer, to put it behind the vote button on the right side. Or to the sidebar, but we need to persist the choice in the moment the toggle is switched. But this could be complicated, if the user does not vote...

**Comment by dartcafe** [comment]
Moved the check box behind the vote button. 
![grafik](https://user-images.githubusercontent.com/26707476/33977905-7f971c42-e09d-11e7-8829-1d0c645b7e31.png)
And for mobile view.
![grafik](https://user-images.githubusercontent.com/26707476/33977930-a2c47f98-e09d-11e7-914e-c72b0617ecfd.png)
