### ISSUE TITLE
Hyperlink recognition in text vote options

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/polls#2102]
## Describe the goal you'd like to achieve

As a **poll owner**, I want to be able to enter hyperlinks to poll vote options that would automatically be recognized as links and made clickable, because it would make polls with hyperlinks more user friendly.

Alternatively / additionally, as a  **poll owner**, I would like to be able use Rich text in poll vote options, preferably using Markdown, for the same reasons as above - because it would make poll vote options more user friendly (possibly duplicate of #1912, although it is not clear in that issue which text the OP wants to be "rich")

## Additional context
This request comes from my users whose feedback on a poll where the poll vote options were made of hyperlinks was along the lines of *why aren't the links clickable? This is not user-friendly*.

**Comment by cptMikky** [comment]
I just found a possible duplicate of this issue, #1709, although that one is rather bloated and I'm not 100 % sure the OP wants the same thing. You may probably consider my issue a "streamlined" version of #1709.

**Comment by dartcafe** [comment]
Yes. I'll close #1709

**Comment by elearningdienst** [comment]
Yeah, cool. That was my Intention, as well. Thanks.
