### ISSUE TITLE
Poll shows wrong time on the day of daylight saving change

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#211]
Polls show the wrong time in the poll, on the day, the day light saving changes. 

1. Create a date poll with an option on 2017 October 29th 9:00
2. The poll shows an option for 2017 October 29th 8:00

All other dates (28th and 30th for example) are interpreting the time zone correct.

**Comment by dartcafe** [comment]
Note to @dartcafe
Short analysis: 
- The calculated time in the vote page is correct referring the stored time (from Oct. 29th on time in Europe is UTC+1). 
- The stored time seems to not respect the ending of daylight saving on Oct 29th.
- Behavior is correct before Oct 29th (UTC+2) and after it (UTC+1).

Reproduce Poll with following options:
28.10.2017 07:30 -> DB value '2017-10-28 05:30' ✅ -> vote page: Okt, 28, 07:30:00 (UTC +2) ✅
29.10.2017 07:30 -> DB value '2017-10-28 05:30' ❌ -> vote page: Okt, 29, 06:30:00 (UTC +1) ✅
30.10.2017 07:30 -< DB value '2017-10-30 06:30' ✅ -> vote page: Okt, 30, 07:30:00 (UTC +1) ✅ 

Need to investigate on writing the UTC time. There seems to be an error on writing the selected vote time to the db.

**Comment by v1r0x** [comment]
> Need to investigate on writing the UTC time. There seems to be an error on writing the selected vote time to the db.

@dartcafe Isn't the UTC time written to the DB?

**Comment by dartcafe** [comment]
Yes. But it seems, that the time is assumed to be UTC+2, but it is UTC+1 from Oct 29th on. 
See https://nc13.yagst.de/index.php/apps/polls/poll/b8oIJNNjpx7Rkyei

**Comment by v1r0x** [comment]
https://github.com/nextcloud/polls/blob/master/lib/Controller/PageController.php#L478 is the line where it's added to the db. I'll have a look at phps `date` function and how `$el` is formatted tomorrow.

**Comment by v1r0x** [comment]
I had a look at the timestamps coming from JS (the values in `$el`) and they are wrong. I think this is a bug in the datepicker lib. I also tried the latest version (2.5.11) and it doesn't work.

**Comment by dartcafe** [comment]
Hmmm. I would say, overwork to the create page should be the next project. So we can use another date picker and another way to build more flexible poll options. The problem will occur next time in march. Until then, we have time. 🤣

**Comment by v1r0x** [comment]
I thought about switching to a js framework. But I only know how to use Angular1 which is rather old.
Maybe vue.js is worth looking at. Would save us a lot of js code and overall complexity.

**Comment by dartcafe** [comment]
We should use the core timepicker. Makes it more unique for the user and it is build in. See: https://github.com/nextcloud/server/issues/6348 and recent related issues.

**Comment by v1r0x** [comment]
Yes, as soon as it is available. If it is something that should be fixed before the new NC datetimepicker (NC 14 I think), it should be passed over to the current datetimepicker lib.

**Comment by splitt3r** [comment]
+1 for using vue.js! I also thought about having a look at it.

**Comment by v1r0x** [comment]
I'd suggest to switch (on a dev branch) to vue.js after @dartcafe has finished the UI improvements.

**Comment by BurtGummer** [comment]
I have almost the same problem with the time. I create a poll around 09:59, but the comments show times 09:05 and 09:10 ...

**Comment by jgrete** [comment]
Another date problem: choosing an expiration date X days from now results in an expiration date X days BEFORE now.
Example: Current day 16th of november. Choose 19th of november as expiration date and you'll get
"expired since 3 days". Maybe it is just a misplaced sign within the date calculation or a method call with interchanged arguments or a wrong translation ??

**Comment by v1r0x** [comment]
@jgrete You talk about the label displayed in the UI, not the date stored in the DB? The wrong translation is fixed in NC 13 (I think), but I don't know if it's available in NC 12 as well. @dartcafe can give more information (hopefully :wink: )

**Comment by jgrete** [comment]
@v1r0x Ok, I'll wait until tomorrow. If it's only the translation the absolute value will decrease, if not increase

**Comment by dartcafe** [comment]
See here: https://github.com/nextcloud/server/pull/6897, https://github.com/nextcloud/server/pull/6896 and
https://github.com/nextcloud/server/pull/6837 are already merged to corresponding branch. You have to wait for the releases.

**Comment by dartcafe** [comment]
No further investigation, since this appears to happen only twice a year. No chance of reproduction right now.
