### ISSUE TITLE
Wrong messages in auto-reminders for polls without expiration date

### ISSUE THREAD

**Issue by nextcloud486153** [nextcloud/polls#2113]
## What is going wrong? What did you observe?
**Describe the bug**

The information that explains auto-reminders mentions the expiration date in the case where there is none. I noticed this while translating these strings, so I don't know where they appear in the app.

**Steps to reproduce the behavior**
1. Open "[src/js/components/Configuration/AutoReminderInformation.vue](https://github.com/nextcloud/polls/blob/7f1d1a53f0b89ea2a87943554071a95f7d5dc0f6/src/js/components/Configuration/AutoReminderInformation.vue)".
2. Lines 34-35 are identical to lines 28-29, even though the first pair is for date polls wihout expiration and the latter pair is for polls with expiration.

## How should it work?
**What you expected to happen?**

The strings on lines 34-35 should be different.

## Information about your polls installation
**Polls version:** v3.4.0-beta1 (and master), it was introduced in e36431e.

## Other information

The rest of the bug report template doesn't apply: the bug is not related to any of them.

**Comment by dartcafe** [comment]
Hey, thanks for reviewing. 

Maybe the difference should be emphasized. But I fear formatting is not possible inside the pop over. 

The first information refers to the expiration date.
https://github.com/nextcloud/polls/blob/7f1d1a53f0b89ea2a87943554071a95f7d5dc0f6/src/js/components/Configuration/AutoReminderInformation.vue#L26-L30

The second refers to the first date option
https://github.com/nextcloud/polls/blob/7f1d1a53f0b89ea2a87943554071a95f7d5dc0f6/src/js/components/Configuration/AutoReminderInformation.vue#L32-L36

**Comment by dartcafe** [comment]
Argh. You seem to refer to the ending part of the explanation. It should be `first date option` instead of `expiration`.
