### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [nextcloud/polls#2117]
Please add compatibility with Nextcloud V23

**Comment by micah** [comment]
https://github.com/nextcloud/polls/issues/2109 does indicate that the Beta supports it

**Comment by brtptrs** [comment]
For me 3.4.0-beta1 seems to work very well on NC23. Thanks!!
https://github.com/nextcloud/polls/releases/tag/v3.4.0-beta1

**Comment by dartcafe** [comment]
We had to wait for some translations to arrive before the release, but you can safely enable version 3.3 in NC23 or download the 3.4 release from the releases page: https://github.com/nextcloud/polls/releases/tag/v3.4.0

Appstore will take some time.
