### ISSUE TITLE
Calendar check for subscribed calendars also

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/polls#2122]
## Check against internal AND external calendars

I want to be able to check poll answers not only against my Nextcloud calendars, BUT ALSO external calendars which are subscribed in Nextcloud calendar (ics subscriptions etc.)

Why? Users not necessarily have all their calendars (private, business) in Nextcloud - So personal availability is the sum of multiple external and internal calendars.

**Comment by dartcafe** [comment]
See #1531
