### ISSUE TITLE
Pools list view is empty

### ISSUE THREAD

**Issue by an0o0nym** [nextcloud/polls#2127]
## What is going wrong? What did you observe?
**Describe the bug**
After creating a new poll I click on any of available menu options (Relevant, My Polls, etc.) but the view is empty. It only says: 

" No polls found for this category

Add one or change category! "

**Steps to reproduce the behavior**
1. Click on 'Add new Poll'
2. Fill up the title
3. Set some "Available Options" to the poll.
4. Click on any of menu items on left hand side (Relevant, My polls, Hidden polls etc.).

## How should it work?
I would expect that the newly created poll is visible when I click on any of menu options (Relevant, My Polls, etc.) . I don't see any hits to /polls/ endpoint after creating a poll. However when I hit refresh page in my web browser it does hit eventually that /polls/ endpoint on nextcloud and the list of polls magically appears.

## Information about your polls installation
**Polls version:** (see apps page)
3.3.0

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
22.2.3
<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [ ] PC
- [x] Linux
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: 94.0
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
[polls] watch canceled - restart watch
[polls] update detected 
Array(3) [ {…}, {…}, {…} ]
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
Check, if the polls where automatically archived. There was a bug in version 3.3.0. See #2111

**Comment by an0o0nym** [comment]
@dartcafe  Why did you close it ???

**Comment by dartcafe** [comment]
> @dartcafe Why did you close it ?

Because you said, it was solved after a reload.

> I spent my time to create this issue and you just close it without solving my problem or even suggestion how to fix it? Good job.

I spend my time creating a free app. If you think, filling out an issue template is a nice gesture to solve problems...

> Apparently you don't re-fetch newly created polls or just don't update the UI in the right way.

It gets refetched. No similair issues in any of the instances, I manage. Maybe you have activated periodic polling instead of long polling? Since there are no issues in the logs, I have to believe it was a hick up or configuration problem.
