### ISSUE TITLE
Add support for anonymous proposals of poll options

### ISSUE THREAD

**Issue by cruelsmith** [nextcloud/polls#2136]
## Describe the goal you'd like to achieve
As a poll owner, I want to be able to setup a anonymous polls that also allow to add anonymous proposals, because it helps to create anonymous polls where you do not known all needed options.

## Describe possible solutions
Displaying the owner of the poll option must be removed or must be also anonymised when the `Anonymous poll` setting is enabled and you are not the owner of the poll.

## Additional context
Version of Polls: 3.4.0

**Comment by dartcafe** [comment]
I actually forgot the anonymization of the proposals. Thanks for reporting. Should be fixed now.
