### ISSUE TITLE
Public share ask for optional email address while do not ask for email address has been set

### ISSUE THREAD

**Issue by cruelsmith** [nextcloud/polls#2137]
## What is going wrong? What did you observe?
After creating a public link for a poll with the enabled option `Do not ask for email address` , you are still optionally asked for a email Address.

Inside the Database the setting is correctly set: `{"publicPollEmail":"disabled"}`.

**Steps to reproduce the behavior**
1. Go to Details => Sharing
2. Click on `+` to create a poll
3. Click on `...` of the new poll
3. Click on `Do not ask for email address` to enable it
4. Access public share link to review if you will be asked for an email

**Add a screenshot of the misbehavior**

None

## How should it work?
**What you expected to happen?**

The wanted behavior is that you will not at all be asked for a email address when the setting is enabled.

## Information about your polls installation
**Polls version:** 3.4.0

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: 3.1.0 ?

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.3

<details>
<summary>List of activated apps</summary>
Currently not Relevant. Can be provided when asked.
</details>
<details>
<summary>Nextcloud Configuration</summary>
Currently not Relevant. Can be provided when asked.
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [x] Other (add name and version): Percona Server (MySQL) 8.0.26

**PHP version:**
- [x] 7.3 or lower
- [ ] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Device:**
- [x] PC
- [ ] Mac
- [x] Mobile phone
- [ ] Tablet

**Browser:**

- [ ] Firefox version:
- [x] Chrome version: 96.0.4664.93
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>
Currently not Relevant. Can be provided when asked.
</details>

<details>
<summary>Browser console log</summary>
None will be generated
</details>

<details>
<summary>Other browser logs</summary>
curl 'https://cloud.example.com/apps/polls/share/8yyaNf6vScoWNkQo/publicpollemail/disabled' \
  -X 'PUT' \
  -H 'authority: cloud.example.com' \
  -H 'content-length: 0' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'requesttoken: <REMOVED> \
  -H 'dnt: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'origin: https://cloud.example.com' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: en-US,de;q=0.9' \
  -H 'cookie: oc_sessionPassphrase=<REMOVED>; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=<REMOVED>; nc_token=<REMOVED>; nc_session_id=<REMOVED>' \
  --compressed

{"share":{"id":8,"token":"8yyaNf6vScoWNkQo","type":"public","pollId":4,"userId":"8yyaNf6vScoWNkQo","emailAddress":"","invitationSent":1639212542,"reminderSent":0,"displayName":"","isNoUser":true,"URL":"https:\/\/cloud.example.com\/apps\/polls\/s\/8yyaNf6vScoWNkQo","showLogin":true,"publicPollEmail":"disabled"}}
</details>

**Comment by dartcafe** [comment]
Thanks. Was a bug, when switching from poll setting to share setting. Should be fixed
