### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#214]
As we have Travis CI running Nc and oC tests now we also need some unit tests at least for the following parts:

- [X] CommentMapper
- [X] DateMapper
- [X] EventMapper
- [X] NotificationMapper
- [X] ParticipationMapper
- [X] ParticipationTextMapper
- [X] TextMapper

**Comment by dartcafe** [comment]
I would like to help, but I have no idea on doing that. If I have a pattern, maybe I can support....

**Comment by splitt3r** [comment]
[Deck](https://github.com/nextcloud/deck/blob/master/tests/unit/Db/AclMapperTest.php) is doing a good job on testing i think. We could start writing CRUD unit tests for our mapper classes.
