### ISSUE TITLE
Polls 3.4.2 - Bugfixes released

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#2141]
## Fixed 
- fix error when adding option  (v3.4.1)
  #2126
- fix missing anonymization of proposal owners in anonymous polls  (v3.4.2)
  #2136
- fix testing of email address constraints for public poll registration (v3.4.2)
  #2137

See reelease notes: https://github.com/nextcloud/polls/releases/tag/v3.4.2
Download ZIP: https://github.com/nextcloud/polls/releases/download/v3.4.2/polls-3.4.2.zip
Download TAR.GZ: https://github.com/nextcloud/polls/releases/download/v3.4.2/polls-3.4.2.tar.gz

**Full Changelog**: https://github.com/nextcloud/polls/compare/v3.4.0...v3.4.2

App store release will follow soon.

**Comment by acsfer** [comment]
Is it normal that poll app takes minutes to complete upgrade?
Any other app takes a few seconds, but polls always take 2-3 minutes to complete the upgrade (trough CLI). 🤔

**Comment by dartcafe** [comment]
This depends on your hardware performance. Polls checks the db integrity on every update, removes indices and recreates them, which takes some time. Here it takes something about 10 seconds.

**Comment by acsfer** [comment]
Thanks, well i believe my hardware is pretty capable (AMD's EPYC™ 7502P, with its 32 cores and simultaneous multi-threading)

As i said, any app but Pools takes seconds. Where can i find those logs and every step so i can debug further?

**Comment by dartcafe** [comment]
In the server log upon updating. The log entries are info level and reported by the updater app.
The are reported via the CLI as well: 
```
2021-12-16T07:03:10+00:00 Repair step: Polls - Remove indices and foreign key constraints
2021-12-16T07:03:20+00:00 Repair step: Polls - Delete duplicates and orphaned records
2021-12-16T07:03:20+00:00 Repair step: Polls - Create indices and foreign key constraints
2021-12-16T07:03:22+00:00 Repair info: Polls - Indices created.
2021-12-16T07:03:23+00:00 Repair info: Polls - Foreign key contraints created.
```
