### ISSUE TITLE
Improvement of the evaluation possibilities

### ISSUE THREAD

**Issue by stepka0815** [nextcloud/polls#2145]
Unfortunately, the last polls update(s) changed the order in which participants are listed in the poll - now in the order in which they participate in the poll, previously in the order of their login names. This now makes it **very** cumbersome to evaluate the poll by a group/team affiliation of participants. We had previously accomplished this by using a prefix with the login names.
Of course, it would be even better if the survey results could be presented on a group basis.

**Comment by dartcafe** [comment]
The polls app never took care of the participants order, except the current user is always put on top. So the order never got changed and was always in the order, they are stored in the database. 

Grouping in any way is not planned will probably never be developed. Sorry.

If you want to request a feature, please use the issue form. Thanks
