### ISSUE TITLE
Public poll, cancel popup can modify poll

### ISSUE THREAD

**Issue by feydreva** [nextcloud/polls#2147]
## What is going wrong? What did you observe?
After creating a poll, using the public link, for public participation.
you have a pop up asking you for Login on the left, or on the right, Participation Name and/or email.

If you click "Cancel" : 
You cannot Vote.
But you are able to add option to the poll

**Steps to reproduce the behavior**
1. Public link of the poll
2. you have the pop up
3. Click Cancel
4. you cannot vote (Normal Behavior) but you can add option (Not normal)

## How should it work?
If you click cancel, you should not be able to interact at all with the poll.
no voting, and no adding suggestion

## Information about your polls installation
**Polls version:** 3.4.2 (Docker nextcloud installation)

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [ x] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x ] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.3

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - encryption: 2.10.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - group_default_quota: 0.1.3
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.2.1
  - password_policy: 1.12.0
  - polls: 3.4.2
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.1.0
  - registration: 1.4.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - end_to_end_encryption
  - files_automatedtagging
  - files_external
  - photos
  - sharepermissions
  - user_ldap

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nuage.paradize.io",
            "nuage.randome.camp",
            "65.108.54.140"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "http:\/\/nuage.paradize.io",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "auth.bruteforce.protection.enabled": false,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR",
        "onlyoffice": {
            "DocumentServerUrl": "\/onlyoffice-document-server\/",
            "DocumentServerInternalUrl": "http:\/\/nextcloud-onlyoffice-document-server\/",
            "StorageUrl": "https:\/\/nuage.paradize.io\/"
        },
        "mail_smtpport": "587",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "app_install_overwrite": [
            "groupfolders"
        ]
    }
}

</details>

### Client configuration
**Device:** 
- [x ] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ x] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

**Comment by dartcafe** [comment]
🙈
