### ISSUE TITLE
PollItem date fields (created, closing date) follow Locale instead of Language

### ISSUE THREAD

**Issue by nicorikken** [nextcloud/polls#2156]
## What is going wrong? What did you observe?
I noticed that the dates in the Poll app match locale rather than language.
In my case I have set my Nextcloud settings with language to English (US) and locale to Dutch (Netherlands).

In the `PollList` kind of views the 'Created' and 'Closing date' entries are shown in Dutch rather than English. To show the difference:

**English (US) language, English (United States) locale:**
![image](https://user-images.githubusercontent.com/7458098/147729207-1fbdb163-a551-4237-9552-f63c2641b17a.png)

**English (US) language, Dutch (Nederlands) locale:**
![image](https://user-images.githubusercontent.com/7458098/147729177-6ea77cf1-e851-4274-b4fd-814a66203eae.png)

Looking at the code, it seems that the `@nextcloud/moment` library is producing a result based on Locale rather than Language:

https://github.com/nextcloud/polls/blob/0183f32c784db0d79e68aa937ec28a1afcab893c/src/js/components/PollList/PollItem.vue#L164-L170
https://github.com/nextcloud/polls/blob/0183f32c784db0d79e68aa937ec28a1afcab893c/src/js/components/PollList/PollItem.vue#L188-L190

I'm not sure if Moment.js can be instructed to respect Language rather than Locale.

**Steps to reproduce the behavior**
1. Go to 'Polls'
2. Configure a Locale different than the language
3. Click on 'All polls (or any other)'
4. See that the date fields have changed language, despite language staying the same.

**Add a screenshot of the misbehavior**

See above.

## How should it work?

As these are relative time measurements, I don't think there is a real need for a locale, and so a language specific result is sufficient.

## Information about your polls installation
**Polls version:** (see apps page) --> As I'm not the admin, I cannot see it, but I guess a recent one as the instance is updated regularly. Perhaps this can be displayed somewhere in the app as well if users report bugs?

**Fresh installation or update from a prior version (from which one)?**
Don't know, and I don't think it is relevant enough to ask.

**How did you install this version?(Appstore or describe installation)**
Don't know, and I don't think it is relevant enough to ask.

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.3.

### Server configuration (decide, if you think it is helpful)
Don't know, and I don't think it is relevant enough to ask.

### Client configuration
**Device:** 
- [X] PC (Linux 🐧) 
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [X] Firefox version: 95.0.1 (64-bit)
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Don't know, and I don't think it is relevant enough to ask.
```
</details>

<details>
<summary>Browser console log</summary>

```
Nothing relevant is printed in the console
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
yep. see #1887
