### ISSUE TITLE
French translation issues, but text in fr.js seems translated already.

### ISSUE THREAD

**Issue by angerized** [nextcloud/polls#2168]
Hello,

Some strings do still appear in english in Polls on Nextcloud 21.0.7 in FR locale (App in version 3.4.2), eventhough they seem translated already.

They are labeled with the red 1 / 2 / 3 in the capture below.

There is also a repeated "dans" ("in") in the poll ending date, there should be only one (green 4).

![image](https://user-images.githubusercontent.com/24433153/148085791-d905a224-2fca-448c-8ebe-9439d6c7ef5e.png)

Kind regards.

**Comment by angerized** [comment]
I found additional translations missing:

In automatic reminders:
![image](https://user-images.githubusercontent.com/24433153/148090629-1cb17420-6687-440e-a433-c082ead76c68.png)

Upon creating a poll:
![image](https://user-images.githubusercontent.com/24433153/148090745-e7683a10-c50e-4698-83a5-ef23d04c1d8b.png)

While sharing:
![image](https://user-images.githubusercontent.com/24433153/148090905-a61ac0fc-c19c-4ade-b9a5-8e0ca3b29999.png)

**Comment by dartcafe** [comment]
This is because, some translations from transifex are delayed and reach the repo after a release. Should be done with the next release.

**Comment by dartcafe** [comment]
And any supporter is welcome to https://www.transifex.com/ to help translating.
