### ISSUE TITLE
When creating a survey, it is not possible to publish it.

### ISSUE THREAD

**Issue by alfredomuchacho** [nextcloud/polls#2179]
When creating a survey, it is not possible to publish it. The "Share" tab remains empty.

Nextcloud Hub II (23.0.0)

![2022-01-10_19-29](https://user-images.githubusercontent.com/97470836/148819415-3b854d67-92ac-434e-90e2-67c9c1ceb820.png)

**Comment by Lesstat** [comment]
I have the very same problem. Downgrading to version 3.4.1 brings the sharing options back. So the bug must be in the new version.

Is there any more info I can provide to help pinpoint this?

**Comment by alfredomuchacho** [comment]
The error occurs only since version 3.4.2. It occurs with both Nextcloud 23.0.0 and version 22.2.0. (The Nextcloud of our club) The same behavior: I create a survey, configure the options and the "Share" tab remains empty.

I don't know how to downgrade to version 3.4.1. :-(

**Comment by dartcafe** [comment]
Sorry, this is not meant personal, but why do you skip the bug form? There is a reason, why it is forced. We need informations to be able reproduce the issues. Otherwise debugging is just guessing.

Just a guess: Disable the adBlocker.

**Comment by alfredomuchacho** [comment]
I must apologize if I have been annoying. But maybe it is possible to give a hint in the descriptions that the adblocker can cause such difficulties. Then at least my message would not be completely in vain.
Thanks to dartcafe for the crucial hint.

**Comment by dartcafe** [comment]
> I must apologize if I have been annoying.

lol. You haven't been annoying, don't care. As i said, don't take it personal, but when starting an issue, the issue descriptions is prefilled with a kind of form which can help to accelarate analysing of problem. 

Of course, we could add hints, but
1) users of plugins which manipulate the content of websites have to be prepared to issues, 
2) this could be a long list or warnings for a lot of plugins or environments and
3) users usually don't read such hints, as well as they skip issue forms. ;-)

Nothing is in vain, I am happy for every problem solved.
