### ISSUE TITLE
Return status code 401 instead of 409 for invalid tokens

### ISSUE THREAD

**Issue by ncdrift** [nextcloud/polls#2187]
## What is going wrong? What did you observe?

If you create an external poll for people without an account, and then make a modified vote POST (changing token and possibly other fields in the request) you will get a 409 Conflict response from the webserver which include a detailed SQL-error message. This should be a generic error message as to not leak unneccessary information

> POST /index.php/apps/polls/check/username HTTP/1.1 
> Host: xxx 
> <REMOVED> 
> { 
> "userName":"testname", 
> "token":"testtoken" 
> } 

> HTTP/1.1 409 Conflict 
> <REMOVED> 
> {"message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*polls_share` WHERE `token` = :dcValue1\"; "} 
> 
> ## Information about your polls installation

**Polls version:** 2.0.6

**Comment by dartcafe** [comment]
Poll version 2.0.6? Shure?

**Comment by dartcafe** [comment]
Besides the fact, that the version isn't supported anymore, there seems to be no change to the current version; What exactly gets leaked? The error message you quoted leaks no sensible information.

**Comment by ncdrift** [comment]
@dartcafe We are running Nextcloud 20.0.14 and Polls 2.0.6 seems to be the latest version for that version of Nextcloud.

**Comment by dartcafe** [comment]
Ah. OK. Regarding the issue: In this case the error message should be an `unauthorized`, but there are no sensible informations leaked. The database structure is no secret.

**Comment by ncdrift** [comment]
@dartcafe 
Could you please update Polls so send the error message as "unauthorized" instead?

We realize you could go to github and get the database structure, but we would like it to not be exposed in our environment unneccessarily.

**Comment by dartcafe** [comment]
I can, but this has no priority and not in the 2.x versions.
