### ISSUE TITLE
Calender conflict rules

### ISSUE THREAD

**Issue by loelkes** [nextcloud/polls#2188]
## What is going wrong? What did you observe?

The poll app shows calendar conflicts if events are "next to" each other.

**Steps to reproduce the behavior**

1. Create a calendar event for a given day from 15:00 to 16:00.
2. Create a date poll and add a date option for the same day going from 16:00 to 17:00.
3. The poll shows a conflict even though there isn't.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/231909/149506327-385160cc-8854-45b3-9365-c7fdd7eedc82.png">

## How should it work?
**What you expected to happen?**

No conflict if events are not overlapping or a setting to specify a certain margin (e.g. 30min) between events to apply for a conflict check. If one event ends at 16:00 and another one starts at 16:00 (as a user) would see them as overlapping.

## Information about your polls installation
**Polls version: 3.4.2**

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: ?

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version: 23.0.0** 
**Calendar version: 3.0.4**

**Comment by dartcafe** [comment]
If I understand you right, you vote for a configurable tolerance span?
Currently it is set one hour before and after the event, if it does not overlap.

**Comment by loelkes** [comment]
I suggest one of the following solutions, in order of preference:
1. Get rid of the one our tolerance span and/or make it adjustable. No need for a GUI, I think at first this can be done site wide through occ command or config file setting.
2. Change the wording to "Possible conflict".

Second solution could be done quickly while waiting for the conflict recgnition to be solved.

**Comment by dartcafe** [comment]
1. The tolerance span is important, so it will not be removed. Configuring is possible
2. Possible conflict will cause layout problems, so it is no quick solution.

I will wait for a complete solution, either with solving the referenced core bug or I will be able to find another fix for that.

**Comment by loelkes** [comment]
Can you explain or give some context why the span is important? 

https://github.com/nextcloud/polls/blob/29d882e37428e4b13bc5d4ce8700743899ab082d/lib/Controller/OptionController.php#L144-L147

**Comment by dartcafe** [comment]
Because I need some time between appointments, i.e. to get from location A to location B.
