### ISSUE TITLE
Cannot restrict access to users in shared groups or invitation by email

### ISSUE THREAD

**Issue by ncdrift** [nextcloud/polls#2189]
## What is going wrong? What did you observe?
**Describe the bug**

It is possible to share Polls with user in the same Nextcloud environment despite that they are not in shared groups.

Like:
User A is a member of **group1**
User B is a member of **group2**

User A can do a search and get a lookup for user B which is not possible in Nextcloud Files or Calender etc because they are not members of a shared group.

## Information about your polls installation
**Polls version:** 2.0.6

## Information about your Instance of Nextcloud
**Nextcloud version:** 20.0.14

**Comment by dartcafe** [comment]
See #658, solved in version 3.2
