### ISSUE TITLE
Authors update

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/polls#219]
@dartcafe @splitt3r 
You both did an awesome job with 0.8.0. But I get all the _fame_. I didn't want to add you to the `<authors>` in `info.xml` without asking. So please feel free to open a PR with your names added :)

**Comment by splitt3r** [comment]
Thx 😄 will add it to https://github.com/splitt3r/polls/tree/unit-tests once it´s working

**Comment by dartcafe** [comment]
You do not only get all the fame, you get also all the complains. 😆 
It's OK to add me. Take nextcloud at dartcafe.de as mail address.  😊

**Comment by v1r0x** [comment]
@dartcafe And you fix most of them :wink:

**Comment by dartcafe** [comment]
Cool, he? If you consider, that I am no programmer. 🥇 😆

**Comment by splitt3r** [comment]
@dartcafe added you [here](https://github.com/nextcloud/polls/pull/224/commits/b4a4fe60069981ccd283c7760dd12a3e85b65651) so we won´t have a merge conflict 😁
