### ISSUE TITLE
BadFunctionCallException "userEmail is not a valid attribute

### ISSUE THREAD

**Issue by burnstreet** [nextcloud/polls#2199]
On NC  22.2.3, Polls 3.4.2, I cannot create polls, I don't see the add new poll button.
Creating polls is not disabled, I am server admin.

In the log, I see the following exception:
`{
    "reqId": "------",
    "level": 3,
    "time": "2022-01-20T21:22:26+01:00",
    "remoteAddr": "------",
    "user": "----",
    "app": "index",
    "method": "GET",
    "url": "/apps/polls/polls?time=1642710146792",
    "message": "userEmail is not a valid attribute",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "version": "22.2.3.0",
    "exception": {
        "Exception": "BadFunctionCallException",
        "Message": "userEmail is not a valid attribute",
        "Code": 0,
        "Trace": [
            {
                "file": "/usr/share/nginx/nextcloud/lib/public/AppFramework/Db/Entity.php",
                "line": 158,
                "function": "setter",
                "class": "OCP\\AppFramework\\Db\\Entity",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/public/AppFramework/Db/Entity.php",
                "line": 73,
                "function": "__call",
                "class": "OCP\\AppFramework\\Db\\Entity",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
                "line": 320,
                "function": "fromRow",
                "class": "OCP\\AppFramework\\Db\\Entity",
                "type": "::"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
                "line": 339,
                "function": "mapRowToEntity",
                "class": "OCP\\AppFramework\\Db\\QBMapper",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Db/ShareMapper.php",
                "line": 73,
                "function": "findEntities",
                "class": "OCP\\AppFramework\\Db\\QBMapper",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 371,
                "function": "findByPoll",
                "class": "OCA\\Polls\\Db\\ShareMapper",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 293,
                "function": "getIsDelegatedAdmin",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 193,
                "function": "getHasAdminAccess",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 170,
                "function": "getIsAllowed",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 238,
                "function": "getIsAllowed",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Model/Acl.php",
                "line": 126,
                "function": "request",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Service/PollService.php",
                "line": 102,
                "function": "setPollId",
                "class": "OCA\\Polls\\Model\\Acl",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Controller/PollController.php",
                "line": 77,
                "function": "list",
                "class": "OCA\\Polls\\Service\\PollService",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Controller/ResponseHandle.php",
                "line": 42,
                "function": "OCA\\Polls\\Controller\\{closure}",
                "class": "OCA\\Polls\\Controller\\PollController",
                "type": "->",
                "args": [
                    "*** sensitive parameters replaced ***"
                ]
            },
            {
                "file": "/usr/share/nginx/nextcloud/apps/polls/lib/Controller/PollController.php",
                "line": 80,
                "function": "response",
                "class": "OCA\\Polls\\Controller\\PollController",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 217,
                "function": "list",
                "class": "OCA\\Polls\\Controller\\PollController",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 126,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php",
                "line": 156,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/private/Route/Router.php",
                "line": 302,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::"
            },
            {
                "file": "/usr/share/nginx/nextcloud/lib/base.php",
                "line": 1006,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->"
            },
            {
                "file": "/usr/share/nginx/nextcloud/index.php",
                "line": 36,
                "function": "handleRequest",
                "class": "OC",
                "type": "::"
            }
        ],
        "File": "/usr/share/nginx/nextcloud/lib/public/AppFramework/Db/Entity.php",
        "Line": 129,
        "CustomMessage": "--"
    }
}`

**Comment by dartcafe** [comment]
I can only guess: The database is not set up properly

So try to 
* disable polls
* delete all polls related tables
* remove all polls related entries from oc_migration and then 
* enable polls again.

If this does not help please open a new issue and help us to understand by filling out the issue form as good as possible. Thanks
