### ISSUE TITLE
OC Screenshots

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/polls#220]
After I uploaded the package to the oc marketplace, I got a mail that it violates the marketplace guidelines (reference to a cloud storage provider which is not oc... :roll_eyes: ).
@dartcafe Am I right that you have a oc instance running? If so, could you add one screenshot for oc?

**Comment by dartcafe** [comment]
I can make some screenshots, or we just cut out the NC header.

**Comment by splitt3r** [comment]
But it´s not possible to show different screenshots for oC / Nc store isn´t it? The screenshot urls are hardcoded in the info.xml and i think it´s not worth it to add some magic to the Makefile only to adopt the screenshot urls.

**Comment by splitt3r** [comment]
We should also add all the screenshots to the info.xml file.

**Comment by dartcafe** [comment]
#222. I just removed the header.

**Comment by v1r0x** [comment]
Hmm...I'm not happy with removing the NC header just because the OC marketplace has annoying restrictions. I'll check if it is possible to select another screenshot in the marketplace or rather drop OC support than live with their restrictions (I mean restrictions were all other NC users have restrictions too, such as not that cool screenshots). But that's just my opinion. What do you think?

**Comment by dartcafe** [comment]
To have some good screenshots, I have to build up representative polls. Doing it in two instances, is annoing. So removing the header is a acceptable agreement for me, besides the manual work of the CSS files. 

But as @splitt3r mentioned here #178, reworking the mail will cause more doubling. 

On the other hand, the release is usable in OC as well, even if it is not in the OC app store.

**Comment by splitt3r** [comment]
We could create screenshots with some -nc / -oc naming convention and replace the urls in the info.xml file in our Makefile.

One thing i don't like about the screenshots without header is that the theme colours don't match the Nc / oC main colours and so they look out of place in one of the appstores.

**Comment by dartcafe** [comment]
I will think about some database imports for showcases.

**Comment by v1r0x** [comment]
> We could create screenshots with some -nc / -oc naming convention and replace the urls in the info.xml file in our Makefile.

I think that's a good compromise.

**Comment by splitt3r** [comment]
@v1r0x @dartcafe https://github.com/nextcloud/polls/pull/224/commits/b4a4fe60069981ccd283c7760dd12a3e85b65651 gave it a try. What do you think? @dartcafe you would need to update the -oc screenshots.

**Comment by splitt3r** [comment]
![Marketplace](https://storage.marketplace.owncloud.com/screenshots/files_clipboard-599ca56b721c5)

They seem to use the Nc + oC logo + some theming trick. Only people who realy care will notice the differences so i like that solution a lot.

**Comment by splitt3r** [comment]
Solved by #257 ref #259
