### ISSUE TITLE
Sharing tab is empty, nobody has granted access NC22.2.3~ynh1

### ISSUE THREAD

**Issue by mateMathieu** [nextcloud/polls#2209]
## What is going wrong? What did you observe?
The sharing tab is not showing any info, nobody has granted access, setting the group in app configuration did not help.

**Steps to reproduce the behavior**
1. Go to polls app
2. Click on create a new one, it says "Currently no user has access to this poll".
3. click on the sharing tab
4. Nothing is showing up, the whole tab is blank

## How should it work?
We should be able to set access to the users.
Using the app configuration and setting the group limitation to "all_users" anr any other group did not help.

## Information about your polls installation
**Polls version:** 3.4.2

**Fresh installation or update from a prior version (from which one)?**
- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: dunno

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore, automatic update
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.3~ynh1

<details>
<summary>Group folder, App order, Appointment, all other are featured apps</summary>

This is a streamlined nextcloud install instance from Yunohost.

**Comment by dartcafe** [comment]
Disable your adblocker

**Comment by mateMathieu** [comment]
Thank you @dartcafe !
