### ISSUE TITLE
l10n: Text string in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/polls#2211]
The following text strings:
https://github.com/nextcloud/polls/blob/495d25241d83684892e34c4c341e97cbb62a7d34/lib/Provider/SearchProvider.php#L69
https://github.com/nextcloud/polls/blob/495d25241d83684892e34c4c341e97cbb62a7d34/lib/Provider/SearchProvider.php#L88

In Transifex they start with a lowercase letter:

![obraz](https://user-images.githubusercontent.com/47037905/150930891-57068359-4b81-40d7-8a05-437544b24b00.png)

Why are they incompatible with source text strings?

**Comment by Valdnet** [comment]
> Just 'Polls'.

The "Polls" text string that starts with an uppercase letter is taken from elsewhere in the code.

**Comment by dartcafe** [comment]
Eh, yes: 'Polls' is used five times in the PHP source and eight times in the JS code. 
'polls' is not used inside any translation strings. So, I have no idea, where Transifex takes the lower string variant from. Maybe it is just the registered app name.

I don't see an issue here. Or is there something I don't understand?

**Comment by Valdnet** [comment]
> I don't see an issue here. Or is there something I don't understand?

There is no problem with that, but I unify text strings in Transifex.

@rakekniven what do you think?

**Comment by rakekniven** [comment]
We had or have the same issues sometimes at the server repo when not only master/main branch is synced.
I had a look at your branches here but could not find the cause for the "polls" (lowercase "p") appearing at Transifex.

See occurences at Transifex:

<img width="1333" alt="Screenshot 2022-01-26 at 10 38 19" src="https://user-images.githubusercontent.com/2069590/151139562-9473de26-14bf-4523-ab60-b7df05893c71.png">

<img width="1340" alt="Screenshot 2022-01-26 at 10 38 30" src="https://user-images.githubusercontent.com/2069590/151139580-b87ae959-3575-4301-b03d-bde8496a1070.png">

**Comment by dartcafe** [comment]
Cool. I think, I was confused, by the JS translations.
