### ISSUE TITLE
Usernames not checked on public polls

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#223]
### Steps to reproduce
1. Create a public poll
2. Enter the public poll as a not logged in user
3. Choose a valid username and vote / comment

### Expected behaviour
i.e. An error message should appear, that the choosen user name is already in use

### Actual behaviour
The user name is accepted and votes in the name of somebody, who already voted (votes are changed) or in the name of a nextcloud user.

Happens in 0.8.0

**Comment by splitt3r** [comment]
I think we need to throttle the username check somehow otherwise someone could try to figure out user names. Here is an example of sth. like that https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Controller/AccountController.php#L80-L87

**Comment by v1r0x** [comment]
Isn't there a bruteforce protection in NC for users/passwords? Maybe this can be adapted.

**Comment by splitt3r** [comment]
@v1r0x very good point ^^ https://github.com/nextcloud/server/pull/3120 seems to help us with that!

**Comment by joergmschulz** [comment]
Yes, confirmed for 9.0 beta 2: when I enter the username 

karl.kraller

for the anonymous poll, I can pretend I am the real Karl Kraller. The real Karl Kraller will be able to modify this vote lateron.
https://test.elternserver.de/index.php/apps/polls/poll/7ceCzpgSrEuSD59e

**Comment by rreichelt** [comment]
This should actually be considered a data leak. We just experienced the issue, that a user in a public poll entered a valid username by accident (e.g. "tuser") and it was accpeted as said existing user and showed it's full name (e.g. "test user"). The public poll function should not be used in EU until fixed due to privacy regulations.

**Comment by dartcafe** [comment]
Checking against existing usernames in one of the next issues to be solved.

**Comment by dartcafe** [comment]
Will be done in vote page migratiuon to vue.

**Comment by Croydon** [comment]
Is this fixed? Cross-reference to a pull request or commit would be nice
