### ISSUE TITLE
Notifications of new comments

### ISSUE THREAD

**Issue by klausfranken** [nextcloud/polls#2245]
## Describe the goal you'd like to achieve

As a poll participant I would also like to be notified of new comments via email, because maybe the appointment is canceled there or other important info is placed.

## Describe possible solutions
Use the same function to send emails if other users change their vote.

## Additional context
E-Mail should contain the new comments, not only information about the existence of new comments.

**Comment by dartcafe** [comment]
When subscribing to a poll, also new comments will be reported since 3.5.x. 
Currently, the translated string is missing and will be delivered within the next version.

**Comment by kangaroo72** [comment]
@klausfranken @dartcafe 
Should the EMail-Notification work for now??
It's not working for me at least....
Thx for reply, Tom
