### ISSUE TITLE
Polls app generates a complete server error after update from 3.4 to 3.5

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/polls#2247]
Polls app generates a server error after update from 3.4 to 3.5

**I get the message:** 

> Composer detected issues in your platform:
> Your Composer dependencies require a PHP version ">= 7.4.0".
> 
> Internal server error
> The server could not complete the request.
> If this happens again, please send the following technical details to your server administrator.

In the changelog to 3.5 is nowhere mentioned that at least PhP 7.4 must be present

Nextcloud: 22.2.2
Linux 4.15.0-159-generic x86_64
PhP-Version: 7.3.16
mysql 10.4.12

**Comment by dartcafe** [comment]
Yes, Sorry and thanks for reporting. Either downgrade to polls 3.4 or update to php 7.4.
See also #2246

**Comment by osm-frasch** [comment]
@dartcafe > Yes, Sorry and thanks for reporting. Either downgrade to polls 3.4 or update to php 7.4. See also #2246

Thanks for the quick info! We will leave it disabled for now.
Have a nice weekend
