### ISSUE TITLE
[3.5.1] Adding any options to a text poll not possible at all

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#2248]
## What is going wrong? What did you observe?
I can't add any options to a text poll anymore. Each new option gives the error message that this option already exists!

**Steps to reproduce the behavior**
1. Create a new text poll
2. Enter a new option
3. You always get an error message that the option already exists

**Add a screenshot of the misbehavior**

![image](https://user-images.githubusercontent.com/3321655/153588294-49da2b44-2510-4f3d-96fd-26fc38dcc6f2.png)

## How should it work?
You should be able to enter options (otherwise the poll is useless ;-) )

## Information about your polls installation
**Polls version:** (see apps page)

3.5.1

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: 3.4.something

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)

23.0.0

<details>
<summary>List of activated apps</summary>

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - appointments: 1.11.12
  - apporder: 0.14.0
  - bbb: 2.2.0
  - bookmarks: 10.0.3
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.5
  - camerarawpreviews: 0.7.15
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - drawio: 1.0.2
  - extract: 1.3.3
  - facerecognition: 0.9.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_automatedtagging: 1.13.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_fulltextsearch: 23.0.0
  - files_fulltextsearch_tesseract: 22.0.0
  - files_inotify: 0.1.11
  - files_linkeditor: 1.1.8
  - files_pdfviewer: 2.4.0
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - fulltextsearch: 23.0.0
  - fulltextsearch_elasticsearch: 23.0.0
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.1.10
  - metadata: 0.15.0
  - music: 1.5.1
  - news: 17.0.1
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.0
  - notifications: 2.11.1
  - notify_push: 0.3.0
  - oauth2: 1.11.0
  - ocdownloader: 1.8.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.5.1
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - qownnotesapi: 21.12.0
  - quickaccesssorting: 1.1.3
  - quicknotes: 0.7.3
  - quota_warning: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.2
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_email: 2.4.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - talk_matterbridge: 1.23.2
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.0
  - user_status: 1.3.1
  - video_converter: 1.0.4
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflow_pdf_converter: 1.8.0
  - workflow_script: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - audioplayer
  - encryption
  - files_external_dropbox
  - guests
  - ```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->

**Database:**
- [ ] MySql version:
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** <!-- Put an x between the brackets ([x]) or check these boxes after you created the issue -->
- [ ] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** <!-- Add your Browser's version and put an x between the brackets ([x]) or check these boxes after you created the issue -->

- [ ] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
Did this error occur, by the first try to add this option?
Dies a reload show up this option?

**Comment by jacotec** [comment]
@dartcafe Don't be too fast with 3.5.2 ... public links are also not working. I'll raise a new issue

**Comment by dartcafe** [comment]
How I would wish we have more users of the beta versions. ;-)

**Comment by dartcafe** [comment]
If you are regarding to the error on adding proposals, this will be covered too with this fix.

**Comment by jacotec** [comment]
@dartcafe Hmmm ... looks like a browser issue. It is on *that* particular browser on my machine. Maybe some cookie/cache things, not sure. Tried on 3 other machines and it's working here. Strange ...

Sorry for the noise!

**Comment by jacotec** [comment]
> If you are regarding to the error on adding proposals, this will be covered too with this fix.

Nope ... I've manually applied your fix for testing ;-)

**Comment by dartcafe** [comment]
> Sorry for the noise!

No problem. Happy about anyone reporting here.
