### ISSUE TITLE
Allow share to edit poll

### ISSUE THREAD

**Issue by Ludogo** [nextcloud/polls#2249]
## Describe the goal you'd like to achieve
When we use poll into an organization, it would be great that another user / group be able to edit poll

As a user chosen by the poll creator i am able to edit poll

## Describe possible solutions
Add an option to chose group or user that are allowed to eidt poll

**Comment by dartcafe** [comment]
You can add a share and promote the user as an admin. This is only possible for site users. 

![grafik](https://user-images.githubusercontent.com/26707476/153619617-987e0b08-f676-4b31-b99f-19d5377f59ad.png)

**Comment by Ludogo** [comment]
very nice . 
Thank you
