### ISSUE TITLE
If polls app is limited to a group (admin) public link is not working

### ISSUE THREAD

**Issue by MeCias** [nextcloud/polls#225]
Hi,

I just noticed (without investigating it any further) that as soon you limit the app access to a specific group like admin you are not allowed to share a poll publicly. It says the app is not enabled. Not sure whether it is a bug or a feature.

**Comment by v1r0x** [comment]
Definitely a feature! :stuck_out_tongue: 
No, of course that's a bug. There should be another issue with that problem, but I couldn't find it. @dartcafe Any idea which one it is?

**Comment by dartcafe** [comment]
See here: #189 and https://github.com/nextcloud/server/issues/6962
This feature is caused by the core.

**Comment by MeCias** [comment]
Thanks a lot.

**Comment by eneiluj** [comment]
nextcloud/server#6962 is a duplicate of nextcloud/server#5309. Just in case someone wants to follow them. I'm the developer of [PhoneTrack](https://gitlab.com/eneiluj/phonetrack-oc) which is seriously affected by this NC server issue.
