### ISSUE TITLE
Give users the ability to delete their votings

### ISSUE THREAD

**Issue by 42ske** [nextcloud/polls#2250]
## Describe the goal you'd like to achieve
*Describe what (goal) you want to achieve and why (value). Please explain your goal and why this is valuable and **do not** describe the solution you suggest. Try to use the following [user story](https://en.wikipedia.org/wiki/User_story) pattern:*
I want to give users the abilty to delete there voting again, while others have the ability to vote with „yes“ or „no“. „No“ in many cases is a different statement than not participating in a poll/voting. I think this does not be an option which has to be activated by the poll admin but also can be default beaviour when registered users participate on polls.

As a **[poll participant/poll owner/...]**, I want to **[be able to .../ don't want to ...]**, because **[it helps to ... /avoids ...]**.

## Describe possible solutions
*If you have a proposal for a way to get to the goal stated above, describe it here.*
Show the trashbin beside the user name as it is already for admins.

## Additional context
*Add a screenshot or a mockup for your UI suggestion or add more context to understand the reason, why you thing this is a valuable request.*

**Comment by dartcafe** [comment]
I don't see the use case. What is the difference between No and not answering to a closed question? 
Users are able to delete their complete votings in the user menu. 

![grafik](https://user-images.githubusercontent.com/26707476/153619136-b8a2c42c-f7b2-4a57-8bec-5bc28a3bf8a3.png)

**Comment by 42ske** [comment]
It's not about closed polls. It's if you use polls for votings and someone already voted, then realized a mistake and have to speak with others before the voting, therefore has to delete the voting again. In cases like that, there's a difference.

But as you told me, this is already possible. I just overlooked the function. The trashbin which ist shown at the users' names if you are admin of a poll ist much more intuitive. Maybe you can discuss if that change could be an improvement in the future. But for now I'm happy that the missed function is already there. Thank you very much.

**Comment by dartcafe** [comment]
I was talking about a closed question, which you can answer with yes or no. :-) 

And on the other hand: Yes, UX is always a topic. The question is, how can a user be guided to achive his goal without questioning, "where can I do what?"

The UX in polls is not the best, as well as the rest of nextcloud. There are a lot of flaws regading that, but some real UX pros are missing here.

**Comment by dartcafe** [comment]
So, I think we can close this issue then, ok?
