### ISSUE TITLE
Username not displayed by take over a poll

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#2259]
Version: 3.5.2

If I go to **Polls** > **Administration** and **take over** a poll the **username** in the modal window is not displayed:

![image](https://user-images.githubusercontent.com/1473674/153708818-f3383e48-af32-46b2-a819-0e68ad55a9ad.png)

**Comment by dartcafe** [comment]
Translation string fixed in Transifex. Thanks for reporting.
