### ISSUE TITLE
Shares with certein Users or Groups dont work

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#2263]
What is going wrong?

Trying to share a Poll with a certain group or user. Entering the groups or users name gives no results and an Error in the Log (see below).

Some groups and users work fine but I wasnt able to pinpoint a problem, some groups work though users in that group dont.

Polls ist the only App with this behaviour.

Searches for shares in other App (ie files, forms) work as intended with all groups and users

I had the same problem last year which was fixed see #1681
As the error ist different I opted to open a new issue.

Information about your polls installation

Polls version 3.5.2 (see apps page)

Fresh installation or update from a prior version (from which one)?
Update

Nextcloud version: (see Nextcloud admin page)
23.0
Server configuration

PHP version:
7.4
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

Log Entry: 
[index] Fehler: Call to a member function error() on null in file '/xxx/apps/polls/lib/Model/UserGroup/Contact.php' line 92

**Comment by dartcafe** [comment]
Damn. The logger is not loaded, before called.
