### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Peter-Toews** [nextcloud/polls#2265]
## What is going wrong? What did you observe?
**Describe the bug**

Hello, when installing the app Polls via the nextcloud administration I get the following error message:Client error: 'GET https://github.com/nextcloud/polls/releases/download/v3.5.0/polls.tar.gz' resulted in a '404 Not Found' response: Not Found

**Comment by dartcafe** [comment]
@v1r0x 3.5.0 is still offered as an update. Is it possible wo withdraw it from the appstore?
@Peter-Toews We deleted the package to avoid further install errors, but the version seems to be still offered via the appstore. Currently there is no update available for PHP 7.3, see: https://github.com/nextcloud/polls/issues/2246

**Comment by v1r0x** [comment]
I couldn't find an option to delete it...sorry!
But with 3.5.2 available there shoud be an update to 3.5.2 without the need for 3.5.0

**Comment by dartcafe** [comment]
> I couldn't find an option to delete it...sorry!

Umpf. No true... 

> But with 3.5.2 available there shoud be an update to 3.5.2 without the need for 3.5.0

Unfortunately not, because 3.5.2 is PHP >= 7.4. 
3.5.0 is offered as an update to PHP 7.3 installations. 

This means, we create a 3.6 from the 3.4.2 tag and a new 3.7 with the current fixes. This way, we have a clean update path.

**Comment by Peter-Toews** [comment]
Thanks for the information

**Comment by v1r0x** [comment]
Ok, my bad....I found a way. Didn't thought about that it is only possible using the REST api and not directly in the appstore :facepalm: :facepalm: :facepalm:

**Comment by dartcafe** [comment]
@Peter-Toews Can you fonfirm, that the update is no longer offered, since the version was removed from the app store?

**Comment by Peter-Toews** [comment]
Thank you, I can confirm that version 3.4.2 is offered and that it works. The update to 3.5.0 is no longer available.
