### ISSUE TITLE
None existing poll leads to server error

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#227]
### Steps to reproduce
1. Create a public poll an copy the link
2. Delete the poll
3. Visit the link

For example: https://nc13.yagst.de/index.php/apps/polls/poll/b8oIJNNjpx7Rkyei

### Expected behaviour
Sth. like: https://github.com/nextcloud/gallery/blob/669c17b4e3a9ffbb2901d78378db3f7702a0cc06/lib/Controller/PageController.php#L131-L156 a nice 404 error page

![Gallery error page](https://user-images.githubusercontent.com/1869584/32143686-93f9f650-bcad-11e7-97d6-a9e0341c4cfd.png)

### Actual behaviour
Internal server error

![Internal server error](https://user-images.githubusercontent.com/1869584/32143860-89708fc0-bcb0-11e7-9105-e4dddd08a5cf.png)

**Comment by splitt3r** [comment]
@v1r0x could you take care of this one? I think this should be a hotfix once it´s done. I have very rare time at the moment.

**Comment by v1r0x** [comment]
@splitt3r I try to find some time for polls this weekend, but can't promise anything.

**Comment by dartcafe** [comment]
Redirecting to `no.acc.tmpl.php` should be enough.
