### ISSUE TITLE
text not translated - Although participant's names are hidden, this is not ...

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/polls#2270]
I use Nextcloud in german.
The most texts in polls are translated. But not this text:

"Although participant's names are hidden, this is not a real anonymous poll because they are not hidden from the owner. Additionally the owner can remove the anonymous flag at any time, which will reveal the participant's names."

**Comment by dartcafe** [comment]
Thanks. Was an error in the translation function, with an invalid app name. 
Fixed in directly to master in https://github.com/nextcloud/polls/commit/a7d7e0e47265d845255357f91dc750e0ba3eb776
