### ISSUE TITLE
add option to not need to enter a name / fake name

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/polls#2271]
Hallo,

i want to use polls for anonymous polls. Sometimes i do not need fake user names.
Perhaps you can implement an option. 

Or is there an option.
I use anonymous polls but polls forces me to insert a fake user name.

**Comment by devnull4242** [comment]
Perhaps it could be possible to use pseudo user like the name of public shares e.g. s/MkqJoTAFzpgb99s
username: **MkqJoTAFzpgb99s** 

Two possibilities:
a.) the username MkqJoTAFzpgb99s is only listed in admin view of polls.
b.) the username in polls in user view is prefilled with MkqJoTAFzpgb99s and can be changed.

This feature would be nice for more anonymous polls. Thanks.

**Comment by dartcafe** [comment]
There are a lot of solutions possible, but as I said:

> rather expensive compared to the value

**Comment by devnull4242** [comment]
Yes. But have you ever used e.g. https://www.strawpoll.me ?
I think it would be cool to have an easy poll tool for the user.
And it is not easy and useful on anonymous polls to insert an username.

**Comment by dartcafe** [comment]
I think there may be reasons for huge enhancements, but I can only repeat myself: This will be a lot of work with a limited value. 

You can try to proper fill out the [request form](https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=feature_request.md) which you obviously deleted, when you created this issue. There is a reason, why we ask to fill this out. 

Try to express your request in form of a user story as explaned in the form and maybe the value and use case is better understandable.
