### ISSUE TITLE
Error when deleting a LDAP user using the occ

### ISSUE THREAD

**Issue by provelo-ict** [nextcloud/polls#2276]
## What is going wrong? What did you observe?

I deleted a LDAP user using occ, I got go an error that seems to originate in the Polls app.
(That's the reason why I created this issue here and not in [](https://github.com/nextcloud/server)

Here is the full log of the error:

```
root@myserver:~# sudo -u www-data php8.0 /var/www/occ user:delete j.doe
An unhandled exception has been thrown:
Error: Call to undefined method OCP\User\Events\UserDeletedEvent::getLogId() in /var/www/apps/polls/lib/Listener/BaseListener.php:137
Stack trace:
#0 /var/www/apps/polls/lib/Listener/BaseListener.php(84): OCA\Polls\Listener\BaseListener->addLog()
#1 /var/www/lib/private/EventDispatcher/ServiceEventListener.php(75): OCA\Polls\Listener\BaseListener->handle()
#2 /var/www/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke()
#3 /var/www//3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#4 /var/www/lib/private/EventDispatcher/EventDispatcher.php(88): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#5 /var/www/lib/private/EventDispatcher/EventDispatcher.php(100): OC\EventDispatcher\EventDispatcher->dispatch()
#6 /var/www/lib/private/User/User.php(301): OC\EventDispatcher\EventDispatcher->dispatchTyped()
#7 /var/www/core/Command/User/Delete.php(63): OC\User\User->delete()
#8 /var/www/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\User\Delete->execute()
#9 /var/www/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#13 /var/www/console.php(99): OC\Console\Application->run()
#14 /var/www/occ(11): require_once('...')

```

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Launch the command occ user:delete <name-of-the-user>
2. See error

## How should it work?

The command should not raise an error.

A clear and concise description of

## Information about your polls installation
**Polls version:** 
5.2

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version:
  Unknown

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version: 22.2.5

<details>
<summary>List of activated apps</summary>

  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.6
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - dav: 1.20.0
  - deck: 1.5.5
  - drawio: 1.0.2
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.13.1
  - files_markdown: 2.3.5
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - forms: 2.4.0
  - group_everyone: 0.1.9
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - polls: 3.5.2
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.4
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - sharelisting: 1.0.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.2
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0

</details>
<details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [x] MySql version: 10.3.31
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [X] 8.0

**Comment by dartcafe** [comment]
Thanks for reporting and the relevant information to get this fixed fast. Bugfix will come shortly (3.5.4).

**Comment by dartcafe** [comment]
For manual update: https://github.com/nextcloud/polls/issues/2273

**Comment by provelo-ict** [comment]
Thank you for the quick fix (and for all the work around this app!)
