### ISSUE TITLE
Move list of polls into left .app-navigation, use .app-content exclusively for poll content

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/polls#228]
As mentioned in https://github.com/nextcloud/polls/pull/166#issuecomment-335975706

> This list of polls is what the left app-navigation is made for. :) We don’t really need a complex table to list these polls, it’s unnecessarily confusing. The navigation can have a simple section for Open polls first and Closed polls below, show the icon for if you voted or not, show the sharing indicator for if it’s shared with users or shared via link, and other details can go in the 3-dot menu. :)

> The left app-navigation is for listing the polls, and the app-content is for displaying one poll. :)

> Currently the Polls app has a mode in the content: Either list of polls, or one poll. That is confusing. The Tasks app only ever shows tasks in the content.

> Tasks app uses app-navigation for a list of task lists, Polls would use it for a list of polls. Tasks uses app-navigation for a list of the tasks in the selected list, Polls would use it for a list of the participants and answers in that selected poll. (The poll detail view as we have now already.)

>  For the empty main view at the start we will have the proper .emptycontent view, looking something like

> Polls app icon
> No polls created yet
> [ Start with your first poll ]

> Just as in all other apps, and in empty folders etc. And as @skjnldsv mentioned, when you open the app, the first poll should be loaded. Or rather, the last one you had open.

> What do you think @v1r0x @skjnldsv @splitt3r @dartcafe? The main point is that the two entirely different view modes in the content are very confusing. This is the same issue we have and will fix in the Deck app: nextcloud/deck#12

**Comment by dartcafe** [comment]
I thought over this a lot of times and I am not happy with the navigation bar for the polls list. When there are many polls, the navigation can mutate to a huge list of polls. And there will be missing details for organisation, which can be important. Finding the right poll on a list with details can be more easy, than finding it via the tight list on the left. 

Additionally the app navigation can get overloaded, if there are many polls in the list and then the details are important to find the right poll together with quick filtering.

I believe, that the first poll is not the one, which interests me. Normally a user enters the app to manage the polls or to vote. When he wants to vote, he wants to enter the poll, he is currently affected by. 

I would prefer the app navigation being for filtering and settings. 

possibly interesting filters can be:
- Polls created by me
- open polls
- Polls, in which I voted
- Polls which are expired
- Poll which expire soon
- Archived polls
- ...

**Comment by dartcafe** [comment]
done in https://github.com/nextcloud/polls/tree/dev-1.0

**Comment by skjnldsv** [comment]
:heart:

**Comment by dartcafe** [comment]
Love you too.

**Comment by jancborchardt** [comment]
Ooooh really nice, have to check it out. :)

@dartcafe are you coming to the Nextcloud Conf this weekend? Would be cool to sit together and collaborate a bit on the app!

**Comment by dartcafe** [comment]
Just saw your message. I was busy the last weeks, so I wasn't available.

**Comment by jancborchardt** [comment]
@dartcafe next Contributor Week is in Berlin November 4–8 if you want to come. :) More info at https://nextcloud.com/blog/join-us-in-berlin-for-the-next-nextcloud-hackweek/
