### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by ThibautPlg** [nextcloud/polls#2297]
## Describe the goal you'd like to achieve
As a Nextcloud manager, I want to be able to transfer ownership of one or all polls from an user to another, because I am facing an user turnover and want to keep poll related data when an account is disabled.
## Describe possible solutions
We would like to have access to an occ command or a gui button to transfer ownership from an account to another, like for Files or Calendar.

## Additional context
-

Thanks for your reading. 
I hope that this feature will be implemented, as it would homogenize the behavior of Nextcloud apps and allow for a more professional use of those tools.

**Comment by Letterfl** [comment]
Am I able to *take over* or also delegate them? For example, I am admin of the Nextcloud and I want to hand over a poll to a user as if it belonged to him.

**Comment by dartcafe** [comment]
At the moment it is just possible to take over a poll. This is to avoid orphaned polls, if a user gets removed from the site.

Transferring the ownership is not a feature atm. 

Delegating owner rights can be stablished by the poll owner via a share entry. 
![grafik](https://user-images.githubusercontent.com/26707476/159375321-87c811c3-0936-4a3e-afdb-48aa21110efe.png)

But you need to disable your adblocker first to use that. 😉

**Comment by dartcafe** [comment]
Put it to the backlog. Transferring ownership is a useful feature.
