### ISSUE TITLE
eMail addresses of poll participants in export files

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#2298]
## Describe the goal you'd like to achieve

I'm using date polls for participant registration to webinars, the date with the most votes will be realized. In the mailing is a link to the poll and a vote is a registration as well.

Now I want to send an email to the registered people ... and unfortunately the only way to get the email addresses is to copy these small, tiny mail addresses in "Sharing" one by one from the web browser.

The email addresses of participants should be also exported in a column next to the name in the CSV and Spreadsheet exports which can be done in the vote app.

## Describe possible solutions
Adding the email addresses as a new column right from the names in the export functions

**Comment by dartcafe** [comment]
see #2177
