### ISSUE TITLE
How owner can view email address on anonymous poll?

### ISSUE THREAD

**Issue by danjde** [nextcloud/polls#2303]
Hi Devs,
using Polls 2.0.6 owner can obtain (manually too) emails of each voters user on anonymous poll?

Many thanks!

davide

**Comment by danjde** [comment]
For an anonymous poll I would like to obtain the results, related to each user (not only overall), and for each user to have the relevant email address and any name with which he was signed.

Is it possible, without going from the database?

thanks

**Comment by danjde** [comment]
I've found, need to point poll to "table view" and then appear three vertical dots where is possible copy (and paste) all emails associated with names.
Not so easy, although for me.

**Comment by dartcafe** [comment]
So wanted to copy all email adresses of all participants? 

Maybe you should update to a more recent version of polls, where you are able to copy all addresses of all participants from the user's menu.

![grafik](https://user-images.githubusercontent.com/26707476/158054276-4ef6decc-d54c-4473-8145-2a3ad29deb69.png)

**Comment by danjde** [comment]
Well, thanks!!

davide
