### ISSUE TITLE
German translation is missing of button "Change date"

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/polls#2313]
## What is going wrong? What did you observe?
German translation is missing for the button "Change date"

**Steps to reproduce the behavior**
1. Login to a nextcloud installation as a user with language 'german' set
2. Add a new poll (any title, date poll) 
3. Add a date
4. Add a time
5. The button "change date" is not translated

![Bildschirmfoto_2022-03-15_13-14-03](https://user-images.githubusercontent.com/100593683/158376676-8f3c26ff-60c2-4d65-9a5f-50bfd96d38b8.png)

## How should it work?
The button "change date" should be translated to "Zeit ändern'

## Information about your polls installation
**Polls version:** 3.5.4

**Fresh installation or update from a prior version (from which one)?** 
- [x] First time install

**How did you install this version?(Appstore or describe installation)**
- [x ] Installed from the appstore

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.5

**Comment by dartcafe** [comment]
Thanks, I first thought the translation was late. But oviously this was a bug in the string selection of the translation. Thanks for reporting.
