### ISSUE TITLE
Usability issue: "Grant access" button

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/polls#2315]
## What is going wrong? What did you observe?

**Describe the bug**

We got feedback of our users, who expect that the "grant access" button should already activate the poll (instead of opening the sharing menu). At least it is unclear for users that they have to click e.g. on the "all users" button. 

(Issue is related to issue #2314) 

**Steps to reproduce the behavior**
1. create new poll (date) with time slots
2. Click on 'Grant access' Button

## How should it work?

According to our user feedback the click on "Grant Access" should directly trigger the slider and grant access to all users 

## Information about your polls installation
**Polls version:** 3.5.4

**Fresh installation or update from a prior version (from which one)?**
- [x ] First time install

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore

## Information about your Instance of Nextcloud
**Nextcloud version:** 22.2.5

**Comment by dartcafe** [comment]
Thanks. Got the UX issue. But it could also be surprisingly for a user, if the button grants access for all users, if he just wants to create a private poll with selected sharees. 

Anyways, the button is quite ugly. 

I think a better aproach would be something like #2241

**Comment by dartcafe** [comment]
SInce the (ugly) button got removed in the upcomming version, I will close this issue is vavor of #2241. I hope, this will support the poll creation better than just referring to the sidebar.
