### ISSUE TITLE
[Discussion] Remove the status "unvoted"

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#232]
IMHO the status "unvoted" is obsolete, because it has no message in the sense of a poll. Either you say "yes" or "no". The status "maybe" is a compromise, which means yes, but with a lower priority. 

What is unvoted good for? As an owner of a poll, I want to have a concrete answer for my question and no I will maybe decide later. 

What do you think?

**Comment by v1r0x** [comment]
Is it actually used at all? Or is it simply the default for new voters?
I'd suggest to switch to _maybe_ as default (same as dudle) and remove _unvoted_ if not used.

**Comment by dartcafe** [comment]
It's the default and has no further meaning, besides the message, that the user did not decide. 

Default to 'maybe' is no good solution in my opinion, because the user did't explicitly says yes to the option, he didn't vote. So I would interprate it as a 'no', because maybe means 'yes, but...'

So I would change the default to 'no'.

**Comment by v1r0x** [comment]
IMO it is not always 'yes, but...' or it's a very broad definition of 'but...' 😉 
Also the user didn't explicitly said no to an option. Beside that their votes are only stored if the click on the vote button. So they always have to check each checkbox.

I prefer a neutral default aka 'maybe'

**Comment by dartcafe** [comment]
I was just judging from comments regarding the 'maybe' it is interprated as 'yes, but...' or 'OK, if no other date fits, I'll be in' or similar. 

Beeing undecided is never good for a clear decision's fundament, so IMHO I would eliminate the 'maybe'. But if the users want this option, I will not argue against it. 

But the question has to be, what a creator of a poll mant's to achieve. He asks something and gets a bunch of maybes, because users just click one option, because they say 'yes, that fits'. For the rest, he has to speculate, if he just didn't click, or if he says, this option is 'OK, but...' or whatever is to interprate into this behavior.

A default of 'no' signals clear, that if the user does not click, he says 'no'. There ist no room for interpration. 

Like in real life: When I ask my wife, if the companies me and she gives no answer, it's a NO and no 'maybe' and less a 'yes'. 

BTW: I took a peek to doodle: A poll starts with an empty checkbox, which means 'no'! Like dudle does it as well.

**Comment by v1r0x** [comment]
You're right. Dudle defaults to _No_ as well. Thought it was _Maybe_. Then I'm ok with doing the same as the "major" poll apps :)

**Comment by dartcafe** [comment]
Done in #226
