### ISSUE TITLE
A too long title breaks the "export data" function

### ISSUE THREAD

**Issue by r-hmn** [nextcloud/polls#2320]
**Observation**
When i create a text poll with a short name, at any stage i can select the "Download" (as csv, html,excel etc)
For a report with a title with this length: "12345678901234567890123456789012" 
the "download data" buttons stop working. One character less, and the exporting works again.

**Steps to reproduce the behavior**
1. Go to polls
2. Create a text based poll
3. type in a plain name e.g. "new poll"
4. click the down arraw and press 'download as csv'. A  "save as" window appears as it should. cancel this window.
5. add a unicode character to the title. e.g. 👩‍🌾 or a double quote " character.
6. click the down arraw and press 'download as csv'. Nothing happens. this is wrong. it should be same as point 4.

**Environment**
Nextcloud AIO Beta v0.8.0 (nextcloud 23.0.2)
Polls	3.5.4
Browsers: Chromium, Brave, Edge

**Comment by r-hmn** [comment]
ahh This issue is closed, and merged 22 days ago
https://github.com/nextcloud/polls/issues/2285

**Comment by dartcafe** [comment]
No problem.
