### ISSUE TITLE
Share menu doesn´t show anything / remain empty

### ISSUE THREAD

**Issue by Letterfl** [nextcloud/polls#2322]
[bug report polls CLEAN.txt](https://github.com/nextcloud/polls/files/8319356/bug.report.polls.CLEAN.txt)

### Steps to reproduce
Open an poll
click on share or publish
look at an empty palette

### Expected behaviour
the share menu shows public links and delegation to other users

### Actual behaviour
the share - sidebar remain empty, even when triggering via publish/grant access
https://user-images.githubusercontent.com/37409675/159246200-a5f83a2a-d9aa-452b-83ce-b43aa300c2ee.png

## Server configuration detail

**Operating system:** Linux 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64

**Webserver:** Apache/2.4.51 (Unix) (fpm-fcgi)

**Database:** mysql 10.3.32 and phpMyAdmin 

**PHP version:** 

7.4.24
Modules loaded: Core, date, libxml, pcre, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, bz2, curl, exif, ftp, gd, gettext, gmp, iconv, imagick, intl, mailparse, mysqli, openssl, pdo_mysql, posix, soap, sockets, sodium, xmlrpc, zip, zlib, Zend OPcache

**Nextcloud version:** 23.0.2 - 23.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** based on guides how to install nextcloud hub on a synology NAS (DS420+)

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - bruteforcesettings: 2.3.0
 - cloud_federation_api: 1.6.0
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - polls: 3.5.4
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - registration: 1.4.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - support: 1.6.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - updatenotification: 1.13.0
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - welcome: 1.0.1
 - workflowengine: 2.5.0
Disabled:
 - activity
 - admin_audit
 - circles
 - comments
 - encryption
 - files_external
 - files_videoplayer
 - firstrunwizard
 - nextcloud_announcements
 - photos
 - recommendations
 - user_ldap
 - user_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***.goip.de",
        "***.synology.me",
        "**IP**"
    ],
    "0": [
        "192.168.188.50"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "23.0.2.1",
    "overwrite.cli.url": "https:\/\/***.goip.de\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local (USB Drive)

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4911.0 Safari/537.36 Edg/101.0.1193.0 - Edge Version 101.0.1193.0 (Offizielles Build) dev (64-Bit) 

**Operating system:** WIndows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 

not available due such no terminal in DSM
```
</details>

<details><summary>Nextcloud log</summary>

```

more logs in attached file

**Comment by Letterfl** [comment]
it´s my first ever post / issue report on github, so please feel free to comment things what I need to add or change in the future :D

**Comment by dartcafe** [comment]
Compliments. Challenge perfectly mastered. 😄 

To your issue: Disable your adblocker. 

See #2179, #1452, #1503, #1782

**Comment by Letterfl** [comment]
Uh, well. First of all, thank you. :D I overlooked the other articles after all... 
And frankly interesting that an adblocker prevents these codes....

**Comment by dartcafe** [comment]
Adblockers seem to respond to the keyword share with different variations, depending on the settings and used lists.
