### ISSUE TITLE
Polls Sharing Tab is blank, no way to publish a poll

### ISSUE THREAD

**Issue by tim-tation** [nextcloud/polls#2330]
## What is going wrong? What did you observe?
The complete Sharing Tab in the Polls App is blank, so there is no way to publish a Poll. I updated to the newest version, I deactivated and reactivated the app, I cleared the cash, I tested different browsers, the problem persists. We have several Nextcloud instances running on our server, all of them are up to date and all of them have the same problem.

**Steps to reproduce the behavior**
1. Go to Polls
2. Publish a Poll
3. Click on Sharin Tab or use Grant Access Button
4. Nothing there

<img width="485" alt="Screenshot 2022-03-24 at 11 37 19" src="https://user-images.githubusercontent.com/7450128/159898489-063f99c0-18e2-48f7-ba48-1b7b84f555a4.png">

## How should it work?
Expect the Sharing Tab to have the usual sharing options displayed.

## Information about your polls installation
Checked on Nextcloud Hub II v23.0.2 & v23.0.3

**Fresh installation or update from a prior version (from which one)?**
- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: v23.0.2

**How did you install this version?(Appstore or describe installation)**
- [ ] Installed from the appstore
- [x] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** v23.0.3

<details>
<summary>Nextcloud Configuration</summary>

<?php
$CONFIG = array (
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud.bunte-liste-schwarzenbruck.de',
  ),
  'datadirectory' => '/var/www/vhosts/tim-tation.com/.nextcloud/data/ed6c590811e0',
  'dbtype' => 'mysql',
  'version' => '23.0.3.2',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud_6031eef4',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'instanceid' => 'ocdmw4vetwsd',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'bunte-liste-schwarzenbruck.de',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'bunte-liste-schwarzenbruck.de',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpname' => 'info@bunte-liste-schwarzenbruck.de',
  'mail_smtppassword' => '',
  'default_phone_region' => 'DE',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'updater.secret' => '',
);
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [x] 7.4.26
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [ ] PC
- [x] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: 98.0.1
- [x] Chrome version: 99.0.4844.83
- [x] Safari version: 15.4
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>
{"reqId":"V5SoKxSUSpklNhvTPoqZ","level":3,"time":"2021-02-09T13:15:30+00:00","remoteAddr":"","user":"bls_cloud_admin","app":"no app in context","method":"","url":"--","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve trashManager! Class trashManager does not exist","Code":0,"Trace":[{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":430,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":58,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"function":"OC\\AppFramework\\Bootstrap\\{closure}","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":68,"function":"array_map"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/BootContext.php","line":52,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/files_trashbin/lib/AppInfo/Application.php","line":57,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\Files_Trashbin\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/dav/lib/AppInfo/Application.php","line":113,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_Util.php","line":201,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":554,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":415,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":624,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":367,"function":"loginWithPassword","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/Setup.php","line":436,"function":"login","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/core/Command/Maintenance/Install.php","line":106,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Install","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":1000,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":271,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":147,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/opt/psa/admin/plib/modules/nextcloud/scripts/externals/occ-install.php","line":27,"args":["/var/www/vhosts/tim-tation.com/cloud.bls/console.php"],"function":"require"}],"File":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","Line":115,"CustomMessage":"Could not boot files_trashbinCould not resolve trashManager! Class trashManager does not exist"},"userAgent":"--","version":"20.0.7.1"}
{"reqId":"V5SoKxSUSpklNhvTPoqZ","level":3,"time":"2021-02-09T13:15:30+00:00","remoteAddr":"","user":"bls_cloud_admin","app":"no app in context","method":"","url":"--","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\Files_Versions\\Versions\\IVersionManager! Class can not be instantiated","Code":0,"Trace":[{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":455,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":427,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/files_versions/lib/AppInfo/Application.php","line":119,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/files_versions/lib/AppInfo/Application.php","line":106,"function":"loadBackend","class":"OCA\\Files_Versions\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":68,"function":"registerVersionBackends","class":"OCA\\Files_Versions\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/BootContext.php","line":52,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/files_versions/lib/AppInfo/Application.php","line":91,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\Files_Versions\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/apps/dav/lib/AppInfo/Application.php","line":113,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/legacy/OC_Util.php","line":201,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":554,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":415,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":624,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/User/Session.php","line":367,"function":"loginWithPassword","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/Setup.php","line":436,"function":"login","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/core/Command/Maintenance/Install.php","line":106,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Install","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":1000,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":271,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/3rdparty/symfony/console/Application.php","line":147,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/tim-tation.com/cloud.bls/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/opt/psa/admin/plib/modules/nextcloud/scripts/externals/occ-install.php","line":27,"args":["/var/www/vhosts/tim-tation.com/cloud.bls/console.php"],"function":"require"}],"File":"/var/www/vhosts/tim-tation.com/cloud.bls/lib/private/AppFramework/Utility/SimpleContainer.php","Line":111,"CustomMessage":"Could not boot files_versionsCould not resolve OCA\\Files_Versions\\Versions\\IVersionManager! Class can not be instantiated"},"userAgent":"--","version":"20.0.7.1"}
</details>

**Comment by dartcafe** [comment]
Disable your adblocker. See #2322 and other linked issues there.
