### ISSUE TITLE
Allow creation of polls from a mobile device 

### ISSUE THREAD

**Issue by arandomliz** [nextcloud/polls#2337]
I'd like to be able to create polls, edit them, ... on my mobile device. As of right now even going into desktop mode doesn't show the side bar with which you can manage polls.

The solution could be quite simple by allowing mobile users to open the sidebar using a hamburger menu or similar.

**Comment by arandomliz** [comment]
Nevermind the chrome flag "auto dark mode for web contents" doesn't incert the already existing hamburger menu. Drawing a black icon in front of a black background 🙈
I'm sorry for the inconvenience

**Comment by dartcafe** [comment]
This is not chrom's problem. The hamburger isn't redered properly by the used component. 
See this issue for tracking.
