### ISSUE TITLE
Integrate with calendar

### ISSUE THREAD

**Issue by fab920** [nextcloud/polls#2356]
## Integrate with calendar
Add an option to automatically create a poll one calendar. For each entry in the calendar, an option is added to the poll automatically.

For example, if you manage a sports team, you could create a new calendar for that team. A poll is created automatically for this calender.

Every event that will take place (practice seesion, game, tournament, party...) will be put in the calendar. A new option in the poll will then be created automatically.

The team members now can confirm if they can attend the games.
If events are moved or deleted, the coresponding option is updated.
Events in the past should not be shown / deleted.

**Comment by dartcafe** [comment]
There are a lot of issues addressing the calendar integration. Sometimes it will be done. I can't deliver any doa for this. 
See #121, #411, #400, #1633, #1531
