### ISSUE TITLE
Remove ocsid from info.xml

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#236]
@v1r0x we need to remove the ocsid from our info.xml as it is removed from the validation schema https://apps.nextcloud.com/schema/apps/info.xsd => https://github.com/nextcloud/appstore/blob/master/CHANGELOG.md#added

Perhaps we should also delete https://apps.owncloud.com/content/show.php/Polls?content=174671 ?

**Comment by v1r0x** [comment]
Do you know if ocsid is required by OC?


> Perhaps we should also delete https://apps.owncloud.com/content/show.php/Polls?content=174671 ?

Is this necessary? I'd prefer a deprecated notice and links to the oc and nc app stores.

**Comment by splitt3r** [comment]
I don´t think so. It´s up to you ^^ a notice would also do the job.

**Comment by v1r0x** [comment]
Removed in #233 Let's see if it works with oC :grin:

**Comment by splitt3r** [comment]
The official apps like calendar seem to not have it anymore either.
