### ISSUE TITLE
Export missing

### ISSUE THREAD

**Issue by digital-codes** [nextcloud/polls#2370]
## What is going wrong? What did you observe?
**Describe the bug**

Documentation says there is an export function into several formats
But there is no export button available

**Steps to reproduce the behavior**
Click any buttons "settings, configuration, info, ..." No "export" anywhere

**Add a screenshot of the misbehavior**

## How should it work?
**What you expected to happen?**

A clear and concise description of

## Information about your polls installation
**Polls version:** (see apps page)
3.4.2

**Fresh installation or update from a prior version (from which one)?**
Using polls since 2 years with regular updates

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)

[Nextcloud Hub II](https://cloud.ok-lab-karlsruhe.de/) (23.0.3)

<details>
<summary>List of activated apps</summary>

Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - analytics: 4.2.1
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - documentserver_community: 0.1.12
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_fulltextsearch: 23.0.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - fulltextsearch: 23.0.0
  - groupfolders: 11.1.2
  - impersonate: 1.10.0
  - integration_twitter: 1.0.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.3.2
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.4.2
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - circles: 23.0.1
  - encryption
  - files_external
  - mail: 1.11.7
  - user_ldap

</details>
<details>
<summary>Nextcloud Configuration</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmd50444.contaboserver.net",
            "cloud.ok-lab-karlsruhe.de"
        ],
        "loglevel": 3,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/cloud.ok-lab-karlsruhe.de",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "has_rebuilt_cache": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_sendmailmode": "smtp",
        "theme": "",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "default_phone_region": "DE"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "notify_email_analytics_data": "0",
            "notify_email_analytics_dataset": "0",
            "notify_email_calendar": "1",
            "notify_email_calendar_event": "1",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "0",
            "notify_email_deck": "1",
            "notify_email_deck_card_description": "1",
            "notify_email_deck_comment": "1",
            "notify_email_favorite": "0",
            "notify_email_file_changed": "0",
            "notify_email_file_favorite_changed": "0",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "0",
            "notify_email_shared": "0",
            "notify_email_systemtags": "0",
            "notify_notification_analytics_data": "0",
            "notify_notification_analytics_dataset": "0",
            "notify_notification_calendar": "0",
            "notify_notification_calendar_event": "0",
            "notify_notification_calendar_todo": "0",
            "notify_notification_comments": "0",
            "notify_notification_deck": "0",
            "notify_notification_deck_card_description": "0",
            "notify_notification_deck_comment": "0",
            "notify_notification_favorite": "0",
            "notify_notification_file_changed": "0",
            "notify_notification_file_favorite_changed": "1",
            "notify_notification_group_settings": "1",
            "notify_notification_personal_settings": "0",
            "notify_notification_public_links": "0",
            "notify_notification_remote_share": "0",
            "notify_notification_security": "1",
            "notify_notification_shared": "1",
            "notify_notification_systemtags": "0",
            "notify_setting_batchtime": "0",
            "notify_setting_self": "0",
            "notify_setting_selfemail": "0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "analytics": {
            "enabled": "yes",
            "installed_version": "4.2.1",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "924"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "3.2.2",
            "types": ""
        },
        "carnet": {
            "enabled": "no",
            "installed_version": "0.23.7",
            "types": "filesystem"
        },
        "circles": {
            "enabled": "no",
            "installed_version": "23.0.1",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1645455002,\"2\":1645455303,\"1\":1645455603,\"4\":1645408803,\"5\":1645239717}",
            "migration_22": "1",
            "migration_22_1": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.1.0",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1585344748.6421",
            "lastcron": "1649760602",
            "lastupdateResult": "[]",
            "lastupdatedat": "1649760614",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "b1465ecd89277503f116daac766bc88d",
            "updater.secret.created": "1647941201",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.3.0",
            "types": ""
        },
        "dashboardcharts": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.21.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "groupLimit": "Call4Code,ckan,oklab",
            "installed_version": "1.6.1",
            "types": "dav"
        },
        "documentserver_community": {
            "enabled": "yes",
            "installed_version": "0.1.12",
            "types": "filesystem"
        },
        "dropit": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "encryption": {
            "masterKeyId": "master_aad9e88e",
            "publicShareKeyId": "pubShare_aad9e88e",
            "recoveryKeyId": "recoveryKey_aad9e88e"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "10 GB",
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem"
        },
        "files_fulltextsearch": {
            "enabled": "yes",
            "installed_version": "23.0.0",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "yes",
            "installed_version": "2.3.5",
            "types": ""
        },
        "files_mindmap": {
            "enabled": "no",
            "installed_version": "0.0.25",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.14.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.12.0",
            "types": "logging"
        },
        "fulltextsearch": {
            "enabled": "yes",
            "installed_version": "23.0.0",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "11.1.2",
            "types": "filesystem,dav"
        },
        "impersonate": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "integration_twitter": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "1.11.7",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.11.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerUrl": "https:\/\/cloud.ok-lab-karlsruhe.de\/index.php\/apps\/documentserver_community\/",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationHelp": "true",
            "customizationToolbarNoTabs": "true",
            "defFormats": "{\"csv\":\"false\",\"doc\":\"true\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"true\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"true\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"true\",\"ods\":\"true\",\"odt\":\"true\",\"rtf\":\"true\",\"txt\":\"true\"}",
            "enabled": "yes",
            "groups": "[]",
            "installed_version": "7.3.2",
            "sameTab": "true",
            "types": "prevent_group_restriction"
        },
        "ownpad": {
            "enabled": "no",
            "installed_version": "0.6.15",
            "ocsid": "174679",
            "ownpad_etherpad_enable": "yes",
            "ownpad_etherpad_host": "https:\/\/pad.okfn.de\/",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "3.4.2",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "prevent_group_restriction"
        },
        "quicknotes": {
            "enabled": "no",
            "installed_version": "0.6.3",
            "types": ""
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "3.5.3",
            "types": "filesystem,dav,prevent_group_restriction"
        },
        "serverinfo": {
            "cached_count_filecache": "138411",
            "cached_count_storages": "18",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem"
        },
        "socialsharing_twitter": {
            "enabled": "no",
            "installed_version": "2.3.0",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "13.0.5",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "dav,prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "last_report": "{\"id\":\"ocbh30v0uq4m\",\"items\":[[\"server\",\"version\",\"23.0.2.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Memcached\"],[\"server\",\"memcache.distributed\",\"\\\\OC\\\\Memcache\\\\Memcached\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.29\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.3.28\"],[\"database\",\"size\",73793536],[\"apps\",\"accessibility\",\"1.9.0\"],[\"apps\",\"activity\",\"2.15.0\"],[\"apps\",\"admin_audit\",\"1.13.0\"],[\"apps\",\"analytics\",\"4.0.3\"],[\"apps\",\"bruteforcesettings\",\"2.3.0\"],[\"apps\",\"calendar\",\"3.1.0\"],[\"apps\",\"carnet\",\"disabled\"],[\"apps\",\"circles\",\"disabled\"],[\"apps\",\"cloud_federation_api\",\"1.6.0\"],[\"apps\",\"comments\",\"1.13.0\"],[\"apps\",\"contacts\",\"4.0.8\"],[\"apps\",\"contactsinteraction\",\"1.4.0\"],[\"apps\",\"dashboard\",\"7.3.0\"],[\"apps\",\"dashboardcharts\",\"disabled\"],[\"apps\",\"dav\",\"1.21.0\"],[\"apps\",\"deck\",\"1.6.0\"],[\"apps\",\"documentserver_community\",\"0.1.12\"],[\"apps\",\"dropit\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.13.0\"],[\"apps\",\"federation\",\"1.13.0\"],[\"apps\",\"files\",\"1.18.0\"],[\"apps\",\"files_fulltextsearch\",\"23.0.0\"],[\"apps\",\"files_markdown\",\"2.3.5\"],[\"apps\",\"files_mindmap\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"2.4.0\"],[\"apps\",\"files_rightclick\",\"1.2.0\"],[\"apps\",\"files_sharing\",\"1.15.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.13.0\"],[\"apps\",\"files_versions\",\"1.16.0\"],[\"apps\",\"files_videoplayer\",\"1.12.0\"],[\"apps\",\"firstrunwizard\",\"2.12.0\"],[\"apps\",\"fulltextsearch\",\"23.0.0\"],[\"apps\",\"groupfolders\",\"11.1.2\"],[\"apps\",\"impersonate\",\"1.10.0\"],[\"apps\",\"integration_twitter\",\"1.0.2\"],[\"apps\",\"logreader\",\"2.8.0\"],[\"apps\",\"lookup_server_connector\",\"1.11.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.12.0\"],[\"apps\",\"notifications\",\"2.11.1\"],[\"apps\",\"oauth2\",\"1.11.0\"],[\"apps\",\"onlyoffice\",\"7.3.0\"],[\"apps\",\"ownpad\",\"disabled\"],[\"apps\",\"password_policy\",\"1.13.0\"],[\"apps\",\"photos\",\"1.5.0\"],[\"apps\",\"polls\",\"3.4.2\"],[\"apps\",\"privacy\",\"1.7.0\"],[\"apps\",\"provisioning_api\",\"1.13.0\"],[\"apps\",\"quicknotes\",\"disabled\"],[\"apps\",\"ransomware_protection\",\"1.12.0\"],[\"apps\",\"recommendations\",\"1.2.0\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.13.0\"],[\"apps\",\"settings\",\"1.5.0\"],[\"apps\",\"sharebymail\",\"1.13.0\"],[\"apps\",\"socialsharing_twitter\",\"disabled\"],[\"apps\",\"spreed\",\"13.0.3\"],[\"apps\",\"support\",\"1.6.0\"],[\"apps\",\"survey_client\",\"1.11.0\"],[\"apps\",\"systemtags\",\"1.13.0\"],[\"apps\",\"talk_simple_poll\",\"disabled\"],[\"apps\",\"tasks\",\"0.14.2\"],[\"apps\",\"text\",\"3.4.0\"],[\"apps\",\"theming\",\"1.14.0\"],[\"apps\",\"theming_customcss\",\"1.10.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.12.0\"],[\"apps\",\"updatenotification\",\"1.13.0\"],[\"apps\",\"user_status\",\"1.3.1\"],[\"apps\",\"viewer\",\"1.7.0\"],[\"apps\",\"weather_status\",\"1.3.0\"],[\"apps\",\"whiteboard\",\"disabled\"],[\"apps\",\"workflowengine\",\"2.5.0\"],[\"stats\",\"num_files\",137910],[\"stats\",\"num_users\",15],[\"stats\",\"num_storages\",18],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",17],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",306],[\"stats\",\"num_comment_markers\",5],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",256],[\"files_sharing\",\"num_shares_user\",77],[\"files_sharing\",\"num_shares_groups\",8],[\"files_sharing\",\"num_shares_link\",73],[\"files_sharing\",\"num_shares_link_no_password\",73],[\"files_sharing\",\"num_fed_shares_sent\",1],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"13\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"files_sharing\",\"permissions_3_17\",\"57\"],[\"files_sharing\",\"permissions_4_17\",\"1\"],[\"files_sharing\",\"permissions_0_19\",\"37\"],[\"files_sharing\",\"permissions_1_19\",\"3\"],[\"files_sharing\",\"permissions_2_19\",\"36\"],[\"files_sharing\",\"permissions_3_19\",\"2\"],[\"files_sharing\",\"permissions_6_19\",\"1\"],[\"files_sharing\",\"permissions_1_23\",\"1\"],[\"files_sharing\",\"permissions_2_23\",\"12\"],[\"files_sharing\",\"permissions_0_31\",\"40\"],[\"files_sharing\",\"permissions_1_31\",\"4\"],[\"files_sharing\",\"permissions_2_31\",\"48\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"yes\"]]}",
            "last_sent": "1646212807",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "talk_simple_poll": {
            "enabled": "no",
            "installed_version": "1.3.1",
            "types": "prevent_group_restriction"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.14.4",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.4.1",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "4",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "logoMime": "image\/svg+xml",
            "name": "OK Lab Karlsruhe",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "theming_customcss": {
            "cachebuster": "1586242723873",
            "customcss": "",
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "updatenotification": {
            "analytics": "4.2.1",
            "bruteforcesettings": "2.3.0",
            "calendar": "3.2.2",
            "carnet": "0.23.0",
            "contacts": "4.1.0",
            "core": "23.0.3.2",
            "deck": "1.6.1",
            "documentserver_community": "0.1.12",
            "enabled": "yes",
            "files_fulltextsearch": "21.0.4",
            "files_markdown": "2.3.5",
            "files_mindmap": "0.0.24",
            "files_texteditor": "2.14.0",
            "fulltextsearch": "21.0.3",
            "groupfolders": "10.0.2",
            "installed_version": "1.13.0",
            "integration_twitter": "1.0.2",
            "onlyoffice": "7.3.2",
            "ownpad": "0.6.15",
            "polls": "3.5.0",
            "ransomware_protection": "1.13.0",
            "spreed": "13.0.5",
            "talk_simple_poll": "1.3.1",
            "tasks": "0.14.4",
            "theming_customcss": "1.11.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "whiteboard": {
            "enabled": "no",
            "installed_version": "0.0.3",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "filesystem"
        }
    }
}

</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [x ] 7.3 or lower
- [ ] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [x ] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x ] Firefox version: 98.0.2
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
Not in your version: https://github.com/nextcloud/polls/releases/tag/v3.5.0
