### ISSUE TITLE
Styling not working properly in Chrome

### ISSUE THREAD

**Issue by JDHH83** [nextcloud/polls#2384]
## What is going wrong? What did you observe?
**Describe the bug**

If you open polls in the latest Chrome version (Version 100.0.4896.88 ) all Icons are displayed multiple times due to some css not being picked up by Chrome, it works fine in Firefox.
Please see the attached screenshot.

**Steps to reproduce the behavior**

Open the Polls Admin page with Chrome

**Add a screenshot of the misbehavior**
![image](https://user-images.githubusercontent.com/18344789/164428662-16b1e8d9-fdfa-4e17-a6e3-28fd6276452b.png)

![image](https://user-images.githubusercontent.com/18344789/164428954-acc71d01-94bf-41f1-9a11-9591d77a00fc.png)
If you add -webkit at the beginning to the crossed through css styles it is working in Chrome.

## How should it work?
**What you expected to happen?**

Non repeating icons

## Information about your polls installation
**Polls version:** (see apps page)

3.6.0-beta1

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Hub II (23.0.4 RC1)

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [x] Chrome version: 100.0.4896.88
- [ ] Safari version:
- [ ] Other (add name and version):

**Comment by dartcafe** [comment]
Great thanks!
