### ISSUE TITLE
revealing EMail is not allways GDPR compliant

### ISSUE THREAD

**Issue by demlak** [nextcloud/polls#2392]
## Describe the goal you'd like to achieve
Being GDPR compliant in an environment where EMails should not be revealed

## Describe possible solutions
- best would be an option to hide mailadresses for non-admins / "normal"-Poll-Owners at all
  - nice-to-have, would be an option for poll-attendees to decide for themself, if they want to reveal mailadress (default should be "don't")
- workaround would be an option to disable Mailadresses on export and disable "copy mailadresses to clipboard", etc. - centralised
- not that good.. but still a workaround: give me hints on where to "hack" polls in source-code, to disable.

## Additional context
I know.. many of you asked for including mailadresses on export.. but in our case, this prevents us from using polls at all.
Our case: we manage our users and groups via ldap.. so there is a global ldap-group where everyone is inside.. since nextcloud is still revealing contact information to everyone in the same group (in here 700 semi-private-users), as default, [we had to "hack" some things..](https://github.com/nextcloud/server/issues/14959#issuecomment-950446176) but on polls, poll-owners are able to export poll-information including mailadresses.. 
nevermind.. is it possible to work with Polls, without revealing mailadresses, unless someone explicit accepts to reveal mailadress to poll-owner (like on public links)?

thx for listening.

**Comment by dartcafe** [comment]
Just to clarify: This no GDPR issue, rather than a privacy policy issue. 
I will add a patched version 3.6.1 here in a few minutes, so you can test this. Details can be found in the linked PR.

**Comment by dartcafe** [comment]
@demlak See current [beta release](https://github.com/nextcloud/polls/releases/tag/v3.7.0-beta1).

**Comment by demlak** [comment]
"Harter scheiß!"

Filling a feature request in under 24h.. amazing!

i was testing and it works in case of privacy, like you said.. 
thanks a very very lot!

for UI, maybe this part should be updated:
![Zwischenablage02](https://user-images.githubusercontent.com/11285006/165626935-246c960f-4f2a-44bf-a4db-b183b3379c2c.jpg)
- It is not copy of mail adresses anymore.. 
- the copy in clipboard still includes `<>`

**Comment by dartcafe** [comment]
> Filling a feature request in under 24h.. amazing!

This triggered me, because I try to avoid data, where possible and needed, and I had an idea how to get that qickly done. I just struggled with a class, so I first wanted to reduce code lines before testing. Otherwise I would have been ready this morning after the first coffee. 😀 

> It is not copy of mail adresses anymore. so maybe, the label should be changed.

It still is in case of mail addresses of external users or if the owner invited people from his contact list. The empty brackets are by intention, to indicate that no email address is available.

**Comment by demlak** [comment]
Always good to know the trigger of other people 😂

thx a lot!

**Comment by dartcafe** [comment]
@demlak There was a syntax error. Beta2 fixes that.

**Comment by Keyinator** [comment]
> Find the new settings in the "other Settings" ![grafik](https://user-images.githubusercontent.com/26707476/165479052-1ba6cf0a-65f0-4234-b2e1-2865f811f552.png)

I can't find this option on the latest version (27.1.2). Was it removed?

**Comment by dartcafe** [comment]
Nope. It is there: 
![grafik](https://github.com/nextcloud/polls/assets/26707476/09c98bbe-be69-4cf3-9ba3-2cf0038a1ed4)
