### ISSUE TITLE
do not show polls menu button (tested with Nextcloud guests user)

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/polls#2398]
In Nextcloud Guests (possibly also with other users) the user sees the app polls.
Especially with Nextcloud Guests it is bad because there are only three apps shown:
files, photos and ... **polls**.

## What is going wrong? What did you observe?
There are a lot of options in polls to deactivate polls.
But in every option the menu point polls is activated.

## How should it work?
I think there must be an option to hide the menu button.

**Polls version:** (see apps page)
3.6.1

**Nextcloud version:**
23.0.4

**Comment by dartcafe** [comment]
I don't understand this issue. Which icon are you referring to?

**Comment by dartcafe** [comment]
Ah. You are referring to the app icon in the top navigation, right? 
If yes, this is controlled by the guest app. I guess polls is white listed for guests. There is nothing what can be do in Polls.

**Comment by devnull4242** [comment]
Yes. In the guest app it can be deactivated. My fault. Thanks for the great app.
