### ISSUE TITLE
Allow change of name after initial dialogue

### ISSUE THREAD

**Issue by SirBuvex** [nextcloud/polls#2400]
It would be great if users could change their displayed name after they clicked "OK" on the initial dialogue. In my case, I invited people by email (not in the `Anton Apple <anton@apple.com>` format but only the email address). Then, they forgot to fill in their names and now their email addresses are displayed as their name… which bothers me a little ;)
So it would be great, if the admin could change the name afterwards and also the people themselves (simply the same way they can already change their email address).

Maybe another way of preventing this kind of problem completely may be that the email address will only be inserted in the email form field so they have to insert their name manually… (at least as an option)

**Comment by dartcafe** [comment]
👍 This is on the list. Since the entered name is also the user's identifier, there is to do a lot more refactoring and this will unfortunately last longer.
