### ISSUE TITLE
Settings icon visibility problem with theming

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#2405]
The settings icon does not work well with theming: It does not switch color needed for contrast against custom background:

![Screenshot 2022-05-03 at 08 57 53](https://user-images.githubusercontent.com/43957716/166419745-e4adbbdc-c002-4550-82e1-69a8e7550718.png)

Proposal button as a reference:
![Screenshot 2022-05-03 at 08 58 14](https://user-images.githubusercontent.com/43957716/166419765-b6e72223-a0a7-4e6c-87a3-93c6e71db4ee.png)

**Comment by dartcafe** [comment]
We have to wait for an update of @nextcloud/vue to support material design icons for the actions

**Comment by herrmannsdorfer** [comment]
Confirmed. #2439 fixes this issue.
