### ISSUE TITLE
EMail-Notification for activity

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/polls#2420]
Is it possible, to get a mail, once there's any activity from participants?
Maybe it's a function, where I didn't find, yet??

I used Framadate before as doodle, but it's no longer maintained, and polls looks like a great replacement.

Thanks,

-Tom-

**Comment by dartcafe** [comment]
You can subscribe to poll events via the user menu:
![grafik](https://user-images.githubusercontent.com/26707476/168652497-c1e3e8f9-b6f3-4b31-aa2f-ca7becbcd79c.png)

**Comment by kangaroo72** [comment]
Thank you for that "hint".
Indeed, it works! :-D
