### ISSUE TITLE
Wrong translation in polish language

### ISSUE THREAD

**Issue by Maniok2212** [nextcloud/polls#2430]
## What is going wrong? What did you observe?
**Wrong translation in "enter name" dialogue**

It literary says "name is not correct" in polish

![IMG_20220522_125534](https://user-images.githubusercontent.com/106015493/169700134-0a997908-f3a1-449a-a1d7-dbbd8b416311.jpg)

## How should it work?
"nieprawidłowa" means "not correct". It should be "prawidłowa" which means "correct".

## Information about your polls installation
**Polls version:** 3.6.1

**Fresh installation**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.1

</details>

**Comment by dartcafe** [comment]
@Valdnet Can you check that in transifex?

**Comment by Valdnet** [comment]
@Maniok2212 Thanks for reporting a translation error 👍. The text string was incorrectly translated a year ago by a translator from Transifex.
I also invite you to check and actively translate other new text strings 😉.

@dartcafe The text string has been changed to look more stylistic.
Please approve #2443.
