### ISSUE TITLE
[Feature Request] multiple selection in text poll of one option

### ISSUE THREAD

**Issue by citizenserious** [nextcloud/polls#2435]
## Describe the goal you'd like to achieve

As a poll owner,I want to be able to give poll participants the option to give more than one vote per topic in text polls. Because it gives the option to make pools like that:

T-Shirt White M
T-Shirt White L
T-Shirt Black M
T-Shirt Black L
T-Shirt Green M
T-Shirt Green L

there you could select how many T-Shirts you need.
Right now I have to give the user the option like this

1x T-Shirt White M
2x T-Shirt White M
3x T-Shirt White M
1x T-Shirt White L
2x T-Shirt White L
3x T-Shirt White L
.... and so on

## Describe possible solutions
Implement a optional option to vote multiple times in a text poll

Thanks  a lot for this great app (:

**Comment by dartcafe** [comment]
This is like using a counter instead of yes, no, maybe. Right?

**Comment by citizenserious** [comment]
@dartcafe Exactly.  The option to count (vote) more times for one option.

**Comment by dartcafe** [comment]
So it is comparable to #765. Still on the list, but no progress so far.

**Comment by citizenserious** [comment]
@dartcafe oh... yes it is. I am sorry, I really searched multiple keywords. I must have over looked this.
