### ISSUE TITLE
Editing participants in the share field causes errors in the log

### ISSUE THREAD

**Issue by stepka0815** [nextcloud/polls#2437]
### Observation

- Each character input generates 2 errors.
- Deleting characters also causes these error messages, but not for every character I delete.
- The functionality of Polls does not seem to be affected.

Normally I wouldn't expect these error messages.

### The 2 errors
![grafik](https://user-images.githubusercontent.com/93402363/170491805-ea3c6935-f7da-4f4a-a45d-86f4a0a1b8f6.png)

Formatted details:
- [PHP] Fehler: Undefined array key 0 at /var/www/nextcloud/apps/polls/lib/Service/SystemService.php#125
GET /index.php/apps/polls/search/users/a
from 78.50.14.210 by A1_UmfTest at 2022-05-26T12:42:26+00:00
- [PHP] Fehler: Undefined array key 0 at /var/www/nextcloud/apps/polls/lib/Service/SystemService.php#124
GET /index.php/apps/polls/search/users/a
from 78.50.14.210 by A1_UmfTest at 2022-05-26T12:42:26+00:00

### Versions used
NC version: 23.0.0
Polls version: 3.6.1 (update installed 1 day ago from Appstore)

Let me know, if you need further informations.

**Comment by dartcafe** [comment]
> Let me know, if you need further informations.

Yes, please. Use the [issue form](https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=bug_report.md), that you skipped. I have no idea, how I can reproduce, what you did.
