### ISSUE TITLE
Clear votes older than specified date

### ISSUE THREAD

**Issue by benjamindahl** [nextcloud/polls#2446]
Hey,

we've got a poll with about 40 participants and 30 options (1200 cells) which we shift one week further weekly. 
At the moment the performance for loading this poll is quite poor. In the beginning, it was good but after some time it became slower every week. The system of our nextcloud hosted by https://owncube.com has 4 GB of RAM.

We'd like to suggest being able to clear votes which are older than 6 weeks.

cheers
Benny

**Comment by dartcafe** [comment]
Could you describe the process in more detail? I.e. the steps you are executing.
