### ISSUE TITLE
Incorrect grammar for closing date on closed poll info view

### ISSUE THREAD

**Issue by kimimaru4000** [nextcloud/polls#2453]
When a poll is closed, it still says "Closing" instead of "Closed". For example, if a poll closed 7 minutes ago, it will say "Closing: 7 minutes ago", which is confusing.

See the image below:
![Poll](https://user-images.githubusercontent.com/1388037/172915796-382131e8-de5e-4ffe-af74-d81e940683bd.png)

Steps to replicate:
1. Open a poll and close voting in the near future
2. Wait for voting to be closed for the poll
3. Go to the poll and click on the (i) icon to bring up the information panel
4. Observe that it says "Closing:" instead of "Closed:"

**Comment by dartcafe** [comment]
Actually it is correct, because in this case "closing" means the noun "closing" or the closing time and not the verb "to close".
