### ISSUE TITLE
"Leistungseinstellungen" field to small

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#2461]
## What is going wrong? What did you observe?
Field to small

A clear and concise description of what is wrong.
The field for "Leistungseinstellungen" in your own profile is a little bit to small

**Steps to reproduce the behavior**
1. Go to "Settings"
2. "Polls"
3. See the small field

**Add a screenshot of the misbehavior**
![image](https://user-images.githubusercontent.com/1473674/174475770-57bb96e3-736f-4e18-add8-a31fc892686c.png)

## Information about your polls installation
**Polls version:** 3.7.0-beta2

**Database:**
- [ ] MySql version:
- [X] MariaDB version: 10.3
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [X] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration
**Device:** 
- [X] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [x] Microsoft Edge: 102.0.1245.44 (Offizielles Build) (64-Bit)

**Comment by dartcafe** [comment]
Should be fixed in beta5: 
![grafik](https://user-images.githubusercontent.com/26707476/174676078-1ed58ccc-97a9-4727-8ab2-c81d49ff2504.png)

**Comment by dartcafe** [comment]
Ah. And there is a new bug, i am already aware of:
![grafik](https://user-images.githubusercontent.com/26707476/174676235-a2163070-1344-4e8e-a201-274c27fd6250.png)

**Comment by dartcafe** [comment]
I'll close this, since it is fixed.
