### ISSUE TITLE
Blank page after clicking on the personal link again (after voting)

### ISSUE THREAD

**Issue by LuHa9** [nextcloud/polls#2466]
## What is going wrong? What did you observe?
I have a poll with personal links. When I first click on my personal link (as an external poll user, i.e. I am not logged in in Nextcloud) I received via email everything was fine so I made my answers to the poll. After closing the window and return to the page by clicking on the personal link again (or pasting the URL in the browser) I only get a blank (white) page.

Actually this behavior only occurs in Safari Browser on the Mac (macOS Monterey). If I take the same link in Chrome or in Safari on iOS, the poll will appear and I can change my answers.

Another poll user reported the same behavior. She reported that this behavior only occurs in Chrome Browser on her Android phone. My guess is that this behavior occurs in especially that browser where the user made his first answers to the poll.

**Steps to reproduce the behavior**
1. Go to the poll as an external user by clicking on the personal invitation link.
2. Make answers and close the window.
3. Got to the poll again by clicking on the personal invitation link (using the same browser).
4. See error (blank white page)

**Add a screenshot of the misbehavior**
<img width="1296" alt="Bildschirmfoto 2022-06-22 um 21 21 18" src="https://user-images.githubusercontent.com/107914877/175119329-0e69d3ad-3a1b-4808-8b78-196e454b00db.png">

## How should it work?
**What you expected to happen?**
That the poll will appear always by using the personal link.

## Information about your polls installation
**Polls version:** 3.6.1

**Fresh installation or update from a prior version (from which one)?**
- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.1.

<details>
<summary>List of activated apps</summary>
I don't have access to my command line because I use Nextcloud as a SaaS.
</details>
<details>
<summary>Nextcloud Configuration</summary>
I don't have access to my command line because I use Nextcloud as a SaaS.
</details>

### Client configuration
**Device:** 
- [ ] PC
- [x] Mac
- [x] Mobile phone
- [ ] Tablet

**Browser:** 
- [ ] Firefox version:
- [x] Chrome version: 103.0
- [x] Safari version: 15.4
- [ ] Other (add name and version):

## Logs
I don't know how to get the logs.

**Comment by LuHa9** [comment]
Update: I can reproduce it with a new poll (see steps above), but I cannot reproduce it by using Chrome as the first Browser (in which I made my first answers).

**Comment by LuHa9** [comment]
It seems like a cookie problem. If I delete my cookies in Safari the page appears after reloading it.

**Comment by dartcafe** [comment]
Any logs from the client console could help a lot

**Comment by LuHa9** [comment]
I‘m sorry but what logs do especially help and how do I get them?

**Comment by dartcafe** [comment]
Safari's menu has a developer entry. Open it and click on "open Javascript console" or similair. 
Then you will get a window under your page, with some logging entries. 
* Look out for error entries in the console. 
* Also check, if under the tab elements you can see the HTML DOM aka expandable HTML elements
* And check the network tab to inspect, if there is network activity which loads code from the site. 

If you are not sure, make screenshots. If you dont want to share them here, you can upload them [there](https://nc.yagst.de/s/FXXDEK2SPmF9rpH).

I tried to reproduce it on Windows and Mac with Firefox, Chrome and Safari and cannot reproduce that issue.

**Comment by LuHa9** [comment]
Thanks. I uploaded the screenshots there. I could reproduce it on three clients (Macbook, iMac, iPhone). The other poll user on an Android Phone.

**Comment by LuHa9** [comment]
I just uploaded another screenshot there (Console_normalBehavior): The console tab when the poll loads regularly without any visible error. Comparing them reveals that each of the error logged appears in the non-error-case as well. The entry "[polls] - 'Watch for updates'" just doesn't appear in the error case.

**Comment by LuHa9** [comment]
And another screenshot: Network_2.png. It reveals that the entry "share" appears infinitely often (also by further scrolling);-)

**Comment by dartcafe** [comment]
Good news I could reproduce the issue. It seems to only happen with email shares (I should read the report better). I will investigate further. So I do not need any further information from you. 

Thanks for reporting.

**Comment by LuHa9** [comment]
Great! Do you see any workaround for that that already in this version works? Maybe something like generating a new link that won't be shared via email share?

**Comment by dartcafe** [comment]
Use a public link and let the users register.

**Comment by LuHa9** [comment]
One short question: Includes the bug fixing in 3.7.0 also my concrete example poll that is already in process or does it only fixes the bug in new released polls? Thank you for the fast fixing at this point!

**Comment by dartcafe** [comment]
That fixes existing polls also.
