### ISSUE TITLE
user picture from ldap not shown

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#247]
In a poll, all users have pictures (came from ldap). But one users picture not shown:

![image](https://user-images.githubusercontent.com/1249295/32830518-bf9b4282-c9f5-11e7-8064-69e47136c378.png)

If i login with this user, the picture is shown at the menu.

The only error in the log is:

`	OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM *PREFIX*polls_events WHERE hash = ?"; parameters Array ( [0] => 8nVBekSk3g77Rug7 ) ; limit ""; offset ""
/var/www/html/nextcloud/lib/public/AppFramework/Db/Mapper.php - line 359: OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM *...', Array, NULL, NULL)
/var/www/html/nextcloud/apps/polls/lib/Db/EventMapper.php - line 58: OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM *...', Array, NULL, NULL)
/var/www/html/nextcloud/apps/polls/lib/Controller/PageController.php - line 279: OCA\Polls\Db\EventMapper->findByHash('8nVBekSk3g77Rug...')
[internal function] OCA\Polls\Controller\PageController->editPoll('8nVBekSk3g77Rug...')
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Polls\Controller\PageController), 'editPoll')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Polls\Controller\PageController), 'editPoll')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('PageController', 'editPoll', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/polls/edi...')
/var/www/html/nextcloud/index.php - line 48: OC handleRequest()
{main}`

Any ideas?

**Comment by splitt3r** [comment]
Does the browser console say sth.? Is the avatar shown in other apps? I thnink Nc handles the avatars so the chances are high that we can´t do anything here. You could also inspect the element with your browser to check the images url.

**Comment by BurtGummer** [comment]
Hello splitt3r,

i right click on the error-picture, "Inspect" (in germand "Untersuchen"), klick on console: nothing there:

![image](https://user-images.githubusercontent.com/1249295/32831806-c8626892-c9f9-11e7-84a1-e680d35a6b79.png)

NC show the picture - **if i login with this user, i see** his picture (for example in "personal" or in shares or in the menu).

The images URL seems exact the same, except the username (2 different Franks):

![image](https://user-images.githubusercontent.com/1249295/32832144-cce226f4-c9fa-11e7-8815-4353a1129557.png)

one Frank works, one not.

If i right click the pic and "open picture in new tab", one frank i can see, one have just a white page.

**Comment by BurtGummer** [comment]
wtf?!? i dont know why, but now it works. Seems it needs some time to synchronize the pictures. Sorry and thank you :-)
