### ISSUE TITLE
Answer option „not answered“ after adding a new option

### ISSUE THREAD

**Issue by LuHa9** [nextcloud/polls#2472]
## Describe the goal you'd like to achieve
As a poll owner I can add new answer options to the poll even if poll users already answered the outgoing ones. If those users don’t update their answer, it will be displayed as if they had given the answer „no“ to these new options. Hence I as a poll owner do not see a difference between „not answered/updated yet“ and the answer „no“ which is confusing for both the poll owner an the poll users. Furthermore I as a poll owner could hereby kind of fudge the users answers…

## Describe possible solutions
Adding a new default answer „not answered yet“ (colour grey) for the cases described above.

**Comment by dartcafe** [comment]
Unvoted is counted as no, because the paticipant did not say "yes" (or "maybe"). A participant can tell if he answered or not, since unvoted options a displayed as an empty cell incontrast to an explicit "no".

For the result it makes no difference.

We had several discussions in the past about it.
