### ISSUE TITLE
Owner should be able to remove entries

### ISSUE THREAD

**Issue by eraelpeha** [nextcloud/polls#248]
It would be a great enhancement if the owner of a poll has the ability to delete single result lines from a poll (in case of test / multiple / fake entries).

**Comment by dartcafe** [comment]
I will think over it. But it schould be reproducable for other participants. For example mark them as invalid...

**Comment by Mannshoch** [comment]
Maybe an option to to chose to show them as "removed" or simply remove an entry without information. 
At moment I remove entries direct in the database.

**Comment by ebiel** [comment]
I strongly support the addition of this feature.
In my opinion,
- the owner of a poll and any user in the admin group should be allowed to do this
- there is no need for displaying removed participants (poll-owner and admin are trustworthy)
This seems to be related to #397 and from a use-case perspective also to #377 .

**Comment by Mannshoch** [comment]
>     * there is no need for displaying removed participants (poll-owner and admin are trustworthy)

Maybe only list them as removed for the admin

**Comment by japso** [comment]
Personally, I do not see any advantage in displaying removed participants (and their votes?). Could you explain to me how this is meaningful in your use-case?

If the displaying of removed participants together with their votes is something others consider useful, I'd very much prefer an option for the owner/creator of a poll and any user in the admin group to hide participants together with their votes (= poll entries):
- poll entry not hidden: poll entry visible for all users viewing the poll, poll entry is counted towards the total number of yes/nos of a vote option 
- poll entry hidden: UI: poll entry is shown as inactive for poll owner/creator and any user in the admin group and still shown at the same place within the table of votes; UI: poll entry is not visible for regular users viewing the poll; poll entry is not taken into account for calculating the total number of yes/nos of a vote option

This should be fairly simple to implement:
- you introduce a boolean parameter hidden for every poll entry
- this boolean parameter has to be queried at certain points (UI, total number of yes/no etc.)

**Comment by japso** [comment]
Thank you @jancborchardt , I full agree with you. Removing entries is the priority here.

**Comment by tbhunderbird** [comment]
Any updates on when it might become available?

**Comment by dartcafe** [comment]
Standard answer: When it's ready. 

Work on vue migration is in progress. After that, it could be possible to be on the todo list.

**Comment by MacGulliver** [comment]
Any news as of now?

**Comment by thamvmk** [comment]
Yeah, anyone working on this feature?

**Comment by dartcafe** [comment]
#736
