### ISSUE TITLE
Switchin from scss to css. 

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#250]
There are some issues regarding non standard installations of NC. So we should switch to css for the releases, until scss support in NC is complete for this installation variants. Additionally this issue would support NC11 and OC as well.

**Comment by splitt3r** [comment]
How do other apps like [Contacts](https://github.com/nextcloud/contacts/tree/master/css) or [Deck](https://github.com/nextcloud/deck/tree/master/css) handle this problem? Sounds like a rare case 🤔 perhaps we could implment a fallback?

**Comment by dartcafe** [comment]
The problem seems to be inside the scss precompiler in NC which compiles `background-image: url('../img/open-voted-vote.svg');` to `background-image: url('../../../apps/polls/css/../img/open-voted-vote.svg');` pointing from the css directory. 

If I compile the scss locally the precompiler leaves it untouched. 

I have no idea how to have a fall back strategy. Seems, that the functions in core have to be updated. Until then, we can switch to native compiled css.

**Comment by dartcafe** [comment]
@v1r0x: We just need to eleminate the scss files from the releases. 
@splitt3r Any change to have a robot which nightly compiles the css files? Maybe for some other jobs too.

**Comment by splitt3r** [comment]
Hm i don´t think so. Perhaps Travis CI could do it but that would be a very hacky solution. Let´s wait for an answer to https://github.com/nextcloud/polls/issues/249#issuecomment-346048705.

**Comment by splitt3r** [comment]
So if https://github.com/nextcloud/server/pull/7257 don´t need to switch 👍

**Comment by Hanzei** [comment]
https://github.com/nextcloud/server/pull/7257 is merged :smile:
