### ISSUE TITLE
Admin: Add votes from users manually

### ISSUE THREAD

**Issue by maniackatzentier** [nextcloud/polls#2500]
## Describe the goal you'd like to achieve
It would be great if it would be possible (as ADMIN) to be able to add votes from users to the poll. E.g. if the user did not vote in Nextcloud directly, but told the admin his preferred option (e.g. orally in person or via mail), the admin should be able to add this vote manually.

This helps to get a complete overview of a poll result, also considering users who had no possibility to cast their vote in Nextcloud directly.

**Comment by dartcafe** [comment]
@maniackatzentier Hmmm. Seems I did not send my comment. I try to recover it from my brain. ;-)

First: This is against the intention of this poll.
Second: The implementation has a lot of complexity, so it is more expensive than it seems compared to the value.

But to achieve this, you can use a public link in another container, browser or in a private window and answer in the name of the participant.
