### ISSUE TITLE
Argument 8 passed to OC\Core\Controller\AvatarController::__construct() must implement interface OCP\Files\Folder, null given

### ISSUE THREAD

**Issue by darootler** [nextcloud/polls#251]
### Steps to reproduce
1. Create a public poll
2. Access the public poll
3. Check the log files

### Expected behaviour
No errors are logged

### Actual behaviour
I am receiving the following error:
`{index} Exception: {"Exception":"TypeError","Message":"Argument 8 passed to OC\\Core\\Controller\\AvatarController::__construct() must implement interface OCP\\Files\\Folder, null given, called in \/var\/www\/owncloud\/core\/Application.php on line 98","Code":0,"Trace":"#0 \/var\/www\/owncloud\/core\/Application.php(98): OC\\Core\\Controller\\AvatarController->__construct('core', Object(OC\\AppFramework\\Http\\Request), Object(OC\\AvatarManager), Object(OC\\Cache\\File), Object(OC\\L10N\\L10N), Object(OC\\User\\Manager), Object(OC\\User\\Session), NULL, Object(OC\\Log))\n#1 \/var\/www\/owncloud\/lib\/composer\/pimple\/pimple\/src\/Pimple\/Container.php(113): OC\\Core\\Application->OC\\Core\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#2 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(111): Pimple\\Container->offsetGet('AvatarControlle...')\n#3 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(81): OC\\AppFramework\\Ut
 ility\\SimpleContainer->query('AvatarControlle...')\n#4 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#5 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#6 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(307): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#7 \/var\/www\/owncloud\/lib\/base.php(928): OC\\Route\\Router->match('\/avatar\/Andi\/64')\n#8 \/var\/www\/owncloud\/index.php(56): OC::handleRequest()\n#9 {main}","File":"\/var\/www\/owncloud\/core\/Controller\/AvatarController.php","Line":82}`

### Server configuration

**Operating system**:
Ubuntu 16.04.3

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.7.20

**PHP version:**
7.0.22

**Nextcloud version:** (see Nextcloud admin page)
ownCloud 10.0.3

**Where did you install Nextcloud from:**
Repositories

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_videoplayer: 0.9.8
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.1
  - polls: 0.8.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_versions
  - firstrunwizard
  - provisioning_api
  - theme-example
  - user_external
```

**Nextcloud configuration:**

```
{
    "system": {
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbhost": "localhost:\/run\/mysqld\/mysqld.sock",
        "dbname": "owncloud",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": false,
        "forcessl": true,
        "installed": true,
        "instanceid": "ocex2kqrsky0",
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 360,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 1,
        "logtimezone": "Europe\/Vienna",
        "mail_domain": "marschik.biz",
        "mail_from_address": "owncloud",
        "mail_smtphost": "smtp.marschik.biz",
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwrite.cli.url": "https:\/\/owncloud.marschik.biz\/owncloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": "1800",
        "syslog_tag": "ownCloud",
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "trusted_domains": [
            "owncloud.marschik.biz"
        ],
        "trusted_proxies": [
            "192.168.2.1"
        ],
        "updatechecker": false,
        "version": "10.0.3.3"
    }
}
```

**Are you using an external user-backend, if yes which one: LDAP plugin**

### Client configuration
**Browser: Edge**

**Operating system: Windows 10**

#### Nextcloud log (data/nextcloud.log)
```
  Server Name: server
  IP Address: 192.168.2.2
  Date/Time: Nov 21 23:07:39


 {index} Exception: {"Exception":"TypeError","Message":"Argument 8 passed to OC\\Core\\Controller\\AvatarController::__construct() must implement interface OCP\\Files\\Folder, null given, called in \/var\/www\/owncloud\/core\/Application.php on line 98","Code":0,"Trace":"#0 \/var\/www\/owncloud\/core\/Application.php(98): OC\\Core\\Controller\\AvatarController->__construct('core', Object(OC\\AppFramework\\Http\\Request), Object(OC\\AvatarManager), Object(OC\\Cache\\File), Object(OC\\L10N\\L10N), Object(OC\\User\\Manager), Object(OC\\User\\Session), NULL, Object(OC\\Log))\n#1 \/var\/www\/owncloud\/lib\/composer\/pimple\/pimple\/src\/Pimple\/Container.php(113): OC\\Core\\Application->OC\\Core\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#2 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(111): Pimple\\Container->offsetGet('AvatarControlle...')\n#3 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(81): OC\\AppFramework\\Ut
 ility\\SimpleContainer->query('AvatarControlle...')\n#4 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#5 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#6 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(307): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#7 \/var\/www\/owncloud\/lib\/base.php(928): OC\\Route\\Router->match('\/avatar\/Andi\/64')\n#8 \/var\/www\/owncloud\/index.php(56): OC::handleRequest()\n#9 {main}","File":"\/var\/www\/owncloud\/core\/Controller\/AvatarController.php","Line":82}
```

**Comment by splitt3r** [comment]
Can reproduce it and found https://github.com/owncloud/core/issues/23158 after googling it. Perhaps you could give some feedback there so they can investigate further.

**Comment by splitt3r** [comment]
Issue in core repo is reopened so i will close this for now.
