### ISSUE TITLE
[Feature Request] Notifiy poll participants about poll result via e-mail

### ISSUE THREAD

**Issue by im-fabian** [nextcloud/polls#2518]
## Describe the goal you'd like to achieve
*Describe what (goal) you want to achieve and why (value). Please explain your goal and why this is valuable and **do not** describe the solution you suggest. Try to use the following [user story](https://en.wikipedia.org/wiki/User_story) pattern:*

As a **poll owner**, I want to **be able to send an E-Mail with selected options to the poll participants after closing the poll**, because **it helps to inform the poll participants about the results**.

## Additional context
Often polls are used to shedule an appointment. So the participants need to get to know which day and time was choosen. Therefor it would be good if a poll owner can trigger such a notification.

GUI-wise I would place on the configure page right after the poll closure button. A info should be placed there if the notification has already be send and if the selected poll option was changed since the notification was send.

**Comment by dartcafe** [comment]
Still on the todo list

**Comment by dartcafe** [comment]
How about that?
![grafik](https://user-images.githubusercontent.com/26707476/183242748-bf36ec1a-a034-419b-b72f-22825f0d5a3d.png)
![grafik](https://user-images.githubusercontent.com/26707476/183242749-f14fd99f-f5a9-4230-a9e8-fbf76b1fdd95.png)

**Comment by dartcafe** [comment]
Mobile view
![grafik](https://user-images.githubusercontent.com/26707476/183242847-db6edcca-8265-4dca-83fd-2cfe5d639ea8.png)
![grafik](https://user-images.githubusercontent.com/26707476/183242881-ebc6a31a-9658-4959-ab72-992b9e247b8b.png)

**Comment by im-fabian** [comment]
I find this very appealing!

**Comment by im-fabian** [comment]
Accidentally closed.
