### ISSUE TITLE
User info should be editable for current user

### ISSUE THREAD

**Issue by ribeaud** [nextcloud/polls#2521]
## Describe the goal you'd like to achieve
When accessing a poll, I get asked for my name via a popup window (assuming this is a _public_ poll and I am not logged-in). After having entered my name and optionally an email address, I am no longer able to edit this information afterwards.

## Describe possible solutions
How about making the user info cell clickable for the entry associated to current user? On click, the popup appears again and user can correct his input.

**Comment by dartcafe** [comment]
Comming the next version. See #2494 and #2400
