### ISSUE TITLE
Not able to export if the owner is removed from the poll

### ISSUE THREAD

**Issue by ribeaud** [nextcloud/polls#2522]
## What is going wrong? What did you observe?

As poll **owner**, if I remove myself from the poll, I am no longer able to export the poll. I have to be part of the _public_ poll (_visible_ in the list of participants), even though I did not select any option.

**Steps to reproduce the behavior**
1. Create a simple and default date poll with two options
2. Remove yourself from the poll
3. Make the poll _public_ and access it in a incognito window 
4. Enter a name and select one option
5. Back to the **owner** view, try to export the poll ---> Nothing happens

## How should it work?

The poll should be exportable. As workaround, a (removed) **owner** could just temporary add himself to the poll (by ticking/unticking an option). By doing so, you get listed on the _public_ poll and the poll is then exportable.

**Comment by ribeaud** [comment]
This issue seems to relate to #2407.

**Comment by dartcafe** [comment]
Nope. This is a new bug.

**Comment by dartcafe** [comment]
As a workaround the owner just needs to vote in any option with no. Will be fixed in 3.8.0 and in the next beta (3.8.0-beta5)
