### ISSUE TITLE
Share tab remains empty

### ISSUE THREAD

**Issue by FloMiLe** [nextcloud/polls#2545]
## What is going wrong? What did you observe?
After creating a poll, the share tab remains empty so that a poll cannot be made public or shared.

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. Add new poll.
2. Click on share tab.
3. See that the tab body remains empty, i.e. white with nothing to click.

**Add a screenshot of the misbehavior**

<img width="887" alt="Screen Shot 2022-08-19 at 16 32 29" src="https://user-images.githubusercontent.com/13892710/185643416-6cf6af12-f88f-43de-ac4c-061b6f9d277a.png">

## How should it work?
**What you expected to happen?**

The sharing tab show offer options for sharing, as I believe it used to do.

## Information about your polls installation
**Polls version:** 3.7.0

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.4

**Comment by dartcafe** [comment]
Disable ad blocker

**Comment by FloMiLe** [comment]
Thanks a lot, @dartcafe! That did it.

May I just ask out of curiosity why add blockers seem to identify this particular part of the page as an ad?

**Comment by dartcafe** [comment]
Probably terms like `share` and similair.

**Comment by nextcloud486153** [comment]
Sorry for the necrobump, but for future readers of the future: if you want to keep your adblocker on, you can add the following filter to show the sharing sidebar:

```adblock
*#@#.app-polls .sidebar-share
```
