### ISSUE TITLE
Consolidate particip tables?

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#255]
The tables `polls_particip` and `polls_particip_text` are carrying the same information, with the difference, that the option is a date type on one side and a text type of the other side.

Either, we add a column to carry both types or the date type can become a text type with type migration in the get function. 

So we can ommit some functions in the controller, which are duplicates, besides the difference in the poll type.

**Comment by splitt3r** [comment]
Parts of the data model are a bit strange indeed 😆 we should consider some optimizations but also need to create a solid migration.

**Comment by splitt3r** [comment]
While recreating my Nc app i also dived deeper into sharing and comments in Nc. We could do pretty cool things in the polls app there too.

**Comment by v1r0x** [comment]
Yes, the data model is a bit crappy 😅 I'm open for suggestions, if the existing data can be easily migrated.

**Comment by dartcafe** [comment]
I think, it is a good moment for cleaning up the data model. But I fear, I have no change to get into it, because of missing programming experience. 

Also some more smoother ways of sharing and commenting would be great. At least, I have some ideas of making the create/update GUI a little bit more comfortable. 

So what about merging the develp branch and start with some work under the engine cover?

**Comment by splitt3r** [comment]
Great idea. Ref https://github.com/nextcloud/server/issues/7315
