### ISSUE TITLE
[Feature Request] Limit amount of voters

### ISSUE THREAD

**Issue by hw-p** [nextcloud/polls#2564]
Is it possible to add limit, how many people can vote?

**Comment by dartcafe** [comment]
Nearly everything is possible. But please fill out the form, which is offered for a [feature request](https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=feature_request.md).

**Comment by hw-p** [comment]
I am sorry sir.

**Comment by dartcafe** [comment]
Nix "Sir". 😉 There is a reason, why we want the forms to be used. Understanding the use case is essential for a good implementation and to be able to compare value and effort.
