### ISSUE TITLE
Error: Return type of OCA\Polls\Db\Log::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed

### ISSUE THREAD

**Issue by dell-mic** [nextcloud/polls#2565]
## What is going wrong? What did you observe?
**Describe the bug**

Since installing the polls app I observe error logs similar to the following on my nextcloud instance:
```
Error: Return type of OCA\Polls\Db\Log::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at [...]/apps/polls/lib/Db/Log.php#84
```
Errors seem getting logged for different classes' `jsonSerialize()` methods.

However, I did not observe any user facing bugs when using the app (tested with one poll only so far)

**Steps to reproduce the behavior**
1. Install app
2. Check system logs

**Add a screenshot of the misbehavior**

n/a

## How should it work?
**What you expected to happen?**

No error logs related to polls app.

## Information about your polls installation
**Polls version:** 3.7.0

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.4

<details>
<summary>List of activated apps</summary>

- accessibility: 1.10.0
- activity: 2.16.0
- bruteforcesettings: 2.4.0
- circles: 24.0.1
- cloud_federation_api: 1.7.0
- comments: 1.14.0
- contactsinteraction: 1.5.0
- dashboard: 7.4.0
- dav: 1.22.0
- deck: 1.7.1
- federatedfilesharing: 1.14.0
- federation: 1.14.0
- files: 1.19.0
- files_downloadactivity: 1.13.0
- files_external: 1.16.1
- files_linkeditor: 1.1.11
- files_markdown: 2.3.6
- files_pdfviewer: 2.5.0
- files_rightclick: 1.3.0
- files_sharing: 1.16.2
- files_trashbin: 1.14.0
- files_versions: 1.17.0
- files_videoplayer: 1.13.0
- firstrunwizard: 2.13.0
- logreader: 2.9.0
- lookup_server_connector: 1.12.0
- nextcloud_announcements: 1.13.0
- notifications: 2.12.0
- oauth2: 1.12.0
- occweb: 0.1.0
- password_policy: 1.14.0
- photos: 1.6.0
- polls: 3.7.0
- privacy: 1.8.0
- provisioning_api: 1.14.0
- ransomware_protection: 1.13.0
- recommendations: 1.3.0
- serverinfo: 1.14.0
- settings: 1.6.0
- sharebymail: 1.14.0
- survey_client: 1.12.0
- systemtags: 1.14.0
- text: 3.5.1
- theming: 1.15.0
- twofactor_backupcodes: 1.13.0
- twofactor_totp: 6.4.0
- updatenotification: 1.14.0
- user_status: 1.4.0
- viewer: 1.8.0
- workflowengine: 2.6.0

</details>
<details>
<summary>Nextcloud Configuration</summary>

</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version: 10.5.16
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0 (8.1.7)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Device:** 
- [ ] PC
- [x] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [x] Chrome version: 104
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

See above 

</details>

<details>
<summary>Browser console log</summary>

n/a

</details>

<details>
<summary>Other browser logs</summary>

n/a
</details>

**Comment by dartcafe** [comment]
Thanks. Error is thrown since php 8.1

**Comment by dartcafe** [comment]
Unfortunately, the error is not thrown here. I added annotations and hope, that this will fix it.

**Comment by dell-mic** [comment]
I can report back after the next upgrade including this fix ;)
