### ISSUE TITLE
[Feature Request] Limit amount of voters

### ISSUE THREAD

**Issue by hw-p** [nextcloud/polls#2569]
## Describe the goal you'd like to achieve
As a poll owner i want to set max limit to amount of poll participants. For example maximal 500 people can take poll.

## Describe possible solutions
set max limit to poll participants, when limit is reached - poll should be closed.

## Additional context
![image](https://user-images.githubusercontent.com/73251155/187619945-5dc5eaaf-88e0-4e93-9d6e-0dbe4b4ad3f3.png)

**Comment by dartcafe** [comment]
Thanks for readding it, Sir. ;-) 

But the use case is still not clear to me. What is a voter in your case? 
* Does every voter count as voter, regardless of his decision (yes/no,maybe)? 
* Which use case is addressed here? Why does this add a value to the app. Unfortinately you skipped the "why"-section of the user story.

**Comment by hw-p** [comment]
I am sorry, I dont think that far. 

 - Does every voter count as voter, regardless of his decision (yes/no,maybe)? 
 - Which use case is addressed here? Why does this add a value to the app. Unfortinately you skipped the "why"-section of the user story.

 For my case /which not means, that is good idea/ will be best: after X Yes Answers close the poll. - misusing it as reservation for intern event. But it will be nice to set max amount of voters - For example, I need to get answer for question from 500 people to use it as representative sample.

**Comment by dartcafe** [comment]
Ah, OK. But why not limiting the yes votes per option? Any other vote will get blocked, if the threshold is reached, unless someone removes his yes vote. 

Since all votes are registered directly, immediate closing is not recommented, because it would block the last voter, even if he immediately wants to correct his answer.

Automatic closing is only supported for the set closing time.

**Comment by hw-p** [comment]
or at least drawing thick red line after X votes . Sorry I am not program architect and I can not thik that far as you. But definitelly appreciate your answers and time.

**Comment by dartcafe** [comment]
Just try the option. In the end the result is, what you probably expect, no one can add a vote after the threshold is reached.

Maybe the apperance is different from what you expect.

**Comment by hw-p** [comment]
That is exactly what I want. After X Votes, dont allow other to vote. Max amount of voters for this poll reached.

**Comment by dartcafe** [comment]
I understand you right, the exiting option fits your needs? If yes, you may close this issue.
