### ISSUE TITLE
cannot see public user names in vote overview for predefined options

### ISSUE THREAD

**Issue by fajabird** [nextcloud/polls#2570]
## What is going wrong? What did you observe?
votes on predefined options will not show the user-name while suggestions do.

A clear and concise description of what is wrong.

**Steps to reproduce the behavior**
1. create new poll
2. add some options and enable "allow suggestions"
3. share public link to a test user
4. test user: open link and add own suggestion + pick one predefined vote
5. See error
predefined vote is marked as votes but no username is displayed
suggestion has the username who created it

**Add a screenshot of the misbehavior**

## How should it work?
I expect that all votes (if poll is not to anonymous) will show usernames so I know who picked what option

A clear and concise description of

## Information about your polls installation
**Polls version:** (see apps page)

**Fresh installation or update from a prior version (from which one)?**

- [x] First time install
- [ ] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [x] MySql version:
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
I don't understand your request. Could you explain, what you expect. Maybe with a mockup.

**Comment by fajabird** [comment]
sure... hopefully that screenshot helps:

here is a poll configured as stated above, i.e. public link and suggestions are allowed, although the point with the suggestions is actually not relevant - it just shows the difference:

![grafik](https://user-images.githubusercontent.com/1955116/187891171-fce47e94-eb86-4423-8945-767d54701aa3.png)

- first item has no votes yet
- items 2-5 have a single vote
- items 6 and 7 are suggestions with a vote

this overview will only show the names of the people (the circles on the right side) that created a suggestion - but I would also like to see who voted for what. 

Does it help?

**Comment by fajabird** [comment]
closing myself - just found the Table-View button finaly.

**Comment by fajabird** [comment]
see above
