### ISSUE TITLE
Thousands of requests per second, is this expected?

### ISSUE THREAD

**Issue by solracsf** [nextcloud/polls#2582]
## What is going wrong? What did you observe?
**Describe the bug**

Thousands of requests per second (here a very tiny extract):

```
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/poll/101/watch?offset=1662626038 HTTP/1.1" 304
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631342941 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631342585 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631342713 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/poll/101/watch?offset=1662626038 HTTP/1.1" 304
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343423 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343033 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343135 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/s/zISfP5LKE8wYP0tH/watch?offset=1662626038 HTTP/1.1" 304
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/poll/101/watch?offset=1662626038 HTTP/1.1" 304
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343476 HTTP/1.1" 200
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343930 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343623 HTTP/1.1" 200
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/s/56GIrUMtXiYILYuK/watch?offset=1662626038 HTTP/1.1" 304
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631343883 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/poll/101/watch?offset=1662626038 HTTP/1.1" 304
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631344430 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631344109 HTTP/1.1" 200
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/poll/101/watch?offset=1662626038 HTTP/1.1" 304
46.247.240.36 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631344358 HTTP/1.1" 200
80.15.122.66 - [08/Sep/2022:12:02:22 +0200] "GET /apps/polls/settings/app?time=1662631344872 HTTP/1.1" 200
```

## Information about your polls installation
**Polls version:** (see apps page)

3.7.0

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version:

**How did you install this version?(Appstore or describe installation)**

- [ ] Installed from the appstore
- [x] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

### Client configuration
**Device:** 
- [ ] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
Not intended. I have to inspect. Turn off long polling in the admin section meanwhile and switch to periodic polling.

**Comment by solracsf** [comment]
22.2.10

**Comment by dartcafe** [comment]
ATM I don't understand, why this happens. For some reason the server part immediately responses to the request, instead of periodically check, if there is a new log entry in the db and response then or after a timeout of 30 seconds. 

I also noticed this behvior once, but only once with NC24.

It is also confusing, that the watch service is called and the settings request is sent then three times. 

> Turning off long polling "solves" this. Can't `notify_push` app help here, if detected?

This app is for clients and I don't know it.

Something like https://github.com/nextcloud/push would be handy, but it is archived.

**Comment by dartcafe** [comment]
Still digging. Could you provide some information from the console log with activated debug info?

**Comment by solracsf** [comment]
I'll try it ASAP.
