### ISSUE TITLE
"Call to a member function getTimestamp() on null" in Polls Autoreminder

### ISSUE THREAD

**Issue by gohrner** [nextcloud/polls#2586]
## What is going wrong? What did you observe?

Got a notification from my Nextcloud instance today:

```text
Error: Call to a member function getTimestamp() on null in /var/www/nextcloud/apps/polls/lib/Service/MailService.php:173
Stack trace:
#0 /var/www/nextcloud/apps/polls/lib/Cron/AutoReminderCron.php(49): OCA\Polls\Service\MailService->sendAutoReminder()
#1 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(79): OCA\Polls\Cron\AutoReminderCron->run(NULL)
#2 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(95): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#3 /var/www/nextcloud/cron.php(151): OCP\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#4 {main}
```

It's most likely related to a public date poll I created two days ago. I assume someone tried to vote and something went wrong.

Unfortunately, I don't know who or what exactly triggered it.

## Information about your polls installation
**Polls version:** 3.4.2

**Fresh installation or update from a prior version (from which one)?**
- [x] Update from a prior version
  Version number of the previous version: unknown - Polls is already installed since a few years at least.

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Server configuration detail
 **Operating system:** Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
 **Webserver:** Apache/2.4.38 (Debian) (apache2handler)
 **Database:** mysql 10.3.34
 **PHP version:** 7.3.31-1~deb10u1
 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium,
session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom,
mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql,
pdo_pgsql, pgsql, apc, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sysvmsg,
sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache
 **Nextcloud version:** 23.0.8 - 23.0.8.1
 **Updated from an older Nextcloud/ownCloud or fresh install:** 
 **Where did you install Nextcloud from:** unknown
 <details><summary>Signing status</summary>
 Array
(
)
 </details>
 <details><summary>List of activated apps</summary>
 ```
Enabled:
- accessibility: 1.9.0
- activity: 2.15.0
- appointments: 1.12.7
- calendar: 3.3.2
- circles: 23.1.2
- cloud_federation_api: 1.6.0
- comments: 1.13.0
- contacts: 4.2.0
- contactsinteraction: 1.4.0
- dashboard: 7.3.0
- dav: 1.21.0
- federatedfilesharing: 1.13.0
- federation: 1.13.0
- files: 1.18.0
- files_pdfviewer: 2.4.0
- files_rightclick: 1.2.0
- files_sharing: 1.15.0
- files_trashbin: 1.13.0
- files_versions: 1.16.0
- files_videoplayer: 1.12.0- firstrunwizard: 2.12.0
- forms: 2.5.1
- impersonate: 1.10.0
- integration_zammad: 1.0.4
- logreader: 2.8.0
- lookup_server_connector: 1.11.0
- mail: 1.12.8
- nextcloud_announcements: 1.12.0
- notifications: 2.11.1
- oauth2: 1.11.0
- password_policy: 1.13.0
- photos: 1.5.0
- polls: 3.4.2
- privacy: 1.7.0
- provisioning_api: 1.13.0
- recommendations: 1.2.0
- richdocuments: 5.0.7
- serverinfo: 1.13.0
- settings: 1.5.0
- sharebymail: 1.13.0
- spreed: 13.0.8
- support: 1.6.0
- survey_client: 1.11.0
- systemtags: 1.13.0
- text: 3.4.1
- theming: 1.14.0
- twofactor_backupcodes: 1.12.0
- updatenotification: 1.13.0
- user_status: 1.3.1
- viewer: 1.7.0
- weather_status: 1.3.0
- workflowengine: 2.5.0
Disabled:
- admin_audit
- encryption
- files_external
- integration_whiteboard: 0.0.14
- user_ldap
 ```
</details>
 <details><summary>Configuration (config/config.php)</summary>
 ```
{
"instanceid": "***REMOVED SENSITIVE VALUE***",
"passwordsalt": "***REMOVED SENSITIVE VALUE***",
"secret": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
"nextcloud.ohrner.net"
],
"datadirectory": "***REMOVED SENSITIVE VALUE***",
"dbtype": "mysql","version": "23.0.8.1",
"overwrite.cli.url": "https:\/\/nextcloud.ohrner.net\/",
"htaccess.RewriteBase": "\/",
"dbname": "***REMOVED SENSITIVE VALUE***",
"dbhost": "***REMOVED SENSITIVE VALUE***",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"dbuser": "***REMOVED SENSITIVE VALUE***",
"dbpassword": "***REMOVED SENSITIVE VALUE***",
"installed": true,
"memcache.local": "\\OC\\Memcache\\APCu",
"memcache.locking": "\\OC\\Memcache\\Redis",
"redis": {
"host": "***REMOVED SENSITIVE VALUE***",
"port": 6379
},
"mail_smtpmode": "smtp",
"mail_smtpauthtype": "PLAIN",
"mail_from_address": "***REMOVED SENSITIVE VALUE***",
"mail_domain": "***REMOVED SENSITIVE VALUE***",
"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
"mail_smtpport": "25",
"mail_smtpsecure": "tls",
"maintenance": false,
"theme": "",
"loglevel": 0,
"mail_smtpauth": 1,
"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
"mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>
 **Cron Configuration:** Array
(
[backgroundjobs_mode] => cron
[lastcron] => 1662840006
)
  **External storages:** files_external is disabled
 **Encryption:** no
 **User-backends:** 
* OC\User\Database
  **Talk configuration:** 
 STUN servers
* exklave.ohrner-it.com:3478
TURN servers
* turn:exklave.ohrner-it.com - udp,tcp
 Signaling servers (mode: internal):
* no custom server configured
  **Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome
104.0.5112.101 Safari/537.36


## Logs

Server log excerpt:

```json
{"reqId":"yPP2VLd0rokHrGvJzPg7","level":0,"time":"2022-09-09T13:30:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 6571","userAgent":"--","version":"23.0.8.1"}
{"reqId":"yPP2VLd0rokHrGvJzPg7","level":0,"time":"2022-09-09T13:30:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Polls\\Cron\\AutoReminderCron job with ID 6571","userAgent":"--","version":"23.0.8.1"}
{"reqId":"yPP2VLd0rokHrGvJzPg7","level":3,"time":"2022-09-09T13:30:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined offset: 0 at /var/www/nextcloud/apps/polls/lib/Service/MailService.php#173","userAgent":"--","version":"23.0.8.1","exception":{"Exception":"Error","Message":"Undefined offset: 0 at /var/www/nextcloud/apps/polls/lib/Service/MailService.php#173","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/polls/lib/Service/MailService.php","line":173,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 0","/var/www/nextcloud/apps/polls/lib/Service/MailService.php",173,[[{"__class__":"OCA\\Polls\\Db\\Poll","id":18}],1662730201,[],{"__class__":"OCA\\Polls\\Db\\Poll","id":18},[]]]},{"file":"/var/www/nextcloud/apps/polls/lib/Cron/AutoReminderCron.php","line":49,"function":"sendAutoReminder","class":"OCA\\Polls\\Service\\MailService","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Polls\\Cron\\AutoReminderCron","type":"->","args":[null]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":151,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"yPP2VLd0rokHrGvJzPg7","level":3,"time":"2022-09-09T13:30:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Call to a member function getTimestamp() on null","userAgent":"--","version":"23.0.8.1","exception":{"Exception":"Error","Message":"Call to a member function getTimestamp() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/polls/lib/Cron/AutoReminderCron.php","line":49,"function":"sendAutoReminder","class":"OCA\\Polls\\Service\\MailService","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Polls\\Cron\\AutoReminderCron","type":"->","args":[null]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":151,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/polls/lib/Service/MailService.php","Line":173,"CustomMessage":"--"}}
```

**Comment by dartcafe** [comment]
Thanks for the report. If your version information is correct, I recommet updating first to 3.7 and check if the error still occurs.

**Comment by gohrner** [comment]
I'd prefer to use the Polls version which can be installed through the "Apps" section instead of manually installing some version.

3.4.2 is the latest version available for installations there - at least no update is being offered:
![image](https://user-images.githubusercontent.com/26199042/189518135-fa1965d1-f394-4618-8c43-32b020c289da.png)

("All Apps sind aktuell." means "All Apps are up to date.")

Maybe the new Polls version is not compatible with my server?

* Nextcloud 23.0.9 (latest maintenance release)
* Debian 10 Buster (will soon be updated) x64 with PHP 7.3
(see installation details above)

May there be any other reason why no upgrade is being offered?

**Comment by dartcafe** [comment]
Ah, OK. I didn't recognize, you are still running PHP 7.3. Polls doesn't support PHP 7.3 anymore. 

ATM I have no chance to reproduce this with an acceptable effort.

**Comment by gohrner** [comment]
Ok, thanks in any case.

I have to upgrade to Debian 11 soon anyway (Debian 10 just fell into limited LTS support this weekend), which ships with PHP 7.4.

I just hope Polls won't require PHP 8 anytime soon then. ;)

**Comment by dartcafe** [comment]
ATM, there is no concrete plan to drop PHP 7.4, but it will happen.
