### ISSUE TITLE
Drop support?

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#259]
There should be a general decision, on which fork we concentrate future development and support. 

As NC and OC get more and more incompatible, it becomes difficult to support both forks. So we should state clear, which of them will be supported in the future. The last experience with the migrations is not a good one.
Vote here: https://nc12.yagst.de/index.php/apps/polls/poll/gi5jJL5InqNqZ77a

Also we should state clear which versions of the supported fork are subject of the development and support. 
Vote here: https://nc12.yagst.de/index.php/apps/polls/poll/ewL2Txz2fXAw8ny8

I tried a new tool for the polls. 😆 Poll is open until 12/16/2017

**Comment by splitt3r** [comment]
Its's Nextcloud :grin:

**Comment by dartcafe** [comment]
Brief summary, so far: 

- 7 participants, 
- 0 votes for owncloud, 
- 7 for nextcloud.

https://nc12.yagst.de/index.php/apps/polls/poll/gi5jJL5InqNqZ77a

- 5 participants
- 5 votes for current version
- 4 votes for current - 1 and 1 against
- 4 votes against current version -2 and 1 maybe

This means, that for the moment we will continue support for oC 10, NC12 and NC11. NC11 support will be dropped in the moment NC13 is released (expected for the end of this year). As soon, as oC 11 will be released, support for oC will drop. 

Correct?

**Comment by splitt3r** [comment]
https://www.techandme.se/owncloud-10-0-4-last-vm-version/ an interesting article realted to this issue 😁

**Comment by splitt3r** [comment]
We should also remove the Nc 10 & Nc 11 versions of the app from the [store](https://apps.nextcloud.com/apps/polls) so they aren´t around anymore.

**Comment by tflidd** [comment]
> We should also drop support for php 5.6 (It´s old and slow and nearly end of life).

It looks like NC 13 will be the last supported version for PHP 5.6:
https://github.com/nextcloud/server/issues/7368

**Comment by splitt3r** [comment]
https://dev.to/adamculp/stop-the-pain-upgrade-to-php-7-c40 yep but we could drop it earlyer :)

**Comment by splitt3r** [comment]
If we continue to support Nc 12 we need to drop the migrations for now :/ https://github.com/nextcloud/polls/tree/develop-0.9/lib/Migration. We could also make 0.8.X => Nc 12 and >0.9 => Nc 13+ but that would mean backports like the core does  :confused:.

**Comment by Croydon** [comment]
> We should also remove the Nc 10 & Nc 11 versions of the app from the store so they aren´t around anymore.

What benefits has this? Some people aren't able to switch instantly to new releases, you prevent them from using this extension easily for no good reason I can see right now.

**Comment by splitt3r** [comment]
Because they use an old unsupported version which could contain bugs. To secure your personal data your Nc instance should really be up to date. But get your point :neutral_face:

**Comment by dartcafe** [comment]
I second splitt3r.  Because of changing APIs of the core, security reasons, etc. it is recommended (better: essential) to always upgrade to the supported versions of the core. And to be honestly, upgrades are no more a pain in the ass at least since version 12.

Regarding for polls, we have to decide to focus to keep the amount of work for developing and testing limited. 

If there are people, who cannot instantly upgrade to supported versions of the server, they will run in the same problem not only for the polls app. But everybody is free to fork this repo and continue devolping for his own needs.

**Comment by Croydon** [comment]
To clearify my position here: Drop support for these old NC versions in development, just don't delete the old versions from the app store.

**Comment by splitt3r** [comment]
Yep. But by deleting the packages we can help to force people to stay up to date 😄

**Comment by Croydon** [comment]
No, you are forcing people not to use this app.

**Comment by splitt3r** [comment]
The only way to force some people to update their software ^^ but anyway we´ll let the packages online.

**Comment by v1r0x** [comment]
Just a FYI from my side:
I lost my VM including signing keys for both NC and OC. I already created a new one for NC, but since we want to drop/dropped OC support, I'll close this one, update the readme and close all OC related issues.

Reopen if you disagree.
