### ISSUE TITLE
Edit own item fails if Name differ in whitespaces in public polls

### ISSUE THREAD

**Issue by RainerBraunschweig** [nextcloud/polls#261]
### Steps to reproduce
1. Make an entry and vote in a public poll
2. call again same public poll to modify your vote
3. type in your name with a different count of whitespaces between first name and surname and vote again

### Expected behaviour
the old entry should be replaced

### Actual behaviour
the old and the new vote apear and the owner of the poll will be confused.

It would be great to have an ability to modify votes in a public poll.

**Comment by dartcafe** [comment]
It is actually no good solution just to enter a name without a ckeck, if the username exists. In this way anybody can change any poll entry. We have to build an abstraction with checks on the username and an individual hash for every participant, so he canndirectly edit his own vote. Regarding #223

**Comment by dartcafe** [comment]
Reenterin poll will be possible via public link for invited users
