### ISSUE TITLE
Error saving vote

### ISSUE THREAD

**Issue by RalfAlbers** [nextcloud/polls#2612]
## What is going wrong? What did you observe?
We have an public anonymous hidden Poll (Version 3.8.1) on NC (Version 24.0.5).
After given a Name for the vote, you are unable to check any option. You are getting always the error "Beim Speichern der Stimme ist ein Fehler aufgetreten", so something like "Error saving our vote". 
When you've enabled debug mode in our browser, you can see this:

"request": {
          "method": "PUT",
...
          "url": "https://MY-DOMAIN/apps/polls/s/CaoVa4ccdvy9AaG6/vote",
          postData": {
            "mimeType": "application/json",
            "params": [],
            "text": "{\"optionId\":57,\"setTo\":\"yes\"}"
          }
        },
        "response": {
          "status": 401,
...
          "statusText": "Unauthorized",
          "content": {
            "mimeType": "application/json; charset=utf-8",
            "size": 39,
            "text": "{\"message\":\"denied permission comment\"}"
          }
        },
}

I've shorten the data a bit.
I can reproduce this with different browser.

## How should it work?
Successfully save the vote(s) from any user :-)

## Information about your polls installation
**Polls version:** 3.81

**Fresh installation or update from a prior version (from which one)?**
- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version:
  I've installed the Polls for years, but the last 2 years we don't have used Polls

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.5

<details>
<summary>List of activated apps</summary>
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.1
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - deck: 1.7.1
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - forms: 2.5.1
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.8.1
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - sharerenamer: 3.0.1
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - appointments: 1.12.8
  - circles: 22.1.1
  - dashboard: 7.0.0
  - encryption: 2.9.0
  - files_retention: 1.13.2
  - files_trackdownloads: 1.11.0
  - firstrunwizard: 2.4.0
  - registration: 1.5.0
  - suspicious_login: 4.2.0
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
</details>
<details>
<summary>Nextcloud Configuration</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "MY-DOMAIN",
            "MY-IP"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "logrotate_size": "104847600",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "theme": "",
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "de"
    }
}

</details>

**Comment by zimmersi** [comment]
same here.
Polls v3.8.1
NC v24.0.5

it is not possible to vote for a private poll with public link when comments are disabled. 
So, as a workaround, you have to activated the "Allow comments" feature.

**Comment by zimmersi** [comment]
seems to be fixed with polls 3.8.2
see here #2600 and #2608
