### ISSUE TITLE
Copying dates is sometimes not working

### ISSUE THREAD

**Issue by Ziesie1** [nextcloud/polls#2625]
## What is going wrong? 
If I try to duplicate a date daily (or weekly) in the poll app, it sometimes do not create a correct date option. Instead of a whole day it only produce a date with timing information from 00:00 to 23:00.

## Steps to reproduce the behavior:
I start with the 22th of october 2022 and copy it 10 times.
![image](https://user-images.githubusercontent.com/47595958/195136822-9a56c253-35df-469f-892b-f107b22ea886.png)

Thereafter, I get the following result:
![image](https://user-images.githubusercontent.com/47595958/195137053-1d014923-63c2-4062-ad9a-c13c2ab77973.png)

This problem only appears on the 29th / 30th of october. Before and after, I can create copies without a problem.
If I delete the false options (dates) and try to create the 30th of october manually, the copy mechanic works well.

## How should it work?
It should create options with hole days only, not date times (see images above).

## Information about your polls installation
**Polls version:** 3.8.2

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: 3.8.1

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.6 

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [x] MySql version: 10.5.16
- [ ] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [ ] Firefox version:
- [x] Chrome version: 105.0.5195.125
- [ ] Safari version:
- [ ] Other (add name and version):

**Comment by dartcafe** [comment]
That bug appears only on dates where summer time starts or end, because the event is defined as an event, which has a 24 hour duration. In this case from 00:00 to 23:00 = 24 hours.

Since the change is made in the backend, the information of the clients timezone is unknown for the server.

This is still a todo.

**Comment by Coernel82** [comment]
Cannot confirm that this is only related to day light savings start or end:
I created an event for Friday 4th of August. The change of daylight savings always is on Sundays. I wanted to increment the 4th of August weekly in increments of 2 weeks for 8 events.
Not working. For the 11th of August this is working though.

**Comment by dartcafe** [comment]
It doesn't depend on the day of week. When the original date lies before the day light saving date and the cloned after, this happens.
