### ISSUE TITLE
improve call to action in public registration modal

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/polls#2627]
I'd like to suggest a few improvements to the prompts in `src/js/components/Poll/PublicRegisterModal.vue`. The current language is functionally useful, yet it seems a bit wordy and awkward to this native English speaker.

Original/existing (on the `master` branch as of commit 98fc2782df8f7a9a3e6751197c4545d59bd98c88):

![01 original public register modal](https://user-images.githubusercontent.com/50639/195397682-9d44411f-aeb9-42a6-b2cb-91885bb0f1f0.png)

Proposed:

![02 updated public register modal](https://user-images.githubusercontent.com/50639/195397907-4a194ec7-e1fe-456c-a06b-c25da0e1a721.png)

I suggest these tooltips:

* **Guest** - Participate in this poll as a guest without registering or logging in.
* **Name** - Provide your name or nickname to let other participants know who you are. You may include your preferred pronouns here as well. You can change your name later.
* **Email** - If you provide an email address you will receive poll reminders and a personal link to update or review your responses. You can change or remove your email address later.

**Comment by dartcafe** [comment]
@meonkeys Thanks for your suggestions. I updated the registration screen, but rermoved the tooltips. 
![grafik](https://user-images.githubusercontent.com/26707476/205485149-f5e7fad4-46a3-4e10-b8e7-6c8ed902d03a.png)
![grafik](https://user-images.githubusercontent.com/26707476/205485236-2df9cc7b-1b3c-4cfb-a9d2-3ac37d1206cb.png)
![grafik](https://user-images.githubusercontent.com/26707476/205485266-a479a966-ba59-4406-8817-624e2b264ce6.png)

**Comment by meonkeys** [comment]
Nice! I added a couple of comments on the pull request. I like the use of placeholders, too,

**Comment by dartcafe** [comment]
Thanks a lot!
