### ISSUE TITLE
[timezone] Times in Firefox differ from those in Chromium

### ISSUE THREAD

**Issue by hamoid** [nextcloud/polls#2635]
## What is going wrong? What did you observe?

Displayed times differ between browsers in the same computer.

**Steps to reproduce the behavior**

To reproduce I only open Polls in Firefox and Chromium.

**Add a screenshot of the misbehavior**

![image](https://user-images.githubusercontent.com/108264/196673662-b72838d7-cb62-4f50-8f34-47dfad4b4dee.png)

## How should it work?

The local times are used in all browsers.

## Information about your polls installation
**Polls version:** 3.8.2

**Fresh installation or update from a prior version (from which one)?**
- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: Unknown

**How did you install this version?(Appstore or describe installation)**
- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 24.0.6

<details>
<summary>List of activated apps</summary>

Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.2
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.8.2
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0

</details>
<details>
<summary>Nextcloud Configuration</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "yes.hamoid.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/yyy.xxx.com",
        "dbtype": "pgsql",
        "version": "24.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "default_phone_region": "DE",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_sendmailmode": "pipe",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [ ] MariaDB version:
- [x] PostgreSQL version: 12.12
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [x] 7.4
- [ ] 8.0

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: 106.0
- [x] Chromium version: 106.0
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

I'll add if needed

**Comment by dartcafe** [comment]
See #995

**Comment by hamoid** [comment]
Thank you. Too bad the answer that seems to point at the issue links to a deleted GitHub issue :(
https://github.com/nextcloud/polls/issues/995#issuecomment-652595065

I know I can check the timezone. I wish I could specify the timezone when creating the poll. When I realized the date was wrong I shifted all the options by 2 hours accidentally deleting people's answers.

**Comment by hamoid** [comment]
Seems to be this Firefox setting: `privacy.resistFingerprinting` in `about:config`. That makes Firefox report the UTC time zone.

**Comment by hamoid** [comment]
@dartcafe Any chance the timezone could be selected by the user when creating the poll? It could default to whatever the browser suggests, but this would be easier to notice and correct.

**Comment by dartcafe** [comment]
Something is planned but it is an UX challenge.
