### ISSUE TITLE
export is not working because external user id from votes table is missing in shares table

### ISSUE THREAD

**Issue by zimmersi** [nextcloud/polls#2636]
## What is going wrong? What did you observe?
**Describe the bug**

We are using our Nextcloud instance the first time for a public poll with around 300 external attendees. The creator of the poll has informed me that it is not possible to export the results. That's why I have checked the database and found that there are several user ids in the votes table that are missing in the shares table and this causes the export to stop working.

**Steps to reproduce the behavior**

have not found a way yet. sorry. but votes can be found with following sql statement
SELECT * FROM oc_polls_votes AS votes WHERE votes.user_id LIKE 'ex_%' AND NOT EXISTS (SELECT * FROM oc_polls_share AS shares WHERE shares.user_id = votes.user_id)

**Add a screenshot of the misbehavior**

## How should it work?
**What you expected to happen?**

Maybe the export should ignore these votes?!

## Information about your polls installation
**Polls version:** (see apps page)
3.8.2

**How did you install this version?(Appstore or describe installation)**

- [ x ] Installed from the appstore

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
24.0.6

<details>
<summary>List of activated apps</summary>

```
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ x ] MariaDB version: 10.5.17

**PHP version:**
- [ x ] 7.4

### Client configuration
**Device:** 
- [ x ] PC

**Browser:** 

- [ x ] Firefox version:
- [ x ] Chrome version:

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
[index] Fehler: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*polls_share` WHERE (`poll_id` = :dcValue1) AND (`user_id` = :dcValue2)";  at <<closure>>

 0. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 363
    OCP\AppFramework\Db\QBMapper->findOneQuery()
 1. /var/www/nextcloud/apps/polls/lib/Db/ShareMapper.php line 106
    OCP\AppFramework\Db\QBMapper->findEntity()
 2. /var/www/nextcloud/apps/polls/lib/Service/UserService.php line 134
    OCA\Polls\Db\ShareMapper->findByPollAndUser()
 3. /var/www/nextcloud/apps/polls/lib/Service/MailService.php line 82
    OCA\Polls\Service\UserService->evaluateUser()
 4. /var/www/nextcloud/apps/polls/lib/Service/PollService.php line 384
    OCA\Polls\Service\MailService->resolveEmailAddress()
 5. /var/www/nextcloud/apps/polls/lib/Controller/PollController.php line 163
    OCA\Polls\Service\PollService->getParticipantsEmailAddresses()
 6. /var/www/nextcloud/apps/polls/lib/Controller/BaseController.php line 59
    OCA\Polls\Controller\PollController->OCA\Polls\Controller\{closure}("*** sensitive parameters replaced ***")
 7. /var/www/nextcloud/apps/polls/lib/Controller/PollController.php line 163
    OCA\Polls\Controller\BaseController->response()
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Polls\Controller\PollController->getParticipantsEmailAddresses()
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
10. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
11. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
12. /var/www/nextcloud/lib/base.php line 1030
    OC\Route\Router->match()
13. /var/www/nextcloud/index.php line 36
    OC::handleRequest()
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
@zimmersi Thanks for reporting. Find the fixed version in https://github.com/nextcloud/polls/releases/tag/v3.8.3

**Comment by zimmersi** [comment]
great, thx!
