### ISSUE TITLE
Hide results while poll is open

### ISSUE THREAD

**Issue by PieterHollevoet** [nextcloud/polls#265]
An option to make a poll completely anonymous by not showing the choices made by other users.

**Comment by dartcafe** [comment]
For the moment I would not vote for this, because the use case is not clear to me. We have anonymous polls. I cannot see the advantage. One more function to test in every release. And we need some admin functions I guess.

**Comment by Mannshoch** [comment]
I think it should be possible to vote for people which do not have Nextcloud account, like doodle allows it.
If the admin allow anonym user to add his vote, he should be able to set up an E-Mail address as a required field.

**Comment by splitt3r** [comment]
Please open another issue for your request.

**Comment by b-pfl** [comment]
> For the moment I would not vote for this, because the use case is not clear to me. We have anonymous polls. I cannot see the advantage. One more function to test in every release. And we need some admin functions I guess.

Well, this would be one option to select when setting up the poll. When using this tool to ask people to vote without biassing them, the option to hide the results (and also the comments) would help a lot.

**Comment by Refhi** [comment]
> > For the moment I would not vote for this, because the use case is not clear to me. We have anonymous polls. I cannot see the advantage. One more function to test in every release. And we need some admin functions I guess.
> 
> Well, this would be one option to select when setting up the poll. When using this tool to ask people to vote without biassing them, the option to hide the results (and also the comments) would help a lot.

I concur very much : when we want to have unbiased pools (scientific studies or opinion studies for example) it would be very useful

**Comment by MeCias** [comment]
Would like to see this as an option as well. People tend to vote last if you wanna find a common date for something. The last person just pics one date of  6 remaining options and you have no alternative if something goes wrong with the last date. A anonymous vote where just the admin can see the result would be nice.
