### ISSUE TITLE
Decrease insane JavaScript amount/size

### ISSUE THREAD

**Issue by ltGuillaume** [nextcloud/polls#2650]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

The total size of the JavaScript files currently included is imho insane: 14MB, not even including the size of *.js.map, which is 31MB.

Are you perhaps including an insane amount of dependencies that are never used, or what's going on here?

### Describe possible solutions

Check what dependencies are actually necessary for this thing to work and strip everything else.

**Comment by dartcafe** [comment]
> Are you perhaps including an insane amount of dependencies that are never used, or what's going on here?

Not that I am aware of. Any hints?

**Comment by ltGuillaume** [comment]
I am not versed in webpack strategies, but I imagine adding the following would help a lot:

```
optimization: {
  splitChunks: {
    chunks: 'all'
  }
}
```

Source (with other tips for optimization): https://news.shardlabs.io/how-to-drastically-reduce-your-bundle-size-and-load-time-in-vue-js-54370d513fdf

**Comment by dartcafe** [comment]
> > Are you perhaps including an insane amount of dependencies that are never used, or what's going on here?
> 
> Not that I am aware of. Any hints?

My question was regarding unused dependencies. Chunk splitting is already used.
