### ISSUE TITLE
Erroneous behavior of cursor when filling in email address

### ISSUE THREAD

**Issue by ltGuillaume** [nextcloud/polls#2651]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

_On mobile devices, tested in Bromite (Chromium-based) and Mull (Firefox Fennec-based)_

When entering your email address, the address is validated in realtime. This, however, causes erroneous behavior of the cursor while typing: after a validation, it jumps back to somewhere in the typed address. As a result, the following example address:
`some.example@email.address`
will turn into something like
`soexamem@adessdrailpleme`

### What did you expect, how polls should behave instead?

The cursor position should not be influenced by the validation process

### What steps does it need to replay this bug?

Enter or edit your email address as guest in a poll via the settings dropdown menu.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### Additional client environment information

I have a rather slow phone (due to its age), so this might have something to do with it. Regardless, the manipulation of the cursor position should never happen.

### NC version

Nextcloud 24 (Nextcloud Hub 2)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Should be solved after the last development (changing http requests and registration dialog).

**Comment by dartcafe** [comment]
@ltGuillaume I'll close that issue, because the behavior changed and the problem should be solved. If the problem still exists after the update, feel free to reopen this issue.
