### ISSUE TITLE
Remove orphaned entries after deleting poll

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#267]
We should do sth. like https://github.com/nextcloud/deck/blob/master/lib/Migration/UnknownUsers.php to remove all the orphaned entries and sth. like https://github.com/splitt3r/mindmaps/blob/feature/rework-js/lib/AppInfo/Application.php#L58-L76 so it doesn´t happen again.

**Comment by dartcafe** [comment]
Should be subject of the backend rework (especially, the classes rework)

**Comment by woodychuck** [comment]
Unsure if it is the same issue but we encountered problems when an LDAP user was offboarded but still had shares for others: the effect of this is that the other users (shared_with) cannot access their files anymore (browser error message: "This directory is unavailable, please check the logs or contact the administrator") and also cannot connect a new desktop client:

![image](https://user-images.githubusercontent.com/27004189/48257936-4309e180-e414-11e8-9e71-c3dced536b1f.png)

(ID 2281 is what I can still see as item_source in the table oc_share in the NC database)

**Comment by woodychuck** [comment]
@dartcafe oops, my bad, of course not. I completely overlooked that specific detail while looking for hints and issues on my specific problem which is NC core related. Sorry!
