### ISSUE TITLE
Thoughts about some tasks

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#268]
Some thoughts about nessecary changes in my point of view (incl. adopting some CRs): 
- create own user class, which gives posibility for 
  - seperating nc users from public users and checking user names (#223), 
  - identifying groups and users (#82),
  - creating individual links for public users, so they can change the votes, (#261), 
  - creating individual invitation for users and 
  - offer email notification even for public users
- generally optimization to the data scheme (#262, #255)
- rework of the create/edit page (#131, #136, #162, #211)
  - replace the date picker with jQuery date picker, as in core (#156), 
  - more functions for comfort (i.e. create series of dates, copying of dates, etc.) and 
  - enhance time selects (#201, #194)
- give the admins rights to delete, change polls
- Adding filters for organizing polls by using the sidebar (#228, #163)
- integrating in calendar app (#121),
- support notifications (#188)
- support circles (#204)
- Rework Email (#178)
- ...

**Comment by splitt3r** [comment]
A lot of work to do... But the result will be pretty awesome 💪

**Comment by v1r0x** [comment]
I agree with @splitt3r. Nice ToDo list

**Comment by dartcafe** [comment]
This issue make no more sense.... closing
