### ISSUE TITLE
Alternative appointments

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/polls#2684]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

We have the use case to choose 1 desired appointment ("yes") and e.g. two alternative appointments ("maybe"). We tried to restrict the poll with 'Limit "Yes" votes'.
When a user vote for 'yes' (fixed date) it is not possible to choose any alternative dates, because you can only choose a 'maybe' vote by first choosing 'yes' and then clicking again
It should be possible that you can still vote 'maybe' / no votes, even if you have reached the number of allowed yes votes.
Current workaround: We have to tell the participants to choose the alternative dates first and then the fixed date.

**Comment by dartcafe** [comment]
Thanks for contribution. This is a duplicate of #2387 and already on the to list but has no priority.
