### ISSUE TITLE
NC 13b3 regression: Mobile browsers can no longer scroll

### ISSUE THREAD

**Issue by nursoda** [nextcloud/polls#271]
### Steps to reproduce
1. Upgrade to NC13b3
2. Open a public poll in a mobile browser such as Brave on Android

### Expected behaviour
User should be able to scroll sideways to reach all selectable options.
### Actual behaviour
One cannot scroll sideways at all rendering all "bigger" polls inaccessible on mobile browsers:
![grafik](https://user-images.githubusercontent.com/8425483/34165920-d90c8e76-e4dd-11e7-9a9c-52ab946105e7.png)
There are rendering issues in the desktop version, too:
![grafik](https://user-images.githubusercontent.com/8425483/34165963-f371e39c-e4dd-11e7-8329-0ba335808066.png)

### Server configuration
**Nextcloud version:** 13b3
**Where did you install Nextcloud from:** Upgrade via admin/installer
**Signing status:** no errors
**Polls version:** 0.8.0

**Comment by dartcafe** [comment]
I had this issue too. This should be fixed in current master. Can you test?

**Comment by dartcafe** [comment]
Ah. No. Thought vertical scrolling was the problem, because this is fixed. Horizontal scrolling is still an issue. Did not recognize that. Thanks.

**Comment by dartcafe** [comment]
Umpf. Horizontal scrollbar is hidden from core for media screens up to 768px width. Added CSS directive to main.scss. @nursoda Can you test?

**Comment by dartcafe** [comment]
You can test here until db reset: https://nc13.yagst.de/index.php/apps/polls/poll/Ji7hO2zhnLX0VQRq

**Comment by nursoda** [comment]
As I said in bug https://github.com/nextcloud/polls/issues/272: This version looks great, a WAY BETTER presentation for mobile devices. No need to scroll horizontally ;-)
