### ISSUE TITLE
Dates far in the future are not stored correctly

### ISSUE THREAD

**Issue by oneindelijk** [nextcloud/polls#2710]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

As a test I added a date poll with some dates in the far future, ie I added 1/03/2059 which showed up as another date some 80 years earlier

### What did you expect, how polls should behave instead?

The date to be stored and displayed as entered

### What steps does it need to replay this bug?

1. Start a new date poll
2. Add an item, pick a date +20 Yrs in the future
3. Observe the added poll item

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

4.0.0

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 7.4

### Database engine

PostgreSQL

### Database Engine version or other Database

Postgres 11

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
The databese is configured to store timestamps as integer with a range up to 2147483647, which is equivalent to the datetime Tue Jan 19 2038 03:14:07 GMT+0000.
