### ISSUE TITLE
Cannot scroll page after clicking Cancel

### ISSUE THREAD

**Issue by ltguillaume** [nextcloud/polls#2712]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When you have a long poll description or always show the result list, a user cannot read the full description/see the results on a smaller screen after clicking the `Cancel` button. The page is only scrollable after filling in a name and pressing `OK`.

### What did you expect, how polls should behave instead?

Page should be scrollable after clicking `Cancel`, too.

### What steps does it need to replay this bug?

1. Create poll with a long description
2. Share the poll
3. Open the poll via the shared link and click `Cancel`
4. Try to scroll down

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

3.8.3

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 24 (Nextcloud Hub 2)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Is this still an issue? I could reproduce that before, but not anymore with the current release.

**Comment by ltGuillaume** [comment]
Currently, I'm stuck on 3.8.4 with a 32-bit OS, sry.

**Comment by dartcafe** [comment]
At least since Nextcloud 25 and the removal of the footer, I can't reproduce that anymore. Fell free to reopen, if this happens again.
