### ISSUE TITLE
Polls on android App doesn't appear

### ISSUE THREAD

**Issue by glama** [nextcloud/polls#2713]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

hi, 
After installing Polls in NextCloud works fine, but the option doesn't appear on NextCloud App (Android)

Thanks.

### What did you expect, how polls should behave instead?

Similar interface  as in browser.

### What steps does it need to replay this bug?

1.
Look in NextCloud Android App Menu or show how to access it.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 23 (Nextcloud Hub 1)

### PHP engine version

PHP 7.4

### Database engine

MySQL

### Database Engine version or other Database

 5.7.36 MySQL Community Server 

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Nextcloud Signing status

```shell
No logs, only on Android signed in.
```

**Comment by dartcafe** [comment]
@tobiasKaminsky Can you help? 

I don't even know if polls is intended to appear in the android app.

**Comment by tobiasKaminsky** [comment]
Android Files is "only" for files and related tasks.
It is somehow a part of Android Talk, if one creates a poll within a conversation.

For regular polls web browser is the way to go.

**Comment by dartcafe** [comment]
@glama I'll close that, since polls is not intended to appear in the android app.
