### ISSUE TITLE
Last line is hidden for unauthenticated users

### ISSUE THREAD

**Issue by DennisNewhouse** [nextcloud/polls#2719]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Unfortunately the last line in original or table view is hidden by Nextcloud Banner and Privacy policy.

### What did you expect, how polls should behave instead?

All lines should be visible for authenticated and unauthenticated users

### What steps does it need to replay this bug?

1. Create text poll with text and i.e. 4 options
2. Create public link
3. Open public link and click "cancel"
4. Scroll down to see all options
5. Last option 4 is hidden by banner

![image](https://user-images.githubusercontent.com/23340402/209817821-1ef512a7-52f0-41cb-bd00-7d4409ca7d3e.png)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 7.4

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by bymarlin04** [comment]
I'm having the same issue on iOS / iPadOS, where the last option is shadowed by a banner. I think a possible solution could be to either add a padding at the bottom of the options list or to hide the banner.

![grafik](https://user-images.githubusercontent.com/53409409/211693088-7892ecb8-e8f0-4532-8bd4-99ac9a45edca.png)

﻿

**Comment by dartcafe** [comment]
Fixed in #2681/#2682, the footer got removed.
This is a problem, which is caused in the core template together with the vue libs provided from Nextcloud.
