### ISSUE TITLE
Menu should not be accessible in public polls (w/o user logged in)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/polls#272]
### Steps to reproduce
1. Create a public poll
2. Don't login, just use the link to access it, e.g. on a mobile browser
3. tap on the empty space of the top bar

### Expected behaviour
No menu should appear since the apps (files, mail, whatever) are not accessible w/o login.
### Actual behaviour
The (public/anonymous user gets a menu that he/she cannot use:
![grafik](https://user-images.githubusercontent.com/8425483/34166200-981ff38e-e4de-11e7-98ee-08ec140d1fb4.png)

### Server configuration
**Nextcloud version:** confirmed on 12.0.4 and 13b3

**Comment by dartcafe** [comment]
Related to #140. @nursoda Please confirm, the mobile menu does not appear here for me: https://nc13.yagst.de/index.php/apps/polls/poll/Ji7hO2zhnLX0VQRq

**Comment by nursoda** [comment]
Absolutely. No Menu there, and a WAY BETTER presentation for mobile devices. GREAT!

**Comment by dartcafe** [comment]
Thanks for checking and testing.

**Comment by dartcafe** [comment]
Good point. Feel free to add an issue, because I am afraid this point could be lost. And we can discuss possible solutions there.

**Comment by dartcafe** [comment]
And this scrolling issue may be remaining on mobile devices with wider polls in landscape view.

**Comment by nursoda** [comment]
Created https://github.com/nextcloud/polls/issues/276 as requested.

On my tablet, side scrolling works.
