### ISSUE TITLE
Can't install Polls 4.1.2 since 4.1.1 (Database error when running migration)

### ISSUE THREAD

**Issue by Silverscott** [nextcloud/polls#2754]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Hello ! Since my try to manually install Polls 4.1.1, i can't no more install 4.1.2 :/
i have this message when i try to install Polls 4.1.2 via GUI in NC 👎🏻

`Database error when running migration 040102Date20230123072601 for app polls An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'description' at row 1`

### What did you expect, how polls should behave instead?

Installation of the application Polls

### What steps does it need to replay this bug?

1.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

4.1.2

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

MySQL

### Database Engine version or other Database

15.1 Distrib 10.5.18-MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
[settings] Erreur: Exception: Database error when running migration 040102Date20230123072601 for app polls
An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'description' at row 1 at <<closure>>

0. /var/www/nextcloud/lib/private/Installer.php line 153
   OC\DB\MigrationService->migrate()
1. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 451
   OC\Installer->installApp()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Settings\Controller\AppSettingsController->enableApps()
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
6. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
7. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

POST /index.php/settings/apps/enable
from 192.168.1.254 by Scott at 2023-01-26T09:28:42+00:00
```

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my-domain.net:8443"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/my-domain.net:8443",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "daily",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "admin_notifications"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_phone_region": "FR",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        }
    }
}

--------------------------

root•/var/www/nextcloud» ./occ config:list system                                                                                                  zsh: permission non accordée: ./occ

--------------------------
```

### List of activated Apps

```shell
root•/var/www/nextcloud» sudo -u www-data php occ app:list                                                                                         [10:39:50]
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.4.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - external: 5.0.0
  - externalpassword: 1.1.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.3
  - integration_google: 1.0.9
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - rainloop: 7.2.6
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - unsplash: 2.1.1
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - audioplayer: 3.3.1
  - bruteforcesettings
  - encryption: 2.13.0
  - mail: 2.2.2
  - polls: 4.1.0-beta6
  - side_menu: 3.5.2
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by dartcafe** [comment]
Are you able to post the database structure of the table `oc_polls_polls`?

**Comment by Silverscott** [comment]
Oh yes i can if you give me the sql command to export it :)

**Comment by Silverscott** [comment]
I think i found...

MariaDB [nextcloud]> SHOW COLUMNS from oc_polls_polls;
+------------------+---------------+------+-----+----------+----------------+
| Field            | Type          | Null | Key | Default  | Extra          |
+------------------+---------------+------+-----+----------+----------------+
| id               | int(11)       | NO   | PRI | NULL     | auto_increment |
| type             | varchar(64)   | NO   |     | datePoll |                |
| title            | varchar(128)  | YES  |     |          |                |
| description      | text          | YES  |     | NULL     |                |
| owner            | varchar(256)  | YES  |     |          |                |
| created          | int(11)       | NO   |     | 0        |                |
| expire           | int(11)       | NO   |     | 0        |                |
| deleted          | int(11)       | NO   |     | 0        |                |
| access           | varchar(1024) | NO   |     | private  |                |
| anonymous        | int(11)       | NO   |     | 0        |                |
| allow_maybe      | int(11)       | NO   |     | 1        |                |
| vote_limit       | int(11)       | NO   |     | 0        |                |
| option_limit     | int(11)       | NO   |     | 0        |                |
| show_results     | varchar(64)   | NO   |     | always   |                |
| admin_access     | int(11)       | NO   |     | 0        |                |
| important        | int(11)       | NO   |     | 0        |                |
| allow_comment    | int(11)       | NO   |     | 1        |                |
| hide_booked_up   | int(11)       | NO   |     | 1        |                |
| allow_proposals  | varchar(64)   | NO   |     | disallow |                |
| use_no           | int(11)       | NO   |     | 1        |                |
| proposals_expire | int(11)       | NO   |     | 0        |                |
| misc_settings    | text          | YES  |     | NULL     |                |
+------------------+---------------+------+-----+----------+----------------+
22 rows in set (0,002 sec)

**Comment by dartcafe** [comment]
I have no idea, what happens. I think, I have to recreate the repair steps. 
For a quck fix it should be enough to change the settings a followed: 

| Field | Type | Null | Key | Default | Extra |
|------------------|---------------|------|-----|----------|----------------|
| id | int(11) | NO | PRI | NULL | auto_increment |
| type | varchar(64) | NO | | datePoll | |
| title | varchar(128) | ***_NO_*** | | | |
| description | text | ***_NO_*** | | | |
| owner | varchar(256) | YES | | | |

**Comment by dartcafe** [comment]
That cannot be the source. 
What is the content of the description field of the first record?

**Comment by Silverscott** [comment]
How can obtain this information please ?

**Comment by dartcafe** [comment]
The first record in the table. The error message says, the content will be trucated. But this seems not the concrete error, since I do not belive, you have a description with more than 65000 characters.

**Comment by Silverscott** [comment]
yes but can you give me the sql command to obtain the content of the description field of the first record ?

**Comment by dartcafe** [comment]
```
SELECT `description` FROM `oc_polls_polls` LIMIT 1
```

**Comment by dartcafe** [comment]
Another solution could be to drop all polls tables an reinstall the app. If you have no polls which have to be kept.

**Comment by Silverscott** [comment]
> ```sql
> SELECT `description` FROM `oc_polls_polls` LIMIT 1
> ```

Hello @dartcafe René,

Here the answer 👍🏻 

MariaDB [nextcloud]> SELECT `description` FROM `oc_polls_polls` LIMIT 1;
+-------------+
| description |
+-------------+
| NULL        |
+-------------+
1 row in set (0,000 sec)

**Comment by Silverscott** [comment]
Hello Team,

I finally managed to uninstall Polls completely and reinstall them and everything works properly. We can therefore proceed to the closing of the note

**Comment by dartcafe** [comment]
Glad, your issue is solved and you can proceed. But there is still someting wrong with the migration or repair staps. See https://github.com/nextcloud/polls/issues/2756#issuecomment-1435516563. 

I am still hanging around with that.

**Comment by dartcafe** [comment]
FYI: 4.1.3 is out. The migration got a complete overwork and was tested with a lot of destroyed databases and inconsitent states. All tests ended with a valid database.
