### ISSUE TITLE
UI: Emphasize WHERE user input is and how it works

### ISSUE THREAD

**Issue by nursoda** [nextcloud/polls#276]
### Steps to reproduce
1. create a poll
2. let "aunt Sally" users try to use the app
    (no matter whether on PC or mobile)

### Expected behaviour
User ideally should be able to intuitively use the UI to select her/his preferred choice(s).

Proposal: The app should GUIDE the user where to ACT, like emphasize where the actual SWITCHES are, e.g. with a mildly pulsating mirror at the position where the "switch all" button is now. I know that a "switch all" button is handy, too, but the indicator is more important. Or you might want to add a fourth 'initial' state (empty checkbox) indicating that interaction is possible there.

### Actual behaviour
Users are baffled how to use the UI at all, some users don't grasp that they have to actually save/send their choice, some complain that -while trying to find out how to use it- they "accidentaly" hit the "switch all" "button" and thereby reset their choices.

**Comment by dartcafe** [comment]
Suggestions: 
- What about immediately saving the vote after klick? So the vote button can be removed. 
Especially on mobile views an easier handling. Less klicking on desktops
- Empty options if a user enters a poll, he didn't vot in before. Empty votes get the "no" state and is a red creoss, if he enters it again. 
Additinally some shadow could be added, to give the switch a little more button style
- remove switch all button.
I vote again for removing it.  The intention of a poll is, to get feedback of the user of his opinions or availability. Switching all options at once is no optinion in my view, it is just lazy or a matter of "I don't care". 
@v1r0x @splitt3r 
Optinions?

**Comment by dartcafe** [comment]
BTW: What do you think about  https://gitter.im/nextcloud-polls

**Comment by v1r0x** [comment]
> What about immediately saving the vote after klick? So the vote button can be removed.
> Especially on mobile views an easier handling. Less klicking on desktops

IMO this can be confusing. At least without visual feedback. And sending each single vote to the server should disable all others, so there is no async sh*t which leads to wrong results or something else.

> Remove switch all button.

I'd keep it. It is good for larger polls. Let's say you want to order pizza and someone starts a poll with all possible toppings (of course no pineapple) and you like all of them. Or you don't care about most of them (yellow), but definitely want cheese and onions.
Or if you want to find an appointment for training or a movie night and all dates work for you.
This might not be the regular poll, but it is great to have such an option for the 1 in 100 polls you need it. And I'd curse you, if I need this feature and it is no longer there 😁

**Comment by splitt3r** [comment]
@v1r0x no onions but pineapples please 👍

**Comment by v1r0x** [comment]
@splitt3r You are a monster....

**Comment by splitt3r** [comment]
![evil](https://media.giphy.com/media/fFSJFtyedUg5W/giphy.gif)

**Comment by nursoda** [comment]
I vote for the "save each click" since it's the way NC works all over, so it's consistent.
But there should be an easy way to edit or remove a poll since such a click is easily made.
Plus, clicking or tapping a checkbox should report an error if no name is given first.
MAYBE even that might be "guided" by graying out things I cannot select YET (w/o name).

Please do the 80% case first. That's w/o "switch all". "Switch all" might be opt-in on CREATING a poll ...

**Comment by nursoda** [comment]
About gitter.im : To me it's "yet another messenger (and channel to look into). Personally, I'd rather not install even another one. I'd keep it on one platform or use a well-established messenger such as Telegram or Signal.

**Comment by dartcafe** [comment]
Votes are saved instantly in https://github.com/nextcloud/polls/tree/dev-1.0
Unvoted options are displayed  as a black cross. 
![grafik](https://user-images.githubusercontent.com/26707476/64480367-8238c880-d1c6-11e9-90bb-6754d52d4134.png)
