### ISSUE TITLE
Only one Poll for IP

### ISSUE THREAD

**Issue by 19Topgun93** [nextcloud/polls#2772]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a Poll owner, I want to be able to limit the Polls per IP-Adress, because it helps to avoid double or more Polls from one Adress. So that can limit the possibility to manipulate the Poll. Perhaps a function per Browser Session could be useful too.

Actual you can only limit the Polls with usernames or users of the cloud. So if somebody want to manipulate the Poll in one or another way, a IP option would be useful. Because of this we went to Strawpoll to poll our polls. If this is public.

### Describe possible solutions

I informed me a little bit, and Javascript could be log the IP if the option is on for this poll. If the User try to make another Poll, he gets a Message. After the Poll is closed, the IPs could be erased.

**Comment by dartcafe** [comment]
Sorry, but this is a complex implementation with expensive coding, testing, maintainig compared to a very limited value.

In your use case you assume that an IP address represents a single user, which is not what happens in real life. Multiple users can share the same IP address, users have dynamic adress changes and IP addresses can be spoofed.

Additionally this could cause conflicts with the GDPR and needs at least an additionally opt-in from every user. 

Sorry for saying no. But thanks to your very good example of a user story.

**Comment by 19Topgun93** [comment]
> Sorry, but this is a complex implementation with expensive coding, testing, maintainig compared to a very limited value.
> 
> In your use case you assume that an IP address represents a single user, which is not what happens in real life. Multiple users can share the same IP address, users have dynamic address changes and IP addresses can be spoofed.
> 
> Additionally this could cause conflicts with the GDPR and needs at least an additionally opt-in from every user.
> 
> Sorry for saying no. But thanks to your very good example of a user story.

Thanks for your response, and that one IP-Adress only one user expect, I didn't wanted to say that so, but it could limit the user, that he make another and another window open. The most User doesn't know that to with the IP Adress. 

With the IP Adress, I have the same concern like you. I use Nextcloud for not to have many data around, because of this, the erase the IP after closed and that the IP not in every time one user is. Also it gives people who are sitting in a NAT from the ISP itself. It would be a limiter. A complete would be impossible also. But, I am also concern, if a company like strawpoll use this. That is a tricky thing :/ 

Thank you for your good answer. Perhaps I have time in the future to do the work for my self and implement it in my Nextcloud.... is that ok for Nextcloud? I don't want a bad link on you guys :D With the necessary ok from the user and so on :D 

Thanks for your work all of yours :)

**Comment by dartcafe** [comment]
Everyone is welcome to participate in the development of an open source system like that. 

You can try, but we should understand that every added complexity has its drawbacks, like maintenance in the future and increased test afford (especially for this feature, because it is affected by the network layer). And it is an additionally error source.

In any case like that the added value must be understandable and if it is really a value for most users, when it comes with this cost of work.
