### ISSUE TITLE
No e-mail notification on poll creation

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/polls#278]
As mentioned in #188 there is some e-mail notification feature with this app. I just created two polls, one shared with another user and one shared with a user group. None of the other participants got any mail notification.

### Steps to reproduce
1. Create a new poll
2. Select some users to share the poll with
3. Click "Create poll"

### Expected behaviour
All selected users should get a mail with the link

### Actual behaviour
No mail is being sent

## Server configuration detail

**Operating system:** Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.6
 - nextcloud_announcements: 1.1
 - notes: 2.3.2
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - polls: 0.8.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - direct_menu
 - encryption
 - files_external
 - firstrunwizard
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "occo35bymryr",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.domain.de"
    ],
    "datadirectory": "\/usr\/local\/owncloud",
    "overwrite.cli.url": "https:\/\/cloud.domain.de",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "appstore.experimental.enabled": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "nextcloud",
    "mail_domain": "cloud.domain.de",
    "mail_smtphost": "mail.domain.de",
    "mail_smtpport": "587",
    "loglevel": 0,
    "filesystem_check_changes": 1,
    "maintenance": false,
    "updatechecker": false,
    "theme": "elektrat",
    "app.mail.smtplog.enabled": true,
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "filelocking.enabled": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by mcnesium** [comment]
There *are* mail notifications sent out to the creator, if there are comments or participations on the poll.

**Comment by splitt3r** [comment]
So this is a feature request to let all participants receive email notifcations?

**Comment by mcnesium** [comment]
If sending mails on poll creation is not implemented yet, then yes.

**Comment by splitt3r** [comment]
Will have a look at it.

**Comment by dartcafe** [comment]
Something, we should inspect together with things like invitations and intergration with circles.

**Comment by prsnbrg** [comment]
It is possible over the notification app from ownCloud and nextCloud to notify all participants if they log in?

**Comment by dartcafe** [comment]
Notification will be added in similar ways (notification app, circles, email, ...).

**Comment by dartcafe** [comment]
Related to #178
