### ISSUE TITLE
Method Not Allowed at Resend Email

### ISSUE THREAD

**Issue by sleeplessnight2** [nextcloud/polls#2789]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Guest users cannot resend a welcome email.

Here the browser console informs me with a "405 Method Not Allowed".

See attached Picture

![2023-03-02_15-48-29](https://user-images.githubusercontent.com/8561601/222465664-41358d7e-d524-4b70-891a-022271e2efa6.jpg)

### What did you expect, how polls should behave instead?

An email should be sent.

### What steps does it need to replay this bug?

1.  Create a survey.
2. Create a public link.
3. Open the link
4. Enter ONLY one name.
5. Click on the options icon
6. Enter an email address
7. Then click on the button "Receive your personal link by email".

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 7.4

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
See https://github.com/nextcloud/polls/releases/tag/v4.1.7
