### ISSUE TITLE
[Feature Request] Federated / email sharing

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/polls#279]
As an extension to #278 I would like to see the option to add arbitrary participants to the poll, like other federated cloud IDs or mail addresses. This should be working just like the regular sharing works in Nextcloud, so that there is no need to have an account on the same instance to participate in a poll.

**Comment by splitt3r** [comment]
Very good idea but not that easy to implement. And i think the advantage over normal public link sharing is very small.

**Comment by dartcafe** [comment]
That's something, what I expect with the invitaion. Base for this should be the remodelling of an own user class, where non system users can be invited via mail and reenter their vote with an unique link. I already worked on a proposal for the user class. As soon, I will have time, I will finish this and we can discuss it. I think; I will have time next week.

**Comment by joergmschulz** [comment]
such user class would allow non-nextcloud users to modify their poll on their next visit.

**Comment by dartcafe** [comment]
Invitation via eMail and personal link is implemented in version 1.0. Federated invitation is not on the road map for now.
