### ISSUE TITLE
0.8.1 release

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#280]
ToDos: 
* [x] Final tests
* [x] Update CHANGELOG.md and https://github.com/nextcloud/polls/releases/tag/untagged-7ce48c9be9cfb4cf7475
* [x] check compatibilty against oC
* [ ] Build package for apps.nextcloud.com
* [ ] Build package for marketplace.owncloud.com

**Comment by splitt3r** [comment]
Will do some oC 10 / Nc 12 / Nc 13 testing tomorrow.

**Comment by v1r0x** [comment]
@dartcafe looks good! Unfortunately, I don't have time to do the testing, but I can build the packages as soon as you want to.
oC support ends with 0.9?

**Comment by dartcafe** [comment]
I tested oC10, NC11, NC12, NC13. I found no more major issues. 
And yes, we decided to drop support for oC after this release and NC11 as soon, as NC13 is out. So this means now in my POV.

**Comment by dartcafe** [comment]
@splitt3r Any tests outstanding?

**Comment by splitt3r** [comment]
https://github.com/nextcloud/polls/wiki looks good 👍 will do some tests today

**Comment by v1r0x** [comment]
Wiki looks good! 👍

**Comment by dartcafe** [comment]
So let's fire.

**Comment by splitt3r** [comment]
I think we should backport https://github.com/nextcloud/polls/issues/223 that issue to 0.8.X once it is fixed.

**Comment by dartcafe** [comment]
Good point. Would be neccessary. But we have to be sure, the migration system works on this. Or we patch this first and start the db schema changes afterwards. Is a little bit tricky, or am I wrong?

**Comment by dartcafe** [comment]
@v1r0x Can you prepare the relaese for the app stores? Version 0.8.0 is not really UI compatible with NC13. Just made an update on a production site to RC1 and saw this. 

We should set min version to 13 for this release.

**Comment by dartcafe** [comment]
Nonsense. I mean max version NC12 for 0.8.0

**Comment by splitt3r** [comment]
Ah ok ^^ yeah that´s a good idea

**Comment by v1r0x** [comment]
@dartcafe I try to publish the release and zips to the app stores tonight.

**Comment by dartcafe** [comment]
I am a little bit busy at work at the moment. So some delay for further things will occur...

**Comment by dartcafe** [comment]
I updated the 0.8 and 0.9 branches, so they are up to date with the current master.

**Comment by dartcafe** [comment]
@v1r0x If you mind, you can give access to me in the app store, so I can help there (and learn. :-))

Anyone knows, whats happened to the pictures on github? The pictures in the readme.md are linked correctly. I noticed this problem occours at other projects too.

**Comment by v1r0x** [comment]
@dartcafe App store is rather unspectacular. The magic happens in the Makefile 😉 
The marketplace is a crappy piece of ****...Every release needs around 30 minutes to submit. But afair this was the last time! 🎉 🎆 

@dartcafe @splitt3r Thanks again for your work!

**Comment by ansorg** [comment]
When will this show up in the OwnCloud Market? Still at 0.8.0

**Comment by dartcafe** [comment]
@v1r0x

**Comment by v1r0x** [comment]
Should be fixed....I hate this crappy marketplace :rage:

**Comment by duub** [comment]
still in 0.8.1 in the owncloud market... is going to be upgraded? should migrate to nextcloud?
