### ISSUE TITLE
Error message trying to install polls

### ISSUE THREAD

**Issue by johnnydvc** [nextcloud/polls#281]
### Steps to reproduce
1. Enable Polls from the nextcloud apps section

### Expected behaviour
Polls should work

### Actual behaviour

```
An exception occurred while executing 'ALTER TABLE oc_polls_dts ADD `poll_id` INT DEFAULT NULL, DROP description, CHANGE `id` `id` INT AUTO_INCREMENT NOT NULL, CHANGE `dt` `dt` DATETIME DEFAULT NULL, ADD PRIMARY KEY (`id`)': SQLSTATE[23000]: Integrity constraint violation: 1062 ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '7' for key 'PRIMARY'
```

## Server configuration detail

**Operating system:** Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l

**Webserver:** nginx/1.9.10 (fpm-fcgi)

**Database:** mysql 5.5.57

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, PDO, apcu, curl, gd, json, mcrypt, memcache, memcached, mysql, mysqli, pdo_mysql, readline, redis, mhash, apc, Zend OPcache

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** unknown

**Where did you install Nextcloud from:** unknown

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - apporder: 0.4.1
 - bookmarks: 0.10.1
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.5
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.3.0
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.7
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notes: 2.3.2
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - phonetrack: 0.1.1
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - ransomware_protection: 1.0.5
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.3
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - encryption
 - files_external
 - files_videoplayer
 - polls
 - survey_client
 - theming
 - unsplash
 - user_external
 - user_ldap
```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocugwb8v1qw1",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "johnnydvc.spdns.org",
        "picloud2.jstoexwl5axd8znt.myfritz.net"
    ],
    "datadirectory": "\/var\/www\/data",
    "overwrite.cli.url": "johnnydvc.spdns.org",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "default_language": "de",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "en3",
    "mail_domain": "mailbox.org",
    "mail_smtpauth": 1,
    "mail_smtphost": "smtp.mailbox.org",
    "mail_smtpport": "587",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "log_type": "owncloud",
    "logfile": "nextcloud.log",
    "loglevel": 2,
    "logdateformat": "F d, Y H:i:s",
    "log_rotate_size": 10485760,
    "trashbin_retention_obligation": "auto",
    "appstore.experimental.enabled": "true",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
    "updatechecker": "true",
    "updater.release.channel": "stable",
    "integrity.check.disabled": "false",
    "mysql.utf8mb4": "true"
}
```
</details>

**Are you using encryption:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by splitt3r** [comment]
Was the app enabled before or is it a fresh install?

**Comment by johnnydvc** [comment]
Yes, I had it enabled before the upgrade.
Is there a folder that needs deleting?
I have deleted the apps folder but that didn't fix it. 
Thanks

**Comment by splitt3r** [comment]
Dropping the polls_dts table should fix the problem. But it's a strange error and the db changes are handled by Nc :unamused:. I will try to somehow reproduce the issue.

**Comment by splitt3r** [comment]
Dropping the polls_dts table should fix the problem. But it's a strange error and the db changes are handled by Nc :unamused:. I will try to somehow reproduce the issue.

**Comment by splitt3r** [comment]
Dropping the polls_dts table should fix the problem. But it's a strange error and the db changes are handled by Nc :unamused:. I will try to somehow reproduce the issue.

**Comment by splitt3r** [comment]
Dropping the polls_dts table should fix the problem. But it's a strange error and the db changes are handled by Nc :unamused:. I will try to somehow reproduce the issue.

**Comment by dartcafe** [comment]
For an inspection it could be useful to have the tables. Can you upload a dump of the oc_polls_* tables here: [https://nc12.yagst.de/index.php/s/ekigFpvJQZrbBKl](https://nc12.yagst.de/index.php/s/ekigFpvJQZrbBKl)?

Which version did you try to install?
Is that an upgrade of the polls app? If yes, from which version?

Alternatevely you can drop all tables named oc_polls_* and enable polls after that.

**Comment by dartcafe** [comment]
Maybe, this could be an explanation? 
https://stackoverflow.com/questions/5402949/mysql-cant-make-column-auto-increment

**Comment by johnnydvc** [comment]
Thank you very much.
I dropped all the polls tables and that did the trick.
