### ISSUE TITLE
Group meeting scheduler with personalized availabilities (not choosing from blocks). Drag and drop user interface.

### ISSUE THREAD

**Issue by ArneDuyver** [nextcloud/polls#2811]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a team member, I want to able to easily schedule meetings with a team. Existing poll solutions do not meet my expectations because each attendee can only chose from certain blocks.
My vision for a utility is the following:
- Invite a set number of people for a meeting (give a day period range in which the meeting must be held)
- Each member can select spots in a calendar (fully free, not needing to chose between predefined blocks)
- - preferably by using a drag and drop method on a week calendar .
- - (also being able to mention: "online" or "in person" or "only if no other possible")
- The systems gives a live ranking (with first place being all members who already submitted a response are available -> decreasing in numbers of availability ...)

Extra functionalities:
- link with calendar so if anything comes up in the available time specified earlier, your availability is automatically updated
- link with calendar so if everyone submitted an availability the top moment is filled into your agenda and a confirmation email is sent
- possibility to rank your availabilities to distinguish between them (effects overall ranking of final meeting date)
- final ranking is also calculated on who is more important to be at a meeting then others

### Describe possible solutions

I think this should be possible, but a lot of work.

### Additional context

I quickly searched for such an open source and free application but could'nt find one.
I my team people's availabilities are not fixed blocks, but could be 5 min intervals so it is difficult to define blocks in the beginning where everyone can choose between. One person is available mondag from 9 till 10:15 and another from 9:45 till 11. So how do they fill in blocks from 9-10 and 10-11? a short meeting from 9:45 till 10:15 is the obvious choice but is difficult to find in current meeting schedulers. At least the ones I know of.

Massive thanks in advance for all the hard work so far and possible work or just recommendations for my problem in the future.

**Comment by dartcafe** [comment]
Like this? #1694

**Comment by ArneDuyver** [comment]
Indeed thanks a lot for the reference. 
I would like the option to choose increments of 15 minutes though.
