### ISSUE TITLE
open poll after clicking URL (not logged in) and then login

### ISSUE THREAD

**Issue by mark-franz** [nextcloud/polls#2812]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

When I receive a poll invite and click on the URL, I want to get direct access to the poll - also when I first need to login. 

### Additional context

1. Receive an invite to participate on a poll like e.g. https://cloud..../apps/polls/s/12345678
    -  Note: the poll I was invited to was a "private" poll but with public access (i.e. also guests could participate). 

3. Click the URL. > Browser opens Nextcloud
4. Get window "participate as guest or as logged-in user"
5. Log in to Nextcloud

Expected behaviour: after login, the poll opens

Actual behaviour: after login, the "files" app opens

**Comment by dartcafe** [comment]
That is a bug, because this feature was there before. I can reproduce that and will investigate.
