### ISSUE TITLE
Cannot select calendars for availability

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/polls#2814]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

The polls app user menu offers to select calendars to respect for user‘s availability. However in the current beta you can enable the calendar selection, but there is no way to select or add any existing calendars to it

### What did you expect, how polls should behave instead?

Selecting existing calendars should be possible to restrict availability times

### What steps does it need to replay this bug?

1. Install app
2. Ensure you have existing calendars
3. Go to polls user settings menu
4. Enable top most check box to select calendars

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

Latest beta

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [X] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
N/A
```

### Additional client environment information

N/A

### NC version

Other/Don't know

### Other Nextcloud version

NC26

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
N/A
```

### Additional environment informations

N/A

### Configuration report

```shell
N/A
```

### List of activated Apps

```shell
N/A
```

### Nextcloud Signing status

```shell
N/A
```

### Additional Information

N/A

**Comment by dartcafe** [comment]
I don't get your point. 

I can select the available calendars in the Polls Settings. 

![grafik](https://user-images.githubusercontent.com/26707476/226952002-0059187b-c1f0-45a6-9ac4-75b9bf3e52f2.png)

**Comment by mkrecek234** [comment]
This is what it looks like on my end

![image](https://user-images.githubusercontent.com/28671486/226956233-3d71d09b-822c-42f7-9c15-1dc53fb286de.png)

And I have these calendars for the logged in users in "calendar" app:
![image](https://user-images.githubusercontent.com/28671486/226956492-4a38cffd-ec05-4495-91d4-d8d86fa5c913.png)

**Comment by dartcafe** [comment]
There is a 500 error. This will be logged in the ser logs. I need that to investigate this. 

Please don't understand me wrong, but delivering the neccessary information by properly filling out the form fields speeds up investigation and fixing and reduces communication times. There is a reason, why the information in the bug form is requested.

**Comment by mkrecek234** [comment]
Hi @dartcafe Sorry for not providing the detailed logs in the first place. I reinstalled NC26 (before I had multiple updates for several beta versions) - in a fresh install, Polls work as intended and the calendars appear again. Closing this issue therefore.

**Comment by dartcafe** [comment]
@mkrecek234 Thanks for updating! 👍
