### ISSUE TITLE
[Feature Request] in addition of who changed something also add what changed

### ISSUE THREAD

**Issue by AkbahafA** [nextcloud/polls#2820]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll participant, I would like to, not only know who changed something, but also what has been changed, this would be helpful for everyone, participating in the poll.

We use Poll for weekly sports training with a team of 10 people.
The poll stretches over 8 months.
After the initial opening of the poll, were most of the people register for some dates for, lets say, the next 3 months, someone additional joins or leaves a previously registered date or extends his "reservations"

In the current state, the only information everyone gets is, that "Person A changed something". Then everyone checks on the poll to see if it is for the next training, if he will be maybe alone or if there are to many participants or whatever.

### Describe possible solutions

A change or add, from a poll, should be made visible thru the eMail notification system and on the activity tab in the poll sidebar.
This could be a "per Poll" setting and preferably there would be a default setting, on the server, if it is activated by default for each new poll or not.

### Additional context

eMail notifiction
![image](https://user-images.githubusercontent.com/128912217/227725515-3c3c804b-6b50-4405-a63a-31a762753140.png)

Sidebar
![image](https://user-images.githubusercontent.com/128912217/227725696-7eae04eb-9fe1-4a27-a6ea-7ceef6a6aac3.png)

**Comment by AkbahafA** [comment]
And first of all, thank you for developing such a already great tool for our Nextcloud servers!!
It really helped me, to migrate from Doodle.
Thank you Sir!

**Comment by dartcafe** [comment]
This is by intention. We just record the action once between the cron jobs because this otherwise could lead to a massive list of changes.

Imagine a poll with 10 options and ten participants. And additionally if the participants change their vote multiple times. This could result in 100 notification and more. 

I think we should abstain from that.
