### ISSUE TITLE
Reminder Email use local IP and http instead of the Nextcloud-URL

### ISSUE THREAD

**Issue by sleeplessnight2** [nextcloud/polls#2837]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

The reminder email does not contain the link with the Nextcloud URL, but uses the Local IP and http instead of https.

The same applies to the button URL

For Example:

The link from the invation:
https://sub.domain.tld/index.php/apps/polls/s/fygT1oo6X5bY2EBg

The link from the reminder:
http://192.168.1.23/index.php/apps/polls/s/fygT1oo6X5bY2EBg

### What did you expect, how polls should behave instead?

That the same URL as the one from the invitation is taken.

### What steps does it need to replay this bug?

1. Create a poll
2. invite a user with "Name email@domain.tld"
3. send invite
4. wait for the reminder email

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

4.1.8

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [X] Linux
- [X] MacOs
- [X] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 27 (Nextcloud Hub 5)

### PHP engine version

PHP 7.4

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Check your configuration for `overwrite.cli.url.` The CLI needs to know, which domain is to be used.
