### ISSUE TITLE
5.0.0-rc1: IEMailTemplate class cannot be queried via container

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/polls#2842]
The following just cannot work, as there is no registered service for the IEMailTemplate class in the app container:

https://github.com/nextcloud/polls/blob/b785f16c1fc6eeaa35a755b9ebf2ceaa46914142/lib/Model/Mail/MailBase.php#L74

Or is it my setup? I constantly get  `OCP\\AppFramework\\QueryException`  when this interface class is queried.

This happens with the forthcoming v5 release.

**Comment by rotdrop** [comment]
Could not this be simply cured by not using the container, but instead use `MailBase::getEmailTemplate()`?

BTW: the frontend does not show an error as seemingly the error returned from the AJAX  call is not diagnosed by the app's JS code. So this is nasty: you only realize hours or days later that it did not work out and then you have to look into the developer tools JS console.

**Comment by dartcafe** [comment]
See  #2836
