### ISSUE TITLE
Translate Error in german language

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/polls#2845]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

![Poll - Übersetzungsfehler](https://user-images.githubusercontent.com/96744684/229841544-f6160507-4f68-4acf-9874-70038dbd5276.jpg)

Vers. 4.1.8 - Nextcloud 25.0.5

The word "swinwin" (below the e-mail field) must edit to "Deinen" 

Btw: Here its in german - thats right. But how decides poll in which language the window is displayed?

### What did you expect, how polls should behave instead?

The word "swinwin" (below the e-mail field) must edit to "Deinen" 

### What steps does it need to replay this bug?

1.
use my poll
https://nco.stefan-franz.de/index.php/apps/polls/s/kqEDtxF77nvkrocp

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

4.1.8

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 7.3

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Thanks. See https://github.com/nextcloud/polls/pull/2840#issuecomment-1494995565
