### ISSUE TITLE
Polls cannot be edited when user has no mail address

### ISSUE THREAD

**Issue by Python3Freak** [nextcloud/polls#2852]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

With Nextcloud 26.0.0 and Polls 5.0.0, polls (even newly created ones) cannot be edited if the user has no mail address set in profile. Polls can still be viewed and used by logged out persons by link.

Workaround: Set mail address in profile, even a dummy will work

### What did you expect, how polls should behave instead?

Even without mail address users should be able to create and edit own polls.

### What steps does it need to replay this bug?

1. log in as user
2. ensure, no mail address is set in profile
3. create a poll

### Installation method

Installed/updated using occ

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

5.0.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### PHP engine version

PHP 8.0

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dirdi** [comment]
After the upgrade to 5.0.0, the cron job then and now throws the following error:
```
TypeError: Cannot assign null to property OCA\Polls\Model\UserBase::$emailAddress of type string in /usr/www/users/user/domain.tld/apps/polls/lib/Model/User/User.php:54
Stack trace:
#0 /usr/www/users/user/domain.tld/apps/polls/lib/Model/Group/Group.php(57): OCA\Polls\Model\User\User->__construct()
#1 /usr/www/users/user/domain.tld/apps/polls/lib/Service/MailService.php(189): OCA\Polls\Model\Group\Group->getMembers()
#2 /usr/www/users/user/domain.tld/apps/polls/lib/Service/MailService.php(167): OCA\Polls\Service\MailService->sendAutoReminderToRecipients()
#3 /usr/www/users/user/domain.tld/apps/polls/lib/Service/MailService.php(131): OCA\Polls\Service\MailService->processSharesForAutoReminder()
#4 /usr/www/users/user/domain.tld/apps/polls/lib/Cron/AutoReminderCron.php(44): OCA\Polls\Service\MailService->sendAutoReminder()
#5 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/Job.php(78): OCA\Polls\Cron\AutoReminderCron->run()
#6 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#7 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#8 /usr/www/users/user/domain.tld/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#9 {main}
```

I suspect this is cause by the same bug. However, on my NextCloud instance every user has an e-mail address configured and public polls are forbidden. Hence I can neither confirm nor deny @Python3Freak 's observation that setting a dummy e-mail address mitigates the bug. Instead I report that the bug occurs, even if e-mail addresses were set.

**Comment by dartcafe** [comment]
Thanks for reporting. 5.0.1 is out. See https://github.com/nextcloud/polls/issues/2857

**Comment by loelkes** [comment]
I suggest reopening this since, after upgrading manually to 5.0.1 the issue is not gone. This appears after opening the polls app. 

```
[index] Error: Exception: Cannot assign null to property OCA\Polls\Db\Share::$emailAddress of type string in file '/var/www/html/lib/public/AppFramework/Db/Entity.php' line 134 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Polls\\Co ... "], "list")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Polls\\Controller\\PollController", "list", ["OC\\AppFramewo ... "], ["polls.poll.list"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/apps/polls/polls")
3. /var/www/html/index.php line 36
   OC::handleRequest()

```

All users on this instance have email addresses. There are no errors in the cron job.

**Comment by loelkes** [comment]
After digging a bit it seems that this is an issue with the ACL.  It is assumed that all polls are shared with users. If a poll is shared via link, it will fail.

https://github.com/nextcloud/polls/blob/bf2c39ff2a44dfe0cd9c13e655b34e82ed107ec0/lib/Model/Acl.php#L334-L348

There should be a check if the result of the ShareMapper query returns a user or not. Since User-realted methods are used on something that is not a user it will later crash. This happens at multiple spots, the code above is only one example.

I don't have enough experience with Nextcloud to write a pull request, hopefully my analysis of the problem helps.

**Comment by dartcafe** [comment]
The check is there. Line 335 checks, if the user is logged in. The problem is, if a share has null stored as the email address the class crashes. 

`[index] Error: Exception: Cannot assign null to property OCA\Polls\Db\Share::$emailAddress of type string in file '/var/www/html/lib/public/AppFramework/Db/Entity.php' line 134 at <<closure>>`

**Comment by dirdi** [comment]
After upgrading to 5.0.2 the cronjob keeps sending me stack traces:
```TypeError: Cannot assign null to property OCA\Polls\Db\Log::$displayName of type string in /usr/www/users/user/domain.tld/lib/public/AppFramework/Db/Entity.php:136
Stack trace:
#0 /usr/www/users/user/domain.tld/lib/public/AppFramework/Db/Entity.php(167): OCP\AppFramework\Db\Entity->setter()
#1 /usr/www/users/user/domain.tld/lib/public/AppFramework/Db/Entity.php(75): OCP\AppFramework\Db\Entity->__call()
#2 /usr/www/users/user/domain.tld/lib/public/AppFramework/Db/QBMapper.php(321): OCP\AppFramework\Db\Entity::fromRow()
#3 /usr/www/users/user/domain.tld/lib/public/AppFramework/Db/QBMapper.php(339): OCP\AppFramework\Db\QBMapper->mapRowToEntity()
#4 /usr/www/users/user/domain.tld/apps/polls/lib/Db/LogMapper.php(81): OCP\AppFramework\Db\QBMapper->findEntities()
#5 /usr/www/users/user/domain.tld/apps/polls/lib/Service/MailService.php(65): OCA\Polls\Db\LogMapper->findUnprocessed()
#6 /usr/www/users/user/domain.tld/apps/polls/lib/Cron/NotificationCron.php(44): OCA\Polls\Service\MailService->sendNotifications()
#7 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/Job.php(78): OCA\Polls\Cron\NotificationCron->run()
#8 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#9 /usr/www/users/user/domain.tld/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#10 /usr/www/users/user/domain.tld/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#11 {main}```

**Comment by dartcafe** [comment]
Thanks for reporting. 
Next time please always open a new issue, so it can be tracked. And comments in closed issues may get missed.
