### ISSUE TITLE
Public Shared Polls queries for users in a loop?

### ISSUE THREAD

**Issue by b90g** [nextcloud/polls#2855]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### What went wrong, what did you observe?

When i share [a poll publicly](https://wolke.dev.netzbegruenung.de/apps/polls/s/P3gbfNAX2Y9oZwgr) and enter a user name the interfaces queries for existing user names until it breaks. in my browser meanwhile i get a green check mark that i can use that user name. when i submit my user name to start polling the  dialog windows stays afloat the poll and i can not enter my polling options. 

### What did you expect, how polls should behave instead?

1. I open the link.
2. I enter a name so people know who submitted their  poll options
3. I submit my polls
fin

### What steps does it need to replay this bug?

1.Publicly share a poll (see first paragraph)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.0.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

(112 versions on both browsers, no plugins installed)

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
```

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Database Engine version or other Database

10.5.18

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
after entering the user name:


{"reqId":"ZqGyJX77D1ZOKAulKMic","level":0,"time":"2023-04-13T11:49:00+02:00","remoteAddr":"2a03:d9c0:3000::a21e","user":"--","app":"polls","method":"POST","url":"/apps/polls/check/username","message":"Controller OCA\\Polls\\Controller\\PublicController::validatePublicUsername created 54746 QueryBuilder objects, please check if they are created inside a loop by accident.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0","version":"25.0.5.1","data":{"app":"polls"}}
{"reqId":"ZqGyJX77D1ZOKAulKMic","level":2,"time":"2023-04-13T11:49:00+02:00","remoteAddr":"2a03:d9c0:3000::a21e","user":"--","app":"polls","method":"POST","url":"/apps/polls/check/username","message":"Controller OCA\\Polls\\Controller\\PublicController::validatePublicUsername executed 54746 queries.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0","version":"25.0.5.1","data":{"app":"polls"}}
```

when submitting the user name:

```
{"reqId":"Iwaeri5OxQtk8SWG0YWp","level":2,"time":"2023-04-13T11:55:01+02:00","remoteAddr":"2a03:d9c0:3000::a21e","user":"--","app":"no app in context","method":"POST","url":"/apps/polls/s/P3gbfNAX2Y9oZwgr/register?time=1681379700904","message":"Failed to parse mimetypemapping.json: Syntax error","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0","version":"25.0.5.1","data":[]}
{"reqId":"Iwaeri5OxQtk8SWG0YWp","level":0,"time":"2023-04-13T11:55:01+02:00","remoteAddr":"2a03:d9c0:3000::a21e","user":"--","app":"user_saml","method":"POST","url":"/apps/polls/s/P3gbfNAX2Y9oZwgr/register?time=1681379700904","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0","version":"25.0.5.1","data":{"app":"user_saml"}}
```
```


### Additional environment informations

_No response_

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud01.wolke-dev.verdigado.net",
            "wolke.dev.netzbegruenung.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 0,
        "debug": true,
        "overwrite.cli.url": "https:\/\/wolke.dev.netzbegruenung.de",
        "dbtype": "mysql",
        "version": "25.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "filelocking.ttl": 3600,
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_readmemd",
            "onlyoffice"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "data-fingerprint": "490ffc7bacdce6eb676bcbc2013215ca",
        "integrity.check.disabled": false,
        "simpleSignUpLink.shown": false,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "maintenance_window_start": 1,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.2
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_antivirus: 4.0.3
  - files_pdfviewer: 2.6.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.2
  - gruenegroupfoldermanagement: 2.0.0
  - keeweb: 0.6.12
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.8.0
  - password_policy: 1.15.0
  - passwords: 2023.4.30
  - polls: 5.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_saml: 6.0.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - apporder: 0.15.0
  - dashboard: 6.0.0
  - drawio: 1.0.3
  - encryption
  - federation: 1.5.0
  - files_external
  - files_rightclick: 0.15.1
  - impersonate: 1.10.0
  - photos: 1.4.0
  - recommendations: 0.6.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - suspicious_login
  - twofactor_totp: 4.1.0
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional Information

I use polls on a compare able setup but with ldap on its backend. 

(dont mind the unredacted IP addresses, its a vpn anyway.)

**Comment by dartcafe** [comment]
I have no idea what this can be. Reproducing failed. But I have no SAML or SSO in any way. 
I can see no loop, which could cause this error. Maybe the maintainers of the SSO app can enlighten me.

**Comment by b90g** [comment]
the issue still persists, thank you stale bot for considering my vacation time...

i am not a maintainer of a SSO App so i cant give you much feedback on this. should i contact them for you? open an issue there when you  are sure that this is causing the user search in polls to fail? @dartcafe

**Comment by dartcafe** [comment]
And don't blame the stale bot. He just did his work. If you were on vacation and come back, just reopen the issue with a comment. 

But I can't still not help because I have no idea, how to debug this issue or even reproduce it. I was only speculating, if another developer has a hint what is going wrong here. 

The user check simply calls a search function from the core system and then the error is raised with your configuration. 

To be precise, it is raised here: https://github.com/nextcloud/server/blob/2b7d03778fb47908174a3a2f380278addc98cae5/lib/private/AppFramework/Http/Dispatcher.php#L144-L159

**Comment by dartcafe** [comment]
@nickvergessen Any idea? Why are such numbers of queries created. I would expect it is just one query.

The error stated above is raised here, I assume:
https://github.com/nextcloud/server/blob/0c64e313b8c350b5872e107b0e4e1ab3d9767c0d/lib/private/AppFramework/Http/Dispatcher.php#L152-L159

For example, the search for existing usernames with `IUserManager:search()` is initiated here:
https://github.com/nextcloud/polls/blob/b7c1ff68938fd9f5733d26cedcacb8e0bd6231e8/lib/Model/User/User.php#L90-L100

A little bit context: Existing usernames are not allowed for participant's names in a public polls. For this a search for the requested (public) username is initiated.

The complete search method (also for groups i.e.) can be found here:
https://github.com/nextcloud/polls/blob/b7c1ff68938fd9f5733d26cedcacb8e0bd6231e8/lib/Service/SystemService.php#L132-L185

**Comment by svenseeberg** [comment]
I found the issue. It comes from a custom group extension. However, I'm wondering if we need to fix something on both ends. First, obviously, we have an performance issue with our group back end.

But I'm wondering why the groups should checked. Can groups vote? Is there a chance of mixing things up? Because I can vote in a publicly shared poll by entering a name "Test" and then later create a group named "Test". This worked without any issues. In the end this function is only leaking information about existing user and group names, isn't it?

**Comment by dartcafe** [comment]
Group names are reserved names of the site and therefore forbidden.

**Comment by svenseeberg** [comment]
> Group names are reserved names of the site and therefore forbidden.

What happens if a user participates as "Test" and later a group "Test" is created? Nothing is preventing this right now. IMHO this results in undefined behavior.

**Comment by dartcafe** [comment]
Yes, right, but at the moment it is as it is. Needs some massive change for that.

**Comment by svenseeberg** [comment]
> Yes, right, but at the moment it is as it is. Needs some massive change for that.

Alright, then this issue can probably be closed.

**Comment by dartcafe** [comment]
Not sure, if the initial problem is solved. I was just regarding to the group name check.

**Comment by svenseeberg** [comment]
The initial problem is not a problem of the Polls app but of an internal app (that provides an additional group back end), that is not really as fast as it should be. IMHO the issue could be kept open as a reminder that things do not yet add up (not allowed to name a polls participants as a group, but adding groups with names of polls participants is okay). But if you (the developers) do not consider this relevant, then it can be closed.
