### ISSUE TITLE
Can not Create multiple options at once

### ISSUE THREAD

**Issue by c-cal** [nextcloud/polls#2876]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

![image](https://user-images.githubusercontent.com/57274151/234235613-7495a9d6-14f2-43c3-afd8-9d32cb9b4aa7.png)

### What did you expect, how polls should behave instead?

No error message

### What steps does it need to replay this bug?

Just try to add multiple options in the text area

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.0.4

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
No log while error is occurring
```

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### Other Nextcloud version

25.0.3

### PHP engine version

Other/Don't know

### Database engine

PostgreSQL

### Database Engine version or other Database

13.10

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
No log while error is occurring
```

### Additional environment informations

Docker

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by dartcafe** [comment]
Nice find. Thank you. Fixed in upcomming 5.0.5
