### ISSUE TITLE
Delete poll options in mobile view

### ISSUE THREAD

**Issue by wurrtelbrumft** [nextcloud/polls#2878]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When I login into my nextcloud on a mobile device and want to change a poll option I have to delete the poll option and create a new one. But on a mobile device the "bin-icon" is not visible. It appears when I try to rearrange the options but when I click on it, it disappears again and the option is not beeing deleted.

### What did you expect, how polls should behave instead?

The bin icon should be visible for the poll options also on a mobile device.

### What steps does it need to replay this bug?

1.  Replace the bin-icon visually a little bit towards the center of the poll option (in mobile view).

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 23 (Nextcloud Hub 1)

### PHP engine version

PHP 7.3

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Please tell me which width you use. I can easily tap the button down to a width of 300px. 
![grafik](https://user-images.githubusercontent.com/26707476/234395765-b4584f22-5836-41a0-b5cf-904ec2a9fa36.png)

**Comment by wurrtelbrumft** [comment]
Yes it looks like this as well on my phone. I think the Problem might be that the bin-icon seems to appear only when hovering... so it's not visible directly on the phone (as I said it becomes visible when I rearrange the order of the options).
But when I press on "Delete option" (the little hovering popup), the bin-icon disappears again and nothing happens.

(my phone screen resolution is 1080x2400)
