### ISSUE TITLE
Wrong url in mail to users

### ISSUE THREAD

**Issue by mellow2012** [nextcloud/polls#2880]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

when we open the link in the mail to th poll it looks like this:
https://example.cloud/index.php/apps/polls/vote/19
but in nextcloud we have this:
https://example.cloud/apps/polls/vote/19

the problem is that we have a black site.

### What did you expect, how polls should behave instead?

that the link in the mail are correct

### What steps does it need to replay this bug?

1.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

5.0.4

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [X] MacOs
- [X] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Check your configuration for `overwrite.cli.url` The CLI needs to know, which domain is to be used.

**Comment by mellow2012** [comment]
thanks that was it

**Comment by mellow2012** [comment]
@dartcafe sorry
it worked with the manual send mail 
but not with the reminder mail

how can i check my overwrite.cli.url is set correct

**Comment by dartcafe** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=index

check `overwrite.cli.url`, `htaccess.IgnoreFrontController` and the entries for getting clean URLs.

**Comment by mellow2012** [comment]
htaccess.IgnoreFrontController was it 
now it looks good

thank you

**Comment by Coernel82** [comment]
Thank you from me as well @dartcafe !
