### ISSUE TITLE
can access public poll with mandatory email.

### ISSUE THREAD

**Issue by punkyard** [nextcloud/polls#2886]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Error message when trying to access to public poll with email confirmation 
No log in NC Logging

![Capture d’écran 2023-05-01 à 14 54 21](https://user-images.githubusercontent.com/59349105/235455132-a3e0c86e-bb80-494b-a275-4e1d515d41d4.png)

### What did you expect, how polls should behave instead?

access a public poll with an email confirmation

### What steps does it need to replay this bug?

1. create a poll
2. make it public
3. activate mandatory email option
4. create public link
5. go to public link
6. try to answer an email and access the poll

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Other browser

Brave

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [X] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

Other/Don't know

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Configuration report

```shell
Nextcloud AIO v4.9.0
```

**Comment by dartcafe** [comment]
please add some server log information for analysis

**Comment by dartcafe** [comment]
I think, it can be closed, since this error is no more reproducable.
