### ISSUE TITLE
can't add circles to polls

### ISSUE THREAD

**Issue by punkyard** [nextcloud/polls#2887]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

If it's possible to add a user to a poll, it ain't to add circles.
When a user is clicked, it's name is added in the left column.
It won't with a circle.

![Capture d’écran 2023-05-01 à 14 39 06](https://user-images.githubusercontent.com/59349105/235458963-f3fa9e6c-f3cd-422c-b560-93a610efc83c.png)

### What did you expect, how polls should behave instead?

Add circles and give them permissions.

### What steps does it need to replay this bug?

1. create a poll
2. go to share
3. enter a circle name
4. click to add it

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

5.0.4

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Other browser

brave

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [ ] Linux
- [X] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

Other/Don't know

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
no related logs
```

**Comment by dartcafe** [comment]
This is fixed in #2875
