### ISSUE TITLE
Error in log when adding dedicated users to a poll

### ISSUE THREAD

**Issue by abysso2** [nextcloud/polls#290]
Hi, when i choose dedicated user in a poll, everything seems to work like a charm, but i get a error message in the log, when i choose the single users:

```
{"reqId":"LALR7nUvjCBxqSlBTv2O","level":3,"time":"2018-01-21T13:07:37+01:00","remoteAddr":"X.X.X.X","user":"me","app":"polls","method":"POST","url":"\/index.php\/apps\/polls\/search","message":"Array\n(\n    [0] => user_claus\n)\n","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
```

Any idea, why polls produces this error-message?

Regards,
Andreas

**Comment by abysso2** [comment]
Waht kind of additional info can i offer?

**Comment by splitt3r** [comment]
Sorry ^^. Would be nice if you could fill out the https://github.com/nextcloud/polls/blob/master/ISSUE_TEMPLATE.md with https://apps.nextcloud.com/apps/issuetemplate.

**Comment by dartcafe** [comment]
Should be fixed in current beta.
