### ISSUE TITLE
Unhandled exception during update to 5.0.5

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/polls#2900]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

sudo -u www-data php8.1 ./occ app:update --all
polls new version available: 5.0.5
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Polls\Db\TableManager::deleteAllDuplicates() in /var/www/nc_01/nextcloud/apps/polls/lib/Migration/RepairSteps/DeleteInvalidRecords.php:70
Stack trace:
#0 /var/www/nc_01/nextcloud/lib/private/Repair.php(127): OCA\Polls\Migration\RepairSteps\DeleteInvalidRecords->run()
#1 /var/www/nc_01/nextcloud/lib/private/legacy/OC_App.php(1068): OC\Repair->run()
#2 /var/www/nc_01/nextcloud/lib/private/legacy/OC_App.php(1005): OC_App::executeRepairSteps()
#3 /var/www/nc_01/nextcloud/lib/private/Installer.php(200): OC_App::updateApp()
#4 /var/www/nc_01/nextcloud/core/Command/App/Update.php(107): OC\Installer->updateAppstoreApp()
#5 /var/www/nc_01/nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php(298): OC\Core\Command\App\Update->execute()
#6 /var/www/nc_01/nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nc_01/nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nc_01/nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/nc_01/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#10 /var/www/nc_01/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nc_01/nextcloud/occ(11): require_once('...')
#12 {main}

After ./occ upgrade every thing seems fine again.

### What did you expect, how polls should behave instead?

Should cleanly update.

### What steps does it need to replay this bug?

1. Nextcloud 25 or 26 installation
2. Polls app version 5.0.4 installed
3. Update with cli: sudo -u www-data php8.1 ./occ app:update --all

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

5.0.5

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### Other Nextcloud version

Nextcloud 26

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "testcloud.emrich-ebersheim.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/testcloud.emrich-ebersheim.de\/",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "25.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "appstore.experimental.enabled": "true",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 8,
        "trashbin_retention_obligation": "auto",
        "maintenance": false,
        "default_language": "de",
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "files_readmemd",
            "co2clock",
            "data_request",
            "carnet"
        ],
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.8.0
  - announcementcenter: 6.5.1
  - appointments: 1.14.14
  - audioplayer: 3.3.1
  - breezedark: 25.0.2
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.3
  - carnet: 0.24.6
  - checksum: 1.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - co2clock: 0.1.3
  - collectives: 2.4.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.2
  - dashboard: 7.5.0
  - data_request: 1.12.0
  - dav: 1.24.0
  - deck: 1.8.3
  - dicomviewer: 1.2.4
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.3
  - files_downloadactivity: 1.16.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.2.0
  - gpxpod: 5.0.10
  - groupfolders: 13.1.3
  - health: 1.6.2
  - integration_github: 1.0.15
  - login_notes: 1.2.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.6
  - maps: 1.0.2
  - metadata: 0.18.0
  - news: 21.2.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.7.2
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2023.5.30
  - passwords_handbook: 2023.5.20
  - photos: 2.0.1
  - polls: 5.0.4
  - previewgenerator: 5.2.4
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.16.0
  - ransomware_protection: 1.14.0
  - recognize: 3.8.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.7.4
  - spreed: 15.0.5
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - terms_of_service: 2.1.0
  - text: 3.6.0
  - theming: 2.0.1
  - timemanager: 0.3.7
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_migration: 3.0.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.8
  - workflow_script: 1.10.0
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - files_external
  - suspicious_login: 4.2.1
  - twofactor_totp
  - user_ldap
```

**Comment by rteitge** [comment]
Same here. PHP 8.1 and NC 26.0.1

**Comment by dartcafe** [comment]
PLease just repeat the update. The problem seems to be, that the Nextcloud updates loads the classes too early before they get updated and the changed methods or classes cannot be executed properly. 

I could reproduce this behavior and on all instances repetition of the update installs polls correctly.

**Comment by dartcafe** [comment]
> I need to investigate this on cloned instance

Thanks for your support

> running the normal steps again gave other problems

What did you observe?

**Comment by RainerEmrich** [comment]
AFAIS you have to use './occ upgrade' in the nextcloud installation directory to recover.
A simple repetition isn't going to work.

**Comment by zmijunkie** [comment]
On upgrades I use to do a occ upgrade as well, also db:add-missing-indices/db:add-missing-columns/db:add-missing-primary-keys and as as last step I do app:update. I did these steps twice and got a repair error inbetween

```
Repair error: An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "WHERE"
LINE 1: ..._options" "t1" INNER JOIN "oc_polls_options" "t2" WHERE ("t1...
```
                                                             
Strange enough all tests pass now and hopefully everything wnt well

**Comment by dartcafe** [comment]
> 
> ```
> Repair error: An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "WHERE"
> LINE 1: ..._options" "t1" INNER JOIN "oc_polls_options" "t2" WHERE ("t1...
> ```

This is stange. Which database are you using? This error has nothing to do with this issue. 

> Strange enough all tests pass now and hopefully everything went well

Yeah. This is from the duplicate tidy. If the indexes got created, this is no problem, but in the end it should not happen. I have to check this again. Do you fancy opening another issue for that?
