### ISSUE TITLE
Tell me your opinion: Vote page design

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#2908]
### Your Message to the world

I am struggeling about the layout/design of the vote page. It seems a little bit noisy to at the moment. So please tell me what you think about the proposals.

### Current implementation:
* Unvoted or no votes have a red background.
* columns are hardly to differentiate in a new poll

light | dark
-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/03bccd30-5099-4e07-aebe-92e161890b31)|![grafik](https://github.com/nextcloud/polls/assets/26707476/95b2a1bc-fd60-4b4a-a694-c521e377a403)
![grafik](https://github.com/nextcloud/polls/assets/26707476/c2e2f3b5-caeb-414e-8c29-173bbd30f214)|![grafik](https://github.com/nextcloud/polls/assets/26707476/6326edb3-01ea-4a2e-aef3-7ae40cb27f87)

### Proposal A:
* Unvoted or no votes have no background.

light | dark
-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/489a5fd6-de9e-4385-9cb6-fbcbf0721077)|![grafik](https://github.com/nextcloud/polls/assets/26707476/b313086f-c0eb-401d-931e-76a28388bab6)

### Proposal B:
* alternating columns background separate the columns

light | dark
-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/438791f3-9510-4035-a6ec-aa398d4cdb41)|![grafik](https://github.com/nextcloud/polls/assets/26707476/e34d7380-bbf5-46fd-9671-cf8ca77bc24f)
![grafik](https://github.com/nextcloud/polls/assets/26707476/11f4d2c7-531d-4b92-8746-55eefde087a7)|![grafik](https://github.com/nextcloud/polls/assets/26707476/4089b261-400c-46b4-a530-102d3a7c86ee)

Proposal C:
* locked options are marked with an icon, to tell they are blocked, because of limited votes

light | dark
-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/3b0dc17f-c3c7-471b-92c5-3667d35da675)|![grafik](https://github.com/nextcloud/polls/assets/26707476/c5268370-ea5f-46b7-b5f3-5935ec516685)

FYI: There is an [old issue](https://github.com/nextcloud/polls/issues/1602) with proposals from a student's group which was only implemented partially. 

Opinions?
Suggestions?
Other proposals?

cc @nextcloud/designers

**Comment by Jerome-Herbinet** [comment]
I prefer proposal B.

**Comment by dartcafe** [comment]
Hey. Thanks. Can you also explain, what of the aspects leeded you to this conclusion?

**Comment by Jerome-Herbinet** [comment]
> Hey. Thanks. Can you also explain, what of the aspects leeded you to this conclusion?

I prefer the B proposal, because without the background colours on any 2 column, I find it hard to distinguish which data is in which column, quite simply.

**Comment by dartcafe** [comment]
Hey guys. Thanks a lot for your feedback so far. 

So I get you mostly prefer less red cells but a visual aid for the columns. But I also think alternating columns are too noisy. I tried the hover suggestion as an alternative as suggested by @jancborchardt.

Regarding Doodle: I have the feeling, they adopted some styles from polls 😆 It is quite similair. But they restricted a lot of options, which were possible before. 

Prototype:
hovering | closed status
-| - 
![16-05-_2023_11-22-49](https://github.com/nextcloud/polls/assets/26707476/f62fcbed-ef94-4cfd-9b26-29d7c8799bea)|![grafik](https://github.com/nextcloud/polls/assets/26707476/b60ea937-abb9-4bdc-8f20-3d1f632c0554) 

So what changed? 
* red background is removed from no/unvoted
* added hover state for the columns
* locked vote cells appear with a red background as well as the column hover has a red background.

Not sure, if the red background of locked columns is a little bit kind of over engeneering. 

>  Maybe you want to think about using the same font size for the different date/time elements for easier reading.

@martingwb A bigger font size would end in a new layout challange. 

>  Maybe some kind of separator (thin line) below the time would help to "group" the date/time elements.

Not a fan of it, since it adds more noise. We had that a while ago and removed it. 

>  An option to display any limit would help to make a poll more transparent for participants.

True. ATM it is only visible in the info drop down. --> Another issue is need for that.

**Comment by dartcafe** [comment]
> I like the current view more than the proposals, but it would be nice to have a grey background for the personal vote line. This would differ the columns.

Not sure if that helps for orientation as the personal row is always on top and has clickable icons with borders. But how does that support differentiating the columns, if the whoöe row is grey?

> 
> Additionally it would be nice to have an option how to deal with unvoted and no-votes. My idea is, to have the choice between:
> 
>     * show no-vote and unvoted (unvoted -> grey background, no-vote red-background with a X inside)
>     * show no-vote as unvoted (unvoted & no-votes with grey background)
>     * show unvoted as no-vote  (unvoted & no-votes with red background with a X inside)

We had that several times, but there is no different meaning between unvoted and no. 
* The participant can tell if he clicked for an option (unvoted=empty, any vote=icon)
* For any other participant there is no difference between a no-vote and an unvoted option, both say: No, not opted in. For the result it is the same message.
* The advantage: only yes-votes need an action.

Looking at doodle: No-votes and unvoted are both empty cells. Also no difference here.

**Comment by Metrax** [comment]
> > I like the current view more than the proposals, but it would be nice to have a grey background for the personal vote line. This would differ the columns.
> 
> Not sure if that helps for orientation as the personal row is always on top and has clickable icons with borders. But how does that support differentiating the columns, if the whoöe row is grey?
 
I wouldn't make the whole row grey, just some make bubbles like at the other cells. Than you can see, based on the size and the lines between the cells, to which date it is aligned.

I'm not good at css, but i've tried to simulate it:
![image](https://github.com/nextcloud/polls/assets/1061866/54fa5733-fcbc-4422-9dd6-d27fa06cb997)



> > Additionally it would be nice to have an option how to deal with unvoted and no-votes. My idea is, to have the choice between:
> > ```
> > * show no-vote and unvoted (unvoted -> grey background, no-vote red-background with a X inside)
> > * show no-vote as unvoted (unvoted & no-votes with grey background)
> > * show unvoted as no-vote  (unvoted & no-votes with red background with a X inside)
> > ```
> 
> We had that several times, but there is no different meaning between unvoted and no.
> 
> * The participant can tell if he clicked for an option (unvoted=empty, any vote=icon)
> * For any other participant there is no difference between a no-vote and an unvoted option, both say: No, not opted in. For the result it is the same message.
> * The advantage: only yes-votes need an action.
> 
> Looking at doodle: No-votes and unvoted are both empty cells. Also no difference here.

This depends on the usage. For finding a date to come together for a meeting no-votes and unvoted is the same.

At one of my associations, we are using date polls to make the attendance planing. Our members say yes for the days they can participate in our museum work, and no for the days, they can't. Here it would be very useful for the organizers to know the days, where the members said "no". The days they are undecided, will be left  as no-vote. The "Maybe" Vote is also not an option, because the members have click it for all days. On the days, where all association leaders have no time, normal members are doing the organization for the day, here it would be also helpful if anyone can see it. So, for this case it would be very helpful to see the difference between "no-votes" and "unvoted". My english is not the best, but i hope could show you why it can be important in some usecases to have the difference between "unvoted" and "no-votes". It would be nice if the poll-author make a decision about that :-)

**Comment by dartcafe** [comment]
> This depends on the usage. For finding a date to come together for a meeting no-votes and unvoted is the same.

This is exactly the purpose and main use case of this app. 

> The "Maybe" Vote is also not an option, because the members have click it for all days.

So this is a convinience issue, because users find it annoying to click through to the maybe-state. But if I understand you right, your use case is still valid without the convinience issue, right?

>It would be nice if the poll-author make a decision about that :-)

The poll author already made several decisions about that. 😉 

We have two states, which we need for a closed question: 
yes = opt-in
no = opt-out

This is all I need for planning a date; opt-in and opt-out. The maybe-option is the third state, which helps undecidable people to leave the backdoor open or to signal, they will decide later. 

Remark: I am also not a fan of this option, in a role of a poll organizer. I want answers, no more questions. A maybe is always bad for planning. 

Anyways we have the third option for a long time and users use it; me aswell, because of undecidab.... 😉 

Your request wants to redefine the unvoted option from "it is not a yes, so we take it as a no" to "no answer seems to be undecided, so we interpret it as maybe". In other words, all unanswered options (which is the initial state) are to be understood as maybe. In order of that we could remove the maybe-option, because it is not need anymore.

**Comment by jancborchardt** [comment]
> Yes, it is because of a delete button, wich appears on hovering. Was too lazy until now to fix that.

How about instead having that action on the right of the row, just like we do in the account management and other tables? It could then also be permanently visible, which makes it more accessible. And if further actions are needed, it can be a 3-dot action menu. :)

**Comment by dartcafe** [comment]
Wouldn't it be better to move it to an action menu of the avatar? A column on the right side has to be sticky, to make it visible, even if the vote pages gets wider. Since it is not a commonly used function a permanent visible row maybe deplaced. 

At least such action maybe expected as an avatar menu by the user.

**Comment by dartcafe** [comment]
Another extended proposal: 

light | dark
-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/3d787df6-0b46-4bc9-a12b-541e9d8954e3)|![grafik](https://github.com/nextcloud/polls/assets/26707476/a399f6b2-18e5-48e0-96b8-2d1b3582c28b)
![grafik](https://github.com/nextcloud/polls/assets/26707476/ce91be36-4381-4987-93ab-a1ccc4a36d9c)|![grafik](https://github.com/nextcloud/polls/assets/26707476/dec086b5-2cb5-456a-9b3f-de981e2d13b5)

**Comment by dartcafe** [comment]
The alternative style can be activated in the user settings. closing for now
