### ISSUE TITLE
How change svg application icon with png icon ?

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/polls#291]
Hello,

How can i change the default svg app icon by my png animated icon, please ?
Thanks,
![poll2](https://user-images.githubusercontent.com/16205280/35214640-236d0cf4-ff62-11e7-8572-c460e9352be1.png)

**Comment by dartcafe** [comment]
If you want to change it in your running system, make a grep for the filename you want to replace and change the references inse these files. 

Where do you want to place this icon? Everywhere the svg occurs or just on defined places?

**Comment by Ludovicis** [comment]
OK thanks dartcafe, i have find. i must change this file:
apps/polls/lib/AppInfo/Application.php
apps/polls/css/main.css
apps/polls/css/main.scss

Thanks,
