### ISSUE TITLE
Poll result downloads do not contain any given votes

### ISSUE THREAD

**Issue by stevleibelt** [nextcloud/polls#2920]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I am having an ongoing poll with a lot of options.
The poll contains 38 options and has an introduction text over 13 lines with a total of 683 characters.

Some options have votes already as seen in the screenshot.

![image](https://github.com/nextcloud/polls/assets/2287220/187ee35f-8b97-4e83-806a-43c9866b8364)

Once downloaded the result of the **ongoing** poll, I get an empty result download. I've tried open document, csv, excel or html.

![image](https://github.com/nextcloud/polls/assets/2287220/cab52189-fd19-464f-a6c5-000ee6aa2531)

The download contains the introduction text as well as the options but no votes.

### What did you expect, how polls should behave instead?

I would have expected that the download contains entries in the participants with a corresponding check the selected option.

### What steps does it need to replay this bug?

![image](https://github.com/nextcloud/polls/assets/2287220/5341fd0e-d557-45b4-b6e7-3c8f9e32d425)

I am running the following configuration:

* PHP 8.0.28
* Nextcloud 26.0.1
* polls: 5.0.5

My nextcloud instance is a very old one and exists since the dates of owncloud. I am using polls since it was released but all is updated frequently.
This is the first time I am running a poll with that much options and the first time I am having this issue.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [X] Other/Don't know

### Other browser

Tor, Librewolf

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [X] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### PHP engine version

PHP 8.0

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Configuration report

```shell
{
    "system": {
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.bazzline.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "log_rotate_size": 33554432,
        "singleuser": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": "1.5"
        },
        "updater.release.channel": "stable",
        "mail_smtpsecure": "ssl",
        "overwrite.cli.url": "https:\/\/my.domain.tld",
        "data-fingerprint": "38b16dc45686a6e09394ae5887b2bc79",
        "mail_smtpauthtype": "LOGIN",
        "default_language": "en",
        "force_language": false,
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "",
        "mail_smtpdebug": false,
        "app_install_overwrite": [
            "calendar",
            "files_reader",
            "ocsms",
            "dashboardcharts"
        ],
        "has_rebuilt_cache": true,
        "encryption.legacy_format_support": true,
        "mail_sendmailmode": "pipe",
        "tempdirectory": "\/home\/my_home_user\/just\/a\/path\/to\/the\/data\/temp",
        "mysql.utf8mb4": true,
        "default_phone_region": "DE",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
php occ app:list
Enabled:
  - admin_audit: 1.16.0
  - analytics: 4.9.1
  - audioplayer: 3.3.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - cloud_federation_api: 1.9.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - encryption: 2.14.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_retention: 1.15.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - forms: 3.2.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - maps: 1.0.2
  - news: 21.2.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - polls: 5.0.5
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_email: 2.7.3
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - activity: 2.18.0
  - apporder: 0.15.0 (installed 0.15.0)
  - circles: 26.0.0 (installed 23.1.0)
  - comments: 1.16.0 (installed 0.2)
  - dashboardcharts: 0.1.3
  - event_update_notification: 2.2.0 (installed 2.2.0)
  - files_markdown: 2.4.0 (installed 2.4.0)
  - files_mindmap: 0.0.27 (installed 0.0.27)
  - files_trashbin: 1.16.0 (installed 0.4)
  - files_versions: 1.19.1 (installed 1.0.3)
  - firstrunwizard: 2.15.0 (installed 1.0)
  - health: 1.6.2 (installed 1.6.2)
  - quota_warning: 1.17.0 (installed 1.17.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - suspicious_login: 4.4.0 (installed 4.2.1)
  - systemtags: 1.16.0 (installed 1.13.0)
  - tables: 0.5.0 (installed 0.5.0)
  - timemanager: 0.3.7 (installed 0.3.7)
  - timetracker: 0.0.79 (installed 0.0.79)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.3.1)
  - weather_status: 1.6.0 (installed 1.3.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional Information

Thanks for all the fish so far!

**Comment by Elorius840** [comment]
Same issue with a fresh installtion of Nextcloud 26.0.1.
Textpoll with 20 options and currently 50 users.

**Comment by Elorius840** [comment]
Finally, i found the bug. 
If you delete a user with existing votes the problem occurs. If you delete the correspondig votes from the database the export function is again working correctly.
My suggestion to the developers:
Make sure that existing votes of a user are deleted with the user itself.

**Comment by stevleibelt** [comment]
This makes absolutely sense since I needed to create test users and test polls for this poll to check that all is working
And guess what? Since this are test users and test polls, I've deleted them as poll admin via the web frontend.

**Comment by stevleibelt** [comment]
@Elorius840 to ease up my search, would you be so kind and tell me the tables I have to look into?

**Comment by Elorius840** [comment]
I was just writing the answer ;-) 
Well solved!

**Comment by dartcafe** [comment]
Good to know it is solved for you at the moment. But it still stays a bug from users without email address.

**Comment by stevleibelt** [comment]
> Good to know it is solved for you at the moment. But it still stays a bug from users without email address.

Exactly. Thanks for adding it to the next milestone!
