### ISSUE TITLE
Unable to add date options in NC26

### ISSUE THREAD

**Issue by ttenroK** [nextcloud/polls#2930]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

After the upgrade to NC26 it isn't possible to add new date options to a poll. After trying to add a date, an error appears at the right top, e.g. "Fehler beim Hinzufügen von 5. Juni 2023"/"Error when adding 5 June 2023".

### What did you expect, how polls should behave instead?

Instead, the date option should be added to the poll.

### What steps does it need to replay this bug?

1. Upgrade to NC26
2. Create a new poll
3. Try to add a new date as option

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

5.0.5

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
session heartbeat polling started session-heartbeat.js:103:9
Registering notifications container as a menu NotificationsApp.vue:219
Notifications permissions granted NotificationsApp.vue:453
Has notify_push enabled, slowing polling to 15 minutes NotificationsApp.vue:231
Polling interval updated to 900000 NotificationsApp.vue:413
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:275
Got notification data NotificationsApp.vue:376
Polling interval updated to 900000 NotificationsApp.vue:413
XHRPOST
https://<mydomain>/apps/polls/option
[HTTP/2 500 Internal Server Error 551ms]

Error adding option: <!DOCTYPE html>
<html>
<head>
    <title>Internal Server Error - Storage Share - Hetzner Online GmbH</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <link rel="apple-touch-icon" sizes="180x180" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAMAAAAKE/YAAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAA9lBMVEXVDC3bMEzqiJjzucP1xc33ztX1xs7zusTri5vcNFDWFDTjX3XtlaTvo6/xrrnvpLHtmaflaH3YGzrndIf++/z//////f3oe43eQlz75ur98vPjWnHcM0///P3//v7dO1XWFTT76Ov+9/jaKUbqhpbskaDjXHLpfpDxr7rzu8XriprxrLf2ytHtmKbzvMX0vcb2zNPum6n0v8j2zdT3z9b30Nf30df42N3bLEnwqLT76u3unqv2ydDunKnsj57qhZbskJ/kZnrpgJHbL0v++vvcN1LXGjn87/HmcYThUGf99PXqhJXwqbXwqrbZI0HmcIPwpbLZJEIhxI7dAAAAAWJLR0QV5dj5owAAAAlwSFlzAAAFMQAABTEBt+0oUgAAAAd0SU1FB…
 
Object { error: {…} }
 
Object { payload: {…} }
options.js:185:3



```

### Additional client environment information

Nextcloud is hosted on Hetzner-servers

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### PHP engine version

Other/Don't know

### Other PHP version

8.2

### Database engine

MySQL

### Database Engine version or other Database

10.5

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
-
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - appointments: 1.15.1
  - audioplayer: 3.3.1
  - bruteforcesettings: 2.6.0
  - cadviewer: 8.70.4
  - calendar: 4.3.4
  - calendar_news: 1.1.7
  - calendar_resource_management: 0.5.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.5.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - documentserver_community: 0.1.13
  - external: 5.1.0
  - extract: 1.3.5
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_accesscontrol: 1.16.0
  - files_automatedtagging: 1.16.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - files_zip: 1.4.0
  - firstrunwizard: 2.15.0
  - forms: 3.3.0
  - fulltextsearch_elasticsearch: 26.0.0
  - groupfolders: 14.0.2
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - memories: 5.1.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - polls: 5.0.5
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - registration: 2.1.0
  - related_resources: 1.1.0-alpha1
  - serverinfo_hetzner: 1.18.0
  - settings: 1.8.0
   - sharebymail: 1.16.0
  - spreed: 16.0.4
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tables: 0.5.0
  - talk_matterbridge: 1.26.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
   - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - encryption: 2.14.0
  - end_to_end_encryption: 1.12.5 (installed 1.12.5)
  - files_external: 1.18.0
   - mail: 3.1.1 (installed 3.1.1)
  - ownpad: 0.7.1 (installed 0.7.1)
  - pandoc: 0.5.0 (installed 0.5.0)
   - richdocuments: 8.0.2 (installed 8.0.2)
  - theming_customcss: 1.14.0 (installed 1.14.0)
   - user_ldap: 1.16.0
  - wopi: 3.5.11 (installed 3.5.11)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by dartcafe** [comment]
The server log is needed, since it is an 500 error.

BTW: The warnings can get excluded from the console log.

**Comment by ttenroK** [comment]
> The server log is needed, since it is an 500 error.
> 
> BTW: The warnings can get excluded from the console log.

Hmm... I don't have any logs. If I navigate to `https://<mydomain>/settings/admin/logging` there are no server logs. Even when I activate all levels of logging.

**Comment by dartcafe** [comment]
That's bad. Without it, I can only guess what the error can be. 

Just a try: call `occ polls:db:rebuild` to check or fix the db structure.

**Comment by dartcafe** [comment]
because there is a bug.

**Comment by JayBeRayBearGun** [comment]
i've got the same issue,... but occ polls:db:rebuild does not work, it generates errors

**Comment by bburdette** [comment]
upgraded 23->24->25 and couldn't add poll options, users could respond to polls.  `occ polls:db:rebuild` appears to have fixed it for me too.
