### ISSUE TITLE
Cannot delete my own poll

### ISSUE THREAD

**Issue by xylo** [nextcloud/polls#294]
### Steps to reproduce
1. Create a poll
2. Open the poll
3. Go to poll settings
4. Click on "delete poll" (german: "Umfrage löschen")
5. Click on "OK" when the confirmation dialog appears

### Expected behaviour
I expect the poll to get deleted.  Moreover there should be some sort of server communication.

### Actual behaviour
Except the confirmation dialog disappears nothing else happens when I click on "OK".  There is not even a communication with the server.

### Server configuration

**Operating system:** Linux 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64

**Webserver:** Apache/2.4.25 (Debian) SVN/1.9.5 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_jk/1.2.42 PHP/5.6.30-0+deb8u1 mod_python/3.3.1 Python/2.7.13 OpenSSL/1.0.2l (cgi-fcgi)

**Database:** mysql 10.1.26

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, PDO, curl, gd, gmp, imap, json, ldap, mcrypt, mysql, mysqli, OAuth, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, readline, sqlite3, xmlrpc, xsl, mhash, Zend OPcache

**Nextcloud version:** 12.0.5 - 12.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:** 

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - calendar: 1.5.7
  - contacts: 2.0.1
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - grauphel: 0.6.6
  - issuetemplate: 0.3.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - polls: 0.8.1
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - comments
  - encryption
  - files_external
  - files_pdfviewer
  - logreader
  - nextcloud_announcements
  - richdocuments
  - serverinfo
  - survey_client
  - systemtags
  - theming
  - user_ldap

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "dbname": "system-owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "defaultapp": "calendar",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
***REMOVED SENSITIVE VALUE***
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{***REMOVED SENSITIVE VALUE***}"
                ]
            }
        ],
        "loglevel": 3,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

* Firefox 57.0.4 (64-Bit)

**Operating system:**

* Ubuntu 17.10 (Linux 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

#### Nextcloud log (data/nextcloud.log)

It's empty.

#### Browser log

```
Laden fehlgeschlagen für das <script> mit der Quelle "blob:https://MY_SERVER.de/1512c53c-bba1-4ba7-a7ef-496683641ec1".
9442MFZDDKJDm4Iu:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf blob:https://MY_SERVER.de/1512c53c-bba1-4ba7-a7ef-496683641ec1 blockiert ("script-src 'nonce-NFFwT0JiSHNrVjRrZThUOFR4bXMrOG1jZWF0UmdyY1p0ZkI0MTRkQ0NnST06cEdFQVI5ZUo2UVppRFl5OUlXeklsZnpQSWU4LzZQRktoNXhOb09nSld6ST0=' 'unsafe-eval'").
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://MY_SERVER.de/core/vendor/core.js?v=cd62bb79da81bce3acc4b784b9deedc4
Source-Map-Adresse: purify.min.js.map
[Weitere Informationen]
TypeError: form is undefined
[Weitere Informationen]
app.js:8:3
deletePoll
https://MY_SERVER.de/apps/polls/js/app.js:8:3
<anonym>
https://MY_SERVER.de/apps/polls/js/vote.js:123:3
dispatch
https://MY_SERVER.de/core/vendor/core.js:3:6414
add/r.handle
https://MY_SERVER.de/core/vendor/core.js:3:3224
```

**Comment by dartcafe** [comment]
Confirmed. Deleting is only possible in the list of polls. Deleting from the details view does not work. Thanks for reporting.

**Comment by dartcafe** [comment]
fixed in branch https://github.com/nextcloud/polls/tree/fix-delete-poll 
PR #295. Can you test this?

**Comment by xylo** [comment]
Thanks for fixing this and thanks for the hint that I can also delete the poll in the list view.

Regarding testing: Sorry, I don't have the time to test the git version right now, but I will test the next app release.

**Comment by dartcafe** [comment]
My tests were good. Will merge after review.
