### ISSUE TITLE
Wrong german translation

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/polls#2976]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

We noticed a few wrong translations (German language):

![cloud](https://github.com/nextcloud/polls/assets/100593683/a8a0ca50-2c4f-4cbe-afb7-3c3ee85e3d04)

### What did you expect, how polls should behave instead?

Our suggestions are (see also https://github.com/nextcloud/polls/blob/master/l10n/de.json) :

1) "Enter your name or nickname" was already fixed by https://github.com/nextcloud/polls/commit/95ab05ee5f489dfff6fd36b2de509c8defd6ce6e#diff-7c35eadec8d53ccf9315e025b8f81c2caa571bc228e69a65865dc43b4c49d79fR328

2) "Enter your email address to get your personal access link." 
   currently translated with: "Gebe deine E-Mail-Adresse ein, um deinen persönlichen Zugangslink zu erhalten."
   should be translated to: "Gib deine E-Mail-Adresse ein, um deinen persönlichen Zugangslink zu erhalten."
   
3) "Optional email address" : 
   currently translated with: "Optionale E-Mail-Adresse"
   should be translated to: "E-Mail-Adresse (optional)"

4) "Remember me for 30 days" : 
   currently translated with: "Für 30 Tage an mich erinnern"
   should be translated to: "Daten 30 Tage lang merken"
   

### What steps does it need to replay this bug?

1. Open a poll shared by link as unauthorized user (guest user)

### Installation method

Installed/updated using occ

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

5.0.5

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.0

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other/Don't know

**Comment by dartcafe** [comment]
Translations are done by the community at [Transifex](https://www.transifex.com/). 

I updated the german strings according to your proposals. Thanks a lot for your participation.

**Comment by ZID-TU-Graz** [comment]
Thank you very much for updating, 
Unfortunately the changes to the mailadress-textbox mishappened in english/are missing an e
"Email adress (optional)" should be "E-Mail-Adresse (optional)"
Best regards!

screenshot:
![image1](https://github.com/nextcloud/polls/assets/100593683/c0a3f5c1-519e-43f5-881b-ce6c600c406c)
