### ISSUE TITLE
App doesn't cooperate with `occ db:convert-type`

### ISSUE THREAD

**Issue by notEvil** [nextcloud/polls#2980]
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When converting to another db type, the tables are not created and therefore not converted.

In

https://github.com/nextcloud/polls/blob/0a8c7451b33c962db01ad65599ca5166421096ce/lib/Migration/Version050100Date20230515083001.php#L48

`$schemaClosure` is not used and therefore migration to a different schema/database is currently not supported.

### What did you expect, how polls should behave instead?

Well, the app should cooperate by using `$schemaClosure` and return the schema (OC\DB\SchemaWrapper) the closure returns. See https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html
If it does that, it shouldn't do
https://github.com/nextcloud/polls/blob/0a8c7451b33c962db01ad65599ca5166421096ce/lib/Migration/Version050100Date20230515083001.php#L51
since Nextcloud`s MigrationService takes care of the rest (e.g. uses the correct connection). I have tested this and it fixes the issue.

### What steps does it need to replay this bug?

1. use `occ db:convert-type`
2. observe rows `oc_polls_...` under "The following tables will not be converted:"

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.1.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Database Engine version or other Database

11.0.2

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Feel free to open a new PR with your suggested changes.

**Comment by dartcafe** [comment]
I changed the migration methods by doubling the code. Something I wanted to avoid but there was no elegant way to use the ISchemaWrapper and the DBAL\Schema in one method. Thanks for your PR, it si obsolete, but I took me into the right direction. 

Actually, I was never aware of `occ db:convert-type`. 

The upcomming beta will include the fix. So if you are able to proof the fix, I would be happy.

**Comment by notEvil** [comment]
Thanks! I migrated to Nextcloud All-in-One and therefore can't easily try the command anymore (would need to mess with the Docker container). And the old install is defunct, so can't promise.
