### ISSUE TITLE
Sharing doesn't work / tab empty

### ISSUE THREAD

**Issue by ueismann** [nextcloud/polls#2987]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Set up a poll, however the sharing tab remains empty and does not display any options for sharing

### What did you expect, how polls should behave instead?

sharing tab should display sharing options

### What steps does it need to replay this bug?

1. create new poll
2. click '"sharing"

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.1.0

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### Other browser

Brave

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### Other Nextcloud version

26.0.2

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by ueismann** [comment]
Switching browsers or turning off Brave Shields solved the issue....

**Comment by dartcafe** [comment]
Duplicate. Please search the issues first.

> This issue is not already reported on Github (I've searched it).

https://github.com/nextcloud/polls/issues?q=%22share+tab%22

delivers i.e.

* https://github.com/nextcloud/polls/issues/2769
* https://github.com/nextcloud/polls/issues/2545
* https://github.com/nextcloud/polls/issues/2330
