### ISSUE TITLE
Nextcloud - & customm menu logo do overlapping each other

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/polls#2997]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Nextcloud - & customm menu logo do overlapping each other
![ScreenShot047](https://github.com/nextcloud/polls/assets/32612067/b0c83f56-ea2a-46a2-9c51-832e62f5d3be)

### What did you expect, how polls should behave instead?

no overlapping should happen

### What steps does it need to replay this bug?

1. create a public poll and click on the public link

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

polls: 5.2.0

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

MS EDGE

### Additional client environment information

Windows 11 HOME

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Please recreate the issue in the corresponding repository.
