### ISSUE TITLE
Polls doesn't check for conflicts on calendars

### ISSUE THREAD

**Issue by Luncheon3462** [nextcloud/polls#3002]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

In my calendar listing, there are 2 calendars that have been shared with me internally (from other nextcloud users in my instance).   In the polls settings, I have selected these 2 calendars to be checked for conflicts under "Calendar Check".   However, when selecting time and date options for a meeting poll, the conflicts are not identified.   In other words, if I select a date and time when there is already a meeting on one of the 2 internally shared nextcloud calendars, the conflict in not noted in polls.

### What did you expect, how polls should behave instead?

The conflict should be noted in polls

### What steps does it need to replay this bug?

1.  Select a date and time with a conflicting event on a calendar that have been selected for conflict checks.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 7.3

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
This is no bug, but normal behavior. Unless a user is not an attendee of an event, it will not be recognized as a conflict. The existence of an event alone does not affect busy times.

In the end, Polls can't do anything here because the event is not even reported in the query.
