### ISSUE TITLE
Putting current user on top

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#305]
How about something like this? 
![grafik](https://user-images.githubusercontent.com/26707476/35808508-47a5693e-0a86-11e8-83ef-ca717f6caec3.png)

**Comment by v1r0x** [comment]
I think it looks strange with the buttons between the two vote blocks. I'd keep it as it is :)

**Comment by dartcafe** [comment]
That's just a quick throw. The intention is, to seperate the current user from the table of other votes and put his action in the direct view. In the case, that there is a huge amount of participants, the current user has to scroll down to his vote, which maybe out of sight then. 

An unexperienced user may be confused, if he doesn't see his options right on opening the poll. This also regarding the intention of #276.

**Comment by jancborchardt** [comment]
Totally agree the current user should be on top, directly visible.

We should put the "Vote" button on the right, as you go through the options from left to right, as with reading. Then it can all fit in one row. The "Receive notifications" can be inside of a 3-dot-menu popover.

**Comment by dartcafe** [comment]
I think about a second header, like in the create page, so we can put sticky controls there.  What do you think?
![grafik](https://user-images.githubusercontent.com/26707476/48575198-91861700-e911-11e8-9180-f621fa5d9dcd.png)

**Comment by dartcafe** [comment]
The idea is to have all action buttons in one place regardless the amount of options. On smaller screens and on mobile the action buttons can go out of view. So it is easier to finih the vote without scrolling to the bottom. Same for the vote page with many participants or with many options.
![grafik](https://user-images.githubusercontent.com/26707476/48755652-5b8cbe00-ec96-11e8-881a-92d6894b4d83.png)
