### ISSUE TITLE
Several French translation errors

### ISSUE THREAD

**Issue by remileblond67076** [nextcloud/polls#3060]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Several French translation errors

### What did you expect, how polls should behave instead?

- confusion between "public" and "publique"
- Lack of consistency between infinitive and present tense
- Some confusing translations

### What steps does it need to replay this bug?

This problem can be observed when the application is configured in French.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

PostgreSQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by solracsf** [comment]
This must be fixed at Transifex.
https://explore.transifex.com/nextcloud/nextcloud/

**Comment by remileblond67076** [comment]
Thanks for advice.
Transifex updated.
