### ISSUE TITLE
NC:Polls Upgrade/Migration Bug

### ISSUE THREAD

**Issue by Gigulon** [nextcloud/polls#3068]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

While trying to Upgrade via CLI, Polls App v.3.8.4 to 5.2.0 or higher Upgrade fails with :

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1005 Can'\''t create table `bcbox`.`oc_polls_comments` (errno: 150 "Foreign key constraint is incorrectly formed")\n'

The Upgrade process tries to change cloumn types from "int" to "bigint" but that's not working because of Foreign key constraint.

For example, changes from 3.8.4 to 5.2.0 -:
- oc_polls_polls ID changed from int to BIGINT
- oc_polls_comments poll_id changed to BIGINT
- oc_polls_comments id changed to BIGINT

After Upgrade, Polls is working but the DB Scheme has not changed.

### What did you expect, how polls should behave instead?

Maybe set foreign_key_checks=0; before tying to update.

### What steps does it need to replay this bug?

1. Install Nextcloud 22, 23 or 24
2. Install Polls App v.3.8.4
3. Upgrade Nextcloud to > 25, 26, 27
4. Upgrade to Polls 5.2.0 via "occ app:update polls"

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

3.8.4

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### Other browser

Shell (CLI)

### NC version

Other/Don't know

### Other Nextcloud version

Nextcloud 24.0.12.5

### PHP engine version

PHP 7.3

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Hmm. Actually all indexes and foreign key constraints get removed before the migration and rebuild at the and. At least they should. 

Have you tried `occ polls:db:rebuild`?

**Comment by Gigulon** [comment]
Sorry. Using Polls 5.3.2 fixed this issue.

Thanks
