### ISSUE TITLE
Dates on android browser broken

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/polls#307]
The android browser (xiaomi) shows wrong date format.

Firefox on the same device works well.

Info about phone:
- Xiaomi Mi-4c
- Android: 7.0 (MIUI 8.3)
- com.android.browser:  V8.5.14

Thank you.

![screenshot_2018-02-07-13-23-14-689_com android browser](https://user-images.githubusercontent.com/20214043/35916878-3dd75ae8-0c0c-11e8-8d61-6c1a97a33fea.png)
![screenshot_2018-02-07-13-23-55-292_com android browser](https://user-images.githubusercontent.com/20214043/35916879-3df5c21c-0c0c-11e8-9f4a-019a8f761d53.png)

**Comment by lachmanfrantisek** [comment]
## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** nginx/1.13.8 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit

**PHP version:** 7.2.2
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** docker image hoellen/nextcloud:13.0

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - announcementcenter: 3.1.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - caniupdate: 0.1.2
 - checksum: 0.3.5
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.6
 - deck: 0.3.0
 - drop_account: 0.0.6
 - dropit: 0.1.0
 - end_to_end_encryption: 1.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.2.2
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - gpxpod: 2.2.2
 - groupfolders: 1.2.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.9
 - metadata: 0.6.0
 - mood: 0.3.3
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - registration: 0.3.1
 - richdocuments: 1.12.40
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.0.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - telephoneprovider: 1.0.1
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - twofactor_u2f: 1.5.1
 - updatenotification: 1.3.0
 - w2g2: 0.9.9
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard
 - music
 - phonetrack
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "logdateformat": "Y-m-d H:i:s",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

**Comment by splitt3r** [comment]
Could you somehow look up which timezone the xiaomi browser requests by default? Looks like a browser problem.

**Comment by lachmanfrantisek** [comment]
I'm not sure, how to test it. I've found [this site](http://comingnext.sourceforge.net/drupal7/localtime). Which returns same results for both browsers. Any idea, how to get this information?

Thank you!

## Xiaomi browser
```
Browser Localtime/Timezone Test

Your browser is telling me that your local time is Thu Feb 08 2018 23:52:00 GMT+0100 (CET)
Winter date: Sat Jan 15 2000 15:00:00 GMT+0100 (CET)
Summer date: Sat Jul 15 2000 15:00:00 GMT+0200 (CEST)
winter offset : -60
summer offset : -120
corrected localtime: Wed Feb 07 2018 23:52:00 GMT+0100 (CET)
corrected summer offset: -120
DST difference for summer time: 1


Current date/time: Thu Feb 08 2018 23:52:00 GMT+0100 (CET)
Last minute before DST change occurs in 2018: 03/25/2018 01:59:00 and 10/28/2018 02:59:00
```

## Firefox

```
Browser Localtime/Timezone Test

Your browser is telling me that your local time is Thu Feb 08 2018 23:54:43 GMT+0100 (CET)
Winter date: Sat Jan 15 2000 15:00:00 GMT+0100 (CET)
Summer date: Sat Jul 15 2000 15:00:00 GMT+0200 (CEST)
winter offset : -60
summer offset : -120
corrected localtime: Wed Feb 07 2018 23:54:43 GMT+0100 (CET)
corrected summer offset: -120
DST difference for summer time: 1


Current date/time: Thu Feb 08 2018 23:54:43 GMT+0100 (CET)
Last minute before DST change occurs in 2018: 03/25/2018 01:59:00 and 10/28/2018 02:59:00
```

**Comment by lachmanfrantisek** [comment]
Results from [another webpage](http://browserspy.dk/date.php):


## Xiaomi browser
```
Test	Result
Time and date	Thu Feb 08 2018 23:59:23 GMT+0100 (CET)
GMT'ed	Thu, 08 Feb 2018 22:59:23 GMT
Locale String	Thu Feb 08 2018 23:59:23 GMT+0100 (CET)
Time-Zone offset	-60 minutes
Milliseconds since January 1, 1970	1518130763000
Internet Beat	@ 999
Time on browserspy.dk server	Thu, 08 Feb 2018 16:59:23 -0600
Time on your PC	Thu Feb 08 2018 23:59:23 GMT+0100 (CET)
Difference between server and PC time	0 seconds
```

## Firefox
```
Test 	Result
Time and date 	Thu Feb 08 2018 23:58:04 GMT+0100 (CET)
GMT'ed 	Thu, 08 Feb 2018 22:58:04 GMT
Locale String 	8. 2. 2018 23:58:04
Time-Zone offset 	-60 minutes
Milliseconds since January 1, 1970 	1518130684000
Internet Beat 	@ 998
Time on browserspy.dk server 	Thu, 08 Feb 2018 16:58:03 -0600
Time on your PC 	8. 2. 2018 23:58:04
Difference between server and PC time 	1 seconds 
```

**Comment by dartcafe** [comment]
Strange presentation. I guess the js interpretor is not able to handle the date functions (toLocaleString) properly. 

This code should result in the date parts (month, day, day of week, time), but it seems, that it always produces the complete date string instead of it components. 

https://github.com/nextcloud/polls/blob/80e58ac0bd4b64f2d7ef5d68109bf696cdd0c6d6/js/vote.js#L138-L144

So, there will be no quick solution, if not somebody tries to fix that. I would investigate into the locale implementation later. 

After some googeling: the locale implementation ist not supported from all os/browser combination, especially in combination with android.

**Comment by lachmanfrantisek** [comment]
Thank you for time.

Honestly, I am not a web developer, but would be glad, if you could resolve it in the future -- we sadly cannot force people not to use this browser. Especially if it is the default one.

Nevertheless, thanks!
