### ISSUE TITLE
Can't install the app on Nextcloud 13

### ISSUE THREAD

**Issue by pierreonthenet** [nextcloud/polls#308]
### Steps to reproduce
1. Update NextCloud from 12 to 13
2. Try to install the Poll app from Applications list (/index.php/settings/apps?category=tools)
3. After clicking on "Activate", the message "Could not extract app polls" is shown under the button

### Expected behaviour
The app should have been installed and activated

### Server configuration
NextCloud 13 hosted on Niloo.fr

**PHP version:** 5.6.33

**Nextcloud version:**  13

**Where did you install Nextcloud from:** Update from 12.0.4

```
No errors have been found.
```

**List of activated apps:**

```
Activity 2.6.1
Auditing / Logging 1.3.0
Bookmarks 0.10.1
Brute-force settings 1.0.3
Calendar 1.6.0
Can I update? 0.1.2
Checksum 0.3.5
Collaborative tags 1.3.0
Comments 1.3.0
Contacts 2.0.1
Default encryption module 2.0.0
Deleted files 1.3.0
Federation 1.3.0
File sharing 1.5.0
First run wizard 2.2.1
Gallery 18.0.0
Log Reader 2.0.0
Monitoring 1.3.0
Nextcloud announcements 1.2.0
Notes 2.3.2
Notifications 2.1.2
Password policy 1.3.0
PDF viewer 1.2.0
Share by mail 1.3.0
Text editor 2.5.1
Theming 1.4.1
Update notification 1.3.0
Usage survey 1.1.0
Versions 1.6.0
Video player 1.2.0
```

**Nextcloud configuration:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'datadirectory' => '/cloud/data',
  'dbtype' => 'sqlite3',
  'version' => '13.0.0.14',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'share_folder' => '/Shared',
  'mail_smtpmode' => 'php',
  'secret' => '',
  'forcessl' => true,
  'mail_from_address' => 'noreply',
  'mail_domain' => '',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => 3,
  'trashbin_retention_obligation' => 'auto',
  'overwrite.cli.url' => '',
  'overwriteprotocol' => 'https',
  'updater.secret' => '',
);

```

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 58.0.1

**Operating system:** Mac OS 10.11.6

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"WntO238AAAEAADPOpuAAAACd","level":3,"time":"2018-02-07T19:09:23+00:00","remoteAddr":"88.185.216.18","user":"pierre","app":"core","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"Could not extract app polls","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```

**Comment by splitt3r** [comment]
Can´t reproduce that with the steps you described.

**Comment by dartcafe** [comment]
Tried it as well under diiferent circumstances and couldn't reproduce this. There seems to be problem when extracting the app to the apps folder. Could this be an access problem? 

Could you please check the existence of the polls folder inside the apps folder and it's attributes /read/write/execute and the owner of the folders?

**Comment by dartcafe** [comment]
No further information?

**Comment by pierreonthenet** [comment]
I'm sorry, I didn't had time to test it further more... I'll try tonight.

**Comment by pierreonthenet** [comment]
I'm trying to figure out the source of the problem by reading the source... It's not really easy but it seams to be a NextCloud problem.
I'll let you know if I find anything.
Thank you.

**Comment by splitt3r** [comment]
Have you tried downloading the app from https://apps.nextcloud.com/apps/polls and installing it manually?
