### ISSUE TITLE
Select range - Option for "Individual entry for each day"

### ISSUE THREAD

**Issue by natrius** [nextcloud/polls#3081]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

Sometimes i need to create a entry for a whole month to find a suitable date for everyone. Currently i had to create a entry for every day manually and there is no quick way to achieve this.

### Describe possible solutions

When activating "Select range" add a checkbox with "Individual entry for every day in that range" (Probably a shorter name would be good :D )

![image](https://github.com/nextcloud/polls/assets/7243447/b0e4e0ef-6d4d-4eff-aa30-df5a7135ea0d)

### Additional context

I use this quite often. Friends often use https://nuudel.digitalcourage.de/ for example, there is a extra button for "Add range dates" and it creates a entry for each day.

**Comment by dartcafe** [comment]
Why not create the first option and then clone them?
![grafik](https://github.com/nextcloud/polls/assets/26707476/10f9df7f-5bf7-47c8-9277-62d356cbc447)
![grafik](https://github.com/nextcloud/polls/assets/26707476/20eae463-a894-4d80-bb23-3fae52a11568)
![grafik](https://github.com/nextcloud/polls/assets/26707476/cd38b3a2-0260-4350-b447-6b06398d9303)

**Comment by natrius** [comment]
I tried it now and it works. 

It did not occur to me to find that setting under "Clone option". But i don't really have an idea to make it better findable currently :/

Thanks!

**Comment by dartcafe** [comment]
I assume, I can close it?!
