### ISSUE TITLE
Poll creation button not sufficiently visible

### ISSUE THREAD

**Issue by remileblond67076** [nextcloud/polls#3082]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

The create poll button is not sufficiently visible, as it is displayed in a very light color.
![image](https://github.com/nextcloud/polls/assets/65656372/5c39676c-5563-45f1-8bce-b01f73a6e1cd)

It should appear in a much more saturated color, so as to jump out at you, as is done in the "Agenda" application, for example.
![image](https://github.com/nextcloud/polls/assets/65656372/4c3459d2-e874-44bc-beb0-09153a90dace)

Many inexperienced users complain that they can't figure out how to create a new survey, even though the button is right there in front of them.

This small change could really improve the user experience of this excellent tool.

Thank you in advance.

### Describe possible solutions

Use vivid colors, as is done in "Agenda" application, for example.
![image](https://github.com/nextcloud/polls/assets/65656372/b685d1cb-bfda-4b9a-bd4f-c959d76f7c2a)

**Comment by dartcafe** [comment]
Yes. agree, it should be primary, not secondary.

**Comment by dartcafe** [comment]
Has to be changed in the vue library. https://github.com/nextcloud-libraries/nextcloud-vue/issues/4551
