### ISSUE TITLE
Can´t see the plus from the add Button (ownCloud 10.0.6)

### ISSUE THREAD

**Issue by prsnbrg** [nextcloud/polls#309]
### Steps to reproduce
1. Open the overview panel from the polls
2.
3.

### Expected behaviour
Tell us what should happen
See the plus from the add Button in the overview of the polls.

### Actual behaviour
Tell us what happens instead
Can´t see the plus from the button, i see only the outlines from the button.

### Server configuration

**App Version**:
0.8.0

**Operating system**:

**Web server:**
Apache2
**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
ownCloud 10.0.6

**Where did you install Nextcloud from:**
Update from an older oC version
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
fixed css #310
