### ISSUE TITLE
Rename Login dialog to show people where to view the poll results

### ISSUE THREAD

**Issue by useross** [nextcloud/polls#3119]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

I hear very often the question from users of my polls (they just receive a clickable link and dont have an account), how to read the poll results. Seems like the `cancel`-Button leads to a missunderstanding by some users. I´d like to ask if it is possible to change the wording for more clarity how to view the results of a poll.

### Describe possible solutions

i would like to suggest the following words for the guest-log-in

![grafik](https://github.com/nextcloud/polls/assets/148186217/e4566735-071a-447d-8e1f-e23081e190f2)

**Comment by dartcafe** [comment]
@useross Thanks for your suggestion. 

I would not change the button texts. Depending on the translation layout issues may occur.

But I think about changing the user flow and present the vote page initially on entering the public share. A new button could then ask the user for participation. After the button click the registration dialog will be raised.

**Comment by useross** [comment]
@dartcafe Changing the user flow and present the vote page initially on entering the public share is also a nice idea! Sound even better, because the users sees from the beginning the current state of the poll.
