### ISSUE TITLE
Missing Styling when creating or participating in polls

### ISSUE THREAD

**Issue by m-Schlitzer** [nextcloud/polls#312]
### Steps to reproduce
1. Installing from the appstore
2. Create Poll

### Expected behaviour
The poll creator and poll should be displayed as the example pictures in the README.md

### Actual behaviour
The styling is off, some users also can't create polls

### Server configuration
**Operating system:** Linux 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64

**Webserver:** nginx/1.13.5 (fpm-fcgi)

**Database:** sqlite3 3.15.1

**PHP version:** 7.1.10
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mcrypt, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_notifications: 1.0.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - checksum: 0.3.5
 - comments: 1.2.0
 - dav: 1.3.0
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.2.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - polls: 0.8.1
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - deck
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "\/data",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "ocadc83b19e7",
    "mail_from_address": "mailer",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.alienco.de"
    ],
    "overwrite.cli.url": "https:\/\/cloud.alienco.de",
    "dbtype": "sqlite3",
    "version": "12.0.3.3",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_domain": "alienco.de",
    "mail_smtphost": "smtp.strato.de",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using encryption:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

</details>

**Comment by m-Schlitzer** [comment]
![screenshot_20180213_202014](https://user-images.githubusercontent.com/20104782/36169289-27b73ca2-10fc-11e8-84ac-d61bac4631f2.png)

**Comment by m-Schlitzer** [comment]
![capture](https://user-images.githubusercontent.com/20104782/36169335-4730d98a-10fc-11e8-947b-c52af7768450.PNG)

**Comment by splitt3r** [comment]
Already cleared the cache?

**Comment by m-Schlitzer** [comment]
Cache has been cleared on mine and another users machine.

**Comment by splitt3r** [comment]
Hm strange looks exactly like https://github.com/nextcloud/polls/issues/306 @dartcafe any idea?

**Comment by m-Schlitzer** [comment]
After updating our nextcloud and disabling and then enabling the app again, it seems to work as expected. I'm sorry I cannot provide further information.

**Comment by splitt3r** [comment]
Ok. we will try to investigate futher as it is already the second issue of this kind.

**Comment by dartcafe** [comment]
This IS a caching issue. When you look into the browser's console, you will find a 404 or similar error of the css file. Everytime, when I ran into this issue, a forced reload helps. BTW: Firefox is behaving different than Chrome. Must be something with the server side scss pre compiler. I will inspect this on time.
