### ISSUE TITLE
Polls overview - Don't show red icon "you did not comment"

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#313]
At the moment a red comment icon is shown in the polls home / overview if the user has not commented the poll. Usually a red sign indicates something is wrong or input / action is needed, which seems misleading on behalf of comments.
Proposal: Only show the green (could then also be neutral black/white or grey) comment icon if a comment was made. Do not show the red icon at all.

**Comment by dartcafe** [comment]
You are right. We should indicate the user specifig information in another way. Maybe just show the relevant indicators and hide them, if they do not apply.

**Comment by joergmschulz** [comment]
we should display the red flag if the user hasn't polled yet. But for the comment, a red flag shouldn't be displayed, in my opinion. The green one might help users.
