### ISSUE TITLE
Help wanted for writing PHP tests

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#3147]
## We are hiring a developer for writing tests for the PHP backend. 

Top conditions: 
* 100% remote work
* Free fruits and drinks in your refrigerator (if you buy then)
* Self-determinded working times
* ...

Or in other words: Who is able and willing to write tests and support this app?

**Comment by jovialcore** [comment]
Hi. I am willing to write the tests. 
Is this position still available?

**Comment by dartcafe** [comment]
> Hi. I am willing to write the tests.

You would make me happy with contibuting and maintaining tests!
