### ISSUE TITLE
Issue with Display of "No" Votes Icon

### ISSUE THREAD

**Issue by Lambazsq** [nextcloud/polls#3173]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

While voting "no," the corresponding icon fails to appear, leading to an empty display of the vote. This issue is observed by both poll users and poll owners. Upon inspecting the element, it becomes evident that the icon element is absent, unlike in the case of "yes" or "maybe" votes where the icon element is correctly displayed. The missing "no" votes icon creates confusion and requires attention for resolution.

### What did you expect, how polls should behave instead?

I expected that, when a user votes "no," the corresponding icon would be displayed as intended. Contrary to this expectation, the current behavior results in the absence of the "no" votes icon. To resolve this issue, the expected behavior should include the correct display of the "no" votes icon, aligning with the user's selection and maintaining consistency with the behavior observed in "yes" or "maybe" votes.

### What steps does it need to replay this bug?

To Reproduce the Bug:

    Navigate to the poll creation page.
    Configure the poll with specific options and settings.
    Cast a vote by selecting "no" as the response.
    Observe that, upon submitting the "no" vote, the corresponding icon is not displayed.
    Inspect the element to confirm the absence of the "no" votes icon in the code.
    Contrast this with the behavior observed when voting "yes" or "maybe," where the icon is correctly displayed.

Yes vote : 
![Capture d’écran 2023-11-27 114752](https://github.com/nextcloud/polls/assets/147703016/61eeaf69-1566-462d-b56d-7f0d07b38660)

![image](https://github.com/nextcloud/polls/assets/147703016/06575151-4f7d-47db-974a-1438203989d0)

Maybe vote :
![image](https://github.com/nextcloud/polls/assets/147703016/9b12eede-185f-477b-ab5b-5f17ef9d4377)

![image](https://github.com/nextcloud/polls/assets/147703016/83daf1dd-575f-478a-854d-fef2e4d6b248)

No vote :
![image](https://github.com/nextcloud/polls/assets/147703016/fde82ac3-f0a7-48fc-9e9c-12a55e8a909f)

![image](https://github.com/nextcloud/polls/assets/147703016/4acca503-25f5-4355-ad7d-07b6babe8df3)

Review :
![image](https://github.com/nextcloud/polls/assets/147703016/f23439df-2bbb-448d-9458-566f5611093a)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.4.2

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

Brave

### NC version

Nextcloud 27 (Nextcloud Hub 5)

### Other Nextcloud version

27.1.4

### PHP engine version

PHP 8.0

### Other PHP version

8.0.30

### Database engine

PostgreSQL

### Database Engine version or other Database

14.5

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
This is no bug, it is by intention to reduce the amount of icons, because it looks very noisy then.
