### ISSUE TITLE
Poll Title should also go into the html-document's `<title>` tag

### ISSUE THREAD

**Issue by ccoenen** [nextcloud/polls#318]
### Current behaviour
When I navigate to a poll, the browser title will remain the default "Umfragen" ("Polls") for every single poll. This is a problem for navigating one's history or also for identifying polls from the browser tab title.

### Expected behaviour
The Poll's title should be part of the document title, so that identification is easier.

To Dos
- [X] Create/Edit page
- [x] Vote page

**Comment by splitt3r** [comment]
Good point :+1:

**Comment by v1r0x** [comment]
Yeah, good idea :)

**Comment by dartcafe** [comment]
Change in the vote will come together with the vue migration.

**Comment by ccoenen** [comment]
:tada:
