### ISSUE TITLE
[Feature Request] Event Schedule poll display and editor changes

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/polls#320]
This is so cool! I don't recall seeing a poll editor that was this cool about picking dates/times for an event.

Two things that bugged me while I was trying it were:
1. No ability to do a date only poll without the time of day options.
2. Horizontal linear display of the poll selection.

Many events that I have been near the planning of were dominated by people debating over what day to pick; time was never part of the discussion. I can certainly see how time is of the essence when planning a meeting, but their's a whole class of polls I can't make properly with the way this is designed right now.

About the display, it could just be me, but I think the horizontal rendering is awful. Vertical would be a slight improvement. A grid would be better with dates ordered vertical and time ordered horizontal. In an ideal world, it would look like a calendar grid. I realize that poses new problems, but if you are clever enough to do what you did so far, I think you could do this too. How about a default context sensitive display that takes into account the date range selected; all dates in the same week, do a week display, only one date selected, do a day planner display, etc. To deviate from the default display you would have buttons for the participant to switch the poll between standard calendar views; day, week, month, year and schedule. The button for the poll would appear in the calendar square if it was a date only choice, and if times were to be selected clicking on the choice icon would resize that square to show a 1-day schedule style grid with the time slots holding the poll buttons in their right locations.

Just riffing here, but why wasn't there a way to say how long of an event it was that the poll was picking a starting time for?

I think an ideal use for the event poll as it is now is employees of a business like a restaurant putting in the hours they **want to work** (_green check_), **can't work** (_red X_), and **are available** (_yellow ?_).

**Comment by WNYmathGuy** [comment]
What if the grid was like a Cross-Tab Query (aka Pivot-Table) and the collection of names were in a drop-down list in the upper left corner of the poll display? The options in the drop-down would be Summary, _just showing the vote counts_, or one entrant's name selected which would show their votes (_and if it was my name I could edit it_).

**Comment by dartcafe** [comment]
Seems to be too complicated for development, testing and at least for the user. If someone wants to make a proposal, we could discuss this.

**Comment by dartcafe** [comment]
I will close this issue, because, there are two issues in one. The first one is in development and I feel, that the second one will not be developed. Feel free to reopen or open a new issue and copy your thoughts about the second idea, if you want to continue the discussion.

**Comment by gponzo** [comment]
I use quite often polls app and I believe it should be rearranged on a vertical layout too.
Web pages and thus browser's sizing are vertical, as well as mobile devices screens.
So, showing options in vertical would allow to see many more of them, while participants are usually less than options.

Please take this into proper consideration :)
