### ISSUE TITLE
When searching: Column not found: 'polls_polls..deleted'

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/polls#3203]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

> An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'polls_polls..deleted' in 'where clause'

The error/trace is sadly not fully logged. The URL in question was: 
`"url": "/ocs/v2.php/search/providers/poll/search?term=abc&from=%2Fapps%2Ffiles%2F"`

Part of the trace:
```
{
    "file": "/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
    "line": 295,
    "function": "wrap",
    "class": "OC\\DB\\Exceptions\\DbalException",
    "type": "::"
},
{
    "file": "/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
    "line": 335,
    "function": "executeQuery",
    "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/apps/polls/lib/Db/PollMapper.php",
    "line": 112,
    "function": "findEntities",
    "class": "OCP\\AppFramework\\Db\\QBMapper",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/apps/polls/lib/Service/PollService.php",
    "line": 118,
    "function": "search",
    "class": "OCA\\Polls\\Db\\PollMapper",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/apps/polls/lib/Provider/SearchProvider.php",
    "line": 59,
    "function": "search",
    "class": "OCA\\Polls\\Service\\PollService",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/lib/private/Search/SearchComposer.php",
    "line": 345,
    "function": "search",
    "class": "OCA\\Polls\\Provider\\SearchProvider",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/core/Controller/UnifiedSearchController.php",
    "line": 119,
    "function": "search",
    "class": "OC\\Search\\SearchComposer",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "line": 230,
    "function": "search",
    "class": "OC\\Core\\Controller\\UnifiedSearchController",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "line": 137,
    "function": "executeController",
    "class": "OC\\AppFramework\\Http\\Dispatcher",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
    "line": 184,
    "function": "dispatch",
    "class": "OC\\AppFramework\\Http\\Dispatcher",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/lib/private/Route/Router.php",
    "line": 315,
    "function": "main",
    "class": "OC\\AppFramework\\App",
    "type": "::"
},
{
    "file": "/var/www/nextcloud/ocs/v1.php",
    "line": 65,
    "function": "match",
    "class": "OC\\Route\\Router",
    "type": "->"
},
{
    "file": "/var/www/nextcloud/ocs/v2.php",
    "line": 23,
    "args": [
        "/var/www/nextcloud/ocs/v1.php"
    ],
    "function": "require_once"
}
```

### What did you expect, how polls should behave instead?

Should not throw an exception on search ;)

### What steps does it need to replay this bug?

1. Used search while in the files app to search for something

### Installation method

Installed/updated using occ

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

6.0.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Add your browser log here

```shell
Nothing besides the requests throwing a 500.
```

### NC version

Other/Don't know

### Other Nextcloud version

28.0.0

### PHP engine version

Other/Don't know

### Other PHP version

PHP 8.2

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Great, thanks. There was a typo.

**Comment by SystemKeeper** [comment]
Thank you for the fast fix! 👍
