### ISSUE TITLE
Limit to vote with just one answer

### ISSUE THREAD

**Issue by natrius** [nextcloud/polls#3206]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a **poll owner**, I want to **be able to limit the votes to one per person**, because **it helps to make clear decisions**. For example, i have votings where something has to be decided, so there is "Agree, Abstain, Disagree, Undecided" available. But everyone voting should just be able to vote for one exclusively. 

This type of voting would ideally be accompanied with https://github.com/nextcloud/polls/issues/1444 for example. 

### Describe possible solutions

Could be a new poll type when creating a "New poll", so there would be

- Date poll
- Text poll
- Pie chart poll

Or something like that?

**Comment by dartcafe** [comment]
Not sure if I understand you right. You are already to limit the possible vote answers by user and by option.

**Comment by dartcafe** [comment]
Ah, I think I understand now. You want the eventually and the no vote been counted as vote too. This sounds more like a survey, which should be solved by forms.

**Comment by natrius** [comment]
Hm, maybe a screenshot clarifies what i mean. I have 4 options and just one is and should be valid. 

![grafik](https://github.com/nextcloud/polls/assets/7243447/0e5df40d-8cb5-463d-88d1-0621d744a4aa)

maybe that helps? I will look into forms.

**Comment by natrius** [comment]
Hm, maybe a screenshot clarifies what i mean. I have 4 options and just one is and should be valid. 

![grafik](https://github.com/nextcloud/polls/assets/7243447/292fde8f-f73c-4101-b2f8-ce5ebd6ce56e)


maybe that helps? I will look into forms.

**Comment by dartcafe** [comment]
Just limit the votes to one vote per user.
![grafik](https://github.com/nextcloud/polls/assets/26707476/52b38659-c3f6-43f4-84e0-7d9fb0965c74)

**Comment by natrius** [comment]
Yes, i see what you mean. I feel like that could be clearer explained/shown somehow to avoid confusion but to be honest, i currently don't have an idea on how do to that. Thank you for the answer!
