### ISSUE TITLE
[Feature Request] Discrete style polling

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/polls#321]
Because of human psychology, other peoples answers can influence an individuals ability to answer a question truthfully. I forget the experiment that demonstrated [GroupThink](https://www.verywellmind.com/what-is-groupthink-2795213) but it is a problem.

The default on a survey/poll should be private responses, and maybe a public landing page. I don't know where it would be useful to have polls where each new entrant sees the responses of the previous entries; maybe an application of game-theory would know. It should be an option to manually do it that way.

**Comment by dartcafe** [comment]
We can make a poll for this. 😁 I am sure, we could discuss endless without any satisfying solution. Feel free to create an anonymous poll, if you like and choose the option. I think we will keep the default as it is, as all other similar apps do this as well.

**Comment by WNYmathGuy** [comment]
I took your advice and created an anonymous poll. It didn't have the effect you said _**or**_ you didn't understand what I meant. This video gives an example of the problem. 
[https://www.youtube.com/watch?v=sno1TpCLj6A](https://www.youtube.com/watch?v=sno1TpCLj6A)
