### ISSUE TITLE
Allow to change the shown username for one poll

### ISSUE THREAD

**Issue by natrius** [nextcloud/polls#3210]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a **poll owner**, I want to **be able to change my username for a specific poll**, because **i have to create polls for specific projects where i have a different username**. 

### Describe possible solutions

If marking or doubleclicking the username in the poll, a small edit-buttorn or a editable name appears, accept and the name is for the poll set.

### Additional context

My username in NC is my first name. Now, if i create a poll for a project i'm using and share the poll publically the other enter as guests their usernames and now i'm there with my first name instead of my username. 
First, not everybody probably knows my username and second, not every project and not every user should know my first name. 

So it would be great if i could change the shown name in the poll for that poll. 

I did not find a setting for that currently and no github issue fitting.

**Comment by dartcafe** [comment]
As a logged in user, the displayed name is always the displayname. The username aka user id aka login name will be hidden in a public poll for reason. But you are able to participate as a public user with the name of your choice?!

Possibly this can be changed, when I am finished with changing the user management. This will be done part by part to address the possibility of creating polls by public users. I think of allowing to change the display name of the user's share even as internal user.

But definetely no priority.

**Comment by natrius** [comment]
Ah, my fault. At the end of writing it i thought that "Username" might be the wrong term. I mean the displayname. 

As a nextcloud user i think i should be able to change my displayname for one poll. I mean, i can obviously just use the guest-link and open it with a private-browser-windows but... that that should be not that complicated in my opinion.

**Comment by natrius** [comment]
I know it is. I don't think it is easy to implement or something like that - i just think it should not be that complicated to show another displayname like it is currently ('compliated' with starting a private browser window and opening the guest-link).

I hope this was not a misunderstanding. And thanks for all the work you do!

**Comment by dartcafe** [comment]
@natrius Yorry, but I have to say no to this feature. I would judge this as an edge case and it means a lot of work. 
* Adding  options to change displayname for this poll
* Storing the displayName
* Editing the displayName
* Revert to the original displayName
* Rights for admins and poll owners (are they allowed to see the name or not?)
* etc.

Much work, limited value and unusual for Nextcloud apps. 

Closing this.
