### ISSUE TITLE
Let me delete myself as poll owner (possibility to create a poll for someone else)

### ISSUE THREAD

**Issue by natrius** [nextcloud/polls#3211]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a **poll owner**, I want to **be able to create a poll for someone not active on my nextcloud instance (because polls is really good!) but i may not participate**.

### Describe possible solutions

When deleting myself after creating the poll, there should not be anyone in that list anymore. 

### Additional context

If i create a poll, i'm there immediately and if i close the poll i'm still there, just without decision. I can delete my line AFTER the poll is closed, but as soon as i open the poll again, i'm there again. 
Putting the owner in the poll immediately is a good choice, but it should be possible to delete myself from the poll properly before closing the poll. 

EDIT: Just to be sure, i checked now the created poll with another browser and it seems i'm delted? I just show up in my own admin-overview in the poll. Then its maybe a bug, not a feature.

**Comment by dartcafe** [comment]
You are not deleted, but still not existent as a participant as long as there are no votes by you. 

But the participant's count in the info is wrong.

**Comment by natrius** [comment]
No. 

![grafik](https://github.com/nextcloud/polls/assets/7243447/96cc6a07-dbad-48b8-b53e-22452c72e117)

Left with logged in user, i pressed 'Delete' next to the username already. On the right the guest-link where the user is actually deleted it seems. 
But its kinda confusing to see myself on the left side, the logged in screen still as the poll owner.

**Comment by dartcafe** [comment]
Again: 
The reason, why you see yourself as a participant is that you entered the poll and have to be able to vote. Therefore you are added virtually. But you are not really a participant until you vote.

**Comment by natrius** [comment]
💡  (not available as reaction :p )
