### ISSUE TITLE
[Feature-Request] Answer-Option "others"

### ISSUE THREAD

**Issue by joesch2** [nextcloud/polls#3212]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll owner, I would like also set an answer-option "other".
If poll participant select this option, he can enter an additional text to the option (maximum length configurable).
This can be helpful, for example, if you want to ask which parents a child can go home with during a vote at a school event.

Example:
My child
- goes to the after-school care center
- goes by bus
- others (enter individual text from poll participant)

**Comment by dartcafe** [comment]
If I understand you right, you are talking about a textpoll with two options and want to allow participants to  chose another optin, which is not listed. Right? 

> goes to the after-school care center
> goes by bus

In this case you can simply allow the participants to add new options or create a poll option "See comments" and ask the paticipants to add their alternative to the comments.

**Comment by joesch2** [comment]
Thank you for the suggestion. However, I can only try it out in a few months and then give feedback on the parents' acceptance.
