### ISSUE TITLE
Translation more user friendly

### ISSUE THREAD

**Issue by prsnbrg** [nextcloud/polls#322]
Tell us what should happen
In my opinion it is more user-friendly, if in the overview instead of "public" for example in German would be "public". (In the column "Access")

**ownCloud version:** (see ownCloud admin page)
ownCloud 10.0.7

**Comment by dartcafe** [comment]
Sorry. I don't understand your request. 

> "public" for example in German would be "public"

**Comment by dartcafe** [comment]
Do you mean: "There is only the english term and no translation"?

**Comment by prsnbrg** [comment]
Oh sry, I mean in German is public "öffentlich" and I think that it is more user friendly with a translation in all languages.

**Comment by joergmschulz** [comment]
Regarding Beta for 9.0: What's the state of the translation? Quite some strings are still missing. Can you give a hint where this  can be done? Transifex?

**Comment by BurtGummer** [comment]
I would also like to translate the English areas into German, but cannot find the app at transiflex:

![image](https://user-images.githubusercontent.com/1249295/45014504-0e963580-b01f-11e8-9b32-d88a445440ce.png)

**Comment by dartcafe** [comment]
Should be done automatically from the transifex-bot.

**Comment by BurtGummer** [comment]
Hello dartcafe,

sorry, if i ask again: i login to transifex.com -> Explore -> search to poll, but there are no projects (just one from joomla). Can you give me a hint?

**Comment by dartcafe** [comment]
Fixed in 0.9
