### ISSUE TITLE
Login makes voting impossible

### ISSUE THREAD

**Issue by Bagoult** [nextcloud/polls#3225]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I created a poll and shared a link to my friends. Unfortunately, many of them reported they couldn't vote. First, they opened the link, then clicked on register and then logged in. But when they got redirected on the poll, the square to vote for each option didn't show.

### What did you expect, how polls should behave instead?

When a user logs in after opening the poll, they should be able to vote.

### What steps does it need to replay this bug?

1. Create a poll and a public link.
2. Log out from your account.
3. Open the link. You cannot vote because you are neither logged in nor temporarily registered. 
![1](https://github.com/nextcloud/polls/assets/114882781/9ded21ae-e615-4652-bcd0-c2117a6bb86f)
4. Choose "Register" > "Login". Enter your username and password.
5. You are redirected to the poll but still unable to vote.
![2](https://github.com/nextcloud/polls/assets/114882781/825351f2-7c21-49d0-b35f-515dc0b5fc48)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

6.0.1

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

Firefox mobile

### NC version

Other/Don't know

### Other Nextcloud version

28.0.1

### PHP engine version

Other/Don't know

### Other PHP version

8.2.7

### Database engine

MySQL

### Database Engine version or other Database

8.0.35

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Additional Information

There is no problem with temp register.

**Comment by dartcafe** [comment]
It is fixed in 6.1. Just reload the page after registering.

**Comment by dartcafe** [comment]
Forget what I said. I will check this.

**Comment by Ximerox** [comment]
Hello, I had exactly the same problem. Now, after a few hours, it's as if nothing had ever happened. No change to the server or Nextcloud. Suddenly everything worked again.

**Comment by dartcafe** [comment]
The bug is reproducible: 
After entering a poll via a public link as a logged in user or when logging in from the registration modal, voting access is denied. 

As long as the session is valid only rights for viewing the poll is granted. After starting a new session (i.e. by logging out and in again) the poll is accessible for an logged in user as long as the poll is configured for internal participation.

**Comment by nodiscc** [comment]
Can confirm what is reported above on v6.0.1.
Steps to reproduce:
- As a logged in user, create a poll (tested with date-based polls) and set a few voting options
- Go to the `Sharing` tab and `Add a new public link`
- Copy the generated public link and access it from the same browser session
- Poll results are displayed in "view-only" mode (i.e. no checkboxes displayed)

![image](https://github.com/nextcloud/polls/assets/3950390/10be1a25-afd7-47ad-9bd3-02eca697cf5c)

- I was unable to cast a vote without logging out and logging in again

![image](https://github.com/nextcloud/polls/assets/3950390/1ddfb813-f72c-4b49-8bae-d561f3517a6e)

**Comment by dartcafe** [comment]
6.1 beta has the fix. If you are brave enough, you can use it. I am just about to build the rc1 after a lot of refactoring, testing and fixing . I am happy for every feedback.
