### ISSUE TITLE
Feature request: Markdown support

### ISSUE THREAD

**Issue by DBX12** [nextcloud/polls#325]
Formatting the poll text and comments would be very nice, I would like to use markdown for that, because in other Addons markdown is already used for that. Even just simple styling (bold, italics, underline) would be a big help

**Comment by dartcafe** [comment]
Didn‘t we discuss this recently?

**Comment by splitt3r** [comment]
Did we 😁?

**Comment by Cinux90** [comment]
It's been almost a year... is there any progress here?

**Comment by dartcafe** [comment]
Sorry. Not so far. I made a start but I had too many problems getting this safe. So no progress so far.

**Comment by Cinux90** [comment]
no problem dartcafe. thanks for the update. :)

**Comment by pongraczi** [comment]
+1  
For Description, it would be really helpful. I use 1.6.3 with NC20.5.  Or at least multiline support as a temporary workaround.  
Thanks

**Comment by dartcafe** [comment]
Oops. Multiline support for the description disappeared somehow. Fixed it in the master branch.
