### ISSUE TITLE
When sharing to a group the "Resolve and send all invitations" button should disabled after one click

### ISSUE THREAD

**Issue by haug-den-lucas** [nextcloud/polls#3266]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When sharing a Poll to a group the button "Resolve and send all invitations" appears.
Clicking this button has no visual affect at first (as processing sending mails in the background takes a while).
This leads the user to believe his click did not trigger the intended action, so the button gets clicked again leading to the same invitation mail being sent multiple times.

### What did you expect, how polls should behave instead?

After clicking the "Resolve and send all invitations" button, the button should either become disabled immediately or show a loading spinner until the action is finished (after which the button disappears anyway, so there is already a functionality to determine when all mails are sent)

### What steps does it need to replay this bug?

1. Create a poll
2. Create a group with multiple users
3. Invite the group to the poll
4. Click the "Resolve and send all invitations" button (and see no immediate response)
5. Click the button again because you think it didn't work
6. Enjoy multiple mails in your inbox :)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

28.0.1

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Thanks for reporting 👍 
Should be done in the next version.
