### ISSUE TITLE
Navigation elements not aligned

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#3270]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

The last elements of the sidebar are not aligned and too left

### What did you expect, how polls should behave instead?

All elements in the same position

### What steps does it need to replay this bug?

1. See last elements

![image](https://github.com/nextcloud/polls/assets/1473674/b132c6b6-511a-415b-861d-c60bea5306e4)

The problem is the missing UL-Tag:
![image](https://github.com/nextcloud/polls/assets/1473674/b6fdfbd1-ff00-41ce-a43e-253008127719)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

6.0.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

NextCloud 28 (I can't select it here, not entry in drop down)

### PHP engine version

PHP 8.0

### Other PHP version

PHP 8.3 (I can't select it here, not entry in drop down)

### Database engine

MariaDB

### Database Engine version or other Database

MariaDB 10.11

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
I am aware of this since a couple of months. The error comes from the @nextcloud/vue components, since `NcAppNavigationItem` get rendered as `<li>` but the footer slot but does not surround them with the <ul> element.
