### ISSUE TITLE
Create a android or ios poll application as doodle app

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/polls#328]
Hello,

Can you create a android or ios poll application as doodle app, polleverywhere, or thepollapp , please ? (From your poll nextcloud app obviously :))

I think using a phone application is better than using the web browser on phone...

Thanks for your answer :)

Sorry for the pull request...

**Comment by splitt3r** [comment]
No problem :) I think that we don´t have the man power to also create / maintain an app 😞 but as the Nc app is getting even better with vue.js (thx @dartcafe) it will also get more mobile friendly / faster.

**Comment by dartcafe** [comment]
If someone wants to create an app for this purpose, we can talk about implementation an API for this need. I will close this issue, because of that.
