### ISSUE TITLE
Data loss going from v3 to v5

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/polls#3280]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

As the admin of a production setup I'm going through an upgrade marathon. The Nextcloud setup is upgraded step by step from 22 to 27, Polls from 3.8.4 to 5.4.2.
We have noticed that data is lost once the migration is done. I've analyzed it and it seems to be caused by a wrong order of migration and repair steps.
1) The two migrations are executed and add columns like polls_votes.vote_option_hash
2) `\OCA\Polls\Db\TableManager::deleteAllDuplicates` runs ``SELECT DISTINCT `t1`.`id` FROM `*PREFIX*polls_votes` `t1` INNER JOIN `*PREFIX*polls_votes` `t2` ON `t1`.`id` < `t2`.`id` WHERE (`t1`.`poll_id` = `t2`.`poll_id`) AND (`t1`.`user_id` = `t2`.`user_id`) AND (`t1`.`vote_option_hash` = `t2`.`vote_option_hash`)``. At this point, vote_option_hash is an empty string. Therefore the full table is wrongly considered duplicates and data is DELETEd.
3) `\OCA\Polls\Db\TableManager::migrateOptionsToHash` runs to fill the columns that have just been deleted.

### What did you expect, how polls should behave instead?

1) Upgrade schema
2) Fill hash columns
3) Deduplicate

### What steps does it need to replay this bug?

1. Set up v3
2. Fill polls+votes tables
3. Switch to v5
4. Run occ upgrade

With adjustment of nextcloud-max in info.xml I was able to replay the data loss on my server master/29 dev setup.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

v5.2.2

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### NC version

Nextcloud 27 (Nextcloud Hub 5)

### PHP engine version

Other/Don't know

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by ChristophWurst** [comment]
v4 is probably never installed because v3/v5 are the latest

![image](https://github.com/nextcloud/polls/assets/1374172/bc9de35d-a620-4b32-8056-c6b51248c5e5)

**Comment by dartcafe** [comment]
I can't find a version 5.2.2. You mean 5.4.2?

**Comment by ChristophWurst** [comment]
Yes. My bad.

**Comment by dartcafe** [comment]
Argh. Yes. If the duplication removal relies on existing valid hashes, it must fail after initial column creation.

I think it should be done by changing the order of the repairsteps and call UpdateHashes before DeleteInvalidRecords
