### ISSUE TITLE
External user shown twice, due to space at end of name

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#329]
### Steps to reproduce
1. create a poll
2. send the link belonging to the poll to recipients.  The recipients have no login in the nextcloud instance
3. User fills in the poll, but at the end of the name there is a space.  For example "Mr Champion "
4. Add an additional date to the selextion, so new voting is needed.  This is not straight forward as the name needs to be copied and the existing entries must be copied.  When the name is copied, the space at the end is not selected

### Expected behaviour
The space at the end is removed, only one entry is shown "Mr Champion"

### Actual behaviour
The space at the end is not removed, there are now entries shown, being:
"Mr Champion"
"Mr Champion "
The latter can only be removed using sql commands :(

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.1.x

**Nextcloud version:** 13.x

**Where did you install Nextcloud from:** nextcloud.org

**Comment by dartcafe** [comment]
#261
