### ISSUE TITLE
External user can not easily modify his/her date selection

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#330]
### Steps to reproduce
1. create a poll
2. send the link belonging to the poll to recipients.  The recipients have no login in the nextcloud instance
3. User fills in the poll
4. Add an additional date, so new voting is needed.  Or for another reason the user wants to change his/her date selection.  This is not trivial....

### Expected behaviour
User can change his/her entry (date selection) and vote

### Actual behaviour
User must use the same name.  Copy the existing entries, and make the selection for the added entry of the date to be modified.  Only after this the user can press vote, to make the voting work.
This does not seem to be intuitive for users (at least that was the feedback I got).

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.1.x

**Nextcloud version:** 13.x

**Where did you install Nextcloud from:** nextcloud.org

**Comment by dartcafe** [comment]
Same as #223. See #268 and #331 as well.
