### ISSUE TITLE
Provide an external user a password to protect his/her date selection

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#331]
### Steps to reproduce
1. create a poll
2. send the link belonging to the poll to recipients.  The recipients have no login in the nextcloud instance
3. User fills in the poll.  User votes and that's it.
4. The user mentioned in step 3 can revisit the vote, and change the date selection, using the name(s) that are shown and vote.  

### Expected behaviour
Provide the user a way to protect his/her selection with a kind of password (only when the user wants that).  Next time the vote is revisited and modified the user's new selection is only accepted when the password is provided.  Or a use a gotcha, or a question that the user must provide (last name of your mother, something like that).

### Actual behaviour
Anybody can change the date selection.....

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.1.x

**Nextcloud version:** 13.x

**Where did you install Nextcloud from:** nextcloud.org

**Comment by v1r0x** [comment]
Hi @radoeka 
That's a valid point, but also a special case and not that critical (at least IMO). It's a lot of logic/testing to do for a rather advanced feature. I'd keep it as idea on the backlog for future releases or a PR if someone wants to help.
If other users want this as well or @dartcafe and @splitt3r think this should be done ASAP, I'm ok with implementing it :)

**Comment by dartcafe** [comment]
I stated this before #223. Solution should be, that a public user gets an unique link to be able to edit his own vote.
