### ISSUE TITLE
Poll can't be answered when entering as registered user

### ISSUE THREAD

**Issue by mylaeus** [nextcloud/polls#3313]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I have a public poll. When i am logged in in Nextcloud and then klick on the link, the poll can be answered correcctly.
When I am not logged in and click on the link, the poll is visible and I am asked to register. Now I sign in as a registered user. The Login works ok, but it is not possible to answer the poll.

### What did you expect, how polls should behave instead?

I should be able to answer the poll when I sign in as a registered user.

### What steps does it need to replay this bug?

1. Create an openly accessible poll.
2. Create a pubic link to the poll.
3. Log out off Nextcloud.
4. Activate the link to the poll. Nextcloud opens and shows the poll. You are not logged in.
5. Push the button to register. The window to enter yout name opens.
6. Do not enter the name, but choose to sign in as registered user with your credentials.
7. Sign in. You see the poll, but you cann't answer it. There are no boxes to tick.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Affected polls version

6.0.1

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### Other Nextcloud version

28.0.2

### PHP engine version

PHP 8.1

### Database engine

MySQL

### Database Engine version or other Database

10.6.16

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Fixed in 6.1, see #3225 and #3269

**Comment by dartcafe** [comment]
Great Bug description BTW!
