### ISSUE TITLE
It's not clear that the user populated the date selection

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#332]
### Steps to reproduce
1. create a poll
2. send the link belonging to the poll to recipients.  The recipients have no login in the nextcloud instance
3.  The initial date value is not available (red cross).

### Expected behaviour
The initial selection should not be red (cross), green (check), or orange (question mark), but for example an hyphen "-" or just empty.
This way it is clear to the organizer, that a selection is still to be made and the person should be asked to to revisit the poll.

### Actual behaviour
The initial selection is a red cross, due to this it is not clear whether the use really selected this, or it is just the initial value....

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.1.x

**Nextcloud version:** 13.x

**Where did you install Nextcloud from:** nextcloud.org

**Comment by v1r0x** [comment]
@radoeka 
This seems to be a controversy comparable to Windows vs. Linux, Apple vs. Android, PS4 vs. Xbox vs. Switch, etc. 😉 
There are (good) arguments for yes as default, maybe as default and no as default. And also for none of these three options. I also favored the solution with an _empty_ placeholder, but in the meantime I think default should be one of the three (yes, maybe, no) options.
As a workaround or "solution" I suggest using the comment section to inform the owner, that a user needs more time or has to check for other events.
I close this for now, but if you think this should be reopened, feel free to do so (or @dartcafe and @splitt3r)

**Comment by radoeka** [comment]
@v1r0x  I would like to re-open the issue, but I don't have permission to do so (at least I did not discover how).

Use case:
- Create a poll with dates
- current initial default (no) is ok.
- Users are filling the date picker
- After some time (can be short): no good date found: add an additional day (or additional days)
- It's now not clear anymore which date is a real 'no' and which one has the default value from the recently added dates
- Another default (empty, or an hyphen '-', or ???) makes it possible to distinguish between the two cases:
  -  A real no, the person is not available at a day
  - and a newly added date, that is not yet populated by a user

**Comment by dartcafe** [comment]
I plan to mark added dates as new dates for the voter. so a user has the ability to identify new dates. Maybe unvoted options of other users can be marked as not voted until now, but still as a 'no'. So it is transparent, who voted for which date. 

Is that a solution?

**Comment by dartcafe** [comment]
@radoeka Agree?

**Comment by radoeka** [comment]
@dartcafe I'm honored that you ask/wait for my opinion, thanks.

It's hard for me how your proposal works out.  
What's a new date?
How do you mark a data as new, and is it immediately clear to a user not using the poll app often (or for the first time), that this is a newly added date?

Let's come up with a use case:
- poll is up
- new date is added, and marked as new date
- users are informed by the owner that they need to vote again
- user A visits the poll, changes an former date, but not the new one
  (the new date is than no, but the user actually did not vote for that date, hence the date should remain new)
- Another date gets added
- For user A there should now be two dates, marked as new.

If it works like this, I think that would be fine.

What will happen when the poll is released for the first time, will all the dates be marked as new?

(In the back of my mind, I still think that a fourth choice 'not voted' (besides, no, yes, maybe) will be easier / more consistent)....

**Comment by dartcafe** [comment]
After vote from dartcafe:
![grafik](https://user-images.githubusercontent.com/26707476/39393300-e123a8fa-4ac3-11e8-84aa-00828a8d46a2.png)
and after adding a new option, the poll will be presented to dartcafe like this maybe:
![grafik](https://user-images.githubusercontent.com/26707476/39393308-01f8dde8-4ac4-11e8-9073-9ff4bd216e08.png)

**Comment by radoeka** [comment]
What's the exact difference between screenshot 2 and 3 (the last 2)? 

Is this a mockup or a real screenshot -> I ask as the last date (column) should be somewhere in the middle, to make it chronological (in date order).  If that is not done by the current code, it looks like a bug.

I think that the use of the text 'New option!' is not consistent with the other icons (X, V, ?).
But, is there a character that is as clear as the new text 'New option'?  
Perhaps "-"?  Perhaps "-" with a hoover over text stating 'new option!'?
Or a '+' (as in being added)?  Or '*'?

What does the '4' with green background in the top right corner tell?  In my poll it shows red, but it is not clear to me what it wants to tell me.  Is there an explanation for this somewhere?

**Comment by radoeka** [comment]
A little more:

Use a striking background color for the newly added date?
Something like dark grey with white text?  That way the user sees immediately the deviation.

Thus (if I may); for a newly added date: use a dark grey colored cell, with white text and when one hoovers over the icon, it will tell: 'New option! Added at <date>'.  
The latter (the <date> should take into the account the locale, but that's already done I think by Nextcloud).

**Comment by dartcafe** [comment]
> What's the exact difference between screenshot 2 and 3 (the last 2)?
In the last screenshot the first option was replaced by an option with another time. This is a real screenshot from my devolping inctance and just a throw. The visual design will be applied later. 
> What does the '4' with green background in the top right corner tell?
It says: There are 4 comments, and at least one is from you. 
> New option! Added at 
There is no information stored, when a poll was changed. It is simply the information: "You already voted, but there were some options added after your last vote." When and which option was added, give no helpful information for the result. Maybe changes will be added in the comments as a log for the poll.
