### ISSUE TITLE
Add a note or notification that one has to disable adblocker extensions

### ISSUE THREAD

**Issue by hashworks** [nextcloud/polls#3324]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

I just ran into #3182, and it wasn't clear to me that my ad blocker extension was the cause for the problem.

### Describe possible solutions

Display a note or notification when stuff is blocked by an ad blocker.

**Comment by dartcafe** [comment]
I understand your intention and it seems to be a good idea. Sorry, but no. This way you are delegating the responsibility caused by using DOM manipulating software to the developers. Why should I, as a developer, spent time for coding, maintaining and testing this?
