### ISSUE TITLE
apps/polls/s/RR69oaCr redirect to apps/polls/not-found after registered user renewed call to poll (6.1.1)

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/polls#3326]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I can fill out the survey via the public link after logging in with registered Nextcloud user. If I then call up the link again, I get a 404 error. I can find the poll in "Teilgenommen" (participated)

### What did you expect, how polls should behave instead?

See the old poll directly to edit the poll

### What steps does it need to replay this bug?

1. Poll 6.1.1

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a much older version (more than one major version)

### Affected polls version

6.1.1

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

Nextcloud 28.0.2

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Please describe your exact steps for reproduction. 

I opened a public link and logged in as a user. I end in the requested poll and can participate without a problem.

**Comment by dartcafe** [comment]
The reproduction steps where incomplete. Now I got the situation. 

See https://help.nextcloud.com/t/umfragen-mit-ldap-anbindung/181888/16

**Comment by nicovd737** [comment]
Hello,
Not sure if i have the exact same problem.
Since update of polls in my nextcloud this morning, all publics polls are not accessible anymore by public (404 - poll not found).
I have seen in release notes that there is a huge change but i didn't find what change exactly.
Is that a bug or is there any changes in the way to make polls public ?

Thanks
Nico

**Comment by dartcafe** [comment]
PLease open a newe issue and provide some information from the log files and the console/network tab of your browser.

**Comment by dartcafe** [comment]
> Is that a bug or is there any changes in the way to make polls public ?

no. If it does not work, it is a bug.
