### ISSUE TITLE
NotFoundException Error loading poll with id 0 after upgrading to 6.1.1

### ISSUE THREAD

**Issue by razorrazor** [nextcloud/polls#3330]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

After upgrading to 6.1.1 version, I receive the following NextCloud log error: NotFoundException Error loading poll with id 0

### What did you expect, how polls should behave instead?

Not showing anything

### What steps does it need to replay this bug?

1. Login into NextCloud.
2. Click on Polls menu icon.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

6.1.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

28.0.2

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Database Engine version or other Database

10.5.23

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
NotFoundException Error loading poll with id 0
```

**Comment by dartcafe** [comment]
I have no idea why a poll with the number 0 should be referenced. So I need more information.

Please add some more information from your log file. Use the logfile viewer in the admin section and copy the stack trace you find there in the details view. 

Additionally watch the network tab and share log entries showing errors from the polls app.

**Comment by dartcafe** [comment]
Now I can reproduce this bug. But it doesn't have any affect on the usage of Polls and does not explain, why you say, you see nothing. 

Can you post a screenshot?

**Comment by dartcafe** [comment]
I think I misunderstod your initial post and the fix will close this issue. 
Thanls for reporting.
