### ISSUE TITLE
Polls 6.1.3 - Unable to invite external people

### ISSUE THREAD

**Issue by nicovd737** [nextcloud/polls#3335]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

We can't add external mail adresses when sharing polls to some external peoples only.
If name or email is not known by nextcloud, it's impossible to invite external people. 
Only workaround seems to make polls public for everyone which is not good for us. 

### What did you expect, how polls should behave instead?

Able to invite external people:

![image](https://github.com/nextcloud/polls/assets/28760546/b6c1ae03-ac7b-497f-a30a-d4031b2e102b)

### What steps does it need to replay this bug?

1. Create a poll
2. Try to share it with an external mail adresses not known by nextcloud

### Installation method

Installed/updated via extracting downloaded package to the apps folder

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

6.1.3

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [X] Other/Don't know

### Add your browser log here

```shell
polls.js:141  You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null}ariaLabel: nulltext: undefined[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() o {_uid: 454, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}
```

### NC version

Other/Don't know

### Other Nextcloud version

28.0.2

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Database Engine version or other Database

10.6

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
Nothing is logs relevant for that issue.
```

**Comment by dartcafe** [comment]
The select component seems to behave different as before. I opened an issue in the component repository.

**Comment by dartcafe** [comment]
At least plain email addresses got fixed with this PR. But still combinations of name and email address is broken.
