### ISSUE TITLE
upgrade to Polls 6.1.3 - TypeError: Cannot assign null to property OCA\\Polls\\Db\\EntityWithUser::$anonymized of [...]/lib/public/AppFramework/Db/Entity.php#136

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/polls#3338]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

On Update to Polls 6.1.3 (Nextcloud 23.0.2) i get this errors:

```
{"reqId":"ZdhZ8NjAVKFucjEMFk68fwAAABk","level":1,"time":"2024-02-23T08:40:17+00:00","remoteAddr":"*.*.*.*","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=30YveKdcVuJOOwVIUJvNw18C843JqNZUYuCBSPS%2FooU%3D%3AlTNMEu4PYpYpUE8mHdW4mTJmnua6%2Bu4wALDvKZbZ7OM%3D","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Polls - Create hashes for votes and options","userAgent":[..]
{"reqId":"ZdhZ8NjAVKFucjEMFk68fwAAABk","level":1,"time":"2024-02-23T08:40:17+00:00","remoteAddr":"*.*.*.*","user":"--","app":"polls","method":"GET","url":"/core/ajax/update.php?requesttoken=30YveKdcVuJOOwVIUJvNw18C843JqNZUYuCBSPS%2FooU%3D%3AlTNMEu4PYpYpUE8mHdW4mTJmnua6%2Bu4wALDvKZbZ7OM%3D","message":"Updated 6 hashes in oc_polls_options","userAgent":[...]
{"reqId":"ZdhZ8NjAVKFucjEMFk68fwAAABk","level":3,"time":"2024-02-23T08:40:17+00:00","remoteAddr":"*.*.*.*","user":"--","app":"PHP","method":"GET","url":"/core/ajax/update.php?requesttoken=30YveKdcVuJOOwVIUJvNw18C843JqNZUYuCBSPS%2FooU%3D%3AlTNMEu4PYpYpUE8mHdW4mTJmnua6%2Bu4wALDvKZbZ7OM%3D","message":"TypeError: Cannot assign null to property OCA\\Polls\\Db\\EntityWithUser::$anonymized of type int at /path/to/nextcloud/lib/public/AppFramework/Db/Entity.php#136","userAgent":[...]
```

### What did you expect, how polls should behave instead?

The upgrade destroys my Nextcloud installation. I expect a correct upgrade.

### What steps does it need to replay this bug?

1. Test system with SQLite not MariaDB
2. Upgrde to Polls 6.1.3

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

Polls 6.1.3

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Add your browser log here

```shell
No relevant browser log. Maybe you can use this browser information (sorry german):

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: Not a mysql database -> nothing to do
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Polls - Remove old migrations from migrations table
Reparaturinformation: tidy migration entries
Reparaturschritt: Polls - Remove foreign key constraints and generic indices
Reparaturschritt: Polls - Drop orphaned tables
Reparaturinformation: No orphaned tables found
Reparaturschritt: Polls - Drop orphaned columns
Reparaturinformation: No orphaned columns found
Reparaturschritt: Polls - Create hashes for votes and options
Es ist ein Fehler aufgetreten.
```

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### Other Nextcloud version

Nextcloud 28.0.2

### PHP engine version

PHP 8.1

### Database engine

SQlite

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Please provide the stack trace from the logfile viewer. The log lines do not give much information.
