### ISSUE TITLE
difference between "not voted" and "no" when results displayed

### ISSUE THREAD

**Issue by helgesleo** [nextcloud/polls#3347]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll owner, I want to be able to see if a participant has not voted or voted with "no", because it helps. Actually there is no optical difference - also no difference in Exports

### Describe possible solutions

not voted boxes just show empty, not with class "no"

**Comment by dartcafe** [comment]
> ... because it helps

Helps with what?

**Comment by dartcafe** [comment]
BTW: This topic is dicussed before. The current implementation is by intention.

The only relevant votes for the result are "yes" (and "maybe" for the undecided) . Not voted is the equivalent to not "yes" (and not "maybe) and therefore equivalent to "no". 

Until now, there is no value in differentiating between not voted or a "no" vote, except for the voter himself to get a feedback if he voted a particular option or not.

**Comment by helgesleo** [comment]
a matter of opinion. I think (and others) that there is a difference between:
Yes - definitely
maybe - it would be possible but not ideal
no - definitely no
and
not voted - because you simply cannot or do not want to give an assessment yet or it may be too far in the future for the person voting. In this case you can remind to vote again.

But ok - sorry that some people see it differently and sorry that I didn't find this discussion before (which shows that I'm not the only one who might see it that way). I had already looked.

**Comment by dartcafe** [comment]
There is still no difference between no and not voted in the context of the poll result. The wish of beeing able to differentiate between both if more likely a fear of losing control than a valuable information. In all cases it says not "yes" aka "no". 

If I ask you "will we give me a penny" and you just don't answer, it's a no and I will not get a penny. No matter if you heard me or are just did not wanted to answer.

**Comment by helgesleo** [comment]
It's nice how simple 0 and 1 the world can be - the fact that I would like to give you a penny but first have to check whether I even have one disappears in a 0 and 1 world.

It doesn't matter, I rebuilt it myself.

btw. Thank you again for our explanation and the illustrative example. Where did you graduate in communication psychology? Giving no answer can show up for different reason: „no“, hesitation, insecurity, looking for a solution or „yes“. Giving no reply to any question is a form of violence. As a specialist for communication, you are certainly aware of that. If beeing violent is the language you want to promote - ok. But this is not the kind of appreciation and cooperation I am used to.

**Comment by ET80** [comment]
While it doesn't change i.e. the amount of seats for a restaurant reservation, it might be useful to see who hasn't voted yet.
Think of the aunt someone has - who will surely join but also constantly forgets to vote.
Having the number of none-voter (or voters details) will help eliminate the uncertainty.

For me the actual view is based on certain yes, having the unvoted changes this to certain (yes/no) and uncertain.
