### ISSUE TITLE
Owner sees a list of invited users and groups

### ISSUE THREAD

**Issue by gent187** [nextcloud/polls#338]
It would certainly be a great addition if the owner of a particular survey could see the invited users and or groups in a list.
![bildschirmfoto 2018-05-22 um 11 42 09](https://user-images.githubusercontent.com/38076552/40354936-67095268-5db5-11e8-91c3-692b5033def3.png)

**Comment by dartcafe** [comment]
User management is a to do. So this will be visible then. But this will last a little bit. So, please be patient... :-)

**Comment by rollanders** [comment]
I support this whish and would take it one step further. I would like to use the poll for registering attendance at scout meeting.s If the admin could prespecify the names of the scouts and the dates for meetings, the admin could use this app to register their attendance.

**Comment by dartcafe** [comment]
List of invited users is visible in the crate page in 0.9.
