### ISSUE TITLE
InvalidParameterException: Parameter "hash" for route "polls.page.goto_poll" must match "[^\\/]++" ("" given) to generate a corresponding URL

### ISSUE THREAD

**Issue by brenzi** [nextcloud/polls#339]
### Steps to reproduce
1. Install polls from market
2. open polls as any user

### Expected behaviour
Polls app starts

### Actual behaviour
Internal Server Error

### Server configuration

**Operating system**:
ubuntu 16.04 server

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
owncloud 10.0.8

**Where did you install Nextcloud from:**
incrementally updated from Versoin 8

**Signing status:**
integrity check fails because of some extra files, but hashes are ok

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.4
  - notifications: 0.3.3
  - polls: 0.8.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.6
  - templateeditor: 0.3
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external

**Owncloud configuration:**
{
    "system": {
        "instanceid": "51161f77c276e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "owncloud.log",
        "loglevel": "2",
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "#############"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox
**Operating system:**
ubuntu 16.04 desktop

#### Owncloud log 
```
{"reqId":"PEFTT7Z6A8rroYfXwX8u","level":3,"time":"2018-05-27T08:51:05+00:00","remoteAddr":"185.45.236.200","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/polls\/","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"hash\\\" for route \\\"polls.page.goto_poll\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(119): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'polls.page.goto...', 1, Array, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(382): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('polls.page.goto...', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('polls.page.goto...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(90): OC\\\\URLGenerator->linkToRoute('polls.page.goto...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/polls\\\/templates\\\/main.tmpl.php(96): OC\\\\URLGenerator->linkToRouteAbsolute('polls.page.goto...', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(221): include('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(196): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/ownclo...', NULL)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(232): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'index')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/apps\\\/polls\\\/')\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":146}"}
```

#### Browser log
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

```

**Comment by dartcafe** [comment]
Does this error still occur?

**Comment by dartcafe** [comment]
Cannot reproduce this bug.
