### ISSUE TITLE
Combine polls / combo view does not work

### ISSUE THREAD

**Issue by b90g** [nextcloud/polls#3395]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

index.php/apps/polls/combo

does not show any  Polls the right  menue isnt expanable, no reaction from browser console:

![grafik](https://github.com/nextcloud/polls/assets/63392812/5790510e-ee00-430e-8d03-cca202a870d4)

### What did you expect, how polls should behave instead?

https://github.com/nextcloud/polls/pull/2175

### What steps does it need to replay this bug?

1. have two date polls
2. click on the Combine Polls button
3. not finding any polls to combine

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

7.0.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Database Engine version or other Database

10.11.6

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
I noticed that a while ago, but decided to wait, if someone is missing the function. 🤣 

Sorry for that, but until now not in the mood to fix that.

**Comment by dartcafe** [comment]
The analysis lasted longer than the fix. --> fixed
