### ISSUE TITLE
Dbal Exception

### ISSUE THREAD

**Issue by vatolin** [nextcloud/polls#3396]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

In Polls 7.0.0 on Nextcloud 28.0.3 I get reported in the logfile every five minutes a failure:

DbalException An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR: zero-length delimited identifier at or near """" LINE 1: ...") AS "current_user_votes", coalesce(shares.type, "") AS use... ^
Error while running background job (class: OCA\Polls\Cron\AutoReminderCron, arguments: ) 

How can I solve this issue?

### What did you expect, how polls should behave instead?

I would expect to have a logfile without reports on failures.

### What steps does it need to replay this bug?

1. Have a look at /index.php/settings/admin/overview
2. Have a look at /index.php/settings/admin/logging

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### PHP engine version

PHP 8.2

### Database engine

PostgreSQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by vzsze** [comment]
I'm seeing this issue, too since I upgraded Polls to 7.0.0.

**Comment by joergmschulz** [comment]
see #3394
