### ISSUE TITLE
New polls Creation not available

### ISSUE THREAD

**Issue by waqasazfar** [nextcloud/polls#3405]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I am using NC AIO latest version, I am unable to access poll creation option, in fact no other users or admin are unable to do so.
I removed polls and reinstalled it, still polls creation is not available. 

### What did you expect, how polls should behave instead?

There should be option "Add new polls" as described on https://help.nextcloud.com/t/the-nextcloud-polls-app-meet-the-developers/174797

### What steps does it need to replay this bug?

1.
don't know, its just happening in my AIO

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

7.0.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 29

### Other Nextcloud version

28.0.3

### PHP engine version

Other/Don't know

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by waqasazfar** [comment]
![Uploading Screenshot 2024-03-30 at 4.33.49 PM.png…]()

**Comment by dartcafe** [comment]
See #3401 You can update to Polls 7.0.2 from the relases page or wait until it is published to the appstore.

Otherwise please provide some more information than 'does not work' to be able to analyse the problem.
