### ISSUE TITLE
Grammatical errors Spelling errors during registration

### ISSUE THREAD

**Issue by amayr69** [nextcloud/polls#3411]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When registering in German, the following is displayed:

"Um teilzunehmen, registriere Dich sich mit einem Namen"

### What did you expect, how polls should behave instead?

"Um teilzunehmen, registrieren Sie sich mit einem Namen"
or
"Um teilzunehmen, registriere Dich mit einem Namen"

### What steps does it need to replay this bug?

1.
Register for a public survey

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 29

### PHP engine version

PHP 8.2

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Thanks. Fixed in transifex.
