### ISSUE TITLE
DoesNotExistsException Spamming in LogNC-

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#3412]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

After updating the app to 7.0.2 my log is spammed by this error:

![image](https://github.com/nextcloud/polls/assets/1473674/4fe997ea-596f-46fa-bf12-7090f943c890)

### What did you expect, how polls should behave instead?

no errors

### What steps does it need to replay this bug?

1. install the latest version

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.0.2

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### Other Nextcloud version

28.0.4

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Please post the details of the error entry, so I can analyse the stack.

**Comment by Dennis1993** [comment]
That’s all what is in the log (see screenshot above). Or what you mean?
Thanks

**Comment by dartcafe** [comment]
Click on the three dot menu and copy the raw entry.

![grafik](https://github.com/nextcloud/polls/assets/26707476/25b2caa0-b729-48bb-8667-3d2b392207bb)

**Comment by dartcafe** [comment]
This is strange. It seems as if the votes of a non existing polls are requetsed. I changed the error handling. 

Since I could not reproduce the situation, please be so kind to report, if the error still occurs after the update.

**Comment by Dennis1993** [comment]
Ok thank you very much
