### ISSUE TITLE
Text polls with same content are not possible

### ISSUE THREAD

**Issue by mtancoigne** [nextcloud/polls#342]
### Steps to reproduce
1. create a text poll with entries `foo bar` and `bar foo`. Save it
2. create a text poll with entries `foo bar` and `bar bar`. Save it
3. Visit the two polls

### Expected behaviour
I expect the poll with entries  `foo bar` and `bar bar` to have the two entries

### Actual behaviour
Only `bar bar` shows.

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
13.0.2
**Where did you install Nextcloud from:**
I don't remember
**Signing status:**

```
No errors have been found.
```

### Potential source of the issue:
Polls entries are identified by their content instead of id ?

I wonder if the same happens with date polls, and if voting for a given date/time in a poll validates the same date in other ones...

**Comment by dartcafe** [comment]
I cannot reproduce this. 
I did the following: 
![bildschirmfoto vom 2018-06-10 um 11 44 42](https://user-images.githubusercontent.com/26707476/41200368-b2d10b12-6ca3-11e8-8984-b2839c215baf.png)
and
![bildschirmfoto vom 2018-06-10 um 11 47 19](https://user-images.githubusercontent.com/26707476/41200389-12333a12-6ca4-11e8-9dfd-abaf2f29b380.png)


and get:
![bildschirmfoto vom 2018-06-10 um 11 46 42](https://user-images.githubusercontent.com/26707476/41200391-179df62c-6ca4-11e8-9fac-6f961357cbfc.png)
and
![bildschirmfoto vom 2018-06-10 um 11 46 56](https://user-images.githubusercontent.com/26707476/41200393-1c21ffd6-6ca4-11e8-80d1-547818e9293a.png)

**Comment by mtancoigne** [comment]
I'll redo this on my side too and provide some feedback.

**Comment by mtancoigne** [comment]
Ok then, I created two text-based polls:

**Poll 1: `foo`, `bar`**
![screenshot_20180613_232218](https://user-images.githubusercontent.com/1732268/41378988-0ab161e6-6f61-11e8-9296-1cb689cdf8ac.png)

**Poll 2: `foofoo`, `foo` and  `bar`**
![screenshot_20180613_232310](https://user-images.githubusercontent.com/1732268/41379036-3105c9cc-6f61-11e8-858d-14d72151cb3b.png)

** Looking at poll 2: `foo` and `bar` are not an option**
![screenshot_20180613_232344](https://user-images.githubusercontent.com/1732268/41379075-4d14fc14-6f61-11e8-868f-f1cf45f78255.png)

**Comment by dartcafe** [comment]
❓ I cannot reproduce it on my instance. I did exactly the same, but I have all options. Maybe you could repeat the creation here: https://nc13.yagst.de/

Just login with github account.

**Comment by mtancoigne** [comment]
@dartcafe, I created two polls on the instance:
 - https://nc13.yagst.de/index.php/apps/polls/poll/nPDfTqETCAaQEDhB (first step)
 - https://nc13.yagst.de/index.php/apps/polls/poll/ypHtflPG3IOYUrJT (second, broken step)

**Comment by mtancoigne** [comment]
Which is totally the point, I created the second poll with "foo", "bar" and "foo bar", but only "foo bar" was kept.

**Comment by dartcafe** [comment]
Please test in current beta, or wait until release...

**Comment by joergmschulz** [comment]
cannot reproduce this with the current BETA version 2 for 9.0

**Comment by mtancoigne** [comment]
@dartcafe I don't have a machine to test the beta version right  now, sadly

**Comment by dartcafe** [comment]
@mtancoigne No problem. But I am sure, this will not occur any more...

**Comment by mtancoigne** [comment]
@dartcafe Great then, maybe we should wait for 0.9.0 to be out before closing this...
