### ISSUE TITLE
participant can remove a vote

### ISSUE THREAD

**Issue by ET80** [nextcloud/polls#3424]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll participant, I want to be able to remove a vote because it helps keeping an overview which votes are still to be made.
With a higher amount of options - i.e. planning dates for a recurring event - it becomes handy to not decide on all options in the beginning.
There might also be cases where no definitively vote might be possible when the poll starts.

### Describe possible solutions

Modify the vote selection cycle and add "not voted" ( "yes" -> {"maybe" ->} "no" -> "not voted" ).

### Additional context

The indication of "not voted" (empty box) vs. "no" (box with cross) can be identical with the behavior of of the settings switch "delete vote when set to no" (sorry, translated back from german).
The mentioned option itself doesn't work for this feature request as it deletes all votes with "no".

**Comment by dartcafe** [comment]
See  different issues: https://github.com/nextcloud/polls/issues?q=is%3Aissue+is%3Aclosed+%22not+voted%22+
