### ISSUE TITLE
Visual change request: Change the "You have no polls" message with a spinner

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/polls#3438]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

When having lots (and I mean really lots) of polls, it can take a while for the request to get all the available polls. During this time the user sees the message "You have no polls". 

To signalize to the user that polls are in the process of being loaded, it would be more user friendly to add a spinner while the polls load. (of course the "You have no polls" message should remain if the user really has no polls).

**Comment by susnux** [comment]
Already implemented, but somewhen it was broken as the loading state was set to always false.
