### ISSUE TITLE
No pools with mobile devices

### ISSUE THREAD

**Issue by TakeitISI81** [nextcloud/polls#3453]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Polls not work with mobile devicees

### What did you expect, how polls should behave instead?

I can't vote

### What steps does it need to replay this bug?

1.
vote with a mobile device

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### PHP engine version

PHP 8.2

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
I can't confirm that, voting works even on mobile. 
Sorry, without information, I can't help. Maybe you better switch to the [community forum](https://help.nextcloud.com/c/apps/polls/94).
