### ISSUE TITLE
(Feature Request) Notification/Activity on poll share

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/polls#347]
### Expected behaviour

When I make a poll accessible for somebody (individuals, groups, ...) I would like that I have the option that these individuals get "poked", i.e. get a notification mail and an entry in their activity thing.

I guess the built-in activity and notification system already provide good enough options for that (default: activity + mail, but users can override these settings). Otherwise this could be done per-poll-creation/modification.

In the current implementation (at least on my system, happy to provide details if this is a bug) I have to create a poll and then poke everybody involved myself (i.e. send a mail "hey, I just create this poll: ....") , which is difficult if its a group.

**Nextcloud version:**
13.0.3

**Comment by dartcafe** [comment]
Notification needs a complete review and change. Integration of notification, email and circles is planned.

**Comment by dartcafe** [comment]
Related to #178
