### ISSUE TITLE
(Feature Request) Detail Pane should be open by default or included in single Poll View

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/polls#348]
The "details" Panel/Sidebar should imho be visible by default when looking at a single poll (most importantly but not only the comments can add real value). It is hidden by default on my old travel-laptop-setup with a ~1300 Pixel-wide resolution.

If this interferes too much with the consistent nextcloud UX, information from that pane should be included in the view (preferably at the bottom of the page).

**Comment by dartcafe** [comment]
I had this thougt too. While testing, this is annoing, if the width is wide enough.

**Comment by dartcafe** [comment]
In 0.9-beta2 it is implemented for the create/edit page.

**Comment by dartcafe** [comment]
Done in vote page as well.
