### ISSUE TITLE
(Feature Request) Add Custom Poll create Template

### ISSUE THREAD

**Issue by ETrko** [nextcloud/polls#349]
Hello all,

is there a possibilty to create a custom template to customize options.
We have several cases where changes on the "create.tmpl.php" are needed and we are coding them our selves.
For Example changing the default option for polls to hidden.
These changes will be gone with any update from the polls app.

Any way to integrate something like this?

Many thanks

**Comment by dartcafe** [comment]
I would prefer a possibility for configuring the defaults.

**Comment by ETrko** [comment]
Would be a possibility aswell.

**Comment by yrammos** [comment]
On a tangent to this issue, I'm wondering whether it is possible to hide all responses from the voting page. I am interested in using this plugin as a voting system and disclosing the number of type of already submitted votes adds unacceptable bias to the process. Many thanks!

**Comment by dartcafe** [comment]
On the todo list.

**Comment by dartcafe** [comment]
Dealing with defaults, which can be configured increases maintenance and test affort. 

You can use hidden polls as a template in any way you want and make duplicates from this. So I will close this...
