### ISSUE TITLE
Booked options are displayed even though the "Hide not available options" option is selected.

### ISSUE THREAD

**Issue by f-Ridolin** [nextcloud/polls#3495]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Booked options are displayed even though the "Hide not available options" option is selected.
The user sees all options, but cannot click on the booked ones.

### What did you expect, how polls should behave instead?

Booked options should be hidden if the "Hide not available options" option is selected.

### What steps does it need to replay this bug?

1. Create a date poll with multiple options.
2. Vote as a user.
3. Vote as another user.  

<img width="282" alt="image" src="https://github.com/nextcloud/polls/assets/163536930/b088aa1f-3edd-47b1-8cd2-51f21a367d94">

<img width="292" alt="image" src="https://github.com/nextcloud/polls/assets/163536930/84d20f05-55b5-4da6-ba38-9d83d0c82a1f">

<img width="300" alt="image" src="https://github.com/nextcloud/polls/assets/163536930/483a7994-27ec-46db-b635-43e88c000bad">

<img width="300" alt="image" src="https://github.com/nextcloud/polls/assets/163536930/51eccf13-742c-4b6e-b79d-635dd1422400">

### Installation method

Installed/updated via extracting downloaded package to the apps folder

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.0.3

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Can't confirm that
Owner's View | Participant's View | 2nd Participant's View
-|-|-
![grafik](https://github.com/nextcloud/polls/assets/26707476/3d08d4f1-8280-41cf-a9f5-443817e33b3a) | ![grafik](https://github.com/nextcloud/polls/assets/26707476/a1a7c201-b579-4b41-860a-454975c37ab7) | ![grafik](https://github.com/nextcloud/polls/assets/26707476/0b86a57c-a45b-4479-9e71-771432590c3b)


As an admin you still see them. The option only applies to participants.

**Comment by f-Ridolin** [comment]
It is clear that this option only applies to participants.
But shouldn't it also be possible to hide unavailable options if the results are not shown for participants?

![poll-options-view](https://github.com/nextcloud/polls/assets/163536930/5f30e532-615e-46c8-85e3-ca2285dd6636)

**Comment by dartcafe** [comment]
As you can see in my screenshots, the booked out results are hidden for other participants than the poll owner.
But any explicit information, that the bug oviously only appears when results are hidden, would have been helpful. 
Now I can reproduce it. 👍
