### ISSUE TITLE
Guest can not be registered a duplicated click kills that user registration..... Button should be locked till registration is done or rejected.

### ISSUE THREAD

**Issue by elschman** [nextcloud/polls#3499]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

If the new guest enters his things in the poll registration form (username + email) and doesnt wait till the next page opens and click a second time the  ok button , registration doesnt work as expected and he gets an error.

### What did you expect, how polls should behave instead?

The registration button should be locked till the registration process is done.

### What steps does it need to replay this bug?

click twice at the ok button ... 

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

7.0.3

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [X] Other/Don't know

### NC version

Nextcloud 28

### Other Nextcloud version

28.0.3

### PHP engine version

PHP 8.2

### Other PHP version

8.2.16

### Database engine

MariaDB

### Database Engine version or other Database

11.0.3

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by septatrix** [comment]
I agree that the button should be disabled after the first submission. I have received messages by several users that stated that guest registration "was broken" and that they received errors due to them clicking the button again before the registration was settled.

**Comment by septatrix** [comment]
Alternative: The form also sends a UUID which is instead used to prevent duplicated. Submitting twice would then be idempotent. However, simply disabling the button and replacing it with a spinner should be the simpler option.

**Comment by dartcafe** [comment]
Button will get disabled, if the registration is pending. 

Thanks for reporting! 👍
