### ISSUE TITLE
poll votes not shown on android (7.1.2) browser (default and firefox)

### ISSUE THREAD

**Issue by himpierre** [nextcloud/polls#351]
### Steps to reproduce
1. Create Poll
2. Vote 
3. View the Poll on Mobile
4. Votes are not shown as if nobody voted

### Expected behaviour
Votes are shown

### Actual behaviour
Poll looks like nobody voted.

**Operating system**:
Linux / Android

**Web server:**
Apache 2.4.33

**Database:**
MariaDB

**PHP version:**
7.2.6

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Where did you install Nextcloud from:**
tar

**Signing status:**

```
No errors have been found.
```

thanks and cheers

**Comment by himpierre** [comment]
Uh, just saw the votes are shown when rotating the phone to landscape view. Turning it back to vertical view and the votes vanish. Strange.

**Comment by dartcafe** [comment]
Works as designed, to optimize the view in portrait view.
