### ISSUE TITLE
Translation (DE) German locale

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/polls#3516]
💯 
- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

**Translation issue** and "Preferences" shall be translated as "Einstellungen" for the German (DE) locale, I presume.

### What did you expect, how polls should behave instead?

Non for behave but be brave and provide applicable German display please.

### What steps does it need to replay this bug?

1. select German locale
2. select polls and have a look

![Bildschirmfoto 2024-05-17 um 19 29 25](https://github.com/nextcloud/polls/assets/4863737/b26ecce0-a115-4ea9-bc2c-bc61e391cf30)

Issue was intentionally marked with an orange box in the a.m. picture of the GUI

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a much older version (more than one major version)

### Affected polls version

6.3.0 and older almost all, I presume

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### Add your browser log here

```json
LOL
```

### Additional client environment information

macOS & GNU/Linux

### NC version

Nextcloud 27

### PHP engine version

PHP 8.2

### Database engine

MySQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
n.a.
```

### Additional Information

Keep on the good work and prosper.

🌻

**Comment by dartcafe** [comment]
The translation from transifex did not make it into the last 6.x package. So update to Nextcloud 27 and Polls 7 or wait until backport of 7.1 will be done for the version 6.x and Nextcloud 27.
