### ISSUE TITLE
E-Mail notification if archived

### ISSUE THREAD

**Issue by joesch2** [nextcloud/polls#3518]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

I archived some older polls today. Afterwards, all participants in the affected polls received a message saying “... please check your vote ...”. Which added some confusion. 
I think it would be right if the notification only occurred when the content changed, but not when it was archived.

**Comment by dartcafe** [comment]
Indeed. Autoreminders were active for archived polls. Should be fixed by excluding archived polls from the select for autoreminders.
