### ISSUE TITLE
[Feature Request] Setting to limit number of selection(s) per vote

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/polls#352]
I would like to see a setting where we can specify how many of the available options a person can select per vote.

For example, let's say we have 16 options, but I want each vote to only be able to select one of them. Or perhaps up to 4 of the options.

As it stands right now, I don't know a way to limit how many options each vote can select when voting, and this doesn't work in many scenarios.

**Comment by dartcafe** [comment]
We will think over it after the 0.9 release. We already have a feature request to limit the number of possible votes to only one. This will enhance this.

**Comment by yannw** [comment]
Just wanted to add the same request, so +1 
Thanks a lot!

**Comment by BloodyIron** [comment]
Hmm, any word on this? Last response was June.

**Comment by dartcafe** [comment]
It is in the backlog. Has no priority for now.

**Comment by HAVP** [comment]
Just wanted to add the same request, so +1

**Comment by XeroxDev** [comment]
Same for me! :D Can't wait for this feature.

**Comment by BloodyIron** [comment]
Any word on this? I'm hoping we can get more polish to the polls system, as it's rather unintuitive, especially for those actually administrating it! XD

**Comment by dartcafe** [comment]
> Any word on this? I'm hoping we can get more polish to the polls system, as it's rather unintuitive, especially for those actually administrating it! XD

Suggestions are always welcome? Feel free to open issues with some.

**Comment by BloodyIron** [comment]
@dartcafe where exactly do you think you're posting? This is my post which is a Feature Request... how exactly is that not what you're suggesting here? @_@

**Comment by dartcafe** [comment]
1. This issue is about limiting the number of possible votes. So other requests should get their own issue.

2. I don't see, what exactly you are suggesting. Requesting a polish is very general and difficult to realize. A more detailed description would help us to unterstand your request.

**Comment by BloodyIron** [comment]
It was meant as a vague approximate goal, alluding that the original request would contribute to the polish of the polling facet.

I've found it rather clunky to use compared to many other ways polls can be presented. It's not intuitive, or self-indicative of how exactly the poll works, as someone trying to fill it out.

**Comment by dartcafe** [comment]
I think, I understand yóur intention. You say, it is not intuitive from your point of view and you may be right. 

But to understand my point of view: What are your suggestions to make polls more intuitive.

It's like, you are saying, you do not want a green car. This does not help me to choose which color matches your taste. I can make it pink and you say: I don't like pink cars, too. Frustrating

**Comment by BloodyIron** [comment]
Well, right now, I'm asking for a way to limit the number of selections :P 

But if I were to expand on the user experience... as of this writing...

1. With each option having a check and an x, it's not clear you can only pick one, or what it even means. I think this needs to be visually presented in a way that reflects how many votes you have. If you have only one per question, then visually it should look like you can only pick one. If you have more than one vote per question, perhaps something similar to one vote, but list how many votes you have remaining for that question?
2. it would be nice if we could have multiple questions per poll, each having their own type options.
3. It would be nice if we had more question types, such as 1-10's (or whatever #, maybe make this a variable you can set at time of creation), an area for comments, some others that I can't think of right now.
4. I think it would be worthwhile to have it explicitly say something like "anonymous voting enabled" or something like that when the poll is not set to "registered users only", as some may assume registration is needed if not exactly stated one way or another.
5. If we could get pie charts or some sort of visual representation of results of polls, that would help!

Generally, I would like it if I could get all the functionality (or more) found in alternatives (such as survey monkey) which I can't self host, but of course this one I can self host. ;)

Hope that helps! :D

**Comment by BloodyIron** [comment]
Okay I updated and retested #1, so it's pretty good for being clear at this point I think.

I'm not sure how this polling structure can work with multiple questions per poll, but I think it's still something worth figuring out. One question per poll can lead to survey exhaustion. As in, people don't want to be filling polls out constantly, they will do it as a courtesy from time to time, so multiple questions can get more info out when people are prepared to participate.

**Comment by dartcafe** [comment]
OMG. LOL. No. I was referring to 
> Any word on this? I'm hoping we can get more polish to the polls system, as it's rather unintuitive, especially for those actually administrating it! XD

The initial issue was fine. Sorry for confusion.

**Comment by BurtGummer** [comment]
> I would like to see a setting where we can specify how many of the available options a person can select per vote.
> 
> For example, let's say we have 16 options, but I want each vote to only be able to select one of them. Or perhaps up to 4 of the options.
> 
> As it stands right now, I don't know a way to limit how many options each vote can select when voting, and this doesn't work in many scenarios.

Is there anything new about this?

I have the same request: 2 options but just 1 should be selectable.

**Comment by dartcafe** [comment]
No news for now.

**Comment by MacGulliver** [comment]
+1

**Comment by dartcafe** [comment]
#738
