### ISSUE TITLE
Bring back PHP 8.0 support for Nextcloud 29 or older

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/polls#3530]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Version 7 of polls dropped PHP 8.0 support hence it can't be installed on any Nextcloud Server version it officially supports that is running on PHP 8.0

### What did you expect, how polls should behave instead?

Have polls installable on Nextcloud up to v29 with PHP8 which currently is blocked by the updater given the PHP 8.1 requirement of the app.

See https://github.com/nextcloud/server/wiki/Releases-and-PHP-versions

### What steps does it need to replay this bug?

1. Have a Nc instance with PHP8.0
2. Can't install polls given the PHP 8.1 requirement

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

7.x

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

PHP 8.0 runnign instance, version of Nc is irrelevant

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Additional Information

As mentioned above the issue is that the app isn't matching the server version's infrastructure requirements as defined in https://github.com/nextcloud/server/wiki/Releases-and-PHP-versions

**Comment by AndyScherzinger** [comment]
If you have any questions, please let me know @dartcafe @v1r0x @ArtificialOwl 

https://github.com/nextcloud/polls/pull/3353 bumped php-min to 8.1 while it doesn't give me a reason as to why it got bumped

**Comment by dartcafe** [comment]
Yep. One Question: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by AndyScherzinger** [comment]
Good point. Actually the docs are wrong... I'll raise a ticket for that 👍

**Comment by AndyScherzinger** [comment]
Turns out `/latest` of the docs already shows v30.... which dropped php8.0

**Comment by AndyScherzinger** [comment]
So the later is correct in terms of supported php versions, but the docs shown for latest aren't

**Comment by dartcafe** [comment]
I just made an update of [v7.0.3](https://github.com/nextcloud/polls/tree/v7.0.3) to [v7.0.4](https://github.com/nextcloud/polls/tree/v7.0.4)

Find the new version here: https://github.com/nextcloud/polls/releases/tag/v7.0.4

I roughly tested it and found no issues after switching to PHP 8.0. Maybe you can have a look.
