### ISSUE TITLE
Remove or change name requirement for text votes

### ISSUE THREAD

**Issue by StarSmasher44** [nextcloud/polls#3540]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll participant/poll owner, I would appreciate the ability to get rid of the requirement for a name on public polls. I dislike the idea of having random people having to enter a name on the text polls, since the end result is usually just the numbers.

If the system is built upon requiring that name, I could propose a really simple solution; Give us a tickbox woth "Name required", toggling it off will enter a random name, number(s) or any random letters would do. 

This would also make sense for anonymous polls, and it's a very simple way to implement it too.

### Describe possible solutions

As stated above, just replace name with a random string, or numbers. Super simple flex-tape solution :D

**Comment by dartcafe** [comment]
I don't see the value of automating a name setting over the requirement, that the user enters a random name upon registration. What is unreasonable with that?

Sure, we can add a configuration, but by the cost of more configuration options, more code, more maintenence, more regression testing, more error sources ...

Regarding anonymity: The user is free to enter any string combination he likes. 

So, sorry to say no ATM.
