### ISSUE TITLE
[core] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S22]

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/polls#3545]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Error occurs every 5 min (sched by cron)

polls: 6.4.1

Nextcloud version:27.1.10.2
Red Hat Enterprise Linux release 8.10 (Ootpa)
10.6.18-MariaDB
Apache/2.4.37
PHP 8.2.19

==> same error - since upgrade from 27.1.9.1 to 27.1.10.2

[core] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'polls_share.id' in 'group statement' at <>

/var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 295
OC\DB\Exceptions\DbalException::wrap()
/var/www/html/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 335
OC\DB\QueryBuilder\QueryBuilder->executeQuery()
/var/www/html/nextcloud/apps/polls/lib/Db/ShareMapper.php line 115
OCP\AppFramework\Db\QBMapper->findEntities()
/var/www/html/nextcloud/apps/polls/lib/Service/MailService.php line 267
OCA\Polls\Db\ShareMapper->findByPollUnreminded()
/var/www/html/nextcloud/apps/polls/lib/Service/MailService.php line 236
OCA\Polls\Service\MailService->processSharesForAutoReminder()
/var/www/html/nextcloud/apps/polls/lib/Cron/AutoReminderCron.php line 49
OCA\Polls\Service\MailService->sendAutoReminder()
/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php line 81
OCA\Polls\Cron\AutoReminderCron->run()
/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
OCP\BackgroundJob\Job->start()
/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
OCP\BackgroundJob\TimedJob->start()
/var/www/html/nextcloud/cron.php line 152
OCP\BackgroundJob\TimedJob->execute()
Caused by:

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'polls_share.id' in 'group statement' at <>

/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1814
Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1749
Doctrine\DBAL\Connection->handleDriverException()
/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1055
Doctrine\DBAL\Connection->convertExceptionDuringQuery()
/var/www/html/nextcloud/lib/private/DB/Connection.php line 262
Doctrine\DBAL\Connection->executeQuery()
/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 345
OC\DB\Connection->executeQuery()
/var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
Doctrine\DBAL\Query\QueryBuilder->execute()
/var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 293
OC\DB\QueryBuilder\QueryBuilder->execute()
/var/www/html/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 335
OC\DB\QueryBuilder\QueryBuilder->executeQuery()
/var/www/html/nextcloud/apps/polls/lib/Db/ShareMapper.php line 115
OCP\AppFramework\Db\QBMapper->findEntities()
/var/www/html/nextcloud/apps/polls/lib/Service/MailService.php line 267
OCA\Polls\Db\ShareMapper->findByPollUnreminded()
/var/www/html/nextcloud/apps/polls/lib/Service/MailService.php line 236
OCA\Polls\Service\MailService->processSharesForAutoReminder()
/var/www/html/nextcloud/apps/polls/lib/Cron/AutoReminderCron.php line 49
OCA\Polls\Service\MailService->sendAutoReminder()
/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php line 81
OCA\Polls\Cron\AutoReminderCron->run()
/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
OCP\BackgroundJob\Job->start()
/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
OCP\BackgroundJob\TimedJob->start()
/var/www/html/nextcloud/cron.php line 152
OCP\BackgroundJob\TimedJob->execute()
at 2024-06-06T12:10:02+02:00

### What did you expect, how polls should behave instead?

no errors like that

### What steps does it need to replay this bug?

Error occurs every 5 min (sched by cron)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

polls: 6.4.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 27

### Other Nextcloud version

Nextcloud version:27.1.10.2

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Database Engine version or other Database

10.6.18-MariaDB

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Nextcloud Signing status

```shell
no errors found
```

**Comment by dartcafe** [comment]
Fixed in [v6.4.2](https://github.com/nextcloud/polls/releases/tag/v6.4.2)
