### ISSUE TITLE
Polls 7.1.0 released (2024-06-09)

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#3547]
### Annoncement

# Releasenotes 7.1.0
### Fix
 - Fixed counting of orphaned votes
 - Disable registration button while registration is pending
 - Disable "resolve group share" while resolving
 - Fix showing booked up options in polls with hidden results 
### Changes
 - Mainly performance improvements
 - Changed API structure for polls, please refer to the documentation
### Performance
 - Added an option to allow to add polls to the navigation (default)
 - Limited polls inside the navigation to 6 items
 - Render the polls list in chunks of 20 items

# Downloads
Overview and changelog: https://github.com/nextcloud/polls/releases/tag/7.1.0
Download ZIP: https://github.com/nextcloud/polls/releases/download/7.1.0/polls-7.1.0.zip
Download TAR.GZ: https://github.com/nextcloud/polls/releases/download/7.1.0/polls-7.1.0.tar.gz

**Comment by patrickTUD** [comment]
On my two nextcloud instances, this update triggered the maintenance mode. Is this intentional?

**Comment by osm-frasch** [comment]
@patrickTUD Same here (maintenance mode)

**Comment by louim-lbs** [comment]
Same here (NC 29.0.2). As a workaround, I needed to run:

```
occ upgrade
occ maintenance:mode --off
```

And now everything is back to normal.
I have an error in my log, maybe related:

```
[index] Erreur: OCA\Polls\Db\UserMapper::__construct(): Argument #2 ($userManager) must be of type OCP\IUserManager, OC\Session\CryptoSessionData given, called in /config/www/nextcloud/apps/polls/lib/AppInfo/Application.php on line 158 in file '/config/www/nextcloud/apps/polls/lib/Db/UserMapper.php' line 43
	GET /settings/apps/update/polls
	de 128.********** par ********** à 10 juin 2024, **********
```

**Comment by patrickTUD** [comment]
I used a similar workaround. I only disabled the maintenance mode via command line and run the upgrade via the web interface. I don't have the error mentioned by @louim-lbs  in my log. For me, it's the following error in both instances:

`Exception OCA\Polls\Db\OptionMapper::__construct(): Argument #2 ($userSession) must be of type OCA\Polls\UserSession, OCA\Polls\Db\UserMapper given, called in /var/www/html/nextcloud/apps/polls/lib/AppInfo/Application.php on line 198 in file '/var/www/html/nextcloud/apps/polls/lib/Db/OptionMapper.php' line 25`

**Comment by Arcocide** [comment]
Problem : Since update to 7.1.0 the app Polls is empty.
[Nextcloud Hub 8](29.0.2)

**Comment by PatrickJosh** [comment]
This issue is already known, have a look at https://github.com/nextcloud/polls/issues/3526 for the ongoing discussion of it.

**Comment by dartcafe** [comment]
Guys, please use the issues to report bugs or errors. Locking. 

**For those, who ran into the problem: Start `occ upgrade` again from the command line.**
