### ISSUE TITLE
[0.9-beta] Maybe is not an option doesn't change anything

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#355]
### Steps to reproduce
1. create poll while specifying 'disallow maybe vote'
2. save this poll

### Expected behaviour
user should not be able to select maybe nor be presented the yellow maybe option

### Actual behaviour
maybe is still possible

didn't clear browser cache / just a first glimpse of the 9.0 version.

// This is to hide my congratulations for the next version ! I like it! and will try to test as much as possible in the next days //

**Comment by dartcafe** [comment]
Confirmed. This is not implemented yet. I didn't change anything in the vote page. Sorry for confusion. And thanks for testing... 👍

**Comment by dartcafe** [comment]
Did a quick job. Fixed in beta-2 (see updated pre-release).
