### ISSUE TITLE
Can't export - V7.1.1

### ISSUE THREAD

**Issue by infog14** [nextcloud/polls#3573]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Nextcloud 28.0.6 & 29.0.2 (Test in 2 NC)
V7.1.1 Polls
the export button to csv, html has disappeared. We can't export a result of  a poll. I couldn't find any information about stopping export to another format in git. Is this a bug ?

### What did you expect, how polls should behave instead?

This function was requested in the past. It would be interesting if she reappeared

### What steps does it need to replay this bug?

1.Create a poll
2. Answer 
3. No export button
![image](https://github.com/nextcloud/polls/assets/173352361/d0024107-bd9f-4d8a-b26c-fef1fe782bbc)

We tried on a blank and a complete
Thank you

### Installation method

Installed/updated using occ

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.1.1

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### Other Nextcloud version

28.0.6

### PHP engine version

PHP 8.2

### Database engine

PostgreSQL

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by Drallibor** [comment]
👍 We face the same problem. The configuration seems to be the same as @infog14 

### Add your browser log here
![ECHANGE_2024-06-20_err-polls-export](https://github.com/nextcloud/polls/assets/33466457/d259bdd3-db7d-47d8-a5b0-2066d98a29ec)

### Additional client environment information
Windows / Linux

### NC version
Nextcloud 29.0.2

### Other Nextcloud version
Hub 8

### PHP engine version
PHP 8.2

### Other PHP version
No response

### Database engine
MySQL

### Database Engine version or other Database
10.6.18

### Which user-backends are you using?

- [X] Default user-backend (database)
- [X] LDAP/ Active Directory
- [] SSO - SAML
- [] Other/Don't know

### Add your nextcloud server log here
We have a lot of errors like this one :

`[index] Erreur: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT `polls_polls`.*, (SELECT COUNT(`user_vote_sub`.`vote_answer`) FROM `*PREFIX*polls_votes` `user_vote_sub` WHERE (`user_vote_sub`.`poll_id` = `polls_polls`.`id`) AND (`user_vote_sub`.`user_id` = :dcValue1)) AS `current_user_count_votes`, (SELECT COUNT(`user_vote_sub`.`vote_answer`) FROM `*PREFIX*polls_votes` `user_vote_sub` WHERE (`user_vote_sub`.`poll_id` = `polls_polls`.`id`) AND (`user_vote_sub`.`user_id` = :dcValue1) AND (`user_vote_sub`.`vote_answer` = :dcValue2)) AS `current_user_count_votes_yes`, (SELECT COUNT(`user_vote_sub`.`vote_answer`) FROM `*PREFIX*polls_votes` `user_vote_sub` LEFT JOIN `*PREFIX*polls_options` `vote_options_join` ON (`vote_options_join`.`poll_id` = `user_vote_sub`.`poll_id`) AND (`vote_options_join`.`poll_option_text` = `user_vote_sub`.`vote_option_text`) AND (`vote_options_join`.`deleted` = '0') WHERE (`user_vote_sub`.`poll_id` = `polls_polls`.`id`) AND (`user_vote_sub`.`user_id` = :dcValue1) AND (`vote_options_join`.`id` IS NULL)) AS `current_user_count_orphaned_votes`, coalesce(MAX(options.timestamp), :dcValue3) AS max_date, coalesce(MIN(options.timestamp), :dcValue4) AS min_date, COUNT(`options`.`id`) AS `count_options`, coalesce(user_shares.type, '') AS user_role, `user_shares`.`locked` AS `is_current_user_locked`, coalesce(user_shares.token, '') AS share_token, group_concat(distinct group_shares.user_id SEPARATOR ",") AS group_shares FROM `*PREFIX*polls_polls` `polls_polls` LEFT JOIN `*PREFIX*polls_options` `options` ON (`polls_polls`.`id` = `options`.`poll_id`) AND (`options`.`deleted` = '0') LEFT JOIN `*PREFIX*polls_share` `user_shares` ON (`polls_polls`.`id` = `user_shares`.`poll_id`) AND (`user_shares`.`user_id` = :dcValue5) AND (`user_shares`.`deleted` = '0') LEFT JOIN `*PREFIX*polls_share` `group_shares` ON (`polls_polls`.`id` = `group_shares`.`poll_id`) AND (`group_shares`.`type` = 'group') AND (`group_shares`.`deleted` = '0') WHERE `polls_polls`.`id` = :dcValue6 GROUP BY `polls_polls`.`id`, `user_shares`.`type`, `user_shares`.`locked`, `user_shares`.`token`";  at <<closure>>`

 0. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 361
    OCP\AppFramework\Db\QBMapper->findOneQuery()
 1. /var/www/html/apps/polls/lib/Db/PollMapper.php line 65
    OCP\AppFramework\Db\QBMapper->findEntity()
 2. /var/www/html/apps/polls/lib/Service/WatchService.php line 39
    OCA\Polls\Db\PollMapper->find()
 3. /var/www/html/apps/polls/lib/Controller/WatchController.php line 37
    OCA\Polls\Service\WatchService->watchUpdates()
 4. /var/www/html/apps/polls/lib/Controller/BaseController.php line 52
    OCA\Polls\Controller\WatchController->OCA\Polls\Controller\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/html/apps/polls/lib/Controller/WatchController.php line 37
    OCA\Polls\Controller\BaseController->responseLong()
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Polls\Controller\WatchController->watchPoll()
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
10. /var/www/html/lib/base.php line 1068
    OC\Route\Router->match()
11. /var/www/html/index.php line 38
    OC::handleRequest()

GET /index.php/apps/polls/poll/0/watch?offset=1718882429
from 164.177.34.168 by drobillard_4119 at 2024-06-20T11:20:39+00:00

### Additional environment informations
No response

### Configuration report
[config-list.txt](https://github.com/user-attachments/files/15913504/config-list.txt)

### List of activated Apps

- activity: 2.21.1
- admin_audit: 1.19.0
- bruteforcesettings: 2.9.0
- calendar: 4.7.6
- circles: 29.0.0-dev
- cloud_federation_api: 1.12.0
- comments: 1.19.0
- contacts: 6.0.0
- contactsinteraction: 1.10.0
- dashboard: 7.9.0
- dav: 1.30.1
- deck: 1.13.0
- extract: 1.3.6
- federatedfilesharing: 1.19.0
- files: 2.1.0
- files_downloadlimit: 2.0.0
- files_external: 1.21.0
- files_pdfviewer: 2.10.0
- files_reminders: 1.2.0
- files_sharing: 1.21.0
- files_trashbin: 1.19.0
- files_versions: 1.22.0
- forms: 4.2.4
- groupfolders: 17.0.1
- logreader: 2.14.0
- lookup_server_connector: 1.17.0
- notifications: 2.17.0
- oauth2: 1.17.0
- password_policy: 1.19.0
- polls: 7.1.1
- privacy: 1.13.0
- provisioning_api: 1.19.0
- related_resources: 1.4.0
- richdocuments: 8.4.3
- secrets: 1.5.4
- serverinfo: 1.19.0
- settings: 1.12.0
- sharebymail: 1.19.0
- spreed: 19.0.3
- systemtags: 1.19.0
- text: 3.10.0
- theming: 2.4.0
- twofactor_backupcodes: 1.18.0
- updatenotification: 1.19.1
- user_ldap: 1.20.0
- viewer: 2.3.0
- workflowengine: 2.11.0

### Nextcloud Signing status
No response

### Additional Information
No response
