### ISSUE TITLE
Page blanche polls suite à mise à jour update to Polls 7.1.1 from 7.0.1

### ISSUE THREAD

**Issue by Aurore34** [nextcloud/polls#3582]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

JQMIGRATE: Migrate is installed, version 3.4.1
index.es.js:2337 Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
Show 1 more frame
Show less
polls-main.mjs:3 Uncaught SyntaxError: Cannot use import statement outside a module

### What did you expect, how polls should behave instead?

avoir accés aux sondages

### What steps does it need to replay this bug?

1.
mise à jour du polls

### Installation method

Installed/updated via extracting downloaded package to the apps folder

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.1.1

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Add your browser log here

```json
JQMIGRATE: Migrate is installed, version 3.4.1
index.es.js:2337 Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
Show 1 more frame
Show less
polls-main.mjs:3 Uncaught SyntaxError: Cannot use import statement outside a module
```

### NC version

Nextcloud 27

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other/Don't know

### Configuration report

```json
.
```

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

```shell
.
```

### Additional Information

.

**Comment by dartcafe** [comment]
Please use english and provide the requested information.
