### ISSUE TITLE
Popupmenu in Internet Explorer does not work 

### ISSUE THREAD

**Issue by ETrko** [nextcloud/polls#359]
### Steps to reproduce
1. Use Internet Explorer
2. Select a Poll
3. Try to open the 3dot-Menu

### Expected behaviour
Should show the Popupmenu

### Actual behaviour
Displayissue of the Popupmenu. It doesnt show correctly / at all.

### Client configuration
IE Edge / 9

**Comment by joergmschulz** [comment]
can you try to reproduce this in the current Beta? Presumably this is resolved there. At least I can't reproduce it there.

**Comment by ETrko** [comment]
doesnt work in the current beta as well.
IE 11. 

tried with the latest daily build from today.

**Comment by dartcafe** [comment]
Confirmed. Does not work in ie11. Edge is pretty fine for me. Maybe, I will fix it, but I am not sure.
