### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/polls#360]
Hi @dartcafe,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We try to keep up compatibility with older apps, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827 You can run `occ app:check-code` to validate that there are no issues with deprecated or private message calls. 

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14. 

Btw. you might have seen that starting August 25, the Nextcloud Conference takes place at the familiar TU Berlin. (https://nextcloud.com/conf/)! We'd like all contributors to be there and that most certainly includes you. You might already have registered but if you haven't - please consider joining us!

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket:

**Comment by dartcafe** [comment]
@juliushaertl I am testung with the vue branch, but I am not sure, if it is done until NC 14, because I am still hasseling with vue. Polls works, exept some issues with the template. I think I will build a 0.8.2, but I need @v1r0x for building the package.

Is there an ETM for the release?

**Comment by juliushaertl** [comment]
We will have an RC1 this week, and a release probably in 2 if everything works well: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-14

**Comment by dartcafe** [comment]
I just finished version 0.8.2. To get it compatible with OC 10 and NC 14 I added some fixes to the css. Makefile is updated and tested (packages run with OC 10 and NC 14). Release is out from `stable-0.8`.

@v1r0x: Would you compile the packages and deploy them in the appstore and marketplace?

**Comment by juliushaertl** [comment]
Great, thanks for looking into that @dartcafe :+1:

**Comment by dartcafe** [comment]
Great. Thanks. Ragarding to OC: there is a serious bug on public pages and we promised to support this version. Any idea, how to do this with low effort?

**Comment by juliushaertl** [comment]
@dartcafe @v1r0x The Nextcloud app store also supports multiple maintainers for an app, in case you want to share the work in the future. :wink:

**Comment by v1r0x** [comment]
@juliushaertl I only found the option to transfer ownership. How can I add someone as maintainer? Is it only available with a _real_ account (not login via github)?
