### ISSUE TITLE
Error while updating Polls

### ISSUE THREAD

**Issue by marienorbert** [nextcloud/polls#3604]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

While updating the Poll 7.1.2 to 7.1.3 in Nextcloud administration apps updating, Nextcloud is switching as normal to Maintanance mode and does not go on any further. Nextcloud stays blocked in maintanance mode.
All other apps are up to date.

### What did you expect, how polls should behave instead?

Normally there is no problem when updating.

### What steps does it need to replay this bug?

1. …/index.php/settings/apps/updates/polls
2. click on update
3. after about 5 to 10 seconds, Nextcloud is showing an error: "An error occurred during the request. Unable to continue. (translated from french: "Une erreur s'est produite pendant la demande. Impossible de poursuivre.")
4. Nextcloud stays blocked

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.1.2

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 29

### Other Nextcloud version

Nextcloud Hub 8 (29.0.3)

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Database Engine version or other Database

Mysql 10.5.21

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by Mer0me** [comment]
You can run
`sudo -u www-data php occ maintenance:mode --off`
to regain access to Nextcloud.

But the bug must be resolved, it's not the normal behavior !

**Comment by dartcafe** [comment]
Agree: https://github.com/nextcloud/server/issues/38158
