### ISSUE TITLE
(Feature Request) "Manager <- Employer" activity

### ISSUE THREAD

**Issue by Trafikson** [nextcloud/polls#364]
Hi,

I didnt see that any plugin is doing that and it should help with better control of data flow:

Possibility to select who is "manager" of someone manager can setup which aspects of activity he wanna be noticed, for example:
someone is setting public share, someone downloaded file from that share, user see mail with activity info, manager got that mail as well.
ofc perfect version would be that this could be imported from ldap manager attribute but setting it on nextcloud directly is nice too

**Comment by dartcafe** [comment]
You should open this feature request in the server repository. If there is support by the server, maybe we can implement a delegation function like this. But I fear this carries a lot of complexity,
