### ISSUE TITLE
Only empty pages on Pools App after penultimate update

### ISSUE THREAD

**Issue by Maxotauro** [nextcloud/polls#3645]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

After the penultimate and also the last update to version 7.2.0 the Polls App doesn't show any output and any features anymore. Calling the Polls App only an empty page is visible although before the update various polls where created and used, some of them were already archived. None of them are accessible or at least visible after the update. Neither for me as the poll owner nor for poll users.

Also the properties page of the Poll App is completely empty. No text or options are shown. 

In summary: No input is possible and no output shown after update to 7.2.0

### What did you expect, how polls should behave instead?

The Polls App should show the same content after the updates as before. 

### What steps does it need to replay this bug?

1. Update to 7.2.0 
2. Call Polls App shows only an empty page. Neither active polls nor any functional options are displayed. 
3. Check the properties page of the Polls App. Also here only an empty pages is shown with no property options (see picture below). 

![Empty customizing page](https://github.com/user-attachments/assets/14007cd0-aae3-42a2-ab7b-64ab9eec66c8)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.1.4, 7.2.0

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [X] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 27

### Other Nextcloud version

27.1.5 Enterprise

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other/Don't know

**Comment by dartcafe** [comment]
Please check your nginx configuration. See https://github.com/nextcloud/polls/issues/3561#issuecomment-2176749710

Or at least add some logging information.

**Comment by Maxotauro** [comment]
Thank you René for the helpful information.
