### ISSUE TITLE
Support printing the poll

### ISSUE THREAD

**Issue by rubo77** [nextcloud/polls#365]
### Steps to reproduce
1.open the poll inFirefox
2.press CTRL P
3.select save as file

### Expected behaviour
the resulting pdf should contain the whole page. if there are ore options than fit on the page it should try landscape print or wrap in a useful manner

### Actual behaviour
The print is not usable

**Comment by dartcafe** [comment]
close this in favour for an csv export. (i.e. #366)

**Comment by dartcafe** [comment]
Added css-definitions for @media print: 
original poll (Firefox)
![grafik](https://user-images.githubusercontent.com/26707476/115985352-d2d38400-a5ab-11eb-9029-08a27902e593.png)
## Print view (Firefox)
![grafik](https://user-images.githubusercontent.com/26707476/115985438-28a82c00-a5ac-11eb-9463-ba4166d4a594.png)
## Print view (Chrome)
![grafik](https://user-images.githubusercontent.com/26707476/115985481-57260700-a5ac-11eb-96d5-18d55d8c65e2.png)
