### ISSUE TITLE
export poll

### ISSUE THREAD

**Issue by rubo77** [nextcloud/polls#366]
### Steps to reproduce
1.open the poll inFirefox
2.press CTRL A, CTRL C
3.paste the result in libreoffice calc

### Expected behaviour
the selected options should be visible in calc for example with a 0 for not sure, a 1 for taking part and a -1 for not taking part

### Actual behaviour

The selected options are not in the clipboard

### Alternative solution
add an export to csv functionality

**Comment by DJCrashdummy** [comment]
the most obvious solution would probably be a CSV-export to the files-app...

**Comment by rubo77** [comment]
as a workaround, a bash script with a mysql command would come in handy.

someone knows, how to do that?

**Comment by CATERBN** [comment]
+1 for the csv export option. This is the lack that make the app not actually usable for me when involving 30 to 80 user. Waiting for it to switch from [framadate](https://framadate.org) ;)

**Comment by dairaine** [comment]
+1 CSV export.

**Comment by DrAxelbauer** [comment]
+1 Yeah export function would be a great deal to the app!!!

**Comment by andriusign** [comment]
How is the enhancement going? Would be also great to make "Download as PDF".

**Comment by dartcafe** [comment]
No work on this at the moment. Time is limited for me recently. And I have to finish the complete migration to vue first. Sorry about that...

**Comment by rubo77** [comment]
When is that migration finished? Where can we track the progress?

**Comment by dartcafe** [comment]
It's finished and the release will be uploaded to the appstore shortly.

**Comment by rubo77** [comment]
Why to the AppStore?
Isn't it also for the web version?

**Comment by daandres** [comment]
is there any plan for realasing the export feature? 
thanks.

**Comment by dartcafe** [comment]
Sorry, no plans ATM. It is still in  the backlog.

**Comment by joesch2** [comment]
First of all, thank you very much for the good app. We are using them due to Corona in our non-profit sports club. Therefore it would be very helpful (certainly not only for us) to be able to export and store the result as a PDF document. Unfortunately, the printout with CTRL + P is not very clear. I would therefore be very happy if the possibility of printing could be pursued further.

Many Thanks, Jörg

**Comment by dartcafe** [comment]
See #365 for print poll

**Comment by bnjmnschwn** [comment]
+1 for .csv export function.

**Comment by mamo2021** [comment]
+1 for .csv-Export function

**Comment by Coernel82** [comment]
+1 .csv ♥

**Comment by clawoflight** [comment]
I would love CSV export. The one from https://framadate.org/ is excellent and I have built automatic scheduling apps around it.

**Comment by dartcafe** [comment]
I am working on an export solutions since this morning. But this will take some more time. Since it's not that simple.

**Comment by dartcafe** [comment]
See linked pr #2169, if it meets your expectations.
