### ISSUE TITLE
Translation for "E-Mail adress Bar" when entering a Poll as an external Person

### ISSUE THREAD

**Issue by ZID-TU-Graz-Collab** [nextcloud/polls#3695]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

When creating a public link to your Poll you can choose to have the participants enter a mailadress (none / optional / mandatory)
For options (optional/mandatory) there is no translation (at least not to german), while there is for the Rest (screenshot reference)
QoL Change

### Describe possible solutions

German Translation could be:
Email address (optional)  -> E-Mail-Adresse (Optional)
Email adress (mandatory) -> E-Mail-Adresse (Verpflichtend)  //  Or: E-Mail-Adresse (Notwendig)

### Additional context

![grafik](https://github.com/user-attachments/assets/1ce88e69-b326-4164-b77a-26e3facb0c97)
![grafik](https://github.com/user-attachments/assets/96b8c392-5e8b-4c40-9a9b-a5e3cea41286)

**Comment by dartcafe** [comment]
Thanks. The translation function was misused, so the base strings didn't make it to transifex. Give it a few days, so the translations can land here.
