### ISSUE TITLE
Poll types upon poll creation not displayed correctly in NC 28

### ISSUE THREAD

**Issue by KalleFK** [nextcloud/polls#3704]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When creating a new poll in NC 28 the options for creating either a date poll or a text poll is not displayed correctly.
Instead of showing the options as it did before now the options are hidden behind the text below the "New poll" button.
The text appears if you scroll down in the frame containing "New poll" but otherwise it is not displayed, the user can only see the text "Poll type".

See below:
The problem appears when using: Edge, Chrome and Firefox.
![2024-09-12_15-29-23](https://github.com/user-attachments/assets/ee9ba8ab-9e33-4b1a-888b-0f36daa9c5d4)
![2024-09-12_15-29-42](https://github.com/user-attachments/assets/f3dc1871-368b-48c2-a83c-f31a0477c48e)

### What did you expect, how polls should behave instead?

The user should be able to see the options without the need to scroll down. 
Most people are not going to find the alternatives.

### What steps does it need to replay this bug?

1. Install Nextcloud  28.0.9 
2. Open up the Polls app
3. Create a new poll

### Installation method

Installed/updated via extracting downloaded package to the apps folder

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.2.1 and 7.2.2

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

-

### Add your browser log here

```json
-
```

### Additional client environment information

-

### NC version

Nextcloud 28

### Other Nextcloud version

28.0.9 

### PHP engine version

PHP 8.2

### Other PHP version

-

### Database engine

PostgreSQL

### Database Engine version or other Database

16.0

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other/Don't know

### Add your nextcloud server log here

```json
-
```

### Additional environment informations

-

**Comment by dartcafe** [comment]
Thanks. Added a temporary fix, but must be solved in https://github.com/nextcloud-libraries/nextcloud-vue/issues/6079 IMHO.
