### ISSUE TITLE
[feature request] Show participants in mobile portrait view

### ISSUE THREAD

**Issue by rubo77** [nextcloud/polls#372]
At the moment the mobile view on Android is missing the participants:

![tmp_28799-screenshot_20180830-1537122081102564](https://user-images.githubusercontent.com/1591563/44863300-46425d80-ac6c-11e8-8e05-b6bb0115f7d8.jpeg)

**Comment by dartcafe** [comment]
Turn mobile by 90°

**Comment by rubo77** [comment]
how could we make this more obvious?

**Comment by dartcafe** [comment]
For now, I would say discover and experience.

**Comment by rubo77** [comment]
Or a button in portrait mode "show participants"

**Comment by dartcafe** [comment]
What should the button do?

**Comment by rubo77** [comment]
I usually never turn my device and auto rotation is off. And I think many users have the same situation. 

The button should Either change the underlying css so the Landscape CSS is used in portrait mode (you would have to zoom in and out to read everything then)

Or just show a message that you have to turn the device to see the participants

**Comment by dartcafe** [comment]
I'll put it in the backlog.

**Comment by dartcafe** [comment]
Since we have no vote for this, I'll close this.

**Comment by seblu** [comment]
I just get users complaining about the missing participants names.

Responsive mode should not remove information. Especially since the list of participants is the key information.

**Comment by rubo77** [comment]
please either show the particibants in protrait mode too (the uer will have to scroll and zoom then) or add a button in portrait mode "show participants"

**Comment by dartcafe** [comment]
I tested the non responsive design with some users. It was a pain, especially on polls with a couple of text options. Turning to landscape was accepted and learned very fast.

**Comment by rubo77** [comment]
OK, Then If only landscape works, there should be **no portrait mode at all**, just show a big button "Turn your device" would suffice

**Comment by seblu** [comment]
There is a way, technically to force the phone to display in landscape mode. Not that I like application doing that.
Landscape mode is not learned very fast, expect if you are in the same room as your user.
