### ISSUE TITLE
Exceeding the "yes"-votes-per-option limit by voting at the same time

### ISSUE THREAD

**Issue by ZID-TU-Graz-Collab** [nextcloud/polls#3752]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When multiple users vote for the same Option at the same time, the yes-option-limit is exceeded.
This can happen when (more than) 2 users open the poll with the option-limit not full yet.
As long as the users don't reload their website they can vote on the option, even though the limit is already exceeded after the first vote of one of them.

### What did you expect, how polls should behave instead?

After selecting an option there should be a check if this option is still free, then the green marker appears.

### What steps does it need to replay this bug?

1. create a poll & limit yes-votes per option to 1
2. Share the poll to another user
3. Open the poll for both users (different browsers or private window)
4. select the same option on both accounts, without reloading either website 
5. reload one website -> 2 votes for the same option
Screenshot 1: Open simultaneously![Image](https://github.com/user-attachments/assets/a50cc950-11b4-409c-aa71-2fe6d61bc95e)
2: Select the same option, don't reload inbetween![Image](https://github.com/user-attachments/assets/45c4cbb9-b2d9-436b-b2a9-985d4edc5551)3: After reloading 
![Image](https://github.com/user-attachments/assets/a331d4f4-7965-4a14-949e-ab4e3fb8ecdc)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.2.2 

### Which browser did you use, when experiencing the bug?

- [x] Firefox
- [x] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 29

### Other Nextcloud version

29.0.6

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
With 7.2.4 the vote actually gets blocked, but without proper user feedback.
