### ISSUE TITLE
Upradging NC 29.0.7 -> 29.0.8 causes migration error in 060100Date20240209073304

### ISSUE THREAD

**Issue by weberhofer** [nextcloud/polls#3754]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

The following error has been reported on update:
```
Error: Database error when running migration 060100Date20240209073304 for app polls
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1832 Cannot change column 'poll_id': used in a foreign key constraint 'FK_A20806F93C947C0F'
```
I think, there might be wrong entries in the database which must be cleaned up before doing the change.

### What did you expect, how polls should behave instead?

No error message

### What steps does it need to replay this bug?

Update NC/Poll.

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.2.4

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

command line update

### NC version

Nextcloud 29

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Configuration report

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.staatendokumentation.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "AT",
        "dbtype": "mysql",
        "version": "29.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "maintenance_window_start": 1,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6380
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "debug": false,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "apporder",
            "admin_notifications",
            "fulltextsearch_elasticsearch",
            "fulltextsearch",
            "bookmarks_fulltextsearch",
            "files_fulltextsearch",
            "bbb"
        ],
        "updater.server.url": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "overwritehost": "cloud.staatendokumentation.at",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^10\\.10\\.15\\.109$",
        "overwrite.cli.url": "https:\/\/cloud.staatendokumentation.at",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "26",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "preview_max_x": 512,
        "preview_max_y": 512
    }
}

### List of activated Apps

Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - apporder: 0.15.0
  - bbb: 2.7.2
  - bookmarks: 14.2.6
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.2
  - event_update_notification: 2.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_fulltextsearch: 29.0.1
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.3.1
  - fulltextsearch: 29.0.1
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.5
  - integration_giphy: 2.0.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.9
  - nextcloud_announcements: 1.18.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.1
  - password_policy: 1.19.0
  - photos: 2.5.0
  - picker: 1.0.11
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.7
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.10
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tables: 0.8.1
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - translate: 2.2.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflow_pdf_converter: 1.14.1
  - workflowengine: 2.11.0
Disabled:
  - encryption: 2.17.0
  - files_external: 1.21.0
  - polls: 7.2.4 (installed 3.5.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev (installed 5.0.0)
  - user_ldap: 1.20.0

### Nextcloud Signing status

No errors have been found.

**Comment by dartcafe** [comment]
You are coming from a rather old version (3.5.0). 

### Solution occ, which will probably not work, if the current version cannot be enabled:
* run `app:enable polls`
* run `occ polls:db:rebuild`

### Solution Surgeon, if you want to keep your data
* remove all foreign key constrains from all tables named `oc_polls_*` and then active polls

### Solution Berserker, if you do not need any data from the existing version: 
* uninstall polls
* remove all tables named `oc_polls_*`
* reinstall polls

### Solution Tricky, I did not test, if this works
* download the version [6.3.0](https://github.com/nextcloud/polls/releases/tag/v6.3.0)
* remove your polls installation and copy the content of the release package to your apps folder
* enable polls
* after that update to 7.2.4 via appstore or occ commands

The problem occurs, because changing field types needs all FK constraints removed before the change. This has been removed due to performance issues with very large databases.

**Comment by FrViPofm** [comment]
Hi,
I'm just trying to install Polls 7.2.4 on Nextcloud 30.0.1

And I get the issue : 
```
Une erreur s'est produite pendant la demande. Impossible de poursuivre.
Database error when running migration 060100Date20240209073304 for app polls Column "oc_polls_options"."owner" is NotNull, but has empty string or null as default.
```
Is it the same issue ?
Do I need to open an new issue ?

**Comment by dartcafe** [comment]
> Is it the same issue ? Do I need to open an new issue ?

I don't know your circumstances, so I can't determine, if it is the same or another error.

**Comment by weberhofer** [comment]
Thanks, @dartcafe for your help! I have selected your "Solution Surgeon" suggestion.

After displaying all foreign keys to the table `oc_polls_polls`  I have removed those (6 in total). Enabling the app successfully ran the migrations and re-created new foreign keys.
