### ISSUE TITLE
[8.0.0-alpha] Copy public link to clibboard doeys not work anymore

### ISSUE THREAD

**Issue by Juergen-Vollmer** [nextcloud/polls#3755]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Copy public link to clibboard doeys not work anymore. See screenshot below ![Image](https://github.com/user-attachments/assets/ae8606a6-d99f-47c6-8d47-12af0f55ae37).

The clipboard contains only the server name and not the "cryptic" link, which allwos access to the poll.
The same olds for the QR-code.

### What did you expect, how polls should behave instead?

The correct link should be placed in the clipboard an dthe generated qr code.

### What steps does it need to replay this bug?

1. I just upgraded today to Nextcloud  30.0.1.2 which uses 8.0.0-alpha8.
2. On another nextcloud instance  (also  30.0.1.2) which uses polls 7.2.4 everything works fine!

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

8.0.0-alpha8

### Which browser did you use, when experiencing the bug?

- [x] Firefox
- [x] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

30.0.1.2 

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Configuration report

{
"system": {
"instanceid": "***REMOVED SENSITIVE VALUE***",
"passwordsalt": "***REMOVED SENSITIVE VALUE***",
"secret": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
"nextcloud.vollmer.computer",
"nextcloud.vollmer.homelinux.net",
"nextcloud.vollmer.home"
],
"enable_previews": true,
"datadirectory": "***REMOVED SENSITIVE VALUE***",
"dbtype": "mysql",
"version": "30.0.1.2",
"overwrite.cli.url": "https:\/\/nextcloud.vollmer.computer",
"htaccess.RewriteBase": "\/",
"dbname": "***REMOVED SENSITIVE VALUE***",
"dbhost": "***REMOVED SENSITIVE VALUE***",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"dbuser": "***REMOVED SENSITIVE VALUE***",
"dbpassword": "***REMOVED SENSITIVE VALUE***",
"installed": true,
"mail_from_address": "***REMOVED SENSITIVE VALUE***",
"mail_smtpmode": "smtp",
"mail_sendmailmode": "smtp",
"mail_domain": "***REMOVED SENSITIVE VALUE***",
"mail_smtpauthtype": "LOGIN",
"memcache.local": "\\OC\\Memcache\\APCu",
"loglevel": 0,
"log_type": "file",
"log_rotate_size": 104857600,
"maintenance": false,
"onlyoffice": {
"verify_peer_off": true
},
"theme": "",
"simpleSignUpLink.shown": false,
"app_install_overwrite": [
"calendar",
"keeweb",
"files_readmemd",
"twofactor_email",
"keeporsweep",
"twofactor_rcdevsopenotp",
"whiteboard",
"twofactor_u2f",
"nextbackup",
"polls",
"twofactor_admin",
"richdocuments",
"previewgenerator",
"forms",
"groupfolders",
"files_markdown",
"files_mindmap",
"tasks",
"spreed",
"afterlogic",
"mindmap_app",
"richdocumentscode",
"twofactor_totp",
"pdfdraw",
"customproperties",
"cookbook",
"imageconverter",
"files_videoplayer",
"integration_whiteboard"
],
"twofactor_enforced": "true",
"twofactor_enforced_groups": [
"u2f"
],
"twofactor_enforced_excluded_groups": [],
"maintenance_window_start": 1,
"default_language": "de_DE",
"default_locale": "de_DE",
"default_phone_region": "DE",
"force_language": "de_DE",
"skeletondirectory": "",
"updater.release.channel": "beta",
"mail_smtpauth": 1,
"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
"mail_smtpport": "587",
"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
"mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
}

### List of activated Apps

nabled:
- activity: 3.0.0
- admin_audit: 1.20.0
- app_api: 4.0.0
- audioplayer: 3.4.1
- bruteforcesettings: 3.0.0
- calendar: 5.0.1
- circles: 30.0.0-dev
- cloud_federation_api: 1.13.0
- comments: 1.20.1
- contacts: 6.1.0
- contactsinteraction: 1.11.0
- cookbook: 0.11.2
- customproperties: 2.0.4
- dashboard: 7.10.0
- dav: 1.31.1
- deck: 1.14.1
- federatedfilesharing: 1.20.0
- federation: 1.20.0
- files: 2.2.0
- files_downloadlimit: 3.0.0
- files_external: 1.22.0
- files_markdown: 2.4.1
- files_mindmap: 0.0.30
- files_pdfviewer: 3.0.0
- files_reminders: 1.3.0
- files_sharing: 1.22.0
- files_trashbin: 1.20.1
- files_versions: 1.23.0
- firstrunwizard: 3.0.0
- forms: 4.3.1
- groupfolders: 18.0.3
- integration_collaboard: 1.0.10
- keeweb: 0.6.20
- logreader: 3.0.0
- lookup_server_connector: 1.18.0
- mail: 4.0.2
- nextcloud_announcements: 2.0.0
- notes: 4.11.0
- notifications: 3.0.0
- oauth2: 1.18.1
- password_policy: 2.0.0
- phonetrack: 0.8.1
- photos: 3.0.2
- polls: 8.0.0-alpha8
- previewgenerator: 5.6.0
- privacy: 2.0.0
- provisioning_api: 1.20.0
- recommendations: 3.0.0
- related_resources: 1.5.0
- richdocuments: 8.5.1
- serverinfo: 2.0.0
- settings: 1.13.0
- sharebymail: 1.20.0
- support: 2.0.0
- survey_client: 2.0.0
- suspicious_login: 8.0.0
- systemtags: 1.20.0
- tasks: 0.16.1
- text: 4.1.0
- theming: 2.5.0
- twofactor_admin: 4.5.0
- twofactor_backupcodes: 1.19.0
- twofactor_email: 2.7.4
- twofactor_nextcloud_notification: 4.0.0
- twofactor_totp: 12.0.0-dev
- updatenotification: 1.20.0
- user_status: 1.10.0
- viewer: 3.0.0
- weather_status: 1.10.0
- webhook_listeners: 1.1.0-dev
- whiteboard: 1.0.4
- workflowengine: 2.12.0
Disabled:
- drawio: 3.0.3 (installed 3.0.3)
- encryption: 2.18.0
- files_videoplayer: 1.14.0
- user_ldap: 1.21.0

### Nextcloud Signing status

No errors have been found.

### Additional Information

The bug occurs from ipdate of nextcloud 30.0.1.0to 30.0.1.2

**Comment by dartcafe** [comment]
Can't approve. Works here, with the current dev (ahead of alpha-8). But I don't remember having changed anything regarding that.

**Comment by Juergen-Vollmer** [comment]
I found in /var/log/nexcloud.log the error message

   Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist.


does this help?

Here the complete line:

{"reqId":"lVRs9ByWMDpRYjkPFFAx","level":1,"time":"2024-10-20T09:26:40+00:00","remoteAddr":"192.168.0.1","user":"juergen.vollmer","app":"no app in context","method":"GET","url":"/apps/polls/poll/55?time=1729416400081","message":"Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","version":"3Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist."0.0.1.2","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist.","Code":0,"Trace":[{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/Route/Router.php","line":374,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/Route/CachingRouter.php","line":50,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/URLGenerator.php","line":71,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/URLGenerator.php","line":83,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/apps/polls/lib/Db/Share.php","line":241,"function":"linkToRouteAbsolute","class":"OC\\URLGenerator","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/apps/polls/lib/Db/Share.php","line":152,"function":"getURL","class":"OCA\\Polls\\Db\\Share","type":"->"},{"function":"jsonSerialize","class":"OCA\\Polls\\Db\\Share","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/public/AppFramework/Http/JSONResponse.php","line":63,"function":"json_encode"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/AppFramework/Http/Dispatcher.php","line":159,"function":"render","class":"OCP\\AppFramework\\Http\\JSONResponse","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/vollmer.computer/www/nextcloud/src/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/vollmer.computer/www/nextcloud/src/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"message":"Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist.","exception":{},"CustomMessage":"Unable to generate a URL for the named route \"polls.public.vote_page\" as such route does not exist."}}

**Comment by Juergen-Vollmer** [comment]
Since I need polls urgently, I deleted the app an installed manually (unpacking the tgz.gz file) polls-v7.2.4.
Everything works fine again.

Jürgen

**Comment by dartcafe** [comment]
> I found in /var/log/nexcloud.log the error message
> 
> Unable to generate a URL for the named route "polls.public.vote_page" as such route does not exist.
> 
> does this help?
> 


Ah yes. This helps. Indeed this is already [fixed](https://github.com/nextcloud/polls/pull/3749), so with the next alpha release, this should work. 

I will close this upon this information.
