### ISSUE TITLE
UI / scrollbar with much columns easy to miss

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#376]
Hello,

its not really good manageable, if the poll has very much columns:

![image](https://user-images.githubusercontent.com/1249295/45079876-dad90f80-b0f3-11e8-853a-c43f4985ee80.png)

1. The scrollbar is easy to miss
2. This would also allow you to miss the other columns

Polls Version 0.8.1.

**Comment by alexanderdd** [comment]
Hello, why is this closed? It is not yet fixed in 0.8.3

In my firefox 65.0 there is not even a scrollbar at the bottom.

This bug is the reason I did not use polls but doodle because I was afraid participants will not see the other options.

**Comment by dartcafe** [comment]
It was fixed in the 0.9.1 release. I guess you are using ownCloud, which we are not supporting anymore.

**Comment by alexanderdd** [comment]
I just tested this in NC 30.0.6, the scrollbar is now directly below the options, not at the bottom of the window as shown in the screenshot of the issue. 

So yes, this is fixed, thank you!
