### ISSUE TITLE
Cannot add poll

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/polls#3764]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I am running latest alpha on NC30 - unfortunately there is no "+" (Add) button visible (seen on Safari)

### What did you expect, how polls should behave instead?

Show button to add a new poll

### What steps does it need to replay this bug?

1. Install latest beta/alpha on a NC30.0.1 install
2. Open Polls

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

8.0.0.0-alpha8

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [x] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

NC30

### PHP engine version

PHP 8.3

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
see #3758
