### ISSUE TITLE
Edit other users poll

### ISSUE THREAD

**Issue by Boerny** [nextcloud/polls#377]
**Which Polls version are you running?** (see apps page) 0.8.1

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page) 13.0.6

As admin/ creator of the poll it would be great to edit other user name and poll entries.

**Comment by dartcafe** [comment]
What exactly would the user case be for this?

**Comment by Boerny** [comment]
When I create a public poll, some users can not edit their filled in data.(For example private Browsing activated)
I do not find a way to these users poll entries.
Would be great when these entries could be deleted, updated by the admin of the poll.

**Comment by dartcafe** [comment]
I don't get the "private browsing". How can this browser setting prevent editing own polls?

**Comment by Floyer007** [comment]
I think he likes to see the same features like me.
I will explain it in detail.

There should be a option that everyone (but not necessary. please see second case) could edit all users polls.
(Especially for Admins like in Issue https://github.com/nextcloud/polls/issues/386)

Use-Cases for it:
I have some friends who doesn't have a account in my Nextcloud.
Therefore I give them a link to the poll.
E.g. Friend "A" enters his poll and a day later something changed in his shedule.
=> "A" doesn't have time to a specific Time/Day anymore.
"A" and even I as admin won't be able to change anything at the poll at the current state.
Therefore anyone (Use-Case "I trust my friends") should be able to change any other poll from non users, which had contribute via the access-link.

In the case it hasn't to be open for everyone (Use-Case "I don't trust my friends"):
There should be a link for anyone without a account to change the specific poll later.
The Admin should be able to see each link in the case Friend "B" lost his link to edit his poll.

This feature should be deactivalable/switchable obviously for the Admin.

I'm using Version  0.8.3 in Nextcloud 14.0.1

**Comment by dartcafe** [comment]
Developed for admin in #409

**Comment by dartcafe** [comment]
Sorry. Only for changing poll options and deleting polls. Editing votes needs more work.

**Comment by dartcafe** [comment]
related to #397

**Comment by dartcafe** [comment]
#397 
Edit paticipants votes via shared link
