### ISSUE TITLE
After upgrade no layout (css) at poll page

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#379]
**Which Polls version are you running?** 0.8.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** 13.0.5

### Steps to reproduce
1. Go to polls page
2. Only ascii displayed ( in polls area )
3. Before upgrade to 0.8.3 this was okay (though it was sometime I used the page)

### Actual behaviour
Ascii characters are displayed

### Expected behaviour
CSS is used to make up the page

The update should not break existing/working functionality

**In case of a bug, please answer the following questions**

### Server configuration

**Where did you install Nextcloud from: from the apps page (update)

**Operating system**: linux

**Web server:** apache

**Database:** sqlite3

**PHP version:** 7.0.x

What is the best thing I can do?
Remove the app, and it's database tables and install again?
What tables are to be removed?

Can it be fixed (would be nice)?

**Comment by dartcafe** [comment]
Make a forced reload. The scss-caching would be probaly the problem.

**Comment by radoeka** [comment]
I did that, sorry didn't state that in the description.
I did it once more, still the same; no css layout.
Tried two difference browser, both show the same

**Comment by radoeka** [comment]
I see this in the logs when I go to the polls page:
  

Error | PHP | Invalid argument supplied for foreach() at /srv/www/vhosts/<fqdn>/nextcloud-13.0.5/lib/private/Template/SCSSCacher.php#160

```
141          * Check if the file is cached or not
142          * @param string $fileNameCSS
143          * @param ISimpleFolder $folder
144          * @return boolean
145          */
146         private function isCached($fileNameCSS, ISimpleFolder $folder) {
...
160                                 foreach ($deps as $file=>$mtime) {
161                                         if (!file_exists($file) || filemtime($file) > $mtime) {
162                                                 return false;
163                                         }
164                                 }

```

**Comment by dartcafe** [comment]
What does the browser log in the console say?

**Comment by radoeka** [comment]
@dartcafe: 
> What does the browser log in the console say?

Can you provide a detailed instruction how to use that.  When I start chromium or firefox from the command line, there is no (useful) output.

I has posted the screenshot, but unfortunately to the wrong topic.  Well here it is:

![image](https://user-images.githubusercontent.com/2937666/45261882-76c38d80-b40a-11e8-867b-8b33f1499c05.png)

**Comment by dartcafe** [comment]
Did you do a forced reload, or just a usual reload?

**Comment by radoeka** [comment]
I think I did a forced reload; (shift <f5>) of shift <with the mouse at reload> in the browser(s)
If this is not the forced reload you're proposing, let me the exact steps to perform

**Comment by dartcafe** [comment]
Yes. I mean to clear the cache from the current site. 
The console is the second tab on your screen. I want to know, if there are error messages, which relate to the css/scss files. 

I have this issue every time, when the stylesheets are updated. But a forced reload or flushing caches resolves this problem. I have no idea, how I can force NC to recreate the proper CSS files.

**Comment by radoeka** [comment]
Here you have it:
![image](https://user-images.githubusercontent.com/2937666/45288544-3daf1a00-b4eb-11e8-813a-2ada7a04ba25.png)

I tried it in a different browser (MS IE), that I did not use before to access the site (as far as I remember).  Same page layout (no / limited css)

**Comment by radoeka** [comment]
I've upgraded to version 13.0.6 from 13.0.5.
I had to remove the data in oc_filecache.  When I now visit the polls page, the layout looks ok.

**Comment by dartcafe** [comment]
Sorry, I was away a few days. Glad to see, that this was really a caching issue.

**Comment by radoeka** [comment]
I think that you're interpreting oc_filecache incorrectly.  This is the nextcloud file cache, and not a browser cache.   I don't think this is the general solution for the css layout issue.  Any in my case it solved the issue, but it does not feel as it was done in the right way.

**Comment by dartcafe** [comment]
That's a core functionality which is handled by NC itsself. We are not interprating the oc_filecache in any way. Normally this issue occurs in combination with the browsers cache, when the browser does not recognize the change of the css files, which are generated from NC out of our scss files. If the filecache errors, the css files are not generated correctly and so the browser cannot read them. 

We had similar issues before with docker installations and/or external filesystems.
