### ISSUE TITLE
Users in the admin group should be able to edit polls

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#386]
Hello,

if a user is in the group "admin", he should be able to edit all polls - because he is admin of nextcloud.

**Comment by rubo77** [comment]
Also Admin's should be able to edit all votes, that were made by others on the polls

**Comment by brtptrs** [comment]
I would prefer the option to edit/delete polls i'm allowed to see as admin. We have many outdated public polls that fill litter the overview for everyone. 
Being able to remove those polls would be great. Having access to private polls should, i think, be a configuration option.

**Comment by dartcafe** [comment]
Edit and delete developed in #409. Editing of polls for owner and admin is mentioned in another change request. So I will close this issue.
