### ISSUE TITLE
Restrict poll creation to certain selectable groups

### ISSUE THREAD

**Issue by eldeh** [nextcloud/polls#390]
In certain clouds it is desired that only a subset of the potential particpants of the polls is able to create polls.

Therefore, it would be good, if the cloud administrator could restrict the right to create polls to certain groups. This would be a similar behavior to the Nextcloud announcements where the cloud administrator can also restrict the right to create new announcements.

**Comment by UnserUp** [comment]
Very important.
Please, if you could give priority to this proposal.
You do not want everyone to be able to publish a survey. It is intended that only a group of users can create surveys.
Urgent please.

**Comment by dartcafe** [comment]
Closing in favour of #1106
