### ISSUE TITLE
Notifications for users

### ISSUE THREAD

**Issue by khayman123** [nextcloud/polls#391]
Hi. I've noticed, that if I set up poll for other users, they dont get any notice about new poll. 

So the best solution for this, that new poll send email for nextcloud users and add activity and/or notification.

**Comment by dartcafe** [comment]
Related to #178

**Comment by terrar** [comment]
Will the user notification be realized in the foreseeable future?
I like the app itself very well, but without notification, it is useless because then i must still first notify all involved users by mail or messenger that there is a new poll for them.
This option is indispensable!

**Comment by dartcafe** [comment]
Notification will be realized. I cannot pont a milestone right now. Still refactoring in my spare time. But Things will be easier after the vue migration. (Better backend and frontend separation)
