### ISSUE TITLE
Problem with textpoll

### ISSUE THREAD

**Issue by Hylasius** [nextcloud/polls#393]
**Which Polls version are you running?** (see apps page)
0.8.3.

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
14.0.3  (stable)

### Steps to reproduce
1. build a textbased poll
2. it is not possible to create it
3. get the message:
"Nothing selected!
Click on cells to color them green."
(in german I used:
Nichts ausgewählt!
Klicke auf Zellen um sie grün zu färben.)

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

**In case of a bug, please answer the following questions**

### Server configuration

**Where did you install Nextcloud from:**

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by Hylasius** [comment]
installed from Nextcloud.org
Debian 9
apache2 + MariadDB 10 + PHP 7.1 (all actual updated)
Signing status: "No errors have been found."

Client
Win10, Firefox 62.0.3 (64bit) 

It's not possible tu send you the picture. 
Follow this link [http://BetrifftUns.de/github/2018-10-15_Problem_textbasierte_Umfrage-erstellen.gif](url)

**Comment by dartcafe** [comment]
see #160, #131

**Comment by Hylasius** [comment]
Thx
It works.

⁣Ich bin derzeit - vielleicht auch für Sie  - unterwegs. Sofern diese eMail noch weitere Informationen erfordert, sende ich sie Ihnen gern nach meiner Rückkehr. ​


-------- Originale Nachricht --------
Von: "René Gieling" <notifications@github.com>
Gesendet: Mon Oct 15 22:37:58 MESZ 2018
An: nextcloud/polls <polls@noreply.github.com>
Cc: Hylasius <koordinator@isfev.de>, Author <author@noreply.github.com>
Betreff: Re: [nextcloud/polls] Problem with textpoll (#393)

see #160, #131
