### ISSUE TITLE
Feature Request: Folder Images/Icons

### ISSUE THREAD

**Issue by JustAdamHere** [nextcloud/polls#398]
**Is your feature request related to a problem? Please describe.**
It would be great to select an image to use as the folder icon when listing files. 

**Describe the solution you'd like**
A list of suitable images to use as the folder, with the option of selecting your own folder icon.

**Describe alternatives you've considered**
I don't think that there is anything like this in Nextcloud.

**Additional context**
I think it should work in a similar way to choosing an icon for a folder in Windows!

**Comment by dartcafe** [comment]
Are you sure, you posted this in the right project? This is the polls project...

**Comment by dartcafe** [comment]
I think, https://github.com/nextcloud/server ist the right project for this,

**Comment by dartcafe** [comment]
I think, you have to submit the suggestion there.
