### ISSUE TITLE
in 0.9 RC1 LDAP usr name is shown instead of display name

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#402]
### What is going wrong?
**Describe the bug**

Testing 0.9 RC1 I found that LDAP users are shown with their usr name as participants. In 0.8.3 they were listed with their display name. LDAP usr names are not human readable - at least when pulled from a Windows AD ... Screenshot attached.
 
**To Reproduce**
1. Log on to NC as an LDAP usr
2. Create a new or edit an existing poll
3. Yourself as a participant or as owner is shown with user name

**Expected behavior**
Display name should be shown as in 0.8.3

**Screenshots**
![bildschirmfoto 2018-10-31 um 09 46 18](https://user-images.githubusercontent.com/43957716/47776820-8e750f00-dcf3-11e8-8fe4-c278b078e062.png)

### Information about your polls installation
**Polls version?** (see apps page)
0.9.0 RC1

**Fresh installation or update from a prior version (from which one)?**
"updated" from 0.8.3

**How did you install this version?(Appstore or describe installation)**
git clone https://github.com/nextcloud/polls.git

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
NC 14.0.3

**Comment by dartcafe** [comment]
I will look after it. Seems, that we display the user id instead of the user's full name.

**Comment by dartcafe** [comment]
Did a quick fix displaying the user's DisplayName.

**Comment by dartcafe** [comment]
@herrmannsdorfer Can you confirm?
RC 2 is out.

**Comment by herrmannsdorfer** [comment]
Sorry, latest polls app from git repo downloaded a few minutes ago still shows user id instead of display name ...

**Comment by herrmannsdorfer** [comment]
Sorry again. I used the wrong branch. Bug is fixed in develop-0.9
