### ISSUE TITLE
New feature: Booking list with limited number of entries.

### ISSUE THREAD

**Issue by Jerks88** [nextcloud/polls#403]
**Is your feature request related to a problem? Please describe.**
We organize internal training at regular intervals. We want to use a poll to give the employees the possibility to "book" pre defined dates. 

**Describe the solution you'd like**
Due to the limited room size, it would be great if there is a possibility to limit the number of replies to avoid overbooking appointments.

**Describe alternatives you've considered**
There is no alternative but expensive software that is not worth it.

**Additional context**

**Comment by Jerks88** [comment]
It isn‘t a duplocate. In the Feature Request #162 the author wants a possibility to disable multiple answers from the point of view of the user. I want to limit the number of answers for an answer possibility.

For example i want to start a poll to ask the employees when they want to get their training for a new software:

A 5th of November 10am
B 5th of November 2pm
C 10th of November 10am
D 10th of November 2pm

I want to say that only 15 employees can vote for each choice. When 15 employees had voted for A then it should greyed out an can‘t be selected anymore.

**Comment by dartcafe** [comment]
Yes you are right, but this would be a feature of a planning tool and is beyond the scope of a poll app. Additionally, it would add a lot of complexity in handling votes. I think, this is a feature request, which will not be developed. 

And I think something like a spreadsheet can handle this as well....

**Comment by dartcafe** [comment]
I put it in the backlog. Maybe this could be another type of a poll.

**Comment by dartcafe** [comment]
#739
