### ISSUE TITLE
No groups with Umlaut accepted

### ISSUE THREAD

**Issue by UkeFan** [nextcloud/polls#405]
### polls doesn't show groups starting with Ö for example
I can choose any group but not my group "ÖA". I have an uptodate polls and NC-14-Version.

**To Reproduce**
1. Go to a poll
2. Try to share with a group named "ÖA"
3. See, that polls doesn't come up with its name ));;

**Comment by dartcafe** [comment]
Which polls version?

**Comment by UkeFan** [comment]
0.8.3

**Comment by dartcafe** [comment]
Tested in 0.9. Works. But thanks for reporting.
