### ISSUE TITLE
(Enhancement) Users of a public poll should (optionally?) be able to edit the votes

### ISSUE THREAD

**Issue by gohrner** [nextcloud/polls#406]
**Which Polls version are you running?** (see apps page)
0.8.3
**Nextcloud or ownCloud?:**

Nextcloud

**Nextcloud/ownCloud version:** 14.0.3

### Steps to reproduce
1. Publicly share a poll
2. Participate in the poll without being logged in

### Actual behaviour
Once the vote is cast, it cannot be adjusted or retracted

### Expected behaviour
The current behaviour is good to avoid abuse / meddling with other polls, but in case you share a public poll with known-to-be-fair participants, it would be good to configure the poll such that the other participants can change all votes (ideally, only their own votes, but that's probably more complicated to implement...)

**Comment by dartcafe** [comment]
Should be part of the invitation system, so we can set individual hashes.

**Comment by g6094199** [comment]
+1

e.g. non registered users can add their email address to the vote, so we can 1st inform about updates if they like (checkbox) to and 2nd can send a fix link to their vote where they can adjust their vote. 
I dont like cookies in this case.

**Comment by pLum0** [comment]
Any progress on this? Without this enhancement, poll is useless for me as Event Scheduler.

**Comment by dartcafe** [comment]
Just reentered development since some heavy months in my job. Finishing the vote page goes first.

**Comment by realwuffi** [comment]
I would like this feature as well.
I must not be too complicated as @gohrner explained: if the people which are invited are known to treat the poll responsible, it would not matter that someone could change all entries.
I try to move away from doodle, but this missing feature makes it impossible for me at the moment.
Thanks for the great work.

**Comment by dartcafe** [comment]
>  if the people which are invited are known to treat the poll responsible, it would not matter that someone could change all entries.

I bet, there are enough optinions, which will say the opposite. An invitation system with personal links/tokens is on the to do list.

**Comment by dacoex** [comment]
@dartcafe Together with @dfsp-spirit we tried to implement this feature yesterday.
Please have a look at:
https://github.com/dfsp-spirit/polls/commit/eddc2e9a74ed4b89239928a4a8089b17f5e37ebf
We tried to run the branch dev-1.0 locally but the pages remained blank.

**Comment by dacoex** [comment]
@dartcafe May you please add a short statement on why it was closed?
It is not clear if this was addressed or rejected, and if so why.
