### ISSUE TITLE
toggle-all is quite confunding

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/polls#41]
I used the app for many test, you know.
I think the "toggle-all" button is quite confunding.
I think you cannot use the toggle-concept (usually binary, on-off, true-false, etc.) for a three states application.
The user must know that the sequence of the toggle button value is GRY.
Then, if you vote Green/Yellow/Red all the options the toggle button does not change its own status so you can achieve the following situation:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13790353/51b2cefe-eae8-11e5-9e3c-801778a2cd03.JPG)
and you expect that pressing the toggle button all options should become Y ... no, they stay G and the toggle becomes G.
I don't know. It's quite strange and confunding.

**Comment by v1r0x** [comment]
I thought the same behaviour for the toggle-all button would be the best. As every normal button it switches to the next color. What would you prefer?

**Comment by danielepercivaldi** [comment]
Ok. I have thougth a bit during the day, and I have stated the following rule:

- the toggle button must show always the "destination color".

So:
the sequence is YGR.
if you enter a never voted poll:

1. all items are white and toggle is Y
2. if you press the toggle then all items become Y and the toggle G
3. if you press the toggle again then all items become G and the toggle R
4. if you press the toggle again then all items become R and the toggle Y
5. if you vote single item toggle does not change unless all items become all Y/G/R: in this case toggle becomes respectively G/R/Y

What about it?

**Comment by v1r0x** [comment]
I'll implement it and then we can evaluate if it is more user friendly

**Comment by dartcafe** [comment]
I made a try in #151. Not yet finished, but a step in the suggested direction, I think. 
![grafik](https://user-images.githubusercontent.com/26707476/30183974-a24a11b8-941c-11e7-9fad-6a7be3642496.png)

**Comment by dartcafe** [comment]
Solved in #151.

**Comment by danielepercivaldi** [comment]
Great work! I think there is more work to do about details, but now the feature exists and this is the most important thing. Thanks.
