### ISSUE TITLE
Group icon missing in settings (share with ...)

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#416]
### What is going wrong?
**Describe the bug**
Since 0.9.0 RC1 the group icon in settings (share with ...) is missing.

Additionally the group's name is missing too - at least in Safari 12 and FF 63. The group name is shown in Chrome 70.

![bildschirmfoto 2018-11-12 um 08 35 38](https://user-images.githubusercontent.com/43957716/48333677-97050800-e658-11e8-8ab0-4fe0b23b6b87.png)

Sharing polls with groups works.

**Comment by herrmannsdorfer** [comment]
I cloned the repo from git a few minutes ago. The bug is still present.

As far as I can see there is no way to set an avatar for a group. When you share a file to a group the group's icon is the same as with users who did not set an avatar: first letter of the user/group name in a random colored circle.

In apps like deck or talk groups get a different "generic" avatar:

![bildschirmfoto 2018-11-13 um 08 46 04](https://user-images.githubusercontent.com/43957716/48398288-a3ed2e80-e720-11e8-9183-41b923c94de0.png)

I would suggest polls uses this one too. It makes it easier to distinguish between sharing between a single user or a group when the user or group name is not visible.

**Comment by dartcafe** [comment]
Maybe a caching problem?  Which Branch did you pull? develop-0.9? Master is not up to date yet.  Avatar creation works great here, even with a fresh created one. 
![grafik](https://user-images.githubusercontent.com/26707476/48399053-db5cda80-e722-11e8-9690-d20e7abd8f79.png)

**Comment by herrmannsdorfer** [comment]
You are absolutely right. I used the wrong  branch and did not clear the browser cache.

Bug is fixed in current develop-0.9 :-)

Sorry for the noise.

**Comment by dartcafe** [comment]
No sorry. Every test result is welcome.
