### ISSUE TITLE
Notification email in participant's language, not recipients 

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/polls#419]
### What is going wrong?
**Describe the bug**

It's possible to receive notifications when other people participate in the poll.
But the notification email is in the participant's language, not in the language of the person receiving the notification. 
 
**To Reproduce**
1. Create two user accounts
2. Set one to english, the other one two french
3. As user one, create a new notification and subscribe for updates
4. As user two, participate in the poll
5. user one receives a notification email in french

**Expected behavior**

Notification email for user one is in english.

### Information about your polls installation
**Polls version?** (see apps page)
0.8.3

**Fresh installation or update from a prior version (from which one)?**
Fresh

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
14.0.3

**Comment by georgehrke** [comment]
Just as a hint:
You are using `IL10N` in the `PageController`:
https://github.com/nextcloud/polls/blob/master/lib/Controller/PageController.php#L93
https://github.com/nextcloud/polls/blob/master/lib/Controller/PageController.php#L168

Instead you have to get the `OCP\L10N\IFactory`:
figure out what language:
`$config->getUserValue($userId, 'core', 'lang', 'en');`

get the translations: https://github.com/nextcloud/server/blob/fef51895c2689275805bc166bc3f5be95a836b35/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L175

**Comment by dartcafe** [comment]
Related to #178
