### ISSUE TITLE
Compatibility with 15

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/polls#421]
It would be nice to get this available for Nextcloud 15. There is a list of breaking changes in https://github.com/nextcloud/server/issues/11045, but I doubt that the polls app has problems with that. It should be limited to raising the max version number in `info.xml`, give it a test and then publish a new version to the app store.

cc @dartcafe

**Comment by dartcafe** [comment]
I checked NC 15 already and it seems to work exept generating icons from the app. 
NC 15:
![grafik](https://user-images.githubusercontent.com/26707476/48578805-ec703c00-e91a-11e8-9fc0-ae4d7bfb364f.png)

NC14
![grafik](https://user-images.githubusercontent.com/26707476/48578816-f3974a00-e91a-11e8-83e2-2a5e5c3fe642.png)

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
@dartcafe It seems that the --icon-no is hardcoded in vote.scss, while the colors.scss file is not even included in the poll page.

Not sure where `--icon-no: url('/index.php/svg/core/actions/close/f45573?v=1');` is coming from, I didn't get this when trying.

**Comment by dartcafe** [comment]
??? 

https://github.com/nextcloud/polls/blob/a2695bbf7b799cea9ac86d76427905f1315472c7/css/vote.scss#L1

**Comment by juliushaertl** [comment]
@dartcafe Ok I probably was confusing something then. Anyway is there a reason you have a separate .no class in the vote.scss file? If you just use the .icon-no/.icon-yes classes you define in colors.scss for your element it works fine.

![image](https://user-images.githubusercontent.com/3404133/48782034-89e1bc00-ecdd-11e8-9ecc-d9766ee1e153.png)

**Comment by juliushaertl** [comment]
Yes, sorry about the docs there, the icon variables should probably not being considered as stable (aka public api) cc @skjnldsv We should indicate that devs should just use the mixins.

**Comment by skjnldsv** [comment]
@juliushaertl yes! :wink:  there is a lot of things we need to put on the docs :grin:
