### ISSUE TITLE
RC2 for 0.9.1: text poll: duplicate entries should  be prevented

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#433]
### What is going wrong?
Text polls with duplicate entries: Voting for one of the duplicates will change the state of the other as well.

The vote should only change the state of the correct option.

You can try it here: https://test.elternserver.de/index.php/apps/polls/poll/wquQRCAnVyZK7uuu

This bug is a regression - it has been present previously, but it had been fixed in  #124  .

This bug happens in the current master. 

<img width="1178" alt="grafik" src="https://user-images.githubusercontent.com/6523646/49079744-bd729800-f241-11e8-9023-93398be75aa7.png">

Edit: add reference to original fix

**Comment by dartcafe** [comment]
One of the next versions will prevent creating duplicate entries, so this issue will not occur any more. If OK, I will rename the issue. Duplicate entries should not be used, because the poll options are compared with the string entered. Otherwise the tracking of poll changes will get very complex.

**Comment by joergmschulz** [comment]
Hmmm. For contribution list queries, the feature has been handy. When somebody wanted to bring two pounds of coffee, he could apply two times 'yes'. The solution had been to add IDs to the text votes. Maybe it would even be better to identify entries by ID instead of text. SQL injections possible?

**Comment by dartcafe** [comment]
Identifying with IDs would make it really complex, if entries are changed after someone polls. What if someone changed the content and/or sense of an option's text? It is not that trivial.

**Comment by dartcafe** [comment]
IMHO these kind of list queries are not in the scope of a poll. Of course you can do this, but this is like request for using date polls like i. e. a booking system #403 or other requests, which are not really a poll.

Maybe, this can be another type of use case, which founds one more poll type.

**Comment by joergmschulz** [comment]
Yes. #403 would resolve the use case. 
So I rename the topic of this issue.
While I'd like to have the possibility of duplicate entries, I understand the consequences of the backend (data model doesn't allow this). OT: Is this the reason why it is not possible to change text poll entries?

**Comment by joergmschulz** [comment]
duplicate options still are not suppressed, but when you click on one instance of the duplicate, the other is affected as well.

**Comment by dartcafe** [comment]
Yep. But unter normal circumstances, it should not be possible to create a duplicate entry. 
Easy solution if that happens: Delete the duplicate.
