### ISSUE TITLE
PR #437 breaks 0.9.1 in NC 14.0.4 - missing database migration

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#443]
I commented in #437 but the issue is closed and the branch disallow-to-allow already merged into master: 

This PR breaks the app with NC 14.0.4. I pulled the latest master from GIT and now I experience the following errors:

![bildschirmfoto 2018-12-12 um 11 40 05](https://user-images.githubusercontent.com/43957716/49874641-47645880-fe1f-11e8-9c61-f896b9968210.png)

Polls app is unusable at the moment. I cannot access existing polls or create new ones.

Polls app that was upgraded was 0.9.1 RC2. I upgraded to the latest master on the CLI (git clone https://github.com/nextcloud/polls.git).

**Comment by dartcafe** [comment]
If you updated from a prior pre-release, this occurs, but not, if you migrate from a published release.

**Comment by dartcafe** [comment]
You can fix this manually in the database in this case. 
Rename the column disallow_maybe to allow_maybe in the tale polls_events and invert the values 0<->1.

**Comment by herrmannsdorfer** [comment]
Works for me. I did not check the "regular" update (from 0.8.x) but the suggested manual migration after the update from a 0.9.x RC was OK. Polls is fully functional again.
