### ISSUE TITLE
App requires NC 14 or lower

### ISSUE THREAD

**Issue by nielsk** [nextcloud/polls#444]
### What is going wrong?
The app cannot be used in NC 15 because it requires NC 14 or lower.

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
Nextcloud

**Which Version?**
0.8.3 (an update is not offered to a newer version)

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 2.1.8
  - dav: 1.8.0
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.0.5
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - files_accesscontrol
  - files_external
  - files_reader
  - files_retention
  - polls
  - spreed
  - twofactor_totp
  - unsplash
  - user_external
  - user_ldap

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.my.tld",
            "office.my.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

### Server configuration

**Operating system**: CentOS 7.6.1810

**Web server:** Apache 2.4.6

**Database:** mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** PHP 7.1.24

**Signing status:** What?

```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:** Nope

**Comment by dartcafe** [comment]
We have some issues on releasing th app in the app store. You can download the current package from the releases and upload it to the apps folder. 
https://github.com/nextcloud/polls/releases/download/0.9.1/polls-0.9.1.zip

**Comment by dartcafe** [comment]
Which version was installed before?

**Comment by dartcafe** [comment]
Ah. OK, I see. 0.8.3. I will reproduce the update.

**Comment by dartcafe** [comment]
Hmmm. My way:

- nc13 instance with polls 0.8.3
- Update to nc14.0.4
- Update to nc15.0.0 --> polls 0.8.3 got deactivated, database schema is 0.8.3
- empty polls directory
- copy contents of polls-0.9.1.zip into polls directory
- activated polls 0.9.1 --> migration ran silently, database schema ist polls 0.9.1
And the app works.

It seems, that the migration did not run on your site. Can you poost the entries of your oc_migration table. And the names of the polls regarding tables? oc_polls_*

**Comment by nielsk** [comment]
I disabled the app once more and re-enabled it and now it works (this would be the second or third time). Thanks for your work and help. 

Niels
