### ISSUE TITLE
Polls 0.9.1 not published on apps.nextcloud.com

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/polls#447]
Polls v0.9.1 seems not to be published in Nextclouds AppStore on apps.nextcloud.com

**Comment by jurgenhaas** [comment]
@dartcafe have you noticed this? Also 0.9.2 is not published in the app store.

**Comment by v1r0x** [comment]
Yes, having problems in the build/release process. Will be uploaded, as soon as the problems are fixed.

**Comment by nextgen-networks** [comment]
@v1r0x any news about the status? Could anybody from community be of help?

**Comment by GoetheG** [comment]
> 
> 
> Waiting for a response from the NC team...

We're alwayting for a response from them :)

**Comment by v1r0x** [comment]
0.9.3 is finally released in the appstore. Happy holidays everyone! 🎅
