### ISSUE TITLE
User-selections are misaligned

### ISSUE THREAD

**Issue by jboschuk** [nextcloud/polls#452]
### What is going wrong?
**Describe the bug**
The user selections are not aligned to the option they belong to, but in smaller columns, so that the header (with all the options) is wider than the displayed selections.
The same applies to the selection-page, where the user makes his/her selections.

**To Reproduce**
1. Create poll
2. Make selections
3. Display poll

**Expected behavior**
Under each options the corresponding selections of the respective user should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16845574/50281267-3767fc80-044f-11e9-8c81-2701c32150d6.png)

Image shows not all options, but all selections.

### Information about your polls installation
**Polls version?** (see apps page)
0.9.1

**Fresh installation or update from a prior version (from which one)?**
fresh installation.
Fresh installation

**How did you install this version?(Appstore or describe installation)**
occ command (``app:install``)

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud docker

**Which Version?**
15.0.0

**List of activated apps:**
default
+mail
+deck
+gallery
+calendar
+previewgenerator
+camerarawpreviews
+music
+gpxpod
+polls

### Server configuration

**Operating system**:
Docker 18.09.0 on Ubuntu 18.04 LTS

**Web server:**

**Database:**
MySQL (MariaDB)

**Comment by dartcafe** [comment]
Fixed in 0.9.3.
