### ISSUE TITLE
Update to 0.9.3 failed for postgresql database

### ISSUE THREAD

**Issue by merrx** [nextcloud/polls#454]
### What is going wrong?
**Describe the bug**
After updating the app to version 0.9.3, the 'php occ upgrade' can't be finished, because of database errors.

**To Reproduce**
1. Update the app from 0.9.2 to 0.9.3
2. run 'php occ upgrade'

**Expected behavior**
the upgrade command shoud finish.

**Error in cmd line**
```
Updating <polls> ...
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT "id" FROM "cloud_polls_options" WHERE (poll_id = "1") AND (poll_option_text ="2018-10-05 16:00:00")':

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "1" does not exist
LINE 1: ... "id" FROM "cloud_polls_options" WHERE (poll_id = "1") AND (...
                                                             ^
Update failed
```

**Server configuration**
Nextcloud 14.0.4
PostgeSQL 11.0
Nginx 1.14.0
Ubuntu 18.04

### I found a workaround:
Change in polls/lib/Migration/Version0009Date20181125061900.php
lines 371/372
```
->where('poll_id = "' . $pollId . '"')
->andWhere('poll_option_text ="' . $text . '"');
```
to
```
->where('poll_id = \'' . $pollId . '\'')
->andWhere('poll_option_text =\'' . $text . '\'');
```
Postgresql is sensitive for " and '

**Comment by dartcafe** [comment]
Added your patch in #456

**Comment by dartcafe** [comment]
@merrx Can you confirm the bug fix? I have no chance to test on PostgreSQL.

**Comment by dartcafe** [comment]
New release 0.9.5 https://github.com/nextcloud/polls/releases/tag/0.9.5
