### ISSUE TITLE
update to 0.9.4 failed for postgres database

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/polls#457]
### What is going wrong?
**Describe the bug**
After updating the app to version 0.9.4, the 'php occ upgrade' can't be finished, because of database errors.

**To Reproduce**
1. Update the app from 0.8.3 to 0.9.4
2. run 'php occ upgrade'

**Expected behavior**
the upgrade command shoud finish correctly.

**Screenshots**
I just tried the migration from 0.8.3 to 0.9.4 and got the following error.
I did as a quick fix to get our instance back to work now disable the polls app.
.And I did migrate Nextcloud now from 14.0.4 to 15.0.0

docker-compose exec -u www-data app php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating ...
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT "id" FROM "oc_polls_options" WHERE (poll_id = '20') AND (poll_option_text ='there's coffee in that nebula...')':

SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "s"
LINE 1: ...RE (poll_id = '20') AND (poll_option_text ='there's coffee i...
^
Update failed
Maintenance mode is kept active
Reset log level

### Information about your polls installation
**Polls version?** (see apps page)
0.9.4

**Fresh installation or update from a prior version (from which one)?**

**How did you install this version?(Appstore or describe installation)**

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
15.0.0

**Comment by dartcafe** [comment]
I am getting mad. :weary:
Seems, that it is no good idea to make string based queries.

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/releases/tag/0.9.5 should fix this. Worked on different MySQL instances.

**Comment by gohrner** [comment]
> Seems, that it is no good idea to make string based queries.

Mh, right, it definitely is't - look like that was an SQL injection vulnerability (and a fairly trivial one) we had here.

**Comment by dartcafe** [comment]
@GuidoDr Is the issue solved? If yes, you can close the issue.

**Comment by GuidoDr** [comment]
yes it is solved, thanks
