### ISSUE TITLE
polls 0.9.5 does not create db-structure on NC 15

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/polls#460]
Fresh install of 0.9.5 does not create the required tables in db.
leads polls unusable :-/

**To Reproduce**
0. (optional) deinstall old polls and delete database tables
1. install polls 0.9.5 from appstore
2. open polls app
error is shwown - log says db tables are missing

**Expected behavior**
polls screen should be shown

### Information about your polls installation
**Polls version?** 0.9.5

**Fresh installation or update from a prior version (from which one)?**
fresh install

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
nextcloud

**Which Version?**
15.0.0

**Nextcloud/ownCloud version:** (see Nextcloud admin page)

```

### Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->

**Operating system**: ubuntu 16.04.05

**Web server:** apache 2

**Database:** mysql 5.5.27

**PHP version:** 7.2

**Signing status:** ok

**Comment by nextgen-networks** [comment]
@dartcafe thanks for the info - polls installed tables after deleting polls related oc_migration entries.

Having polls save issues afterwards but opening a separate issue for that.

**Comment by joergmschulz** [comment]
Thank you - that's been the solution. Issue only has been present for the test environment where I had some devel state versions. Prod upgraded without issue (could only confirm today after test went well).
