### ISSUE TITLE
Table 'nc.oc_polls_events' doesn't exist

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#463]
### What is going wrong?
Update from some unremembered develop version (around 9.3) to appstore 9.5 went wrong.
So I deleted all oc_polls table and tried to reinstall.
But, no tables are created during install.

Server: NC14.0.4
Server log prints: 
`
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT DISTINCT oc_polls_events.id, oc_polls_events.hash, oc_polls_events.type, oc_polls_events.title, oc_polls_events.description, oc_polls_events.owner, oc_polls_events.created, oc_polls_events.access, oc_polls_events.expire, oc_polls_events.is_anonymous, oc_polls_events.full_anonymous FROM oc_polls_events LEFT JOIN oc_polls_votes ON oc_polls_events.id = oc_polls_votes.id LEFT JOIN oc_polls_comments ON oc_polls_events.id = oc_polls_comments.id WHERE (oc_polls_events.access = ? AND oc_polls_events.owner = ?) OR oc_polls_events.access != ? OR oc_polls_votes.user_id = ? OR oc_polls_comments.user_id = ? ORDER BY created' with params ["hidden", "joerg.schulz", "hidden", "joerg.schulz", "joerg.schulz"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nc.oc_polls_events' doesn't exist`

**Comment by dartcafe** [comment]
see #460
