### ISSUE TITLE
Change text of "Vote!" button if a vote was already submitted.

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#473]
**Is your feature request related to a problem? Please describe.**
Just a minor visual enhancement.

**Describe the solution you'd like**
If someone has already voted the text of the "Vote!" button should change to "Update!".

**Describe alternatives you've considered**
If there have been changes made to the poll (added options, and so on) the "Update!" button could additionally change its colour.

**Comment by harcesz** [comment]
Our user have to be reminded abut clicking the "vote" button, they pick options, and assume it's auto-saved. Maybe the bottom could be dropped altogether and replaced with auto-saving picks?

**Comment by bpcurse** [comment]
@harcesz Sounds like a good idea!
The triggering of activity (email) would probably have to be adapted to this behaviour, so it doesn't spam you on each click.

**Comment by harcesz** [comment]
wait a given time from the last choice and then email?

**Comment by dartcafe** [comment]
obsolete. Ther is no vote button any more.
