### ISSUE TITLE
Old-Date Picker please!

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/polls#477]
I totally understand the wish and necessity for consistency. But I really want you to ask for another date-picker, the date-picker before 0.9.1. was wonderful.

Have you ever tried not just to add one date with the new date-picker, which is the use for every other app or maybe okay to test with, but to create a poll with 7 days and three different times for every day with the new date picker? It was a nightmare and I'm still a little bit frightened for my next planning of board conference (my use case). There have been so much clicks, and scrolls.. terrible. 

Despite of this, and foremost, I really love this app and I want to thank you for your work!

**Comment by dartcafe** [comment]
I agree with you. I am also not completely satisfied with this date picker, but it’s the one Nextcloud’s cue components use and since we decided to switch to vue, using the JQuery date picker is no more possible. 

But to get some more comfort, I am thinking about offering sequences like recurring calendar events and cloning of existing polls.

**Comment by dartcafe** [comment]
The decision, which date picker to use depends on the vue-components developer's decisions. I believe, any suggestion is welcome there. 

>  Why it's not possible to add range date with vue, please ?

Of course, this is possible and planned (i.e. #194, #201, #404, #426). But it needs more work than just adding it to the vue app. So please stay tuned...

**Comment by florom** [comment]
Hi Devs,

I really appreciate the work of the polls app in nextcloud but please find a solution for a datepicker to add more the one date eventuelly without time are set a default time in advance.

As it is now you really have to be a fan of nextcloud and privacy to use polls - Which I am but as time passes it is getting more and more difficult to convince myself that it is really worth it.

Thank you.

**Comment by dartcafe** [comment]
We will stay with the default date picker.
