### ISSUE TITLE
Not possible to vote for none of the options

### ISSUE THREAD

**Issue by mMuck** [nextcloud/polls#479]
### What is going wrong?
**Describe the bug**
In the poll/vote view I can't vote for none of the options = all red. Can anyone confirm this please for further analysis. Thx.

Not sure if this is relevant: Public user at public poll page. Anonymous poll = not showing the voters publicly. "maybe" option turned off.

**Expected behavior**
The vote should be possible. It's a possible answer for a date poll.

### Information about your polls installation
**Polls version?**
current
**Fresh installation or update from a prior version (from which one)?**
updated today from the previous version
**How did you install this version?(Appstore or describe installation)**
Appstore
### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
NC
**Which Version?**
current stable
### Client configuration
**Device:**
Desktop
**Browser:**
FF current stable
**Operating system:**
Win7

**Comment by dartcafe** [comment]
Confirmed. It is not possible to vote without a click in at least one option. But it is possible to say "no" to all options with at least clicking thru one of the options. Will check this later

**Comment by dartcafe** [comment]
Did a quick hack, to make it possible to leave all states to no, without clicking
