### ISSUE TITLE
You cannot translate some texts

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/polls#48]
Allthough changed in it.php and it.json, some text are not translate:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936230/8666965c-efbc-11e5-95d7-b99bcf0a54de.JPG)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936269/bc7eefc8-efbc-11e5-84a5-6fb52edacae2.JPG)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936283/d4591d62-efbc-11e5-80e3-0588b445f907.JPG)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936300/f422e3c6-efbc-11e5-8d05-a0ce63816fe4.JPG)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936316/1dc09836-efbd-11e5-81b5-a0c6415ca82b.JPG)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13936364/737230dc-efbd-11e5-837b-2394c7489c03.JPG)

**Comment by v1r0x** [comment]
The js strings are (from what I read in the documentation) not translatable. But I'll update the translations for the other strings.

**Comment by danielepercivaldi** [comment]
I’ve already done for italian editing files it.php and it.json. Do you need them?



[cid:logo1db0ac7]

Daniele Percivaldi

INTRE' S.r.l.
Via Gaslini, 2 - 20900 MONZA (MB) - ITALY
Tel. +39-039-28.45.774 - Fax +39-039-28.40.734
http://www.intre.it e-mail: d.percivaldi@intre.it

Nota informativa:
In ottemperanza della Legge 196/2003 sulla tutela dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate e sono esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario), tenendo presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio e' vietata. Nel caso in cui aveste ricevuto questa e-mail per errore, vogliate avvertire il mittente al piu' presto a mezzo posta elettronica e distruggere il presente messaggio.
 Please note:
This email transmission including its attachments, are intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material.  Any views or opinions are solely those of the author and do not necessarily represent those of Intré S.r.l., unless specifically stated.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited.   If you received this email in error, please contact the sender and delete the email transmission immediately.

P Please consider the environment before printing this e-mail!

Da: v1r0x [mailto:notifications@github.com]
Inviato: mercoledì 23 marzo 2016 12:13
A: v1r0x/polls <polls@noreply.github.com>
Cc: Percivaldi Daniele <d.percivaldi@intre.it>
Oggetto: Re: [polls] You cannot translate some texts (#48)


The js strings are (from what I read in the documentation) not translatable. But I'll update the translations for the other strings.

**Comment by v1r0x** [comment]
Would be great. I'll update the english and german files and then you can create a pull request for the italian version (or send them per email or gist).

**Comment by danielepercivaldi** [comment]
I think this is the better way. I'm not sure about using pull request. I cannot understand how it works ... you know, I'm not a developer.

[it.json.txt](https://github.com/v1r0x/polls/files/185911/it.json.txt)
[it.php.txt](https://github.com/v1r0x/polls/files/185912/it.php.txt)

**Comment by splitt3r** [comment]
The datepicker translation problem is somehow covered by #156 the rest should be solved.
