### ISSUE TITLE
Add option to restrict public poll creation

### ISSUE THREAD

**Issue by gaviidae** [nextcloud/polls#481]
**Which Polls version are you running?**
Version 0.9.5

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
Version 15.0.0

This is a feature request.
As admin I would like to be able to take away the possibility for registered users to create public polls (restrict them to only create polls for other registered users). Preferably there would be options to restrict poll creation parameters for users using the Administration->Sharing menu like there are for file sharing.

Explanation:
My Nextcloud instance is only for private use and I don't want any content to be accessible publicly, yet with this app it would be possible for registered users to open a public poll. Also the kind of polls I want my users to do are of no business to the public and I don't want the possibility of someone erroneously leaking private info only because they forgot to set the correct option. I want to get as close to fool proof privacy as I can get. Also due to the nature of the polls, only registered users should have a say in the outcome.
Nextcloud allows the restriction of public links to files, it should allow for the restriction of public polls.

**Comment by dartcafe** [comment]
As we do not have any adminitration section for now, I will put it into the backlog. I am not sure, but I think, you can restrict the app to groups, and it will not be accessible via public links.

**Comment by gaviidae** [comment]
I have added the group restriction in the app menu but it is still possible for users to add public polls. I checked to see if they are accessible without sign in and they are. The link suffices for access.

**Comment by dartcafe** [comment]
Sad. I thought, that a group restriction limits the access to public pages of the app by core. 
So, we keep it for the backlog until finishing the complete vue migration (which will be finished soon, I hope).
