### ISSUE TITLE
After upgrade to nc15.1, error on open poll, empty poll

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#488]
I have upgrade my NC 14.4 to 15.1, now i have an error if i open an poll:

`{"reqId":"aFnYkHjNNf4ofw3iU5V9","level":3,"time":"2019-01-11T09:04:32+00:00","remoteAddr":"11.11.12.12","user":"USER","app":"index","method":"GET","url":"\/cloud\/apps\/polls\/poll\/X6aZc4A6RyIfLfS2","message":{"Exception":"BadFunctionCallException","Message":"disallowMaybe is not a valid attribute","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Db\/Entity.php","line":146,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->","args":["disallowMaybe",["1"]]},{"file":"\/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Db\/Entity.php","line":70,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->","args":["setDisallowMaybe",["1"]]},{"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::","args":[{"id":"2","hash":"X6aZc4A6RyIfLfS2","type":"0","title":"Testumfrage","description":"testuffgob","owner":"USER","created":"2018-09-24 09:06:22","access":"user_USER2","expire":"2018-10-16 22:03:00","is_anonymous":"0","full_anonymous":"0","disallow_maybe":"1","allow_maybe":"1"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":329,"function":"call_user_func","args":["\\OCA\\Polls\\Db\\Event::fromRow",{"id":"2","hash":"X6aZc4A6RyIfLfS2","type":"0","title":"Testumfrage","description":"testuffgob","owner":"USER","created":"2018-09-24 09:06:22","access":"user_USER2","expire":"2018-10-16 22:03:00","is_anonymous":"0","full_anonymous":"0","disallow_maybe":"1","allow_maybe":"1"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":372,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":[{"id":"2","hash":"X6aZc4A6RyIfLfS2","type":"0","title":"Testumfrage","description":"testuffgob","owner":"USER","created":"2018-09-24 09:06:22","access":"user_USER2","expire":"2018-10-16 22:03:00","is_anonymous":"0","full_anonymous":"0","disallow_maybe":"1","allow_maybe":"1"}]},{"file":"\/var\/www\/html\/nextcloud\/apps\/polls\/lib\/Db\/EventMapper.php","line":60,"function":"findEntity","class":"OCP\\AppFramework\\Db\\Mapper","type":"->","args":["SELECT * FROM *PREFIX*polls_events WHERE hash = ?",["X6aZc4A6RyIfLfS2"],null,null]},{"file":"\/var\/www\/html\/nextcloud\/apps\/polls\/lib\/Controller\/PageController.php","line":228,"function":"findByHash","class":"OCA\\Polls\\Db\\EventMapper","type":"->","args":["X6aZc4A6RyIfLfS2"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"gotoPoll","class":"OCA\\Polls\\Controller\\PageController","type":"->","args":["X6aZc4A6RyIfLfS2"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Polls\\Controller\\PageController"},"gotoPoll"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Polls\\Controller\\PageController"},"gotoPoll"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Polls\\Controller\\PageController","gotoPoll",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"hash":"X6aZc4A6RyIfLfS2","_route":"polls.page.goto_poll"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"hash":"X6aZc4A6RyIfLfS2","_route":"polls.page.goto_poll"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"hash":"X6aZc4A6RyIfLfS2","_route":"polls.page.goto_poll"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/polls\/poll\/X6aZc4A6RyIfLfS2"]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Db\/Entity.php","Line":115,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.1.2"}`

Polls version 0.9.5 on a Debian Stretch with Apache2 and MariaDB.

Oh, and if i create a new poll its the same. If i click to the poll directly, the error above occurs. If i click an "edit poll" i can edit the poll but the new poll is empty?

If i edit the poll and enter new data, the "save" button hanging in "Writing Poll .." endless.

Maybe a better formated log:

```
[index] Error: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM *PREFIX*polls_events WHERE hash = ?"; parameters Array
(
    [0] => 
)
; limit ""; offset "" at <<closure>>

 0. /var/www/html/nextcloud/lib/public/AppFramework/Db/Mapper.php line 372
    findOneQuery("SELECT * FROM * ... ?", [""], null, null)
 1. /var/www/html/nextcloud/apps/polls/lib/Db/EventMapper.php line 60
    findEntity("SELECT * FROM * ... ?", [""], null, null)
 2. /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php line 357
    findByHash("")
 3. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    writePoll({id: 0,hash: "", ... e}, {pollDates: [{id ... ]}, [], "edit")
 4. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Polls\Contro ... }}, "writePoll")
 5. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Polls\Contro ... }}, "writePoll")
 6. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\Polls\\Controller\\ApiController", "writePoll", OC\AppFramework\ ... {}, {_route: "polls.api.write_poll"})
 7. <<closure>>
    __invoke({_route: "polls.api.write_poll"})
 8. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "polls.api.write_poll"})
 9. /var/www/html/nextcloud/lib/base.php line 987
    match("/apps/polls/write")
10. /var/www/html/nextcloud/index.php line 42
    handleRequest()

POST /cloud/apps/polls/write
from 11.11.12.12 by USER at 2019-01-11T09:34:50+00:00
```

**Comment by dartcafe** [comment]
From above
> disallowMaybe is not a valid attribute
This is a hint, that you updated from a test version. 
See https://github.com/nextcloud/polls/issues/482#issuecomment-451752603
