### ISSUE TITLE
[Feature Request] Custom Attributes/Additional Fields

### ISSUE THREAD

**Issue by nickisashkir** [nextcloud/polls#489]
**Is your feature request related to a problem? Please describe.**
This feature is not related to any bug right now. I am frustrated that I cannot easily add Descriptions or other various comment fields within my contents on NextCloud. I feel that Additional Fields/Custom Attributes, perhaps based upon tags should be an option. 

**Describe the solution you'd like**
I have broken this up into what Basic Functionality could look like at first. Makes it easier. But, I have also included some harder features, that I believe would be badass. 

*Basic Functionality*

* Create "Additional Fields" through an App page. It can be as simple as raw text input. 
* Display custom fields that are filled out in the sidebar of documents/items in the cloud. 
* Always have sidebar display unless hidden while viewing an image, pdf, etc.
* Default Field can be "Description" which can store a description of said item. This would get people into the idea of what these fields are meant for. 
* Edit button that lets you edit these fields once they're saved. These items are unique per file/document. So each document will need them inputted in manually or via a workflow process. 

*Intermediate Functionality*

* Allow us to control what kind of field is what. Like plain text, date, HTML/Markdown, etc. (Which we can fake or manually curate related documents)

*Advanced Functionality*

* It would be cool if these can be conditional attributes. For example: The custom fields relating to Contracts only show when the document is "tagged" contracts. Or Medical tags will only show fields relating to the tag Medical. Could be pretty powerful and allow for awesome sorting and descriptions. 
* A way to mass import data/documents to keep these fields filled out automatically. 
* A workflow process to sort through the attributes and rename files, etc based upon it. 

I have attached a mock up of the end result. 

This would revolutionize NextCloud for me and bring it to near the same level as SpringCM.

**Describe alternatives you've considered**
I've considered the comments. But, the comments are not prominent, and are meant to be comments. These are editable collaborative fields. But, they aren't descriptions.

**Additional context**
If you're interested I can create more screenshots of what the panels should look like. I don't know how complex this is. But, basically when I open a file called MSA1999.pdf I would like to see information in the sidebar about MSA1999.pdf. Such as I may have a name for it, other contracts that it is related to (that I can fill out manually using Markdown or html), the date of the contract, whether or not it is renewable (evergreen). etc. 

I used contracts as an example because I see people using NextCloud for contract management. I personally am using it to keep track of my surgeries and my medical history. So some items I would have on this: 

- Procedure Date: 2018/05/10*
- Procedure Type: AVR
- Related Documents: [Labs], [Operative Report]
- Facility Name: Cedars Sinai
- Physician: Dr. Doe

 (*medical files are required 8601 format by most government contracts and hospitals). 

Or Education:

- Academic Year: 2008-2009
- Quarter: 2nd
- Department: Social Sciences
- Teacher: Professor Flint

The possibilities are endless and having custom document fields/attribute fields/additional fields, or however you want to call them, I feel can propel NextCloud into an entirely new world of automation, document storage, file storage, and more. It doesn't need to be "amazingly" strong right now with 

A mockup of the final result is this: 
![image](https://user-images.githubusercontent.com/5299975/51081354-901f6380-16a2-11e9-9f36-12c852b09e6d.png)

I can create more previews if they're wanted. I hope this was clear enough :)

**Comment by dartcafe** [comment]
@nickisashkir Cool Idea, but I fear, you posted inside the wrong repository. This seems to adress the core of nextcloud... 
This is the polls app repository.

**Comment by nickisashkir** [comment]
> @nickisashkir Cool Idea, but I fear, you posted inside the wrong repository. This seems to adress the core of nextcloud...
> This is the polls app repository.

Thank you! I am trying to find the main repository. The website took me to the polls for issue reporting sorry about that!

**Comment by dartcafe** [comment]
Take this: https://github.com/nextcloud/server
