### ISSUE TITLE
Allow options to be exclusive 

### ISSUE THREAD

**Issue by rgr101** [nextcloud/polls#490]
Sometime it doesn't make sense to allow all options to be checked, like yes-or-no options. 

Example: 

Invitation to an event. Allowed options shall be 

- Yes, I'll attend by myself
- Yes, I'll attend and will be accompanied by my partner
- I'm so sorry, I can't attend

These options of course should be exclusive, so there might be a checkbox like 
'only allow one option per participant'

**Comment by dartcafe** [comment]
I think this is something like #352

**Comment by dartcafe** [comment]
Closed due to missing feedback

**Comment by rgr101** [comment]
Sry github didn‘t forward your post - yes you‘re right - it‘s covered by #352 ☺️
