### ISSUE TITLE
Add duration for events in the poll

### ISSUE THREAD

**Issue by budachst** [nextcloud/polls#492]
**Is your feature request related to a problem? Please describe.**
When trying to create a poll for scheduling a meeing, often times the date and starting times are not enough if dealing with a number of invitees, whose schedule is very busy. These invitees often, or almost in our case, demand a precise duration for the event in question.

**Describe the solution you'd like**
Provide a way to additionally set the duration for an event in the poll.

**Describe alternatives you've considered**
We tried text based polls, but these are not "calendarish" enough and people generally don't read all the text, if the poll is about finding a date for a meeting.

**Additional context**
Actually, doodle provides this feature and the adption will be increased and we can nudge peaople towards usingf the poll app on our NC instance, rather than doodle or the like.

**Comment by dartcafe** [comment]
👍   #194, #201, #404, #426

**Comment by dartcafe** [comment]
Adding duration and All day option to date options
