### ISSUE TITLE
Feature Request: Support Libressl

### ISSUE THREAD

**Issue by Floppybobby** [nextcloud/polls#493]
**Is your feature request related to a problem? Please describe.**
It's 2019 and we have operating systems that come with LibreSSL by default now. These operating systems should also be able to use the nextcloud client by default. 

**Describe the solution you'd like**
Support LibreSSL in addition to OpenSSL. OwnCloud is already doing this.

**Comment by dartcafe** [comment]
Wrong Repo?

**Comment by dartcafe** [comment]
@Floppybobby Seems you choosed the wron Repo for your request. Please use the server repo of nextcloud.
