### ISSUE TITLE
Bigger or auto adapting description text field

### ISSUE THREAD

**Issue by radoeka** [nextcloud/polls#495]
**Is your feature request related to a problem? Please describe.**
The description field is too small and must be resized every time.

**Describe the solution you'd like**
A bigger description field, or a description fields that shows the correct size compared to the available text.

**Describe alternatives you've considered**

**Additional context**
The description field
- shows up when the poll is created
- it is located on the left side of the page
- it is located below the title field.

**Comment by dartcafe** [comment]
Unfortunately this autoheight thing is a little bit complex. Will solve this later.
