### ISSUE TITLE
Use icons and tooltip to display access permissions in polls overview

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#497]
**Is your feature request related to a problem? Please describe.**
The text strings in the access column (public, hidden, ...) do not fit nicely into the design, especially not in the pretty display concept from #487.

**Describe the solution you'd like**
It would probably look better and save space if there were icons used in the access column instead of text strings. It might be difficult to create graphic items that are distinct enough, but this should not be a problem if a mouseover tooltip with the corresponding text string was displayed in addition.

**Comment by dartcafe** [comment]
Good idea. Do you have a proposal for the icons?

**Comment by bpcurse** [comment]
I am not very good at designing icons, but I will try to describe them. Maybe I can add a mockup later.
What I have seen on the nextcloud repository so far @jancborchardt and @skjnldsv are the right ones when it comes to this kind of design ideas.

- **Registered users:** A single or two person icon (like contacts app) with a small rectangle containing some stars to resemble a password prompt and thus a logged in user or instead of the rectangle a lock symbol or a green checkmark.
- **Hidden:** A crossed-out eye symbol (or maybe a lock symbol)
- **Public:** An icon resembling a group similar to the contacts app icon, only with a lot more people on it
- **Shared only:** Maybe the contacts app icon again, but this time only combined with a classic triangular sharing symbol

**Comment by dartcafe** [comment]
What is important is, that the icon is self speaking for a common user. The tool tip can give the right information, but we don't have it on touch devices. Nextcloud icons can be found here: https://docs.nextcloud.com/server/stable/developer_manual/design/icons.html

**Comment by bpcurse** [comment]
@dartcafe Thanks for the hint!
Then I would propose the following, taken only from the existing icons:

### Registered users: (every user account registered with the nextcloud instance)
![grafik](https://user-images.githubusercontent.com/29312856/52182869-1c382d00-2802-11e9-92fb-57539ca1fb72.png)
icon-group

### Hidden: (only the user who created the poll)
![grafik](https://user-images.githubusercontent.com/29312856/52182880-55709d00-2802-11e9-89d6-2aff600bbb38.png)
icon-category-security

_**or**_

![not_visible](https://user-images.githubusercontent.com/29312856/52183188-a3d36b00-2805-11e9-9968-b0d3fc0b83c3.png)
icon-toggle [edited]

### Public: (everyone with the link to the poll)
![grafik](https://user-images.githubusercontent.com/29312856/52182887-72a56b80-2802-11e9-8212-d5415a917d9c.png)
icon-link

_**or**_

![grafik](https://user-images.githubusercontent.com/29312856/52182912-bb5d2480-2802-11e9-8646-52ab9b0c1236.png)
icon-public

### Shared only: (a set of defined users or groups)
![grafik](https://user-images.githubusercontent.com/29312856/52182898-92d52a80-2802-11e9-8608-39a1595e8d5e.png)
icon-shared

Please check if my description in the brackets meets the actual permissions.

**Comment by dartcafe** [comment]
> ### Registered users: (every user account registered with the nextcloud instance)
> ![grafik](https://user-images.githubusercontent.com/29312856/52182869-1c382d00-2802-11e9-92fb-57539ca1fb72.png)

👍 
> ### Hidden: (only the user who created the poll)
> ![grafik](https://user-images.githubusercontent.com/29312856/52182880-55709d00-2802-11e9-89d6-2aff600bbb38.png)

👍 

> ### Public: (everyone with the link to the poll)
> ![grafik](https://user-images.githubusercontent.com/29312856/52182887-72a56b80-2802-11e9-8212-d5415a917d9c.png)

👍 

> ### Shared only: (a set of defined users or groups)
> ![grafik](https://user-images.githubusercontent.com/29312856/52182898-92d52a80-2802-11e9-8608-39a1595e8d5e.png)
👍 👎

**Comment by dartcafe** [comment]
Maybe this

> ### Shared only: (a set of defined users or groups)
> ![grafik](https://user-images.githubusercontent.com/29312856/52182912-bb5d2480-2802-11e9-8646-52ab9b0c1236.png)

**Comment by v1r0x** [comment]
> ### Shared only: (a set of defined users or groups)
> 
> ![grafik](https://user-images.githubusercontent.com/29312856/52182898-92d52a80-2802-11e9-8608-39a1595e8d5e.png)

I prefer this one over the link chain icon for shared polls. It's common as indicator for shared content.

**Comment by dartcafe** [comment]
![grafik](https://user-images.githubusercontent.com/29312856/52182898-92d52a80-2802-11e9-8608-39a1595e8d5e.png)

is normally use for share action and


![grafik](https://user-images.githubusercontent.com/29312856/52182912-bb5d2480-2802-11e9-8646-52ab9b0c1236.png)

is usally used for shared things

**Comment by v1r0x** [comment]
> ![grafik](https://user-images.githubusercontent.com/29312856/52182898-92d52a80-2802-11e9-8608-39a1595e8d5e.png)
> 
> is normally use for share action and

IMO it is used for shares with other users without a link (afair it is also used for shares in other NC apps)

> ![grafik](https://user-images.githubusercontent.com/29312856/52182912-bb5d2480-2802-11e9-8646-52ab9b0c1236.png)
> 
> is usally used for shared things

IMO this is used for shared links.

But I'm fine with both icons, what do you think @jancborchardt ?

**Comment by bpcurse** [comment]
If it is not too much effort to code, the icons could even be shown in the "create poll" view as miniatures next to the accessibility choices. This way new users would see them already on creation of a poll and learn their meaning.

![mockup_polls_creation_with_icons](https://user-images.githubusercontent.com/29312856/52290924-7dcad980-2971-11e9-936a-fb5fba255ae6.png)
