### ISSUE TITLE
Sort on colums user page

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/polls#508]
Be able to sort on columns in the user admin page, for example "last login". That way it's easier to find users who haven't logged in for a while and maybe de-activated them or delete them.

Sorting on username or quota would be handy too.

Just able to sort any column actually.

**Describe alternatives you've considered**
The alternative is going through a long list of users to find people who havent logged in for a while.

**Comment by v1r0x** [comment]
This seems to be related to nextcloud server. This is the polls app repo :wink:

**Comment by Omaha2002** [comment]
I'm sorry!
