### ISSUE TITLE
l11n incomplete

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/polls#510]
### What is going wrong?
**Describe the bug**
Some elements and tooltips seem to be be missing from the (only German?) translation

**To Reproduce**
Inspect the list view in the poll app

**Screenshots**

![z_screenshot_20190206_001](https://user-images.githubusercontent.com/8102905/52358133-c0ef8000-2a37-11e9-8ed3-157146eab071.png)

### Information about your polls installation
**Polls version?** 
0.9.5

**Fresh installation or update from a prior version (from which one)?**
Update 

**How did you install this version?(Appstore or describe installation)**
From the appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
14

**Comment by dartcafe** [comment]
Done in next release.
