### ISSUE TITLE
Anonymous polls

### ISSUE THREAD

**Issue by HAVP** [nextcloud/polls#512]
Allow fully anonymous polls where only the creator can see the votes (without names)  

**Describe the solution you'd like**
Hide all voting entries for the users.

Looks like this feature is not wanted by the developers.
You could create reals polls for voting.

**Comment by dartcafe** [comment]
> Looks like this feature is not wanted by the developers.

Yep. I see no value for this. This is a simple polls app and not showing the status and results leads to more complexity. The next question will be, how do you present the result and when to the participants. There are a lot of to dos in this repo which are much higher in priority. 

So sorry, but I think, we will not think about developing in the next time.

**Comment by virtualdxs** [comment]
This is unfortunate. Most polling apps don't allow you to see others' votes until you've already voted so others' votes don't sway yours.
