### ISSUE TITLE
[Feature Request] Allow multiple answers for options in one survey 

### ISSUE THREAD

**Issue by scroom** [nextcloud/polls#513]
**Is your feature request related to a problem? Please describe.**
I wanted to ask some of my students (we are using Nextcloud in school) some questions and realized, that I have to create one survey per question.

**Describe the solution you'd like**
Would be great to have the possibility to have several questions per survey. Something like "Add another question ..."

**Comment by dartcafe** [comment]
Ehm. Just press enter, and the option eill be added. 
![text poll](https://user-images.githubusercontent.com/26707476/52367892-68c37880-2a4d-11e9-8c34-262b4fc8b59c.gif)

**Comment by scroom** [comment]
I know that I can add options to a question but this is not what I meant. I would like to have several questions with potentially several options in one survey.

**Comment by scroom** [comment]
For example: 

1. What grade do you give to programme item 1? (Options 1,2,3,4,5,6)
2. What grade do you give to programme item 2? (Options 1,2,3,4,5,6)
....

**Comment by bpcurse** [comment]
Yes, this would be nice to have, but it sounds more like a major survey app's usecase (e.g. limesurvey that can be self-hosted and "integrated" into nextcloud via external sites app).
So I suppose this is out of scope of this app (but I am not a developer).

**Comment by dartcafe** [comment]
Hmmm. This is a polls app and not meant for this type of survey, althought it seem related. This maybe a good idea, but needs a lot of contepts to not break the current app structure. 

Not easy to implement. We had a similair issue (#403), which also needs another poll type. 

I'll put it in the backlog, but I fear this will last longer to be developed.

**Comment by UnserUp** [comment]
Personal opinion: Quite interesting proposal. It would allow to realize a survey of multiple questions.

**Comment by Rello** [comment]
+1 on this
as NC Forms is not really usable, this would be an alternative.
currently NC does not provide anything close to MS Forms unfortunately

**Comment by albertleidinger** [comment]
+1

**Comment by v1r0x** [comment]
Since NC forms exist now and aims to replace google forms (I guess MS forms is similar?), IMHO this should be better discussed there. As @dartcafe mentioned in one of his earlier posts this is different from what this polls app wants to be (a doodle alternative).
What do you think @dartcafe ?

**Comment by dartcafe** [comment]
@v1r0x I totally agree. I am watching the forms app too. And I am very satisfied, that this app aims on use cases, which people requested here. Forms seems to address some kind of surveys with another aproach, as we can do here.  So we can stay focused on simple text polls and date polls. 

There is a good discussion here: https://github.com/nextcloud/forms/issues/274

**Comment by dartcafe** [comment]
https://github.com/nextcloud/forms is the right app for this.
