### ISSUE TITLE
Resize type icons to 16px

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#516]
With 32px
![grafik](https://user-images.githubusercontent.com/26707476/52368450-b4c2ed00-2a4e-11e9-8d74-b8cd4d3bd9d5.png)

With 16 px
![grafik](https://user-images.githubusercontent.com/26707476/52368510-e1770480-2a4e-11e9-8131-b76a15f50656.png)

resizing the indicator as well
![grafik](https://user-images.githubusercontent.com/26707476/52368761-7f6acf00-2a4f-11e9-92c1-532449e3d134.png)

see discussion in #497

**Comment by v1r0x** [comment]
Is the checkmark itself important? If not, I'd suggest dropping the checkmark and only use a green dot (for the resized version). The checkmark is almost not visible, thus I'd remove it.

**Comment by dartcafe** [comment]
> Is the checkmark itself important?

Nope, whens sized to 16px, because it is too small. See #520. But I still find them too small near to the 2 lines of description. 
![grafik](https://user-images.githubusercontent.com/26707476/52930681-ac6d8a80-3349-11e9-8a85-8283ac55636e.png)
