### ISSUE TITLE
Add pictures to poll options

### ISSUE THREAD

**Issue by makayabou** [nextcloud/polls#517]
We already can create a poll by date or text item.
I would like to be able to create polls by image.
For example: wich draw should we choose as main character for our game?
Picture 1 or 2 or 3...
Thank you!

**Comment by dartcafe** [comment]
@makayabou I had this on my mind too. But an issue for the backlog.

**Comment by CATER-COM** [comment]
+1

**Comment by zer0brain** [comment]
+1

**Comment by dartcafe** [comment]
closing as duplicate of #940
