### ISSUE TITLE
Release 10.0

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#521]
@v1r0x From my point of view, we can release 10.0 after or without merging #520 . What do you think. My time ist limited at the moment, but I would like to start migration of the vote page, so we can head straight to release 1.0 and start maintenance and further development.

**Comment by dartcafe** [comment]
@v1r0x ready?

**Comment by dartcafe** [comment]
Release 0.10.0 tagged and pre-released
https://github.com/nextcloud/polls/releases/tag/v0.10.0

**Comment by dartcafe** [comment]
Waaaaa. Checkout the wrong branch. Linter failed too -> fixed.

**Comment by dartcafe** [comment]
Updated tag and release

**Comment by mr-bolle** [comment]
![22-02-_2019_20-45-03](https://user-images.githubusercontent.com/22414212/53267092-d5dc3c80-36e2-11e9-9852-e5174d5a4367.jpg)

this release does not contains all current files from the branch
Example 
* polls/appinfo/info.xml 0.9.5
* polls/jd/vote.js

**Comment by dartcafe** [comment]
Grmpfl. Shouldn't do that right before going to work, I attached the wrong file. Thanks for the hint, now you can find the correct archive attached.

**Comment by mr-bolle** [comment]
FYI: So far, the new release has not yet been made available in app store apps.nextcloud.com

**Comment by v1r0x** [comment]
Done
