### ISSUE TITLE
Resize the column that is showing the access permissions

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#523]
**Which Polls version are you running?** (see apps page)
0.10.0

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.4

### Actual behaviour
The column containing the access icons is too narrow. The description ("access", "Zugriff") is not shown properly.
![bildschirmfoto_2019-02-24_18-21-33](https://user-images.githubusercontent.com/29312856/53302668-1a8de200-3861-11e9-8ef2-fa836b91eb15.png)

### Expected behaviour
Column should have the necessary width to show the whole column label

**Comment by bpcurse** [comment]
Seems to be fixed in 10.0.1. Closing.

**Comment by dartcafe** [comment]
accidentally :sunglasses:
