### ISSUE TITLE
Archive polls

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#524]
**Is your feature request related to a problem? Please describe.**
If you want to remove a poll from the overview, you can only delete it (or set it to hidden, which doesn't remove it from your own list).

There could be a valid use case, where you want to keep polls and their results for later reference, but you don't want them to stay visible in the polls list.

**Describe the solution you'd like**
A polls archive and the option "archive poll" in the 3-dot menu could be a good way to go for this use case. As an additional sophisticated option the polls in the archive could be tagged or grouped by user defined topics.

**Describe alternatives you've considered**
An option to move old polls to the bottom of the list.

**Comment by dartcafe** [comment]
Yep. Had this on my mind too. But will come after migration the polls list to the navigation.

**Comment by dartcafe** [comment]
Poll will be moved to deleted polls like an archive.
