### ISSUE TITLE
Mark and sort polls where the user only has access due to admin privileges

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#525]
**Is your feature request related to a problem? Please describe.**
At the moment it is not visible at first which polls in the list you only see due to admin privileges and they are mixed with other polls you have normal access to.

**Describe the solution you'd like**
The polls with access only due to admin rights should be tagged somehow. e.g. the access symbol could be shown in another colour (red, blue or whatever)
Additionally polls that meet this condition, should be shown at the bottom of the list as they will probably be of low or even no interest to the user.

**Describe alternatives you've considered**
"(Do not) show only admin accessible polls" option for admin users.

**Comment by bpcurse** [comment]
After using polls for quite a while as an admin and a normal user, I would recommend the following solution (from an administrator users perspective):

- By default: Do not show polls you are not invited to and you can only gain access through admin rights (if you use Nextcloud for everyday tasks as a user that has additional admin access this should be the right default)
- In the new Polls version there could be a checkbox in the settings (bottom left) named "Admin view", "Admin access" or "Show polls as admin" or the like.
This setting can either be changed permanently if the default setting doesn't fit or if you just need to display every poll on the instance temporarily.

**Comment by dartcafe** [comment]
Had something similar i mind. Something for upcomming version.

**Comment by dartcafe** [comment]
Since we have some filters via the navigation, I assume this issue as obsolete.
