### ISSUE TITLE
Possibility to re-order Options (Text)

### ISSUE THREAD

**Issue by ElpyDE** [nextcloud/polls#529]
**Is your feature request related to a problem? Please describe.**

Sometimes it is desirable to have option in a poll in a certain order. While you add options to a text poll, they are always appended to the end of the list. If you missed an option that would better be added in the middle of the list, you can't do so. The only possibility right now is to remove all options that are supposed to be further down in the list and then re-add all of them again.

**Describe the solution you'd like**

A drag-and-drop mechanism to re-order option would be perfect.

**Describe alternatives you've considered**

One could think of an (alphabetical or alphanumerical) auto-sort. It could also be helpful in addition. However, I think that a customizable order is preferable in terms of flexibility and different use cases.

**Additional context**

It would also be cool to rename options, i.e. change their text/label. This would especially allow the correction of typos. The ability to re-order options may serve as an alternative to renaming. It's different though when there are votes already - I would assume them to be kept when renaming but adding a new option with (slightly) different name and moving it to replace the original one clearly wouldn't maintain the votes.

**Comment by g6094199** [comment]
or it would be nice that a click on the title, date, etc would order the list like in any file explorer.

**Comment by dartcafe** [comment]
Renaming is not part of #529, but reordering. Rename of an option will change the votes, because the text is compared.
