### ISSUE TITLE
CSP err with 0.10.0

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#531]
I just updated polls from git and now I receive an CSP err and a blank screen opening polls:

![bildschirmfoto 2019-02-25 um 09 37 22](https://user-images.githubusercontent.com/43957716/53324513-3d5fdb00-38e1-11e9-9015-e70a1dc3ef93.png)

In Chrome this err reads as:

> Refused to execute script from 'https://files.herrmannsdorfer.de/nextcloud/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I updated from a working release 0.9.4 using
`git clone https://github.com/nextcloud/polls.git`

0.10.0 was not offered with web updater (maybe since I was cloning the repo the last couple of updates?).

**Comment by brtptrs** [comment]
I get these CSP errors for 0.10.0 in Firefox. The upgrade was made normally via the update.

![z_screenshot_20190225_002](https://user-images.githubusercontent.com/8102905/53352240-b6cbed80-3922-11e9-851c-00964f97b478.png)

**Comment by dartcafe** [comment]
This seems not to be polls related, but there have been some changes to the CSP options in the code. I will investigate.

**Comment by dartcafe** [comment]
I cannot reproduce this. I tried this with different browsers. If you have more information...

**Comment by herrmannsdorfer** [comment]
I deleted 0.10.0 from our apps directory. Then I downloaded and enabled 0.10.1 from app store. Polls is working again.

Dunno if 0.10.1 cured the issue or the clean install from the store. In the past I did several `git clone` in order to check RCs or PRs. Maybe that broke something.

**Comment by dartcafe** [comment]
Good to read.
