### ISSUE TITLE
scroll only dates, leave participants visible

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#533]
**Is your feature request related to a problem? Please describe.**
Working in polls with many dates or text options you will need to scroll to the right and then loose the info which line belongs to which participant

**Describe the solution you'd like**
As @BurtGummer commented in #383 

> scroll only the red marked part of the poll without the names so you can always see who the values are from

![](https://user-images.githubusercontent.com/1249295/46058862-054f4300-c15d-11e8-9d08-9c333a5be05c.png)

**Describe alternatives you've considered**
none - considered buying an ultra-wide screen to work with polls consisting of daily options in a month 😄

**Comment by dartcafe** [comment]
We allready had that request. Will be part of the vue migration.

**Comment by dartcafe** [comment]
Developed in https://github.com/nextcloud/polls/tree/dev-1.0
