### ISSUE TITLE
Feature request: Support for HTTP Public Key Pinning

### ISSUE THREAD

**Issue by janipewter** [nextcloud/polls#536]
**Is your feature request related to a problem? Please describe.**
Not necessarily

**Describe the solution you'd like**
Please add support for HTTP-based Public Key Pinning (RFC 7469). I am aware this feature is dangerous and support has been removed from web browsers but I believe there is a use case for applications which require high security.  I would like the ability to pin TLS certificate public key hashes in Nextcloud server so any clients which connect will only communicate with the server if the presented certificate matches one of the pinned keys. This will entirely prevent TLS interception (essentially, man in the middle attacks) when users are behind TLS middleboxes and have CA certificates in their local trust store which can issue certificates for local use (such as filtering etc). 

**Describe alternatives you've considered**
There are no feasible alternatives for what I am trying to achieve. Certificate transparency and DNS CAA have largely replaced HPKP for general web browsing, but they cannot stop anyone issuing a self signed certificate for any domain and showing it to devices which trust that CA.

**Additional context**
Find out more about HPKP
https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning
https://tools.ietf.org/html/rfc7469

**Comment by dartcafe** [comment]
Semms, you posted in the wrong repo. Please post yout issue to the server repo https://github.com/nextcloud/server
