### ISSUE TITLE
X not visible for declined option

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/polls#537]
### What is going wrong?
the X icon is not visible for the declined option in today's build. The other icons are visible.

<img width="149" alt="x-not-visible" src="https://user-images.githubusercontent.com/6523646/53664862-19e2ba80-3c6a-11e9-96ca-1ff27cc47088.png">

**Comment by dartcafe** [comment]
Feature after discussion in #420 - Adopting doodles behavior.
