### ISSUE TITLE
all polls disappeared after update to 0.10.1

### ISSUE THREAD

**Issue by heldzz** [nextcloud/polls#540]
### What is going wrong?
all polls disappeared after update to 0.10.1

**To Reproduce**
update to 0.10.1

**Expected behavior**
normal behavior

### Information about your polls installation
0.10.1 installed directly from the app store

### Information about your Instance of Nextcloud/ownCloud
nextcloud 15.0.5
```

**Comment by Laeusel** [comment]
Hello,

exactly the same issue here.

By clicking Polls-Button, website is switching to
***/index.php/apps/polls/
back to
***/index.php/
and showing only white content.

**Comment by heldzz** [comment]
I don't know how it happend, but "accidentally" everything works fine no. I really did nothing, but now the polls appear to work as intended.
Same behavior on your side, Laeusel?

**Comment by Laeusel** [comment]
no improvement here. :-(

**Comment by Laeusel** [comment]
Update:

It depends on the Browser or some caching.
I tried it with IE instead of FF, and it works again.
Maybe in your case it was a renewal of some expired leases.?
Now i will look for suspicious data in my FF-Caches.

**Comment by dartcafe** [comment]
It is a caching issue of the browser which loads an old version of the app. Clearing website info helps. Sorry for that. I keep this issue open and pinnend.

**Comment by Dubidubiduu** [comment]
I don't get it to work again in my Firefox. Used CRTL+F5, Page Info -> Clear Cookies and Site Data and logged out an in again. No success. Even tried private mode.

Chrome/Iron works thou.

**Comment by dartcafe** [comment]
You have to clear the cache. Clearing cookies & website data has no effect. You'll find it in the settings under privacy...

**Comment by Dubidubiduu** [comment]
Thought CRTL+F5 would delete the cache for this site.. Anyway, your solution worked for me. Thanks!
