### ISSUE TITLE
Release 0.10.x regressions with IE11

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#541]
Just noticed that #445 or #446 is back with IE11 and current release 0.10.1:

![bildschirmfoto 2019-03-04 um 10 12 12](https://user-images.githubusercontent.com/43957716/53723133-53344980-3e67-11e9-9713-ef76b907831b.png)

BTW: type icons from #516 or #520 are not visible at all in IE11.

Shouldn't be highest priority but as long as MS ships IE11 maybe worth a look ...

**Comment by v1r0x** [comment]
Have you tried a forced reload (no cached version) of the page? Either <kbd>Ctrl</kbd> + <kbd>F5</kbd> or in a private window (if IE supports this).

**Comment by herrmannsdorfer** [comment]
@v1r0x That does not help.

And here comes another screenshot with more participants:

![bildschirmfoto 2019-03-04 um 10 55 03](https://user-images.githubusercontent.com/43957716/53725407-3d755300-3e6c-11e9-8a90-32cbd29e8fb4.png)

Looks like only your own votes are affected. The poll width issue from 0.9.x was different.

Adding to that: not only the type icons are missing in the polls list but also the background circle of the number of comments. CSS hell with IE 11? You have my sympathy ...

**Comment by dartcafe** [comment]
IE does not support mask-image, that why the images are not shown. 
https://caniuse.com/#search=mask-image

And the other problem: :scream: :dizzy_face: :sob: :imp: :angry: :neutral_face: :sunglasses: :innocent:

I am not willing to fix that. :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by herrmannsdorfer** [comment]
@dartcafe You have my sympathy too ...

You may label this issue _won't fix_ and close it at will. Never mind! I do not care for IE11 either.
