### ISSUE TITLE
Revamping polls

### ISSUE THREAD

**Issue by affan98** [nextcloud/polls#543]
Hi, I'm a student at the University of Maryland.  I'm working with a team of students to greatly improve the usefulness of polls.  For example we want to add more question types and other things.  Could we get in touch to discuss more

**Comment by dartcafe** [comment]
Of course, everytime. What is your intention? Taking part in development or talking about improved concepts?

**Comment by affan98** [comment]
We want to take part in development.

Let me give you some more context first.

I'm communicating to you on behalf of an 8 person team.  We are all students at UMD.  We're taking a software engineering class and as part of the class we have a semester long project.  The project that has been assigned to us is to create a forms app similar to what google has for the nextcloud platform.  

We're still in the planning phase of our project.  We aren't sure if we will build off the existing polls app or build a new app entirely.  We are also still hashing out all of the features we plan to implement.  I can send you the final list of features once we have it but right now we're looking to add more question types, change the way users respond to questions, exporting results to csv, and some other things.

What are your thoughts?
Do you believe that this should be built into the polls app?
Or should we make a new app?
Are there any features you would like to see?
Which features of the existing polls app do you think are outdated or are broken?
Which features of the existing polls app would you like us to carry over? 
If we build off of the existing app are there any guidelines we need to follow?

**Comment by dartcafe** [comment]
Hey. If you surf around the issues in this repo, you will find some of your features as requests. We will bring them into the polls app, as long as it keeps complexity manageable. The main problem of an app will be getting more and more features, but loosing focus of architecture and the ability of maintenance and testability. 

And we should not loose the focus of the main thought behind this app. The guys at doodle didn't change much of their app in the last years, but added features in a homeopathic way. 

The core question is: What do you want to achieve? Doing a project for three months and then do the next thing? Or take part in a development on top of an existing app and continue participation?

So you have three options:
- Take part in the development of the app and make your experience in managing an intercontinal project
- Build a complete new app for your project
- Make a fork and build your features on top of this. 

Every option has its pros and cons.

**Comment by affan98** [comment]
I see, so the current polls app is an alternative to doodle.  We are trying to build an alternative to google forms so that means we need to build a new app.  We will probably end up using some of the code that is already in polls.  For example the sharing features you have built will be useful for us too.

Thanks for your help

**Comment by dartcafe** [comment]
Ah ok. Now I see. Yes I would recommend to build a new app. Especially because you have a project duration, which maybe will not meet our speed. :-) Looking forward to you solution. And of course, you can use parts or all of the source as long as you respect the licence conditions, it is open source.
