### ISSUE TITLE
Still can vote after poll expired, self vote disappears

### ISSUE THREAD

**Issue by andriusign** [nextcloud/polls#545]
**Which Polls version are you running?** (see apps page)
 0.10.1
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.5
### Steps to reproduce
1. Create poll, set poll expire date, vote. 
2. After poll expired open poll and click button "Vote".

### Actual behaviour
After clicking "Vote" button self vote disappears.

### Expected behaviour
Voting after poll expired is not possible, even for the creator. Button "Vote" is not active, nor triggers any action.

**Comment by dartcafe** [comment]
I cannot reproduce this. If an poll is expired, voting is no more possible. Do you have some more information, so I can reproduce this.

**Comment by andriusign** [comment]
I have uploaded screencast here: https://we.tl/t-EXwgzDWXIM
Will be deleted on 22 March, 2019. Please check or download until then.
--

**Comment by dartcafe** [comment]
Great, thanks. Nice find. I will fix that.

**Comment by andriusign** [comment]
Maybe it is possible to hide the "Vote" button at all after the voting has ended?

**Comment by dartcafe** [comment]
Yeah. Something like this.

**Comment by dartcafe** [comment]
Hopefully solved in 1.0
