### ISSUE TITLE
Unchecking "Expires" checkbox does not make poll active.

### ISSUE THREAD

**Issue by andriusign** [nextcloud/polls#546]
**Which Polls version are you running?** (see apps page)
 0.10.1
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.5
### Steps to reproduce
1. Create poll, set poll expire date, vote. 
2. After poll expired, open poll settings, unlock configuration, uncheck "Expires" (do not edit date/time), save.

### Actual behaviour
Poll is still expired. Need to readjust date to make poll active again.

### Expected behaviour
Poll is active after unchecking "Expires" checkbox without changing the date/time.

**Comment by dartcafe** [comment]
The expiration is represented of an existing expiration date in the data base. I did not find a way to set this date to null unsing the standard i/o. Just rise the expiration date as work around.

Maybe we have to add a concrete switch.

**Comment by andriusign** [comment]
Could you please refer me to the place in code which does that saving? I might figure out something. :)

**Comment by dartcafe** [comment]
All happens in thi function:

https://github.com/nextcloud/polls/blob/49a84c9bf7e13bb664f2ee13cc49f046d39aea3e/lib/Controller/ApiController.php#L411

SetExpire = null
https://github.com/nextcloud/polls/blob/49a84c9bf7e13bb664f2ee13cc49f046d39aea3e/lib/Controller/ApiController.php#L444-L448

And Write it via Mapper

https://github.com/nextcloud/polls/blob/49a84c9bf7e13bb664f2ee13cc49f046d39aea3e/lib/Controller/ApiController.php#L470

**Comment by dartcafe** [comment]
Just set a valid expiry date.
