### ISSUE TITLE
Cannot choose an option on Safari on iOS

### ISSUE THREAD

**Issue by thoschl** [nextcloud/polls#550]
### Cannot choose an option on Safari on iOS

I sent a Text based poll. But the Users were not able to choose an option when using Safari Browser on iOS 
**To Reproduce**
1. Create a poll
2. Sent link to poll by iMessage
3. The receiver is able to open the poll but cannot choose an option or cklick on answer.

**Expected behavior**
Choose an option and click on answer to take part in a poll.

### Information about your polls installation
**Polls version? 0.10.2** 

**Updated from a 0.10.1**

**Comment by dartcafe** [comment]
Just testet on Safari with iOS and MacOS. But it works. Can you send me a link to the poll?
