### ISSUE TITLE
Add extra form to poll 

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/polls#552]
Mockup:
![setup](https://user-images.githubusercontent.com/7795891/54687594-49277180-4b1c-11e9-8f86-644cf8c73045.png)

![Vote](https://user-images.githubusercontent.com/7795891/54687727-8e4ba380-4b1c-11e9-8f7f-65488e4d37be.png)

**Comment by dartcafe** [comment]
Can you describe more detailed, what your CR is about?

**Comment by Mannshoch** [comment]
What do you mean with CR?

**Comment by dartcafe** [comment]
Change Request.

**Comment by Mannshoch** [comment]
Goal of these request is to get some personal Data from the participant. It could be used If I do not know him. Also it could be used to try to start a conversation or comment the poll itself.

**Comment by aslmx** [comment]
:+1: 

This could also aid to get recommendations for alternatives. 

Imagine you have a poll but you forgot some options (for what ever reasons), you could add a field to have users let you know.

Of course eMail - to have a very basic and rudimentary control of who voted, is also a nice idea.

Would appreciate if this gets some priority :)

**Comment by dartcafe** [comment]
@aslmx Commenting is already possible, why another comment field?

**Comment by dartcafe** [comment]
@Mannshoch Additinal fields will raise complexity and has carries some new UX challenges. Sounds like an edge case. I do not see the value of additional fields comparing to the effort.

**Comment by Mannshoch** [comment]
Could you please add this ticket to the backlog for the UX. I hope there will be a time when there will be a redesign of the UI and you maybe pick it up again.
