### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by tgrignon** [nextcloud/polls#553]
We use Poll for our nonprofit organization to take resolutions. When everyone has voted, we close the poll with expiration date.

I want to know if it's possible to create a filter feature where, by default, show everything or we can show only non-expired polls (maybe just a toggle button?).

Other thing, when the poll is expired I make a screenshot and save the current result. Is it possible to have a button to export to PNG the result of the poll?

Thank you

**Comment by Mannshoch** [comment]
I vote additional for a CSV, ICS/CalDAV and SVG export.

**Comment by dartcafe** [comment]
The filters (or categories including an archive), will come later. Expired polls should then move to an archive by time or by archiving them explicitly. 

A CSV-Export is on the todo list as well as calDAV. Bit this will take some time.

**Comment by dartcafe** [comment]
I think, this request is obolete since introducing the navigation and it's sections.
