### ISSUE TITLE
End-Date and Right-Management

### ISSUE THREAD

**Issue by k-0** [nextcloud/polls#554]
One problem is that every user sees all other groups and users while sharing, regardless of their group. It makes sense here that he sees only group members to share.

Another problem is that there is only one start time an no end time for the polls.

**Comment by dartcafe** [comment]
The duration of an appoinment is on the todo list and will com. I am not sure, about the right management. 
I understand you right, you like to see, that polls are restricted to group members of the owner of the poll?

Why not using a hidden poll and invite the group?
