### ISSUE TITLE
Feature: Possibility to invite local/external users

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#555]
Hi,

it would be nice to be able to directly invite local users (maybe via the activity tab and info popup on the client). Like the calendar does in activity.
We can just have an field to typ the names of the useres to invite?
For external users just add the email adresses or use the local address books infos while typing names.

Sash

**Comment by dartcafe** [comment]
Will come. I recently experimented with this. Is a little bit tricky. The invitations need a rework.
