### ISSUE TITLE
add optional fields 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/polls#560]
Hi, 
is it possible to give the possibility to add fields the user have to fill out e.g.
my age is: ___
I will bring to the meeting: ___
My level is: ___

The same as asked here: https://help.nextcloud.com/t/google-forms-like-survey/27374/5

Thanks!

**Comment by dartcafe** [comment]
There are many requests for other kind of polls, I will think about it, when going into this.

**Comment by aslmx** [comment]
I guess this is similar to https://github.com/nextcloud/polls/issues/552 and might be combined?

**Comment by jakobroehrl** [comment]
@aslmx: Yes that's right.
