### ISSUE TITLE
votes are missing

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/polls#561]
**Which Polls version are you running?** (see apps page)
0.10.2
**Nextcloud or ownCloud?:**

Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
 15.0.5

### Steps to reproduce
1. unknown
2.
3.

### Actual behaviour
I created two polls sent the link to the participants, set the Checkbox to receive voting Infos.

I got 10 emails but have only 8 votes in my polls I each of the polls one vote from different participants is missing.

### Expected behaviour
Email should only be send when vote is saved without error

**In case of a bug, please answer the following questions**

### Server configuration

**Where did you install Nextcloud from:**
nextcloud repo

**Operating system**:
Debian 9.8
**Web server:**
 Apache/2.4.25 (Debian)
**Database:**
10.1.26-MariaDB-0+deb9u1 Debian 9.1
**PHP version:**
7.0.33.0

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bookmarks: 0.16.4
  - calendar: 1.6.4
  - circles: 0.16.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - deck: 0.5.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.6
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.1
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.5
  - fulltextsearch_elasticsearch: 1.2.4
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.6
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - rainloop: 6.0.2
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - socialsharing_facebook: 1.0.4
  - socialsharing_twitter: 1.0.4
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - w2g2: 2.2.4
  - workflowengine: 1.5.0
Disabled:
  - caniupdate
  - encryption
  - gallery
  - mail
  - mindmaps
  - mood
  - notes
  - user_ldap

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmname",
            "vmname.local",
            "unknown.cloud.de",
            "192.168.123.29"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 180,
        "overwrite.cli.url": "https:\/\/unknown.cloud.de",
        "overwritehost": "unknown.cloud..de",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "skeletondirectory": "",
        "share_folder": "\/Mit mir geteilt",
        "loglevel": 0,
        "theme": "",
        "auth.bruteforce.protection.enabled": false
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
None

### Client configuration
**Browser:**
Chrome / Edge
**Operating system:**
W7 / W10
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
Could not reproduce this, sorry.
