### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Manuelibt** [nextcloud/polls#562]
### What is going wrong?
The App shows a blank screen

**To Reproduce**
Updatet to newest version10.2

Nextcloud Version is 15.6

**Comment by dartcafe** [comment]
Normally, this occurs, if the application is updated. This is a browser caching problem. Clear your website data. Actually, it should be OK now. Time heals this automatically, when the cache is out of date. Pleas give information, if the problem still exists.
