### ISSUE TITLE
Mark unvoted options after poll edit as unknown as opposed to not available

### ISSUE THREAD

**Issue by maralorn** [nextcloud/polls#564]
**Is your feature request related to a problem? Please describe.**
When a poll is edit, it appears that the added options look as being voted  as "not available" for all people who did not update their entries. It would be nice to be able to distinguish between not updated and actually not available entries.

**Describe the solution you'd like**
Those fields, where the corresponding voter hasn't yet updated their results should be marked with a grey question mark or similar. This shouldn't be hard since the app already knows for which entries this applies, since it shows them as "new" to the voting user.

**Comment by dartcafe** [comment]
From the creator's view it is wanted to know, which date in a date poll is accepted by all participants. If someone did not opt in for a specific date, he does not vote for this date. So it is a no for this date option.

**Comment by maralorn** [comment]
That is an interesting response. Other polling software handles this differently.
Is there any other way for the creator to see who did update their response after adding the new dates? In real life situations about making an appointment that is a very relevant information.
