### ISSUE TITLE
Option to remove users

### ISSUE THREAD

**Issue by xylo** [nextcloud/polls#566]
**Is your feature request related to a problem? Please describe.**
I run into the need of removing users from a poll already multiple times.  Here are two use cases:
1) You created a poll and want to send the link to some people.  But before, you want to test if they can actually fill in their dates.  So you create a test user that you cannot remove afterwards. :(  I guess everybody runs in this for the first time.
2) When somebody accidentally mistype his/her name they probably want to correct there mistake.  They might also create a new row with their correct name.  But one of these rows have to be removed to get valid poll results.

**Describe the solution you'd like**
It would be nice to have a remove button behind the name or at the end of the row.  A click on the button should ask the user for confirmation and if this is given the row should be removed.

**Describe alternatives you've considered**
The confirmation would be nice but is optional.

**Comment by dartcafe** [comment]
Editing votes and users is an existing request. Deleting includes this.

**Comment by wunschadresse** [comment]
for those who land here, without knowing where to look further: https://github.com/nextcloud/polls/issues/377
