### ISSUE TITLE
Participation State "Possibly" not Considered in a Meaningful Way

### ISSUE THREAD

**Issue by gohrner** [nextcloud/polls#568]
### What is going wrong?
**Describe the bug**

The "possibly" participation state does not really seem to be considered in a meaningful way.

**To Reproduce**
1. Create a poll which allows "possibly" besides "attend / don't attend".

**Expected behavior**

The "possibly" state should count
1. as participation
1. or partial participation and partial rejection
1. or be displayed separately for a date, besides participation and non-participation.

In fact, however, it does not seem to be taken into account at all for scheduling decisions.

**Screenshots**

![image](https://user-images.githubusercontent.com/26199042/56082304-8af3c100-5e17-11e9-9cf6-a525abfa7bd2.png)

### Information about your polls installation
**Polls version?** 0.10.2

**Fresh installation or update from a prior version (from which one)?**

Upgrade from some 0.9.x version via some 0.10.x versions.

**How did you install this version?(Appstore or describe installation)**

Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**

NextCloud

**Which Version?**

15.0.7

**Nextcloud/ownCloud version:** (see Nextcloud admin page)

???

**List of activated apps:**

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Server configuration

**Operating system**:

Debian 9 Stretch

**Web server:**

Apache 2.4.25-3+deb9u7

**Database:**

MariaDB 10.1.37-0+deb9u1

**PHP version:**

7.0.33-0+deb9u3

**Signing status:**

```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:**

none

### Client configuration
**Device:**

Desktop

**Browser:**

Chromium
Version 73.0.3683.86 (Offizieller Build)

**Operating system:**

Ubuntu 18.04

**Comment by v1r0x** [comment]
> 2. or partial participation and partial rejection

 I don't see the difference to the current solution. It either doesn't affect the result or is not necessarily a better date, if you have 4 yes, 2 maybe, 0 no on the one hand and 1 yes, 5 maybe, 0 no on the other. 4 definite yes may be better than 1 definite yes and 5 maybe, but it may be the other way round. Depends on the question/options asked. Same for the option 1.

> 3. or be displayed separately for a date, besides participation and non-participation.

This might be too much information in the UI, but I'm open to suggestions. What's your opinion @dartcafe ?

**Comment by gohrner** [comment]
> > 1. or be displayed separately for a date, besides participation and non-participation.
> This might be too much information in the UI, but I'm open to suggestions. What's your opinion @dartcafe ?

Well, if you have one date with 2 yes and no maybe and another date with 2 yes and 3 maybe, the latter date probably would be preferrable.

Currently you do not get a clear indication for this, if you do not have a closer look at the actual voting details.

**Comment by dartcafe** [comment]
Displaying the undecided count has no woth in my eyes. But actually it is respected for the decicion, which is the best option. If there is a standoff between options, the one with the undecided votes have more weight.
