### ISSUE TITLE
Names under 3 characters not allowed in poll responses

### ISSUE THREAD

**Issue by cmho** [nextcloud/polls#570]
### What is going wrong?
**Describe the bug**
When responding to polls, people with names shorter than 3 characters (e.g. Ry, Ty, Ed) 

**To Reproduce**
1. Go to a publicly-shared poll
2. Attempt to enter a response with a two-character name

**Expected behavior**
Since two character names/nicknames aren't unheard of, the poll should allow a response  from anyone entering at least two characters, or perhaps just any response at all.

**Screenshots**

![](https://cdn.discordapp.com/attachments/557043304408285184/568579024918544385/Screen_Shot_2019-04-18_at_6.29.51_PM.png)
The above message came up when entering a name as "Ry"

### Information about your polls installation
**Polls version?** (see apps page)
0.10.2

**Fresh installation or update from a prior version (from which one)?**
Fresh

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
NextCloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.7

**List of activated apps:**

Accessibility 1.1.0, Activity 2.8.2, AppOrder 0.6.0, Audio Player 2.6.1, Calendar 1.6.4, Collabora Onlin 3.2.4, Collaborative tags 1.5.0, Comments 1.5.0, Contacts 3.1.1, Custom CSS 1.3.0, Deleted files 1.5.0, Federation 1.5.0, File sharing 1.7.0, First run wizard 2.4.0, Full text search 1.2.5, Full text search - Bookmarks 1.2.0, Full text search - Files 1.2.6, Gallery 18.2.0, Log Reader 2.0.0, Mail 0.11.1, Markdown Editor 2.0.6, Monitoring 1.5.0, News 13.1.6, Nextcloud announcements 1.4.0, Notes 2.6.0, Notifications 2.3.0, Password policy 1.5.0, PDF viewer 1.4.0, Share by mail 1.5.0, Social 0.1.4, Support 1.0.0,  Talk 5.0.3, Text editor 2.7.0, Theming 1.6.0, Update notification 1.5.0, Usage survey 1.3.0, Versions 1.8.0, Video player 1.4.0, Auditing / Logging 1.5.0, Default encryption module 2.3.0, External storage support 1.6.0, JavaScript XMPP Chat 3.4.3, LDAP user and group backend 1.5.0, Notifications for calendar event updates 0.3.4

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
**Nextcloud configuration:**

**Operating system**: Ubuntu 16

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.2

**Signing status:** 

```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
n/a

### Client configuration
**Device:**
Desktop/MacBook Pro 

**Browser:**
Firefox

**Operating system:**
High Sierra

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
We will think about that, when we change the usage of public users.

**Comment by dartcafe** [comment]
Edge case. keep 3 characters as min. limit

**Comment by sublimemarch** [comment]
Respectfully, I strongly disagree that this is an edge case. There are many, many people around the world with two character names, and short names are significantly more common in some places than others. I have several friends with two character names who currently have to add a strange extra character when attempting to fill out a poll I send them (for example, "Al?" instead of their name "Al"). A person's name is a critical part of who they are, and isn't an edge case to them. Not being able to type one's name is a pretty significant barrier to using this tool. Are you open to others submitting pull requests to resolve this issue?
