### ISSUE TITLE
Created date in list incorrect and translations issue

### ISSUE THREAD

**Issue by Alex9779** [nextcloud/polls#577]
### What is going wrong?
**Describe the bug**
Using localized view of Nextcloud (German) but the list of polls shows created dates and expiry dates not translated. Also the time base for calculating the created date seem to be UTC.

**To Reproduce**
German localization active, Server in Europe/Berlin locale and timezone

**Expected behavior**
Translated information correctly calculated

**Screenshots**
![image](https://user-images.githubusercontent.com/6394581/57213862-5a531180-6fe8-11e9-8c44-1025686a4225.png)
The polls have just been created, so there should be "just now" in the column or better "Gerade eben" translated.
Time information works for the normal system just fine, created folders show the info correctly so do files...

### Information about your polls installation
**Polls version?** (see apps page)
0.10.2

**Fresh installation or update from a prior version (from which one)?**
fresh

**How did you install this version?(Appstore or describe installation)**
added app from AppStore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
15.0.7

Hope thats enough information...

**Comment by dartcafe** [comment]
Fixed in 1.0 but still need timezone correction (WIP).
