### ISSUE TITLE
wrong connection between external users and nextcloud users

### ISSUE THREAD

**Issue by verqueert** [nextcloud/polls#578]
### What is going wrong?
**Describe the bug**
If a external user with no nextcloud user add himself to a poll we get a wrong result if the name the external user is using is similar to a username of a nextcloud user.
In this case poll builds a connection to this user and shows his name.

This automatic connection makes only sense in an internal poll.

**To Reproduce**

for example: wie have a nextcloud user called john (full name john Smith), if an other user with no nextcloud acces is invited to a poll and hi is writing as name "john", John Smith is immediately displayed.

**Expected behavior**
Expected is, that only "John" is displayed

**Screenshots**

### Information about your polls installation
**Polls version?** (see apps page)
0.10.2
**Fresh installation or update from a prior version (from which one)?**
fresh installation
**How did you install this version?(Appstore or describe installation)**
appstore
### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
nextcloud
**Which Version?**
15.05
**Nextcloud/ownCloud version:** (see Nextcloud admin page)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by verqueert** [comment]
If a external user with no nextcloud user add himself to a poll we get a wrong result if the name the external user is using is similar to a username of a nextcloud user.
In this case poll builds a connection to this user and shows his name.
for example: wie have a nextcloud user called john (full name john Smith), if an other user with no nextcloud acces is invited to a poll and hi is writing as name "john", John Smith is immediately displayed.

This automatic connection makes only sense in an internal poll.

**Comment by dartcafe** [comment]
Yep. We already have an issue for that, so I will close this as a dublicate. User handling of public users is still a to do.
