### ISSUE TITLE
Do not default to negative vote

### ISSUE THREAD

**Issue by frankm42** [nextcloud/polls#581]
### What is going wrong?
When a user opens the poll (and has not yet voted) the default reply of that user is already set to negative. This is very confusing as it looks like there is already a negative reply for all dates.

**Expected behavior**
There should not be any choice preset before the user has actually entered something.

**Comment by frankm42** [comment]
> To A) The default is a opt out, so this is wanted behavior. BUT: a user cannot tell, if he has already voted, if all is set to unvoted. So there should be an edit option to change the vote.

I am not quite sure what you mean. I don't find the current behaviour intuitive in any way, and neither are the users I have spoken to. If there needs to be a preset vote it should be yellow/undecided but I don;t really see why this should be necessary

**Comment by dartcafe** [comment]
Which state should be default, if not "no"?

**Comment by osfrance** [comment]
I agree with @franckm42 it's a better thing if the default vote for a new user's poll is "yellow/undecided" and not "no". It's possible to change this with modifying a default variable in the code ?

**Comment by v1r0x** [comment]
I'd keep it that way. Yellow is only available if the 'maybe' option is checked in the poll settings. Also this is an ongoing discussion. After switching the default from 'maybe' to 'no' there are people arguing for 'maybe' and after switching back it's vice versa.
