### ISSUE TITLE
The comment section can be mistaken for a login field

### ISSUE THREAD

**Issue by frankm42** [nextcloud/polls#582]
### What is going wrong?
Even with only a handful users, I have had several cases where users have entered their password into the comment field, because they mistook it for the login form. As this comment cannot be edited again, this is quite a problem.
In organisations with > 5 users, this will rather be a daily occurance I'd assume.

**Expected behavior**
Simplest solution could be to make the comment field larger to make it obvious it is a text field.

**Comment by frankm42** [comment]
#580 
> To B) Good point, we should overthink that. There should also be a synchronisation between the user names.

We could use the username that is entered to vote. Does this still work without a session when the site is reloaded?

**Comment by dartcafe** [comment]
If we recognise the user, this is possible.

**Comment by dartcafe** [comment]
Username must be provided before voting of public polls.
