### ISSUE TITLE
There is no login field

### ISSUE THREAD

**Issue by frankm42** [nextcloud/polls#583]
### What is going wrong?
I have had (angry) users tell me they couldn't find the login field when they accessed the poll through a link.

**Expected behavior**
Adding a link to the login page with a jump back action to the poll after login would solve this.

**Comment by frankm42** [comment]
#580 
> To C) You mean, when the poll is not a public one?

Even if the poll is public, users can login if they have an account.

**Comment by dartcafe** [comment]
When a public poll is enteresd and the user is not logged in, the poll is delivered on a public page with no login option. This is default behaviour. The user can click on the NC icon, log in and reenter the poll as logged in user.
