### ISSUE TITLE
Name as URL-Parameter

### ISSUE THREAD

**Issue by rschrenk** [nextcloud/polls#587]
**Is your feature request related to a problem? Please describe.**
When distributing the poll via URL anonymous users have to choose their name on their own. It would be more userfriendly if (at least for some cases) we could provide the name by passing an url-parameter.

**Describe the solution you'd like**
If the URL is called and the parameter ?name=Robert is passed along with it the poll should automatically suggest the name "Robert" in the textfield. If I want so I could change the name, but most users will keep it.

That way it would be possible to integrate the name with the link in most newsletter-systems and such.

**Additional context**
Etherpad for example uses the same idea and allows several paramters --> [https://github.com/ether/etherpad-lite/wiki/Embed-Parameters](https://github.com/ether/etherpad-lite/wiki/Embed-Parameters)

**Comment by dartcafe** [comment]
As you are able to invite people from your contacts list, I think this feature is obsolete. Agree? Otherwise it would get complex adding individual parameters to add parameters to the share link.

**Comment by rschrenk** [comment]
Hi, I would not agree that the contacts list is the same functionality. In our case the nextCloud is only used in our team. We are organizing conferences with a huge amount of participants and allow them to take place in various polls to manage enrolment to slots.

So the participants do not have a nextCloud-account, but we share the links in Moodle-courses where they are authenticated participants. That way it is possible to extend the links that are shown to the users dynamically. I think that also other systems that are used to distribute hyper links are capable of extending URLs with dynamic fields.

I think it would not be hard just to implement to retrieve a GET-parameter as a name, if the participant of the poll is not authenticated in nextCloud, but it would raise convenience of using it with a bunch of people.

**Comment by dartcafe** [comment]
https://github.com/nextcloud/forms is the right app for this.
