### ISSUE TITLE
New line in description ends up with <br/>

### ISSUE THREAD

**Issue by darootler** [nextcloud/polls#59]
Hi,

if you write multiple lines in the field "Description" the break will be shown as `<br/>` and no new line is added.

Here are some screenshot:

![image](https://cloud.githubusercontent.com/assets/11849583/14844496/11f4a4ae-0c58-11e6-8233-ee6a32152c14.png)

![image](https://cloud.githubusercontent.com/assets/11849583/14844516/2d26fa7e-0c58-11e6-96d0-1f1c2c3e084b.png)

Regards
Richard

**Comment by theonlytruth** [comment]
Today I tried polls and had this problem again. Can someone confirm this?

**Comment by dartcafe** [comment]
Jup. Confirmed.

**Comment by v1r0x** [comment]
It's all your fault @dartcafe 😝 see #233

**Comment by dartcafe** [comment]
Should be fixed with #260. See https://github.com/nextcloud/polls/pull/260#issuecomment-349417659

**Comment by dartcafe** [comment]
@v1r0x: Can you confirm the fix? If so we can release 0.8.1 an head on.

**Comment by v1r0x** [comment]
@dartcafe Last time I tested it worked as expected 👍

**Comment by rubo77** [comment]
line breaks don't end up with a BR any more, but they are gone alltogether, so it is not possible to add a newline in the output of the poll-description.

see #500
