### ISSUE TITLE
Drop down menus not clickable in mobile view

### ISSUE THREAD

**Issue by coxtor** [nextcloud/polls#594]
### What is going wrong?
**Describe the bug**
When viewing the app on a mobile browser the drop down sections are unclickable. This also applies when using the "view desktop version" functionality of the browser. The issue persists on at least Firefox and Chrome mobile. 

**To Reproduce**
1. Open the app and create a poll
2. Return to poll overview
3. Click on the three dots to open the dropdown
4. Try to select any element

**Expected behavior**
The menu points are clickable.

**Screenshots**

### Information about your polls installation
0.10.2

**Fresh installation or update from a prior version (from which one)?**
docker nextcloud 16, issue also occurs on nextcloud 15

**How did you install this version?(Appstore or describe installation)**
appstore

**Comment by welshcoder** [comment]
Hi,

I can confirm this bug also appears in Safari using iPhone iOS 11.4 and in Firefox 68.0 on Android 8.0.0 on a Samsung Galaxy S7 too.
Using Polls 0.10.2, NC 16.0.3 (manual clean install) and PHP 7.1 on FreeBSD 11.2.
I hope that helps.

**Comment by Ich5003** [comment]
Bug is still present.
Chrome on Android 10, Pixel 3a

In my opinion this is one of the most important bugs to fix, because not being able to share a poll on mobile phone prevents using this in any productive area
