### ISSUE TITLE
List of polls inaccessible with Microsoft Edge

### ISSUE THREAD

**Issue by borisa31** [nextcloud/polls#599]
### What is going wrong?
After login, when i try to view lists of polls with Microsoft Edge
i have the message : "Error while loading this page
We have tried to load this page several times, but the problem with this site persists and more important tasks must await you. So, rather than continue to infinity, try again later."

**To Reproduce**
1. Open Microsoft Edge and login on Nextcloud https://mynextcloud.com
2. Click on 'Polls' (top menu)
3. See error
"Error while loading this page
We have tried to load this page several times, but the problem with this site persists and more important tasks must await you. So, rather than continue to infinity, try again later."

**Expected behavior**
View the list of polls with Microsoft Edge
url : https://mynextcloud.com/index.php/apps/polls/

This page correctly display on Firefox or Chrome

### Information about your polls installation
**Polls version?** (see apps page)
0.10.2

**Fresh installation or update from a prior version (from which one)?**
Fresh installation

**How did you install this version?(Appstore or describe installation)**
Appstore 

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud 

**Which Version?**
15.0.7

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
I cannot confirm this bug. I can access the polls without problems with Edge. Can you add a screenshot of the error message?

**Comment by borisa31** [comment]
> 
> I cannot confirm this bug. I can access the polls without problems with Edge. Can you add a screenshot of the error message?

Test on Microsoft Edge 41.16299.785.0

![2019-06-11 11_19_29-Microsoft Edge](https://user-images.githubusercontent.com/51477512/59260242-8bec7780-8c3b-11e9-93d8-379472a5e87d.png)

**Comment by dartcafe** [comment]
Sorry, but I could not reprouce this behavior on all instances. I tried hardly.

**Comment by element303** [comment]
Okay, maybe it's an firewall problem (waf) in my company.
The problem persists with me, thank you for trying anyway

**Comment by AJHoeh** [comment]
Hey, I experience the same issue. Chrome and firefox work fine but when testing with edge I recieve the same error message. Is it really possible that this is firewall related?

**Comment by dartcafe** [comment]
As long, as I am not able to reproduce this, it is difficult to analyse this issue. Since Edge will be history soon, please use another browser.

**Comment by Ich5003** [comment]
Same problem here.
Current edge version shows the loading animation multiple times and then the error pages.
Current polls and nextcloud version.
