### ISSUE TITLE
Description formatted text

### ISSUE THREAD

**Issue by clippde** [nextcloud/polls#603]
I would appreciate formatted text in description field:
line breaks, Headlines, image, etc.

Maybe put possibility of html-tags to this field.
Prior-ranking from my point of view should be line-breaks, as a basic feature.
Longer Texts are not structurable.

Occasion: I require a decided description for my polls, at best with images included.
Something likewise html/CSS, tiny MCE would be perfect.

**Comment by dartcafe** [comment]
I will try tiptap, when the vue migration is finished.

**Comment by nextgen-networks** [comment]
Some Polls are complex and need an explanation that faces their complexity.
Formatting would be of great help here! :-)

Thanks!

**Comment by mMuck** [comment]
`\n` will add a linebreak, but I would prefer markdown. May apps use it.

@dartcafe  Until the tiptap solution is ready (great idea BTW) perhaps you can add a simple markdown renderer like that one from the readme.md project...

This is a feature which will give a great value to the poll app! Thanks. :smile: :+1:

**Comment by dartcafe** [comment]
This will double the work and maybe makes a migration necessary. And: Limited time at the moment.

**Comment by mMuck** [comment]
Then tiptap would be a good option.

**Comment by dartcafe** [comment]
#325
