### ISSUE TITLE
Messed up Database

### ISSUE THREAD

**Issue by Manuelibt** [nextcloud/polls#605]
Hello, 

i messed up the database because of an update issue.. 
I was hoping, that the database is building up itself by reinstalling the app. That didn't happen.. 
What can i do to reinstall the database? 

Thanks for your help!

**Comment by dartcafe** [comment]
Delete all oc_polls_* dbs. Unfortunately app DBs are not deleted after removing an app.

**Comment by Manuelibt** [comment]
Hello and thanks for your answer. I tried it, but after reinstall the db were not build up again. Is there anything else i have to delete to start clean?

**Comment by dartcafe** [comment]
look inside the oc_migration and delete the records for the polls app. After thatthe migration system should rebulild the proper dbstructure. I forgot to mention that.

**Comment by Manuelibt** [comment]
THANK YOU! That helped.
