### ISSUE TITLE
Feature request: Download Permission like Hide Download option in Share Link

### ISSUE THREAD

**Issue by maliknet** [nextcloud/polls#607]
![image](https://user-images.githubusercontent.com/35651642/61020253-43a1b000-a3c7-11e9-96b8-68b1ad251433.png)
Hide Download option is already in Share link options in Nextcloud. But the option isn't available if you share with another user / group. The idea is to create a download permission like a hide download option in share link.

I think this feature very needed in real world case especially for strict permission.

**Comment by dartcafe** [comment]
Sure, you're in the right repo?

**Comment by maliknet** [comment]
I'm Sorry it's wrong. I will Close this issue and re-post in the right repo.
Thanks for your comment @dartcafe
