### ISSUE TITLE
Create new poll, add option, no button

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/polls#614]
I create a new poll, klick "Textbased" and enter a text.. and now? I miss a "Add"-Button or something. OK, if i press ENTER on the keyboard the option is added, but thats not intuitive.

![image](https://user-images.githubusercontent.com/1249295/61851687-f427ad80-aeb7-11e9-98f5-a22bbd34683a.png)

Poll Version is 0.10.2, Nextcloud 15.

**Comment by dartcafe** [comment]
I would say it is intuative, but maybe, we spend an button for this.
