### ISSUE TITLE
Anonymous polls - delete poll

### ISSUE THREAD

**Issue by Mathias-Ro** [nextcloud/polls#615]
Anonymous polls can't be edited or deleted.
It would be nice to find a way for edit or delete them.
Maybe set a password for my poll or, 
same IP can edit it or
the owner of the poll can do it.

Regards,
Mathias

**Comment by dartcafe** [comment]
shares like file shares are coming after or with version 1.0

**Comment by dartcafe** [comment]
And admin access for editing votes, too.
