### ISSUE TITLE
Result of the Vote printable or export as image

### ISSUE THREAD

**Issue by ghosttable** [nextcloud/polls#618]
Hi,
we would need to print the vote result for documentation.

Would this be possible to get a option to print as pdf, or maybe to export as image?
Of course we could take a screenshot but this is a dirty workarround.

but else its a nice app, keep up the good work

greetz and regards

**Comment by ghosttable** [comment]
Any Chance this will get into Polls?

**Comment by dartcafe** [comment]
Yea. Sometimes. 😀 I amk missing time for progress on version 1.0. Export will come with something like in # 366
