### ISSUE TITLE
To dos for Version 1.0

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#619]
- [x] Security Checks in backend
- [x] Bring back responsibility
- [x] Fix design glitches
- [x] Bring back public poll
- [x] Add share system (personal invitations)
- [x] public polls are changeable via personal or invitation link
- [x] move notification to cron job
- [x] write tests (Travis will not be happy now)
- [x] create poll inline

What is changed so far:
- Migrated app completely to vue
- Refactoring of backend
- Instant saving votes
- inline editing of the poll (creating is still a separate page)
- separation of the store and controllers
- I don't remember, what else

A great start for new features.
If you want to try the current dev status, see https://github.com/nextcloud/polls/tree/dev-1.0

**Comment by dartcafe** [comment]
A little preview: https://nc.yagst.de/index.php/s/QwqYkw8yZrpLCGc

**Comment by ghosttable** [comment]
Hi i just asked this in a Post a few days ago, 
we would need to print the vote result for documentation.

Would this be possible to get a option to print as pdf, or maybe to export as image?
Of course we could take a screenshot but this is a dirty workarround. 

but else its a nice app, keep up the good work 

greetz and regards
