### ISSUE TITLE
possibility to order the poll list like in file explorers

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#627]
Hi,

it would be nice that a click on the title, date, etc would order the list like in any file explorer.

Sash

**Comment by martinhilde** [comment]
it would be extremely helpful to have at least a workaround how to sort the polls since we use the tool for our volunteers to sign in for services - therefor they gotta be in a chronological order.
thank you very much

**Comment by dartcafe** [comment]
The next version needs some more development. Sorry not possible before that.

**Comment by martinhilde** [comment]
I see, thanx for reply.
At the moment it's actually the case that the most recently administrated poll appears at the bottom of the list - but not always, unfortunately. If it would work reliably, it would would be almost perfect for me.

**Comment by dartcafe** [comment]
Duplicate #529

**Comment by dartcafe** [comment]
Sorry, no duplicate but part of 1.2
