### ISSUE TITLE
ownCloud 10.2.1 compatibility

### ISSUE THREAD

**Issue by galandilias** [nextcloud/polls#630]
**Which Polls version are you running?** (see apps page) None :) as latest is not compliant :)

**Nextcloud or ownCloud?:** ownCloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page) 10.2.1

### Actual behaviour
Not possible to install plugin in 10.2.1 ownCloud

### Expected behaviour
Well :) it should be possible to install and use :)

**Comment by dartcafe** [comment]
Sorry, but ownCloud is no more supported. See https://github.com/nextcloud/polls/wiki

If you like, you can fork the 0.8 stable branch. https://github.com/nextcloud/polls/tree/stable-0.8
