### ISSUE TITLE
Release 0.10.4

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#632]
@v1r0x: The master branch is up to date. Could you bake the new release and publich it to the store?

**Comment by dartcafe** [comment]
Ahem. Wait. Didn't merge the nc-17 branch.

**Comment by dartcafe** [comment]
@v1r0x Could you test and release?

**Comment by ximex** [comment]
any updates here?

**Comment by v1r0x** [comment]
Yes, the new release should be available this week! Sorry for the delay!

**Comment by v1r0x** [comment]
It looks like my new ryzen can't handle 64bit virtualbox images... :man_facepalming: 
Hopefully there is a fix for this :crossed_fingers:

**Comment by dartcafe** [comment]
Can I help? 
BTW: You can enable the "untested" app on NC 17 without issues.

**Comment by HFranz** [comment]
any updates here?

**Comment by gruentee** [comment]
> Can I help?
> BTW: You can enable the "untested" app on NC 17 without issues.

I unpacked the downloaded archive from the releases page but get #531 (CSP error) with NC 17.

**Comment by herrmannsdorfer** [comment]
@v1r0x Did you follow this thread, settings and workarounds on the [VirtualBox forum](https://forums.virtualbox.org/viewtopic.php?f=1&t=82323)? 

Hopefully the link helps - a NC 17 compatible version of polls is overdue ...

**Comment by v1r0x** [comment]
@herrmannsdorfer Thanks for the link! Activating CPU virtualization (SVM) in the BIOS fixed the problem.

The new release is now available on the appstore! Finally! Sorry for the looong delay.
