### ISSUE TITLE
Sorting goes wrong

### ISSUE THREAD

**Issue by thechonta** [nextcloud/polls#638]
The Sorting is some kind wrong.

In the code is an Order BY for sort by creation Date, so the oldest Poll should be always the first, but it doesn't.

With postgresql the last edited poll goes to the button. In somekind the last edited goes to the middle.
Possably the sorting is messed up if the polls database is changed by different people.

A fix that the order would be always by name would be awesome, so the user can adjust the order simply by name.

Featurerequest: Allow to create Polls only for specific groups. If i block asses in the nextcloud itself they don't see the polls at all.

Kind regards 

Chonta

**Comment by dartcafe** [comment]
There is no real sorting. The polls are sorted in the order they are received from the controller. Sorting and grouping will be a feature of the 1.0 version.

**Comment by dartcafe** [comment]
See # 635
