### ISSUE TITLE
Error messages "Undefined index: [...]" when opening polls app 

### ISSUE THREAD

**Issue by AJHoeh** [nextcloud/polls#639]
I hope this is the right place for posting this. Basically I recieve error messages when opening polls app. Everything seems to be working but I guess if those are thrown something goes wrong... I am not 100% about this, but I think this behaviour started after updating to nextcloud 16.04

### What is going wrong?
When the polls app is opened, following error messages are thrown:

`Error | PHP | Undefined index: id at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#392
Error | PHP | Undefined index: id at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#388
Error | PHP | Undefined index: id at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#387 
Error | PHP | Undefined index: access at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#181
Error | PHP | Undefined index: access at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#179 
Error | PHP | Undefined index: access at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#177
Error | PHP | Undefined index: owner at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#175
Error | PHP | Undefined index: id at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#382 
Error | PHP | Undefined index: owner at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#375
Error | PHP | Undefined index: id at /var/www/html/nextcloud/apps/polls/lib/Controller/ApiController.php#373 `

**To Reproduce**
1. Open polls app
2. Recieve error messages

**Expected behavior** No error messages

### Information about your polls installation
**Polls version?**  

**How did you install this version?** Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?** Nextcloud

**Nextcloud/ownCloud version:** 16,04

**List of activated apps:**

Enabled:
 - accessibility: 1.2.0
 - admin_audit: 1.6.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - group_everyone: 0.1.3
 - groupfolders: 4.1.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - activity
 - announcementcenter
 - apporder
 - contacts
 - dropit
 - encryption
 - files_external
 - firstrunwizard
 - gallery
 - mail
 - nextcloud_announcements
 - survey_client
 - systemtags
 - twofactor_totp
 - user_ldap

**Nextcloud configuration:**

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED***"
        "***REMOVED***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/REMOVED\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "logfile": "\/var\/log\/nextcloud.log",
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 104857600,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "overwriteprotocol": "https",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "theme": "",
    "trashbin_retention_obligation": "auto, 7",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_template_class": "OCA\\Mail\\EmailTemplate"
}

### Server configuration

**Operating system**: Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Signing status:** No errors have been found.

**Are you using an external user-backend, if yes which one:** no

**Comment by dartcafe** [comment]
I have no idea, but I had this also with corrupt database table entries. Maybe you can remove the poll_ tables and the migration entries related to poll and reinstall the app.

**Comment by AJHoeh** [comment]
I also have no idea what the problem was but the new polls update fixed it, thank you!
