### ISSUE TITLE
Extending poll: users can't edit the new entries

### ISSUE THREAD

**Issue by Kugeleis** [nextcloud/polls#640]
### What is going wrong?
After I extended a poll the existing members can't edit the new dates.
It is a public poll. The members/useres have no account in this nextcloud.

**To Reproduce**
1. Create a public poll
2. Have people fill the poll (not useres of this nextcloud)
3. Add more dates to the poll.
4. A non-member can't fill the new dates in the existing lines.

**Expected behavior**
The new entries should be open to be filled.

### Information about your polls installation
**Polls version?** 0.10.2

**Fresh installation or update from a prior version (from which one)?**
updated

**How did you install this version?(Appstore or describe installation)**
app store

### Information about your Instance of Nextcloud/ownCloud
Nextcloud 16.0.4

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
This is a duplicate and on the to do list...
