### ISSUE TITLE
Description not representative

### ISSUE THREAD

**Issue by tgrignon** [nextcloud/polls#641]
When adding spaces in description it's not keeped to display. The reason is : in the database, table poll_events, key description is VARCHAR when it supposed to be TEXT.

Other reason : vote.tmpl.php line 143
`<?php print_unescaped($description); ?>`

Should be
`<?php print_unescaped(nl2br($description)); ?>`

**Comment by dartcafe** [comment]
I don't get you. What spaces? My spaces are kept.... ?!

**Comment by simmstein** [comment]
The description could be multi-lines with breaks (<br>). I think that we should use markdown.

**Comment by dartcafe** [comment]
> 
> The description could be multi-lines with breaks (`<br>`). I think that we should use markdown.

#325
