### ISSUE TITLE
NC17 compatibility

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#643]
Polls 0.10.2 does not seem NC 17 ready. The NC updater is missing an update. I am running NC 16.0.5:

![Bildschirmfoto 2019-09-30 um 10 44 18](https://user-images.githubusercontent.com/43957716/65864324-f9025500-e371-11e9-9e96-731acb9b0da9.png)

BTW: Current Release 0.10.3 is not offered as an update. But this version is not NC 17 ready either?

**Comment by dartcafe** [comment]
The master is up to date for NC17. Appstore release is just missing. 
@v1r0x

**Comment by dartcafe** [comment]
@ChristophWurst Can you help me? I could not get contact to @v1r0x, seems he is not available at the moment. The problem is, that I have no access to the appstore to maintain the releases there. 
Do you have any idea, how to get access to the repo or someone who can help?

**Comment by v1r0x** [comment]
Sorry, I had a lot to do at work...I'll try to release it to the appstore tonight :crossed_fingers: Sorry again!

**Comment by dartcafe** [comment]
Don't worry. I know this. Maybe we should get a way, that we both can maintain the app store updates.

**Comment by dartcafe** [comment]
See Updates in #632
