### ISSUE TITLE
Limit votes

### ISSUE THREAD

**Issue by delumerlino** [nextcloud/polls#647]
**Which Polls version are you running?** (see apps page)
0.10.2
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.4
### Steps to reproduce
1. Create new poll
2. Add vote options
3. Publish!

Good morning,
I would like to limit to X votes the options, so once an option reach positive votes expressed in X it is lo longer choosable.

Thanks

**Comment by dartcafe** [comment]
#738, #739
