### ISSUE TITLE
Create series of options

### ISSUE THREAD

**Issue by ibayer** [nextcloud/polls#649]
Thanks for this nice app!

**Is your feature request related to a problem? Please describe.**

I couldn't find an easy way to create many time slot options at once. Creating each option
individually is too time consuming in some instances.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

I need to find a 30 minutes slot for 10 people sometime between 22.10 - 25.10. Only slots
between 2pm - 5pm are possible.

**Describe the solution you'd like**

After selecting a date I would like to be able to select multiple times 2pm 3pm etc that are added as separate options to the poll. Being able to repeat this for other days easily (like the shift option, but copy to other day instead) would be even better.

**Describe alternatives you've considered**
---

**Additional context**

 Selecting multiple times #326

**Comment by kangaroo72** [comment]
I totally agree ... actually I'm using https://date.escher.cc based on FRAMADATE.
For me it's important. In my case, I often try to find only one appointment for 6-8 People. Sometimes it matches only once or twice in six months. I do not use polls, if I have to click 180 days manually ;-)

**Comment by dartcafe** [comment]
see first throw in #855
