### ISSUE TITLE
Hidden polls are not hidden (repetition of bugs 511/101 ?)

### ISSUE THREAD

**Issue by hj-beckers** [nextcloud/polls#651]
### What is going wrong?
All users can access hidden polls.

versions:
OpenSUSE 15.1
nextcloud 17.0.0.7 (continuously updated)
php 7.2.5
Mariadb 10.2.22
polls 0.10.4

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.

**Comment by dartcafe** [comment]
Should be working now with implementation of the acl.
