### ISSUE TITLE
Name auto completion gives away registered NC user names in public polls

### ISSUE THREAD

**Issue by dajusc** [nextcloud/polls#657]
### What is going wrong?
**Describe the bug**
In a public poll, the auto completion for the name field possibly gives away full names of registered nextcloud users.

**To Reproduce**
1. Create a nextcloud user "John" with full name "John SecretLastName" 
2. Create a public poll and copy its link to the clipboard
3. Use a different browser or log out of nextcloud and open the public poll
4. Type "John" into the name field and confirm the vote
5. The intermediate poll results are displayed, showing a new entry by "John SecretLastName"

**Expected behavior**
No auto completion should be applied for the name field, or there should only be "live" auto completion if the polls participant is currently logged into the nextcloud instance corresponding to the public poll.

**Screenshots**
n.a.

### Information about your polls installation
**Polls version?** (see apps page)
0.10.4

**Fresh installation or update from a prior version (from which one)?**
fresh

**How did you install this version?(Appstore or describe installation)**
Using my nextclouds builtin app management

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
16.0.6

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
see above

**more information on request, if necessary**

**Comment by dartcafe** [comment]
Duplicate #223
