### ISSUE TITLE
Manage poll via API call

### ISSUE THREAD

**Issue by Schmalztopf** [nextcloud/polls#660]
The idea is to have the possibility to manage polls via an API. 

Our use case is to create recurring polls according to a schedule. As we did not find any option set this up, our idea was, that it might be easy to manage this via API calls regularly. This might be creating one according to a template or just reuse an existing poll.

If there is any option to do this with the current version, a hint how to do this might be helpfull

**Comment by dartcafe** [comment]
At the monent you can do this manually. Clone a poll and shift all dates. In Version 1.0 I prepared external Endpoints for public polls. 
Managing polls via an API is currently not on the roadmap. But I think, this will be not a big thing, since back- and frontend are now separated.

**Comment by JulienSambre** [comment]
Hi!
I have a different use case (want to make my AI create an event : poll + mail people) and would love to see this API option added ;).

**Comment by dartcafe** [comment]
closing this, in favor of #879
