### ISSUE TITLE
Feature Request for android app: Ability to specify a default external app when opening video files (mp4)

### ISSUE THREAD

**Issue by Dho100** [nextcloud/polls#665]
On my Android 9 and 10 device, streaming mp4 videos is slow and choppy. I don't have issues streaming the videos when I use the "Stream with..." function to stream the video using the Photos app (Google Photos), and would prefer just to have the videos open in Photos instead of the Nextcloud app by default for all mp4 file extensions.

Request is to enable users to define default external apps to open files with by default.

Thank you!

**Comment by dartcafe** [comment]
Please post your request in the correct repo.
