### ISSUE TITLE
Limit number of participants for a poll

### ISSUE THREAD

**Issue by natrius** [nextcloud/polls#671]
**Describe the solution you'd like**

Set maximum participants. Exampe 6. When 6 "yes" are reached ("maybe" not included) voting is not possible anymore. Or just not counted, not sure what would be better - when not counted someone could be marked as drop-out and the next in row would count again. 
Not completely sure on how to work with that the best way, if interested i will try to work something better out.

**Comment by dartcafe** [comment]
Limitation is now possible per option #739 and per participant #738. 
Generally limitation to yes votes per poll is not planned.
