### ISSUE TITLE
Share by circles ? 

### ISSUE THREAD

**Issue by livier** [nextcloud/polls#674]
The most important way of orginising our nextcloud's users are the circles. 
I foud that "polls" does not offer sharing with "circles" 
So, I ca't offer this for the users to share with circles, and can't use Polls for the moment. 

As we say, Paris was not build on one day, Hold on ;-)

**Comment by dartcafe** [comment]
It is still on the feature list #204 
- [ ] First have to finish 1.0 and sharing. 
- [ ] After that learning of the circles API.
