### ISSUE TITLE
Create new poll: pre-select last choosen date as pre-selsected

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#684]
**Is your feature request related to a problem? Please describe.**
The fist time you hit "Add a date option" the current date is pre-selected, which is ok. When you hit "Add a date option " the second time the current date is pre-selected again, but i always would like to have a the last selected date as start, cause typical range of your selection will start in that area (e.g. some time 3 months in the future)

**Describe the solution you'd like**
Plz use the last used date as pre-selected starting point in "Add a date option"

**Comment by dartcafe** [comment]
That is a bug and solved for Version 1.0.
