### ISSUE TITLE
Support all emoji

### ISSUE THREAD

**Issue by ahstro** [nextcloud/polls#692]
### What is going wrong?
Some emoji are replaced by question marks, e.g. "????"

**To Reproduce**
1. Create poll with emoji in title or description
2. View poll
3. See error

**Expected behavior**
The emoji used should be displayed.

**Screenshots**
Creating:
![borked-emoji-1](https://user-images.githubusercontent.com/3090888/71385210-4ba48380-25e6-11ea-9da0-76e13ce1bc58.png)
Viewing:
![borked-emoji-2](https://user-images.githubusercontent.com/3090888/71385211-4ba48380-25e6-11ea-8a82-a525d24a1dc3.png)

### Information about your polls installation
**Polls version?** (see apps page)
0.10.4

**Fresh installation or update from a prior version (from which one)?**
Fresh

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
15.0.12

**Comment by dartcafe** [comment]
I cannot confirm problems with emoijs. Please check, if your DB setup supports UTF8 with multibyte support. Maybe an update to a newer NC version is a good idea (i.e. NC 17).

**Comment by ahstro** [comment]
@dartcafe Thanks for the tip. Any idea how to do that? 😇

**Comment by dartcafe** [comment]
What? An update or change of the db setup? There is a doc about that. https://docs.nextcloud.com/server/17/admin_manual/configuration_database/mysql_4byte_support.html
