### ISSUE TITLE
Testers wanted: Beta3 of polls 1.0 is out

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#706]
polls is now a complete vue app with PHP backend. The UI got a huge overwork too and will be a good start for further improvements and newe cool features. 

please help testing and report bugs as a new issue with a [1.0 beta] tag, so we will be able to get the final release out together with the new NC version 18. 

Thanks in advance for your support.
Download the latest beta version here: https://github.com/nextcloud/polls/releases

❗️  ~~After Update refresh your browser cache to force load of the current installed version.~~
❗️ cache clearing shouldn't be neccesary any more ✔️

**Comment by guzzisti** [comment]
I've installed the beta on my testing instance.

My feedback so:
- You can not start editing a poll from the list view, you need to open a poll and find the small gear wheel icon in the upper right corner. I'd like to have the "edit" button more obvious and on the list view as well.
- In a schedule poll time selection is broken. No matter what time you are selecting in the dropdown, the poll option adopts the current time.

**Comment by dartcafe** [comment]
>     * You can not start editing a poll from the list view, you need to open a poll and find the small gear wheel icon in the upper right corner. I'd like to have the "edit" button more obvious and on the list view as well.
I think, changing the sidebar default to open would be the best solution. So we need no edit button. Will change this.
> 
>     * In a schedule poll date/time selection is broken. No matter what date/time you are selecting in the dropdown, the poll option adopts the current date & time.
Erks. Damn. I will check and fix this.
> 
>     * Public poll with a link only shows a blank page with the nextcloud header and footer although some poll options have been set. There are some js errors in the browser console:
I don't get these warnings and errors and don't know where they come from. But I fixed the public vote. Did some changes to the backend and forgot the pubic vote. 

> Besides that, it looks good for a first beta. 👍
Thanks for your time and support.
Beta2 will come shortly.

**Comment by dartcafe** [comment]
beta2 is published.

**Comment by guzzisti** [comment]
I can confirm that the two bugs mentioned earlier are fixed, despite a few german translations missing. I tried the Transifex-link on https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md but this shows me a 404. What do i need to do to request access to the transifex project to contribute some translations?

From my point of view the top section of the vote page looks a bit messy. The heading is  inconspicuous, the expire message to prominent and the "switch view" button seems to float around with no relation to anything. Though I don't have a good idea especially the latter could be improved.
![image](https://user-images.githubusercontent.com/10488791/71783136-a2488f00-2fe2-11ea-875d-e0301a30539d.png)

On the vote page, the poll icon and the poll title are misaligned:
![image](https://user-images.githubusercontent.com/10488791/71783229-0a4ba500-2fe4-11ea-9407-3d331e70e275.png)

**Comment by dartcafe** [comment]
Tranlations are normally done in a few days after merging in to the master branch. 

The source for polls is https://www.transifex.com/nextcloud/nextcloud/polls/, but you have to have an account and be added to the nextcloud organisation as a translater. Create an account and then you can apply for access. 

The switch view is a quick solution to be ableto test the introduced vote view and not final. I need feedback, what users think about the other type of view.

The heading is a h2, which is bigger than h1. I don't know why. I think, I will erase the colored hints for ongoing polls. 

The misalignment of the icons is because, the poll description is missing. There are two lines. But design is a ever lasting issue.

**Comment by xf-** [comment]
- I created a new poll a result from currently open poll was visible.
- "No comments yet. Be the first." -> i Can't write comments on a closed poll
- <details><summary>Error while creating second text poll</summary><code> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An  exception occurred while executing 'INSERT INTO "oc_polls_polls"  ("type", "owner", "created", "title", "description", "access", "expire",  "anonymous", "full_anonymous", "allow_maybe", "vote_limit", "settings",  "options", "show_results", "deleted", "admin_access") VALUES(?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["datePoll",  "blubb", 1578657952, "test", "", "hidden", 0, 0, 0, 0, 0, "", "",  "always", 0, 0]:  SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value  violates unique constraint "prefix_polls_polls_pkey" DETAIL:  Key (id)=(4) already exists.</code>
</details>

**Comment by RiSK1979** [comment]
Testing Beta 3 when settings up a poll (no matter which type) I automatically get this meaningless comment, highlighted by me in yellow on the poll:
![Unbenannt-1](https://user-images.githubusercontent.com/4215448/72169553-a18f6e80-33cf-11ea-8d34-57d32f0e30f1.jpg)

**Comment by leolivier** [comment]
Hi @dartcafe 
This application sounds very interesting as I'm looking for a replacement of Doodle, but...

I had previously installed 0.10.4 version and created a test poll.
Then I deactivated this version, downloaded the 1.0b3 zip from github, unzipped it in the apps directory after having moved the old one.
Now, when activating the 1.0b3 version, I get the following error:
`An exception occurred while executing 'INSERT INTO `oc_polls_polls` (`id`, `type`, `title`, `description`, `owner`, `created`, `expire`, `deleted`, `access`, `anonymous`, `full_anonymous`, `allow_maybe`, `options`, `settings`, `vote_limit`, `show_results`, `admin_access`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "textPoll", "test poll", "test poll em", "olivier", 1578679562, 0, 0, "hidden", 0, "0", "1", "[\"yes\",\"no\",\"maybe\"]", "", 0, "always", 0]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'`

Looks like it didn't clear the old test before deactivating and it tries now to recreate the same poll...
I can indeed try to remove the line in the mysql table but might be a bug on your side...

**Comment by leolivier** [comment]
> Tranlations are normally done in a few days after merging in to the master branch.
> 
> The source for polls is https://www.transifex.com/nextcloud/nextcloud/polls/, but you have to have an account and be added to the nextcloud organisation as a translater. Create an account and then you can apply for access.

I changed a translation in transifex for 'public polls" which translates in French to 'Sondages publics' and not 'Sondages publiques'

Also I have a problem when I try to add some recipient:
```
[PHP] Error: Undefined index: ORG at /var/www/nextcloud/apps/polls/lib/Controller/SystemController.php#168 POST /index.php/apps/polls/siteusers/get/
from 192.168.0.254 by olivier at 2020-01-10T19:05:18+00:00

[PHP] Error: Undefined index: PHOTO at /var/www/nextcloud/apps/polls/lib/Controller/SystemController.php#174 POST /index.php/apps/polls/siteusers/get/
from 192.168.0.254 by olivier at 2020-01-10T19:05:18+00:00

[PHP] Error: Undefined index: userEmail at /var/www/nextcloud/apps/polls/lib/Controller/ShareController.php#156 POST /index.php/apps/polls/share/write/
from 192.168.0.254 by olivier at 2020-01-10T19:30:07+00:00
```
And I have the same kind of error when I try to create a public link...
and I can't share the poll with anybody...

**Comment by dartcafe** [comment]
> Testing Beta 3 when settings up a poll (no matter which type) I automatically get this meaningless comment, highlighted by me in yellow on the poll:

I discovered this translation a few days ago too and corrected this already. Strings in the master branch are up to date.

**Comment by dartcafe** [comment]
> Also I have a problem when I try to add some recipient:

@leolivier Seems that some error handling is missing (user from contacts seems to have not the neccesary fileds. I will check this this weekend. 

We had some bugs in the migration of the versions before beta3. Unfortunately removement/deactivating of an app does not clear the database. Do wipe the tables you have to do the this you did: 
* deactivate/delet the app
* remove all tables of the poll
* remove all migration entries from that poll. 

After that the migration system executes the db functions. If you skip one of the steps above, you will have a problem.

**Comment by dartcafe** [comment]
@xf- Seems you have to clean up the DB first. See comment above for repair steps.

**Comment by dartcafe** [comment]
@leolivier Thanks for testing. If you find a bug or suggest an enhancement, the better way is to open a separate issue.
