### ISSUE TITLE
Alternative vote page

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#707]
I am thinking about an alternative display for the vote page. Especially text polls are not really beautiful, when displayed with the table layout. And I think the table layout has much information, which is not worthy for the current participant. 

I made a quick try for an alternative display and vote page. Tell me what you think.
![grafik](https://user-images.githubusercontent.com/26707476/71754443-70bab100-2e86-11ea-895e-aa9fa46f0b66.png)

**Comment by herrmannsdorfer** [comment]
I like the alternative display because it gives a condensed view on the votes. Especially helpful when the poll has many options.

For analysis you might want to sort the options by preference (most green on top).
