### ISSUE TITLE
date of expiry

### ISSUE THREAD

**Issue by ThomasKujawa** [nextcloud/polls#711]
### What is going wrong?

I wanted to delete the expiration date. Even if I save it, the date will be retained. Only setting a later date brought a solution.

**To Reproduce**
1. Go to Umfrage bearbeiten
2. Click on Konfiguration freischalten
3. Haken bei Ablaufdatum setzen entfernen
4. Das Auswahlfeld Datum verschwindet
5. Umfrage aktualisieren
6. Anzeige: Umfrage speichert
7. Click on 'Polls' - alle Umfragen anzeigen
Error: Datum wieder vorhanden

```
<?php
$CONFIG = array (
  'instanceid' => 'ocpbnht19px2',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'familienfreun.de',
    1 => 'www.familienfreun.de',
    2 => 'familienfreun.de.w0174798.kasserver.com',
  ),
  'datadirectory' => '/www/htdocs/w0174798/cloud/data',
  'overwrite.cli.url' => 'https://familienfreun.de',
  'dbtype' => 'mysql',
  'version' => '17.0.1.1',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'familienfreund.de',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'w0174798.kasserver.com',
  'mail_smtpport' => '',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'maintenance' => false,
  'default_language' => 'de',
  'tempdirectory' => '/www/htdocs/w0174798/cloud/tmp',
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'app_install_overwrite' => 
  array (
    0 => 'calendar',
  ),
);
```

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- tmp/url84f9112701208084a5c3cd83bebc52a9
		- tmp/url4ed948e587cf8303b6d80e7039e04b86
		- tmp/url0a5b31316eb5738aacfebcbcc534077f
		- tmp/url7aece663f3690ab465be498ae8e258e1
		- tmp/url14f48a3c8dcc719f4d9f081169eb1ffe
		- tmp/url746982a4d465921e4b0edcc7bd1ab852
		- tmp/urlb03a20b93eb0735cc78423c2bfccdb63
		- cronjob.php
- text
	- EXTRA_FILE
		- package-lock.json
		- README.md
		- .l10nignore
		- package.json
		- l10n/.gitkeep
		- .gitattributes
		- .github/pull_request_template.md
		- .github/ISSUE_TEMPLATE/Feature_request.md
		- .github/ISSUE_TEMPLATE/Bug_report.md
		- .tx/config
		- .eslintrc.js

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [tmp/url84f9112701208084a5c3cd83bebc52a9] => Array
                        (
                            [expected] => 
                            [current] => fa4bea79841e3cabda5b6f9c6144a64d0190d13f76a4627aa1f8f5ef4cb975b04b2b6165b719ecc520bf2126b593e8f0eb1490802648453753e10ece9318af59
                        )

                    [tmp/url4ed948e587cf8303b6d80e7039e04b86] => Array
                        (
                            [expected] => 
                            [current] => 7041243357d6c450290d11ad4066ff2f009d4499d65d15060d0b19ff7de52a7ff9ac84b76711a759411e43bcdb8898776b39bb5a789389d360603cae53a8e0e5
                        )

                    [tmp/url0a5b31316eb5738aacfebcbcc534077f] => Array
                        (
                            [expected] => 
                            [current] => e96b4a0e21f1393ea7c352752d19eed1e257747278107efc16eca28888ef57e1c150a882735095782af811a5588980c1bb43dd282f82e220565441ef9181dc1d
                        )

                    [tmp/url7aece663f3690ab465be498ae8e258e1] => Array
                        (
                            [expected] => 
                            [current] => 9d60cc1c392779c388406f04931f785edd5f0ed52244bc6a87585e64ee25e05fbf0a62d501b637cb6a94115bf2a87489ab1be5e6ebc24194d7f9f7edec1f95bb
                        )

                    [tmp/url14f48a3c8dcc719f4d9f081169eb1ffe] => Array
                        (
                            [expected] => 
                            [current] => 867bace1715b84a6ff1cad91e8d51c48d16a5502c402c499625b4a44967f0c1c7945edc9405dbe203f2760513ff9338a2766a2dad89ded9834bc84718b58ce08
                        )

                    [tmp/url746982a4d465921e4b0edcc7bd1ab852] => Array
                        (
                            [expected] => 
                            [current] => 8719fe595ec56914d307fd6e9760fa89fdacaf5e5db30fac8dcb1ff97ac8826d73f8f70d3bda704922001730d1482f10f63a2a6ba64987c79ccabe3f3d4762de
                        )

                    [tmp/urlb03a20b93eb0735cc78423c2bfccdb63] => Array
                        (
                            [expected] => 
                            [current] => ad357b9bb49a0a7fe9aa3704a166f66ace552ab97546249cafa28336ea6dcb6c49d62284d8afb603f83bc08fa5e2d3da9c5549de9f98eab7d353e59eda6b3aa8
                        )

                    [cronjob.php] => Array
                        (
                            [expected] => 
                            [current] => 81ad1d2cbaba81a29e5ec8e1464c0e9ac9017ebc144a191c766ea8b83d246e1ac137b5cfc49b74e2e79b48eef9360b4fc8b565887883460618d566fda1765346
                        )

                )

        )

    [text] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [package-lock.json] => Array
                        (
                            [expected] => 
                            [current] => 851dfbb766522728bdb6b468b02e4f3bd8a5f481c1ce89c7d151764b8ec0c35344032d771b8bb94b3e99f6e625c580c41eb3e480166d165731039f6de2e002c4
                        )

                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => ec0ad73e49149bc6200d8b07cc14a6795936d6c150ad20d30c9d694ea6ebe4b4738f81fc50d1f84d68d0c62e045f1b854ab56a1264b9310aadb2aa54a7573194
                        )

                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 3a07b78d317a75ec5a027b869771b5464be4749f645e8e9e1999864c710ce5b115279bd159758addcf0bcd182e28da35da0156c5ff43af69bb869e5225818f98
                        )

                    [package.json] => Array
                        (
                            [expected] => 
                            [current] => fec4073b810d23b3b314e58c1ba6c40f12f429fb623998685d65f93e5afc45f7ddc91d8467e905b00536c091ed3f5395b054f01df8d2f0dd6d213442d1241b11
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                    [.gitattributes] => Array
                        (
                            [expected] => 
                            [current] => da176baa1edf0a8408ffa35e07849a980e68fe0dd5f53569e583aec2e362f61d47e1ff6968d2fd92787b59ee2f8f38cbe8dcdde7e3ef1e24081cd21dc61e1d30
                        )

                    [.github/pull_request_template.md] => Array
                        (
                            [expected] => 
                            [current] => 9307a7ab3b06266ccda57e66ae678b31db3faf26a51c508d60b9bc2874ed59d46bcd1c1d07970e2af0947f826f050f953cbf02a962a4b40cb1572f5fcd8f94a1
                        )

                    [.github/ISSUE_TEMPLATE/Feature_request.md] => Array
                        (
                            [expected] => 
                            [current] => 84541137d4035e61148e33f0560e8f96c2dffde247b672459cf45f32c57bcfb6a4479dcf9c45b6598e95f61369bfad2d16c7784d59a689ad46c7b332216f891b
                        )

                    [.github/ISSUE_TEMPLATE/Bug_report.md] => Array
                        (
                            [expected] => 
                            [current] => 2a574514bba022a69c723616091bfd19eb5b4821aef95846eb942e90ee80cf2b2b8710091660fc99b43eb922b47d96f89b4e38c72d14909d76a9c88edbe7a28b
                        )

                    [.tx/config] => Array
                        (
                            [expected] => 
                            [current] => 80dfc72f84d02213d63b236925f020fc21f17fc5d1964cd84c0530fb65f3738cd03ff923f50ba8396d5832f5a04276891733281ecba82321cb426f13aa968516
                        )

                    [.eslintrc.js] => Array
                        (
                            [expected] => 
                            [current] => 74262fe75f2c990b21f1116e86083b5ec635a084a3c3cba8ef7cf62f6ea398ed5f1b94c770a230993273a7bd2ff1587106b778814331e4bf6c0e20b82340bc94
                        )

                )

        )

)```



```

{"reqId":"XhMVfzXiIOpbh6HjXKe@fgAAAAE","level":3,"time":"2020-01-06T11:09:52+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"POST","url":"\/index.php\/apps\/polls\/write\/poll","message":"Illegal string offset 'type' at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#433","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVfzXiIOpbh6HjXKe@fgAAAAE","level":3,"time":"2020-01-06T11:09:52+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"POST","url":"\/index.php\/apps\/polls\/write\/poll","message":"Illegal string offset 'type' at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#435","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMViKr04P@wKkPfEc5vkAAAAB0","level":3,"time":"2020-01-06T11:10:00+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVjKr04P@wKkPfEc5vmAAAAC0","level":3,"time":"2020-01-06T11:10:04+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVkKr04P@wKkPfEc5vnwAAADs","level":3,"time":"2020-01-06T11:10:08+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVniYTrJX6455RrsB3MwAAAAc","level":3,"time":"2020-01-06T11:10:22+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVniYTrJX6455RrsB3MwAAAAc","level":3,"time":"2020-01-06T11:10:22+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVvUxMYd9X1PDbutPHxgAAABM","level":3,"time":"2020-01-06T11:10:53+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMVvUxMYd9X1PDbutPHxgAAABM","level":3,"time":"2020-01-06T11:10:53+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMV5Ak9Irne9wqZ82vT9gAAAHM","level":3,"time":"2020-01-06T11:11:32+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMWCNBCqC-hqH6tK@e7xgAAAAc","level":3,"time":"2020-01-06T11:12:08+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMWCNBCqC-hqH6tK@e7xgAAAAc","level":3,"time":"2020-01-06T11:12:08+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"mxE7C2KiTn1i5YXe8xn0","level":2,"time":"2020-01-06T11:15:15+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/www.fachkraefteallianz-suedwest.de\/feed\/ read error : cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)","userAgent":"--","version":"17.0.1.1"}
{"reqId":"mxE7C2KiTn1i5YXe8xn0","level":2,"time":"2020-01-06T11:16:10+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/instaffo.com\/feed\/ read error : Client error: `GET https:\/\/instaffo.com\/feed\/` resulted in a `404 Not Found` response:\n<!doctype html>\n<html lang=\"de\">\n  <head>\n    <meta charset=\"utf-8\" \/>\n    <meta\n      name=\"viewport\"\n      content=\"wi (truncated...)\n","userAgent":"--","version":"17.0.1.1"}
{"reqId":"mxE7C2KiTn1i5YXe8xn0","level":3,"time":"2020-01-06T11:16:10+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"mxE7C2KiTn1i5YXe8xn0","level":2,"time":"2020-01-06T11:16:10+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"http:\/\/www.bvmw-leipzig-expertenteam-recht.de\/feed\/ read error : No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"mxE7C2KiTn1i5YXe8xn0","level":2,"time":"2020-01-06T11:16:15+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/bessermittag.de\/feed\/ read error : Client error: `GET https:\/\/bessermittag.de\/feed\/` resulted in a `404 Not Found` response:\n<!doctype html><!--[if lt IE 7]> <h (truncated...)\n","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":3,"time":"2020-01-06T11:32:07+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:07+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/mephisto976.de\/nachrichten\/rss read error : No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:08+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/www.leipzig.de\/?type=100&tx_ttnews%5Bcat%5D=126&tx_ttnews%5BsinglePid%5D=573 read error : Server error: `GET https:\/\/www.leipzig.de\/?type=100&tx_ttnews%5Bcat%5D=126&tx_ttnews%5BsinglePid%5D=573` resulted in a `503 Service Temporarily Unavailable` response:\n<!DOCTYPE html>\n<html lang=\"de-DE\">\n    <head>\n        <meta charset=\"utf-8\">\n        <meta name=\"keywords\" content=\"\">\n (truncated...)\n","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:10+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/www.bonifatiuswerk.de\/werk\/aktuelles\/nachrichten-2019\/rss.xml read error : Client error: `GET https:\/\/www.bonifatiuswerk.de\/werk\/aktuelles\/nachrichten-2019\/rss.xml` resulted in a `404 Not Found` response","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":3,"time":"2020-01-06T11:32:13+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:13+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"http:\/\/kostblog.de\/feed\/ read error : No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":3,"time":"2020-01-06T11:32:32+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:32+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/www.bagwfbm.de\/atom\/news read error : No parser can handle this stream","userAgent":"--","version":"17.0.1.1"}
{"reqId":"KmND2uvRG3mToQAI1bjs","level":2,"time":"2020-01-06T11:32:43+00:00","remoteAddr":"","user":"--","app":"news","method":"","url":"--","message":"https:\/\/derstandard.at\/?page=rss&ressort=KolumnevonJesperJuul read error : Client error: `GET https:\/\/derstandard.at\/?page=rss&ressort=KolumnevonJesperJuul` resulted in a `404 Not Found` response:\n\r\n\r\n<!DOCTYPE html>\r\n<html lang=\"de\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=devi (truncated...)\n","userAgent":"--","version":"17.0.1.1"}
{"reqId":"XhMbCNGmBFsBRBkYyP-EcAAAAAM","level":3,"time":"2020-01-06T11:33:28+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbCdGmBFsBRBkYyP-EcQAAAAU","level":3,"time":"2020-01-06T11:33:29+00:00","remoteAddr":"95.91.92.145","user":"JanaSchlegel","app":"polls","method":"GET","url":"\/index.php\/apps\/polls\/poll\/hoboRzDu6Tg0H9ZX","message":"JanaSchlegel","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbTa0RPGo0n7YaaLXkXgAAAAk","level":3,"time":"2020-01-06T11:34:37+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/poll\/hoboRzDu6Tg0H9ZX","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbTa0RPGo0n7YaaLXkXgAAAAk","level":3,"time":"2020-01-06T11:34:37+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/poll\/hoboRzDu6Tg0H9ZX","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbv743jSecXg2DctjnyAAAAAc","level":3,"time":"2020-01-06T11:36:31+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbv743jSecXg2DctjnyAAAAAc","level":3,"time":"2020-01-06T11:36:31+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbyr5f@Hk2gH3X0ZzpoAAAAAM","level":3,"time":"2020-01-06T11:36:42+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/poll\/1","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMbyr5f@Hk2gH3X0ZzpoAAAAAM","level":3,"time":"2020-01-06T11:36:42+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/poll\/1","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMcNQ6X6Flce00NUPzYmgAAAAc","level":3,"time":"2020-01-06T11:38:29+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Db\/Event.php#86","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
{"reqId":"XhMcNQ6X6Flce00NUPzYmgAAAAc","level":3,"time":"2020-01-06T11:38:29+00:00","remoteAddr":"95.91.92.145","user":"ThomasKujawa","app":"PHP","method":"GET","url":"\/index.php\/apps\/polls\/get\/polls","message":"strpos(): Empty needle at \/www\/htdocs\/w0174798\/cloud\/apps\/polls\/lib\/Controller\/ApiController.php#280","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.1.1"}
```

**Comment by dartcafe** [comment]
Which version of polls do you refer to?

**Comment by dartcafe** [comment]
Just checked 1.0 beta2: Removing expiration date works. I ssume, you refer to version 0.10, where this was a known issue. I close this.
