### ISSUE TITLE
Polls 1.0 beta issue while activating in apps

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/polls#712]
![grafik](https://user-images.githubusercontent.com/6906390/71842077-312bd900-30c1-11ea-8b03-3af104df8d9a.png)

known issue?

**Comment by dartcafe** [comment]
Which DB system is in use?

**Comment by kangaroo72** [comment]
MariaDB 10.4.11 on Ubuntu 18.04 LTS

**Comment by dartcafe** [comment]
I made a fix in #713. Can you replace your version of the file Version0010Date20191227063812.php with the updated from this PR, deactivate polls and activate it again? The migration will continue. 

https://github.com/nextcloud/polls/blob/migrationFix/lib/Migration/Version0010Date20191227063812.php

**Comment by kangaroo72** [comment]
Works, but cannot activate. The app still shows "activate" again.

**Comment by dartcafe** [comment]
Which NC version? I made another fix for the migration. Maybe, this helps. Version0010Date20191227063812.php is to replace another time. sorry...

**Comment by kangaroo72** [comment]
Still not working. NC17.0.0

**Comment by dartcafe** [comment]
Any log entries? 
Can you do a db rollback before the migration? 
Another way: 
- Remove polls from the system
- remove all tables beginning with oc_polls
- remove all entries from oc_migration regarding to the polls app
- install from appstore (0.10.4)
- create a test poll
- install polls (with replaced Version0010Date20191227063812.php)
- activate app

**Comment by kangaroo72** [comment]
Does not work at all :-(
`Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

InvalidArgumentException: Migration step 'OCA\Polls\Migration\Version0010Date20191227063812' is unknown

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.`

**Comment by dartcafe** [comment]
can you send a dump of your oc_polls tabels and the oc_migration? 
You can upload here: https://nc.yagst.de/index.php/s/5Dc8wWGY5AKfHMj

**Comment by dartcafe** [comment]
I tried now several times with the steps above and it works on my side, after removing the issues. I will pack a new beta this evening. Maybe, you can try again with the new release.

**Comment by kangaroo72** [comment]
is the new beta online?

**Comment by dartcafe** [comment]
come today. I am merging

**Comment by kangaroo72** [comment]
will give a try ...

**Comment by kangaroo72** [comment]
Still the regular app needed, and then copy over the beta?

**Comment by kangaroo72** [comment]
![grafik](https://user-images.githubusercontent.com/6906390/72021720-f5367680-326e-11ea-8c86-91a2a75cbe1d.png)

**Comment by kangaroo72** [comment]
works now
