### ISSUE TITLE
1.0b2: "Create poll" design flaws

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#716]
The "create poll" process needs some polishing:

- The button "Add new Poll" is way to big.
- Depending on your browser the type part is misaligned and controls are overlapping (Safari and Firefox above, Chrome below).
- After you applied a title and a type for your new poll the app should immediately open the details pane on the right. Without configuration, options etc a poll makes no sense.

![Safari](https://user-images.githubusercontent.com/43957716/71987481-8fc29580-322e-11ea-8d13-abbd97aeb3d4.png)

![Chrome](https://user-images.githubusercontent.com/43957716/71987491-96510d00-322e-11ea-8de6-eb221098a376.png)

**Comment by dartcafe** [comment]
Firefox is ok for me, but chrome has an issue (first picture).

**Comment by dartcafe** [comment]
fixed in beta3 (al least ok in firefox and chrome)

**Comment by herrmannsdorfer** [comment]
Confirmed for FF and Chrome. Safari still shows the overlapping controls as Chrome did before.

And now the details in the right pane automatically open after you hit "Apply". Very good!
