### ISSUE TITLE
Sort polls in poll list

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#717]
- There should be a way to sort polls in the left overview "All polls" or in the main view, eg by dragging an item or selecting a column header.
- I would prefer a standard sorting by youngest at the top. This way you don't have to scroll down to see the latest entries (new polls or polls with recent votes or comments).
- Maybe it would be a good idea to pin selected polls as favorites at the very top of the list.

**Comment by dartcafe** [comment]
Sorting is still missing and will come with a better poll management.
Favorites are not planned for now. there are things of more worth. You can open an issue for that.

**Comment by dartcafe** [comment]
#586
