### ISSUE TITLE
1.0b2: "Delete" is missing

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#718]
- The delete function does not work.
- The clone function does not work either or I do not understand how to use it.

**Comment by herrmannsdorfer** [comment]
The "Delete poll" button in the config pane works. The option in the overview (...) does not.

**Comment by herrmannsdorfer** [comment]
When a poll ist already deleted, the option to delete it should be omitted in the three dot menu in the overview (or replaced with "restore poll" instead).

**Comment by herrmannsdorfer** [comment]
As deleted polls are also listed in the "All polls" overview (should they?) they should have an "deleted" icon to distinguish them from open polls. Red icon perhaps?

**Comment by dartcafe** [comment]
poll management will return later. I removed the options for the moment, as they do not work as expected.

**Comment by dartcafe** [comment]
When deleting a poll, it diapperas from all lists and appears in the deleted polls on my test site.

**Comment by herrmannsdorfer** [comment]
Just tried with a new user and fresh polls. Deleted two of them and added this info to the title. The deleted polls are not in "All polls" in the left pane but still listed in the main view. They are of course listed in "Deleted polls".

![Bildschirmfoto 2020-01-09 um 14 36 25](https://user-images.githubusercontent.com/43957716/72072427-33bf4600-32ee-11ea-82b8-9420f0557efa.png)

**Comment by dartcafe** [comment]
Ah. I only watched the navigation. Will check that.
