### ISSUE TITLE
1.0b2: Public poll features missing

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#719]
It is great that you added personal tokens for public polls. The personal link should be recoverable:
- The participant has to enter his e-mail address to receive his personal link.
- This way he may opt to receive updates on the poll as well.
- The moderator should be able to send lost personal links to participants (again e-mail address is needed).
- Maybe a hint is needed: "no mail means no updates and no way to recover a lost personal link to this poll" or something similar and more polite ...

**Comment by dartcafe** [comment]
> * The participant has to enter his e-mail address to receive his personal link.

comes later
 
> * This way he may opt to receive updates on the poll as well.
depends on the mail address


> * The moderator should be able to send lost personal links to participants (again e-mail address is needed).

planned. Workaround: copy link and sen an email
> * Maybe a hint is needed: "no mail means no updates and no way to recover a lost personal link to this poll" or something similar and more polite ...

as stated above: Workaround: copy ...

"If you're not embarrassed by the first version of your product, you’ve launched too late"

**Comment by dartcafe** [comment]
#286
