### ISSUE TITLE
1.0b2: timestamps in comments are off

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#720]
The calculation of timestamps in comments is a bit off. When I comment now and refresh the page the comment will show a date "an hour ago" ("vor einer Stunde" in German). A little more precision would be helpful.
The talk devs had a similar problem once and they chose simple hh:mm and put headings in the form "14 days ago, Dec 27, 2019" (centered, light gray, with hairline to the left and right) to give some structure to the chat history. This way you need not translate every timestamp of every comment to some inaccurate verbal expression of time.

**Comment by dartcafe** [comment]
fixed in beta3
