### ISSUE TITLE
Checkboxes not working as expected

### ISSUE THREAD

**Issue by marcoesch** [nextcloud/polls#725]
### What is going wrong?
When answering to a poll the checkboxes are not working correctly - the red X is not displayed just the square is turning red. Yellow "Maybe" option and the "Yes" option are displayed correctly for the Nextcloud 15.0.12 with App version 0.10.4
For the Nexctcloud 17.02 und App-Version 0.10.4 it is worse just the square is changing colors nothing appears inside the checkbox

**To Reproduce**

**Expected behavior**
inside the square one of 3 elements should appear checked (green), checked between paraentheses (yellow), or X  (red)

**Screenshots**

### Information about your polls installation
**Polls version?** (see apps page)
0.10.4
**Fresh installation or update from a prior version (from which one)?**
update
**How did you install this version?(Appstore or describe installation)**
Dont know
### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud
**Which Version?**
Nextcloud 15.0.12 and Nextcloud 17.02

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:**
Desktop/mobile phone/ tablet/... 

**Browser:**
Firefox and Chrome
**Operating system:**

### Logs

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by dartcafe** [comment]
I had this several times and it seems to be a caching issue in the old version. Clear all website data and cache and stay tuned: Version 1.0 will be released soon.
