### ISSUE TITLE
Remove Participants from vote

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#736]
Poll owner should be able to remove participants and their votes from a poll.

**Comment by UweV** [comment]
There is an new option in 1.2.0 RC "Allow admins to edit poll". I can activate the checkbox "As an admin you may edit this poll" but after that I find no way to edit votes from other users or remove wrong participants!

**Comment by dartcafe** [comment]
This setting allows an admin to act like the owner. Editing votes is still not implemented.

**Comment by UweV** [comment]
Ok I understand. It would be very helpful if a owner could remove wrong participants from his poll.
For example in case a user had made votes from different devices.

**Comment by dartcafe** [comment]
That's why this issue and the linked ones exist. It is schedudeld with the 'next' milestone, which means, it will be developed in one of the next releases. I hope within the 1.x releases.
