### ISSUE TITLE
Limit numer of votes per participant

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#738]
Limit the numer of 'yes' votes a participant can set.

**Comment by dartcafe** [comment]
DB is prepared

**Comment by topiux** [comment]
@dartcafe +1 a must for our use case. Thanks for giving attention to this feature request.

**Comment by christianlupus** [comment]
@dartcafe I would need this feature too. Is there any plan if and when this might get implemented in the frontend?
I am less concerned about a way to trick in multiple votes from one user but more of a UX such that there is only a set of radio buttons (aka exactly one option to choose from).

**Comment by dartcafe** [comment]
No schedule right now. But not in the 1.5 version.

**Comment by jhnet** [comment]
+1 as I would need this too ;)

**Comment by annievoss** [comment]
+1 me too!

**Comment by ostasevych** [comment]
Are any updates on this request?..
