### ISSUE TITLE
Polls 1.0.0 RC3 is out

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#740]
Polls 1.0 is feature complete. Just bug fixes will be done. Best will be a fresh install or an update from the last release 0.10.4. 

❗️ Please remember, this is still a test version and a pre-release. So please do not use on a production system. 

This is hopefully the last testversion before the stable release

Download here: https://github.com/nextcloud/polls/releases/tag/v1.0-rc3

**Comment by herrmannsdorfer** [comment]
Good job! I did a quick test and found the following issues:

- in table layout the column headings are misaligned in fav votes (Safari only).
![Bildschirmfoto 2020-01-13 um 09 04 22](https://user-images.githubusercontent.com/43957716/72241550-66678800-35e7-11ea-8595-022903603bc1.png)

- missing "remember last state" when switching view (was working in beta). That would mitigate the design change with default view - not every user likes the new design ...
- invitation mail is sent, activity mails are not. no err in log. no cron err.
- public poll shows blank page in Chrome and Safari (working in FF).
![Bildschirmfoto 2020-01-13 um 09 03 38](https://user-images.githubusercontent.com/43957716/72241564-6d8e9600-35e7-11ea-8f3c-e382c9a61114.png)

- new polls are not automatically listed in "All polls" (refresh needed, was working in beta).
- icons missing in "all polls" list. Only icon for text based polls are shown.
![Bildschirmfoto 2020-01-13 um 09 04 58](https://user-images.githubusercontent.com/43957716/72241535-5ea7e380-35e7-11ea-9875-f9a0a4baed71.png)

**Comment by brtptrs** [comment]
In our test installation public links result in an empty page. Firefox shows this error:

![2020-01-13_16-01-public-poll](https://user-images.githubusercontent.com/8102905/72266193-2c65a880-361e-11ea-8d4f-e42d3fa54f1d.png)

**Comment by herrmannsdorfer** [comment]
Just checked public poll with FF again: @brtptrs is right. I edited my comment above accordingly.

**Comment by dartcafe** [comment]
@herrmannsdorfer 

> in table layout the column headings are misaligned in fav votes (Safari only).

Checked on Firefox, Chrome and Safari. Looks Ok for me in all three browsers. 

> missing "remember last state" when switching view (was working in beta). That would mitigate the design change with default view - not every user likes the new design ...

last state was  never remembered, I think, it looks like, because, if you chenge from poll to poll, the state remains, as well as the sidebar state.


> invitation mail is sent, activity mails are not. no err in log. no cron err. EDIT: A few minutes later (cron?) the log shows:

Yep. The background job had a bug, so it stops every time. Alreaday fixed this yesterday. 
But there seems to be a bug in the background job execution (or it's by design), because on every cron execution, only one job is executed, although the notification job is set to be executed every five minutes (or seconds, docs are a little bit confusing). In the end, the job should be called on every cron execution, but it don't. I will check this afterwards.


> public poll shows blank page.

fixed. also @brtptrs 



> new polls are not automatically listed in "All polls" (refresh needed, was working in beta).

fixed


> icons missing in "all polls" list. Only icon for text based polls are shown.

The calendar icon is alway generated as icon-calendar-fff (icon is white), All other icons are ok. As a workaround, I hardcoded it to black for the moment.

@jancborchardt Any idea, why this only happens to the calendar icon? 
https://github.com/nextcloud/polls/blob/344824b685eee2e26822a618a8a67814671ae2b4/src/js/components/Navigation/PollNavigationItems.vue#L61-L65
The icon-toggle-list class returns 
```
.icon-toggle-filelist {
	background-image: var(--icon-toggle-filelist-000);
}
```
The icon-calendar class returns 
```
.icon-calendar {
	background-image: var(--icon-calendar-fff);
}
```
And @jancborchardt I think, we could need some UX experience for the UI. Any suggestions?

**Comment by dartcafe** [comment]
Updated to RC2 
https://github.com/nextcloud/polls/releases/tag/v1.0-rc2

**Comment by herrmannsdorfer** [comment]
> > in table layout the column headings are misaligned in fav votes (Safari only).
> 
> Checked on Firefox, Chrome and Safari. Looks Ok for me in all three browsers.

Maybe a Safari bug. When I refresh the cache, zoom in and out its sometimes there sometimes not.

> > missing "remember last state" when switching view (was working in beta). That would mitigate the design change with default view - not every user likes the new design ...
> 
> last state was never remembered, I think it looks like, because,if you change from poll to poll, the state remains, as well as the sidebar state.

I will open an issue for that. Maybe a view preference would be a nice enhancement.

Public votes are working now, but in FF you cannot comment (Chrome works):

![Bildschirmfoto 2020-01-14 um 08 52 40](https://user-images.githubusercontent.com/43957716/72324435-3da8c680-36ab-11ea-974c-54f5c6f9213a.png)

**Comment by brtptrs** [comment]
It seem posting the first comment is blocked from the main window. After posting a comment from the right sidebar I can post further comment from the main (middle) pane.

**Comment by herrmannsdorfer** [comment]
But in a public poll there is only a main view, no left or right sidebar.

**Comment by brtptrs** [comment]
The links to submissions, generated via public polls, lead to a "File not found" error.

**Comment by brtptrs** [comment]
Error shown when trying to post a comment as a participant:
![2020-01-14_11-03-poll-comment](https://user-images.githubusercontent.com/8102905/72334647-f0822000-36bd-11ea-8ea7-bcaa8447fae4.png)

**Comment by jancborchardt** [comment]
> And @jancborchardt I think, we could need some UX experience for the UI. Any suggestions?

@dartcafe cool! :) Yes, definitely plenty of suggestions, but this week is a bit busy with release preparations for 18. cc @nextcloud/designers meanwhile.
In general it’s great to see all the nice work towards simplifying the interface, and we can for sure do more there. :)

**Comment by dartcafe** [comment]
> but this week is a bit busy with release preparations for 18

I was sure about that. No hurry. UX should be improved after version 1.0. I want to get it out with NC 18. We can make it better afterwards.

**Comment by dartcafe** [comment]
> /index.php/s/BlWPtihjrrjWa8x8o6nHr
> is shown and does not work
> /index.php/apps/polls/s/BlWPtihjrrjWa8x8o6nHr
> Does work

Grpfl... Will check and fix that later, as well as the commentings. 
BTW: The comments sidebar is obsolete, so I will remove that.

**Comment by herrmannsdorfer** [comment]
> > invitation mail is sent, activity mails are not. no err in log. no cron err. EDIT: A few minutes later (cron?) the log shows:
> 
> Yep. The background job had a bug, so it stops every time. Alreaday fixed this yesterday.
> But there seems to be a bug in the background job execution (or it's by design), because on every cron execution, only one job is executed, although the notification job is set to be executed every five minutes (or seconds, docs are a little bit confusing). In the end, the job should be called on every cron execution, but it don't. I will check this afterwards.

I received a bunch of notifications exactly 5 hrs after the install of RC2. 

System cron job for my NC instance runs every 5 minutes - if that info helps debugging. Last cron related err in log was while RC1 was running.

Never had these err until Polls beta or RC.

![Bildschirmfoto 2020-01-14 um 14 11 57](https://user-images.githubusercontent.com/43957716/72347271-0bfa2480-36d8-11ea-9719-afe9c5148c91.png)

![Bildschirmfoto 2020-01-14 um 14 12 47](https://user-images.githubusercontent.com/43957716/72347281-10264200-36d8-11ea-99f2-9620583406f2.png)

**Comment by dartcafe** [comment]
The comments component behaves strange. If it is placed in the side bar, everything works, as it should. Putting it to the main view this get weird. Commenting throws that error and the vote reloads. There must be something, which I don't see. For the moment I placed it back to the side bar for public and non public polls.

**Comment by dartcafe** [comment]
> I received a bunch of notifications exactly 5 hrs after the install of RC2.

@herrmannsdorfer Are you sure, you replaced the app correctly. I had this log entries in RC1, but fixrd it in RC2. I do not get these errors anymore... I am testing on NC18

**Comment by herrmannsdorfer** [comment]
> > I received a bunch of notifications exactly 5 hrs after the install of RC2.
> 
> @herrmannsdorfer Are you sure, you replaced the app correctly. I had this log entries in RC1, but fixed it in RC2. I do not get these errors anymore... I am testing on NC18

Notifications are resolved with RC2.

Sorry, maybe a misunderstanding. As said: The last cron related err were with RC1. The delayed notifications originated from RC1 tests and they came exactly 5 hrs after RC2 went live on my server (for whatever reason). Server is running NC17. Testing with RC2 now results with invitations and activity notifications sent within the 5 min timeframe of configured background job calling cron.php.

**Comment by dartcafe** [comment]
Ehm. yes. No I see. Good to hear. So it seems to work as expected (nearly)

**Comment by dartcafe** [comment]
Now I understand. The delay is because failed Jobs will be paused 12 hours by the core system.

**Comment by dartcafe** [comment]
Updated to RC3.

**Comment by dartcafe** [comment]
@jospoortvliet We are just releasing polls 1.0. Comming back to your offer in this issue: https://github.com/nextcloud/polls/pull/385#issuecomment-429538593 What about some promotion?

**Comment by dartcafe** [comment]
CC @v1r0x
