### ISSUE TITLE
l10n: Add plural handling to message

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/polls#742]
Reported at Transifex. See

 https://github.com/nextcloud/polls/blob/1582780a61dd47cbb30f3a3b3c584f40e025ca87/src/js/components/Base/PollInformation.vue#L30

Message does not work if only one participant joined a vote.

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/pull/743/commits/8b91e6b9c6506d0df2dd00360b25f7417a1f2484
