### ISSUE TITLE
Preference for default view

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#744]
In polls 1.0 the default view changed from "doodle basic" table layout to a new list view. A "Switch view" button was added to change the mode. Although the last state was not remembered when you log off.

The new list view is a valuable addition. It gives a condensed, analytical overview.

The old layout is more detailed and probably familiar to anyone with doodle experience.

- I would suggest that the last state of the view is remembered. Moderators might want to use the new list view, other participants may prefer the "classic" view.
- To mitigate the layout change I would also suggest that the default view remains the table layout. That will make it easier for new poll participants who doodled before.

**Comment by dartcafe** [comment]
>     * To mitigate the layout change I would also suggest that the default view remains the table layout. That will make it easier for new poll participants who doodled before.

Agree to that. I wanted to force some feedback for the other layout. 



>     * I would suggest that the last state of the view is remembered.

I would prefer a personal setting.

**Comment by prismopensource** [comment]
Would be very nice to have this as an option for the poll itself. For text based polls the default view is almost unusable since longer words will overlap with words from the next column.

**Comment by kainhofer** [comment]
I'm currently setting up the (virtual) general assembly of a large association (>500 members). The voting on all committees is to be done with the nextcloud polls app (the management board was already elected using the polls up in June -> it worked REALLY WELL)!

For my use-case, I would definitely prefer an view option for the poll itself. 
In my case, the committees (to be voted yes/no) have quite long names, so the named in the default table view overlap (bug #927). Furthermore, for private polls, no other votes will be visible, so having one single loooong line of options is certainly less user-friendly than a single column of options.
For date-based polls or polls where other votes are visible, the table view might make more sense. So in my eyes, the default view should be set per-poll and not neccessarily as a personal preference of the user.

BTW, is there currently any way to force a poll into list view by default? I wouldn't mind installing a git version and hardcoding the view for now, but the default table view is simply unusable for text-base polls with long option names.

**Comment by dartcafe** [comment]
@kainhofer This is something I am annoyed about too. I checked out a local branch after I get it working with the current master (just for you 😄). It is not well tested and the master branch is not out yet (but should be shortly). 

If you like, you may try https://github.com/nextcloud/polls/tree/default-view 

Default for text polls is mobile, for date polls it is desktop. User may define their preferred default via the settings, but settings for that are currently missing. 

I didn't plan this to be released with 1.5 but with the following release.

**Comment by dartcafe** [comment]
I added a pre-release release here: https://github.com/nextcloud/polls/releases/tag/v1.5.2-view

**Comment by dartcafe** [comment]
Added settings.
