### ISSUE TITLE
1.0RC2: Invitation to group is not working well

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#748]
Have not tested groups before, but:

- Invitation to a group does not send invitation mail to members of the group.
- Selecting a group from available groups or directly entering a group name and pressing enter gives a notification "Error while adding share". 
![Bildschirmfoto 2020-01-16 um 15 15 59](https://user-images.githubusercontent.com/43957716/72535103-469ac300-3878-11ea-8bf2-0b2b7d21f624.png)

- The group is not immediately listed in the list of invited users below. First you have to refresh the page or switch to other content and return to the shares.
- It is possible to add the same group multiple times (by mistake because list is not refreshed or on purpose).
![Bildschirmfoto 2020-01-16 um 15 18 29](https://user-images.githubusercontent.com/43957716/72535129-56b2a280-3878-11ea-8ecb-ee567d6c1a18.png)

- Each duplicate gets its own "personal" link to the poll which directs to a public poll page - although the members of the group are ordinary NC users with logins. In previous versions the link to participants (known users) was non-public and directs you first to the NC login and after that to the specific poll.

**Comment by dartcafe** [comment]
> Invitation to a group does not send invitation mail to members of the group.

Works here, even when endering the group name "andere" and hitting enter. 
![grafik](https://user-images.githubusercontent.com/26707476/72669180-1cd7cc80-3a2f-11ea-8d7e-e685e18a93fd.png)

> The group is not immediately listed in the list of invited users below. First you have to refresh the page or switch to other content and return to the shares.

hmmm. reactivityy has no issue here, as you can see in the screenshot above.

> It is possible to add the same group multiple times (by mistake because list is not refreshed or on purpose).

I am aware of this. Will be fixed in another release. Maybe, you want to add an issue for that.

> which directs to a public poll page - although the members of the group are ordinary NC users with logins. 

That is indeed nonsense, because the poll link is useless for site users (individual users and group invitations). Will be removed in the next release.

**Comment by hj-beckers** [comment]
I get the same error as above "error while adding share" My nextcloud error log says:
 
Error	PHP	Undefined index: userEmail at /srv/www/htdocs/nextcloud/apps/polls/lib/Controller/ShareController.php#156	
2020-01-22T12:24:00+0100
Error	PHP	Undefined index: userEmail at /srv/www/htdocs/nextcloud/apps/polls/lib/Controller/ShareController.php#156	
2020-01-22T12:21:04+0100
Error	PHP	Undefined index: userEmail at /srv/www/htdocs/nextcloud/apps/polls/lib/Controller/ShareController.php#156	

Poll version is 1.0.0

**Comment by xadium** [comment]
I'm having the 'error while adding share' too.  I've even uninstalled the app, cleaned references to it from the database, dropped the tables and started from scratch.  No joy.

I've got the error when I try:

1. adding a group
2. users defined in Nextcloud
3. contacts in Nextcloud
4. users who come into Nextcloud from an external SQL database

I don't get any errors in the Nextcloud log

**Comment by hj-beckers** [comment]
Have to reopen this issue. 
- disabled polls
- saved polls 1.0.0 and removed the apps/polls directory
- restored polls-1.1.5-RC.tar.gz and renamed it to polls
- changed ownership to wwwrun.www (opensuse)
- enabled polls
- empty/blank screen when starting the app
- disabling/removing polls, restoring 1.0.0 shows all available polls
no entries in nextcloud log and apache errorlog.

**Comment by dartcafe** [comment]
@hj-beckers Did you remove the migration entries in oc_migrations?

>     * restored polls-1.1.5-RC.tar.gz and renamed it to polls

Please take the zip file. the tar.gz is just the source package without compiled app.

**Comment by hj-beckers** [comment]
> @hj-beckers Did you remove the migration entries in oc_migrations?
> 
> > ```
> > * restored polls-1.1.5-RC.tar.gz and renamed it to polls
> > ```
> 
> Please take the zip file. the tar.gz is just the source package without compiled app.

Works now. Thank you.
