### ISSUE TITLE
After installing 1.0RC2 I can no longer login to nextcloud

### ISSUE THREAD

**Issue by hj-beckers** [nextcloud/polls#750]
**Which Polls version are you running?** (see apps page) Trying 1.0RC2

**Nextcloud or ownCloud?:** nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page) 17.0.2

### Steps to reproduce
1. mv apps/polls to polls_old
2. unzip polls1.0-rc2.zip into apps/polls
3. calling https://my.nextcloud/instance results in a update mask for polls/17.0.2
   confirming the update results in a db insert error for oc_polls  (?), 

Aktualisierung auf 17.0.2

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_polls_polls` (`id`, `type`, `title`, `description`, `owner`, `created`, `expire`, `deleted`, `access`, `anonymous`, `full_anonymous`, `allow_maybe`, `options`, `settings`, `vote_limit`, `show_results`, `admin_access`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["27", "datePoll", "Einf\u00fchrungs-\/Wissen-Vermittlung in den Teams Systeme und Netze", "Einf\u00fchrung f\u00fcr die neuen Kollegen im IT-Service sowie Einweisung f\u00fcr die Anwendungsbetreuer", "BRevermann", 1539585860, 0, 0, "public", 0, "0", "1", "[\"yes\",\"no\",\"maybe\"]", "", 0, "always", 0]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '27' for key 'PRIMARY'

4. I could login, but got the error 	'Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.'
This message is from encryption/lib/Controller/StatusController.php.
I could dismiss this message and continue working. That was yesterday. Today nobody can login anymore. The login mask says "Wrong username/password". Asking for a password reset message generates no such mail. Resetting the password with occ user:resetpassword makes no difference.
After disabling the polls app with "occ app:disable polls " we can login, but get still the error message "Invalid private key ..." as above. Encryption was never enabled for this nextcloud instance.

### Actual behaviour
Tell us what happens

### Expected behaviour
I would like to login.
**In case of a bug, please answer the following questions**

### Server configuration

**Where did you install Nextcloud from:**
continuous updated from nextcloud.com
**Operating system**:
Opensuse 15.1
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.2
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - calendar: 1.7.2
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_accesscontrol: 1.7.0
  - files_automatedtagging: 1.7.0
  - files_rightclick: 0.14.2
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - support: 1.0.1
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_email: 1.0.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflow_script: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - forms
  - polls
  - polls1_0_RC2
  - polls_alt
  - privacy
  - recommendations
  - survey_client
  - user_ldap

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*REMOVED VALUE*",
            "*REMOVED VALUE*",
            "*REMOVED VALUE*",
            "*REMOVED VALUE*"
        ],
        "logtimezone": "UTC",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/*REMOVED VALUE*\/nextcloud\/",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "proxy": "*REMOVED VALUE*",
        "forcessl": true,
        "maxZipInputSize": 100,
        "allowZipDownload": false,
        "mail_smtpport": "25",
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "default_locale": "de_DE",
        "default_language": "de",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "logfile": "\/tmp\/nextcloud.log",
        "loglevel": "0",
        "knowledgebaseenabled": false,
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "forms"
        ],
        "mail_sendmailmode": "smtp",
        "htaccess.RewriteBase": "\/nextcloud",
        "theme": ""
    }
}


**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

### Logs

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by Schmuuu** [comment]
Same here. Instead of the NC web GUI I see a screen to upgrade the server and more specific apps like polls. When running occ upgrade the following error comes up:

```
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_polls_share` (`token`, `type`, `poll_id`, `user_id`, `user_email`) VALUES(?, ?, ?, ?, ?)' with params ["Vss3btV26Piw2ThL", "public", "2", null, null]:

SQLSTATE[HY000]: General error: 1364 Field 'user' doesn't have a default value
```

Would love to test this release candidate.

**Comment by dartcafe** [comment]
The login behavior is strange. 
@hj-beckers @Schmuuu 
Can you send me a dump of your oc_polls* tables? There seems to be some unusal data combination, which I cannot reproduce. Please add your user name to the file name. 

Upload is possible here: https://nc.yagst.de/index.php/s/i8LrNyJRyAcjc72

**Comment by dartcafe** [comment]
@Schmuuu There was the column 'user' missing in a migration step. So I think, that was the cause of the issue. I added this columt to the migration. I will release another RC this day. Maybe, you can try to continue the migration.

**Comment by dartcafe** [comment]
@hj-beckers 

I guess, the migration of the events was repeated after it already had been executed before.
Can you please check the following, if you are not able to upload your dump?

- [ ] Is there a table polls_events? 
- [ ] Is there a table polls_polls? 
- [ ] If both of the above questions are answered with yes, do both tables have the same amount of entries? 
- [ ] Is there a table polls_shares? 

You then have the following options: 
# repeat the migration:
* deactivate polls
* delete the table oc_polls_polls
* activate polls

**Comment by Schmuuu** [comment]
Hi @dartcafe 

Sorry I couldn't test and answer yesterday. Tried the RC3 now and now have the very exact same error message as @hj-beckers had.

> Duplicate entry 'X' for key 'PRIMARY'

I'll try to collect the requested data and update this post.

**Comment by Schmuuu** [comment]
@dartcafe Just want to let you know that dropping the table oc_polls_polls worked. The upgrade/ migration was successful afterwards and the app is running.
Thanks for the solution

It is looking really nice! Awesome work! :+1:

**Comment by dartcafe** [comment]
OK. Great and thanks to your support. I deleted the upload after inspecting. I found the combination, which I expected.

**Comment by hj-beckers** [comment]
> 
> 
> @hj-beckers
> 
> I guess, the migration of the events was repeated after it already had been executed before.
> Can you please check the following, if you are not able to upload your dump?
> 
>     * [ ]  Is there a table polls_events?
> 
>     * [ ]  Is there a table polls_polls?
> 
>     * [ ]  If both of the above questions are answered with yes, do both tables have the same amount of entries?
> 
>     * [ ]  Is there a table polls_shares?
> 
> 
> You then have the following options:
> # repeat the migration:
> 
>     * deactivate polls
> 
>     * delete the table oc_polls_polls
> 
>     * activate polls

Sorry for the late reply because of the weekend.
Both tables were there, had the same content (26 entries),.
I deactivated polls, dropped oc_polls_polls, moved apps/polls to polls, restored polls-1.0-rc3.tar.gz into apps/polls/ and activated the app.  Result is an empty page when clicking the polls icon? And all users still get the the error message "Invalid private key ..."

adminer shows table "oc_polls_events" as missing. These polls tables are still there:

zeigen oc_polls_comments
zeigen oc_polls_log
zeigen oc_polls_notif
zeigen oc_polls_options
zeigen oc_polls_polls
zeigen oc_polls_share
zeigen oc_polls_votes 

Reading your instructions again before sending my comment: You didn't ask me to use the new version, right? So it is my fault? I have a sql dump, I could restore the table?

Yours
Hermann-Josef Beckers

**Comment by dartcafe** [comment]
>     1. mv apps/polls to polls_old



> moved apps/polls to polls

What did that mean? Where did you move the polls app to?

**Comment by dartcafe** [comment]
> adminer shows table "oc_polls_events" as missing. These polls tables are still there:
> 
> zeigen oc_polls_comments
> zeigen oc_polls_log
> zeigen oc_polls_notif
> zeigen oc_polls_options
> zeigen oc_polls_polls
> zeigen oc_polls_share
> zeigen oc_polls_votes

That's fine.

> You didn't ask me to use the new version, right? So it is my fault? 

Nope. That's allright. 
> I have a sql dump, I could restore the table?

You could do that. After that
* disable polls
* remove all poll entries in oc_migration (at least these starting with 0010)
* REPLACE Polls app with the RC-3
* make sure, your backup folder of polls is NOT inside the apps folder (there can be only one polls application inside the apps folder)
* activate polls
* migration should run through.

I doubt, the encryption error is related to polls. 

You said 
> Encryption was never enabled for this nextcloud instance

but

> The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
> Enabled:
> [...]
> * encryption: 2.5.0
> 
> [...]

**Comment by hj-beckers** [comment]
> 
> 
> > 1. mv apps/polls to polls_old
> 
> > moved apps/polls to polls
> 
> What did that mean? Where did you move the polls app to?

Sorry for the typo. of course I moved it to apps/polls_old

**Comment by hj-beckers** [comment]
> I doubt, the encryption error is related to polls.
> 
> You said
> 
> > Encryption was never enabled for this nextcloud instance
> 
> but
> 
> > The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
> > Enabled:
> > [...]
> > 
> > * encryption: 2.5.0
> > 
> > [...]
You're right. Disabling encryption disables the error message. After the latest update to 7.0.2 a lot of apps were disabled. I enabled them on the command line. In my history log I found one "occ app:enable encryption" to much. Sorry for the noise.

**Comment by hj-beckers** [comment]
> 
> You could do that. After that

oc_polls_events contains 26 entries

> 
>     * disable polls
> 
>     * remove all poll entries in oc_migration (at least these starting with 0010)

removed 5 entries, 2 starting with 0010
> 
>     * REPLACE Polls app with the RC-3
> 
>     * make sure, your backup folder of polls is NOT inside the apps folder (there can be only one polls application inside the apps folder)
> 
>     * activate polls
> 
had to do this twice, because at first run I forgot to set rights to "wwwrun" -> gave an empty page as before 
>     * migration should run through.
At second run the following error occured: 

An exception occurred while executing 'INSERT INTO `oc_polls_polls` (`id`, `type`, `title`, `description`, `owner`, `created`, `expire`, `deleted`, `access`, `anonymous`, `full_anonymous`, `allow_maybe`, `options`, `settings`, `vote_limit`, `show_results`, `admin_access`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["27", "datePoll", "Einf\u00fchrungs-\/Wissen-Vermittlung in den Teams Systeme und Netze", "Einf\u00fchrung f\u00fcr die neuen Kollegen im IT-Service sowie Einweisung f\u00fcr die Anwendungsbetreuer", "BRevermann", 1539585860, 0, 0, "public", 0, "0", "1", "[\"yes\",\"no\",\"maybe\"]", "", 0, "always", 0]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '27' for key 'PRIMARY'

Seems to be the same as on friday.  If you still have an idea how to clean this situation, we should give it one more try. There is no actual poll running. Starting with a clean/empty database wouldn't be a problem.

Thanks

**Comment by dartcafe** [comment]
Waah. Where is my anser... Gr. 
OK: The error message says, the poll with ID, which I (the migration) want to copy from oc_polls_events to oc_polls_polls already exists. My guess is, you changed the order of the steps. 
1. deactivate or remove polls from the server
2. make sure, there is no copy of another polls backup in the app folder (otherwise NC will find it). 
3. delete the migration entries
4. delete oc_polls_polls
5. delete oc_polls_share (avoid double shares)
6. install polls 1.0 from appstore
7. activate the app

Of course you can wipe the polls app also, delete all tables (oc_polls_*) and remove the migration entries before installing. This will give you a clean install.

**Comment by hj-beckers** [comment]
> 
After following your 7 steps I get an empty polls masks with no entries. 

According to adminer:

oc_migration contains again 5 polls entries, 
oc_poll_comments 10 entries, 
oc_polls_log and oc_polls_share are empty, 
oc_polls_options 140 entries, 
oc_polls_notif 17 entries,
oc_polls_votes 5173 entries.

There is no oc_poll_events table. I made a new poll. Its parameters can be found in oc_polls_polls (?) In case I need the old polls, should they be imported into oc_polls_polls?

I think we can close this issue.
Thank you again for your help.

**Comment by dartcafe** [comment]
oc_polls_events gets deleted after successfull migration.
If the oc_polls_polls table exists, no migration from oc_events will be executed and the oc_polls_events gets deleted, if it exists. 


> In case I need the old polls, should they be imported into oc_polls_polls

Yes. But in this case, with an inconsitent scenario, behavior is unpredictable. 
At least with a clean 0.10.4 install the migration works. But if there are tables, which belong to 1.0.0 and  not to 0.10.4 it can be critical and data loss is possible.
