### ISSUE TITLE
cannot delete or duplicate polls in the main menu in mobile chromium based browser

### ISSUE THREAD

**Issue by szaimen** [nextcloud/polls#754]
### What is going wrong?
**Describe the bug**
cannot delete or duplicate polls in the main menu in chromium based browser

**To Reproduce**
1. create a poll
2. open the polls main menu: "all polls"
3. click on the 3-dots from a poll
4. cannot click on duplicate or delete (the buttons just dont work)

**Expected behavior**
I should be able to duplicate or delete a poll (the buttons should work)

**Screenshots**
![image](https://user-images.githubusercontent.com/42591237/72760561-72e87380-3bd9-11ea-9bd7-8b36f59e3fd7.png)

### Information about your polls installation
**Polls version?** 
1.0

**Fresh installation or update from a prior version (from which one)?**
Updated from the prior version

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
17.0.2

**Browser**
Android mobile chromium 79 based browser

**Comment by dartcafe** [comment]
@skjnldsv Any idea? We are using Actions from nextcloud-vue here. All desktop browsers on Windows (Chrome, Edge, Firefox) and Safari on iOS are working well.

**Comment by szaimen** [comment]
Strangely enogh, the action buttons on the vue-example site seems to work.

**Comment by szaimen** [comment]
Btw, this seems te be related: https://github.com/nextcloud/polls/issues/594

**Comment by szaimen** [comment]
And there is nothing in the console log, so everything seems to work as expected...

**Comment by dartcafe** [comment]
#594 is fixed and comes with the new release. I just saw, that your problem was related to the poll list and not to the navigation list. Do the actions work there?

**Comment by szaimen** [comment]
Do you mean here? Yes these work!
![photo5276135627286490247](https://user-images.githubusercontent.com/42591237/72807104-ef6d6780-3c56-11ea-95c8-3e74dbc1a4e3.jpg)

**Comment by szaimen** [comment]
@dartcafe is this done?

**Comment by szaimen** [comment]
Seems to be done based on the changelog.
