### ISSUE TITLE
cannot create a poll until I press the enter button on mobile chromium based browsers

### ISSUE THREAD

**Issue by szaimen** [nextcloud/polls#755]
### What is going wrong?
**Describe the bug**
cannot create a poll until I press the enter button on mobile browsers

**To Reproduce**
1. create a new poll
2. have to click on the enter button to be able to click on the create poll button

**Expected behavior**
should be able to click on the create poll button instantly after typing in the first letter

**Screenshots**
![image](https://user-images.githubusercontent.com/42591237/72760876-7cbea680-3bda-11ea-8d60-028a9dc575be.png)

### Information a
1.o

**Fresh installation or update from a prior version (from which one)?**
upgraded from the prior version

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Which Version?**
17.0.2

**Browser**
Android mobile chromium 79 based browser

**Comment by dartcafe** [comment]
I could reproduce it with chrome on android. The input is only accepted, when leaving the field or press enter on the keyboard. I believe, that this problem is related to the way, android and/or chrome are sending key inputs to the app. I fear, we have to live with that problem.

**Comment by szaimen** [comment]
> I could reproduce it with chrome on android. The input is only accepted, when leaving the field or press enter on the keyboard. I believe, that this problem is related to the way, android and/or chrome are sending key inputs to the app. I fear, we have to live with that problem.

is this maybe already solved by another app?
Otherwise this bug would appear in every app, that uses an input box, wouldn't it?

**Comment by dartcafe** [comment]
I believe, this problem is common for other vue apps, because we rely on the reactivity system. In the end it depends on the information, which are send from the browsers device. 

I googled a little bit and found this thread: https://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript

**Comment by szaimen** [comment]
> I believe, this problem is common for other vue apps, because we rely on the reactivity system. In the end it depends on the information, which are send from the browsers device.
> 
> I googled a little bit and found this thread: https://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript

So does that mean, that it is not possible, or is there a workaround for this?
Sry, TL;DR.

**Comment by szaimen** [comment]
If there is no workaround for this input recognition:
Maybe a workaround would be just enabling the button on android always and throw an error message, if no title was entered?

**Comment by dartcafe** [comment]
Short: No. I don't want to produce workarounds for specific browser behavior. Just tested a little bit around that. It seems, that the autosuggest prevents sending the keystrokes to the input field. When a word is completetd (choosen via the suggest list) or when pressing a space, the input field gets the update and the app has the needed information to enable the button. Also, when tapping outside the input field enables the button. 

IMHO an acceptable workaround.

**Comment by szaimen** [comment]
I am not completely satisfied by this but you are the developer. 👍
