### ISSUE TITLE
The icons in the left sidebar aren't visible in mobile chromium based browsers

### ISSUE THREAD

**Issue by szaimen** [nextcloud/polls#758]
### What is going wrong?
**Describe the bug**
The icons in the left sidebar aren't visible in mobile chromium based browsers

**To Reproduce**
1. open the left sidebar
2. the icons aren'tvisible

**Expected behavior**
the default icons should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/42591237/72761933-e9877000-3bdd-11ea-8c56-e8660f13ef66.png)

### Information about your polls installation
**Polls version?** (see apps page)
1.0

**Fresh installation or update from a prior version (from which one)?**
updated from prior version

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
nextcloud

**Which Version?**
17.0.2

**Browser**
Android mobile chromium based browser

**Comment by dartcafe** [comment]
All icons are visible to me in dark mode. Which dark mode did you activate? In NC, in the browser, in the OS?

**Comment by szaimen** [comment]
This is on Chromium 79 based Browser on Android mobile. The dark mode is only activated in Nextcloud.

**Comment by dartcafe** [comment]
look like the same issue as https://github.com/nextcloud/nextcloud-vue/issues/830
But the hover seem not to get reset. Minor priority and nothing we can do here. I will close that.
