### ISSUE TITLE
Existing polls not available after update to polls 1.0.0

### ISSUE THREAD

**Issue by domchrgit** [nextcloud/polls#761]
After update to nextcloud/polls 1.0.0 (from version 0.10.4) my existing polls are not visible.
If I browse the MySQL database, the entries are already there, but nothing is available in the new nexcloud/polls

How to recover the existing polls ?

Nextcloud 17.0.2 / Polls 1.0.0 / PHP7.3

**Comment by Art4** [comment]
I also have this issue. The problem is that the sharing url has changed from `https://example.com/index.php/apps/polls/**poll**/abc` to `https://example.com/index.php/apps/polls/**s**/abc`.

It would be nice if there would be a redirection from the old urls to the new ones.

**Comment by dartcafe** [comment]
@domchrgit Can you explain a little bit more? 
* What do you see (screenshot)?
* a sample of your db entries would help (oc_polls)

@Art4 I added a redirection from /poll/* to /s/* for public polls.

**Comment by domchrgit** [comment]
> @domchrgit Can you explain a little bit more?
> 
> * What do you see (screenshot)?
I see an empty page in polls tab since I had a only a single public poll made with previous version...
But effectively, outside of nextcloud, if I change the link as suggested by @Art4, I manage to view my old public poll.
Perhaps with the redirection you add, I will see again the poll in nextcloud after updating with the next release of polls app ?

> * a sample of your db entries would help (oc_polls)
> 
> @Art4 I added a redirection from /poll/* to /s/* for public polls.

**Comment by dartcafe** [comment]
@domchrgit Ah. OK thanks for explaining. 
It depends on the settings in the polls and who created the poll. If another user created the poll and it is set to hidden, only invited users can see the poll and the creator.

**Comment by domchrgit** [comment]
@dartcafe The poll was created by me, as administrator , and it was shared as a public poll...
Under my session I don't see the poll now with version 1.0.0. and the "old" link doesn't work without the modification suggested by @Art4 .
When do you expect to release the new version with your correction in Nexcloud/Polls ?

**Comment by Art4** [comment]
@domchrgit This bug will be fixed with 923d0f106c92e8699b966ea1721abfe15cd8824f.

@dartcafe The problem might be that there is no 404 page or redirect to login. You can reproduce this with an invalid share url like https://example.com/index.php/apps/polls/s/a This shows a white page and logs an error in the console.

**Comment by dartcafe** [comment]
Screenshots and a dastabase dump of the poll would help to understand.

**Comment by dartcafe** [comment]
> The problem might be that there is no 404 page or redirect to login

Yes. There are a lot of features and improvements missing.  It alway helps to create a separate issue for such things.

**Comment by dartcafe** [comment]
>  When do you expect to release the new version with your correction in Nexcloud/Polls ?

depends on available time of @v1r0x

**Comment by domchrgit** [comment]
Finally the problem was solved on my side ... for an unexplained reason, the poll was set to "hidden" after the update of polls app from 0.10.4 to 1.0.0. I changed this access value within the database and now the poll is accessible to other users.
