### ISSUE TITLE
Error while adding a public link

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/polls#763]
### What is going wrong?
I try to add a public link in details/share. This doesn't work. Pop up saying: "Error while adding share"
In the nextcloud log I get:
{"reqId":"XXXXXXXXXXXXXXX","level":3,"time":"2020-01-21T15:02:37+00:00","remoteAddr":"XXXXXXXX","user":"XXXXX","app":"PHP","method":"POST","url":"\/index.php\/apps\/polls\/share\/write\/","message":"Undefined index: userEmail at \/var\/www\/nc_01\/nextcloud\/apps\/polls\/lib\/Controller\/ShareController.php#156","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}

### Information about your polls installation
**Polls version?** (see apps page)
Version 1.0.0 updated from 0.10.4.
Updated from Appstore.

### Information about your Instance of Nextcloud/ownCloud
Nextcloud 17.0.2

**Comment by tmlmt** [comment]
Same issue here. Popup saying "Error while adding share". 
Nextcloud 17.0.2 / Polls 1.0.0 / Firefox 68.0.2 ESR on Windows 10

Network tool says the POST payload sent it:
`{"pollId":3,"share":{"type":"public","userId":"","pollId":3,"token":""}}`
which returns an empty response

**Comment by dartcafe** [comment]
That's strange, I checked the code and the userEmail is set every time. I will debug again and add a check, to avoid this error.

**Comment by RainerEmrich** [comment]
For Invitations it's the same. You try to invite some user or contact, same issue.

**Comment by dartcafe** [comment]
Something's wrong under the sun. I cannot reproduce that behavior. Anyway, I added a fix. Update is expected shortly.

**Comment by xadium** [comment]
HI

I looked at the fix in the [commit](https://github.com/nextcloud/polls/pull/762/commits/84e4f8b78085c04378e2a26b912a1a824db2c9cf) and implemented the fix to ShareController.php on my instance (as per my comment in #748 )

The line in the commit including the comma explodes Nextcloud - 'unexpected ('

`$newShare->setUserEmail(isset($share['userEmail']) ? $share['userEmail'] : '' , );`

the line without the comma has no effect on the issue:

`$newShare->setUserEmail(isset($share['userEmail']) ? $share['userEmail'] : '');`

I think something else is going on here...

**Comment by dartcafe** [comment]
Arrg. F***. Thanks for review. The problem is, I cannot reproduce this error. Of course the comma is a bug. I'll look after this issue.

**Comment by dartcafe** [comment]
Ok. New try, new hope. 
https://github.com/nextcloud/polls/releases/tag/v1.1.1-RC

**Comment by dartcafe** [comment]
This stays hope. Now user shares have a bug. Stay tuned. I will fix this this evenling. Sorry for inconvenience
