### ISSUE TITLE
Error while adding public link

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/polls#766]
### What is going wrong?
**Describe the bug**
Adding a public link does not work after installation v1. I've seen #763 and ported back #762, but error persists. No exception in NC-log.

**To Reproduce**
1. Create a poll
2. Try to add a public link

**Expected behavior**
A public link should be created...

**Screenshots**
![image](https://user-images.githubusercontent.com/1580193/72847659-51ec5500-3ca3-11ea-9e74-7cd0dfe99ca0.png)

![image](https://user-images.githubusercontent.com/1580193/72847795-8e1fb580-3ca3-11ea-8f6f-6d07205e2b17.png)

### Information about your polls installation
**Polls version?** 1.0.0

**Fresh installation or update from a prior version (from which one)?**
Updated version (not sure which one)

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
NC

**Which Version?**
17.0.2

**Comment by dartcafe** [comment]
#763

**Comment by SystemKeeper** [comment]
@dartcafe Please have a look at the report - I saw #763 and also ported back #762 and the error remains (no exception in the nextcloud log).
I installed 1.1.0-RC a few seconds ago:
![image](https://user-images.githubusercontent.com/1580193/72935477-b7087f00-3d65-11ea-9f04-82ed49ed4fbd.png)

Still:
![image](https://user-images.githubusercontent.com/1580193/72935541-d8696b00-3d65-11ea-9b0f-cd30afe17f1a.png)

Why is there a error about adding a share comment? Not sure what I'm missing here...

**Comment by dartcafe** [comment]
Release still pending, you can try the pre release
https://github.com/nextcloud/polls/releases/tag/v1.1.1-RC

**Comment by dartcafe** [comment]
1.1.0-RC was still buggy. 
You catched a very small time span, while this was online...

**Comment by SystemKeeper** [comment]
@dartcafe No problem, updated to 1.1.1:
![image](https://user-images.githubusercontent.com/1580193/72936923-778f6200-3d68-11ea-85bb-ce6d494c6376.png)

Still no way :(
![image](https://user-images.githubusercontent.com/1580193/72936962-89710500-3d68-11ea-90bb-7d9dc737b61c.png)

**Comment by dartcafe** [comment]
Yep. Have some more errors.
I will fix this this evening.

**Comment by SystemKeeper** [comment]
Thx, will report back after the fixes are made.

**Comment by dartcafe** [comment]
new pre-release online

**Comment by dartcafe** [comment]
> Still no way :(

unfolding the first line could help to see the payload. Was this a public share or a personal?

**Comment by SystemKeeper** [comment]
This was a public share. See comment above, its unfolded in screenthot.
I've updated to 1.1.2 - Creation of public links work now - thanks!

But I guess there're still some errors:
![image](https://user-images.githubusercontent.com/1580193/72943403-428a0c00-3d76-11ea-8d52-d6d20284c857.png)

![image](https://user-images.githubusercontent.com/1580193/72943451-60f00780-3d76-11ea-9dc1-ac1bc32620cc.png)

There're also no options visible:
![image](https://user-images.githubusercontent.com/1580193/72943517-88df6b00-3d76-11ea-9181-707eda58ac89.png)

(Just a note, when entering a username, its not enough to press enter, you need to click the arrow, which is kinda unintuitive I guess)

**Comment by dartcafe** [comment]
> But I guess there're still some errors:

Thanks. Was the same reason in another place. 

> Just a note, when entering a username, its not enough to press enter, you need to click the arrow, which is kinda unintuitive I guess

Yes, right. And the field is not really beautiful. Get's an overwork after polls is working stable.
New release out in seconds

**Comment by dartcafe** [comment]
If you are bored: I could need some feedback: https://github.com/nextcloud/polls/issues/771#issuecomment-577837329

**Comment by dartcafe** [comment]
@SystemKeeper If you are bored: I could need some feedback: https://github.com/nextcloud/polls/issues/771#issuecomment-577837329

**Comment by SystemKeeper** [comment]
@dartcafe Installed 1.1.5 and public polls are working fine for me now - thanks!

**Comment by SystemKeeper** [comment]
@dartcafe There're a few things UX-wise which I noticed. Do you want me to open a issue for each or is there a an issue where you track these things?

**Comment by dartcafe** [comment]
> There're a few things UX-wise which I noticed. Do you want me to open a issue for each or is there a an issue where you track these things?

individual issues are welcome, especially UX hints. There is a lot of space for improvement.

**Comment by SystemKeeper** [comment]
@dartcafe Ok, will have a look in the next days and create some issues. Feel free to close anything you don't agree with :-)

**Comment by dartcafe** [comment]
Thanks for your time. I will close the share issues and build a new RC.
