### ISSUE TITLE
Unlimited votes by guests

### ISSUE THREAD

**Issue by republicus** [nextcloud/polls#767]
**Is your feature request related to a problem? Please describe.**
Votes may be cast an unlimited number of times in Public polls

**Describe the solution you'd like**
Limit one vote per IP

**Describe alternatives you've considered**
Flag multiple votes on same IP as duplicate.

**Additional context**

Below nearly all votes are cast by me in a private browser window, one link, multiple votes casted.

![image](https://user-images.githubusercontent.com/47370709/72865112-a17f5080-3ca4-11ea-8e86-13aa44586fa3.png)

**Comment by dartcafe** [comment]
That's by design. A public vote can beused multiple times. Imagine colleagues behind one IP address.
