### ISSUE TITLE
V1.0:  An exception occurred while executing 'INSERT INTO

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#768]
**Which Polls version are you running?** (see apps page)
1.0

**Nextcloud version:** (see Nextcloud admin page)
18.0 

### Steps to reproduce
1. update polls to 1.0

### Actual behaviour
doesnt update, fals with error (see logs)

**In case of a bug, please answer the following questions**

### Server configuration

**Where did you install Nextcloud from:**

**Operating system**:
ubuntu0.18.04.1
**Web server:**
nginx/1.14.0 (Ubuntu)
**Database:**
10.1.43-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
**PHP version:**
7.2

**List of activated apps:**

Enabled:
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.2.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.0.0
  - music: 0.12.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocsms: 2.1.6
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.0.1
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "hXXXXXe",
        "trusted_domains": [
            "XXXX.de"
        ],
        "trashbin_retention_obligation": "auto",
        "version": "18.0.0.10",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "updater.release.channel": "beta",
        "theme": "",
        "activity_expire_days": 90,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "XXXXXXXX",
        "installed": true,
        "app_install_overwrite": [
            "calendar",
            "mail",
            "ocsms",
            "caniupdate",
            "audioplayer",
            "files_external_gdrive",
            "polls",
            "spreed",
            "contacts",
            "bruteforcesettings",
            "files_rightclick",
            "talk_simple_poll"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Logs

An exception occurred while executing 'INSERT INTO `oc_polls_polls` (`id`, `type`, `title`, `description`, `owner`, `created`, `expire`, `deleted`, `access`, `anonymous`, `full_anonymous`, `allow_maybe`, `options`, `settings`, `vote_limit`, `show_results`, `admin_access`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1", "datePoll", "Neujahrsfress 2018", "Auch diese Jahr moechte ich die Moeglcihkeit geben sich mal wieder gepfegt den Bauch voll zu schlagen...natuerlich in einem schoenen Ambiente!", "XXXX", 1511958753, 1512774000, 0, "public", 0, "0", "1", "[\"yes\",\"no\",\"maybe\"]", "", 0, "always", 0]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

**Comment by dartcafe** [comment]
see here: #750
