### ISSUE TITLE
Error creating public link

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#776]
Some systems are showing errors on creating public link 
Install the last release here: https://github.com/nextcloud/polls/releases 

Or wait for the appstore release.

**Comment by Dennis1993** [comment]
now it works, thanks! I hope a release is coming soon for all other users.
Thanks!!!

**Comment by Refhi** [comment]
Thanks for your hard work !

May I ask if the appstore release will be there soon ?
