### ISSUE TITLE
Use display name instead of userid on front end

### ISSUE THREAD

**Issue by christianvw** [nextcloud/polls#777]
### What is going wrong?
**Describe the bug**
After the update to Nextcloud 18 the userids are always displayed in the polls. This is extremely ugly when using openLDAP since the userids are like "d147852-25478daad-dee456a". Its impossible to use the app currently since its impossible to see who clicked on what.

**To Reproduce**
1. Use openLDAP to authenticate
2. Create a poll with a LDAP account
3. Check the poll with a different user

**Expected behavior**
Display names are shown instead of the userids.

### Information about your polls installation
**Polls version?** 1.0.0

**Fresh installation or update from a prior version (from which one)?** Updated from Nextcloud 17 (don't know the version of polls)

**How did you install this version?** Appstore

**Nextcloud or ownCloud?** Nextcloud

**Nextcloud/ownCloud version:** 18.0.0.10

**Comment by dartcafe** [comment]
#715
