### ISSUE TITLE
Allow site user to vote in hidden poll via public link

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/polls#779]
I'd like to discuss a current (v1.1.5) behaviour of polls regarding public links in connection with poll-visibility and app-restriction.

Let's assume we created a private poll (not visible for other users) and created a public link. Now this public link is send to different users, but behaves differently, depending on the user:

- **User is not a nextcloud-user**
Behaves as one would expect. A anon-user can add their votes through the shared public link.

-  **User is a logged-in nextcloud-user**
 1. _The user is allowed to use the polls app (no group restriction under Apps -> Polls)_
In this case the user is able to see the poll, but not make any votes, as it's a private poll and was not shared directly with this user.
 2. _The user is not allowed to use the polls app (ie. is not part of a group which is set in Apps -> Polls)_
In this case opening the public link will bring the user to the default files app.

I'm not sure what the intended behaviour here should be, but it shouldn't be like it is now.
I guess if a public link is shared, it shouldn't matter if the receiving user is a logged-in nextcloud user (with or without permission to use the app) or an anon-user. After all, it's a public link.

Any thoughts?

**Comment by dartcafe** [comment]
How it should be: 
* a hidden poll is hidden for users of the site (not in the list of the apps)
* if a site user enters the poll via a public link, he should be able to vote as any unauthorized user.

So, this is a bug, because, the site user can access the poll, but is not allowed to vote.

**Comment by dartcafe** [comment]
Workaround: set votes with public polls to visible or invite site user indiviually.

**Comment by SystemKeeper** [comment]
Does that cover the case when the use of the app is restricted to a group by the admin?

**Comment by dartcafe** [comment]
Unfortunately not, access is prevented by core. In this case, the user has to log out or use a private window in browser.

**Comment by SystemKeeper** [comment]
Ok, that's what I though. Thanks for fixing the other issue!

**Comment by dartcafe** [comment]
@SystemKeeper While waiting for the 1.1 release, you may checkt this issue in https://github.com/nextcloud/polls/releases/tag/v1.2.0-beta

**Comment by SystemKeeper** [comment]
Hey @dartcafe Thx, hope i can get to this later, will report back.

**Comment by SystemKeeper** [comment]
Looks like it's working now, thanks!
