### ISSUE TITLE
12-hour clock bug

### ISSUE THREAD

**Issue by dwerz** [nextcloud/polls#780]
### What is going wrong?
**Describe the bug**
If one event is marked, an other one (with 12h time gap) is marked at the same time.
Its impossible to choose two events at an interval of 12 hours individually. Missing distinction between 07:00 AM and 07:00 PM or 07:00 and 19:00.

**To Reproduce**
 1. Create a poll
 2. Create two or more events with 12h time gap
 3. Try to vote for one of the events

**Expected behavior**
Just one event, the selectet one, will be marked.

**Screenshots**
![poll-bug-12h-24h](https://user-images.githubusercontent.com/25308355/73124583-efda6b00-3f94-11ea-98ab-7d370a7de0be.png)

### Information about your polls installation
**Polls version?** 1.0.0
**Fresh installation or update from a prior version (from which one)?** Update
**How did you install this version?(Appstore or describe installation)** Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?** Nextcloud
**Which Version?** 17.0.2

**Comment by dartcafe** [comment]
Nice find, thanks. Corrected time format on creating date option
