### ISSUE TITLE
Issue listing or creating polls [NC16]

### ISSUE THREAD

**Issue by scottpk** [nextcloud/polls#787]
### What is going wrong?
**Since update I cannot list or create polls**
Since updating to 1.1.6 I see only the spinning circle when I click on any of the poll lists, or the button to create a new poll. Despite waiting several minutes.

### Steps to reproduce
Go to Nextcloud
Click on Polls
Click "Add new Poll" or any of the lists

### Expected behaviour
I expect that the page for adding a new poll, or the list of polls, would load.

### Actual behaviour
Circle spins forever

## Server configuration detail

**Operating system:** Linux 4.19.88-Unraid #1 SMP Mon Dec 9 11:16:40 PST 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.11

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.5.0
 - calendar: 1.7.2
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.8
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.6.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - maps: 0.1.4
 - nextcloud_announcements: 1.5.0
 - notes: 3.1.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 1.1.6
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "karbonated.asuscomm.com:443",
        "nextcloud.karbon.site:443"
    ],
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.karbon.site",
    "overwritehost": "nextcloud.karbon.site",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0

**Operating system:** Windows 10

## Logs

<details><summary>Browser log</summary>

TypeError: "t.list.filter is not a function"
    allPolls https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:1007
    e https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:936
    h/</o[n]</< https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:936
    get https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    evaluate https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    bn https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    get https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:936
    r https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:942
    get https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    evaluate https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    bn https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    Navigation https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:1035
    _render https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    r https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    get https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    run https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    fn https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    re https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    Xt https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
polls.js:7:11689
    Vt https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    Gt https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    Ut https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    _render https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    r https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    get https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    run https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    fn https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    re https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7
    Xt https://nextcloud.karbon.site/apps/polls/js/polls.js?v=70f4641b-6:7

</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/1653992/73144002-98a8c900-406e-11ea-84f3-15050c1180cc.png)

### Information about your polls installation
**Polls version?** (1.1.6)

**Fresh installation or update from a prior version (from which one)?** Update from previous (1.1.5)

**How did you install this version?(Appstore or describe installation)** Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?** Nextcloud

**Comment by luke-clifton** [comment]
Seeing the same issue on a fresh install after downloading the polls app.

**Comment by dartcafe** [comment]
@luke-clifton Which polls update way did you go? From 1.0.0 or an RC?

**Comment by dartcafe** [comment]
@scottpk Some logs in the admin's log or in the JS console?

**Comment by dartcafe** [comment]
@scottpk Grr. I always miss the collapsed entries.

**Comment by dartcafe** [comment]
Just made a few installation ways. 
* fresh install ✔️ 
* Update from 1.0.0 ✔️ 
* switching from dev branch to master (with 1.1.6) ✔️ 

Both on test, dev and production systems. Still no problem. 

Possible causes: 
* cache issue
* proxy issue
* magic

Could you send me your DB structure? 
Or all poll tables for inspection? 

Secure upload of files is possible here: https://nc.yagst.de/index.php/s/i8LrNyJRyAcjc72

**Comment by tron65** [comment]
i have the same issue, i updated from 1.0.0 to 1.1.6, and i just see the spinning circle, when opening the app. nextcloud-version is 16.0.7 

additionally, when the app is activated, when going to 

Settings -> Overview

the page does not load either.

**Comment by luke-clifton** [comment]
I didn't update. First time using nextcloud, and I just installed the app via the UI.

I do get this on the browser console output.

```
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:521
TypeError: "t.list.filter is not a function"
    allPolls polls.js:41
    e vuex.esm.js:777
    h/</o[n]</< vuex.esm.js:95
    VueJS 3
    get vuex.esm.js:567
    r vuex.esm.js:924
    VueJS 3
    Navigation Navigation.vue:1
    VueJS 7
    Z es.promise.js:114
    r microtask.js:26
vue.esm.js:1897:4
    VueJS 10
    Z es.promise.js:114
    r microtask.js:26
TypeError: "t.list.filter is not a function"
    allPolls polls.js:41
    e vuex.esm.js:777
    h/</o[n]</< vuex.esm.js:95
    VueJS 3
    get vuex.esm.js:567
    r vuex.esm.js:924
    VueJS 3
    filteredList PollList.vue:82
    VueJS 3
    sortedList PollList.vue:97
    VueJS 3
    h PollList.vue:1
    VueJS 7
    Z es.promise.js:114
    r microtask.js:26
vue.esm.js:1897:4
    VueJS 10
    Z es.promise.js:114
    r microtask.js:26
```

**Comment by brtptrs** [comment]
Same error:
Nextcloud 16
Upgrade to 1.1.6
Firefox 72

TypeError: "t.list.filter is not a function"
    allPolls polls.js:41
    e vuex.esm.js:777

**Comment by scottpk** [comment]
Well this is behind letsencrypt container which I am using to allow me to
use HTTPS and keep my files private. I do have Redis cache too. It doesn't
seem they've caused issues with the rest of Nextcloud though.

FYI I did try the direct link to a poll I had created last year and that
did load the poll. So it seems it's just these lists and the creating a new
poll which have an issue.

Also I did switch over to Edge, and that had the same issue.

I'm a microsoftie by day... I'm assuming MariaDB is similar to SQL Server?
I will try to export the database structure.

**Comment by dartcafe** [comment]
What do you get when calling https://yourdomain.com/index.php/apps/polls/poll/list/ ?

**Comment by vilim** [comment]
I get an empty page and the following in the javascript console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. main.js:160:6103
The escapeHTML library is deprecated! It will be removed in nextcloud 19. main.js:750:58
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 8 main.js:750:58
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:40967
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:40967
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:40967
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://##/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:40967
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/updatenotification/img/notification.svg (“img-src”). notifications.js:7:40967
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/nextcloud_announcements/img/app-dark.svg (“img-src”). notifications.js:7:44095
Content Security Policy: The page’s settings blocked the loading of a resource at http://###/apps/nextcloud_announcements/img/app-dark.svg (“img-src”). notifications.js:7:40967
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://##/core/js/dist/main.js?v=c55161b9-5
Source Map URL: main.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://##/apps/notifications/js/notifications.js?v=c55161b9-5
Source Map URL: notifications.js.map

```

**Comment by dartcafe** [comment]
Am I right, if you all have NC16 installed? I just setup an 16 instance, where I have the problem too. 
Seems that the routing system has changed and handels the given routes in the routes.php another way. 

You can manually fix this by commenting out the line 30 in the following code . 

https://github.com/nextcloud/polls/blob/802ad73f1b04441edbc62a73df138e506cc4cbb8/appinfo/routes.php#L29-L31

This was introduced in 1.1.6 to rewrite old public links to the new route. In NC16 this seems to be a problem, because /polls/ is a controller route for calling the backend. We have to change the routes to avoid this conflict. A bugfix will follow this week in this repo. Appstore release will take some time, because @v1r0x is rather busy and is the release manager for this app. 

Thanks for reporting this issue.

**Comment by dartcafe** [comment]
Or update to NC17 or 18. :-)

**Comment by scottpk** [comment]
You’re right, I updated to 17.0.2 and now it loads up OK. Thanks for looking into it!

**Comment by brtptrs** [comment]
The fix from https://github.com/nextcloud/polls/issues/787#issuecomment-578916682 solved the Problem for us on NC16. 
Thank you

**Comment by bpcurse** [comment]
@dartcafe I would like to propose to pin this issue at least until the fix is released to the appstore.

And using this opportunity:
Thank you very much for your extensive efforts in creating and fixing the new 1.x release! And thanks to all the reviewers and bug hunters as well :+1: This is very much appreciated.
