### ISSUE TITLE
Subscription request returns null

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/polls#788]
After setting the notification checkbox on the poll site, the notification is correctly saved, but after a reload, the checkbox is gone again (though notifications are still working!). I've seen that a call to `subscription/get` returns null:
![image](https://user-images.githubusercontent.com/1580193/73175486-9431ee00-410a-11ea-88ea-08c9d84f9a94.png)

Here's output of oc_polls_notif:

```
mysql> Select * FROM oc_polls_notif;
+----+---------+------------------+
| id | poll_id | user_id          |
+----+---------+------------------+
|  1 |       5 | user1            |
|  2 |       5 | user2            |
|  3 |       5 | user2            |
+----+---------+------------------+
3 rows in set (0,00 sec)
```

In this case I am user2. I had a quick look through the code, but didn't see anything obvious to me.

**Comment by dartcafe** [comment]
null is correct. Returncode 200 says, subscription set, 404 says not set.

**Comment by SystemKeeper** [comment]
Ah I see. Will have a look why the checkbox sometimes indicates a wrong state. 
Other than that, shouldn't (poll_id, user_id) be unique in the db?

**Comment by SystemKeeper** [comment]
@dartcafe I've tested a bit around (still on 1.1.5, sorry) and it looks like the request to `subscription/get/` is not made, when a poll is selected on the left side (only when I reload the page). I guess (not tested) it's because the dispatch is only made in the `mounted` event, not in a `watch` event as seen in the comments:
https://github.com/nextcloud/polls/blob/c74ca32e493e5e39cfa772cceb4fd36af105ad6c/src/js/views/PublicVote.vue#L104-L108
?

**Comment by SystemKeeper** [comment]
Ok, I'm still figuering things out here... Sorry not too familiar with Vue.

Have a look at the following:
```
/polls/src/js$ grep -R "loadPoll(" *
store/modules/votes.js: loadPoll(context, payload) {
store/modules/comments.js:      loadPoll(context, payload) {
store/modules/options.js:       loadPoll(context, payload) {
store/modules/shares.js:        loadPoll(context, payload) {
views/PublicVote.vue:                   this.loadPoll()
views/PublicVote.vue:           this.loadPoll()
views/PublicVote.vue:           loadPoll() {
views/Vote.vue:                 this.loadPoll()
views/Vote.vue:         this.loadPoll()
views/Vote.vue:         loadPoll() {
```
I guess when a poll is selected the `loadPoll` action in all modules is called. But as you can see, there's no `loadPoll` option for subscription. Is that's what's missing here?

**Comment by dartcafe** [comment]
The subscription is loaded on mounting the component. But there has to be a watcher on route changes.

**Comment by dartcafe** [comment]
fixed in beta3
