### ISSUE TITLE
LDAP Users are shown by Username not by Display Name

### ISSUE THREAD

**Issue by phimeas** [nextcloud/polls#790]
**Which Polls version are you running?** (see apps page)
1.1.6
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
17.0.2
### Steps to reproduce
1. Update to 1.1.6 and have a LDAP backend (AD or openLDAP)
2. Create a poll or show an existing one with LDAP-Users as owner or contributors

### Actual behaviour
In the poll all LDAP users appear with their username (something like '16d4xxxx-edyy-10xx-8d8a-e16e5b5zzzzz') and not with their display name (e.g. 'Joe Sixpack'), which is hardly readable.

### Expected behaviour
Owners and contributors should be displayed with their readable display names

**Comment by dartcafe** [comment]
#715
