### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#796]
### What is going wrong?
**Describe the bug**
Minor typo (german language)
"Keine Abstimmungsmöglchkeit vorhanden, füge welche hinzu." [sic]

**Expected behavior**
Should be:
"Keine Abstimmungsmöglichkeiten vorhanden, füge welche hinzu."

**Screenshots**
![nextcloud_polls_typo](https://user-images.githubusercontent.com/29312856/73366683-a3ea3780-42ae-11ea-8947-383fb1f23cf9.png)

### Information about your polls installation
**Polls version?** (see apps page)
1.1.6

**Nextcloud or ownCloud?**
Nextcloud 16.0.7

**Comment by dartcafe** [comment]
Yep. Already fixed via transifex. --> Correction in 1.2

**Comment by dartcafe** [comment]
I thought, you reffered to Teinehmer. Reading before helps. ;-) Fixed.
