### ISSUE TITLE
Move personal link to the sidebar

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#799]
After a user write their username the following screen is shown. I think we should move the personal link to the right side for more space on large polls. Between "Details" and "Kommentare" is nothing shown. Maybe we can move it to this blank space?

![image](https://user-images.githubusercontent.com/1473674/73378562-1a903080-42c1-11ea-8266-55f277e7d34f.png)

Or we can move the description "Testerei" to the right side?
For new users, it should be as simple and clear as possible without a lot of text right at the beginning.

What do you think about that?

If we move the link to the right side we should highlight the description because of the info above.

**Comment by dartcafe** [comment]
We definitely need improvement here. But moving to the sidebar throws errors from the used components.

**Comment by dartcafe** [comment]
The link moved to a user menue in 1.8. So this issue is obsolete and I will close this.
