### ISSUE TITLE
Two infos after set "Maybe" option

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#800]
### What is going wrong?
**Describe the bug**
If I set the option "Maybe" for a poll the info on the right side will shown two times. If I disable it I receive only one information.

**To Reproduce**
1. Create a new poll
2. Activate the "Maybe" option (see screenshot)

**Expected behavior**
Only one message appears

**Screenshots**
![image](https://user-images.githubusercontent.com/1473674/73378911-a4d89480-42c1-11ea-9674-12868759f3ba.png)

### Information about your polls installation
**Polls version?** (see apps page)
1.2.0 beta 4

**Nextcloud or ownCloud?**
NC 18.0.0

**Comment by dartcafe** [comment]
fixed.
