### ISSUE TITLE
"Enter a valid username" confusing f

### ISSUE THREAD

**Issue by CoreyBurger** [nextcloud/polls#803]
I found it bit confusing that the text is "Enter a valid username", when it will take anything even non-user names.

My preference would be to change the wording to "Enter your name". If a user gets a specific link in their email, we already know their username and if they are logged in, we have it too.

**Comment by thebarless** [comment]
Also, make the enter key submit the name. Currently have to click on the arrow (Safari) or push the arrow (iOS Safari)

**Comment by dartcafe** [comment]
> 
> 
> Also, make the enter key submit the name. Currently have to click on the arrow (Safari) or push the arrow (iOS Safari)

Already developed.

**Comment by dartcafe** [comment]
The placeholder is changed, the static text will stay as it is, to state clear, that there are conditions on the user name. 
![grafik](https://user-images.githubusercontent.com/26707476/74807091-e61ffb00-52e7-11ea-818d-148f48e8413e.png)
![grafik](https://user-images.githubusercontent.com/26707476/74807178-15366c80-52e8-11ea-955c-32c7c3e6fcb0.png)
![grafik](https://user-images.githubusercontent.com/26707476/74807209-2a130000-52e8-11ea-83ce-0c127082c341.png)
