### ISSUE TITLE
use displayNames in notification instead of userId

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#806]
Confirmed. Notifications work. But ...

Activity notification still uses userId instead of displayName :-)
![Screenshot 2020-01-30 at 09 35 40](https://user-images.githubusercontent.com/43957716/73432885-eb6ed300-4343-11ea-87ed-fcf6c30053fe.png)

_Originally posted by @herrmannsdorfer in https://github.com/nextcloud/polls/pull/798#issuecomment-580142028_

**Comment by herrmannsdorfer** [comment]
Works as expected in 1.2.0RC. Good job!
