### ISSUE TITLE
Polls 1.2.0 Release Candidate 2 is out

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#808]
https://github.com/nextcloud/polls/releases

[See Changelog](https://github.com/nextcloud/polls/blob/master/CHANGELOG.md) for a complete list of changes since 1.1.6

**Comment by Dennis1993** [comment]
It works for me!

One thing: If I set a expire date for the poll and the poll is expired: The user can visit the link and the modal windows for the username is shown. After I typed in my name the poll is shown without my name > because the poll os expired. The modal window is useless in this case.

**Comment by dartcafe** [comment]
Yes, it is obsolete in this case. Will fix this in the next version. Generally it is better to open a new issue for that. Things may get lost otherwise.

**Comment by dartcafe** [comment]
@v1r0x 🚀 Fire release 1.2.0?

**Comment by tortuetorche** [comment]
@dartcafe @v1r0x Any news for releasing the 1.2.0 version?

**Comment by v1r0x** [comment]
@tortuetorche sorry about that. had no time to build the release on my "build machine". I should have some free time this weekend :crossed_fingers:

**Comment by tortuetorche** [comment]
Good news 😎

I built myself the last version (https://github.com/nextcloud/polls/blob/v1.2.0-RC2/README.md#install-from-git) then I installed it on my Nextcloud instance and it's great!
Hope others people can shortly benefits of this polished update 🤞

Many thanks @dartcafe and @v1r0x for this hard work 🙇

**Comment by v1r0x** [comment]
Fresh 1.3.0 released! 🎉
