### ISSUE TITLE
Version mismatch since PR #807 

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#819]
Cosmetic issue:

Since #807 1.2.0rc is listed as version 1.3.0 in Apps. See commit 11afc6f4095e39a22ffb13be12bb0894a57e5249

**Comment by dartcafe** [comment]
Yes. Was planed for 1.3.0 but was easier than I thought. Switched the master version to 1.2.1.

**Comment by dartcafe** [comment]
Switched back to 1.3 to be compatible with the migration schema
