### ISSUE TITLE
1.2RC2: Invitation to group is not working

### ISSUE THREAD

**Issue by maphy-psd** [nextcloud/polls#825]
### What is going wrong?
**Describe the bug**
Invitation to a group does not send invitation mail to members of the group, like #748 

### Information about your polls installation
1.2RC2, app page says 1.3.0

### Information about your Instance of Nextcloud/ownCloud
Nextcloud 17.0.3

**Are you using an external user-backend, if yes which one:** IMAP

#### Nextcloud log (data/nextcloud.log)
nothing regarding polls

#### Browser log
network log says the POST payload sent with
```
{}
```

**Comment by dartcafe** [comment]
Works on my site. Please retry after this weekend, when 1.3 ist probably out.

**Comment by dartcafe** [comment]
@maphy-psd Problem still existent with the new version (1.3.0)?

**Comment by maphy-psd** [comment]
With the new version (1.3.0 - downloaded from the app store) i get this error:

```
uncaught exception: Snap's element argument does not exist. snap.js:506:20
Error writing share Object { error: {…} } Object { payload: {…} } shares.js:161:12
Error while adding share - Error:  Error: "Request failed with status code 409"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
SideBarTabShare.vue:210
    addShare SideBarTabShare.vue:210
```


<details>
  <summary>full error code (for the "invitation click")</summary>
Error writing share 
{…}
​
error: {…}
​​
config: Object { url: "/apps/polls/share/write/", method: "post", data: "{\"pollId\":3,\"share\":{\"type\":\"group\",\"userId\":\"Test\",\"pollId\":3,\"userEmail\":\"\",\"token\":\"\"}}", … }
​​
data: Object {  }
​​
headers: Object { "cache-control": "no-cache, no-store, must-revalidate", "content-length": "2", "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self'", … }
​​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​
status: 409
​​
statusText: "Conflict"
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
 
{…}
​
payload: {…}
​​
share: {…}
​​​
pollId: 3
​​​
token: ""
​​​
type: "group"
​​​
userEmail: ""
​​​
userId: "Test"
​​​
<prototype>: {…}
​​​​
__defineGetter__: function __defineGetter__()
​​​​
__defineSetter__: function __defineSetter__()
​​​​
__lookupGetter__: function __lookupGetter__()
​​​​
__lookupSetter__: function __lookupSetter__()
​​​​
__proto__: 
​​​​
constructor: function Object()
​​​​
hasOwnProperty: function hasOwnProperty()
​​​​
isPrototypeOf: function isPrototypeOf()
​​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​​
toLocaleString: function toLocaleString()
​​​​
toSource: function toSource()
​​​​
toString: function toString()
​​​​
valueOf: function valueOf()
​​​​
<get __proto__()>: function __proto__()
​​​​
<set __proto__()>: function __proto__()
​​
<prototype>: Object { … }
​
<prototype>: {…}
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toSource: function toSource()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
shares.js:161:12
Error while adding share - Error:  Error: "Request failed with status code 409"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
SideBarTabShare.vue:210
    addShare SideBarTabShare.vue:210
</details>

**Comment by dartcafe** [comment]
@maphy-psd Hmmm. Not reproducable here.

If you have access to the db, please check, 
* if the oc_polls_shares table contains the invited group,
* if the group has members,
* do all members have valid eMail addresses,
* is sending out invitations from individual users working?
