### ISSUE TITLE
[1.2.0 RC2] Autofocus and cursor pointer

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#827]
I tested the new 1.2.0 RC2. It is very good. But I have twi minimal enhancements.

1. If I create a public link to share the plus icon is not a pointer cursor:
![image](https://user-images.githubusercontent.com/1473674/74586234-e1a4cb00-4fe5-11ea-84d3-6075e3c0ceb0.png)

2. If I visit the shared link the autofocus is not on the username textarea:
![image](https://user-images.githubusercontent.com/1473674/74586257-157ff080-4fe6-11ea-9352-144f264d0004.png)

**Comment by dartcafe** [comment]
resolved in 1.3

**Comment by dartcafe** [comment]
Em. I think I dreamt about that. Still open.

**Comment by dartcafe** [comment]
I changed the link for creating a public share to a button. Fits better to an action like this IMHO.

**Comment by dartcafe** [comment]
I tried different approchaes, but I can't get the focus on this input field. Anyone who has a solution?

**Comment by v1r0x** [comment]
I can have a look at this tomorrow

**Comment by dartcafe** [comment]
It should work here: 
https://github.com/nextcloud/polls/blob/f878de9715b6b8891cade72ede259c7ae75d014b/src/js/components/VoteTable/VoteHeaderPublic.vue#L119-L128
But I get a JS error: 
```
Vue warn]: Error in nextTick: "TypeError: _this.$refs.userName is undefined"

found in

---> <VoteHeaderPublic> at src/js/components/VoteTable/VoteHeaderPublic.vue
```

Calling `$vm0.$refs.userName.focus()` in the js console works then (VoteHeaderPublic as $vm0).

I also tried to do this via a directive, but I get the same error. 

I guess, the modal component rendering is not ready, when calling from mounted(). Maybe @skjnldsv can explain, if you find no way.

**Comment by v1r0x** [comment]
Problem is the `v-if` together with vuex (if I read this correctly in different issues). I fixed it by adding a watcher to the `v-if` condition (`poll.id`) and then calling `this.setFocus()` instead of in `mounted()`.

```javascript
watch: {
	userName: function() {
            ...
	},
        'poll.id': function(newValue) {
            this.setFocus()
        }
},

mounted() {
    // removed this.setFocus()
},
```

@dartcafe Do you already have a branch or something for this issue or should I fix it?

**Comment by dartcafe** [comment]
https://github.com/nextcloud/polls/tree/publicLinkCursor adresses the other issue (pointer cursor). I also added a custom button component there.

**Comment by dartcafe** [comment]
> Problem is the `v-if` together with vuex

Ah, yes. I had some also, so I used v-show in some places because of that.

**Comment by dartcafe** [comment]
@v1r0x I wanted to test your solution and already applied it to the branch. Works perfectly 👍 Didn't want to rush things, but I was curious.
