### ISSUE TITLE
[1.2.0 RC2] Anonymous poll not saved

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#829]
If I check the checkbox "anonymous poll" and "hide names" the names will be hide. That works. If I reload the page the checkbox is not checked anymore but the function is working. It looks like the current status is not loaded correctly to check the checkbox if its activated

Steps to reproduce:
1. create a new poll
2. make is anonymous and hide names
3. reload the page an see the settings of it

![image](https://user-images.githubusercontent.com/1473674/74586379-2aa94f00-4fe7-11ea-826c-da8efdb408dd.png)

**Comment by dartcafe** [comment]
The full anonymous setting has no further function and will be removed in the next version.

**Comment by v1r0x** [comment]
@dartcafe Any reason why?

**Comment by dartcafe** [comment]
@v1r0x 
It makes no sense in the end. Owner and admin users could remove this setting and see the names. So it is is a misleading feature IMHO and prentents to give anonymity.

Anonymous polls are now anonymous to everyone when the anoymous flag is set. Admin users are treated as a normal user, unless he is the poll owner or the owner gave the permission to admins to edit the poll.

BTW: There is a bug in setting the edit permission for admins, if the owner is an admin user. Will fix this, when back from vacation (this evening).
