### ISSUE TITLE
[1.2.0 RC2] Icon not centered on public vote

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#832]
On public vote the user icon is not centered before the textarea

![image](https://user-images.githubusercontent.com/1473674/74586502-3f3a1700-4fe8-11ea-98a4-b47f95a2f51f.png)

**Comment by dartcafe** [comment]
The avatar is genereated fom the nextcloud-vue component. Nothing we can do here.
@skjnldsv I know, there was a discussion about that. Any solution for individual characters like J?

**Comment by dartcafe** [comment]
Just tested here.
![grafik](https://user-images.githubusercontent.com/26707476/74754073-5ccde180-5271-11ea-9ec2-889499716ee4.png)
looks good for me.

**Comment by dartcafe** [comment]
What browser are you using? OS?

**Comment by Dennis1993** [comment]
Windows 10 with Edge Chomium 80 (the new edge browser)

**Comment by dartcafe** [comment]
Hmmm... Edge in win 10: 
![grafik](https://user-images.githubusercontent.com/26707476/74805240-d5b95180-52e2-11ea-8cbc-5d36344ec2f7.png)

**Comment by dartcafe** [comment]
Ah. This is the public version: 
![grafik](https://user-images.githubusercontent.com/26707476/74805315-0600f000-52e3-11ea-93ce-c93786051741.png)
Icons are obviously generated a different way, for guests. But we cannot fix this here, because they are comming from core (via nextcloud-vue components).
