### ISSUE TITLE
can't create a (first) poll

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/polls#834]
### What is going wrong?
**Describe the bug**
i can't create a poll and the big spinner in the center of the screen keeps spinning forever.

**To Reproduce**
1. open the polls app
2. see the spinner spinning forever
3. everything else seems to appear properly, but if you try to click "create" nothing happens
4. btw: changing categories on the left seems to work... (at least the highlighting and the URL changes) but the spinner keeps going on.

**Expected behavior**
showing an empty list or a message like "nothing here to show, create a poll..." and most important **let me create a poll**.

### Information about your polls installation
**Polls version?** 1.1.6

**Fresh installation or update from a prior version (from which one)?**
update from prior versions: started around nextcloud 13 with the corresponding poll version

**How did you install this version?(Appstore or describe installation)**
appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
nextcloud

**Nextcloud/ownCloud version:** 16.0.8

**List of activated apps:**
different... this behavior appears on more than one instance.

**Nextcloud configuration:**
different... this behavior appears on more than one instance.

### Server configuration

**Operating system**:
ubuntu

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7.2

**Signing status:**
```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:**
also different... no and `OC_User_IMAP`

### Client configuration
**Device:**
at least desktop (didn't test an other client)

**Browser:**
firefox 72.0.2 (64-bit)

**Operating system:**
linux mint 18.3 (based on ubuntu 16.04)

#### Nextcloud log (data/nextcloud.log)
```
nothing interesting...
```

#### Browser log
```
TypeError: "t.list.filter is not a function"
    allPolls polls.js:41
    e vuex.esm.js:777
    h/</o[n]</< vuex.esm.js:95
    VueJS 3
    get vuex.esm.js:567
    r vuex.esm.js:924
    VueJS 3
    Navigation Navigation.vue:1
    VueJS 7
vue.esm.js:1897:12
TypeError: "t.list.filter is not a function"
    allPolls polls.js:41
    e vuex.esm.js:777
    h/</o[n]</< vuex.esm.js:95
    VueJS 3
    get vuex.esm.js:567
    r vuex.esm.js:924
    VueJS 3
    filteredList PollList.vue:82
    VueJS 3
    sortedList PollList.vue:97
    VueJS 3
    h PollList.vue:1
    VueJS 7
vue.esm.js:1897:12
```

### important note
- at nextcloud 17.0.3 (polls 1.1.6) everything works
- at nextcloud 16.0.8 (polls 1.1.6) i get this error
- <sub>at nextcloud 15.0.14 (polls 0.10.4) it also works</sub>

...everything tested on the same server, with the same client etc.

**Comment by dartcafe** [comment]
See #789 
Upgrade to a more recent NC version or wait until update to 1.3.0. Should be available at comming weekend.

**Comment by dartcafe** [comment]
correction. 1.3 is out.

**Comment by DJCrashdummy** [comment]
sorry for creating the duplicate! ...i focused too much on the list and the spinner, since the app loads (but not completely). :wink: 

i can confirm polls 1.3.0 works on both setups. :+1:

**Comment by dartcafe** [comment]
> sorry for creating the duplicate!

Don't worry. Happy, that it is fixed.
