### ISSUE TITLE
1.3.0: Somme poll problems....

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#851]
### What is going wrong?
**Describe the bug**

1. As you can see the crosses in the 2nd line are different (this is a external user)
2.[fixed] i cant change the April 25. checkbox any more. it simply doesnt change, doenst matter how many times i click on it. any other checkbox can be changed!
3. [fixed] also on the April 25. the "maybe" is counted twice but there is only one "maybe" vote

**Screenshots**
![Bildschirmfoto vom 2020-02-27 18-12-49](https://user-images.githubusercontent.com/37833326/75468292-47ea0000-598d-11ea-93c1-deb819ece08b.png)
.
### Information about your polls installation
**Polls version?** 
1.3.0

**Fresh installation or update from a prior version (from which one)?**
update

**How did you install this version?(Appstore or describe installation)**
Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud**

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.1

**List of activated apps:**
```
Enabled:
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.9
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.2.1
  - files_external: 1.9.0
  - files_external_gdrive: 0.4.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - music: 0.13.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocsms: 2.1.7
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/h.de",
        "trusted_domains": [
            "e"
        ],
        "trashbin_retention_obligation": "auto",
        "version": "18.0.1.3",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "updater.release.channel": "beta",
        "theme": "",
        "activity_expire_days": 90,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "569fe2a30a4694f619cf3c388873ecc6",
        "installed": true,
        "app_install_overwrite": [
            "calendar",
            "mail",
            "ocsms",
            "caniupdate",
            "audioplayer",
            "files_external_gdrive",
            "polls",
            "spreed",
            "contacts",
            "bruteforcesettings",
            "files_rightclick",
            "talk_simple_poll"
        ],
        "mysql.utf8mb4": true
    }
}

```

### Server configuration

**Operating system**:
Ubuntu 19.10

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.2

**Signing status:**
```
No errors have been found.
```

### Client configuration
**Device:**
Laptop

**Browser:**
FF 73.0
Chromium Version 80.0.3987.122

**Comment by dartcafe** [comment]
Can you list the entries from the oc_poll_votes table in your db?

**Comment by g6094199** [comment]
`MariaDB [nextcloud]> SELECT * FROM oc_polls_votes;
+-----+---------+--------------------+----------------+---------------------+-------------+
| id  | poll_id | user_id            | vote_option_id | vote_option_text    | vote_answer |
+-----+---------+--------------------+----------------+---------------------+-------------+
......
| 301 |      17 | Grumpy             |              0 | 2019-10-05 08:00:00 | yes         |
| 302 |      17 | Grumpy             |              0 | 2019-10-12 08:00:00 | yes         |
| 303 |      17 | Grumpy             |              0 | 2019-10-19 08:00:00 | yes         |
| 304 |      17 | Grumpy             |              0 | 2019-10-26 08:00:00 | yes         |
| 305 |      20 | xxx    |            157 | 2020-01-04 17:00:00 | yes         |
| 306 |      20 | xxx    |            161 | 2020-01-05 11:00:00 | yes         |
| 307 |      20 | xxx    |            158 | 2020-01-11 17:00:00 | yes         |
| 308 |      20 | xxx    |            162 | 2020-01-12 11:00:00 | yes         |
| 309 |      20 | xxx    |            159 | 2020-01-18 17:00:00 | yes         |
| 310 |      20 | xxx    |            163 | 2020-01-19 11:00:00 | yes         |
| 311 |      20 | xxx    |            160 | 2020-01-25 17:00:00 | yes         |
| 312 |      20 | xxx    |            164 | 2020-01-26 11:00:00 | yes         |
| 313 |      22 | xxx    |            182 | 2020-03-28 16:00:00 | yes         |
| 314 |      22 | xxx    |            183 | 2020-04-04 15:00:00 | yes         |
| 315 |      22 | xxx    |            184 | 2020-04-11 15:00:00 | yes         |
| 316 |      22 | xxx    |            185 | 2020-04-18 15:00:00 | yes         |
| 317 |      22 | xxx    |            186 | 2020-04-25 15:00:00 | maybe       |
| 318 |      22 | xxx    |            186 | 2020-04-25 15:00:00 | maybe       |
| 319 |      22 | SSS             |            185 | 2020-04-18 15:00:00 | yes         |
| 320 |      22 | SSS             |            184 | 2020-04-11 15:00:00 | no          |
| 321 |      22 | SSS             |            187 | 2020-04-25 15:00:00 | no          |
+-----+---------+--------------------+----------------+---------------------+-------------+
246 rows in set (0.04 sec)
``

XXX is my user (1st line)
SSS is the 2nd line

**Comment by dartcafe** [comment]
> | 317 | 22 | xxx | 186 | 2020-04-25 15:00:00 | maybe |
> | 318 | 22 | xxx | 186 | 2020-04-25 15:00:00 | maybe |

For some reason, there is an duplicate entry in the table, which I assume causes this behavior. Please delete one of them.

**Comment by g6094199** [comment]
jep. saw this also. the question is how did it get there?! there seem to be a bug somewhere regarding this.

**Comment by v1r0x** [comment]
You're refering to the black x icons? they are fixed in #844

**Comment by g6094199** [comment]
ok ;-)

**Comment by dartcafe** [comment]
> the question is how did it get there?!

Don't know, parallel voting in two instances? Anyway, we have to make the combination userId, OptionText, timestamp and pollId unique (via db index?) and add a proper error handling for that. Same to do for poll options (pollId and option) to avoid duplicates.

**Comment by g6094199** [comment]
> > the question is how did it get there?!
> 
> Don't know, parallel voting in two instances? 
No

**Comment by dartcafe** [comment]
> No

So, no idea. Maybe a double click. However. Closing this because I created #856
