### ISSUE TITLE
LogIn Option

### ISSUE THREAD

**Issue by achlys75** [nextcloud/polls#852]
**Is your feature request related to a problem? Please describe.**
When not logged there is no possibility to do so. You are forced to choose a nickname. To log in with my nextcloud username I have to do so separately.

**Describe the solution you'd like**
A log in option beneath the 'choose a name' panel.

**Describe alternatives you've considered**
Loading the main site.

**Additional context**
-
Poll Ver:  1.3.0
Nextcloud Ver: 17.0.3

**Comment by dartcafe** [comment]
Good point. Added a link with redirect to the public vote page.
![grafik](https://user-images.githubusercontent.com/26707476/75628677-8aa11780-5bdb-11ea-89f0-f60a9689b940.png)
