### ISSUE TITLE
subscribe to updates via email - (public) participants

### ISSUE THREAD

**Issue by tessus** [nextcloud/polls#853]
**Is your feature request related to a problem? Please describe.**
I often create public polls where people, who do not have an account on my Nextcloud instance can also vote. This works splendidly. However, these users cannot subscribe to any changes via email. This means they have to check manually, whether there are any updates.

**Describe the solution you'd like**
There could be a button or a checkbox `subscribe to updates`, which allows the public user to enter an email address. Please note, this is for participants, not for the creator of the poll.
The email should contain who voted for what (date or text) and the timestamp of the click/vote.
An overview of all possible choices would be nice, but is not a necessity.
(I'm not talking about a matrix (users / choices)).
An admin option could also be implemented to enable/disable this feature.

**Describe alternatives you've considered**
There are no alternatives, except maybe using Doodle, which is rather counterproductive.

**Additional context**
This is one of the best Nextcloud apps, I've encountered so far. It's intuitive, takes care of local timezones, and even allows comments for public users. Fantastic job you did there.
I have also checked previous issues (open and closed) but none of them seem to convey the same use-case.

**Comment by jacotec** [comment]
That's exactly what I'm looking for as well!

I think the eMail field should be presented in the same popup which appears when someone opens the public link (where you need to enter your Username for that Poll), so both can be entered at the same time.

The personal link should be emailed in that case to the participant along with the description of the vote.

To make that even more confortable:
- Giving their email address for participants should be able to be configured as mandatory for the poll admin
- In the "Enter Username" / "Enter eMail" popup dialog a checksum "subscribe to this poll" can give the option to get updates by email or not
