### ISSUE TITLE
Add unique index for options and votes

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#856]
To avoid duplicates, unique indexes should be added to the db:
* oc_polls_votes: `poll_id`, `user_id`, `poll_option_text`
* oc_polls_options: `poll_id`, `poll_option_text`, `timestamp`

@v1r0x Can you add a migration, i get mad with this queryBuilder.
I can add the error handling afterwards, if you don't want to.

**Comment by dartcafe** [comment]
Do we need an error handling inside the migration, if duplicates alredy esist?

**Comment by v1r0x** [comment]
Yes, I think we should drop duplicates in the migration. I don't have much experience with nc migrations, but I'll try my best.

**Comment by dartcafe** [comment]
@v1r0x in the last migration I added a function to remove duplicates, I think this can be adopted here. Do you have time and a mood to develop this?
