### ISSUE TITLE
Poll duplication - restriction

### ISSUE THREAD

**Issue by ArminP160** [nextcloud/polls#858]
Hi,

when we create a poll as admininstrator, automatically it is possible for any user to duplicate this poll and create further ones. Are we doing something wrong - we want to avoid and stop this.

Armin

**Comment by dartcafe** [comment]
I edited your comment. The unfilled form may be misleading. 

The possibility to clone a poll by users who are allowed to create a poll is by intention. Why do you want to stop that?

**Comment by ArminP160** [comment]
Thank you for your reply. The question is correct you raise - for those "allowed" Sure - for those allowed we would like to have this option active - but most are not allowed - but where can I restrict this. So where can I say "Creation of a poll - yes / no"

**Comment by dartcafe** [comment]
At the moment, every user can create a poll. To restrict these rights, we need to add administrative function. This is still a to do.

**Comment by dartcafe** [comment]
closing in favour to #1106
