### ISSUE TITLE
mark option as chosen

### ISSUE THREAD

**Issue by tessus** [nextcloud/polls#859]
**Is your feature request related to a problem? Please describe.**
After a poll has expired or is over, there's no way to mark the option that was picked by the poll owner.

**Describe the solution you'd like**
I would like the possibility to set an option as chosen. In case #853 is considered, an email should be sent out to the participants with the result. 

There are a few ways to accomplish this. Here's one idea:

![image](https://user-images.githubusercontent.com/223439/75687978-a86a8d00-5c6c-11ea-9023-cb963ca03902.png)

After setting one option as chosen, it should be presented to the user somehow. An example below:

![image](https://user-images.githubusercontent.com/223439/75688109-df40a300-5c6c-11ea-886a-204a88e3cba0.png)

One could also dim the other options. I'm not a designer, so someone with more experience should decide on a proper presentation.

**Describe alternatives you've considered**
Currently the only way to convey this info is to modify the description to indicate the chosen option (date or text).

**Comment by dartcafe** [comment]
Duplicate of a long standing request #136.  Will be solved in one of the next releases.

**Comment by tessus** [comment]
Sorry, I was searching for `chosen` when I opened the issue.

The word "choosen" does not exist. Please change the issue title accordingly.
