### ISSUE TITLE
1.3.0: wrong date order

### ISSUE THREAD

**Issue by g6094199** [nextcloud/polls#861]
### What is going wrong?
**Describe the bug**
There is a wrong date order

**To Reproduce**
-create a poll
-release the poll to the public
-user vote-
-add another date (duplicated date with different time)-> dates get added in wrong order

**Expected behavior**
Even when added after the release of the pool additional dates should be ordered in the right way

**Screenshots**
![Bildschirmfoto vom 2020-03-05 12-10-44](https://user-images.githubusercontent.com/37833326/75976709-3ea3ea80-5edb-11ea-85ea-f11886121cfd.png)

### Information about your polls installation
**Polls version?** 
1.3.0

**Fresh installation or update from a prior version (from which one)?**

**How did you install this version?(Appstore or describe installation)**

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud**

**Nextcloud/ownCloud version:** 18

**Comment by dartcafe** [comment]
I have no idea, how this could happen. Dates are ordered on their timestamp.
Can you post the content of the oc_polls_options table with the poll_id of this poll?

**Comment by g6094199** [comment]
| 194 |      23 | 2020-04-12 10:00:00 | 1586685600 | 1586080800 |
| 195 |      23 | 2020-04-19 10:00:00 | 1587290400 | 1586685600 |
| 196 |      23 | 2020-04-26 10:00:00 | 1587895200 | 1587290400 |
| 198 |      23 | 2020-04-20 10:00:00 | 1587376800 | 1586772000 |
| 199 |      23 | 2020-04-05 10:00:00 | 1586080800 | 1586080800 |
| 200 |      23 | 2020-04-12 16:00:00 | 1586707200 | 1586707200 |
| 201 |      23 | 2020-04-19 16:00:00 | 1587312000 | 1587312000 |
| 202 |      23 | 2020-04-26 16:00:00 | 1587916800 | 1587916800 |
| 203 |      23 | 2020-04-05 16:00:00 | 1586102400 | 1586102400 |
+-----+---------+---------------------+------------+------------+

**Comment by dartcafe** [comment]
Did you create the poll with a version before 1.3 and add the new options after the update?

**Comment by g6094199** [comment]
yes!

**Comment by ctueck** [comment]
The same happened to me, same NextCloud and Polls app version as @g6094199 .

Only difference here: I did *not* create the poll in an older version, but everything was under version 1.3.0.

The obvious workaround fixed it easily, though:

```sql
update `[prefix]_polls_options` set `order` = `timestamp` where `poll_id`= [poll ID]
```
