### ISSUE TITLE
Reverts to default language

### ISSUE THREAD

**Issue by jdtechdoc** [nextcloud/polls#863]
Public polls are presented in English rather than in the language of the Nextcloud instance. Any chance to change this behaviour?

**Comment by dartcafe** [comment]
Yep. Change the priority in your browser settings to your preferred language. AFAIK there is no default language for the site. polls uses the language, defined by the core.

**Comment by jdtechdoc** [comment]
Thanks. Honestly, I didin't come across such setting until today. But even when setting Firefox to German, the poll text remains English. I also use "default_language='de'" in Nextcloud config. No change at all.

**Comment by dartcafe** [comment]
I use FF too, and changing the default language results in presenting the public page as expected (german or english). Tested in anonymous window.

**Comment by jdtechdoc** [comment]
Now it does. 
I didn't notice I have to change the order of the languages there. Thanks for your patience, René.
