### ISSUE TITLE
Loading the poll list is very slow

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/polls#864]
### What is going wrong?
**Describe the bug**
When loading the poll app it takes up to 20 seconds for the list to be fully loaded. The main window just shows the standard spinner in this time. Other apps load instantly. Loading a single poll directly shows no delay.

**To Reproduce**
1. Call the poll app

**Expected behavior**
The poll list loads without delay

**Screenshots**

![2020-03-06_13-30-polls](https://user-images.githubusercontent.com/8102905/76083806-b3942480-5fae-11ea-9ee0-83ddec767323.png)

### Information about your polls installation
**Polls version?** 1.3
**Fresh installation or update from a prior version (from which one)?** Update

**How did you install this version?(Appstore or describe installation)** occ update for the latest version

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?** Nextcloud

**Nextcloud/ownCloud version:** 16.04

**Comment by dartcafe** [comment]
138 ms here (7 polls). How many polls do you have on the site? 
I think, we could increase loading by optimize the loading of the complete poll list. Needs some refactoring.

**Comment by brtptrs** [comment]
As admin I count about 50. That is "All" + "Deleted"
I'm not sure how accurate that is, at the moment I don't have access to the db to verify. Is there a way to verify that from the gui?

One more point: Once loaded, moving between the different sections is normal. It seems to be a back-end problem.

**Comment by gerhardbeck** [comment]
I'm working with @brtptrs and can confirm: Once loaded all runs smoothly. But the loading takes a long time

**Comment by dartcafe** [comment]
Loading times increase with the number of polls, options and participants. Server and DB performace are additionally players here.

But there is some room for improvement. The current implementation is a lazy one. ;-)

Currently the polls and their options and votes are loaded from the vue app recursively with a lot of backend calls. We have to move the loading to the backend, so we can get the complete list on the server side and avoid multiple API calls.

> Once loaded, moving between the different sections is normal.
That's because, once the polls are loaded, everything is handled on the JS side and then API calls are just a few.

**Comment by dartcafe** [comment]
I have to correct myself. Loding the polls is done in the backend completely. I already changed this. Allthow I raised the number of polls to nearly 50 the loading time was aproximate 170 ms. What db system are you using?

**Comment by dartcafe** [comment]
Could you replace lib\Controller\PollController.php with the version from [this branch](https://github.com/nextcloud/polls/tree/checkLoadingTimes)?
I added some time capturing and logging on loading polls.

https://github.com/nextcloud/polls/blob/80187f5e20ecb046b5ae8e7cd9cff6a851004aa2/lib/Controller/PollController.php#L115-L145

Check the result in admin's log with debug enabled. I want to know, where the time is spent inside this method.

**Comment by brtptrs** [comment]
Thanks for the effort. I'll try this version and get back to you. It might only be tomorrow. I'm out of office at the moment.

**Comment by brtptrs** [comment]
I'm missing something. 
I don't see any debugging info after doing this:
1) Copy PollController.php from your branch to our live server
2) Set 'debug' => true in the NC config.php
3) Call "apps/polls/list/all" and wait the 20 s for the page to load
4) Watch the log entries on "settings/admin/logging" with "Debug" selected.
5) Download the log file an search for "polls"

Nothing. I guess I need some coffee or some help.

**Comment by dartcafe** [comment]
Did you set `'loglevel' => 0`?

`'debug' => true` is not needed IMHO, it just creates additional information.

See: https://docs.nextcloud.com/server/18/admin_manual/configuration_server/config_sample_php_parameters.html

You should find something like this:
![grafik](https://user-images.githubusercontent.com/26707476/76346099-be2f2080-6304-11ea-8b46-da28e4397224.png)

**Comment by brtptrs** [comment]
This is what I see. Seems odd that the output comes twice. I've double checked, it comes twice from a single page reload.

The output also comes right at the end just before the page is rendered. 

![image](https://user-images.githubusercontent.com/8102905/76541392-cfeb0200-6483-11ea-9d39-c42bf2699d14.png)

**Comment by brtptrs** [comment]
We've just upgraded to NC18. Unfortunately the Problem still exists. If anything loading the list takes slightly longer.

**Comment by dartcafe** [comment]
This is not related to the NC version. Could you post the debug output, when you open a single poll from the command line? i.e. /index.php/apps/polls/vote/1

Reason for the double output: Loading the list is initiated twice, once from the navigation and a second time by mounting the polls list. Maybe, this causes problems.
