### ISSUE TITLE
Hide public polls

### ISSUE THREAD

**Issue by gerhardbeck** [nextcloud/polls#865]
My Nextcloud is part of a company cloud. Lot of people start public polls, sometimes unintentionally, which are not interesting at all.
I want to delete them or hide them

great would be the possibility to hide public polls for oneself.

**Comment by dartcafe** [comment]
Adding configurations for this would increase complexity (at least for tests) by generating limited value. What about sorting the navigation sections in another way. We could put "all polls" to the end of the list and change the secion "participated" to "relevant to me" and list all polls, where the user paticipated, is invited or is owner. "relevant to me" would then be first, followed by "my polls", "all polls" after "hidden polls". 

Thinking about this: Is "hidden polls" neccesary? I think, we can remove this section.

**Comment by dartcafe** [comment]
Mockup:
![grafik](https://user-images.githubusercontent.com/26707476/76106744-c40cc500-5fd7-11ea-9337-1424578dba32.png)

**Comment by gerhardbeck** [comment]
Seems like an easy but useful change.
I'd like to think about the labels. There are, at least in my organisation, a lot of users which just start using olls and are easily confused.
Therefore "participated" seems better than "relevant"
I'm also wondering wheter "public polls" is necessary. Personally "relevant", "public" and "all" would be enough.

**Comment by herrmannsdorfer** [comment]
I would add a section "Active polls" to the list. We have a lot of expired polls which are not deleted or archived. The make other lists unclear or confusing.

**Comment by dartcafe** [comment]
Changed poll filters in the navigation:
![grafik](https://user-images.githubusercontent.com/26707476/77856381-09976900-71f7-11ea-8840-044caaffe5aa.png)

**Comment by gerhardbeck** [comment]
Just got the update. Thanks to @dartcafe , great!
