### ISSUE TITLE
Increase description size

### ISSUE THREAD

**Issue by tristanlins** [nextcloud/polls#867]
**Is your feature request related to a problem? Please describe.**

Sometimes I create a poll with detailed description (length > 1000 characters).
But the database field is limited to 1000 characters.

No error is shown, if the description is too long.
The update simply fails and there is only an xhr error in the devtools.

**Describe the solution you'd like**

Change the type to `TEXT`.

```sql
alter table polls_polls change column description description text;
```

**Describe alternatives you've considered**

Show a warning if the update failed and limit the textarea to 1000 chars.

**Comment by dartcafe** [comment]
Added migration for Version 1.4
