### ISSUE TITLE
Improve the clunky styling - or allow settings for size etc

### ISSUE THREAD

**Issue by rogercreagh** [nextcloud/polls#872]
The current look of the polls is very clunky - unnecessarily large font size and icons.
(naturally this is a matter of opinion, but it doesn't look neat to me)
A particular problem is that the text for labels in the header can easily overflow the column width like this:
![image](https://user-images.githubusercontent.com/44980188/77060377-65304e00-69d0-11ea-9197-18f7cd29d41f.png)
Not only is the text in the header overflowing but note how the icons [x] etc are out of proportion with the user name text.

Now it is possible to fix this with css overrides using the css app for theming - so long as you use the !important (which is a bit naff) - but it would be much better to start with something better proportioned, and in an ideal world provide app settings to set the size of icons and text in the table.

Here's a sample css and an image of the result.
```
/*** improvements to polls layout ***/
.vote-table-item > .icon {
    min-width: 20px !important;
    min-height: 20px !important;
    width: 20px !important;
    height: 20px !important;
}
.vote-header .date-box .month {
    font-size: 1.1em !important;
}
.vote-header .date-box .day {
    font-size: 1.3em !important;
}
.vote-header .date-box .dow {
    font-size: 1.1em !important;
}
.vote-header .text-box {
    font-size: 1.0em !important;
}
```
![image](https://user-images.githubusercontent.com/44980188/77060798-16cf7f00-69d1-11ea-8f0d-40b1cfb2c526.png)

Isn't that nicer? (note the css above also fixes the clunky nature of the date headers, there are probably more things that could be improved.)

Any chance of 
1. changing the default values embedded in the code
2. providing some settings (to be specified) to set the size required.

NB the screenshots above are displaying about half size on my monitor - in real life the current defaults look awful (and no, I haven't got my browser zoom set away from its null position)

**Comment by dartcafe** [comment]
Good approach. But we should have in mind, that voting could be done on  a touch device (i.e. a tablet) , so the action items should have a touch friendly size.

**Comment by rogercreagh** [comment]
> Good approach. But we should have in mind, that voting could be done on a touch device (i.e. a tablet), so the action items should have a touch friendly size.

Which of course is what the `@media` tag is for. Either wrap my suggestion in an `@media screen and (min-width: 700px)` or vice versa according to what else is going on elsewhere in the stylesheet. Absolutely no point in trying to use the same styling for both phones and proper screens - the result will look awful - as it does!

**Comment by dartcafe** [comment]
I partially added your suggestions, but changed the icon size to 30px.
