### ISSUE TITLE
Unshare a shared poll

### ISSUE THREAD

**Issue by DominikWA** [nextcloud/polls#878]
I have many shared polls from other users, but i can not unshare/delete or hide them. The list of polls is getting to large for me to have a good workflow.

An other idea would be to move expired polls in a separate folder, like the public polls or other folders.

**Comment by dartcafe** [comment]
Something, we didn't have in mind. In #875 we changed the folders (filters). I think, the folder "relevant" could ignore expired polls and we can add explicit folder for expired polls. 
Maybe devided in "recently expired" and "old polls"

**Comment by dartcafe** [comment]
Changed navigation and added a section for expired polls. The section relevant ignores expired polls. Other sections will still display expired polls.

**Comment by dartcafe** [comment]
@DominikWA Does the new filtering solve this problem? Can be tested in latest beta.
