### ISSUE TITLE
Admin should not be able to see users' polls

### ISSUE THREAD

**Issue by meaz** [nextcloud/polls#880]
### What is going wrong?
As an admin, it should not be possible to see users' polls, I think it is a privacy issue.

**To Reproduce**
1. Create a poll as user, set as "Hidden to other users"
2. Connect as an admin
3. In "All polls", you can see the user poll

**Expected behavior**
As an admin, users polls should not be visible.

### Information about your polls installation
1.30
Fresh installation
Appstore

### Information about your Instance of Nextcloud/ownCloud
Nextcloud 18

**Comment by dartcafe** [comment]
Admins are treated as normal users, unless you allow them to edit the poll. 
![grafik](https://user-images.githubusercontent.com/26707476/78419523-f0ebe080-7646-11ea-97e7-3346565003f3.png)

**Comment by meaz** [comment]
Thank you, that was my mistake.
