### ISSUE TITLE
Directly share polls by email (like in files)

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#885]
**Is your feature request related to a problem? Please describe.**
I want to invite known people, which are no users of my Nextcloud, to a poll. Right now the invitation needs to be sent manually to any participant by individual emails containing the public link.

**Describe the solution you'd like**
It would be very comfortable to have the same behavior as sharing files in nextcloud: Just enter the email address in the "Share" dialog in the poll app and then just add the share.
Poll should then send an eMail to the user with the poll details and the personal link to make and maintain the vote.

As an option it would be also great to have the ability to add a guest account (like for files sharing) if the "guests" app is installed.

**Additional context**
![image](https://user-images.githubusercontent.com/3321655/78561167-8b028300-7817-11ea-8dc9-f3a4d9d6d779.png)

**Comment by dartcafe** [comment]
see here: #822. Version 1.4 comming up shortly
