### ISSUE TITLE
Beta 1.4.2 (beta3) published

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#886]
See current release: https://github.com/nextcloud/polls/releases
Changelog (https://github.com/nextcloud/polls/blob/master/CHANGELOG.md)
issues and PRs (https://github.com/nextcloud/polls/milestone/26?closed=1)

**Comment by dartcafe** [comment]
@v1r0x Since there are no more critical issues, I think, we could release version 1.4. 

Any concerns?

**Comment by v1r0x** [comment]
Yes, I'm fine with that :+1:

**Comment by dartcafe** [comment]
I raised the Version number to 1.4.2 for the release and updated the changelog. There were no more changes besides transifex since beta2.

**Comment by vieta-123** [comment]
Hello,

is there any timetable for when the final release of version 1.4.2 is going to happen?

Kind regards

**Comment by v1r0x** [comment]
I'm going to release it this week (hopefully). Sorry for the delay!

**Comment by dartcafe** [comment]
No problem, gave me time for two bug fixes. If I have time enough, I can fix #909 before the release. So, end of this week would be a good moment. NC19 will probably not be released until then (don't know the road map).

**Comment by adymorz** [comment]
I think I found a showstopper: https://github.com/nextcloud/polls/issues/910

**Comment by brtptrs** [comment]
I've just tested Beta3 on our test-server and everything seem to work.
The default settings for new polls fit our  needs much better.
I also find the whole app much more intuitive than in the past.
Thank you!!

**Comment by dartcafe** [comment]
@brtptrs Thanks for testing and your feedback. Release will be soon, I think.

**Comment by brtptrs** [comment]
We are still suffering from:
https://github.com/nextcloud/polls/issues/864
Therefore I'm thinking of rolling out this beta (at my own risk obviously) on our live system. 
One question: 
_**Should**_ the upgrade path from (this) beta to the final 1.4.3 be save?

**Comment by dartcafe** [comment]
I do not expect any changes between the latest beta and the release (except some more translation progress).

**Comment by v1r0x** [comment]
Finally done. Thanks again for all contributions and fixes! Especially @dartcafe 🎉 

And sorry again for the delay.
