### ISSUE TITLE
Doesn't work together with AppOrder app

### ISSUE THREAD

**Issue by normen** [nextcloud/polls#888]
### What is going wrong?
When using the AppOrder app in NextCloud to change the order of the main app toolbar items the icons are still in default order when selecting the Polls App.

**To Reproduce**
1. Install nextcloud docker image
2. Install Polls app in NextCloud
3. Install AppOrder app in NextCloud
4. Change the default order of apps
5. See that the app order changes on most pages (e.g. `apps/files`) 
6. See that the app order is still default oder on the polls page (e.g. `apps/polls/list/all`)

**Expected behavior**
The settings configured in AppOrder should be used on the Polls page.

**Screenshots**
See a Video of the issue: https://youtu.be/hd1uhKGgNwo

### Information about your polls installation
**Polls version?** (see apps page)
1.3.0
**Fresh installation or update from a prior version (from which one)?**
Fresh install
**How did you install this version?(Appstore or describe installation)**
Appstore
### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
NextCloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18

**Comment by dartcafe** [comment]
@juliushaertl Any idea, why this happens?

**Comment by Lockorocko** [comment]
Have the same issue :/ I installed nc normally (without docker).

**Comment by juliushaertl** [comment]
I think that is an apporder issue where we [use the href](https://github.com/juliushaertl/apporder/blob/master/js/apporder.js#L12) of the navigation item and that somehow interferes with the subroute /list/all, but I haven't looked into it in detail yet. Is there any error in the browser console when opening the polls page?

**Comment by Lockorocko** [comment]
My console displays this error:
![image](https://user-images.githubusercontent.com/42206677/84652254-a53d9900-af0b-11ea-8216-0eda0cda251b.png)

**Comment by Phil1988** [comment]
I have the same issue.

Console shows these:
![grafik](https://user-images.githubusercontent.com/6054234/88372926-2869ce80-cd97-11ea-9cec-cd1c291e58d8.png)

Its a "non docker" installation of nextcloud.
Polls v1.4.3 on NC v18.0.7.
Several (also 3rd party) nextcloud-apps running. 
Only polls has this issue.

Would be great if someone can fix it :)

**Comment by etcy** [comment]
I'm running NC19 with newest version of both App Order and Polls.
The problem still exists. And yes, seems like it only happens with Polls.

Please someone...fix this!

**Comment by philipreimer** [comment]
Still not working with NC 18.0.9 (snap) and NC 19.0.2

**Comment by juliushaertl** [comment]
So I actually cannot reproduce this, having a custom order works fine with latest master
![image](https://user-images.githubusercontent.com/3404133/92376396-cecd2180-f102-11ea-9600-cbfcd3029ebb.png)

**Comment by Phil1988** [comment]
So might it fix it, if we uninstall and install after that back again?

I cant test it right now but I will report back in a few days.
Last time I tested it (like 14 days ago) it didnt work.

**Comment by philipreimer** [comment]
I have disabled and removed Polls. Then re-installed it - latest version 1.4.3 - into NC Snap 18.0.9 RC1 Build:2020-09-06T23:54:01+00:00 5056261850e1dfd38d3d3b24bb7b6d285f957007 with latest App Order version 0.11.0.

As you can see from the screenshots below navigating to Polls app does completely disable the App Order settings:
* apps are completely out of order
* app "Keyweb" (the third app icon) is visible, although it has been deactivated in App Order settings

![files](https://user-images.githubusercontent.com/5737222/92393609-6f7e0a00-f120-11ea-8d46-e4a09178590c.png)

![polls](https://user-images.githubusercontent.com/5737222/92393618-71e06400-f120-11ea-9874-59d5f3da4b15.png)

I get the following exception in the browser console:

```
Uncaught Snap's element argument does not exist. snap.js:506:20
    s snap.js:506
    exports snap.js:510
    J init.js:211
    <anonym> main.js:36
    jQuery 7
    Webpack 6
```

**Comment by juliushaertl** [comment]
Does it work if you change the order in the apporder settings to something different and back?

**Comment by philipreimer** [comment]
Nope

**Comment by juliushaertl** [comment]
Any chance for a test account where this issue is reproducible? Feel free to mail credentials to the address in my github profile.

**Comment by dartcafe** [comment]
I can reproduce this and created an account for you.

**Comment by dartcafe** [comment]
Funny. I cannot reproduce this behavior on another instance on NC20 with the current dev version of polls.

**Comment by Phil1988** [comment]
Well my NC was on 18.0.5.
I deactivated and deleted polls and reinstalled it (v1.4.3).
Same Problem

I updated NC to 18.0.9 an did the same as above with the same result.
I did update NC to 19.0.3 an did the same as above with the same result.

**Comment by juliushaertl** [comment]
Might be the diff between the latest polls release and master then? I didn't test the release yet to be honest.

**Comment by dartcafe** [comment]
@juliushaertl Maybe, but I have no explanation. Needs more observation.

**Comment by dartcafe** [comment]
After updating to 1.5.4 the icons behave as expected, when defining the app order. But I have still no explanation.

NC 19.0.3 with AppOrder 0.11.0 and Polls 1.5.4. 

Someone can confirm?

**Comment by normen** [comment]
Yes, it seems to work, same combo of NC 19.0.3, AO 0.11.0 and Polls 1.5.4

**Comment by dartcafe** [comment]
So, I think magic happend.

**Comment by Phil1988** [comment]
I can also confirm this.

NC v19.0.3 and Olls v1.5.4 works now.

**Comment by philipreimer** [comment]
With NC 19.0.4, AppOrder 0.11.0 and Polls 1.5.4 the app order is also working as expected now.
