### ISSUE TITLE
URLs in new activity notification mails do not respect 'overwritehost', and possibly other 'overwrite' configuration parameters

### ISSUE THREAD

**Issue by Zepmann** [nextcloud/polls#891]
See the [Nextcloud documentation concerning proxy configuration](https://docs.nextcloud.com/server/18/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurationsl).

Expected behavior:
Emails containing notifications for new activity use overwritehost and similar values to construct the URL to the relevant poll whenever these values are defined.

Actual behavior:
Emails containing notifications for new activity ignore the overwritehost value and possibly other values. The only observation is that overwritehost is ignored. The result is that the constructed URL contains the listening IP address of the web server and internal port number.

Suggested fix:
Use the overwrite values whenever they are defined.

**Comment by dartcafe** [comment]
Do you have an actual example? 
* which notification
* which link is wrong
* how should it look like

I am wondering, if can change anything here inside the app, because URLs are constructed via core functions. Config params are not used or individually respected by the app in any way.

**Comment by Zepmann** [comment]
> Do you have an actual example?
> 
>     * which notification

As I wrote:
> Emails containing notifications for new activity

>     * which link is wrong

It concerns the 'Go to poll' link in the noted email.

>     * how should it look like

Example of what the link is now:
```
https://192.168.1.1:1443/index.php/apps/polls/vote/3
'''

Example of what the link should look like:
```
https://domain.example/index.php/apps/polls/vote/3
```

> I am wondering, if can change anything here inside the app, because URLs are constructed via core functions. Config params are not used or individually respected by the app in any way.

Nextcloud's regular 'a file has been shared with you' notifications do contain correct links, since these do respect 'overwritehost'.

**Comment by DBJRdev** [comment]
We may be able to add details: 

1) our Nextcloud is configured to omit the index.php in the URL. 
2) System emails with the subject "Umfragen App - Neue Aktivität" (Polls app - new activity) have a button "Zur Umfrage gehen" (go to poll), which contains the index.php -> and leads to a blank page. 
3) When you take out the index.php in the link manually, the correct poll appears.

Nextcloud 19.0.3, Polls 1.4.3

**Comment by SprickW** [comment]
I've got a problem with this issue as well and I think running NC behind a reverse proxy is pretty normal, especially for SMEs. 

I also found, thas the polls version available within NC 19.0.3 seems to be pretty old (1.4.3.).

**Comment by dartcafe** [comment]
We take the host's base URL from the core system, so I have no idea how to get the configured domain ATM. 

@nextcloud/server-triage Any hint, how to do that? 

Example of link generation
https://github.com/nextcloud/polls/blob/b17ebbdfbb232d0e1253830886416b2fba80eb62/lib/Service/MailService.php#L263-L267

**Comment by dartcafe** [comment]
> I also found, thas the polls version available within NC 19.0.3 seems to be pretty old (1.4.3.).

Release 1.5.4 is currently not yet available in the appstore. This depends of the availability of @v1r0x, who's time is currently rather limited. Release will be available as soon he is able to to this. Take the relase here from the release page, if you don't want to wait.

**Comment by v1r0x** [comment]
Sorry for the delay. But I uploaded it yesterday :wink: 
Should have informed you about that :sweat_smile:

**Comment by Zepmann** [comment]
This issue is still valid for version 1.5.4.

For anyone who wants to solve this, compare the function used by Polls to generate a 'Go to poll' URL in mails with Nextcloud's own 'a file has been shared with you' mails. The former does it wrong. The latter does it correctly.

**Comment by dartcafe** [comment]
> This issue is still valid for version 1.5.4.

Yes, that's why this issue is still open.

> For anyone who wants to solve this, compare the function used by Polls to generate a 'Go to poll' URL in mails with Nextcloud's own 'a file has been shared with you' mails. The former does it wrong. The latter does it correctly.

The question is, why does the core function not do what is expected. If it's a bug in polls or in the core has to be evaluated.

**Comment by dartcafe** [comment]
> Sorry for the delay. But I uploaded it yesterday 😉
> Should have informed you about that 😅

😆 Had have to check this before... Great and Thanks. Are you available for bug fix releases?

**Comment by Zepmann** [comment]
Why was my previous reply marked as off-topic? It confirmed that the issue is still valid and was not solved due to other changes in newer releases.

More information:
For some information `overwrite.cli.url` in config.php is used by Polls. I think this is not the fault of Polls itself, but due to that Nextcloud's cron job function can run in CLI. Polls relies on this to send notification emails periodically.

This issue can be closed. Even though Polls is not to blame, a note in the documentation is recommended to make admin life a bit easier.

**Comment by nickvergessen** [comment]
Does using `linkToRouteAbsolute` instead of the nested functions solve it?

**Comment by nickvergessen** [comment]
Well `overwrite.cli.url` is set automatically when it was not set before by Nextcloud to the first trusted domain on install or update. It has documentation available but since it's set automatically we don't need to show a warning

**Comment by kesselb** [comment]
> https://github.com/nextcloud/polls/blob/b17ebbdfbb232d0e1253830886416b2fba80eb62/lib/Service/MailService.php#L263-L267

Looks good to me. You could simplify the code a bit by using `linkToRouteAbsolute` . For the cron `overwrite.cli.url` is required.

**Comment by Zepmann** [comment]
> Well `overwrite.cli.url` is set automatically when it was not set before by Nextcloud to the first trusted domain on install or update. It has documentation available but since it's set automatically we don't need to show a warning

It can be set automatically to something the admin does not expect. Many Nextcloud installations are first installed internally before they are exposed externally, and the significance of `overwrite.cli.url` might not be known.

And I never wrote that you had to show a warning. Please do not put words in my mouth.

**Comment by dartcafe** [comment]
> Why was my previous reply marked as off-topic? It confirmed that the issue is still valid and was not solved due to other changes in newer releases.

@Zepmann I marked it off topic, because there is no need to confirm that an issue is not solved, when it is still open. No one said, that this issue was solved, so it does not help in the sense of solving an issue.

**Comment by Zepmann** [comment]
> I marked it off topic, because there is no need to confirm that an issue is not solved, when it is still open.

That is not off topic, since it relates to the described problem. You could have picked [a better reason](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/managing-disruptive-comments) or even better, not hid it at all.

Furthermore, this issue was last noted in April. Since half a year passed, it might be nice to know that the issue was not unintentionally/unknowingly solved in the mean time. Your behavior discourages cooperation.

**Comment by kesselb** [comment]
> You could have picked a better reason or even better, not hid it at all.

> Your behavior discourages collaboration.

Not cool. A lot of people do open source in their free time. Managing all those bug requests and developing new features is a time consuming process. 

If the maintainer thinks a comment is not relevant for a discussion this is something for you to accept. You are free to not use the app. 

@dartcafe some people take a hidden comment very serious. I made the experience that resolved as reason works better than off topic. 

Keep the good work up 👍

**Comment by nickvergessen** [comment]
The issue is solved and the rest should not be discussed here as there might be a lot of people subscribed, so I'm locking this issue to prevent further comments.
