### ISSUE TITLE
GUI issue adding a poll on the iPad

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#892]
### What is going wrong?
There is a GUI issue on the iPad in Safari when you want to create a new poll, the buttons are overlapping the selector. See screenshot below.

![IMG_1071](https://user-images.githubusercontent.com/3321655/78994653-e6e34980-7b40-11ea-9460-8370d0b24ac2.jpeg)

Poll version 1.3.0 on Nextcloud 18.0.3

**Comment by dartcafe** [comment]
Duplicate of #770 and fixed in next version (actually in current beta).

**Comment by jacotec** [comment]
@dartcafe That does not work for me in the current beta. It's still the same, see my comment in #770
