### ISSUE TITLE
Beta 1.4.1 - invitation email partly German and English

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#899]
### What is going wrong?
The standard language of my Nextcloud is set to German, the invitation emails for a new poll is sent in German in the first half and English in the second half:

![image](https://user-images.githubusercontent.com/3321655/79048758-9a227000-7c1f-11ea-9d2e-a0ee1455eeba.png)

**Comment by dartcafe** [comment]
I need the language setting of the poll owner and the recipient of this invitation.

**Comment by dartcafe** [comment]
Ah, I guess you are using the current beta, right? The original string was changed (#894). So it is not yet translated via transifex and it falls back to the original (english) string. It takes a few days, to get translated and sent back to the repo.

**Comment by jacotec** [comment]
@dartcafe Thank you for your feedback ... did not want to make noise, but just wanted to help ironing out issues before this great update goes live 😊

**Comment by dartcafe** [comment]
Don't worry, we need every feedback. Thanks for supporting us.
