### ISSUE TITLE
allow to invite all members of a contact group

### ISSUE THREAD

**Issue by martinbu** [nextcloud/polls#902]
At the moment it is possible to invite

1. users
2. user groups
3. and contacts

to a poll. If I choose a contact, an email is sent to the contact's email address with a personalized poll link. This is great!

But what is missing is the possibility to invite all members of a contact group. If a contact group is invited, each member should get an email with a personalized poll link.

**Comment by mevers-hb** [comment]
We use your app for elections in our working groups.

The automatic notification would be very helpful for a prompt response from colleagues.

Therefore, automatic notification when sharing with groups would be very important to us.

A quick fix would be great.

**Comment by CATER-COM** [comment]
+1

**Comment by dartcafe** [comment]
I implemented invitation for contacts groups. But it works alittle bit different. You can select a contact group as a share. 
After adding the contact group, it can be resolved to individual shares for every group member. 
![grafik](https://user-images.githubusercontent.com/26707476/90061650-b70ea300-dce6-11ea-8ae1-aecc2e261bbb.png)
![grafik](https://user-images.githubusercontent.com/26707476/90061906-1967a380-dce7-11ea-96d7-283ba9e8d827.png)
