### ISSUE TITLE
Translation errors de 

### ISSUE THREAD

**Issue by prochance** [nextcloud/polls#903]
### What is going wrong?

Hello,

When a new survey is created, access is provided under Details:

Verborgen für Ander Nutzer   // In German WRONG
Hidden for other users           //In English

...but it must be right:
Verborgen für Andere Nutzer     // In German correct            

The e with others was forgotten. I have adapted it to my own but it is not taken over in the view. Can anyone tell me what I am doing wrong?

**Screenshots**
https://www.bilder-upload.eu/bild-6fc118-1586945716.jpg.html

### Information about your polls installation
**Polls version?** (1.3.0)

**Fresh installation Yes

**How did you install this version?(Appstore Nextcloud)**

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud version: ( Nextcloud 18.0.3)
```

**Browser:** All Browsers

**Comment by prochance** [comment]
For me, I fixed the bug. Please adjust the file for DE (du) in the next update. Thanks a lot

**Comment by dartcafe** [comment]
Already fixed in transifex and in the next version.
