### ISSUE TITLE
Renaming of Poll Types 

### ISSUE THREAD

**Issue by janklostermann** [nextcloud/polls#906]
**Problem:**
As newbee to polls I was confused about the "Poll Type" choice directly after starting the creation of a new poll: I did not understand that "Poll schedule" was a date poll. It got me more in the direction of scheduling a poll...
After a while of not getting where I wanted with the "Poll schedule", I gave up and tried "text based", which provided what I wanted from the beginning. And then I understood, what the whole thing with the date picker was about...

**Describe the solution you'd like**
My proposal to name them more consistent and therefore better understandable (at least for me ;-) ):
* "Schedule poll" or "Date poll"
* Free text poll

**Describe alternatives you've considered**
Now I know, at least, if the next usage is not too far ahead...

**Comment by dartcafe** [comment]
That was a bug and will be solved in version 1.4

![grafik](https://user-images.githubusercontent.com/26707476/79699025-f6733880-828c-11ea-8a37-eb16a55aace9.png)
