### ISSUE TITLE
Auto-updating of poll results page as participants send in their choices

### ISSUE THREAD

**Issue by janklostermann** [nextcloud/polls#907]
**Problem**
Looking at the poll results I was not sure if was I saw, was the real current status of the poll or not (meaning: no-one answered yet). Only after reloading the page again and again in the browser (also to avoid any browser caching effects), I trusted the results I saw showed the current state of the poll.

**Describe the solution you'd like**
Best would be a push mechanism that would update the page as soon as the participants send in their votes. 
This would have the nice side-effect that you could enjoy the show of people voting and the numbers for the various options rising (especially helpful in (online) workshops where everyone is interested in the results and the results page is shared via screensharing).

**Describe alternatives you've considered**
A maybe easier to implement alternative would be an explicit "Update" button (e.g. in the upper left corner of the results table) that would actively call the reloading of the (now) current result set.

**Comment by dartcafe** [comment]
An update button is identically to a reload. Push will need the implementation websockets. Nothing, what is planned in the near future. Currently we have a pull mechanism, which reloads the polls list every 30 seconds. Maybe we can add the current poll to this. 

But we have to check possible side effects.
