### ISSUE TITLE
shares to contacts can't enter poll (does not exist error)

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#908]
@dartcafe  a long time I didn't get to the app it's a mature App , really great job :)

But il seem that the link shared by mail doesn't work. The link bring user to a page message "Polls doesn't exist". It seem that it create a spécific public link (nice because I suppose this case the user don't need to register, it use the adressbook name). But the link created isn't linked to the poll.

If the bug below is solved, do you think it could be possible to use not only nextcloud user group, but also contact app group. This way you can send your poll to a large group of contact without chekin each one by one in the dropdown list. Search box is looking in the group field but it doesn't provide a way to click on group name to select the whole contacts tha belong to it. This part is duplicate of this #902 

Thanks for all of this job !

_Originally posted by @CATER-COM in https://github.com/nextcloud/polls/issues/388#issuecomment-615394494_

**Comment by dartcafe** [comment]
@CATER-COM
It's always better to create a new issue, if you think, there is a bug. Actually this was a bug. I fixed it directly in the master branch. 

@v1r0x iy you did not build untin now, please make a fresh pull from master with this fix.

**Comment by dartcafe** [comment]
The fix can be tested with the new beta: https://github.com/nextcloud/polls/releases/tag/1.4.2

**Comment by CATER-COM** [comment]
Tested this morning it's ok :)

**Comment by dartcafe** [comment]
Will be closed, when PR is merged.
