### ISSUE TITLE
slow ldap user search 

### ISSUE THREAD

**Issue by jamoedv** [nextcloud/polls#912]
Hello, 

when searching Users to invite, it takes very long to find a user. (up to 10 min) 
The user search in the file sharing app works very fast. Any tip on what I could check ? We are connected to a AD with several thousand users.. but as I said only in the polls invitation it is very slow. 

thank you.

**Comment by dartcafe** [comment]
Interesting. I'd say 9 min are acceptable. But 10? 😁 
To be serious. Seems, we have to refactor the sharing functions. maybe related to #881 or at least should be considered together. 

@scroom, @herrmannsdorfer, @BurtGummer, @phimeas, @PpaiSanchez 
As you seem to use (or did use) polls with LDAP: Do you recognize similar behavior?

**Comment by herrmannsdorfer** [comment]
No problems here (NC 18.0.4, polls 1.4.2). AD search delivers results within milliseconds. But our AD has < 1.000 usr. And NC usr subset is preselected by LDAP filter in settings.

Considering a large userbase on AD I would ask @blizzz for advice. He is working on LDAP optimizations eg nextcloud/server#19919.

**Comment by blizzz** [comment]
I don't know what the Polls app is doing there, but it suppose it is also just calling  the user manager. Hopefully not to fetch all users at once. That would be indeed something to improve here. Someone else shall shed more light there.

If this is all proper, then slow user search is a setup/config issue and rather to be followd up on in the forums, or with a subscription.

**Comment by jamoedv** [comment]
thanks for the feedback. we are using ldap filter in the ldap
configuration.
In the File App everything is working fine so I was wondering there might
be an issue with the poll app itself. If i try to invite users the search
iterates through all users until it finds the right one. During this search
it also tries to load and display the users foto. I cannot see this
behaviour when sharing files to others. Are there any settings which I
could check ?

I will also open a ticket with the subscription support.


Am Do., 23. Apr. 2020 um 17:26 Uhr schrieb blizzz <notifications@github.com

**Comment by blizzz** [comment]
> If i try to invite users the search
iterates through all users until it finds the right one. During this search
it also tries to load and display the users foto.

Ah… yes. This does not scale with many users of course. Someone would need to adjust the polls app to do it differently.

**Comment by dartcafe** [comment]
> Hopefully not to fetch all users at once.

I think, that this maybe an issue. As I said, the search needs an overwork.

**Comment by dartcafe** [comment]
@jamoedv I want to get in this issue now and need some information. 

> During this search it also tries to load and display the users foto.

Polls does not try to load fotos from the users, but from the contacts. Can you verify this?
Did you connect the contacts app to the LDAP or have a big amount of contacts?

Polls does three searches 
* groups -> via groupManager
* users -> via userManager
* contacts -> via contactsManager

and it tries to identify, if  a email address is entered.

**Comment by dartcafe** [comment]
When getting contacts, the systemaddressbook is skipped and only user's address books should be scanned. Maybe the LDAP is also delivered via the contactsManager and scanned. I removed the scanning of the photo from the vcard.

**Comment by dartcafe** [comment]
I hope, that helps. I cannot test this because I have no LDAP running.
