### ISSUE TITLE
Admin users should always be able to delete a poll

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#924]
**Is your feature request related to a problem? Please describe.**
Users can select "Allow administrators to edit this poll" (as opt-in).

If this isn't selected administrators cannot modify **and** cannot delete the poll. (e.g. if the poll violates terms and conditions or is inadequate for other reasons).

Users also create polls and forget about them. As an admin there should always be the possibilty to clean up (without the need to manipulate the database).

**Describe the solution you'd like**
- Administrator users should always be able to **delete** a poll
- Regardless of the proposed solution, the above setting should better be opt-out, instead of opt-in?
- or rephrased as "disallow admin users to edit the poll" and changed in behavior.

**Additional context**
![Screenshot_2020-05-10 Umfragen - Testumfrage](https://user-images.githubusercontent.com/29312856/81501464-ce4d8700-92d8-11ea-82b2-9a0cec5203b0.png)

**Comment by dirdi** [comment]
I completely agree with the proposal. As a workaround that does not require one to manipulate the database, one can leverage the [impersonate app](https://apps.nextcloud.com/apps/impersonate) to delete a poll of another user.
