### ISSUE TITLE
Anonymous poll is misleading, as it is only partially anonymous

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#925]
**Is your feature request related to a problem? Please describe.**
If the option anonymous poll is selected, the creator of the poll still sees all participants' names and their votes. The info text shown to voters is misleading, as it says "... because this is an anonymous poll".

**Describe the solution you'd like**
- Change the option's name to something like "hide participants' names from each other"
- Show a tip to all users stating that the poll creator can still see the participants' names.

**Additional context**
Polls 1.4.3, Nextcloud 18.0.4

**Screenshot**
![Screenshot_2020-05-10 Umfragen - Testumfrage(1)](https://user-images.githubusercontent.com/29312856/81502686-a0b80c00-92df-11ea-9ae4-e08bc35682fa.png)

**Comment by dartcafe** [comment]
We can change the text parts to make this more understandable.

**Comment by dartcafe** [comment]
resolved with extending poll information.
