### ISSUE TITLE
Option names overlap, hard to read

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/polls#927]
When using text options, the options overlap and make it hard/impossible to read. Note also that the first option is cut off at the left:
![Bildschirmfoto vom 2020-05-11 19-44-46](https://user-images.githubusercontent.com/28591861/81593563-efd56e00-93bf-11ea-9841-511a44203757.png)

Nextcloud 18.0.2
Polls  1.4.3

Tell me if you need more info.

Too bad, I just wanted to use Polls for the first time, aaaaand nope, can't use it =(

**Comment by dartcafe** [comment]
Hyphens are missing. A workaround could be to use the table view, there is more space for the text.

**Comment by dartcafe** [comment]
Hyphens are working, but still no effect with chrome and some other browsers: 
https://caniuse.com/#feat=css-hyphens
And there is some strange behavior depending of the used language:
https://stackoverflow.com/questions/28976543/css-hyphens-not-working-in-firefox

Maybe, we should default to the table layout in text polls.

**Comment by dartcafe** [comment]
Avoiding with switch to list layout.

**Comment by alexanderdd** [comment]
I think we should keep this open!?

**Comment by dartcafe** [comment]
Why should we keep an outdated and four years ago closed issue open?

**Comment by alexanderdd** [comment]
@dartcafe in 2020 you closed this issue, suggesting a workaround, which to me is not enough to close an issue, an actual fix is needed (or a "wontfix" decision).

I just checked, and this bug is indeed fixed in NC  29.0.3 

So it can stay closed

sorry for the misunderstanding
