### ISSUE TITLE
Send a poll to predefined list of emailadresses

### ISSUE THREAD

**Issue by bitbonk** [nextcloud/polls#928]
**Is your feature request related to a problem? Please describe.**
We frequently use nextcloud polls to to send a poll to a large number of recipents from an external mailing list that do not and should not have an account in our nextcloud instance. Right now we have to enter all emailadresses by hand each time we want to send a poll to all members of a specific mailing list. 

**Describe the solution you'd like**
Allow us to maintain a list of mailing lists that we can select once as the recipient and each emailadress in that list will get a mail with a unique link tied to that emailadress. It would also be extremely helpful if those emailadresses could be imported from a plain text file or from the clipboard.

**Describe alternatives you've considered**
We could make a regular nextCloud user for each emailadress in those mailing lists. But that is even more tedious to maintain (they need to have passwords and names and group memberships and storage quota etc.) and it would mean they could login and actually use our nectcould instance.

The other alternative to use a public link is not possible because people could vote multiple times or under fake "identities". 

**Additional context**
Nextcould is used in a school context. Mailing lists include things like "all parents", "all parents from 2019 classes", "all staff", "all teachers" etc.

**Comment by dartcafe** [comment]
Seems to be related to #902
