### ISSUE TITLE
Exclusive answers

### ISSUE THREAD

**Issue by topiux** [nextcloud/polls#933]
**Is your feature request related to a problem? Please describe.**
Options are "yes" and "no". Currently both options can be selected which is a contradiction.

**Describe the solution you'd like**
Only one option can be chosen.

**Describe alternatives you've considered**
Add an "exclusive" poll type.

![image](https://user-images.githubusercontent.com/2096159/82741555-52fcc400-9d21-11ea-88dc-9c3d61ae55ff.png)

**Comment by dartcafe** [comment]
see #936 #738
