### ISSUE TITLE
Invited users are sent emails without prompt

### ISSUE THREAD

**Issue by 3rownz** [nextcloud/polls#935]
**Describe the bug**
The is issue realted to the interface design based on the option to add invitations to users. It is not very intuitive, and can lead to miss sending emails (considering all contacts and users are listed here, this could be anyone). The selection of a user should not instantly send a email.

**To Reproduce**
1. Go to share tab
2. Click on enter name to start search
3. Scroll down and select chosen user
4. Email is sent without warning

**Expected behavior**
The user should have a clear indication of submition before the permanent action of sending an email. A possible solution would be to add a user to the list, but not send or allow access untill a submit button to the bottom of the user list is clicked. This would involve having a invited and pending list and adding the pending to invited on submittion.

**Comment by dartcafe** [comment]
This is a to do. For that we added - as a workaroud - a notice, which describes this behavior.
![grafik](https://user-images.githubusercontent.com/26707476/82752248-f949d780-9dbc-11ea-8bcf-4fb81c99ce90.png)

**Comment by amadeous** [comment]
**Proposal of another expected behavior**
It might be that the user/group selected in the search bar could be added to an access list without sending an invitation email and already have rights on the poll and an email could be sent using an email button/icon on the access list?

**Comment by kainhofer** [comment]
We have the same issue. I was preparing a vote for our management board, which is allowed by a new resolution passed by the parliamant, so we needed to follow quite strict rules. As the situation is quite complex, the invitation to vote needed to be sent out by an email containing a discussion of the legal background and detailed instructions and the link to the vote. As we sent a dedicated invitatiton email including the link to the poll, we did not want ANY automatic notification sent out. Unfortunately, I can't seem to find a way to disable the notification altogether (for a single poll or globally).

**Comment by chaosgrid** [comment]
+1

I don't understand why so many Nextcloud Apps send out mass-emails by default. Every email action should always have a prompt.
Also, the current polls app is bugged for installations with LDAP groups that have users which never logged in. Since they do not have a corresponding nextcloud user mapping, getting the email of those accounts fails and on inviting those users, the app reports an error.

**Comment by dartcafe** [comment]
I agree. Sending invitation mail in polls is not transparent and may surprize the users. 

What I have in my mind is to queue invitations (visually) and ask the user to release them manually (or all pending invitations). I hope, that this gives the wanted control to the poll owner.

**Comment by dartcafe** [comment]
see description in #1007

**Comment by dartcafe** [comment]
Invitations get spooled without automatic sending.

![grafik](https://user-images.githubusercontent.com/26707476/86567340-8448f080-bf6b-11ea-97de-554a9df4c3c4.png)
