### ISSUE TITLE
Enforce a user to select single option

### ISSUE THREAD

**Issue by 3rownz** [nextcloud/polls#936]
**Is your feature request related to a problem? Please describe.**
There is no way to enforce a user from selecting just one option. 

**Describe the solution you'd like**
An option in the poll configuration to enforce only one option. When voting and a option is selected all other options are deselected. 

**Additional context**
These seems important for simple poll, I cannot use the poll system without this, is the option there and I cant find it?

**Comment by dartcafe** [comment]
see #933 #738
