### ISSUE TITLE
Change prompt for name in public polls

### ISSUE THREAD

**Issue by xuwey** [nextcloud/polls#938]
### What is going wrong?
**Describe the bug**
When I create a poll and share it with a public link (E-Mail), users are allways prompted to login, instead of using it without that: "Gib deinen Namen ein!" (Enter your name!)

**To Reproduce**

**Expected behavior**
I expect, that using the public sharing link makes it possible to have a free access to the poll.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/65945688/82879922-f0344400-9f3d-11ea-96b3-394b45768146.png)

### Information about your polls installation
**Polls version?** (see apps page)
It's not my installation, it's on a platform called EduDocs.de. Polls version is 1.4.3

**Comment by dartcafe** [comment]
I think you are mislead because of the term username (Benutzername). The prompt want's to get a name from the user and is no login.

We could change the promt to "Tell us who you are (at least three characters)".

**Comment by xuwey** [comment]
Yes, that's it. I tried and it works. It's so easy, but I didn't understand
it.
But I like your suggestion (We could change the promt to "Tell us who you
are (at least three characters)".) and I would prefer it.
Many thanks!

Am Di., 26. Mai 2020 um 14:59 Uhr schrieb René Gieling <
notifications@github.com>:

**Comment by xuwey** [comment]
Yes, that's it, it works. I didn't understand it.
But I like your suggestion!

**Comment by toehold** [comment]
Hi,

when using AD authentication in the public polls, I can enter a name, but it Checking username ....
forever! Clicking OK doesn't work! Pressing Cancel show the poll, but you can't make any changes do it.

**Comment by dartcafe** [comment]
@toehold Guessing, same reason as in #912

**Comment by dartcafe** [comment]
@xuwey 
current implementation
![grafik](https://user-images.githubusercontent.com/26707476/84399511-3dccd400-ac01-11ea-8f77-8377591ab5ec.png)

**Comment by xuwey** [comment]
Hello, my name is Uwe, and you can see it in xuwey ;-)
Okay?

Am Do., 11. Juni 2020 um 16:33 Uhr schrieb René Gieling <
notifications@github.com>:
