### ISSUE TITLE
User belonging to multiple groups invited to the same poll should not get multiple invitation emails

### ISSUE THREAD

**Issue by amadeous** [nextcloud/polls#947]
### What is going wrong?
Hi!
First I would like to express my gratitude for this Nextcloud app and the amazing work the whole team and its community are doing. Thank you! 

**Describe the bug**
When you select groups to sent invitation to it will automatically send an email to every user in the group even if the user was already invited (individually or because they belong to a previously invited group). This behavior has been noticed with a test poll, might be the same for every poll type.

**To Reproduce**
1. Ensure you have a test user (might be yourself) that belongs to 2 (or more) groups.
2. Create a (text) poll
3. Invite the aforementioned groups that include the test user
4. The test user should have received multiple invitation emails for the same poll

**Expected behavior**
If a user already got an invitation for a poll because he belongs to a group, it should not get another one for the same poll (invited individually or because belonging to another invited group).

### Information about your polls installation
**Polls version?**
Version 1.4.3

**Fresh installation or update from a prior version (from which one)?**
Fresh installation

**How did you install this version?**
Through the Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.4

**Are you using an external user-backend, if yes which one:**
None

**Comment by dartcafe** [comment]
not:
* avoid duplicates on creating shares
* link to #912

**Comment by dartcafe** [comment]
Unfortunately it is not possible to tell, if a user already already was invited by a group invitation or not. So this is not resolvable.
At least we added the group name to the invitation mail.
