### ISSUE TITLE
Option to limit how often a shared linked could be opened or downloaded

### ISSUE THREAD

**Issue by MarcelMpunkt** [nextcloud/polls#951]
**What is the problem?**
If you share something via link, you can protect the link by password or expiration date. But often you only want to share something so that somebody else can view or download it _one or several times_. You don´t know exactly when somebody is using the link. But that it has to be opened at least once to fullfil its purpose.

**What could be the solution?**
In the sharing-context-menu there should be an option like: 
- "Set Limit"
  - "Download Limit"
  - "View Limit"

**Are there alternative solutions?**

none

**Additional context**
You could set a limit how often something could be viewed, before it is unavailable. It could also be useful if you want to give away something like an ebook. If you set a download limit of 500 copies, it could only be downloaded 500 times before it is unavailabe. 

![sharing-context-menu](https://user-images.githubusercontent.com/18383682/83555954-640eb780-a50f-11ea-8881-43c903e86e1a.JPG)

**Comment by v1r0x** [comment]
This is the repo for the polls app. You should open your issue in the server repo.
