### ISSUE TITLE
Remove 1,2,3,4 etc minute options and replace with 0,5,10,15 etc

### ISSUE THREAD

**Issue by darkesthour111** [nextcloud/polls#957]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As a general UX improvement we should be able to adjust the time options to 5 minute increments. 99% of meetings/gatherings etc do not start on non divisible by 5 times.

**Describe alternatives you've considered**
None, should be a relatively simple UI enhancement.

**Additional context**
None.

**Comment by dartcafe** [comment]
Could be a nice discussion. This stands in contrast to #826 from @mylaeus

**Comment by mylaeus** [comment]
5 minutes increments is fine for me. That would be more userfriendly

**Comment by dartcafe** [comment]
I second that. Minute steps are indeed annoying.
