### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/polls#965]
**Is your feature request related to a problem? Please describe.**
French version of the app is very faulty, I'd like to enhance it (I am a french teacher). Please tell me how to do that !
Grettings and thanks for all the job !

**Comment by dartcafe** [comment]
Add an account at transifex.com and join the nextcloud team as a french translator. For more information @rakekniven can help for sure.

**Comment by rakekniven** [comment]
See https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550 as well. Closing here.
