### ISSUE TITLE
Add timezone administration section.

### ISSUE THREAD

**Issue by arkhej** [nextcloud/polls#977]
**Is your feature request related to a problem? Please describe.**
I'm creating a Pool, some team members are living in Spain and other in Central America. The
datetime pool change the options depending on where you are.

**Describe the solution you'd like**
I'd like have a configuration section to set and force the timezone to avoid errors about hours format.

**Comment by dartcafe** [comment]
I am not sure, if I get you right. You want to present every participant the same time string independent of the participant's time zone? I would expect the time beeing presented in my time zone.
