### ISSUE TITLE
Send confirmation email to participants

### ISSUE THREAD

**Issue by Ali-romdhani** [nextcloud/polls#978]
First of all, very nice app ! Works great for our voluntary organization (more than 500 peoples).

**Is your feature request related to a problem? Please describe.**
You create a poll, invite users, but cant notify them of the result, or send a confirmation email with other details (ex. the place of the meeting).

**Describe the solution you'd like**
A way to send a email to all participant of the poll from the nextcloud app

**Describe alternatives you've considered**
Other alternative are painful : search through all users to select their email and send with your own email address. If the creator of the poll is not admin, he must ask one to get the email he needs to organize the meeting.

**Additional context**
We are a large voluntary based organization that need every member to be as autonomous as possible. A way for poll creator to send email to participants is essential.

**Comment by dartcafe** [comment]
The notification system needs an overwork first. We will think about a workaround, when the poll confirmation is out (planned for 1.5). But we have no schedule for the notifications.

Another temporary workaround could be copying the email adresses of all participants to the clipboard for further use.

**Comment by Ali-romdhani** [comment]
> Another temporary workaround could be copying the email adresses of all participants to the clipboard for further use.

You mean a button will be add to allow user to copy all participants emails ? That could be great 👍
