### ISSUE TITLE
Missing error notice

### ISSUE THREAD

**Issue by FDVCZ** [nextcloud/polls#979]
**Problem:** Missing error notice when user is registered, but not a member of group with polls enabled

**Expected behavior:** In case registered user get a link to the poll and logs in AND does not belong to the group which is allowed to use polls (see settings in app store), an error notice should appear "You do not have access to polls. Please contact your administrator." 

_System info: NextCloud 18.0.4; Polls v1.4.3_

**Comment by dartcafe** [comment]
Nothing we can do in the app, because the app is not loaded in this case.

**Comment by FDVCZ** [comment]
> Nothing we can do in the app, because the app is not loaded in this case.

It is nice you closed it so quickly, but this is still an ongoing issue directly related to the Polls app, so don't you think this should be somehow fixed (if not within this app then on another level 
 - nextcloud "core" / server)?

**Comment by dartcafe** [comment]
This is not polls related. As i said, the access is prevented by the core, so we can't do anything here in this repo. Feel free to open an issue in the server repo.
