### ISSUE TITLE
Additional features: Resource usage?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/polls#98]
Probably not really a focus of this tool, but it seems similar enough to maybe be added:

Multi-user resource poll, so for example a room, or projector or car etc. Were every user can submit their wish schedule similar to the the current event setup, and then it is easy to settle on a common schedule that respects most of the wishes.

The resource poll creator can than validate a final schedule and that could be exported to .ical or so for integration with the Own/Nextcloud calendar system?

Of course that would need some sort of addition to show to whom the resource is allocated during a certain time.

**Comment by v1r0x** [comment]
I like the idea, but I'm not sure how easy it really is to implement it.
I think it is easy to implement the front-end, but I don't know how easy it is to compute the schedule. There are several parameters you have to consider. Maybe short timespans are preferred over longer ones or if one user already has a slot for one of the resources they are not prioritized for another resource or later timeslot.

Do you have any experience or ideas what could be a good method how to deal with the parameters?

**Comment by poVoq** [comment]
I don't think there is a need to automatically calculate a schedule. Specific preferences  for length etc. can be mentioned in the comments.

But I agree, even a manual validation is also slightly difficult to set up. If the time is ok, maybe there could be just a small check-mark for the poll-creator to validate it (i.e. move a schedule item from tentatively to confirmed), but schedule conflict resolution is probably difficult. Not sure how a proposed schedule could for example easily moved to an hour, day etc. later/earlier?

**Comment by v1r0x** [comment]
I added it to the backlog milestone, since this is definitely a cool feature, but not that important and most of all I _currently_ don't have a good idea how to implement it 😉

**Comment by dartcafe** [comment]
This is a function and primary for colaboration. I would like to see it in the calender app, but this is heavy work, if you think about the administration of the resources. I would focus this app on polls and not on scheduling dates or events. 

Suggestion: close the poll.

**Comment by dartcafe** [comment]
Closing this issue, because this is a feature for planning appointments, but not for a poll. Anyway this is very complicated and heavy weight for this app.
