### ISSUE TITLE
Additional preference setting?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/polls#99]
Right now you can cycle through Red, green and yellow (unavailable, available & unsure) for finding events, but maybe there could be a fourth setting like "main preference" or "priority"?

**Comment by v1r0x** [comment]
The idea of yellow as color was not unsure exactly, but more "if there is no other option this one is ok, but it is not my preferred option". So, in my interpretation they would be red = nope, yellow = ok, but not my favorite, green = this on is ok.
But I think there are several different interpretations. Thus I think it would be good to (re-)add some icons for better visualization and another color.

Any ideas for icons or new color?

**Comment by poVoq** [comment]
Blue could be for priority/preference? Icon could be just a simple "!" or a "P"? but the latter doesn't translate well to other languages.

**Comment by v1r0x** [comment]
Sorry for the long break. I thought about this feature and decided to keep the current solution. All major polls apps (at least the ones I know 😉 ) have 2 or 3 different vote types. But I'll keep this issue open so other people with the same request can add a comment or 👍 on the OP.

**Comment by dartcafe** [comment]
I would close this issue for tidying.

**Comment by dartcafe** [comment]
Keeping issues for disussion is no good idea IMHO. We should keep the issues clean.
