### ISSUE TITLE
allow pure date polls without a time

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/polls#991]
### Is your feature request related to a problem? Please describe.
every now and then we need to find at least a date but don't know/need the exact time (yet).

### Describe the solution you'd like
an option to check, that no time is asked and shown.

**edit:** thinking a little bit further: perhaps this option also just per item would be interesting for some people...
- but that would make it necessary to add this option to the date/time-picker, otherwise it would be no pleasant UX (if you have to check the box for no time beforehand choosing the date).
- on the other hand adding a checkbox to "hide" the time for every chosen option would be a solution to change it afterwards... but this seems also a little bit clunky to me.

...so i'm not sure about a per item solution. :thinking: 

### Describe alternatives you've considered
- adding the time when it **probably** will take place, leads to a ton of discussions... :see_no_evil: 
  if it is clear, that the exact time is to be discussed/announced, some participants with *maybe* answers leave a comment when/why it is possible or not and that's it.
- also using 00:00 as time, raises sometimes confusions or even questions. :frowning:

**Comment by dartcafe** [comment]
similar to #919. Also see this comment https://github.com/nextcloud/polls/issues/919#issuecomment-625792052

Maybe with #492 this can be solved
