### ISSUE TITLE
graded votings

### ISSUE THREAD

**Issue by albertleidinger** [nextcloud/polls#994]
Hi,

I'm member of a Tenant Advisory Board an we're using nextCloud in many ways. Doing polls within nextCloud is great!

But for difficult decisions we prefer graded votings and it would be great to have a solution within nextCloud too.

To do this, it would be necessary to query 3-10 levels of approval or rejection for each option. 

More information on this technique can be found under the keywords "systemic consensus/systemisches Konsensieren" or "positive consensus/positives Konsensieren". (https://www.youtube.com/watch?v=A5As9tcy2dU)

Hope you like it and maybe there's support for this in a future version.

thanks

**Comment by dartcafe** [comment]
Duplicate of #513?

**Comment by albertleidinger** [comment]
Hi, you're right. That would do the trick.
