### ISSUE TITLE
Time is not displayed correctly

### ISSUE THREAD

**Issue by Tealk** [nextcloud/polls#995]
### What is going wrong?
**Describe the bug**
The location settings of me and a colleague are the same, but we will be shown different times for the survey

**To Reproduce**
I have created a survey
the days entered with time
and invited someone

**Screenshots**
Me:
![image](https://user-images.githubusercontent.com/12276250/85954730-01bba200-b969-11ea-8da3-e2d59f650377.png)
Colleague:
![image](https://user-images.githubusercontent.com/12276250/85954742-18fa8f80-b969-11ea-8941-16d38bb360d8.png)

### Information about your polls installation
1.4.3

**Fresh installation or update from a prior version (from which one)?**
i have updated Nextcloud several times, poll i installed the first time with v20

**How did you install this version?(Appstore or describe installation)**
Appstore

## Server configuration detail

**Operating system:** Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64

**Webserver:** nginx/1.14.2 (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 7.4.7

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, memcache, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 19.0.0 - 19.0.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - apporder: 0.10.0
 - calendar: 2.0.3
 - circles: 0.19.2
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.4
 - documentserver_community: 0.1.7
 - drop_account: 0.2.1
 - event_update_notification: 1.0.2
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_downloadactivity: 1.8.0
 - files_linkeditor: 1.1.1
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - flowupload: 1.0.0
 - forms: 1.1.1
 - groupfolders: 6.0.6
 - guests: 1.4.6
 - imageconverter: 1.2.1
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 4.3.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quota_warning: 1.8.0
 - ransomware_protection: 1.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - side_menu: 1.7.0
 - socialsharing_email: 2.0.0
 - spreed: 9.0.1
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 4.1.3
 - twofactor_u2f: 5.1.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0
Disabled:
 - encryption
 - files_external
 - files_lock
 - firstrunwizard
 - issuetemplate
 - recommendations
 - registration
 - text
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "anzah.cloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/anzah.cloud",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "19.0.0.12",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "default_locale": "de",
    "default_language": "de",
    "allow_user_to_change_display_name": true,
    "knowledgebaseenabled": false,
    "theme": "",
    "skeletondirectory": "\/var\/customers\/webs\/Anzah\/anzah.cloud\/core\/skeleton\/neu",
    "trashbin_retention_obligation": "120, auto",
    "versions_retention_obligation": "120, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.release.channel": "stable",
    "check_for_working_webdav": true,
    "logdateformat": "d.m.Y H:i:s",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 104857600,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "data-fingerprint": "01b9630d063ba580c331de332a0ab360",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 10,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "app_install_overwrite": [
        "twofactor_yubikey",
        "tasks",
        "documents",
        "socialsharing_email",
        "issuetemplate"
    ]
}
```
</details>

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database
 * OCA\Guests\UserBackend

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by dartcafe** [comment]
Please check the timezone settings in the browsers.

**Comment by dartcafe** [comment]
@Tealk To be more precise: The timezone is normaly set on your computer. Times are presented in the clients timezone. I guess you and your college have different timezones configured.

**Comment by Tealk** [comment]
Hello @dartcafe and thanks for your answer.
Where exactly does he get this information?

![image](https://user-images.githubusercontent.com/12276250/85980579-36177880-b9d2-11ea-9e90-f2e65b696c00.png)
It won't refer to the programming language? Because the website language is set to German.

**Comment by dartcafe** [comment]
My first answer was misleading. The localisation defines the language. The timezone is set in the os settings.

**Comment by Tealk** [comment]
But this is set correctly, because I see the correct time in my OS.
How is that fetched?

**Comment by Tealk** [comment]
So it must have something to do with the browser, because when I test it in Vivaldi, for example, the time is displayed correctly.

### Add-on's:
uBlock, uMatrix, True Sight, Privacy Redirect, LocalCDN, CSS Exfil Protection, ClearURLs

user.js:
https://www.privacy-handbuch.de/download/streng/user.js

**Comment by dartcafe** [comment]
I have no Idea. You can check your settings here: http://browserspy.dk/date.php

**Comment by Tealk** [comment]
Unfortunately, I can't find the error. With this domain I unfortunately also get a GMT+0000 instead of a GMT+0200

**Comment by dartcafe** [comment]
Sorry, I have no idea, what's going wrong. Try using a clean profile, disable addons one by on, other procedures for analyzing the error.

**Comment by Tealk** [comment]
So even with a new profile I have the same result, so he has to take the language of the browser as reference.

Couldn't you add an option to use the selection of the user in the user profile?

**Comment by dartcafe** [comment]
Which selection? The timezone is taken from the browser's information. In NC is no setting for the timezone.

**Comment by Tealk** [comment]
> Which selection?

This setting I mean, I assume it sets the time. Otherwise, the time display below doesn't make any sense.
![image](https://user-images.githubusercontent.com/12276250/86243577-26e12800-bb96-11ea-9b24-cd061b46bb46.png)

**Comment by dartcafe** [comment]
This setting is for the time format display. This has nothing to do with the timezone.

**Comment by dartcafe** [comment]
Maybe this could be a hint: https://support.mozilla.org/bm/questions/1247616
I guess some privacy setting for avoiding fingerprinting has probably changed the setting in about:config.

**Comment by Tealk** [comment]
Now I have found out where the problem comes from:
https://github.com/ghacksuserjs/ghacks-user.js/issues/965

**Comment by dartcafe** [comment]
Great. Hope, I could help. Will close this.

**Comment by hamoid** [comment]
Do you remember what was the problem @Tealk ? The linked issue 965 has been deleted.

**Comment by hamoid** [comment]
I think I found it: `privacy.resistFingerprinting` in Firefox' `about:config'

**Comment by Tealk** [comment]
So fast I could not react xD
