### ISSUE TITLE
the sender address is always the email of the admin

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/polls#996]
When one of our Nextcloud users creates a poll, the sender address is always the email of the admin and not that of the account user. Is this setting correct? It confuses many?

We use Nextcloud Version 18.0.6
Poll App is the latest Version

**Comment by dartcafe** [comment]
That's correct. NC sends mails via the configured mail system.

**Comment by osm-frasch** [comment]
Thanks for the quick answer I understand. 
Is there no other technical solution or is one being considered? It always 
makes the employees a bit confused, because they think that the voting is done 
via their mail address.

Cheers
-------------------------
Frank

**Comment by dartcafe** [comment]
Unfortunately not, because there is no user dependent SMTP configuration for the used .
