### ISSUE TITLE
Cannot change my entry

### ISSUE THREAD

**Issue by Hk1020** [nextcloud/polls#998]
### What is going wrong?
**Describe the bug**
I cannot modify my entry after I sent the response. I receive _This username is not valid, i.e., because it is already in use._

**To Reproduce**
1. Create a public poll.
1. Check _Allow admins to edit this poll_
1. Check _Visible to other users_
1. Check _Always show results_
1. Add a date option
1. Add a public link
1. Use public link to participate without being a nextcloud user
1. Use public link again and enter the user name used in the previous step.

**Expected behavior**
Be able to modify data entered before.

**Screenshots**
![image](https://user-images.githubusercontent.com/1018004/86498317-a5e88300-bd85-11ea-92d2-6c9b06adbc25.png)

### Information about your polls installation
**Polls version?** 1.4.3

**Fresh installation or update from a prior version (from which one)?** Update from 1.3.0

**How did you install this version?(Appstore or describe installation)** Standard installion via Apps in nextcloud

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud**

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.6

**Comment by dartcafe** [comment]
After entering your name in a public link, a personal link which is different from the public link is created and presented in the header of the poll for reentering. Chosing an already in the poll used name results in the error you posted.

![grafik](https://user-images.githubusercontent.com/26707476/86538593-2da1cf00-bef7-11ea-8f56-cd0378c1132f.png)

Maybe you will find it in the browser history.

**Comment by Hk1020** [comment]
Thanks for you reply. I don't think this is very useful, though. No one will notice this link (I didn't) nor will they store this information somewhere. What should participants do? Like if they made their entry on a PC and then want to continue on a phone?

**Comment by dartcafe** [comment]
I think it is very useful judging from the responses to this feature. We take it the lean way. First the feature is developed and maybe inconvenient. Convenience follows. 

This will be solved when an email can be entered. So the link will be sent to this address. 
Workaround: Copy the link and send to myself via email. Anyway, the owner can send you the link too.

**Comment by Hk1020** [comment]
Having the link emailed is certainly an improvement. But usability is still low. I'd like to see this to be configurable by the poll creator. I think doodle does it right. Just enter your name again and you'll be overwriting your old response. Sure, it can be misused but if you have to deal with such people use this new version with additional links.

**Comment by dartcafe** [comment]
Using a voter's name to change his votes in a public poll is a no go IMHO. Configuration rises the complexity for a limited value. We had some discussions about this in serveral issues. 

In a group poll in doodle, I am able to edit every entry and add users with the same name of any already existing participants.

**Comment by Hk1020** [comment]
> 
> 
> Using a voter's name to change his votes in a public poll is a no go IMHO. Configuration rises the complexity for a limited value. We had some discussions about this in serveral issues.
> 
> In a group poll in doodle, I am able to edit every entry and add users with the same name of any already existing participants.

So it is. Depends on the intended audience. Fits my use case perfectly. Anything else is way too complicated for the users.

**Comment by dartcafe** [comment]
Based on the discussions we had, we decided to imlplement it in the current way. Sorry to say, but doodle seems to be the better alternative for you. Think I can close this issue.

**Comment by Hk1020** [comment]
You are right, doodle fits my use case much better. Except for the tiny bit that it doesn't run on my server. Isn't that why nextcloud was created? Then it should be easy to use, also for non-technical people.

**Comment by dartcafe** [comment]
>  Isn't that why nextcloud was created?

I think so, but I dont see if this is a reason to let anybody edit other peoples' votes, like doodle oviously allows it. Using a personal link which is usable without any further login is quite common in other apps and usecases (i.e. filesharing apps) even for non technical users. 

It respects privacy and protects against manipulation, if you keep the secret confidential.

BTW: This are two of the issues, which led to the current implementation #223, #406

**Comment by Hk1020** [comment]
Good you mention #406. Seems pretty much the same argument. I am not against your scheme, it certainly has its justification. But it is too cumbersome in a lot of situations. I'd therefore really want a doodle-like simple interface as an option. It should be for the pool creator to decide if that is secure enough.

Mailing the link as you suggest at another place is certainly a must. Without it poll creator intervention is required if the personal link is lost. But it requires the voters to supply email addresses which they might not want to do, And switching devices like from PC to mobile is still not a simple task - you need access to your mail on both devices.

**Comment by MartenBE** [comment]
@dartcafe I also have the same use case by using this as a public doodle among friends. I really like the link solution, but it should be displayed much more prominently (like above the poll: "Please save this link if you want to change your vote later. As you do not have an account you will not be able to change your vote without this link! <link>"). Even I as admin only stumbled on this functionality by reading this issue, so I certainly can't expect my non technical friends to figure out that they have to right click their entry and copy the link for later use.

**Comment by MartenBE** [comment]
As I keep getting problems and questions with non-technical persons used to the "edit all" possibilities of doodle, I have decided to drop Nextcloud Polls after months of trying and started self-hosting https://rallly.co/ . This seems to be a good alternative and offers this functionality (see the demo). It seems to be more intuitive for my clients.

**Comment by dartcafe** [comment]
@MartenBE Happy you found another solution for your users. But I would say, we improved the situation with emailing the links on request and saving the last user to a local cookie, to support reentering the poll.

**Comment by MartenBE** [comment]
I recently tested it again with both non- and technical people: most only realized it works with a link after they clicked away. A lot of them also clear cookies automatically on browser close. So it resulted again in an avalanche of "hey, could you edit or delete my entry" e-mails and it is just a mess. Thank you for your work, but it isn't fit for my use case as most users I come in contact with are not used to this workflow (used to doodle etc.) and it just creates a lot of extra work and hassle. As I see a lot of similar cases above, I thought I'd offer an alternative to their case as well as it is designated as a `wontfix` here.
